#Code converted on 2023-08-09 10:48:10
import os
import argparse
from pyspark.sql import *
from pyspark.sql.functions import *
from pyspark.sql.window import Window
from pyspark.sql.types import *
from datetime import datetime
from Datalake.utils.genericUtilities import *
from Datalake.utils.configs import *
from Datalake.utils.mergeUtils import *
from Datalake.utils.logger import *
# COMMAND ----------

parser = argparse.ArgumentParser()
spark = SparkSession.getActiveSession()
parser.add_argument('env', type=str, help='Env Variable')
args = parser.parse_args()
env = args.env
# env = 'dev'

if env is None or env == '':
    raise ValueError('env is not set')

refine = getEnvPrefix(env) + 'refine'
raw = getEnvPrefix(env) + 'raw'
legacy = getEnvPrefix(env) + 'legacy'

# Set global variables
starttime = datetime.now() #start timestamp of the script


# COMMAND ----------
# Processing node SQ_Shortcut_to_TRAINING_SCHED_CHANGE_CAPTURE, type SOURCE 
# COLUMN COUNT: 9

SQ_Shortcut_to_TRAINING_SCHED_CHANGE_CAPTURE = spark.sql(f"""SELECT
TRAINING_SCHED_CHANGE_ID,
TRAINING_SCHED_CHANGE_TYPE_ID,
TRAINING_SCHED_ENTITY_ID,
TRAINING_SCHED_ENTITY_TYPE_ID,
STORE_NBR,
TRAINING_SCHED_CHANGE_STATE_ID,
CHANGE_USER,
CHANGE_TSTMP,
LOAD_TSTMP
FROM {legacy}.TRAINING_SCHED_CHANGE_CAPTURE""").withColumn("sys_row_id", monotonically_increasing_id())

# COMMAND ----------
# Processing node SQ_Shortcut_to_TRAINING_SCHED_CHANGE_CAPTURE_PRE, type SOURCE 
# COLUMN COUNT: 8

SQ_Shortcut_to_TRAINING_SCHED_CHANGE_CAPTURE_PRE = spark.sql(f"""SELECT
CHANGE_ID,
CHANGE_TYPE_ID,
ENTITY_ID,
ENTITY_TYPE_ID,
STORE_NUMBER,
CHANGE_USER,
CHANGE_DATE_TIME,
CHANGE_STATE_ID
FROM {raw}.TRAINING_SCHED_CHANGE_CAPTURE_PRE""").withColumn("sys_row_id", monotonically_increasing_id())

# COMMAND ----------
# Processing node JNR_TRAINING_SCHED_CHANGE_CAPTURE, type JOINER . Note: using additional SELECT to rename incoming columns
# COLUMN COUNT: 17

# for each involved DataFrame, append the dataframe name to each column
SQ_Shortcut_to_TRAINING_SCHED_CHANGE_CAPTURE_temp = SQ_Shortcut_to_TRAINING_SCHED_CHANGE_CAPTURE.toDF(*["SQ_Shortcut_to_TRAINING_SCHED_CHANGE_CAPTURE___" + col for col in SQ_Shortcut_to_TRAINING_SCHED_CHANGE_CAPTURE.columns])
SQ_Shortcut_to_TRAINING_SCHED_CHANGE_CAPTURE_PRE_temp = SQ_Shortcut_to_TRAINING_SCHED_CHANGE_CAPTURE_PRE.toDF(*["SQ_Shortcut_to_TRAINING_SCHED_CHANGE_CAPTURE_PRE___" + col for col in SQ_Shortcut_to_TRAINING_SCHED_CHANGE_CAPTURE_PRE.columns])

JNR_TRAINING_SCHED_CHANGE_CAPTURE = SQ_Shortcut_to_TRAINING_SCHED_CHANGE_CAPTURE_temp.join(SQ_Shortcut_to_TRAINING_SCHED_CHANGE_CAPTURE_PRE_temp,[SQ_Shortcut_to_TRAINING_SCHED_CHANGE_CAPTURE_temp.SQ_Shortcut_to_TRAINING_SCHED_CHANGE_CAPTURE___TRAINING_SCHED_CHANGE_ID == SQ_Shortcut_to_TRAINING_SCHED_CHANGE_CAPTURE_PRE_temp.SQ_Shortcut_to_TRAINING_SCHED_CHANGE_CAPTURE_PRE___CHANGE_ID],'right_outer').selectExpr( \
	"SQ_Shortcut_to_TRAINING_SCHED_CHANGE_CAPTURE_PRE___CHANGE_ID as CHANGE_ID", \
	"SQ_Shortcut_to_TRAINING_SCHED_CHANGE_CAPTURE_PRE___CHANGE_TYPE_ID as CHANGE_TYPE_ID", \
	"SQ_Shortcut_to_TRAINING_SCHED_CHANGE_CAPTURE_PRE___ENTITY_ID as ENTITY_ID", \
	"SQ_Shortcut_to_TRAINING_SCHED_CHANGE_CAPTURE_PRE___ENTITY_TYPE_ID as ENTITY_TYPE_ID", \
	"SQ_Shortcut_to_TRAINING_SCHED_CHANGE_CAPTURE_PRE___STORE_NUMBER as STORE_NUMBER", \
	"SQ_Shortcut_to_TRAINING_SCHED_CHANGE_CAPTURE_PRE___CHANGE_USER as CHANGE_USER", \
	"SQ_Shortcut_to_TRAINING_SCHED_CHANGE_CAPTURE_PRE___CHANGE_DATE_TIME as CHANGE_DATE_TIME", \
	"SQ_Shortcut_to_TRAINING_SCHED_CHANGE_CAPTURE_PRE___CHANGE_STATE_ID as CHANGE_STATE_ID", \
	"SQ_Shortcut_to_TRAINING_SCHED_CHANGE_CAPTURE___TRAINING_SCHED_CHANGE_ID as lkp_TRAINING_SCHED_CHANGE_ID", \
	"SQ_Shortcut_to_TRAINING_SCHED_CHANGE_CAPTURE___TRAINING_SCHED_CHANGE_TYPE_ID as lkp_TRAINING_SCHED_CHANGE_TYPE_ID", \
	"SQ_Shortcut_to_TRAINING_SCHED_CHANGE_CAPTURE___TRAINING_SCHED_ENTITY_ID as lkp_TRAINING_SCHED_ENTITY_ID", \
	"SQ_Shortcut_to_TRAINING_SCHED_CHANGE_CAPTURE___TRAINING_SCHED_ENTITY_TYPE_ID as lkp_TRAINING_SCHED_ENTITY_TYPE_ID", \
	"SQ_Shortcut_to_TRAINING_SCHED_CHANGE_CAPTURE___STORE_NBR as lkp_STORE_NBR", \
	"SQ_Shortcut_to_TRAINING_SCHED_CHANGE_CAPTURE___TRAINING_SCHED_CHANGE_STATE_ID as lkp_TRAINING_SCHED_CHANGE_STATE_ID", \
	"SQ_Shortcut_to_TRAINING_SCHED_CHANGE_CAPTURE___CHANGE_USER as lkp_CHANGE_USER1", \
	"SQ_Shortcut_to_TRAINING_SCHED_CHANGE_CAPTURE___CHANGE_TSTMP as lkp_CHANGE_TSTMP", \
	"SQ_Shortcut_to_TRAINING_SCHED_CHANGE_CAPTURE___LOAD_TSTMP as lkp_LOAD_TSTMP")

# COMMAND ----------
# Processing node FIL_UNCHANGED_RECORDS, type FILTER 
# COLUMN COUNT: 17

# for each involved DataFrame, append the dataframe name to each column
JNR_TRAINING_SCHED_CHANGE_CAPTURE_temp = JNR_TRAINING_SCHED_CHANGE_CAPTURE.toDF(*["JNR_TRAINING_SCHED_CHANGE_CAPTURE___" + col for col in JNR_TRAINING_SCHED_CHANGE_CAPTURE.columns])

FIL_UNCHANGED_RECORDS = JNR_TRAINING_SCHED_CHANGE_CAPTURE_temp.selectExpr( \
	"JNR_TRAINING_SCHED_CHANGE_CAPTURE___CHANGE_ID as CHANGE_ID", \
	"JNR_TRAINING_SCHED_CHANGE_CAPTURE___CHANGE_TYPE_ID as CHANGE_TYPE_ID", \
	"JNR_TRAINING_SCHED_CHANGE_CAPTURE___ENTITY_ID as ENTITY_ID", \
	"JNR_TRAINING_SCHED_CHANGE_CAPTURE___ENTITY_TYPE_ID as ENTITY_TYPE_ID", \
	"JNR_TRAINING_SCHED_CHANGE_CAPTURE___STORE_NUMBER as STORE_NUMBER", \
	"JNR_TRAINING_SCHED_CHANGE_CAPTURE___CHANGE_USER as CHANGE_USER", \
	"JNR_TRAINING_SCHED_CHANGE_CAPTURE___CHANGE_DATE_TIME as CHANGE_DATE_TIME", \
	"JNR_TRAINING_SCHED_CHANGE_CAPTURE___CHANGE_STATE_ID as CHANGE_STATE_ID", \
	"JNR_TRAINING_SCHED_CHANGE_CAPTURE___lkp_TRAINING_SCHED_CHANGE_ID as lkp_TRAINING_SCHED_CHANGE_ID", \
	"JNR_TRAINING_SCHED_CHANGE_CAPTURE___lkp_TRAINING_SCHED_CHANGE_TYPE_ID as lkp_TRAINING_SCHED_CHANGE_TYPE_ID", \
	"JNR_TRAINING_SCHED_CHANGE_CAPTURE___lkp_TRAINING_SCHED_ENTITY_ID as lkp_TRAINING_SCHED_ENTITY_ID", \
	"JNR_TRAINING_SCHED_CHANGE_CAPTURE___lkp_TRAINING_SCHED_ENTITY_TYPE_ID as lkp_TRAINING_SCHED_ENTITY_TYPE_ID", \
	"JNR_TRAINING_SCHED_CHANGE_CAPTURE___lkp_STORE_NBR as lkp_STORE_NBR", \
	"JNR_TRAINING_SCHED_CHANGE_CAPTURE___lkp_TRAINING_SCHED_CHANGE_STATE_ID as lkp_TRAINING_SCHED_CHANGE_STATE_ID", \
	"JNR_TRAINING_SCHED_CHANGE_CAPTURE___lkp_CHANGE_USER1 as lkp_CHANGE_USER1", \
	"JNR_TRAINING_SCHED_CHANGE_CAPTURE___lkp_CHANGE_TSTMP as lkp_CHANGE_TSTMP", \
	"JNR_TRAINING_SCHED_CHANGE_CAPTURE___lkp_LOAD_TSTMP as lkp_LOAD_TSTMP").filter("lkp_TRAINING_SCHED_CHANGE_ID IS NULL OR ( lkp_TRAINING_SCHED_CHANGE_ID IS NOT NULL AND ( IF (CHANGE_TYPE_ID IS NULL, cast(99 as int), CHANGE_TYPE_ID) != IF (lkp_TRAINING_SCHED_CHANGE_TYPE_ID IS NULL, cast(99 as int), lkp_TRAINING_SCHED_CHANGE_TYPE_ID) OR IF (ENTITY_ID IS NULL, cast(99 as int), ENTITY_ID) != IF (lkp_TRAINING_SCHED_ENTITY_ID IS NULL, cast(99 as int), lkp_TRAINING_SCHED_ENTITY_ID) OR IF (ENTITY_TYPE_ID IS NULL, cast(99 as int), ENTITY_TYPE_ID) != IF (lkp_TRAINING_SCHED_ENTITY_TYPE_ID IS NULL, cast(99 as int), lkp_TRAINING_SCHED_ENTITY_TYPE_ID) OR IF (STORE_NUMBER IS NULL, cast(99 as int), STORE_NUMBER) != IF (lkp_STORE_NBR IS NULL, cast(99 as int), lkp_STORE_NBR) OR IF (CHANGE_STATE_ID IS NULL, cast(99 as int), CHANGE_STATE_ID) != IF (lkp_TRAINING_SCHED_CHANGE_STATE_ID IS NULL, cast(99 as int), lkp_TRAINING_SCHED_CHANGE_STATE_ID) OR IF (LTRIM ( RTRIM ( CHANGE_USER ) ) IS NULL, ' ', LTRIM ( RTRIM ( CHANGE_USER ) )) != IF (LTRIM ( RTRIM ( lkp_CHANGE_USER1 ) ) IS NULL, ' ', LTRIM ( RTRIM ( lkp_CHANGE_USER1 ) )) OR IF (CHANGE_DATE_TIME IS NULL, To_DATE ( '12-31-9999' , 'MM-DD-YYYY' ), CHANGE_DATE_TIME) != IF (lkp_CHANGE_TSTMP IS NULL, To_DATE ( '12-31-9999' , 'MM-DD-YYYY' ), lkp_CHANGE_TSTMP) ) )").withColumn("sys_row_id", monotonically_increasing_id())

# COMMAND ----------
# Processing node EXP_UPDATE_VALIDATOR, type EXPRESSION 
# COLUMN COUNT: 11

# for each involved DataFrame, append the dataframe name to each column
FIL_UNCHANGED_RECORDS_temp = FIL_UNCHANGED_RECORDS.toDF(*["FIL_UNCHANGED_RECORDS___" + col for col in FIL_UNCHANGED_RECORDS.columns])

EXP_UPDATE_VALIDATOR = FIL_UNCHANGED_RECORDS_temp.selectExpr( \
	"FIL_UNCHANGED_RECORDS___sys_row_id as sys_row_id", \
	"FIL_UNCHANGED_RECORDS___CHANGE_ID as CHANGE_ID", \
	"FIL_UNCHANGED_RECORDS___CHANGE_TYPE_ID as CHANGE_TYPE_ID", \
	"FIL_UNCHANGED_RECORDS___ENTITY_ID as ENTITY_ID", \
	"FIL_UNCHANGED_RECORDS___ENTITY_TYPE_ID as ENTITY_TYPE_ID", \
	"FIL_UNCHANGED_RECORDS___STORE_NUMBER as STORE_NUMBER", \
	"FIL_UNCHANGED_RECORDS___CHANGE_USER as CHANGE_USER", \
	"FIL_UNCHANGED_RECORDS___CHANGE_DATE_TIME as CHANGE_DATE_TIME", \
	"FIL_UNCHANGED_RECORDS___CHANGE_STATE_ID as CHANGE_STATE_ID", \
	"CURRENT_TIMESTAMP as UPDATE_TSTMP", \
	"IF (FIL_UNCHANGED_RECORDS___lkp_LOAD_TSTMP IS NULL, CURRENT_TIMESTAMP, FIL_UNCHANGED_RECORDS___lkp_LOAD_TSTMP) as LOAD_TSTMP", \
	"IF (FIL_UNCHANGED_RECORDS___lkp_TRAINING_SCHED_CHANGE_ID IS NULL, 1, 2) as UPDATE_FLAG" \
)

# COMMAND ----------
# Processing node UPD_INSERT_UPDATE, type UPDATE_STRATEGY 
# COLUMN COUNT: 11

# for each involved DataFrame, append the dataframe name to each column
EXP_UPDATE_VALIDATOR_temp = EXP_UPDATE_VALIDATOR.toDF(*["EXP_UPDATE_VALIDATOR___" + col for col in EXP_UPDATE_VALIDATOR.columns])

UPD_INSERT_UPDATE = EXP_UPDATE_VALIDATOR_temp.selectExpr( \
	"EXP_UPDATE_VALIDATOR___CHANGE_ID as CHANGE_ID", \
	"EXP_UPDATE_VALIDATOR___CHANGE_TYPE_ID as CHANGE_TYPE_ID", \
	"EXP_UPDATE_VALIDATOR___ENTITY_ID as ENTITY_ID", \
	"EXP_UPDATE_VALIDATOR___ENTITY_TYPE_ID as ENTITY_TYPE_ID", \
	"EXP_UPDATE_VALIDATOR___STORE_NUMBER as STORE_NUMBER", \
	"EXP_UPDATE_VALIDATOR___CHANGE_USER as CHANGE_USER", \
	"EXP_UPDATE_VALIDATOR___CHANGE_DATE_TIME as CHANGE_DATE_TIME", \
	"EXP_UPDATE_VALIDATOR___CHANGE_STATE_ID as CHANGE_STATE_ID", \
	"EXP_UPDATE_VALIDATOR___UPDATE_TSTMP as UPDATE_TSTMP", \
	"EXP_UPDATE_VALIDATOR___LOAD_TSTMP as LOAD_TSTMP", \
	"EXP_UPDATE_VALIDATOR___UPDATE_FLAG as UPDATE_FLAG") \
	.withColumn('pyspark_data_action', when(col('UPDATE_FLAG') ==(lit(1)) , lit(0)) .when(col('UPDATE_FLAG') ==(lit(2)) , lit(1)))

# COMMAND ----------
# Processing node Shortcut_to_TRAINING_SCHED_CHANGE_CAPTURE1, type TARGET 
# COLUMN COUNT: 10


Shortcut_to_TRAINING_SCHED_CHANGE_CAPTURE1 = UPD_INSERT_UPDATE.selectExpr( \
	"CAST(CHANGE_ID AS INT) as TRAINING_SCHED_CHANGE_ID", \
	"CAST(CHANGE_TYPE_ID AS INT) as TRAINING_SCHED_CHANGE_TYPE_ID", \
	"CAST(ENTITY_ID AS INT) as TRAINING_SCHED_ENTITY_ID", \
	"CAST(ENTITY_TYPE_ID AS INT) as TRAINING_SCHED_ENTITY_TYPE_ID", \
	"CAST(STORE_NUMBER AS INT) as STORE_NBR", \
	"CAST(CHANGE_STATE_ID AS INT) as TRAINING_SCHED_CHANGE_STATE_ID", \
	"CAST(CHANGE_USER AS STRING) as CHANGE_USER", \
	"CAST(CHANGE_DATE_TIME AS TIMESTAMP) as CHANGE_TSTMP", \
	"CAST(UPDATE_TSTMP AS TIMESTAMP) as UPDATE_TSTMP", \
	"CAST(LOAD_TSTMP AS TIMESTAMP) as LOAD_TSTMP", \
	"pyspark_data_action as pyspark_data_action" \
)
# Shortcut_to_TRAINING_SCHED_CHANGE_CAPTURE1.write.saveAsTable(f'{raw}.TRAINING_SCHED_CHANGE_CAPTURE', mode = 'overwrite')
spark.sql("""set spark.sql.legacy.timeParserPolicy = LEGACY""")

try:
  primary_key = """source.TRAINING_SCHED_CHANGE_ID = target.TRAINING_SCHED_CHANGE_ID"""
  refined_perf_table = f"{legacy}.TRAINING_SCHED_CHANGE_CAPTURE"
  executeMerge(Shortcut_to_TRAINING_SCHED_CHANGE_CAPTURE1, refined_perf_table, primary_key)
  logger.info(f"Merge with {refined_perf_table} completed]")
  logPrevRunDt("TRAINING_SCHED_CHANGE_CAPTURE", "TRAINING_SCHED_CHANGE_CAPTURE", "Completed", "N/A", f"{raw}.log_run_details")
except Exception as e:
  logPrevRunDt("TRAINING_SCHED_CHANGE_CAPTURE", "TRAINING_SCHED_CHANGE_CAPTURE","Failed",str(e), f"{raw}.log_run_details", )
  raise e
	