
--*****  Creating table:  "WFA_BUSINESS_AREA" , ***** Creating table: "WFA_BUSINESS_AREA"
use legacy;

CREATE TABLE 
    WFA_BUSINESS_AREA(
        WFA_BUSN_AREA_ID BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY (START WITH 10000), 
        WFA_BUSN_AREA_DESC STRING, 
        UPDATE_DT TIMESTAMP, 
        LOAD_DT TIMESTAMP
        ) USING delta LOCATION 'gs://petm-bdpl-prod-nzlegacy-p1-gcs-gbl/labor_mgmt/wfa_business_area';
--DISTRIBUTE ON (WFA_BUSN_AREA_ID)


--*****  Creating table:  "WFA_DEPARTMENT" , ***** Creating table: "WFA_DEPARTMENT"
use legacy;

CREATE TABLE 
    WFA_DEPARTMENT (
        WFA_DEPT_ID BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY (START WITH 10000), 
        WFA_DEPT_DESC STRING, 
        UPDATE_DT TIMESTAMP, 
        LOAD_DT TIMESTAMP
        ) USING delta LOCATION 'gs://petm-bdpl-prod-nzlegacy-p1-gcs-gbl/labor_mgmt/wfa_department';
        

--*****  Creating table:  "WFA_TASK" , ***** Creating table: "WFA_TASK"
use legacy;

CREATE TABLE 
    WFA_TASK (
        WFA_TASK_ID BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY (START WITH 10000), 
        WFA_TASK_DESC STRING, 
        UPDATE_DT TIMESTAMP, 
        LOAD_DT TIMESTAMP
        ) USING delta LOCATION 'gs://petm-bdpl-prod-nzlegacy-p1-gcs-gbl/labor_mgmt/wfa_task';
--DISTRIBUTE ON (WFA_TASK_ID)

