# Databricks notebook source
# MAGIC %sql
# MAGIC
# MAGIC CREATE view legacy.EMPL_LABOR_WK_VW_VZ AS
# MAGIC (SELECT EMPL_LABOR_WK_PSOFT.WEEK_DT
# MAGIC 		,EMPL_LABOR_WK_PSOFT.LOCATION_ID
# MAGIC 		,EMPL_LABOR_WK_PSOFT.STORE_DEPT_NBR
# MAGIC 		,EMPL_LABOR_WK_PSOFT.EARN_ID
# MAGIC 		,EMPL_LABOR_WK_PSOFT.JOB_CODE
# MAGIC 		,EMPL_LABOR_WK_PSOFT.FULLPT_FLAG
# MAGIC 		,EMPL_LABOR_WK_PSOFT.HOURS_WORKED
# MAGIC 		,EMPL_LABOR_WK_PSOFT.EARNINGS_AMT
# MAGIC 		,EMPL_LABOR_WK_PSOFT.EARNINGS_LOC_AMT
# MAGIC 		,EMPL_LABOR_WK_PSOFT.CURRENCY_NBR
# MAGIC 		,EMPL_LABOR_WK_PSOFT.LOAD_TSTMP
# MAGIC    FROM legacy.EMPL_LABOR_WK_PSOFT)
# MAGIC UNION ALL
# MAGIC (SELECT EMPL_LABOR_WK.WEEK_DT
# MAGIC 		,EMPL_LABOR_WK.LOCATION_ID
# MAGIC 		,EMPL_LABOR_WK.STORE_DEPT_NBR
# MAGIC 		,EMPL_LABOR_WK.EARN_ID
# MAGIC 		,EMPL_LABOR_WK.JOB_CODE
# MAGIC 		,EMPL_LABOR_WK.FULLPT_FLAG
# MAGIC 		,EMPL_LABOR_WK.HOURS_WORKED
# MAGIC 		,EMPL_LABOR_WK.EARNINGS_AMT
# MAGIC 		,EMPL_LABOR_WK.EARNINGS_LOC_AMT
# MAGIC 		,EMPL_LABOR_WK.CURRENCY_NBR
# MAGIC 		,EMPL_LABOR_WK.LOAD_TSTMP
# MAGIC 	FROM legacy.EMPL_LABOR_WK);

# COMMAND ----------


