#Code converted on 2023-07-24 08:20:40
import os
import argparse
from pyspark.sql import *
from pyspark.sql.functions import *
from pyspark.sql.window import Window
from pyspark.sql.types import *
from datetime import datetime
from Datalake.utils.genericUtilities import *
from Datalake.utils.configs import *
from Datalake.utils.mergeUtils import *
from Datalake.utils.logger import *
# COMMAND ----------

parser = argparse.ArgumentParser()
spark = SparkSession.getActiveSession()
parser.add_argument('env', type=str, help='Env Variable')
args = parser.parse_args()
env = args.env

if env is None or env == '':
    raise ValueError('env is not set')

refine = getEnvPrefix(env) + 'refine'
raw = getEnvPrefix(env) + 'raw'
legacy = getEnvPrefix(env) + 'legacy'


# COMMAND ----------
# Processing node SQ_Shortcut_to_SDS_EMPLOYEE_GROUP_SERVICE_TYPES, type SOURCE 
# COLUMN COUNT: 5

SQ_Shortcut_to_SDS_EMPLOYEE_GROUP_SERVICE_TYPES = spark.sql(f"""SELECT
SDS_EMPLOYEE_GROUP_SERVICE_TYPES_ID,
SDS_SYSTEM_MODIFIED_TSTMP,
SDS_LAST_MODIFIED_TSTMP,
SDS_CREATED_TSTMP,
LOAD_TSTMP
FROM {legacy}.SDS_EMPLOYEE_GROUP_SERVICE_TYPES""").withColumn("sys_row_id", monotonically_increasing_id())

# COMMAND ----------
# Processing node SQ_Shortcut_to_SDS_PSVC_EMPLOYEE_GROUP_SERVICE_TYPES_C_PRE, type SOURCE 
# COLUMN COUNT: 16

SQ_Shortcut_to_SDS_PSVC_EMPLOYEE_GROUP_SERVICE_TYPES_C_PRE = spark.sql(f"""SELECT
ID,
IS_DELETED,
NAME,
CURRENCY_ISO_CODE,
CREATED_DATE,
CREATED_BY_ID,
LAST_MODIFIED_DATE,
LAST_MODIFIED_BY_ID,
SYSTEM_MOD_STAMP,
LAST_VIEWED_DATE,
LAST_REFERENCED_DATE,
PSVC_EMPLOYEE_GROUP_C,
PSVC_SERVICE_TYPE_C,
PSVC_AVAILABLE_ONLINE_C,
PSVC_COMMISSION_C,
PSVC_SERVICE_TYPE_GROUP_C
FROM {raw}.SDS_PSVC_EMPLOYEE_GROUP_SERVICE_TYPES_C_PRE""").withColumn("sys_row_id", monotonically_increasing_id())

# COMMAND ----------
# Processing node JNR_EMPLOYEE_GROUP_SERVICE_TYPES, type JOINER . Note: using additional SELECT to rename incoming columns
# COLUMN COUNT: 21

# for each involved DataFrame, append the dataframe name to each column
SQ_Shortcut_to_SDS_EMPLOYEE_GROUP_SERVICE_TYPES_temp = SQ_Shortcut_to_SDS_EMPLOYEE_GROUP_SERVICE_TYPES.toDF(*["SQ_Shortcut_to_SDS_EMPLOYEE_GROUP_SERVICE_TYPES___" + col for col in SQ_Shortcut_to_SDS_EMPLOYEE_GROUP_SERVICE_TYPES.columns])
SQ_Shortcut_to_SDS_PSVC_EMPLOYEE_GROUP_SERVICE_TYPES_C_PRE_temp = SQ_Shortcut_to_SDS_PSVC_EMPLOYEE_GROUP_SERVICE_TYPES_C_PRE.toDF(*["SQ_Shortcut_to_SDS_PSVC_EMPLOYEE_GROUP_SERVICE_TYPES_C_PRE___" + col for col in SQ_Shortcut_to_SDS_PSVC_EMPLOYEE_GROUP_SERVICE_TYPES_C_PRE.columns])

JNR_EMPLOYEE_GROUP_SERVICE_TYPES = SQ_Shortcut_to_SDS_PSVC_EMPLOYEE_GROUP_SERVICE_TYPES_C_PRE_temp.join(SQ_Shortcut_to_SDS_EMPLOYEE_GROUP_SERVICE_TYPES_temp,[SQ_Shortcut_to_SDS_PSVC_EMPLOYEE_GROUP_SERVICE_TYPES_C_PRE_temp.SQ_Shortcut_to_SDS_PSVC_EMPLOYEE_GROUP_SERVICE_TYPES_C_PRE___ID == SQ_Shortcut_to_SDS_EMPLOYEE_GROUP_SERVICE_TYPES_temp.SQ_Shortcut_to_SDS_EMPLOYEE_GROUP_SERVICE_TYPES___SDS_EMPLOYEE_GROUP_SERVICE_TYPES_ID],'left_outer').selectExpr(
	"SQ_Shortcut_to_SDS_EMPLOYEE_GROUP_SERVICE_TYPES___SDS_EMPLOYEE_GROUP_SERVICE_TYPES_ID as i_SDS_EMPLOYEE_GROUP_SERVICE_TYPES_ID",
	"SQ_Shortcut_to_SDS_EMPLOYEE_GROUP_SERVICE_TYPES___SDS_SYSTEM_MODIFIED_TSTMP as i_SDS_SYSTEM_MODIFIED_TSTMP",
	"SQ_Shortcut_to_SDS_EMPLOYEE_GROUP_SERVICE_TYPES___SDS_LAST_MODIFIED_TSTMP as i_SDS_LAST_MODIFIED_TSTMP",
	"SQ_Shortcut_to_SDS_EMPLOYEE_GROUP_SERVICE_TYPES___SDS_CREATED_TSTMP as i_SDS_CREATED_TSTMP",
	"SQ_Shortcut_to_SDS_EMPLOYEE_GROUP_SERVICE_TYPES___LOAD_TSTMP as i_LOAD_TSTMP",
	"SQ_Shortcut_to_SDS_PSVC_EMPLOYEE_GROUP_SERVICE_TYPES_C_PRE___ID as ID",
	"SQ_Shortcut_to_SDS_PSVC_EMPLOYEE_GROUP_SERVICE_TYPES_C_PRE___IS_DELETED as IS_DELETED",
	"SQ_Shortcut_to_SDS_PSVC_EMPLOYEE_GROUP_SERVICE_TYPES_C_PRE___NAME as NAME",
	"SQ_Shortcut_to_SDS_PSVC_EMPLOYEE_GROUP_SERVICE_TYPES_C_PRE___CURRENCY_ISO_CODE as CURRENCY_ISO_CODE",
	"SQ_Shortcut_to_SDS_PSVC_EMPLOYEE_GROUP_SERVICE_TYPES_C_PRE___CREATED_DATE as CREATED_DATE",
	"SQ_Shortcut_to_SDS_PSVC_EMPLOYEE_GROUP_SERVICE_TYPES_C_PRE___CREATED_BY_ID as CREATED_BY_ID",
	"SQ_Shortcut_to_SDS_PSVC_EMPLOYEE_GROUP_SERVICE_TYPES_C_PRE___LAST_MODIFIED_DATE as LAST_MODIFIED_DATE",
	"SQ_Shortcut_to_SDS_PSVC_EMPLOYEE_GROUP_SERVICE_TYPES_C_PRE___LAST_MODIFIED_BY_ID as LAST_MODIFIED_BY_ID",
	"SQ_Shortcut_to_SDS_PSVC_EMPLOYEE_GROUP_SERVICE_TYPES_C_PRE___SYSTEM_MOD_STAMP as SYSTEM_MOD_STAMP",
	"SQ_Shortcut_to_SDS_PSVC_EMPLOYEE_GROUP_SERVICE_TYPES_C_PRE___LAST_VIEWED_DATE as LAST_VIEWED_DATE",
	"SQ_Shortcut_to_SDS_PSVC_EMPLOYEE_GROUP_SERVICE_TYPES_C_PRE___LAST_REFERENCED_DATE as LAST_REFERENCED_DATE",
	"SQ_Shortcut_to_SDS_PSVC_EMPLOYEE_GROUP_SERVICE_TYPES_C_PRE___PSVC_EMPLOYEE_GROUP_C as PSVC_EMPLOYEE_GROUP_C",
	"SQ_Shortcut_to_SDS_PSVC_EMPLOYEE_GROUP_SERVICE_TYPES_C_PRE___PSVC_SERVICE_TYPE_C as PSVC_SERVICE_TYPE_C",
	"SQ_Shortcut_to_SDS_PSVC_EMPLOYEE_GROUP_SERVICE_TYPES_C_PRE___PSVC_AVAILABLE_ONLINE_C as PSVC_AVAILABLE_ONLINE_C",
	"SQ_Shortcut_to_SDS_PSVC_EMPLOYEE_GROUP_SERVICE_TYPES_C_PRE___PSVC_COMMISSION_C as PSVC_COMMISSION_C",
	"SQ_Shortcut_to_SDS_PSVC_EMPLOYEE_GROUP_SERVICE_TYPES_C_PRE___PSVC_SERVICE_TYPE_GROUP_C as PSVC_SERVICE_TYPE_GROUP_C")

# COMMAND ----------
# Processing node FIL_SDS_EMPLOYEE_GROUP_SERVICES_TYPE, type FILTER 
# COLUMN COUNT: 21

# for each involved DataFrame, append the dataframe name to each column
JNR_EMPLOYEE_GROUP_SERVICE_TYPES_temp = JNR_EMPLOYEE_GROUP_SERVICE_TYPES.toDF(*["JNR_EMPLOYEE_GROUP_SERVICE_TYPES___" + col for col in JNR_EMPLOYEE_GROUP_SERVICE_TYPES.columns])

FIL_SDS_EMPLOYEE_GROUP_SERVICES_TYPE = JNR_EMPLOYEE_GROUP_SERVICE_TYPES_temp.selectExpr(
	"JNR_EMPLOYEE_GROUP_SERVICE_TYPES___i_SDS_EMPLOYEE_GROUP_SERVICE_TYPES_ID as i_SDS_EMPLOYEE_GROUP_SERVICE_TYPES_ID",
	"JNR_EMPLOYEE_GROUP_SERVICE_TYPES___i_SDS_SYSTEM_MODIFIED_TSTMP as i_SDS_SYSTEM_MODIFIED_TSTMP",
	"JNR_EMPLOYEE_GROUP_SERVICE_TYPES___i_SDS_LAST_MODIFIED_TSTMP as i_SDS_LAST_MODIFIED_TSTMP",
	"JNR_EMPLOYEE_GROUP_SERVICE_TYPES___i_SDS_CREATED_TSTMP as i_SDS_CREATED_TSTMP",
	"JNR_EMPLOYEE_GROUP_SERVICE_TYPES___i_LOAD_TSTMP as i_LOAD_TSTMP",
	"JNR_EMPLOYEE_GROUP_SERVICE_TYPES___ID as ID",
	"JNR_EMPLOYEE_GROUP_SERVICE_TYPES___IS_DELETED as IS_DELETED",
	"JNR_EMPLOYEE_GROUP_SERVICE_TYPES___NAME as NAME",
	"JNR_EMPLOYEE_GROUP_SERVICE_TYPES___CURRENCY_ISO_CODE as CURRENCY_ISO_CODE",
	"JNR_EMPLOYEE_GROUP_SERVICE_TYPES___CREATED_DATE as CREATED_DATE",
	"JNR_EMPLOYEE_GROUP_SERVICE_TYPES___CREATED_BY_ID as CREATED_BY_ID",
	"JNR_EMPLOYEE_GROUP_SERVICE_TYPES___LAST_MODIFIED_DATE as LAST_MODIFIED_DATE",
	"JNR_EMPLOYEE_GROUP_SERVICE_TYPES___LAST_MODIFIED_BY_ID as LAST_MODIFIED_BY_ID",
	"JNR_EMPLOYEE_GROUP_SERVICE_TYPES___SYSTEM_MOD_STAMP as SYSTEM_MOD_STAMP",
	"JNR_EMPLOYEE_GROUP_SERVICE_TYPES___LAST_VIEWED_DATE as LAST_VIEWED_DATE",
	"JNR_EMPLOYEE_GROUP_SERVICE_TYPES___LAST_REFERENCED_DATE as LAST_REFERENCED_DATE",
	"JNR_EMPLOYEE_GROUP_SERVICE_TYPES___PSVC_EMPLOYEE_GROUP_C as PSVC_EMPLOYEE_GROUP_C",
	"JNR_EMPLOYEE_GROUP_SERVICE_TYPES___PSVC_SERVICE_TYPE_C as PSVC_SERVICE_TYPE_C",
	"JNR_EMPLOYEE_GROUP_SERVICE_TYPES___PSVC_AVAILABLE_ONLINE_C as PSVC_AVAILABLE_ONLINE_C",
	"JNR_EMPLOYEE_GROUP_SERVICE_TYPES___PSVC_COMMISSION_C as PSVC_COMMISSION_C",
	"JNR_EMPLOYEE_GROUP_SERVICE_TYPES___PSVC_SERVICE_TYPE_GROUP_C as PSVC_SERVICE_TYPE_GROUP_C").filter("i_SDS_EMPLOYEE_GROUP_SERVICE_TYPES_ID IS NULL OR ( i_SDS_EMPLOYEE_GROUP_SERVICE_TYPES_ID IS NOT NULL AND ( i_SDS_SYSTEM_MODIFIED_TSTMP != SYSTEM_MOD_STAMP OR i_SDS_CREATED_TSTMP != CREATED_DATE OR i_SDS_LAST_MODIFIED_TSTMP != LAST_MODIFIED_DATE ) )").withColumn("sys_row_id", monotonically_increasing_id())

# COMMAND ----------
# Processing node EXP_EMPLOYEE_GROUP_SERVICESS_TYPES, type EXPRESSION 
# COLUMN COUNT: 19

# for each involved DataFrame, append the dataframe name to each column
FIL_SDS_EMPLOYEE_GROUP_SERVICES_TYPE_temp = FIL_SDS_EMPLOYEE_GROUP_SERVICES_TYPE.toDF(*["FIL_SDS_EMPLOYEE_GROUP_SERVICES_TYPE___" + col for col in FIL_SDS_EMPLOYEE_GROUP_SERVICES_TYPE.columns])

EXP_EMPLOYEE_GROUP_SERVICESS_TYPES = FIL_SDS_EMPLOYEE_GROUP_SERVICES_TYPE_temp.selectExpr(
	"FIL_SDS_EMPLOYEE_GROUP_SERVICES_TYPE___sys_row_id as sys_row_id",
	"FIL_SDS_EMPLOYEE_GROUP_SERVICES_TYPE___ID as ID",
	"FIL_SDS_EMPLOYEE_GROUP_SERVICES_TYPE___IS_DELETED as IS_DELETED",
	"FIL_SDS_EMPLOYEE_GROUP_SERVICES_TYPE___NAME as NAME",
	"FIL_SDS_EMPLOYEE_GROUP_SERVICES_TYPE___CURRENCY_ISO_CODE as CURRENCY_ISO_CODE",
	"FIL_SDS_EMPLOYEE_GROUP_SERVICES_TYPE___CREATED_DATE as CREATED_DATE",
	"FIL_SDS_EMPLOYEE_GROUP_SERVICES_TYPE___CREATED_BY_ID as CREATED_BY_ID",
	"FIL_SDS_EMPLOYEE_GROUP_SERVICES_TYPE___LAST_MODIFIED_DATE as LAST_MODIFIED_DATE",
	"FIL_SDS_EMPLOYEE_GROUP_SERVICES_TYPE___LAST_MODIFIED_BY_ID as LAST_MODIFIED_BY_ID",
	"FIL_SDS_EMPLOYEE_GROUP_SERVICES_TYPE___SYSTEM_MOD_STAMP as SYSTEM_MOD_STAMP",
	"FIL_SDS_EMPLOYEE_GROUP_SERVICES_TYPE___LAST_VIEWED_DATE as LAST_VIEWED_DATE",
	"FIL_SDS_EMPLOYEE_GROUP_SERVICES_TYPE___LAST_REFERENCED_DATE as LAST_REFERENCED_DATE",
	"FIL_SDS_EMPLOYEE_GROUP_SERVICES_TYPE___PSVC_EMPLOYEE_GROUP_C as PSVC_EMPLOYEE_GROUP_C",
	"FIL_SDS_EMPLOYEE_GROUP_SERVICES_TYPE___PSVC_SERVICE_TYPE_C as PSVC_SERVICE_TYPE_C",
	"FIL_SDS_EMPLOYEE_GROUP_SERVICES_TYPE___PSVC_AVAILABLE_ONLINE_C as PSVC_AVAILABLE_ONLINE_C",
	"FIL_SDS_EMPLOYEE_GROUP_SERVICES_TYPE___PSVC_COMMISSION_C as PSVC_COMMISSION_C",
	"FIL_SDS_EMPLOYEE_GROUP_SERVICES_TYPE___PSVC_SERVICE_TYPE_GROUP_C as PSVC_SERVICE_TYPE_GROUP_C",
	"CURRENT_TIMESTAMP as UPDATE_TSTMP",
	"IF (FIL_SDS_EMPLOYEE_GROUP_SERVICES_TYPE___i_LOAD_TSTMP IS NULL, CURRENT_TIMESTAMP, FIL_SDS_EMPLOYEE_GROUP_SERVICES_TYPE___i_LOAD_TSTMP) as LOAD_TSTMP",
	"IF (FIL_SDS_EMPLOYEE_GROUP_SERVICES_TYPE___i_SDS_EMPLOYEE_GROUP_SERVICE_TYPES_ID IS NULL, 1, 2) as o_UPDATE_VALIDATOR"
)

# COMMAND ----------
# Processing node UPD_EMPLOYEE_GROUP_SERVICES_TYPES, type UPDATE_STRATEGY 
# COLUMN COUNT: 19

# for each involved DataFrame, append the dataframe name to each column
EXP_EMPLOYEE_GROUP_SERVICESS_TYPES_temp = EXP_EMPLOYEE_GROUP_SERVICESS_TYPES.toDF(*["EXP_EMPLOYEE_GROUP_SERVICESS_TYPES___" + col for col in EXP_EMPLOYEE_GROUP_SERVICESS_TYPES.columns])

UPD_EMPLOYEE_GROUP_SERVICES_TYPES = EXP_EMPLOYEE_GROUP_SERVICESS_TYPES_temp.selectExpr(
	"EXP_EMPLOYEE_GROUP_SERVICESS_TYPES___ID as ID",
	"EXP_EMPLOYEE_GROUP_SERVICESS_TYPES___IS_DELETED as IS_DELETED",
	"EXP_EMPLOYEE_GROUP_SERVICESS_TYPES___NAME as NAME",
	"EXP_EMPLOYEE_GROUP_SERVICESS_TYPES___CURRENCY_ISO_CODE as CURRENCY_ISO_CODE",
	"EXP_EMPLOYEE_GROUP_SERVICESS_TYPES___CREATED_DATE as CREATED_DATE",
	"EXP_EMPLOYEE_GROUP_SERVICESS_TYPES___CREATED_BY_ID as CREATED_BY_ID",
	"EXP_EMPLOYEE_GROUP_SERVICESS_TYPES___LAST_MODIFIED_DATE as LAST_MODIFIED_DATE",
	"EXP_EMPLOYEE_GROUP_SERVICESS_TYPES___LAST_MODIFIED_BY_ID as LAST_MODIFIED_BY_ID",
	"EXP_EMPLOYEE_GROUP_SERVICESS_TYPES___SYSTEM_MOD_STAMP as SYSTEM_MOD_STAMP",
	"EXP_EMPLOYEE_GROUP_SERVICESS_TYPES___LAST_VIEWED_DATE as LAST_VIEWED_DATE",
	"EXP_EMPLOYEE_GROUP_SERVICESS_TYPES___LAST_REFERENCED_DATE as LAST_REFERENCED_DATE",
	"EXP_EMPLOYEE_GROUP_SERVICESS_TYPES___PSVC_EMPLOYEE_GROUP_C as PSVC_EMPLOYEE_GROUP_C",
	"EXP_EMPLOYEE_GROUP_SERVICESS_TYPES___PSVC_SERVICE_TYPE_C as PSVC_SERVICE_TYPE_C",
	"EXP_EMPLOYEE_GROUP_SERVICESS_TYPES___PSVC_AVAILABLE_ONLINE_C as PSVC_AVAILABLE_ONLINE_C",
	"EXP_EMPLOYEE_GROUP_SERVICESS_TYPES___PSVC_COMMISSION_C as PSVC_COMMISSION_C",
	"EXP_EMPLOYEE_GROUP_SERVICESS_TYPES___PSVC_SERVICE_TYPE_GROUP_C as PSVC_SERVICE_TYPE_GROUP_C",
	"EXP_EMPLOYEE_GROUP_SERVICESS_TYPES___UPDATE_TSTMP as UPDATE_TSTMP",
	"EXP_EMPLOYEE_GROUP_SERVICESS_TYPES___LOAD_TSTMP as LOAD_TSTMP",
	"EXP_EMPLOYEE_GROUP_SERVICESS_TYPES___o_UPDATE_VALIDATOR as o_UPDATE_VALIDATOR")\
	.withColumn('pyspark_data_action', when(col('o_UPDATE_VALIDATOR') ==(lit(1)) , lit(0)) .when(col('o_UPDATE_VALIDATOR') ==(lit(2)) , lit(1)))

# COMMAND ----------
# Processing node Shortcut_to_SDS_EMPLOYEE_GROUP_SERVICE_TYPES_3, type TARGET 
# COLUMN COUNT: 18


Shortcut_to_SDS_EMPLOYEE_GROUP_SERVICE_TYPES_3 = UPD_EMPLOYEE_GROUP_SERVICES_TYPES.selectExpr(
	"CAST(ID AS STRING) as SDS_EMPLOYEE_GROUP_SERVICE_TYPES_ID",
	"CAST(NAME AS STRING) as SDS_EMPLOYEE_GROUP_SERVICE_TYPES_NAME",
	"CAST(PSVC_EMPLOYEE_GROUP_C AS STRING) as SDS_EMPLOYEE_GROUP_ID",
	"CAST(PSVC_SERVICE_TYPE_C AS STRING) as SDS_SERVICE_TYPE_ID",
	"CAST(PSVC_SERVICE_TYPE_GROUP_C AS STRING) as SDS_SERVICE_TYPE_GROUP_ID",
	"CAST(PSVC_COMMISSION_C AS DECIMAL(18,3)) as EMPLOYEE_GROUP_SERVICE_TYPES_COMMISSION",
	"CAST(PSVC_AVAILABLE_ONLINE_C AS TINYINT) as AVAILABLE_ONLINE_FLAG",
	"CAST(CURRENCY_ISO_CODE AS STRING) as CURRENCY_ISO_CD",
	"CAST(IS_DELETED AS TINYINT) as DELETED_FLAG",
	"CAST(LAST_VIEWED_DATE AS TIMESTAMP) as SDS_LAST_VIEWED_TSTMP",
	"CAST(LAST_REFERENCED_DATE AS TIMESTAMP) as SDS_LAST_REFERENCED_TSTMP",
	"CAST(SYSTEM_MOD_STAMP AS TIMESTAMP) as SDS_SYSTEM_MODIFIED_TSTMP",
	"CAST(LAST_MODIFIED_DATE AS TIMESTAMP) as SDS_LAST_MODIFIED_TSTMP",
	"CAST(LAST_MODIFIED_BY_ID AS STRING) as SDS_LAST_MODIFIED_BY_ID",
	"CAST(CREATED_DATE AS TIMESTAMP) as SDS_CREATED_TSTMP",
	"CAST(CREATED_BY_ID AS STRING) as SDS_CREATED_BY_ID",
	"CAST(UPDATE_TSTMP AS TIMESTAMP) as UPDATE_TSTMP",
	"CAST(LOAD_TSTMP AS TIMESTAMP) as LOAD_TSTMP",
	"UPD_EMPLOYEE_GROUP_SERVICES_TYPES.pyspark_data_action as pyspark_data_action"
)

try:
  primary_key = """source.SDS_EMPLOYEE_GROUP_SERVICE_TYPES_ID = target.SDS_EMPLOYEE_GROUP_SERVICE_TYPES_ID"""
  refined_perf_table = f"{legacy}.SDS_EMPLOYEE_GROUP_SERVICE_TYPES"
  executeMerge(Shortcut_to_SDS_EMPLOYEE_GROUP_SERVICE_TYPES_3, refined_perf_table, primary_key)
  logger.info(f"Merge with {refined_perf_table} completed]")
  logPrevRunDt("SDS_EMPLOYEE_GROUP_SERVICE_TYPES", "SDS_EMPLOYEE_GROUP_SERVICE_TYPES", "Completed", "N/A", f"{raw}.log_run_details")
except Exception as e:
  logPrevRunDt("SDS_EMPLOYEE_GROUP_SERVICE_TYPES", "SDS_EMPLOYEE_GROUP_SERVICE_TYPES","Failed",str(e), f"{raw}.log_run_details", )
  raise e
	