#Code converted on 2023-07-24 08:31:39
import os
import argparse
from pyspark.sql import *
from pyspark.sql.functions import *
from pyspark.sql.window import Window
from pyspark.sql.types import *
from datetime import datetime
from Datalake.utils.genericUtilities import *
from Datalake.utils.configs import *
from Datalake.utils.mergeUtils import *
from Datalake.utils.logger import *
# COMMAND ----------

parser = argparse.ArgumentParser()
spark = SparkSession.getActiveSession()
parser.add_argument('env', type=str, help='Env Variable')
args = parser.parse_args()
env = args.env

if env is None or env == '':
    raise ValueError('env is not set')

refine = getEnvPrefix(env) + 'refine'
raw = getEnvPrefix(env) + 'raw'
legacy = getEnvPrefix(env) + 'legacy'


# COMMAND ----------
# Processing node SQ_Shortcut_to_SDS_PRICEBOOK, type SOURCE 
# COLUMN COUNT: 5

SQ_Shortcut_to_SDS_PRICEBOOK = spark.sql(f"""SELECT
SDS_PRICEBOOK_ID,
SDS_SYSTEM_MODIFIED_TSTMP,
SDS_LAST_MODIFIED_TSTMP,
SDS_CREATED_TSTMP,
LOAD_TSTMP
FROM {legacy}.SDS_PRICEBOOK""").withColumn("sys_row_id", monotonically_increasing_id())

# COMMAND ----------
# Processing node SQ_Shortcut_to_SDS_PRICEBOOK2_PRE, type SOURCE 
# COLUMN COUNT: 16

SQ_Shortcut_to_SDS_PRICEBOOK2_PRE = spark.sql(f"""SELECT
ID,
IS_DELETED,
NAME,
CURRENCY_ISO_CODE,
CREATED_DATE,
CREATED_BY_ID,
LAST_MODIFIED_DATE,
LAST_MODIFIED_BY_ID,
SYSTEM_MOD_STAMP,
LAST_VIEWED_DATE,
LAST_REFERENCED_DATE,
IS_ACTIVE,
IS_ARCHIVED,
DESCRIPTION,
IS_STANDARD,
PSVC_STORE_C
FROM {raw}.SDS_PRICEBOOK2_PRE""").withColumn("sys_row_id", monotonically_increasing_id())

# COMMAND ----------
# Processing node JNR_SDS_PRICEBOOK, type JOINER . Note: using additional SELECT to rename incoming columns
# COLUMN COUNT: 21

# for each involved DataFrame, append the dataframe name to each column
SQ_Shortcut_to_SDS_PRICEBOOK_temp = SQ_Shortcut_to_SDS_PRICEBOOK.toDF(*["SQ_Shortcut_to_SDS_PRICEBOOK___" + col for col in SQ_Shortcut_to_SDS_PRICEBOOK.columns])
SQ_Shortcut_to_SDS_PRICEBOOK2_PRE_temp = SQ_Shortcut_to_SDS_PRICEBOOK2_PRE.toDF(*["SQ_Shortcut_to_SDS_PRICEBOOK2_PRE___" + col for col in SQ_Shortcut_to_SDS_PRICEBOOK2_PRE.columns])

JNR_SDS_PRICEBOOK = SQ_Shortcut_to_SDS_PRICEBOOK_temp2_PRE.join(SQ_Shortcut_to_SDS_PRICEBOOK_temp,[SQ_Shortcut_to_SDS_PRICEBOOK2_PRE_temp.SQ_Shortcut_to_SDS_PRICEBOOK2_PRE___ID == SQ_Shortcut_to_SDS_PRICEBOOK_temp.SQ_Shortcut_to_SDS_PRICEBOOK___SDS_PRICEBOOK_ID],'left_outer').selectExpr(
	"SQ_Shortcut_to_SDS_PRICEBOOK___SDS_PRICEBOOK_ID as i_SDS_PRICEBOOK_ID",
	"SQ_Shortcut_to_SDS_PRICEBOOK___SDS_SYSTEM_MODIFIED_TSTMP as i_SDS_SYSTEM_MODIFIED_TSTMP",
	"SQ_Shortcut_to_SDS_PRICEBOOK___SDS_LAST_MODIFIED_TSTMP as i_SDS_LAST_MODIFIED_TSTMP",
	"SQ_Shortcut_to_SDS_PRICEBOOK___SDS_CREATED_TSTMP as i_SDS_CREATED_TSTMP",
	"SQ_Shortcut_to_SDS_PRICEBOOK___LOAD_TSTMP as i_LOAD_TSTMP",
	"SQ_Shortcut_to_SDS_PRICEBOOK2_PRE___ID as ID",
	"SQ_Shortcut_to_SDS_PRICEBOOK2_PRE___IS_DELETED as IS_DELETED",
	"SQ_Shortcut_to_SDS_PRICEBOOK2_PRE___NAME as NAME",
	"SQ_Shortcut_to_SDS_PRICEBOOK2_PRE___CURRENCY_ISO_CODE as CURRENCY_ISO_CODE",
	"SQ_Shortcut_to_SDS_PRICEBOOK2_PRE___CREATED_DATE as CREATED_DATE",
	"SQ_Shortcut_to_SDS_PRICEBOOK2_PRE___CREATED_BY_ID as CREATED_BY_ID",
	"SQ_Shortcut_to_SDS_PRICEBOOK2_PRE___LAST_MODIFIED_DATE as LAST_MODIFIED_DATE",
	"SQ_Shortcut_to_SDS_PRICEBOOK2_PRE___LAST_MODIFIED_BY_ID as LAST_MODIFIED_BY_ID",
	"SQ_Shortcut_to_SDS_PRICEBOOK2_PRE___SYSTEM_MOD_STAMP as SYSTEM_MOD_STAMP",
	"SQ_Shortcut_to_SDS_PRICEBOOK2_PRE___LAST_VIEWED_DATE as LAST_VIEWED_DATE",
	"SQ_Shortcut_to_SDS_PRICEBOOK2_PRE___LAST_REFERENCED_DATE as LAST_REFERENCED_DATE",
	"SQ_Shortcut_to_SDS_PRICEBOOK2_PRE___IS_ACTIVE as IS_ACTIVE",
	"SQ_Shortcut_to_SDS_PRICEBOOK2_PRE___IS_ARCHIVED as IS_ARCHIVED",
	"SQ_Shortcut_to_SDS_PRICEBOOK2_PRE___DESCRIPTION as DESCRIPTION",
	"SQ_Shortcut_to_SDS_PRICEBOOK2_PRE___IS_STANDARD as IS_STANDARD",
	"SQ_Shortcut_to_SDS_PRICEBOOK2_PRE___PSVC_STORE_C as PSVC_STORE_C")

# COMMAND ----------
# Processing node FIL_SDS_PRICEBOOK, type FILTER 
# COLUMN COUNT: 21

# for each involved DataFrame, append the dataframe name to each column
JNR_SDS_PRICEBOOK_temp = JNR_SDS_PRICEBOOK.toDF(*["JNR_SDS_PRICEBOOK___" + col for col in JNR_SDS_PRICEBOOK.columns])

FIL_SDS_PRICEBOOK = JNR_SDS_PRICEBOOK_temp.selectExpr(
	"JNR_SDS_PRICEBOOK___i_SDS_PRICEBOOK_ID as i_SDS_PRICEBOOK_ID",
	"JNR_SDS_PRICEBOOK___i_SDS_SYSTEM_MODIFIED_TSTMP as i_SDS_SYSTEM_MODIFIED_TSTMP",
	"JNR_SDS_PRICEBOOK___i_SDS_LAST_MODIFIED_TSTMP as i_SDS_LAST_MODIFIED_TSTMP",
	"JNR_SDS_PRICEBOOK___i_SDS_CREATED_TSTMP as i_SDS_CREATED_TSTMP",
	"JNR_SDS_PRICEBOOK___i_LOAD_TSTMP as i_LOAD_TSTMP",
	"JNR_SDS_PRICEBOOK___ID as ID",
	"JNR_SDS_PRICEBOOK___IS_DELETED as IS_DELETED",
	"JNR_SDS_PRICEBOOK___NAME as NAME",
	"JNR_SDS_PRICEBOOK___CURRENCY_ISO_CODE as CURRENCY_ISO_CODE",
	"JNR_SDS_PRICEBOOK___CREATED_DATE as CREATED_DATE",
	"JNR_SDS_PRICEBOOK___CREATED_BY_ID as CREATED_BY_ID",
	"JNR_SDS_PRICEBOOK___LAST_MODIFIED_DATE as LAST_MODIFIED_DATE",
	"JNR_SDS_PRICEBOOK___LAST_MODIFIED_BY_ID as LAST_MODIFIED_BY_ID",
	"JNR_SDS_PRICEBOOK___SYSTEM_MOD_STAMP as SYSTEM_MOD_STAMP",
	"JNR_SDS_PRICEBOOK___LAST_VIEWED_DATE as LAST_VIEWED_DATE",
	"JNR_SDS_PRICEBOOK___LAST_REFERENCED_DATE as LAST_REFERENCED_DATE",
	"JNR_SDS_PRICEBOOK___IS_ACTIVE as IS_ACTIVE",
	"JNR_SDS_PRICEBOOK___IS_ARCHIVED as IS_ARCHIVED",
	"JNR_SDS_PRICEBOOK___DESCRIPTION as DESCRIPTION",
	"JNR_SDS_PRICEBOOK___IS_STANDARD as IS_STANDARD",
	"JNR_SDS_PRICEBOOK___PSVC_STORE_C as PSVC_STORE_C").filter("i_SDS_PRICEBOOK_ID IS NULL OR ( i_SDS_PRICEBOOK_ID IS NOT NULL AND ( i_SDS_SYSTEM_MODIFIED_TSTMP != SYSTEM_MOD_STAMP OR i_SDS_CREATED_TSTMP != CREATED_DATE OR i_SDS_LAST_MODIFIED_TSTMP != LAST_MODIFIED_DATE ) )").withColumn("sys_row_id", monotonically_increasing_id())

# COMMAND ----------
# Processing node EXP_SDS_PRICEBOOK, type EXPRESSION 
# COLUMN COUNT: 19

# for each involved DataFrame, append the dataframe name to each column
FIL_SDS_PRICEBOOK_temp = FIL_SDS_PRICEBOOK.toDF(*["FIL_SDS_PRICEBOOK___" + col for col in FIL_SDS_PRICEBOOK.columns])

EXP_SDS_PRICEBOOK = FIL_SDS_PRICEBOOK_temp.selectExpr(
	"FIL_SDS_PRICEBOOK___sys_row_id as sys_row_id",
	"FIL_SDS_PRICEBOOK___ID as ID",
	"FIL_SDS_PRICEBOOK___IS_DELETED as IS_DELETED",
	"FIL_SDS_PRICEBOOK___NAME as NAME",
	"FIL_SDS_PRICEBOOK___CURRENCY_ISO_CODE as CURRENCY_ISO_CODE",
	"FIL_SDS_PRICEBOOK___CREATED_DATE as CREATED_DATE",
	"FIL_SDS_PRICEBOOK___CREATED_BY_ID as CREATED_BY_ID",
	"FIL_SDS_PRICEBOOK___LAST_MODIFIED_DATE as LAST_MODIFIED_DATE",
	"FIL_SDS_PRICEBOOK___LAST_MODIFIED_BY_ID as LAST_MODIFIED_BY_ID",
	"FIL_SDS_PRICEBOOK___SYSTEM_MOD_STAMP as SYSTEM_MOD_STAMP",
	"FIL_SDS_PRICEBOOK___LAST_VIEWED_DATE as LAST_VIEWED_DATE",
	"FIL_SDS_PRICEBOOK___LAST_REFERENCED_DATE as LAST_REFERENCED_DATE",
	"FIL_SDS_PRICEBOOK___IS_ACTIVE as IS_ACTIVE",
	"FIL_SDS_PRICEBOOK___IS_ARCHIVED as IS_ARCHIVED",
	"FIL_SDS_PRICEBOOK___DESCRIPTION as DESCRIPTION",
	"FIL_SDS_PRICEBOOK___IS_STANDARD as IS_STANDARD",
	"FIL_SDS_PRICEBOOK___PSVC_STORE_C as PSVC_STORE_C",
	"CURRENT_TIMESTAMP as UPDATE_TSTMP",
	"IF (FIL_SDS_PRICEBOOK___i_LOAD_TSTMP IS NULL, CURRENT_TIMESTAMP, FIL_SDS_PRICEBOOK___i_LOAD_TSTMP) as LOAD_TSTMP",
	"IF (FIL_SDS_PRICEBOOK___i_SDS_PRICEBOOK_ID IS NULL, 1, 2) as o_UPDATE_VALIDATOR"
)

# COMMAND ----------
# Processing node UPD_SDS_PRICEBOOK, type UPDATE_STRATEGY 
# COLUMN COUNT: 19

# for each involved DataFrame, append the dataframe name to each column
EXP_SDS_PRICEBOOK_temp = EXP_SDS_PRICEBOOK.toDF(*["EXP_SDS_PRICEBOOK___" + col for col in EXP_SDS_PRICEBOOK.columns])

UPD_SDS_PRICEBOOK = EXP_SDS_PRICEBOOK_temp.selectExpr(
	"EXP_SDS_PRICEBOOK___ID as ID",
	"EXP_SDS_PRICEBOOK___IS_DELETED as IS_DELETED",
	"EXP_SDS_PRICEBOOK___NAME as NAME",
	"EXP_SDS_PRICEBOOK___CURRENCY_ISO_CODE as CURRENCY_ISO_CODE",
	"EXP_SDS_PRICEBOOK___CREATED_DATE as CREATED_DATE",
	"EXP_SDS_PRICEBOOK___CREATED_BY_ID as CREATED_BY_ID",
	"EXP_SDS_PRICEBOOK___LAST_MODIFIED_DATE as LAST_MODIFIED_DATE",
	"EXP_SDS_PRICEBOOK___LAST_MODIFIED_BY_ID as LAST_MODIFIED_BY_ID",
	"EXP_SDS_PRICEBOOK___SYSTEM_MOD_STAMP as SYSTEM_MOD_STAMP",
	"EXP_SDS_PRICEBOOK___LAST_VIEWED_DATE as LAST_VIEWED_DATE",
	"EXP_SDS_PRICEBOOK___LAST_REFERENCED_DATE as LAST_REFERENCED_DATE",
	"EXP_SDS_PRICEBOOK___IS_ACTIVE as IS_ACTIVE",
	"EXP_SDS_PRICEBOOK___IS_ARCHIVED as IS_ARCHIVED",
	"EXP_SDS_PRICEBOOK___DESCRIPTION as DESCRIPTION",
	"EXP_SDS_PRICEBOOK___IS_STANDARD as IS_STANDARD",
	"EXP_SDS_PRICEBOOK___PSVC_STORE_C as PSVC_STORE_C",
	"EXP_SDS_PRICEBOOK___UPDATE_TSTMP as UPDATE_TSTMP",
	"EXP_SDS_PRICEBOOK___LOAD_TSTMP as LOAD_TSTMP",
	"EXP_SDS_PRICEBOOK___o_UPDATE_VALIDATOR as o_UPDATE_VALIDATOR")\
	.withColumn('pyspark_data_action', when(col('o_UPDATE_VALIDATOR') ==(lit(1)) , lit(0)) .when(col('o_UPDATE_VALIDATOR') ==(lit(2)) , lit(1)))

# COMMAND ----------
# Processing node Shortcut_to_SDS_PRICEBOOK, type TARGET 
# COLUMN COUNT: 18


Shortcut_to_SDS_PRICEBOOK = UPD_SDS_PRICEBOOK.selectExpr(
	"CAST(ID AS STRING) as SDS_PRICEBOOK_ID",
	"CAST(NAME AS STRING) as SDS_PRICEBOOK_NAME",
	"CAST(DESCRIPTION AS STRING) as SDS_PRICEBOOK_DESC",
	"CAST(PSVC_STORE_C AS STRING) as SDS_SERVICE_TERRITORY_ID",
	"CAST(IS_STANDARD AS TINYINT) as STANDARD_FLAG",
	"CAST(CURRENCY_ISO_CODE AS STRING) as CURRENCY_ISO_CD",
	"CAST(IS_ARCHIVED AS TINYINT) as ARCHIVED_FLAG",
	"CAST(IS_ACTIVE AS TINYINT) as ACTIVE_FLAG",
	"CAST(IS_DELETED AS TINYINT) as DELETED_FLAG",
	"CAST(LAST_VIEWED_DATE AS TIMESTAMP) as SDS_LAST_VIEWED_TSTMP",
	"CAST(LAST_REFERENCED_DATE AS TIMESTAMP) as SDS_LAST_REFERENCED_TSTMP",
	"CAST(SYSTEM_MOD_STAMP AS TIMESTAMP) as SDS_SYSTEM_MODIFIED_TSTMP",
	"CAST(LAST_MODIFIED_DATE AS TIMESTAMP) as SDS_LAST_MODIFIED_TSTMP",
	"CAST(LAST_MODIFIED_BY_ID AS STRING) as SDS_LAST_MODIFIED_BY_ID",
	"CAST(CREATED_DATE AS TIMESTAMP) as SDS_CREATED_TSTMP",
	"CAST(CREATED_BY_ID AS STRING) as SDS_CREATED_BY_ID",
	"CAST(UPDATE_TSTMP AS TIMESTAMP) as UPDATE_TSTMP",
	"CAST(LOAD_TSTMP AS TIMESTAMP) as LOAD_TSTMP",
	"UPD_SDS_PRICEBOOK.pyspark_data_action as pyspark_data_action"
)

try:
  primary_key = """source.SDS_PRICEBOOK_ID = target.SDS_PRICEBOOK_ID"""
  refined_perf_table = f"{legacy}.SDS_PRICEBOOK"
  executeMerge(Shortcut_to_SDS_PRICEBOOK, refined_perf_table, primary_key)
  logger.info(f"Merge with {refined_perf_table} completed]")
  logPrevRunDt("SDS_PRICEBOOK", "SDS_PRICEBOOK", "Completed", "N/A", f"{raw}.log_run_details")
except Exception as e:
  logPrevRunDt("SDS_PRICEBOOK", "SDS_PRICEBOOK","Failed",str(e), f"{raw}.log_run_details", )
  raise e
	