#Code converted on 2023-07-24 08:22:03
import os
import argparse
from pyspark.sql import *
from pyspark.sql.functions import *
from pyspark.sql.window import Window
from pyspark.sql.types import *
from datetime import datetime
from Datalake.utils.genericUtilities import *
from Datalake.utils.configs import *
from Datalake.utils.mergeUtils import *
from Datalake.utils.logger import *
# COMMAND ----------

parser = argparse.ArgumentParser()
spark = SparkSession.getActiveSession()
parser.add_argument('env', type=str, help='Env Variable')
args = parser.parse_args()
env = args.env

if env is None or env == '':
    raise ValueError('env is not set')

refine = getEnvPrefix(env) + 'refine'
raw = getEnvPrefix(env) + 'raw'
legacy = getEnvPrefix(env) + 'legacy'


# COMMAND ----------
# Processing node SQ_Shortcut_to_SDS_OPERATING_HOURS, type SOURCE 
# COLUMN COUNT: 5

SQ_Shortcut_to_SDS_OPERATING_HOURS = spark.sql(f"""SELECT
SDS_OPERATING_HOURS_ID,
SDS_SYSTEM_MODIFIED_TSTMP,
SDS_LAST_MODIFIED_TSTMP,
SDS_CREATED_TSTMP,
LOAD_TSTMP
FROM {legacy}.SDS_OPERATING_HOURS""").withColumn("sys_row_id", monotonically_increasing_id())

# COMMAND ----------
# Processing node SQ_Shortcut_to_SDS_OPERATING_HOURS_PRE, type SOURCE 
# COLUMN COUNT: 14

SQ_Shortcut_to_SDS_OPERATING_HOURS_PRE = spark.sql(f"""SELECT
ID,
IS_DELETED,
NAME,
CURRENCY_ISO_CODE,
CREATED_DATE,
CREATED_BY_ID,
LAST_MODIFIED_DATE,
LAST_MODIFIED_BY_ID,
SYSTEM_MOD_STAMP,
LAST_VIEWED_DATE,
LAST_REFERENCED_DATE,
DESCRIPTION,
TIME_ZONE,
PSVC_STORE_NUMBER_C
FROM {raw}.SDS_OPERATING_HOURS_PRE""").withColumn("sys_row_id", monotonically_increasing_id())

# COMMAND ----------
# Processing node JNR_SDS_OPERATING_HOURS, type JOINER . Note: using additional SELECT to rename incoming columns
# COLUMN COUNT: 19

# for each involved DataFrame, append the dataframe name to each column
SQ_Shortcut_to_SDS_OPERATING_HOURS_temp = SQ_Shortcut_to_SDS_OPERATING_HOURS.toDF(*["SQ_Shortcut_to_SDS_OPERATING_HOURS___" + col for col in SQ_Shortcut_to_SDS_OPERATING_HOURS.columns])
SQ_Shortcut_to_SDS_OPERATING_HOURS_PRE_temp = SQ_Shortcut_to_SDS_OPERATING_HOURS_PRE.toDF(*["SQ_Shortcut_to_SDS_OPERATING_HOURS_PRE___" + col for col in SQ_Shortcut_to_SDS_OPERATING_HOURS_PRE.columns])

JNR_SDS_OPERATING_HOURS = SQ_Shortcut_to_SDS_OPERATING_HOURS_temp_PRE.join(SQ_Shortcut_to_SDS_OPERATING_HOURS_temp,[SQ_Shortcut_to_SDS_OPERATING_HOURS_PRE_temp.SQ_Shortcut_to_SDS_OPERATING_HOURS_PRE___ID == SQ_Shortcut_to_SDS_OPERATING_HOURS_temp.SQ_Shortcut_to_SDS_OPERATING_HOURS___SDS_OPERATING_HOURS_ID],'left_outer').selectExpr(
	"SQ_Shortcut_to_SDS_OPERATING_HOURS___SDS_OPERATING_HOURS_ID as i_SDS_OPERATING_HOURS_ID",
	"SQ_Shortcut_to_SDS_OPERATING_HOURS___SDS_SYSTEM_MODIFIED_TSTMP as i_SDS_SYSTEM_MODIFIED_TSTMP",
	"SQ_Shortcut_to_SDS_OPERATING_HOURS___SDS_LAST_MODIFIED_TSTMP as i_SDS_LAST_MODIFIED_TSTMP",
	"SQ_Shortcut_to_SDS_OPERATING_HOURS___SDS_CREATED_TSTMP as i_SDS_CREATED_TSTMP",
	"SQ_Shortcut_to_SDS_OPERATING_HOURS___LOAD_TSTMP as i_LOAD_TSTMP",
	"SQ_Shortcut_to_SDS_OPERATING_HOURS_PRE___ID as ID",
	"SQ_Shortcut_to_SDS_OPERATING_HOURS_PRE___IS_DELETED as IS_DELETED",
	"SQ_Shortcut_to_SDS_OPERATING_HOURS_PRE___NAME as NAME",
	"SQ_Shortcut_to_SDS_OPERATING_HOURS_PRE___CURRENCY_ISO_CODE as CURRENCY_ISO_CODE",
	"SQ_Shortcut_to_SDS_OPERATING_HOURS_PRE___CREATED_DATE as CREATED_DATE",
	"SQ_Shortcut_to_SDS_OPERATING_HOURS_PRE___CREATED_BY_ID as CREATED_BY_ID",
	"SQ_Shortcut_to_SDS_OPERATING_HOURS_PRE___LAST_MODIFIED_DATE as LAST_MODIFIED_DATE",
	"SQ_Shortcut_to_SDS_OPERATING_HOURS_PRE___LAST_MODIFIED_BY_ID as LAST_MODIFIED_BY_ID",
	"SQ_Shortcut_to_SDS_OPERATING_HOURS_PRE___SYSTEM_MOD_STAMP as SYSTEM_MOD_STAMP",
	"SQ_Shortcut_to_SDS_OPERATING_HOURS_PRE___LAST_VIEWED_DATE as LAST_VIEWED_DATE",
	"SQ_Shortcut_to_SDS_OPERATING_HOURS_PRE___LAST_REFERENCED_DATE as LAST_REFERENCED_DATE",
	"SQ_Shortcut_to_SDS_OPERATING_HOURS_PRE___DESCRIPTION as DESCRIPTION",
	"SQ_Shortcut_to_SDS_OPERATING_HOURS_PRE___TIME_ZONE as TIME_ZONE",
	"SQ_Shortcut_to_SDS_OPERATING_HOURS_PRE___PSVC_STORE_NUMBER_C as PSVC_STORE_NUMBER_C")

# COMMAND ----------
# Processing node FIL_SDS_OPERATING_HOURS, type FILTER 
# COLUMN COUNT: 19

# for each involved DataFrame, append the dataframe name to each column
JNR_SDS_OPERATING_HOURS_temp = JNR_SDS_OPERATING_HOURS.toDF(*["JNR_SDS_OPERATING_HOURS___" + col for col in JNR_SDS_OPERATING_HOURS.columns])

FIL_SDS_OPERATING_HOURS = JNR_SDS_OPERATING_HOURS_temp.selectExpr(
	"JNR_SDS_OPERATING_HOURS___i_SDS_OPERATING_HOURS_ID as i_SDS_OPERATING_HOURS_ID",
	"JNR_SDS_OPERATING_HOURS___i_SDS_SYSTEM_MODIFIED_TSTMP as i_SDS_SYSTEM_MODIFIED_TSTMP",
	"JNR_SDS_OPERATING_HOURS___i_SDS_LAST_MODIFIED_TSTMP as i_SDS_LAST_MODIFIED_TSTMP",
	"JNR_SDS_OPERATING_HOURS___i_SDS_CREATED_TSTMP as i_SDS_CREATED_TSTMP",
	"JNR_SDS_OPERATING_HOURS___i_LOAD_TSTMP as i_LOAD_TSTMP",
	"JNR_SDS_OPERATING_HOURS___ID as ID",
	"JNR_SDS_OPERATING_HOURS___IS_DELETED as IS_DELETED",
	"JNR_SDS_OPERATING_HOURS___NAME as NAME",
	"JNR_SDS_OPERATING_HOURS___CURRENCY_ISO_CODE as CURRENCY_ISO_CODE",
	"JNR_SDS_OPERATING_HOURS___CREATED_DATE as CREATED_DATE",
	"JNR_SDS_OPERATING_HOURS___CREATED_BY_ID as CREATED_BY_ID",
	"JNR_SDS_OPERATING_HOURS___LAST_MODIFIED_DATE as LAST_MODIFIED_DATE",
	"JNR_SDS_OPERATING_HOURS___LAST_MODIFIED_BY_ID as LAST_MODIFIED_BY_ID",
	"JNR_SDS_OPERATING_HOURS___SYSTEM_MOD_STAMP as SYSTEM_MOD_STAMP",
	"JNR_SDS_OPERATING_HOURS___LAST_VIEWED_DATE as LAST_VIEWED_DATE",
	"JNR_SDS_OPERATING_HOURS___LAST_REFERENCED_DATE as LAST_REFERENCED_DATE",
	"JNR_SDS_OPERATING_HOURS___DESCRIPTION as DESCRIPTION",
	"JNR_SDS_OPERATING_HOURS___TIME_ZONE as TIME_ZONE",
	"JNR_SDS_OPERATING_HOURS___PSVC_STORE_NUMBER_C as PSVC_STORE_NUMBER_C").filter("i_SDS_OPERATING_HOURS_ID IS NULL OR ( i_SDS_OPERATING_HOURS_ID IS NOT NULL AND ( i_SDS_SYSTEM_MODIFIED_TSTMP != SYSTEM_MOD_STAMP OR i_SDS_CREATED_TSTMP != CREATED_DATE OR i_SDS_LAST_MODIFIED_TSTMP != LAST_MODIFIED_DATE ) )").withColumn("sys_row_id", monotonically_increasing_id())

# COMMAND ----------
# Processing node EXP_SDS_OPERATING_HOURS, type EXPRESSION 
# COLUMN COUNT: 17

# for each involved DataFrame, append the dataframe name to each column
FIL_SDS_OPERATING_HOURS_temp = FIL_SDS_OPERATING_HOURS.toDF(*["FIL_SDS_OPERATING_HOURS___" + col for col in FIL_SDS_OPERATING_HOURS.columns])

EXP_SDS_OPERATING_HOURS = FIL_SDS_OPERATING_HOURS_temp.selectExpr(
	"FIL_SDS_OPERATING_HOURS___sys_row_id as sys_row_id",
	"FIL_SDS_OPERATING_HOURS___ID as ID",
	"FIL_SDS_OPERATING_HOURS___IS_DELETED as IS_DELETED",
	"FIL_SDS_OPERATING_HOURS___NAME as NAME",
	"FIL_SDS_OPERATING_HOURS___CURRENCY_ISO_CODE as CURRENCY_ISO_CODE",
	"FIL_SDS_OPERATING_HOURS___CREATED_DATE as CREATED_DATE",
	"FIL_SDS_OPERATING_HOURS___CREATED_BY_ID as CREATED_BY_ID",
	"FIL_SDS_OPERATING_HOURS___LAST_MODIFIED_DATE as LAST_MODIFIED_DATE",
	"FIL_SDS_OPERATING_HOURS___LAST_MODIFIED_BY_ID as LAST_MODIFIED_BY_ID",
	"FIL_SDS_OPERATING_HOURS___SYSTEM_MOD_STAMP as SYSTEM_MOD_STAMP",
	"FIL_SDS_OPERATING_HOURS___LAST_VIEWED_DATE as LAST_VIEWED_DATE",
	"FIL_SDS_OPERATING_HOURS___LAST_REFERENCED_DATE as LAST_REFERENCED_DATE",
	"FIL_SDS_OPERATING_HOURS___DESCRIPTION as DESCRIPTION",
	"FIL_SDS_OPERATING_HOURS___TIME_ZONE as TIME_ZONE",
	"FIL_SDS_OPERATING_HOURS___PSVC_STORE_NUMBER_C as PSVC_STORE_NUMBER_C",
	"CURRENT_TIMESTAMP as UPDATE_TSTMP",
	"IF (FIL_SDS_OPERATING_HOURS___i_LOAD_TSTMP IS NULL, CURRENT_TIMESTAMP, FIL_SDS_OPERATING_HOURS___i_LOAD_TSTMP) as LOAD_TSTMP",
	"IF (FIL_SDS_OPERATING_HOURS___i_SDS_OPERATING_HOURS_ID IS NULL, 1, 2) as o_UPDATE_VALIDATOR"
)

# COMMAND ----------
# Processing node UPD_SDS_OPERATING_HOURS, type UPDATE_STRATEGY 
# COLUMN COUNT: 17

# for each involved DataFrame, append the dataframe name to each column
EXP_SDS_OPERATING_HOURS_temp = EXP_SDS_OPERATING_HOURS.toDF(*["EXP_SDS_OPERATING_HOURS___" + col for col in EXP_SDS_OPERATING_HOURS.columns])

UPD_SDS_OPERATING_HOURS = EXP_SDS_OPERATING_HOURS_temp.selectExpr(
	"EXP_SDS_OPERATING_HOURS___ID as ID",
	"EXP_SDS_OPERATING_HOURS___IS_DELETED as IS_DELETED",
	"EXP_SDS_OPERATING_HOURS___NAME as NAME",
	"EXP_SDS_OPERATING_HOURS___CURRENCY_ISO_CODE as CURRENCY_ISO_CODE",
	"EXP_SDS_OPERATING_HOURS___CREATED_DATE as CREATED_DATE",
	"EXP_SDS_OPERATING_HOURS___CREATED_BY_ID as CREATED_BY_ID",
	"EXP_SDS_OPERATING_HOURS___LAST_MODIFIED_DATE as LAST_MODIFIED_DATE",
	"EXP_SDS_OPERATING_HOURS___LAST_MODIFIED_BY_ID as LAST_MODIFIED_BY_ID",
	"EXP_SDS_OPERATING_HOURS___SYSTEM_MOD_STAMP as SYSTEM_MOD_STAMP",
	"EXP_SDS_OPERATING_HOURS___LAST_VIEWED_DATE as LAST_VIEWED_DATE",
	"EXP_SDS_OPERATING_HOURS___LAST_REFERENCED_DATE as LAST_REFERENCED_DATE",
	"EXP_SDS_OPERATING_HOURS___DESCRIPTION as DESCRIPTION",
	"EXP_SDS_OPERATING_HOURS___TIME_ZONE as TIME_ZONE",
	"EXP_SDS_OPERATING_HOURS___PSVC_STORE_NUMBER_C as PSVC_STORE_NUMBER_C",
	"EXP_SDS_OPERATING_HOURS___UPDATE_TSTMP as UPDATE_TSTMP",
	"EXP_SDS_OPERATING_HOURS___LOAD_TSTMP as LOAD_TSTMP",
	"EXP_SDS_OPERATING_HOURS___o_UPDATE_VALIDATOR as o_UPDATE_VALIDATOR")\
	.withColumn('pyspark_data_action', when(col('o_UPDATE_VALIDATOR') ==(lit(1)) , lit(0)).when(col('o_UPDATE_VALIDATOR') ==(lit(2)) , lit(1)).when(col('o_UPDATE_VALIDATOR') ==(lit(3)) , lit(3)))

# COMMAND ----------
# Processing node Shortcut_to_SDS_OPERATING_HOURS, type TARGET 
# COLUMN COUNT: 16


Shortcut_to_SDS_OPERATING_HOURS = UPD_SDS_OPERATING_HOURS.selectExpr(
	"CAST(ID AS STRING) as SDS_OPERATING_HOURS_ID",
	"CAST(NAME AS STRING) as SDS_OPERATING_HOURS_NAME",
	"CAST(DESCRIPTION AS STRING) as SDS_OPERATING_HOURS_DESC",
	"CAST(PSVC_STORE_NUMBER_C AS STRING) as STORE_NBR",
	"CAST(TIME_ZONE AS STRING) as TIME_ZONE",
	"CAST(CURRENCY_ISO_CODE AS STRING) as CURRENCY_ISO_CD",
	"CAST(IS_DELETED AS TINYINT) as DELETED_FLAG",
	"CAST(LAST_VIEWED_DATE AS TIMESTAMP) as SDS_LAST_VIEWED_TSTMP",
	"CAST(LAST_REFERENCED_DATE AS TIMESTAMP) as SDS_LAST_REFERENCED_TSTMP",
	"CAST(SYSTEM_MOD_STAMP AS TIMESTAMP) as SDS_SYSTEM_MODIFIED_TSTMP",
	"CAST(LAST_MODIFIED_DATE AS TIMESTAMP) as SDS_LAST_MODIFIED_TSTMP",
	"CAST(LAST_MODIFIED_BY_ID AS STRING) as SDS_LAST_MODIFIED_BY_ID",
	"CAST(CREATED_DATE AS TIMESTAMP) as SDS_CREATED_TSTMP",
	"CAST(CREATED_BY_ID AS STRING) as SDS_CREATED_BY_ID",
	"CAST(UPDATE_TSTMP AS TIMESTAMP) as UPDATE_TSTMP",
	"CAST(LOAD_TSTMP AS TIMESTAMP) as LOAD_TSTMP",
	"UPD_SDS_OPERATING_HOURS.pyspark_data_action as pyspark_data_action"
)

try:
  primary_key = """source.SDS_OPERATING_HOURS_ID = target.SDS_OPERATING_HOURS_ID"""
  refined_perf_table = f"{legacy}.SDS_OPERATING_HOURS"
  executeMerge(Shortcut_to_SDS_OPERATING_HOURS, refined_perf_table, primary_key)
  logger.info(f"Merge with {refined_perf_table} completed]")
  logPrevRunDt("SDS_OPERATING_HOURS", "SDS_OPERATING_HOURS", "Completed", "N/A", f"{raw}.log_run_details")
except Exception as e:
  logPrevRunDt("SDS_OPERATING_HOURS", "SDS_OPERATING_HOURS","Failed",str(e), f"{raw}.log_run_details", )
  raise e
	