#Code converted on 2023-07-21 14:57:42
import os
import argparse
from pyspark.sql import *
from pyspark.sql.functions import *
from pyspark.sql.window import Window
from pyspark.sql.types import *
from datetime import datetime
from Datalake.utils.genericUtilities import *
from Datalake.utils.configs import *
from Datalake.utils.mergeUtils import *
from Datalake.utils.logger import *
# COMMAND ----------

parser = argparse.ArgumentParser()
spark = SparkSession.getActiveSession()
parser.add_argument('env', type=str, help='Env Variable')
args = parser.parse_args()
env = args.env

if env is None or env == '':
    raise ValueError('env is not set')

refine = getEnvPrefix(env) + 'refine'
raw = getEnvPrefix(env) + 'raw'
legacy = getEnvPrefix(env) + 'legacy'


# COMMAND ----------
# Processing node SQ_Shortcut_to_SDS_PSVC_ORDER_PRODUCT_SPECIAL_C_PRE, type SOURCE 
# COLUMN COUNT: 26

SQ_Shortcut_to_SDS_PSVC_ORDER_PRODUCT_SPECIAL_C_PRE = spark.sql(f"""SELECT 

ID, 

OWNER_ID, 

IS_DELETED, 

NAME, 

CURRENCY_ISO_CODE, 

CREATED_DATE, 

CREATED_BY_ID, 

LAST_MODIFIED_DATE, 

LAST_MODIFIED_BY_ID, 

SYSTEM_MOD_STAMP, 

PSVC_SPECIAL_C, 

PSVC_ADJUSTMENT_AMOUNT_C, 

PSVC_ADJUSTMENT_PERCENTAGE_C, 

PSVC_HIDE_FROM_CUSTOMER_ONLINE_INVOICE_C, 

PSVC_IS_FOR_QUOTE_C, 

PSVC_MANUALLY_ENTERED_CODE_C, 

PSVC_ORDER_PRODUCT_C, 

PSVC_PREMIUM_DISCOUNT_C, 

PSVC_SPECIAL_CODE_C, 

PSVC_APPLY_TO_ALL_PRODUCTS_C, 

PSVC_DUPLICATION_C, 

PSVC_AUTO_CALCULATED_PRICE_C, 

PSVC_MANUAL_C, 

PSVC_DISCOUNT_APPLIED_FOR_PERCENTAGE_COU_C, 

PSVC_EVALUATION_ORDER_C, 

LOAD_TSTMP 

FROM

{raw}.SDS_PSVC_ORDER_PRODUCT_SPECIAL_C_PRE

LEFT JOIN SDS_ORDER_ITEM

ON SDS_PSVC_ORDER_PRODUCT_SPECIAL_C_PRE.PSVC_ORDER_PRODUCT_C=SDS_ORDER_ITEM.SDS_ORDER_ITEM_ID

WHERE

SDS_ORDER_ITEM.SMS_ORDER_ITEM_ID  like 'F%' 

OR

SDS_ORDER_ITEM.SMS_ORDER_ITEM_ID IS NULL""").withColumn("sys_row_id", monotonically_increasing_id())
# Conforming fields names to the component layout
SQ_Shortcut_to_SDS_PSVC_ORDER_PRODUCT_SPECIAL_C_PRE = SQ_Shortcut_to_SDS_PSVC_ORDER_PRODUCT_SPECIAL_C_PRE\
	.withColumnRenamed(SQ_Shortcut_to_SDS_PSVC_ORDER_PRODUCT_SPECIAL_C_PRE.columns[0],'ID')\
	.withColumnRenamed(SQ_Shortcut_to_SDS_PSVC_ORDER_PRODUCT_SPECIAL_C_PRE.columns[1],'OWNER_ID')\
	.withColumnRenamed(SQ_Shortcut_to_SDS_PSVC_ORDER_PRODUCT_SPECIAL_C_PRE.columns[2],'IS_DELETED')\
	.withColumnRenamed(SQ_Shortcut_to_SDS_PSVC_ORDER_PRODUCT_SPECIAL_C_PRE.columns[3],'NAME')\
	.withColumnRenamed(SQ_Shortcut_to_SDS_PSVC_ORDER_PRODUCT_SPECIAL_C_PRE.columns[4],'CURRENCY_ISO_CODE')\
	.withColumnRenamed(SQ_Shortcut_to_SDS_PSVC_ORDER_PRODUCT_SPECIAL_C_PRE.columns[5],'CREATED_DATE')\
	.withColumnRenamed(SQ_Shortcut_to_SDS_PSVC_ORDER_PRODUCT_SPECIAL_C_PRE.columns[6],'CREATED_BY_ID')\
	.withColumnRenamed(SQ_Shortcut_to_SDS_PSVC_ORDER_PRODUCT_SPECIAL_C_PRE.columns[7],'LAST_MODIFIED_DATE')\
	.withColumnRenamed(SQ_Shortcut_to_SDS_PSVC_ORDER_PRODUCT_SPECIAL_C_PRE.columns[8],'LAST_MODIFIED_BY_ID')\
	.withColumnRenamed(SQ_Shortcut_to_SDS_PSVC_ORDER_PRODUCT_SPECIAL_C_PRE.columns[9],'SYSTEM_MOD_STAMP')\
	.withColumnRenamed(SQ_Shortcut_to_SDS_PSVC_ORDER_PRODUCT_SPECIAL_C_PRE.columns[10],'PSVC_SPECIAL_C')\
	.withColumnRenamed(SQ_Shortcut_to_SDS_PSVC_ORDER_PRODUCT_SPECIAL_C_PRE.columns[11],'PSVC_ADJUSTMENT_AMOUNT_C')\
	.withColumnRenamed(SQ_Shortcut_to_SDS_PSVC_ORDER_PRODUCT_SPECIAL_C_PRE.columns[12],'PSVC_ADJUSTMENT_PERCENTAGE_C')\
	.withColumnRenamed(SQ_Shortcut_to_SDS_PSVC_ORDER_PRODUCT_SPECIAL_C_PRE.columns[13],'PSVC_HIDE_FROM_CUSTOMER_ONLINE_INVOICE_C')\
	.withColumnRenamed(SQ_Shortcut_to_SDS_PSVC_ORDER_PRODUCT_SPECIAL_C_PRE.columns[14],'PSVC_IS_FOR_QUOTE_C')\
	.withColumnRenamed(SQ_Shortcut_to_SDS_PSVC_ORDER_PRODUCT_SPECIAL_C_PRE.columns[15],'PSVC_MANUALLY_ENTERED_CODE_C')\
	.withColumnRenamed(SQ_Shortcut_to_SDS_PSVC_ORDER_PRODUCT_SPECIAL_C_PRE.columns[16],'PSVC_ORDER_PRODUCT_C')\
	.withColumnRenamed(SQ_Shortcut_to_SDS_PSVC_ORDER_PRODUCT_SPECIAL_C_PRE.columns[17],'PSVC_PREMIUM_DISCOUNT_C')\
	.withColumnRenamed(SQ_Shortcut_to_SDS_PSVC_ORDER_PRODUCT_SPECIAL_C_PRE.columns[18],'PSVC_SPECIAL_CODE_C')\
	.withColumnRenamed(SQ_Shortcut_to_SDS_PSVC_ORDER_PRODUCT_SPECIAL_C_PRE.columns[19],'PSVC_APPLY_TO_ALL_PRODUCTS_C')\
	.withColumnRenamed(SQ_Shortcut_to_SDS_PSVC_ORDER_PRODUCT_SPECIAL_C_PRE.columns[20],'PSVC_DUPLICATION_C')\
	.withColumnRenamed(SQ_Shortcut_to_SDS_PSVC_ORDER_PRODUCT_SPECIAL_C_PRE.columns[21],'PSVC_AUTO_CALCULATED_PRICE_C')\
	.withColumnRenamed(SQ_Shortcut_to_SDS_PSVC_ORDER_PRODUCT_SPECIAL_C_PRE.columns[22],'PSVC_MANUAL_C')\
	.withColumnRenamed(SQ_Shortcut_to_SDS_PSVC_ORDER_PRODUCT_SPECIAL_C_PRE.columns[23],'PSVC_DISCOUNT_APPLIED_FOR_PERCENTAGE_COU_C')\
	.withColumnRenamed(SQ_Shortcut_to_SDS_PSVC_ORDER_PRODUCT_SPECIAL_C_PRE.columns[24],'PSVC_EVALUATION_ORDER_C')\
	.withColumnRenamed(SQ_Shortcut_to_SDS_PSVC_ORDER_PRODUCT_SPECIAL_C_PRE.columns[25],'LOAD_TSTMP')

# COMMAND ----------
# Processing node SQ_Shortcut_to_SDS_ORDER_PRODUCT_SPECIAL, type SOURCE 
# COLUMN COUNT: 28

SQ_Shortcut_to_SDS_ORDER_PRODUCT_SPECIAL = spark.sql(f"""SELECT
SDS_ORDER_PRODUCT_SPECIAL_ID,
SDS_ORDER_PRODUCT_SPECIAL_NAME,
SDS_ORDER_ITEM_ID,
SDS_SPECIAL_ID,
SDS_SPECIAL_CD,
MANUALLY_ENTERED_CD,
PREMIUM_DISCOUNT,
ADJUSTMENT_AMT,
ADJUSTMENT_PCT,
APPLIED_PCT_DISCOUNT_AMT,
EVALUATION_ORDER_NBR,
AUTO_CALCULATED_PRICE,
MANUAL_ADJUSTED_FLAG,
HIDE_FROM_CUSTOMER_ONLINE_INVOICE_FLAG,
APPLY_TO_ALL_PRODUCTS_FLAG,
DUPLICATION,
FOR_QUOTE_FLAG,
SDS_OWNER_ID,
CURRENCY_ISO_CD,
DELETED_FLAG,
HARD_DELETED_FLAG,
SDS_SYSTEM_MODIFIED_TSTMP,
SDS_LAST_MODIFIED_TSTMP,
SDS_LAST_MODIFIED_BY_ID,
SDS_CREATED_TSTMP,
SDS_CREATED_BY_ID,
UPDATE_TSTMP,
LOAD_TSTMP
FROM {legacy}.SDS_ORDER_PRODUCT_SPECIAL""").withColumn("sys_row_id", monotonically_increasing_id())

# COMMAND ----------
# Processing node JNR_SDS_ORDER_PRODUCT_SPECIAL, type JOINER . Note: using additional SELECT to rename incoming columns
# COLUMN COUNT: 54

# for each involved DataFrame, append the dataframe name to each column
SQ_Shortcut_to_SDS_PSVC_ORDER_PRODUCT_SPECIAL_C_PRE_temp = SQ_Shortcut_to_SDS_PSVC_ORDER_PRODUCT_SPECIAL_C_PRE.toDF(*["SQ_Shortcut_to_SDS_PSVC_ORDER_PRODUCT_SPECIAL_C_PRE___" + col for col in SQ_Shortcut_to_SDS_PSVC_ORDER_PRODUCT_SPECIAL_C_PRE.columns])
SQ_Shortcut_to_SDS_ORDER_PRODUCT_SPECIAL_temp = SQ_Shortcut_to_SDS_ORDER_PRODUCT_SPECIAL.toDF(*["SQ_Shortcut_to_SDS_ORDER_PRODUCT_SPECIAL___" + col for col in SQ_Shortcut_to_SDS_ORDER_PRODUCT_SPECIAL.columns])

JNR_SDS_ORDER_PRODUCT_SPECIAL = SQ_Shortcut_to_SDS_PSVC_ORDER_PRODUCT_SPECIAL_C_PRE_temp.join(SQ_Shortcut_to_SDS_ORDER_PRODUCT_SPECIAL_temp,[SQ_Shortcut_to_SDS_PSVC_ORDER_PRODUCT_SPECIAL_C_PRE_temp.SQ_Shortcut_to_SDS_PSVC_ORDER_PRODUCT_SPECIAL_C_PRE___ID == SQ_Shortcut_to_SDS_ORDER_PRODUCT_SPECIAL_temp.SQ_Shortcut_to_SDS_ORDER_PRODUCT_SPECIAL___SDS_ORDER_PRODUCT_SPECIAL_ID],'left_outer').selectExpr(
	"SQ_Shortcut_to_SDS_ORDER_PRODUCT_SPECIAL___SDS_ORDER_PRODUCT_SPECIAL_ID as i_SDS_ORDER_PRODUCT_SPECIAL_ID",
	"SQ_Shortcut_to_SDS_ORDER_PRODUCT_SPECIAL___SDS_ORDER_PRODUCT_SPECIAL_NAME as i_SDS_ORDER_PRODUCT_SPECIAL_NAME",
	"SQ_Shortcut_to_SDS_ORDER_PRODUCT_SPECIAL___SDS_ORDER_ITEM_ID as i_SDS_ORDER_ITEM_ID",
	"SQ_Shortcut_to_SDS_ORDER_PRODUCT_SPECIAL___SDS_SPECIAL_ID as i_SDS_SPECIAL_ID",
	"SQ_Shortcut_to_SDS_ORDER_PRODUCT_SPECIAL___SDS_SPECIAL_CD as i_SDS_SPECIAL_CD",
	"SQ_Shortcut_to_SDS_ORDER_PRODUCT_SPECIAL___MANUALLY_ENTERED_CD as i_MANUALLY_ENTERED_CD",
	"SQ_Shortcut_to_SDS_ORDER_PRODUCT_SPECIAL___PREMIUM_DISCOUNT as i_PREMIUM_DISCOUNT",
	"SQ_Shortcut_to_SDS_ORDER_PRODUCT_SPECIAL___ADJUSTMENT_AMT as i_ADJUSTMENT_AMT",
	"SQ_Shortcut_to_SDS_ORDER_PRODUCT_SPECIAL___ADJUSTMENT_PCT as i_ADJUSTMENT_PCT",
	"SQ_Shortcut_to_SDS_ORDER_PRODUCT_SPECIAL___APPLIED_PCT_DISCOUNT_AMT as i_APPLIED_PCT_DISCOUNT_AMT",
	"SQ_Shortcut_to_SDS_ORDER_PRODUCT_SPECIAL___EVALUATION_ORDER_NBR as i_EVALUATION_ORDER_NBR",
	"SQ_Shortcut_to_SDS_ORDER_PRODUCT_SPECIAL___AUTO_CALCULATED_PRICE as i_AUTO_CALCULATED_PRICE",
	"SQ_Shortcut_to_SDS_ORDER_PRODUCT_SPECIAL___MANUAL_ADJUSTED_FLAG as i_MANUAL_ADJUSTED_FLAG",
	"SQ_Shortcut_to_SDS_ORDER_PRODUCT_SPECIAL___HIDE_FROM_CUSTOMER_ONLINE_INVOICE_FLAG as i_HIDE_FROM_CUSTOMER_ONLINE_INVOICE_FLAG",
	"SQ_Shortcut_to_SDS_ORDER_PRODUCT_SPECIAL___APPLY_TO_ALL_PRODUCTS_FLAG as i_APPLY_TO_ALL_PRODUCTS_FLAG",
	"SQ_Shortcut_to_SDS_ORDER_PRODUCT_SPECIAL___DUPLICATION as i_DUPLICATION",
	"SQ_Shortcut_to_SDS_ORDER_PRODUCT_SPECIAL___FOR_QUOTE_FLAG as i_FOR_QUOTE_FLAG",
	"SQ_Shortcut_to_SDS_ORDER_PRODUCT_SPECIAL___SDS_OWNER_ID as i_SDS_OWNER_ID",
	"SQ_Shortcut_to_SDS_ORDER_PRODUCT_SPECIAL___CURRENCY_ISO_CD as i_CURRENCY_ISO_CD",
	"SQ_Shortcut_to_SDS_ORDER_PRODUCT_SPECIAL___DELETED_FLAG as i_DELETED_FLAG",
	"SQ_Shortcut_to_SDS_ORDER_PRODUCT_SPECIAL___HARD_DELETED_FLAG as i_HARD_DELETED_FLAG",
	"SQ_Shortcut_to_SDS_ORDER_PRODUCT_SPECIAL___SDS_SYSTEM_MODIFIED_TSTMP as i_SDS_SYSTEM_MODIFIED_TSTMP",
	"SQ_Shortcut_to_SDS_ORDER_PRODUCT_SPECIAL___SDS_LAST_MODIFIED_TSTMP as i_SDS_LAST_MODIFIED_TSTMP",
	"SQ_Shortcut_to_SDS_ORDER_PRODUCT_SPECIAL___SDS_LAST_MODIFIED_BY_ID as i_SDS_LAST_MODIFIED_BY_ID",
	"SQ_Shortcut_to_SDS_ORDER_PRODUCT_SPECIAL___SDS_CREATED_TSTMP as i_SDS_CREATED_TSTMP",
	"SQ_Shortcut_to_SDS_ORDER_PRODUCT_SPECIAL___SDS_CREATED_BY_ID as i_SDS_CREATED_BY_ID",
	"SQ_Shortcut_to_SDS_ORDER_PRODUCT_SPECIAL___UPDATE_TSTMP as i_UPDATE_TSTMP",
	"SQ_Shortcut_to_SDS_ORDER_PRODUCT_SPECIAL___LOAD_TSTMP as i_LOAD_TSTMP",
	"SQ_Shortcut_to_SDS_PSVC_ORDER_PRODUCT_SPECIAL_C_PRE___ID as ID",
	"SQ_Shortcut_to_SDS_PSVC_ORDER_PRODUCT_SPECIAL_C_PRE___OWNER_ID as OWNER_ID",
	"SQ_Shortcut_to_SDS_PSVC_ORDER_PRODUCT_SPECIAL_C_PRE___IS_DELETED as IS_DELETED",
	"SQ_Shortcut_to_SDS_PSVC_ORDER_PRODUCT_SPECIAL_C_PRE___NAME as NAME",
	"SQ_Shortcut_to_SDS_PSVC_ORDER_PRODUCT_SPECIAL_C_PRE___CURRENCY_ISO_CODE as CURRENCY_ISO_CODE",
	"SQ_Shortcut_to_SDS_PSVC_ORDER_PRODUCT_SPECIAL_C_PRE___CREATED_DATE as CREATED_DATE",
	"SQ_Shortcut_to_SDS_PSVC_ORDER_PRODUCT_SPECIAL_C_PRE___CREATED_BY_ID as CREATED_BY_ID",
	"SQ_Shortcut_to_SDS_PSVC_ORDER_PRODUCT_SPECIAL_C_PRE___LAST_MODIFIED_DATE as LAST_MODIFIED_DATE",
	"SQ_Shortcut_to_SDS_PSVC_ORDER_PRODUCT_SPECIAL_C_PRE___LAST_MODIFIED_BY_ID as LAST_MODIFIED_BY_ID",
	"SQ_Shortcut_to_SDS_PSVC_ORDER_PRODUCT_SPECIAL_C_PRE___SYSTEM_MOD_STAMP as SYSTEM_MOD_STAMP",
	"SQ_Shortcut_to_SDS_PSVC_ORDER_PRODUCT_SPECIAL_C_PRE___PSVC_SPECIAL_C as PSVC_SPECIAL_C",
	"SQ_Shortcut_to_SDS_PSVC_ORDER_PRODUCT_SPECIAL_C_PRE___PSVC_ADJUSTMENT_AMOUNT_C as PSVC_ADJUSTMENT_AMOUNT_C",
	"SQ_Shortcut_to_SDS_PSVC_ORDER_PRODUCT_SPECIAL_C_PRE___PSVC_ADJUSTMENT_PERCENTAGE_C as PSVC_ADJUSTMENT_PERCENTAGE_C",
	"SQ_Shortcut_to_SDS_PSVC_ORDER_PRODUCT_SPECIAL_C_PRE___PSVC_HIDE_FROM_CUSTOMER_ONLINE_INVOICE_C as PSVC_HIDE_FROM_CUSTOMER_ONLINE_INVOICE_C",
	"SQ_Shortcut_to_SDS_PSVC_ORDER_PRODUCT_SPECIAL_C_PRE___PSVC_IS_FOR_QUOTE_C as PSVC_IS_FOR_QUOTE_C",
	"SQ_Shortcut_to_SDS_PSVC_ORDER_PRODUCT_SPECIAL_C_PRE___PSVC_MANUALLY_ENTERED_CODE_C as PSVC_MANUALLY_ENTERED_CODE_C",
	"SQ_Shortcut_to_SDS_PSVC_ORDER_PRODUCT_SPECIAL_C_PRE___PSVC_ORDER_PRODUCT_C as PSVC_ORDER_PRODUCT_C",
	"SQ_Shortcut_to_SDS_PSVC_ORDER_PRODUCT_SPECIAL_C_PRE___PSVC_PREMIUM_DISCOUNT_C as PSVC_PREMIUM_DISCOUNT_C",
	"SQ_Shortcut_to_SDS_PSVC_ORDER_PRODUCT_SPECIAL_C_PRE___PSVC_SPECIAL_CODE_C as PSVC_SPECIAL_CODE_C",
	"SQ_Shortcut_to_SDS_PSVC_ORDER_PRODUCT_SPECIAL_C_PRE___PSVC_APPLY_TO_ALL_PRODUCTS_C as PSVC_APPLY_TO_ALL_PRODUCTS_C",
	"SQ_Shortcut_to_SDS_PSVC_ORDER_PRODUCT_SPECIAL_C_PRE___PSVC_DUPLICATION_C as PSVC_DUPLICATION_C",
	"SQ_Shortcut_to_SDS_PSVC_ORDER_PRODUCT_SPECIAL_C_PRE___PSVC_AUTO_CALCULATED_PRICE_C as PSVC_AUTO_CALCULATED_PRICE_C",
	"SQ_Shortcut_to_SDS_PSVC_ORDER_PRODUCT_SPECIAL_C_PRE___PSVC_MANUAL_C as PSVC_MANUAL_C",
	"SQ_Shortcut_to_SDS_PSVC_ORDER_PRODUCT_SPECIAL_C_PRE___LOAD_TSTMP as LOAD_TSTMP",
	"SQ_Shortcut_to_SDS_PSVC_ORDER_PRODUCT_SPECIAL_C_PRE___PSVC_DISCOUNT_APPLIED_FOR_PERCENTAGE_COU_C as PSVC_DISCOUNT_APPLIED_FOR_PERCENTAGE_COU_C",
	"SQ_Shortcut_to_SDS_PSVC_ORDER_PRODUCT_SPECIAL_C_PRE___PSVC_EVALUATION_ORDER_C as PSVC_EVALUATION_ORDER_C")

# COMMAND ----------
# Processing node FIL_SDS_ORDER_PRODUCT_SPECIAL, type FILTER 
# COLUMN COUNT: 53

# for each involved DataFrame, append the dataframe name to each column
JNR_SDS_ORDER_PRODUCT_SPECIAL_temp = JNR_SDS_ORDER_PRODUCT_SPECIAL.toDF(*["JNR_SDS_ORDER_PRODUCT_SPECIAL___" + col for col in JNR_SDS_ORDER_PRODUCT_SPECIAL.columns])

FIL_SDS_ORDER_PRODUCT_SPECIAL = JNR_SDS_ORDER_PRODUCT_SPECIAL_temp.selectExpr(
	"JNR_SDS_ORDER_PRODUCT_SPECIAL___i_SDS_ORDER_PRODUCT_SPECIAL_ID as i_SDS_ORDER_PRODUCT_SPECIAL_ID",
	"JNR_SDS_ORDER_PRODUCT_SPECIAL___i_SDS_ORDER_PRODUCT_SPECIAL_NAME as i_SDS_ORDER_PRODUCT_SPECIAL_NAME",
	"JNR_SDS_ORDER_PRODUCT_SPECIAL___i_SDS_ORDER_ITEM_ID as i_SDS_ORDER_ITEM_ID",
	"JNR_SDS_ORDER_PRODUCT_SPECIAL___i_SDS_SPECIAL_ID as i_SDS_SPECIAL_ID",
	"JNR_SDS_ORDER_PRODUCT_SPECIAL___i_SDS_SPECIAL_CD as i_SDS_SPECIAL_CD",
	"JNR_SDS_ORDER_PRODUCT_SPECIAL___i_MANUALLY_ENTERED_CD as i_MANUALLY_ENTERED_CD",
	"JNR_SDS_ORDER_PRODUCT_SPECIAL___i_PREMIUM_DISCOUNT as i_PREMIUM_DISCOUNT",
	"JNR_SDS_ORDER_PRODUCT_SPECIAL___i_ADJUSTMENT_AMT as i_ADJUSTMENT_AMT",
	"JNR_SDS_ORDER_PRODUCT_SPECIAL___i_ADJUSTMENT_PCT as i_ADJUSTMENT_PCT",
	"JNR_SDS_ORDER_PRODUCT_SPECIAL___i_APPLIED_PCT_DISCOUNT_AMT as i_APPLIED_PCT_DISCOUNT_AMT",
	"JNR_SDS_ORDER_PRODUCT_SPECIAL___i_EVALUATION_ORDER_NBR as i_EVALUATION_ORDER_NBR",
	"JNR_SDS_ORDER_PRODUCT_SPECIAL___i_AUTO_CALCULATED_PRICE as i_AUTO_CALCULATED_PRICE",
	"JNR_SDS_ORDER_PRODUCT_SPECIAL___i_MANUAL_ADJUSTED_FLAG as i_MANUAL_ADJUSTED_FLAG",
	"JNR_SDS_ORDER_PRODUCT_SPECIAL___i_HIDE_FROM_CUSTOMER_ONLINE_INVOICE_FLAG as i_HIDE_FROM_CUSTOMER_ONLINE_INVOICE_FLAG",
	"JNR_SDS_ORDER_PRODUCT_SPECIAL___i_APPLY_TO_ALL_PRODUCTS_FLAG as i_APPLY_TO_ALL_PRODUCTS_FLAG",
	"JNR_SDS_ORDER_PRODUCT_SPECIAL___i_DUPLICATION as i_DUPLICATION",
	"JNR_SDS_ORDER_PRODUCT_SPECIAL___i_FOR_QUOTE_FLAG as i_FOR_QUOTE_FLAG",
	"JNR_SDS_ORDER_PRODUCT_SPECIAL___i_SDS_OWNER_ID as i_SDS_OWNER_ID",
	"JNR_SDS_ORDER_PRODUCT_SPECIAL___i_CURRENCY_ISO_CD as i_CURRENCY_ISO_CD",
	"JNR_SDS_ORDER_PRODUCT_SPECIAL___i_DELETED_FLAG as i_DELETED_FLAG",
	"JNR_SDS_ORDER_PRODUCT_SPECIAL___i_HARD_DELETED_FLAG as i_HARD_DELETED_FLAG",
	"JNR_SDS_ORDER_PRODUCT_SPECIAL___i_SDS_SYSTEM_MODIFIED_TSTMP as i_SDS_SYSTEM_MODIFIED_TSTMP",
	"JNR_SDS_ORDER_PRODUCT_SPECIAL___i_SDS_LAST_MODIFIED_TSTMP as i_SDS_LAST_MODIFIED_TSTMP",
	"JNR_SDS_ORDER_PRODUCT_SPECIAL___i_SDS_LAST_MODIFIED_BY_ID as i_SDS_LAST_MODIFIED_BY_ID",
	"JNR_SDS_ORDER_PRODUCT_SPECIAL___i_SDS_CREATED_TSTMP as i_SDS_CREATED_TSTMP",
	"JNR_SDS_ORDER_PRODUCT_SPECIAL___i_SDS_CREATED_BY_ID as i_SDS_CREATED_BY_ID",
	"JNR_SDS_ORDER_PRODUCT_SPECIAL___i_UPDATE_TSTMP as i_UPDATE_TSTMP",
	"JNR_SDS_ORDER_PRODUCT_SPECIAL___i_LOAD_TSTMP as i_LOAD_TSTMP",
	"JNR_SDS_ORDER_PRODUCT_SPECIAL___ID as ID",
	"JNR_SDS_ORDER_PRODUCT_SPECIAL___OWNER_ID as OWNER_ID",
	"JNR_SDS_ORDER_PRODUCT_SPECIAL___IS_DELETED as IS_DELETED",
	"JNR_SDS_ORDER_PRODUCT_SPECIAL___NAME as NAME",
	"JNR_SDS_ORDER_PRODUCT_SPECIAL___CURRENCY_ISO_CODE as CURRENCY_ISO_CODE",
	"JNR_SDS_ORDER_PRODUCT_SPECIAL___CREATED_DATE as CREATED_DATE",
	"JNR_SDS_ORDER_PRODUCT_SPECIAL___CREATED_BY_ID as CREATED_BY_ID",
	"JNR_SDS_ORDER_PRODUCT_SPECIAL___LAST_MODIFIED_DATE as LAST_MODIFIED_DATE",
	"JNR_SDS_ORDER_PRODUCT_SPECIAL___LAST_MODIFIED_BY_ID as LAST_MODIFIED_BY_ID",
	"JNR_SDS_ORDER_PRODUCT_SPECIAL___SYSTEM_MOD_STAMP as SYSTEM_MOD_STAMP",
	"JNR_SDS_ORDER_PRODUCT_SPECIAL___PSVC_SPECIAL_C as PSVC_SPECIAL_C",
	"JNR_SDS_ORDER_PRODUCT_SPECIAL___PSVC_ADJUSTMENT_AMOUNT_C as PSVC_ADJUSTMENT_AMOUNT_C",
	"JNR_SDS_ORDER_PRODUCT_SPECIAL___PSVC_ADJUSTMENT_PERCENTAGE_C as PSVC_ADJUSTMENT_PERCENTAGE_C",
	"JNR_SDS_ORDER_PRODUCT_SPECIAL___PSVC_HIDE_FROM_CUSTOMER_ONLINE_INVOICE_C as PSVC_HIDE_FROM_CUSTOMER_ONLINE_INVOICE_C",
	"JNR_SDS_ORDER_PRODUCT_SPECIAL___PSVC_IS_FOR_QUOTE_C as PSVC_IS_FOR_QUOTE_C",
	"JNR_SDS_ORDER_PRODUCT_SPECIAL___PSVC_MANUALLY_ENTERED_CODE_C as PSVC_MANUALLY_ENTERED_CODE_C",
	"JNR_SDS_ORDER_PRODUCT_SPECIAL___PSVC_ORDER_PRODUCT_C as PSVC_ORDER_PRODUCT_C",
	"JNR_SDS_ORDER_PRODUCT_SPECIAL___PSVC_PREMIUM_DISCOUNT_C as PSVC_PREMIUM_DISCOUNT_C",
	"JNR_SDS_ORDER_PRODUCT_SPECIAL___PSVC_SPECIAL_CODE_C as PSVC_SPECIAL_CODE_C",
	"JNR_SDS_ORDER_PRODUCT_SPECIAL___PSVC_APPLY_TO_ALL_PRODUCTS_C as PSVC_APPLY_TO_ALL_PRODUCTS_C",
	"JNR_SDS_ORDER_PRODUCT_SPECIAL___PSVC_DUPLICATION_C as PSVC_DUPLICATION_C",
	"JNR_SDS_ORDER_PRODUCT_SPECIAL___PSVC_AUTO_CALCULATED_PRICE_C as PSVC_AUTO_CALCULATED_PRICE_C",
	"JNR_SDS_ORDER_PRODUCT_SPECIAL___PSVC_MANUAL_C as PSVC_MANUAL_C",
	"JNR_SDS_ORDER_PRODUCT_SPECIAL___PSVC_DISCOUNT_APPLIED_FOR_PERCENTAGE_COU_C as PSVC_DISCOUNT_APPLIED_FOR_PERCENTAGE_COU_C",
	"JNR_SDS_ORDER_PRODUCT_SPECIAL___PSVC_EVALUATION_ORDER_C as PSVC_EVALUATION_ORDER_C").filter("i_SDS_ORDER_PRODUCT_SPECIAL_ID IS NULL OR ( i_SDS_ORDER_PRODUCT_SPECIAL_ID IS NOT NULL AND ( i_SDS_SYSTEM_MODIFIED_TSTMP != SYSTEM_MOD_STAMP OR i_SDS_CREATED_TSTMP != CREATED_DATE OR i_SDS_LAST_MODIFIED_TSTMP != LAST_MODIFIED_DATE OR IF (OWNER_ID IS NULL, ' ', OWNER_ID) != IF (i_SDS_OWNER_ID IS NULL, ' ', i_SDS_OWNER_ID) OR IF (IS_DELETED IS NULL, - 99999, IS_DELETED) != IF (i_DELETED_FLAG IS NULL, - 99999, i_DELETED_FLAG) OR IF (NAME IS NULL, ' ', NAME) != IF (i_SDS_ORDER_PRODUCT_SPECIAL_NAME IS NULL, ' ', i_SDS_ORDER_PRODUCT_SPECIAL_NAME) OR IF (CURRENCY_ISO_CODE IS NULL, ' ', CURRENCY_ISO_CODE) != IF (i_CURRENCY_ISO_CD IS NULL, ' ', i_CURRENCY_ISO_CD) OR IF (CREATED_BY_ID IS NULL, ' ', CREATED_BY_ID) != IF (i_SDS_CREATED_BY_ID IS NULL, ' ', i_SDS_CREATED_BY_ID) OR IF (LAST_MODIFIED_BY_ID IS NULL, ' ', LAST_MODIFIED_BY_ID) != IF (i_SDS_LAST_MODIFIED_BY_ID IS NULL, ' ', i_SDS_LAST_MODIFIED_BY_ID) OR IF (PSVC_SPECIAL_C IS NULL, ' ', PSVC_SPECIAL_C) != IF (i_SDS_SPECIAL_ID IS NULL, ' ', i_SDS_SPECIAL_ID) OR IF (PSVC_ADJUSTMENT_AMOUNT_C IS NULL, - 99999, PSVC_ADJUSTMENT_AMOUNT_C) != IF (i_ADJUSTMENT_AMT IS NULL, - 99999, i_ADJUSTMENT_AMT) OR IF (PSVC_ADJUSTMENT_PERCENTAGE_C IS NULL, - 99999, PSVC_ADJUSTMENT_PERCENTAGE_C) != IF (i_ADJUSTMENT_PCT IS NULL, - 99999, i_ADJUSTMENT_PCT) OR IF (PSVC_DISCOUNT_APPLIED_FOR_PERCENTAGE_COU_C IS NULL, - 99999, PSVC_DISCOUNT_APPLIED_FOR_PERCENTAGE_COU_C) != IF (i_APPLIED_PCT_DISCOUNT_AMT IS NULL, - 99999, i_APPLIED_PCT_DISCOUNT_AMT) OR IF (PSVC_EVALUATION_ORDER_C IS NULL, - 99999, PSVC_EVALUATION_ORDER_C) != IF (i_EVALUATION_ORDER_NBR IS NULL, - 99999, i_EVALUATION_ORDER_NBR) OR IF (PSVC_HIDE_FROM_CUSTOMER_ONLINE_INVOICE_C IS NULL, - 99999, PSVC_HIDE_FROM_CUSTOMER_ONLINE_INVOICE_C) != IF (i_HIDE_FROM_CUSTOMER_ONLINE_INVOICE_FLAG IS NULL, - 99999, i_HIDE_FROM_CUSTOMER_ONLINE_INVOICE_FLAG) OR IF (PSVC_IS_FOR_QUOTE_C IS NULL, - 99999, PSVC_IS_FOR_QUOTE_C) != IF (i_FOR_QUOTE_FLAG IS NULL, - 99999, i_FOR_QUOTE_FLAG) OR IF (PSVC_MANUALLY_ENTERED_CODE_C IS NULL, ' ', PSVC_MANUALLY_ENTERED_CODE_C) != IF (i_MANUALLY_ENTERED_CD IS NULL, ' ', i_MANUALLY_ENTERED_CD) OR IF (PSVC_ORDER_PRODUCT_C IS NULL, ' ', PSVC_ORDER_PRODUCT_C) != IF (i_SDS_ORDER_ITEM_ID IS NULL, ' ', i_SDS_ORDER_ITEM_ID) OR IF (PSVC_PREMIUM_DISCOUNT_C IS NULL, ' ', PSVC_PREMIUM_DISCOUNT_C) != IF (i_PREMIUM_DISCOUNT IS NULL, ' ', i_PREMIUM_DISCOUNT) OR IF (PSVC_SPECIAL_CODE_C IS NULL, ' ', PSVC_SPECIAL_CODE_C) != IF (i_SDS_SPECIAL_CD IS NULL, ' ', i_SDS_SPECIAL_CD) OR IF (PSVC_APPLY_TO_ALL_PRODUCTS_C IS NULL, - 99999, PSVC_APPLY_TO_ALL_PRODUCTS_C) != IF (i_APPLY_TO_ALL_PRODUCTS_FLAG IS NULL, - 99999, i_APPLY_TO_ALL_PRODUCTS_FLAG) OR IF (PSVC_DUPLICATION_C IS NULL, ' ', PSVC_DUPLICATION_C) != IF (i_DUPLICATION IS NULL, ' ', i_DUPLICATION) OR IF (PSVC_AUTO_CALCULATED_PRICE_C IS NULL, - 99999, PSVC_AUTO_CALCULATED_PRICE_C) != IF (i_AUTO_CALCULATED_PRICE IS NULL, - 99999, i_AUTO_CALCULATED_PRICE) OR IF (PSVC_MANUAL_C IS NULL, - 99999, PSVC_MANUAL_C) != IF (i_MANUAL_ADJUSTED_FLAG IS NULL, - 99999, i_MANUAL_ADJUSTED_FLAG) ) )").withColumn("sys_row_id", monotonically_increasing_id())

# COMMAND ----------
# Processing node EXP_SDS_ORDER_PRODUCT_SPECIAL, type EXPRESSION 
# COLUMN COUNT: 29

# for each involved DataFrame, append the dataframe name to each column
FIL_SDS_ORDER_PRODUCT_SPECIAL_temp = FIL_SDS_ORDER_PRODUCT_SPECIAL.toDF(*["FIL_SDS_ORDER_PRODUCT_SPECIAL___" + col for col in FIL_SDS_ORDER_PRODUCT_SPECIAL.columns])

EXP_SDS_ORDER_PRODUCT_SPECIAL = FIL_SDS_ORDER_PRODUCT_SPECIAL_temp.selectExpr(
	"FIL_SDS_ORDER_PRODUCT_SPECIAL___sys_row_id as sys_row_id",
	"FIL_SDS_ORDER_PRODUCT_SPECIAL___ID as ID",
	"FIL_SDS_ORDER_PRODUCT_SPECIAL___OWNER_ID as OWNER_ID",
	"FIL_SDS_ORDER_PRODUCT_SPECIAL___IS_DELETED as IS_DELETED",
	"FIL_SDS_ORDER_PRODUCT_SPECIAL___NAME as NAME",
	"FIL_SDS_ORDER_PRODUCT_SPECIAL___CURRENCY_ISO_CODE as CURRENCY_ISO_CODE",
	"FIL_SDS_ORDER_PRODUCT_SPECIAL___CREATED_DATE as CREATED_DATE",
	"FIL_SDS_ORDER_PRODUCT_SPECIAL___CREATED_BY_ID as CREATED_BY_ID",
	"FIL_SDS_ORDER_PRODUCT_SPECIAL___LAST_MODIFIED_DATE as LAST_MODIFIED_DATE",
	"FIL_SDS_ORDER_PRODUCT_SPECIAL___LAST_MODIFIED_BY_ID as LAST_MODIFIED_BY_ID",
	"FIL_SDS_ORDER_PRODUCT_SPECIAL___SYSTEM_MOD_STAMP as SYSTEM_MOD_STAMP",
	"FIL_SDS_ORDER_PRODUCT_SPECIAL___PSVC_SPECIAL_C as PSVC_SPECIAL_C",
	"FIL_SDS_ORDER_PRODUCT_SPECIAL___PSVC_ADJUSTMENT_AMOUNT_C as PSVC_ADJUSTMENT_AMOUNT_C",
	"FIL_SDS_ORDER_PRODUCT_SPECIAL___PSVC_ADJUSTMENT_PERCENTAGE_C as PSVC_ADJUSTMENT_PERCENTAGE_C",
	"FIL_SDS_ORDER_PRODUCT_SPECIAL___PSVC_HIDE_FROM_CUSTOMER_ONLINE_INVOICE_C as PSVC_HIDE_FROM_CUSTOMER_ONLINE_INVOICE_C",
	"FIL_SDS_ORDER_PRODUCT_SPECIAL___PSVC_IS_FOR_QUOTE_C as PSVC_IS_FOR_QUOTE_C",
	"FIL_SDS_ORDER_PRODUCT_SPECIAL___PSVC_MANUALLY_ENTERED_CODE_C as PSVC_MANUALLY_ENTERED_CODE_C",
	"FIL_SDS_ORDER_PRODUCT_SPECIAL___PSVC_ORDER_PRODUCT_C as PSVC_ORDER_PRODUCT_C",
	"FIL_SDS_ORDER_PRODUCT_SPECIAL___PSVC_PREMIUM_DISCOUNT_C as PSVC_PREMIUM_DISCOUNT_C",
	"FIL_SDS_ORDER_PRODUCT_SPECIAL___PSVC_SPECIAL_CODE_C as PSVC_SPECIAL_CODE_C",
	"FIL_SDS_ORDER_PRODUCT_SPECIAL___PSVC_APPLY_TO_ALL_PRODUCTS_C as PSVC_APPLY_TO_ALL_PRODUCTS_C",
	"FIL_SDS_ORDER_PRODUCT_SPECIAL___PSVC_DUPLICATION_C as PSVC_DUPLICATION_C",
	"FIL_SDS_ORDER_PRODUCT_SPECIAL___PSVC_AUTO_CALCULATED_PRICE_C as PSVC_AUTO_CALCULATED_PRICE_C",
	"FIL_SDS_ORDER_PRODUCT_SPECIAL___PSVC_MANUAL_C as PSVC_MANUAL_C",
	"FIL_SDS_ORDER_PRODUCT_SPECIAL___PSVC_DISCOUNT_APPLIED_FOR_PERCENTAGE_COU_C as PSVC_DISCOUNT_APPLIED_FOR_PERCENTAGE_COU_C",
	"FIL_SDS_ORDER_PRODUCT_SPECIAL___PSVC_EVALUATION_ORDER_C as PSVC_EVALUATION_ORDER_C",
	"0 as HARD_DELETED_FLAG",
	"CURRENT_TIMESTAMP as UPDATE_TSTMP",
	"IF (FIL_SDS_ORDER_PRODUCT_SPECIAL___i_LOAD_TSTMP IS NULL, CURRENT_TIMESTAMP, FIL_SDS_ORDER_PRODUCT_SPECIAL___i_LOAD_TSTMP) as LOAD_TSTMP",
	"IF (FIL_SDS_ORDER_PRODUCT_SPECIAL___i_SDS_ORDER_PRODUCT_SPECIAL_ID IS NULL, 1, 2) as o_UPDATE_VALIDATOR"
)

# COMMAND ----------
# Processing node UPD_SDS_ORDER_PRODUCT_SPECIAL, type UPDATE_STRATEGY 
# COLUMN COUNT: 29

# for each involved DataFrame, append the dataframe name to each column
EXP_SDS_ORDER_PRODUCT_SPECIAL_temp = EXP_SDS_ORDER_PRODUCT_SPECIAL.toDF(*["EXP_SDS_ORDER_PRODUCT_SPECIAL___" + col for col in EXP_SDS_ORDER_PRODUCT_SPECIAL.columns])

UPD_SDS_ORDER_PRODUCT_SPECIAL = EXP_SDS_ORDER_PRODUCT_SPECIAL_temp.selectExpr(
	"EXP_SDS_ORDER_PRODUCT_SPECIAL___ID as ID",
	"EXP_SDS_ORDER_PRODUCT_SPECIAL___OWNER_ID as OWNER_ID",
	"EXP_SDS_ORDER_PRODUCT_SPECIAL___IS_DELETED as IS_DELETED",
	"EXP_SDS_ORDER_PRODUCT_SPECIAL___NAME as NAME",
	"EXP_SDS_ORDER_PRODUCT_SPECIAL___CURRENCY_ISO_CODE as CURRENCY_ISO_CODE",
	"EXP_SDS_ORDER_PRODUCT_SPECIAL___CREATED_DATE as CREATED_DATE",
	"EXP_SDS_ORDER_PRODUCT_SPECIAL___CREATED_BY_ID as CREATED_BY_ID",
	"EXP_SDS_ORDER_PRODUCT_SPECIAL___LAST_MODIFIED_DATE as LAST_MODIFIED_DATE",
	"EXP_SDS_ORDER_PRODUCT_SPECIAL___LAST_MODIFIED_BY_ID as LAST_MODIFIED_BY_ID",
	"EXP_SDS_ORDER_PRODUCT_SPECIAL___SYSTEM_MOD_STAMP as SYSTEM_MOD_STAMP",
	"EXP_SDS_ORDER_PRODUCT_SPECIAL___PSVC_SPECIAL_C as PSVC_SPECIAL_C",
	"EXP_SDS_ORDER_PRODUCT_SPECIAL___PSVC_ADJUSTMENT_AMOUNT_C as PSVC_ADJUSTMENT_AMOUNT_C",
	"EXP_SDS_ORDER_PRODUCT_SPECIAL___PSVC_ADJUSTMENT_PERCENTAGE_C as PSVC_ADJUSTMENT_PERCENTAGE_C",
	"EXP_SDS_ORDER_PRODUCT_SPECIAL___PSVC_HIDE_FROM_CUSTOMER_ONLINE_INVOICE_C as PSVC_HIDE_FROM_CUSTOMER_ONLINE_INVOICE_C",
	"EXP_SDS_ORDER_PRODUCT_SPECIAL___PSVC_IS_FOR_QUOTE_C as PSVC_IS_FOR_QUOTE_C",
	"EXP_SDS_ORDER_PRODUCT_SPECIAL___PSVC_MANUALLY_ENTERED_CODE_C as PSVC_MANUALLY_ENTERED_CODE_C",
	"EXP_SDS_ORDER_PRODUCT_SPECIAL___PSVC_ORDER_PRODUCT_C as PSVC_ORDER_PRODUCT_C",
	"EXP_SDS_ORDER_PRODUCT_SPECIAL___PSVC_PREMIUM_DISCOUNT_C as PSVC_PREMIUM_DISCOUNT_C",
	"EXP_SDS_ORDER_PRODUCT_SPECIAL___PSVC_SPECIAL_CODE_C as PSVC_SPECIAL_CODE_C",
	"EXP_SDS_ORDER_PRODUCT_SPECIAL___PSVC_APPLY_TO_ALL_PRODUCTS_C as PSVC_APPLY_TO_ALL_PRODUCTS_C",
	"EXP_SDS_ORDER_PRODUCT_SPECIAL___PSVC_DUPLICATION_C as PSVC_DUPLICATION_C",
	"EXP_SDS_ORDER_PRODUCT_SPECIAL___PSVC_AUTO_CALCULATED_PRICE_C as PSVC_AUTO_CALCULATED_PRICE_C",
	"EXP_SDS_ORDER_PRODUCT_SPECIAL___PSVC_MANUAL_C as PSVC_MANUAL_C",
	"EXP_SDS_ORDER_PRODUCT_SPECIAL___PSVC_DISCOUNT_APPLIED_FOR_PERCENTAGE_COU_C as PSVC_DISCOUNT_APPLIED_FOR_PERCENTAGE_COU_C",
	"EXP_SDS_ORDER_PRODUCT_SPECIAL___PSVC_EVALUATION_ORDER_C as PSVC_EVALUATION_ORDER_C",
	"EXP_SDS_ORDER_PRODUCT_SPECIAL___HARD_DELETED_FLAG as HARD_DELETED_FLAG",
	"EXP_SDS_ORDER_PRODUCT_SPECIAL___UPDATE_TSTMP as UPDATE_TSTMP",
	"EXP_SDS_ORDER_PRODUCT_SPECIAL___LOAD_TSTMP as LOAD_TSTMP",
	"EXP_SDS_ORDER_PRODUCT_SPECIAL___o_UPDATE_VALIDATOR as o_UPDATE_VALIDATOR")\
	.withColumn('pyspark_data_action', when(col('o_UPDATE_VALIDATOR') ==(lit(1)) , lit(0)).when(col('o_UPDATE_VALIDATOR') ==(lit(2)) , lit(1)))

# COMMAND ----------
# Processing node Shortcut_to_SDS_ORDER_PRODUCT_SPECIAL_2, type TARGET 
# COLUMN COUNT: 28


Shortcut_to_SDS_ORDER_PRODUCT_SPECIAL_2 = UPD_SDS_ORDER_PRODUCT_SPECIAL.selectExpr(
	"CAST(ID AS STRING) as SDS_ORDER_PRODUCT_SPECIAL_ID",
	"CAST(NAME AS STRING) as SDS_ORDER_PRODUCT_SPECIAL_NAME",
	"CAST(PSVC_ORDER_PRODUCT_C AS STRING) as SDS_ORDER_ITEM_ID",
	"CAST(PSVC_SPECIAL_C AS STRING) as SDS_SPECIAL_ID",
	"CAST(PSVC_SPECIAL_CODE_C AS STRING) as SDS_SPECIAL_CD",
	"CAST(PSVC_MANUALLY_ENTERED_CODE_C AS STRING) as MANUALLY_ENTERED_CD",
	"CAST(PSVC_PREMIUM_DISCOUNT_C AS STRING) as PREMIUM_DISCOUNT",
	"CAST(PSVC_ADJUSTMENT_AMOUNT_C AS DECIMAL(18,3)) as ADJUSTMENT_AMT",
	"CAST(PSVC_ADJUSTMENT_PERCENTAGE_C AS DECIMAL(18,3)) as ADJUSTMENT_PCT",
	"CAST(PSVC_DISCOUNT_APPLIED_FOR_PERCENTAGE_COU_C AS DECIMAL(18,3)) as APPLIED_PCT_DISCOUNT_AMT",
	"CAST(PSVC_EVALUATION_ORDER_C AS TINYINT) as EVALUATION_ORDER_NBR",
	"CAST(PSVC_AUTO_CALCULATED_PRICE_C AS DECIMAL(18,2)) as AUTO_CALCULATED_PRICE",
	"CAST(PSVC_MANUAL_C AS TINYINT) as MANUAL_ADJUSTED_FLAG",
	"CAST(PSVC_HIDE_FROM_CUSTOMER_ONLINE_INVOICE_C AS TINYINT) as HIDE_FROM_CUSTOMER_ONLINE_INVOICE_FLAG",
	"CAST(PSVC_APPLY_TO_ALL_PRODUCTS_C AS TINYINT) as APPLY_TO_ALL_PRODUCTS_FLAG",
	"CAST(PSVC_DUPLICATION_C AS STRING) as DUPLICATION",
	"CAST(PSVC_IS_FOR_QUOTE_C AS TINYINT) as FOR_QUOTE_FLAG",
	"CAST(OWNER_ID AS STRING) as SDS_OWNER_ID",
	"CAST(CURRENCY_ISO_CODE AS STRING) as CURRENCY_ISO_CD",
	"CAST(IS_DELETED AS TINYINT) as DELETED_FLAG",
	"CAST(HARD_DELETED_FLAG AS TINYINT) as HARD_DELETED_FLAG",
	"CAST(SYSTEM_MOD_STAMP AS TIMESTAMP) as SDS_SYSTEM_MODIFIED_TSTMP",
	"CAST(LAST_MODIFIED_DATE AS TIMESTAMP) as SDS_LAST_MODIFIED_TSTMP",
	"CAST(LAST_MODIFIED_BY_ID AS STRING) as SDS_LAST_MODIFIED_BY_ID",
	"CAST(CREATED_DATE AS TIMESTAMP) as SDS_CREATED_TSTMP",
	"CAST(CREATED_BY_ID AS STRING) as SDS_CREATED_BY_ID",
	"CAST(UPDATE_TSTMP AS TIMESTAMP) as UPDATE_TSTMP",
	"CAST(LOAD_TSTMP AS TIMESTAMP) as LOAD_TSTMP",
	"UPD_SDS_ORDER_PRODUCT_SPECIAL.pyspark_data_action as pyspark_data_action"
)

try:
  primary_key = """source.SDS_ORDER_PRODUCT_SPECIAL_ID = target.SDS_ORDER_PRODUCT_SPECIAL_ID"""
  refined_perf_table = f"{legacy}.SDS_ORDER_PRODUCT_SPECIAL"
  executeMerge(Shortcut_to_SDS_ORDER_PRODUCT_SPECIAL_2, refined_perf_table, primary_key)
  logger.info(f"Merge with {refined_perf_table} completed]")
  logPrevRunDt("SDS_ORDER_PRODUCT_SPECIAL", "SDS_ORDER_PRODUCT_SPECIAL", "Completed", "N/A", f"{raw}.log_run_details")
except Exception as e:
  logPrevRunDt("SDS_ORDER_PRODUCT_SPECIAL", "SDS_ORDER_PRODUCT_SPECIAL","Failed",str(e), f"{raw}.log_run_details", )
  raise e
	