#Code converted on 2023-07-24 08:24:10
import os
import argparse
from pyspark.sql import *
from pyspark.sql.functions import *
from pyspark.sql.window import Window
from pyspark.sql.types import *
from datetime import datetime
from Datalake.utils.genericUtilities import *
from Datalake.utils.configs import *
from Datalake.utils.mergeUtils import *
from Datalake.utils.logger import *
# COMMAND ----------

parser = argparse.ArgumentParser()
spark = SparkSession.getActiveSession()
parser.add_argument('env', type=str, help='Env Variable')
args = parser.parse_args()
env = args.env

if env is None or env == '':
    raise ValueError('env is not set')

refine = getEnvPrefix(env) + 'refine'
raw = getEnvPrefix(env) + 'raw'
legacy = getEnvPrefix(env) + 'legacy'


# COMMAND ----------
# Processing node SQ_Shortcut_to_SDS_ORDER_ITEM_PRE, type SOURCE 
# COLUMN COUNT: 46

SQ_Shortcut_to_SDS_ORDER_ITEM_PRE = spark.sql(f"""SELECT
ID,
PRODUCT2_ID,
IS_DELETED,
ORDER_ID,
PRICE_BOOK_ENTRY_ID,
ORIGINAL_ORDER_ITEM_ID,
QUOTE_LINE_ITEM_ID,
AVAILABLE_QUANTITY,
QUANTITY,
CURRENCY_ISO_CODE,
UNIT_PRICE,
LIST_PRICE,
TOTAL_PRICE,
SERVICE_DATE,
END_DATE,
DESCRIPTION,
CREATED_DATE,
CREATED_BY_ID,
LAST_MODIFIED_DATE,
LAST_MODIFIED_BY_ID,
SYSTEM_MOD_STAMP,
ORDER_ITEM_NUMBER,
PSVC_COMMISSION_AMOUNT_C,
PSVC_IS_FOR_QUOTE_C,
PSVC_PRICE_MANUAL_ADJUSTMENT_REASON_C,
PSVC_WORK_ORDER_C,
PSVC_AUTO_CALCULATED_PRICE_C,
PSVC_DUPLICATION_C,
PSVC_MANUAL_ADJUSTED_PRICE_C,
PSVC_APPOINTMENT_DATE_C,
PSVC_ASSOCIATE_C,
PSVC_AUTO_CALCULATED_PRICE_FORMULA_C,
PSVC_IS_HIDDEN_C,
PSVC_CHANGE_COMMISSION_TO_C,
PSVC_CHANGE_TO_COMMISSION_PERCENTAGE_C,
PSVC_COMMISSION_RECEIVER_C,
PSVC_EXPRESS_C,
PSVC_RESOURCE_COMMISSION_C,
PSVC_ORDER_PRODUCT_NUMBER_C,
PSVC_ORDER_PRODUCT_SMS_ID_C,
PSVC_TOTAL_PRICE_FOR_POS_C,
PSVC_UNIT_PRICE_FOR_POS_C,
LINE_ITEM_TOTAL_TAX_C,
PSVC_TOTAL_GROOM_PAY_ELIGIBLE_PRICE_C,
PSVC_ORIGINAL_UNIT_PRICE_C,
PSVC_IS_PREPAID_C
FROM {raw}.SDS_ORDER_ITEM_PRE""").withColumn("sys_row_id", monotonically_increasing_id())

# COMMAND ----------
# Processing node EXP_TOTAL_GROOM_PAY_ELIGIBLE_PRICE_C, type EXPRESSION 
# COLUMN COUNT: 46

# for each involved DataFrame, append the dataframe name to each column
SQ_Shortcut_to_SDS_ORDER_ITEM_PRE_temp = SQ_Shortcut_to_SDS_ORDER_ITEM_PRE.toDF(*["SQ_Shortcut_to_SDS_ORDER_ITEM_PRE___" + col for col in SQ_Shortcut_to_SDS_ORDER_ITEM_PRE.columns])

EXP_TOTAL_GROOM_PAY_ELIGIBLE_PRICE_C = SQ_Shortcut_to_SDS_ORDER_ITEM_PRE_temp.selectExpr(
	"SQ_Shortcut_to_SDS_ORDER_ITEM_PRE___sys_row_id as sys_row_id",
	"SQ_Shortcut_to_SDS_ORDER_ITEM_PRE___ID as ID",
	"SQ_Shortcut_to_SDS_ORDER_ITEM_PRE___PRODUCT2_ID as PRODUCT2_ID",
	"SQ_Shortcut_to_SDS_ORDER_ITEM_PRE___IS_DELETED as IS_DELETED",
	"SQ_Shortcut_to_SDS_ORDER_ITEM_PRE___ORDER_ID as ORDER_ID",
	"SQ_Shortcut_to_SDS_ORDER_ITEM_PRE___PRICE_BOOK_ENTRY_ID as PRICE_BOOK_ENTRY_ID",
	"SQ_Shortcut_to_SDS_ORDER_ITEM_PRE___ORIGINAL_ORDER_ITEM_ID as ORIGINAL_ORDER_ITEM_ID",
	"SQ_Shortcut_to_SDS_ORDER_ITEM_PRE___QUOTE_LINE_ITEM_ID as QUOTE_LINE_ITEM_ID",
	"SQ_Shortcut_to_SDS_ORDER_ITEM_PRE___AVAILABLE_QUANTITY as AVAILABLE_QUANTITY",
	"SQ_Shortcut_to_SDS_ORDER_ITEM_PRE___QUANTITY as QUANTITY",
	"SQ_Shortcut_to_SDS_ORDER_ITEM_PRE___CURRENCY_ISO_CODE as CURRENCY_ISO_CODE",
	"SQ_Shortcut_to_SDS_ORDER_ITEM_PRE___UNIT_PRICE as UNIT_PRICE",
	"SQ_Shortcut_to_SDS_ORDER_ITEM_PRE___LIST_PRICE as LIST_PRICE",
	"SQ_Shortcut_to_SDS_ORDER_ITEM_PRE___TOTAL_PRICE as TOTAL_PRICE",
	"SQ_Shortcut_to_SDS_ORDER_ITEM_PRE___SERVICE_DATE as SERVICE_DATE",
	"SQ_Shortcut_to_SDS_ORDER_ITEM_PRE___END_DATE as END_DATE",
	"SQ_Shortcut_to_SDS_ORDER_ITEM_PRE___DESCRIPTION as DESCRIPTION",
	"SQ_Shortcut_to_SDS_ORDER_ITEM_PRE___CREATED_DATE as CREATED_DATE",
	"SQ_Shortcut_to_SDS_ORDER_ITEM_PRE___CREATED_BY_ID as CREATED_BY_ID",
	"SQ_Shortcut_to_SDS_ORDER_ITEM_PRE___LAST_MODIFIED_DATE as LAST_MODIFIED_DATE",
	"SQ_Shortcut_to_SDS_ORDER_ITEM_PRE___LAST_MODIFIED_BY_ID as LAST_MODIFIED_BY_ID",
	"SQ_Shortcut_to_SDS_ORDER_ITEM_PRE___SYSTEM_MOD_STAMP as SYSTEM_MOD_STAMP",
	"SQ_Shortcut_to_SDS_ORDER_ITEM_PRE___ORDER_ITEM_NUMBER as ORDER_ITEM_NUMBER",
	"SQ_Shortcut_to_SDS_ORDER_ITEM_PRE___PSVC_COMMISSION_AMOUNT_C as PSVC_COMMISSION_AMOUNT_C",
	"SQ_Shortcut_to_SDS_ORDER_ITEM_PRE___PSVC_IS_FOR_QUOTE_C as PSVC_IS_FOR_QUOTE_C",
	"SQ_Shortcut_to_SDS_ORDER_ITEM_PRE___PSVC_PRICE_MANUAL_ADJUSTMENT_REASON_C as PSVC_PRICE_MANUAL_ADJUSTMENT_REASON_C",
	"SQ_Shortcut_to_SDS_ORDER_ITEM_PRE___PSVC_WORK_ORDER_C as PSVC_WORK_ORDER_C",
	"SQ_Shortcut_to_SDS_ORDER_ITEM_PRE___PSVC_AUTO_CALCULATED_PRICE_C as PSVC_AUTO_CALCULATED_PRICE_C",
	"SQ_Shortcut_to_SDS_ORDER_ITEM_PRE___PSVC_DUPLICATION_C as PSVC_DUPLICATION_C",
	"SQ_Shortcut_to_SDS_ORDER_ITEM_PRE___PSVC_MANUAL_ADJUSTED_PRICE_C as PSVC_MANUAL_ADJUSTED_PRICE_C",
	"SQ_Shortcut_to_SDS_ORDER_ITEM_PRE___PSVC_APPOINTMENT_DATE_C as PSVC_APPOINTMENT_DATE_C",
	"SQ_Shortcut_to_SDS_ORDER_ITEM_PRE___PSVC_ASSOCIATE_C as PSVC_ASSOCIATE_C",
	"SQ_Shortcut_to_SDS_ORDER_ITEM_PRE___PSVC_AUTO_CALCULATED_PRICE_FORMULA_C as PSVC_AUTO_CALCULATED_PRICE_FORMULA_C",
	"SQ_Shortcut_to_SDS_ORDER_ITEM_PRE___PSVC_IS_HIDDEN_C as PSVC_IS_HIDDEN_C",
	"SQ_Shortcut_to_SDS_ORDER_ITEM_PRE___PSVC_CHANGE_COMMISSION_TO_C as PSVC_CHANGE_COMMISSION_TO_C",
	"SQ_Shortcut_to_SDS_ORDER_ITEM_PRE___PSVC_CHANGE_TO_COMMISSION_PERCENTAGE_C as PSVC_CHANGE_TO_COMMISSION_PERCENTAGE_C",
	"SQ_Shortcut_to_SDS_ORDER_ITEM_PRE___PSVC_COMMISSION_RECEIVER_C as PSVC_COMMISSION_RECEIVER_C",
	"SQ_Shortcut_to_SDS_ORDER_ITEM_PRE___PSVC_EXPRESS_C as PSVC_EXPRESS_C",
	"SQ_Shortcut_to_SDS_ORDER_ITEM_PRE___PSVC_RESOURCE_COMMISSION_C as PSVC_RESOURCE_COMMISSION_C",
	"SQ_Shortcut_to_SDS_ORDER_ITEM_PRE___PSVC_ORDER_PRODUCT_NUMBER_C as PSVC_ORDER_PRODUCT_NUMBER_C",
	"SQ_Shortcut_to_SDS_ORDER_ITEM_PRE___PSVC_ORDER_PRODUCT_SMS_ID_C as PSVC_ORDER_PRODUCT_SMS_ID_C",
	"SQ_Shortcut_to_SDS_ORDER_ITEM_PRE___PSVC_TOTAL_PRICE_FOR_POS_C as PSVC_TOTAL_PRICE_FOR_POS_C",
	"SQ_Shortcut_to_SDS_ORDER_ITEM_PRE___PSVC_UNIT_PRICE_FOR_POS_C as PSVC_UNIT_PRICE_FOR_POS_C",
	"SQ_Shortcut_to_SDS_ORDER_ITEM_PRE___LINE_ITEM_TOTAL_TAX_C as LINE_ITEM_TOTAL_TAX_C",
	"IF (SQ_Shortcut_to_SDS_ORDER_ITEM_PRE___PSVC_TOTAL_GROOM_PAY_ELIGIBLE_PRICE_C IS NULL, SQ_Shortcut_to_SDS_ORDER_ITEM_PRE___TOTAL_PRICE, SQ_Shortcut_to_SDS_ORDER_ITEM_PRE___PSVC_TOTAL_GROOM_PAY_ELIGIBLE_PRICE_C) as o_PSVC_TOTAL_GROOM_PAY_ELIGIBLE_PRICE_C",
	"SQ_Shortcut_to_SDS_ORDER_ITEM_PRE___PSVC_ORIGINAL_UNIT_PRICE_C as PSVC_ORIGINAL_UNIT_PRICE_C",
	"SQ_Shortcut_to_SDS_ORDER_ITEM_PRE___PSVC_IS_PREPAID_C as PSVC_IS_PREPAID_C"
)

# COMMAND ----------
# Processing node SQ_Shortcut_to_SDS_ORDER_ITEM, type SOURCE 
# COLUMN COUNT: 48

SQ_Shortcut_to_SDS_ORDER_ITEM = spark.sql(f"""SELECT
SDS_ORDER_ITEM_ID,
SDS_ORDER_ITEM_DESC,
SDS_ORDER_ID,
SDS_WORK_ORDER_ID,
SDS_PRODUCT_ID,
SDS_ORDER_ITEM_NBR,
SDS_ORDER_PRODUCT_NBR,
SDS_ORIG_ORDER_ITEM_ID,
SDS_QUOTE_LINE_ITEM_ID,
SDS_PRICEBOOK_ENTRY_ID,
PREPAID_FLAG,
ORDER_ITEM_AVAILABLE_QTY,
ORDER_ITEM_QTY,
UNIT_PRICE,
POS_UNIT_PRICE,
LIST_PRICE,
ORIG_UNIT_PRICE,
MANUAL_ADJUSTED_PRICE,
PRICE_MANUAL_ADJ_REASON,
AUTO_CALCULATED_PRICE,
LINE_ITEM_TOTAL_TAX,
TOTAL_PRICE,
POS_TOTAL_PRICE,
TOTAL_GROOM_PAY_ELIGIBLE_PRICE,
COMMISSION_AMT,
CHANGED_COMMISSION_TO_SERVICE_RESOURCE_ID,
COMMISSION_RECEIVER_ASSOCIATE_NAME,
CHANGED_TO_COMMISSION_PCT,
RESOURCE_COMMISSION_AMT as RESOURCE_COMMISION_AMT ,
DUPLICATION,
APPOINTMENT_TSTMP,
ASSOCIATE_NAME,
AUTO_CALCULATED_PRICE_FORMULA,
EXPRESS_FLAG,
HIDDEN_FLAG,
FOR_QUOTE_FLAG,
SERVICE_TSTMP,
END_TSTMP,
SMS_ORDER_ITEM_ID,
CURRENCY_ISO_CD,
DELETED_FLAG,
HARD_DELETED_FLAG,
SDS_SYSTEM_MODIFIED_TSTMP,
SDS_LAST_MODIFIED_TSTMP,
SDS_LAST_MODIFIED_BY_ID,
SDS_CREATED_TSTMP,
SDS_CREATED_BY_ID,
LOAD_TSTMP
FROM {legacy}.SDS_ORDER_ITEM""").withColumn("sys_row_id", monotonically_increasing_id())

# COMMAND ----------
# Processing node JNR_SDS_ORDER_ITEM, type JOINER . Note: using additional SELECT to rename incoming columns
# COLUMN COUNT: 94

# for each involved DataFrame, append the dataframe name to each column
SQ_Shortcut_to_SDS_ORDER_ITEM_temp = SQ_Shortcut_to_SDS_ORDER_ITEM.toDF(*["SQ_Shortcut_to_SDS_ORDER_ITEM___" + col for col in SQ_Shortcut_to_SDS_ORDER_ITEM.columns])
EXP_TOTAL_GROOM_PAY_ELIGIBLE_PRICE_C_temp = EXP_TOTAL_GROOM_PAY_ELIGIBLE_PRICE_C.toDF(*["EXP_TOTAL_GROOM_PAY_ELIGIBLE_PRICE_C___" + col for col in EXP_TOTAL_GROOM_PAY_ELIGIBLE_PRICE_C.columns])

JNR_SDS_ORDER_ITEM = EXP_TOTAL_GROOM_PAY_ELIGIBLE_PRICE_C_temp.join(SQ_Shortcut_to_SDS_ORDER_ITEM_temp,[EXP_TOTAL_GROOM_PAY_ELIGIBLE_PRICE_C_temp.EXP_TOTAL_GROOM_PAY_ELIGIBLE_PRICE_C___ID == SQ_Shortcut_to_SDS_ORDER_ITEM_temp.SQ_Shortcut_to_SDS_ORDER_ITEM___SDS_ORDER_ITEM_ID],'left_outer').selectExpr(
	"EXP_TOTAL_GROOM_PAY_ELIGIBLE_PRICE_C___ID as ID",
	"EXP_TOTAL_GROOM_PAY_ELIGIBLE_PRICE_C___PRODUCT2_ID as PRODUCT2_ID",
	"EXP_TOTAL_GROOM_PAY_ELIGIBLE_PRICE_C___IS_DELETED as IS_DELETED",
	"EXP_TOTAL_GROOM_PAY_ELIGIBLE_PRICE_C___ORDER_ID as ORDER_ID",
	"EXP_TOTAL_GROOM_PAY_ELIGIBLE_PRICE_C___PRICE_BOOK_ENTRY_ID as PRICE_BOOK_ENTRY_ID",
	"EXP_TOTAL_GROOM_PAY_ELIGIBLE_PRICE_C___ORIGINAL_ORDER_ITEM_ID as ORIGINAL_ORDER_ITEM_ID",
	"EXP_TOTAL_GROOM_PAY_ELIGIBLE_PRICE_C___QUOTE_LINE_ITEM_ID as QUOTE_LINE_ITEM_ID",
	"EXP_TOTAL_GROOM_PAY_ELIGIBLE_PRICE_C___AVAILABLE_QUANTITY as AVAILABLE_QUANTITY",
	"EXP_TOTAL_GROOM_PAY_ELIGIBLE_PRICE_C___QUANTITY as QUANTITY",
	"EXP_TOTAL_GROOM_PAY_ELIGIBLE_PRICE_C___CURRENCY_ISO_CODE as CURRENCY_ISO_CODE",
	"EXP_TOTAL_GROOM_PAY_ELIGIBLE_PRICE_C___UNIT_PRICE as UNIT_PRICE",
	"EXP_TOTAL_GROOM_PAY_ELIGIBLE_PRICE_C___LIST_PRICE as LIST_PRICE",
	"EXP_TOTAL_GROOM_PAY_ELIGIBLE_PRICE_C___TOTAL_PRICE as TOTAL_PRICE",
	"EXP_TOTAL_GROOM_PAY_ELIGIBLE_PRICE_C___SERVICE_DATE as SERVICE_DATE",
	"EXP_TOTAL_GROOM_PAY_ELIGIBLE_PRICE_C___END_DATE as END_DATE",
	"EXP_TOTAL_GROOM_PAY_ELIGIBLE_PRICE_C___DESCRIPTION as DESCRIPTION",
	"EXP_TOTAL_GROOM_PAY_ELIGIBLE_PRICE_C___CREATED_DATE as CREATED_DATE",
	"EXP_TOTAL_GROOM_PAY_ELIGIBLE_PRICE_C___CREATED_BY_ID as CREATED_BY_ID",
	"EXP_TOTAL_GROOM_PAY_ELIGIBLE_PRICE_C___LAST_MODIFIED_DATE as LAST_MODIFIED_DATE",
	"EXP_TOTAL_GROOM_PAY_ELIGIBLE_PRICE_C___LAST_MODIFIED_BY_ID as LAST_MODIFIED_BY_ID",
	"EXP_TOTAL_GROOM_PAY_ELIGIBLE_PRICE_C___SYSTEM_MOD_STAMP as SYSTEM_MOD_STAMP",
	"EXP_TOTAL_GROOM_PAY_ELIGIBLE_PRICE_C___ORDER_ITEM_NUMBER as ORDER_ITEM_NUMBER",
	"EXP_TOTAL_GROOM_PAY_ELIGIBLE_PRICE_C___PSVC_COMMISSION_AMOUNT_C as PSVC_COMMISSION_AMOUNT_C",
	"EXP_TOTAL_GROOM_PAY_ELIGIBLE_PRICE_C___PSVC_IS_FOR_QUOTE_C as PSVC_IS_FOR_QUOTE_C",
	"EXP_TOTAL_GROOM_PAY_ELIGIBLE_PRICE_C___PSVC_PRICE_MANUAL_ADJUSTMENT_REASON_C as PSVC_PRICE_MANUAL_ADJUSTMENT_REASON_C",
	"EXP_TOTAL_GROOM_PAY_ELIGIBLE_PRICE_C___PSVC_WORK_ORDER_C as PSVC_WORK_ORDER_C",
	"EXP_TOTAL_GROOM_PAY_ELIGIBLE_PRICE_C___PSVC_AUTO_CALCULATED_PRICE_C as PSVC_AUTO_CALCULATED_PRICE_C",
	"EXP_TOTAL_GROOM_PAY_ELIGIBLE_PRICE_C___PSVC_DUPLICATION_C as PSVC_DUPLICATION_C",
	"EXP_TOTAL_GROOM_PAY_ELIGIBLE_PRICE_C___PSVC_MANUAL_ADJUSTED_PRICE_C as PSVC_MANUAL_ADJUSTED_PRICE_C",
	"EXP_TOTAL_GROOM_PAY_ELIGIBLE_PRICE_C___PSVC_APPOINTMENT_DATE_C as PSVC_APPOINTMENT_DATE_C",
	"EXP_TOTAL_GROOM_PAY_ELIGIBLE_PRICE_C___PSVC_ASSOCIATE_C as PSVC_ASSOCIATE_C",
	"EXP_TOTAL_GROOM_PAY_ELIGIBLE_PRICE_C___PSVC_AUTO_CALCULATED_PRICE_FORMULA_C as PSVC_AUTO_CALCULATED_PRICE_FORMULA_C",
	"EXP_TOTAL_GROOM_PAY_ELIGIBLE_PRICE_C___PSVC_IS_HIDDEN_C as PSVC_IS_HIDDEN_C",
	"EXP_TOTAL_GROOM_PAY_ELIGIBLE_PRICE_C___PSVC_CHANGE_COMMISSION_TO_C as PSVC_CHANGE_COMMISSION_TO_C",
	"EXP_TOTAL_GROOM_PAY_ELIGIBLE_PRICE_C___PSVC_CHANGE_TO_COMMISSION_PERCENTAGE_C as PSVC_CHANGE_TO_COMMISSION_PERCENTAGE_C",
	"EXP_TOTAL_GROOM_PAY_ELIGIBLE_PRICE_C___PSVC_COMMISSION_RECEIVER_C as PSVC_COMMISSION_RECEIVER_C",
	"EXP_TOTAL_GROOM_PAY_ELIGIBLE_PRICE_C___PSVC_EXPRESS_C as PSVC_EXPRESS_C",
	"EXP_TOTAL_GROOM_PAY_ELIGIBLE_PRICE_C___PSVC_RESOURCE_COMMISSION_C as PSVC_RESOURCE_COMMISSION_C",
	"EXP_TOTAL_GROOM_PAY_ELIGIBLE_PRICE_C___PSVC_ORDER_PRODUCT_NUMBER_C as PSVC_ORDER_PRODUCT_NUMBER_C",
	"EXP_TOTAL_GROOM_PAY_ELIGIBLE_PRICE_C___PSVC_ORDER_PRODUCT_SMS_ID_C as PSVC_ORDER_PRODUCT_SMS_ID_C",
	"EXP_TOTAL_GROOM_PAY_ELIGIBLE_PRICE_C___PSVC_TOTAL_PRICE_FOR_POS_C as PSVC_TOTAL_PRICE_FOR_POS_C",
	"EXP_TOTAL_GROOM_PAY_ELIGIBLE_PRICE_C___PSVC_UNIT_PRICE_FOR_POS_C as PSVC_UNIT_PRICE_FOR_POS_C",
	"EXP_TOTAL_GROOM_PAY_ELIGIBLE_PRICE_C___LINE_ITEM_TOTAL_TAX_C as LINE_ITEM_TOTAL_TAX_C",
	"EXP_TOTAL_GROOM_PAY_ELIGIBLE_PRICE_C___o_PSVC_TOTAL_GROOM_PAY_ELIGIBLE_PRICE_C as PSVC_TOTAL_GROOM_PAY_ELIGIBLE_PRICE_C",
	"EXP_TOTAL_GROOM_PAY_ELIGIBLE_PRICE_C___PSVC_ORIGINAL_UNIT_PRICE_C as PSVC_ORIGINAL_UNIT_PRICE_C",
	"EXP_TOTAL_GROOM_PAY_ELIGIBLE_PRICE_C___PSVC_IS_PREPAID_C as PSVC_IS_PREPAID_C",
	"SQ_Shortcut_to_SDS_ORDER_ITEM___SDS_ORDER_ITEM_ID as i_SDS_ORDER_ITEM_ID",
	"SQ_Shortcut_to_SDS_ORDER_ITEM___SDS_ORDER_ITEM_DESC as i_SDS_ORDER_ITEM_DESC",
	"SQ_Shortcut_to_SDS_ORDER_ITEM___SDS_ORDER_ID as i_SDS_ORDER_ID",
	"SQ_Shortcut_to_SDS_ORDER_ITEM___SDS_WORK_ORDER_ID as i_SDS_WORK_ORDER_ID",
	"SQ_Shortcut_to_SDS_ORDER_ITEM___SDS_PRODUCT_ID as i_SDS_PRODUCT_ID",
	"SQ_Shortcut_to_SDS_ORDER_ITEM___SDS_ORDER_ITEM_NBR as i_SDS_ORDER_ITEM_NBR",
	"SQ_Shortcut_to_SDS_ORDER_ITEM___SDS_ORDER_PRODUCT_NBR as i_SDS_ORDER_PRODUCT_NBR",
	"SQ_Shortcut_to_SDS_ORDER_ITEM___SDS_ORIG_ORDER_ITEM_ID as i_SDS_ORIG_ORDER_ITEM_ID",
	"SQ_Shortcut_to_SDS_ORDER_ITEM___SDS_QUOTE_LINE_ITEM_ID as i_SDS_QUOTE_LINE_ITEM_ID",
	"SQ_Shortcut_to_SDS_ORDER_ITEM___SDS_PRICEBOOK_ENTRY_ID as i_SDS_PRICEBOOK_ENTRY_ID",
	"SQ_Shortcut_to_SDS_ORDER_ITEM___PREPAID_FLAG as i_PREPAID_FLAG",
	"SQ_Shortcut_to_SDS_ORDER_ITEM___ORDER_ITEM_AVAILABLE_QTY as i_ORDER_ITEM_AVAILABLE_QTY",
	"SQ_Shortcut_to_SDS_ORDER_ITEM___ORDER_ITEM_QTY as i_ORDER_ITEM_QTY",
	"SQ_Shortcut_to_SDS_ORDER_ITEM___UNIT_PRICE as i_UNIT_PRICE",
	"SQ_Shortcut_to_SDS_ORDER_ITEM___LIST_PRICE as i_LIST_PRICE",
	"SQ_Shortcut_to_SDS_ORDER_ITEM___ORIG_UNIT_PRICE as i_ORIG_UNIT_PRICE",
	"SQ_Shortcut_to_SDS_ORDER_ITEM___POS_UNIT_PRICE as i_POS_UNIT_PRICE",
	"SQ_Shortcut_to_SDS_ORDER_ITEM___MANUAL_ADJUSTED_PRICE as i_MANUAL_ADJUSTED_PRICE",
	"SQ_Shortcut_to_SDS_ORDER_ITEM___PRICE_MANUAL_ADJ_REASON as i_PRICE_MANUAL_ADJ_REASON",
	"SQ_Shortcut_to_SDS_ORDER_ITEM___AUTO_CALCULATED_PRICE as i_AUTO_CALCULATED_PRICE",
	"SQ_Shortcut_to_SDS_ORDER_ITEM___LINE_ITEM_TOTAL_TAX as i_LINE_ITEM_TOTAL_TAX",
	"SQ_Shortcut_to_SDS_ORDER_ITEM___TOTAL_PRICE as i_TOTAL_PRICE",
	"SQ_Shortcut_to_SDS_ORDER_ITEM___POS_TOTAL_PRICE as i_POS_TOTAL_PRICE",
	"SQ_Shortcut_to_SDS_ORDER_ITEM___TOTAL_GROOM_PAY_ELIGIBLE_PRICE as i_TOTAL_GROOM_PAY_ELIGIBLE_PRICE",
	"SQ_Shortcut_to_SDS_ORDER_ITEM___COMMISSION_AMT as i_COMMISSION_AMT",
	"SQ_Shortcut_to_SDS_ORDER_ITEM___CHANGED_COMMISSION_TO_SERVICE_RESOURCE_ID as i_CHANGED_COMMISSION_TO_SERVICE_RESOURCE_ID",
	"SQ_Shortcut_to_SDS_ORDER_ITEM___COMMISSION_RECEIVER_ASSOCIATE_NAME as i_COMMISSION_RECEIVER_ASSOCIATE_NAME",
	"SQ_Shortcut_to_SDS_ORDER_ITEM___CHANGED_TO_COMMISSION_PCT as i_CHANGED_TO_COMMISSION_PCT",
	"SQ_Shortcut_to_SDS_ORDER_ITEM___RESOURCE_COMMISION_AMT as i_RESOURCE_COMMISSION_AMT",
	"SQ_Shortcut_to_SDS_ORDER_ITEM___DUPLICATION as i_DUPLICATION",
	"SQ_Shortcut_to_SDS_ORDER_ITEM___APPOINTMENT_TSTMP as i_APPOINTMENT_TSTMP",
	"SQ_Shortcut_to_SDS_ORDER_ITEM___ASSOCIATE_NAME as i_ASSOCIATE_NAME",
	"SQ_Shortcut_to_SDS_ORDER_ITEM___AUTO_CALCULATED_PRICE_FORMULA as i_AUTO_CALCULATED_PRICE_FORMULA",
	"SQ_Shortcut_to_SDS_ORDER_ITEM___EXPRESS_FLAG as i_EXPRESS_FLAG",
	"SQ_Shortcut_to_SDS_ORDER_ITEM___HIDDEN_FLAG as i_HIDDEN_FLAG",
	"SQ_Shortcut_to_SDS_ORDER_ITEM___FOR_QUOTE_FLAG as i_FOR_QUOTE_FLAG",
	"SQ_Shortcut_to_SDS_ORDER_ITEM___SERVICE_TSTMP as i_SERVICE_TSTMP",
	"SQ_Shortcut_to_SDS_ORDER_ITEM___END_TSTMP as i_END_TSTMP",
	"SQ_Shortcut_to_SDS_ORDER_ITEM___SMS_ORDER_ITEM_ID as i_SMS_ORDER_ITEM_ID",
	"SQ_Shortcut_to_SDS_ORDER_ITEM___CURRENCY_ISO_CD as i_CURRENCY_ISO_CD",
	"SQ_Shortcut_to_SDS_ORDER_ITEM___DELETED_FLAG as i_DELETED_FLAG",
	"SQ_Shortcut_to_SDS_ORDER_ITEM___HARD_DELETED_FLAG as i_HARD_DELETED_FLAG",
	"SQ_Shortcut_to_SDS_ORDER_ITEM___SDS_SYSTEM_MODIFIED_TSTMP as i_SDS_SYSTEM_MODIFIED_TSTMP",
	"SQ_Shortcut_to_SDS_ORDER_ITEM___SDS_LAST_MODIFIED_TSTMP as i_SDS_LAST_MODIFIED_TSTMP",
	"SQ_Shortcut_to_SDS_ORDER_ITEM___SDS_LAST_MODIFIED_BY_ID as i_SDS_LAST_MODIFIED_BY_ID",
	"SQ_Shortcut_to_SDS_ORDER_ITEM___SDS_CREATED_TSTMP as i_SDS_CREATED_TSTMP",
	"SQ_Shortcut_to_SDS_ORDER_ITEM___SDS_CREATED_BY_ID as i_SDS_CREATED_BY_ID",
	"SQ_Shortcut_to_SDS_ORDER_ITEM___LOAD_TSTMP as i_LOAD_TSTMP")

# COMMAND ----------
# Processing node FIL_SDS_ORDER_ITEM, type FILTER 
# COLUMN COUNT: 94

# for each involved DataFrame, append the dataframe name to each column
JNR_SDS_ORDER_ITEM_temp = JNR_SDS_ORDER_ITEM.toDF(*["JNR_SDS_ORDER_ITEM___" + col for col in JNR_SDS_ORDER_ITEM.columns])

FIL_SDS_ORDER_ITEM = JNR_SDS_ORDER_ITEM_temp.selectExpr(
	"JNR_SDS_ORDER_ITEM___ID as ID",
	"JNR_SDS_ORDER_ITEM___PRODUCT2_ID as PRODUCT2_ID",
	"JNR_SDS_ORDER_ITEM___IS_DELETED as IS_DELETED",
	"JNR_SDS_ORDER_ITEM___ORDER_ID as ORDER_ID",
	"JNR_SDS_ORDER_ITEM___PRICE_BOOK_ENTRY_ID as PRICE_BOOK_ENTRY_ID",
	"JNR_SDS_ORDER_ITEM___ORIGINAL_ORDER_ITEM_ID as ORIGINAL_ORDER_ITEM_ID",
	"JNR_SDS_ORDER_ITEM___QUOTE_LINE_ITEM_ID as QUOTE_LINE_ITEM_ID",
	"JNR_SDS_ORDER_ITEM___AVAILABLE_QUANTITY as AVAILABLE_QUANTITY",
	"JNR_SDS_ORDER_ITEM___QUANTITY as QUANTITY",
	"JNR_SDS_ORDER_ITEM___CURRENCY_ISO_CODE as CURRENCY_ISO_CODE",
	"JNR_SDS_ORDER_ITEM___UNIT_PRICE as UNIT_PRICE",
	"JNR_SDS_ORDER_ITEM___LIST_PRICE as LIST_PRICE",
	"JNR_SDS_ORDER_ITEM___TOTAL_PRICE as TOTAL_PRICE",
	"JNR_SDS_ORDER_ITEM___SERVICE_DATE as SERVICE_DATE",
	"JNR_SDS_ORDER_ITEM___END_DATE as END_DATE",
	"JNR_SDS_ORDER_ITEM___DESCRIPTION as DESCRIPTION",
	"JNR_SDS_ORDER_ITEM___CREATED_DATE as CREATED_DATE",
	"JNR_SDS_ORDER_ITEM___CREATED_BY_ID as CREATED_BY_ID",
	"JNR_SDS_ORDER_ITEM___LAST_MODIFIED_DATE as LAST_MODIFIED_DATE",
	"JNR_SDS_ORDER_ITEM___LAST_MODIFIED_BY_ID as LAST_MODIFIED_BY_ID",
	"JNR_SDS_ORDER_ITEM___SYSTEM_MOD_STAMP as SYSTEM_MOD_STAMP",
	"JNR_SDS_ORDER_ITEM___ORDER_ITEM_NUMBER as ORDER_ITEM_NUMBER",
	"JNR_SDS_ORDER_ITEM___PSVC_COMMISSION_AMOUNT_C as PSVC_COMMISSION_AMOUNT_C",
	"JNR_SDS_ORDER_ITEM___PSVC_IS_FOR_QUOTE_C as PSVC_IS_FOR_QUOTE_C",
	"JNR_SDS_ORDER_ITEM___PSVC_PRICE_MANUAL_ADJUSTMENT_REASON_C as PSVC_PRICE_MANUAL_ADJUSTMENT_REASON_C",
	"JNR_SDS_ORDER_ITEM___PSVC_WORK_ORDER_C as PSVC_WORK_ORDER_C",
	"JNR_SDS_ORDER_ITEM___PSVC_AUTO_CALCULATED_PRICE_C as PSVC_AUTO_CALCULATED_PRICE_C",
	"JNR_SDS_ORDER_ITEM___PSVC_DUPLICATION_C as PSVC_DUPLICATION_C",
	"JNR_SDS_ORDER_ITEM___PSVC_MANUAL_ADJUSTED_PRICE_C as PSVC_MANUAL_ADJUSTED_PRICE_C",
	"JNR_SDS_ORDER_ITEM___PSVC_APPOINTMENT_DATE_C as PSVC_APPOINTMENT_DATE_C",
	"JNR_SDS_ORDER_ITEM___PSVC_ASSOCIATE_C as PSVC_ASSOCIATE_C",
	"JNR_SDS_ORDER_ITEM___PSVC_AUTO_CALCULATED_PRICE_FORMULA_C as PSVC_AUTO_CALCULATED_PRICE_FORMULA_C",
	"JNR_SDS_ORDER_ITEM___PSVC_IS_HIDDEN_C as PSVC_IS_HIDDEN_C",
	"JNR_SDS_ORDER_ITEM___PSVC_CHANGE_COMMISSION_TO_C as PSVC_CHANGE_COMMISSION_TO_C",
	"JNR_SDS_ORDER_ITEM___PSVC_CHANGE_TO_COMMISSION_PERCENTAGE_C as PSVC_CHANGE_TO_COMMISSION_PERCENTAGE_C",
	"JNR_SDS_ORDER_ITEM___PSVC_COMMISSION_RECEIVER_C as PSVC_COMMISSION_RECEIVER_C",
	"JNR_SDS_ORDER_ITEM___PSVC_EXPRESS_C as PSVC_EXPRESS_C",
	"JNR_SDS_ORDER_ITEM___PSVC_RESOURCE_COMMISSION_C as PSVC_RESOURCE_COMMISSION_C",
	"JNR_SDS_ORDER_ITEM___PSVC_ORDER_PRODUCT_NUMBER_C as PSVC_ORDER_PRODUCT_NUMBER_C",
	"JNR_SDS_ORDER_ITEM___PSVC_ORDER_PRODUCT_SMS_ID_C as PSVC_ORDER_PRODUCT_SMS_ID_C",
	"JNR_SDS_ORDER_ITEM___PSVC_TOTAL_PRICE_FOR_POS_C as PSVC_TOTAL_PRICE_FOR_POS_C",
	"JNR_SDS_ORDER_ITEM___PSVC_UNIT_PRICE_FOR_POS_C as PSVC_UNIT_PRICE_FOR_POS_C",
	"JNR_SDS_ORDER_ITEM___LINE_ITEM_TOTAL_TAX_C as LINE_ITEM_TOTAL_TAX_C",
	"JNR_SDS_ORDER_ITEM___PSVC_TOTAL_GROOM_PAY_ELIGIBLE_PRICE_C as PSVC_TOTAL_GROOM_PAY_ELIGIBLE_PRICE_C",
	"JNR_SDS_ORDER_ITEM___PSVC_ORIGINAL_UNIT_PRICE_C as PSVC_ORIGINAL_UNIT_PRICE_C",
	"JNR_SDS_ORDER_ITEM___PSVC_IS_PREPAID_C as PSVC_IS_PREPAID_C",
	"JNR_SDS_ORDER_ITEM___i_SDS_ORDER_ITEM_ID as i_SDS_ORDER_ITEM_ID",
	"JNR_SDS_ORDER_ITEM___i_SDS_ORDER_ITEM_DESC as i_SDS_ORDER_ITEM_DESC",
	"JNR_SDS_ORDER_ITEM___i_SDS_ORDER_ID as i_SDS_ORDER_ID",
	"JNR_SDS_ORDER_ITEM___i_SDS_WORK_ORDER_ID as i_SDS_WORK_ORDER_ID",
	"JNR_SDS_ORDER_ITEM___i_SDS_PRODUCT_ID as i_SDS_PRODUCT_ID",
	"JNR_SDS_ORDER_ITEM___i_SDS_ORDER_ITEM_NBR as i_SDS_ORDER_ITEM_NBR",
	"JNR_SDS_ORDER_ITEM___i_SDS_ORDER_PRODUCT_NBR as i_SDS_ORDER_PRODUCT_NBR",
	"JNR_SDS_ORDER_ITEM___i_SDS_ORIG_ORDER_ITEM_ID as i_SDS_ORIG_ORDER_ITEM_ID",
	"JNR_SDS_ORDER_ITEM___i_SDS_QUOTE_LINE_ITEM_ID as i_SDS_QUOTE_LINE_ITEM_ID",
	"JNR_SDS_ORDER_ITEM___i_SDS_PRICEBOOK_ENTRY_ID as i_SDS_PRICEBOOK_ENTRY_ID",
	"JNR_SDS_ORDER_ITEM___i_PREPAID_FLAG as i_PREPAID_FLAG",
	"JNR_SDS_ORDER_ITEM___i_ORDER_ITEM_AVAILABLE_QTY as i_ORDER_ITEM_AVAILABLE_QTY",
	"JNR_SDS_ORDER_ITEM___i_ORDER_ITEM_QTY as i_ORDER_ITEM_QTY",
	"JNR_SDS_ORDER_ITEM___i_UNIT_PRICE as i_UNIT_PRICE",
	"JNR_SDS_ORDER_ITEM___i_LIST_PRICE as i_LIST_PRICE",
	"JNR_SDS_ORDER_ITEM___i_ORIG_UNIT_PRICE as i_ORIG_UNIT_PRICE",
	"JNR_SDS_ORDER_ITEM___i_POS_UNIT_PRICE as i_POS_UNIT_PRICE",
	"JNR_SDS_ORDER_ITEM___i_MANUAL_ADJUSTED_PRICE as i_MANUAL_ADJUSTED_PRICE",
	"JNR_SDS_ORDER_ITEM___i_PRICE_MANUAL_ADJ_REASON as i_PRICE_MANUAL_ADJ_REASON",
	"JNR_SDS_ORDER_ITEM___i_AUTO_CALCULATED_PRICE as i_AUTO_CALCULATED_PRICE",
	"JNR_SDS_ORDER_ITEM___i_LINE_ITEM_TOTAL_TAX as i_LINE_ITEM_TOTAL_TAX",
	"JNR_SDS_ORDER_ITEM___i_TOTAL_PRICE as i_TOTAL_PRICE",
	"JNR_SDS_ORDER_ITEM___i_POS_TOTAL_PRICE as i_POS_TOTAL_PRICE",
	"JNR_SDS_ORDER_ITEM___i_TOTAL_GROOM_PAY_ELIGIBLE_PRICE as i_TOTAL_GROOM_PAY_ELIGIBLE_PRICE",
	"JNR_SDS_ORDER_ITEM___i_COMMISSION_AMT as i_COMMISSION_AMT",
	"JNR_SDS_ORDER_ITEM___i_CHANGED_COMMISSION_TO_SERVICE_RESOURCE_ID as i_CHANGED_COMMISSION_TO_SERVICE_RESOURCE_ID",
	"JNR_SDS_ORDER_ITEM___i_COMMISSION_RECEIVER_ASSOCIATE_NAME as i_COMMISSION_RECEIVER_ASSOCIATE_NAME",
	"JNR_SDS_ORDER_ITEM___i_CHANGED_TO_COMMISSION_PCT as i_CHANGED_TO_COMMISSION_PCT",
	"JNR_SDS_ORDER_ITEM___i_RESOURCE_COMMISSION_AMT as i_RESOURCE_COMMISSION_AMT",
	"JNR_SDS_ORDER_ITEM___i_DUPLICATION as i_DUPLICATION",
	"JNR_SDS_ORDER_ITEM___i_APPOINTMENT_TSTMP as i_APPOINTMENT_TSTMP",
	"JNR_SDS_ORDER_ITEM___i_ASSOCIATE_NAME as i_ASSOCIATE_NAME",
	"JNR_SDS_ORDER_ITEM___i_AUTO_CALCULATED_PRICE_FORMULA as i_AUTO_CALCULATED_PRICE_FORMULA",
	"JNR_SDS_ORDER_ITEM___i_EXPRESS_FLAG as i_EXPRESS_FLAG",
	"JNR_SDS_ORDER_ITEM___i_HIDDEN_FLAG as i_HIDDEN_FLAG",
	"JNR_SDS_ORDER_ITEM___i_FOR_QUOTE_FLAG as i_FOR_QUOTE_FLAG",
	"JNR_SDS_ORDER_ITEM___i_SERVICE_TSTMP as i_SERVICE_TSTMP",
	"JNR_SDS_ORDER_ITEM___i_END_TSTMP as i_END_TSTMP",
	"JNR_SDS_ORDER_ITEM___i_SMS_ORDER_ITEM_ID as i_SMS_ORDER_ITEM_ID",
	"JNR_SDS_ORDER_ITEM___i_CURRENCY_ISO_CD as i_CURRENCY_ISO_CD",
	"JNR_SDS_ORDER_ITEM___i_DELETED_FLAG as i_DELETED_FLAG",
	"JNR_SDS_ORDER_ITEM___i_HARD_DELETED_FLAG as i_HARD_DELETED_FLAG",
	"JNR_SDS_ORDER_ITEM___i_SDS_SYSTEM_MODIFIED_TSTMP as i_SDS_SYSTEM_MODIFIED_TSTMP",
	"JNR_SDS_ORDER_ITEM___i_SDS_LAST_MODIFIED_TSTMP as i_SDS_LAST_MODIFIED_TSTMP",
	"JNR_SDS_ORDER_ITEM___i_SDS_LAST_MODIFIED_BY_ID as i_SDS_LAST_MODIFIED_BY_ID",
	"JNR_SDS_ORDER_ITEM___i_SDS_CREATED_TSTMP as i_SDS_CREATED_TSTMP",
	"JNR_SDS_ORDER_ITEM___i_SDS_CREATED_BY_ID as i_SDS_CREATED_BY_ID",
	"JNR_SDS_ORDER_ITEM___i_LOAD_TSTMP as i_LOAD_TSTMP").filter("i_SDS_ORDER_ITEM_ID IS NULL OR ( i_SDS_ORDER_ITEM_ID IS NOT NULL AND ( i_SDS_SYSTEM_MODIFIED_TSTMP != SYSTEM_MOD_STAMP OR i_SDS_CREATED_TSTMP != CREATED_DATE OR i_SDS_LAST_MODIFIED_TSTMP != LAST_MODIFIED_DATE OR IF (PRODUCT2_ID IS NULL, ' ', PRODUCT2_ID) != IF (i_SDS_PRODUCT_ID IS NULL, ' ', i_SDS_PRODUCT_ID) OR IF (IS_DELETED IS NULL, - 99999, IS_DELETED) != IF (i_DELETED_FLAG IS NULL, - 99999, i_DELETED_FLAG) OR IF (ORDER_ID IS NULL, ' ', ORDER_ID) != IF (i_SDS_ORDER_ID IS NULL, ' ', i_SDS_ORDER_ID) OR IF (PRICE_BOOK_ENTRY_ID IS NULL, ' ', PRICE_BOOK_ENTRY_ID) != IF (i_SDS_PRICEBOOK_ENTRY_ID IS NULL, ' ', i_SDS_PRICEBOOK_ENTRY_ID) OR IF (ORIGINAL_ORDER_ITEM_ID IS NULL, ' ', ORIGINAL_ORDER_ITEM_ID) != IF (i_SDS_ORIG_ORDER_ITEM_ID IS NULL, ' ', i_SDS_ORIG_ORDER_ITEM_ID) OR IF (QUOTE_LINE_ITEM_ID IS NULL, ' ', QUOTE_LINE_ITEM_ID) != IF (i_SDS_QUOTE_LINE_ITEM_ID IS NULL, ' ', i_SDS_QUOTE_LINE_ITEM_ID) OR IF (AVAILABLE_QUANTITY IS NULL, - 99999, AVAILABLE_QUANTITY) != IF (i_ORDER_ITEM_AVAILABLE_QTY IS NULL, - 99999, i_ORDER_ITEM_AVAILABLE_QTY) OR IF (QUANTITY IS NULL, - 99999, QUANTITY) != IF (i_ORDER_ITEM_QTY IS NULL, - 99999, i_ORDER_ITEM_QTY) OR IF (CURRENCY_ISO_CODE IS NULL, ' ', CURRENCY_ISO_CODE) != IF (i_CURRENCY_ISO_CD IS NULL, ' ', i_CURRENCY_ISO_CD) OR IF (UNIT_PRICE IS NULL, - 99999, UNIT_PRICE) != IF (i_UNIT_PRICE IS NULL, - 99999, i_UNIT_PRICE) OR IF (LIST_PRICE IS NULL, - 99999, LIST_PRICE) != IF (i_LIST_PRICE IS NULL, - 99999, i_LIST_PRICE) OR IF (TOTAL_PRICE IS NULL, - 99999, TOTAL_PRICE) != IF (i_TOTAL_PRICE IS NULL, - 99999, i_TOTAL_PRICE) OR IF (SERVICE_DATE IS NULL, TO_DATE ( '1901-01-01' , 'YYYY-MM-DD' ), SERVICE_DATE) != IF (i_SERVICE_TSTMP IS NULL, TO_DATE ( '1901-01-01' , 'YYYY-MM-DD' ), i_SERVICE_TSTMP) OR IF (END_DATE IS NULL, TO_DATE ( '1901-01-01' , 'YYYY-MM-DD' ), END_DATE) != IF (i_END_TSTMP IS NULL, TO_DATE ( '1901-01-01' , 'YYYY-MM-DD' ), i_END_TSTMP) OR IF (DESCRIPTION IS NULL, ' ', DESCRIPTION) != IF (i_SDS_ORDER_ITEM_DESC IS NULL, ' ', i_SDS_ORDER_ITEM_DESC) OR IF (CREATED_BY_ID IS NULL, ' ', CREATED_BY_ID) != IF (i_SDS_CREATED_BY_ID IS NULL, ' ', i_SDS_CREATED_BY_ID) OR IF (LAST_MODIFIED_BY_ID IS NULL, ' ', LAST_MODIFIED_BY_ID) != IF (i_SDS_LAST_MODIFIED_BY_ID IS NULL, ' ', i_SDS_LAST_MODIFIED_BY_ID) OR IF (ORDER_ITEM_NUMBER IS NULL, ' ', ORDER_ITEM_NUMBER) != IF (i_SDS_ORDER_ITEM_NBR IS NULL, ' ', i_SDS_ORDER_ITEM_NBR) OR IF (PSVC_COMMISSION_AMOUNT_C IS NULL, - 99999, PSVC_COMMISSION_AMOUNT_C) != IF (i_COMMISSION_AMT IS NULL, - 99999, i_COMMISSION_AMT) OR IF (PSVC_IS_FOR_QUOTE_C IS NULL, - 99999, PSVC_IS_FOR_QUOTE_C) != IF (i_FOR_QUOTE_FLAG IS NULL, - 99999, i_FOR_QUOTE_FLAG) OR IF (PSVC_PRICE_MANUAL_ADJUSTMENT_REASON_C IS NULL, ' ', PSVC_PRICE_MANUAL_ADJUSTMENT_REASON_C) != IF (i_PRICE_MANUAL_ADJ_REASON IS NULL, ' ', i_PRICE_MANUAL_ADJ_REASON) OR IF (PSVC_WORK_ORDER_C IS NULL, ' ', PSVC_WORK_ORDER_C) != IF (i_SDS_WORK_ORDER_ID IS NULL, ' ', i_SDS_WORK_ORDER_ID) OR IF (PSVC_AUTO_CALCULATED_PRICE_C IS NULL, - 99999, PSVC_AUTO_CALCULATED_PRICE_C) != IF (i_AUTO_CALCULATED_PRICE IS NULL, - 99999, i_AUTO_CALCULATED_PRICE) OR IF (PSVC_DUPLICATION_C IS NULL, ' ', PSVC_DUPLICATION_C) != IF (i_DUPLICATION IS NULL, ' ', i_DUPLICATION) OR IF (PSVC_MANUAL_ADJUSTED_PRICE_C IS NULL, - 99999, PSVC_MANUAL_ADJUSTED_PRICE_C) != IF (i_MANUAL_ADJUSTED_PRICE IS NULL, - 99999, i_MANUAL_ADJUSTED_PRICE) OR IF (PSVC_APPOINTMENT_DATE_C IS NULL, TO_DATE ( '1901-01-01' , 'YYYY-MM-DD' ), PSVC_APPOINTMENT_DATE_C) != IF (i_APPOINTMENT_TSTMP IS NULL, TO_DATE ( '1901-01-01' , 'YYYY-MM-DD' ), i_APPOINTMENT_TSTMP) OR IF (PSVC_ASSOCIATE_C IS NULL, ' ', PSVC_ASSOCIATE_C) != IF (i_ASSOCIATE_NAME IS NULL, ' ', i_ASSOCIATE_NAME) OR IF (PSVC_AUTO_CALCULATED_PRICE_FORMULA_C IS NULL, - 99999, PSVC_AUTO_CALCULATED_PRICE_FORMULA_C) != IF (i_AUTO_CALCULATED_PRICE_FORMULA IS NULL, - 99999, i_AUTO_CALCULATED_PRICE_FORMULA) OR IF (PSVC_IS_HIDDEN_C IS NULL, - 99999, PSVC_IS_HIDDEN_C) != IF (i_HIDDEN_FLAG IS NULL, - 99999, i_HIDDEN_FLAG) OR IF (PSVC_CHANGE_COMMISSION_TO_C IS NULL, ' ', PSVC_CHANGE_COMMISSION_TO_C) != IF (i_CHANGED_COMMISSION_TO_SERVICE_RESOURCE_ID IS NULL, ' ', i_CHANGED_COMMISSION_TO_SERVICE_RESOURCE_ID) OR IF (PSVC_CHANGE_TO_COMMISSION_PERCENTAGE_C IS NULL, - 99999, PSVC_CHANGE_TO_COMMISSION_PERCENTAGE_C) != IF (i_CHANGED_TO_COMMISSION_PCT IS NULL, - 99999, i_CHANGED_TO_COMMISSION_PCT) OR IF (PSVC_COMMISSION_RECEIVER_C IS NULL, ' ', PSVC_COMMISSION_RECEIVER_C) != IF (i_COMMISSION_RECEIVER_ASSOCIATE_NAME IS NULL, ' ', i_COMMISSION_RECEIVER_ASSOCIATE_NAME) OR IF (PSVC_EXPRESS_C IS NULL, - 99999, PSVC_EXPRESS_C) != IF (i_EXPRESS_FLAG IS NULL, - 99999, i_EXPRESS_FLAG) OR IF (PSVC_RESOURCE_COMMISSION_C IS NULL, - 99999, PSVC_RESOURCE_COMMISSION_C) != IF (i_RESOURCE_COMMISSION_AMT IS NULL, - 99999, i_RESOURCE_COMMISSION_AMT) OR IF (PSVC_ORDER_PRODUCT_NUMBER_C IS NULL, ' ', PSVC_ORDER_PRODUCT_NUMBER_C) != IF (i_SDS_ORDER_PRODUCT_NBR IS NULL, ' ', i_SDS_ORDER_PRODUCT_NBR) OR IF (PSVC_ORDER_PRODUCT_SMS_ID_C IS NULL, ' ', PSVC_ORDER_PRODUCT_SMS_ID_C) != IF (i_SMS_ORDER_ITEM_ID IS NULL, ' ', i_SMS_ORDER_ITEM_ID) OR IF (PSVC_UNIT_PRICE_FOR_POS_C IS NULL, - 99999, PSVC_UNIT_PRICE_FOR_POS_C) != IF (i_POS_UNIT_PRICE IS NULL, - 99999, i_POS_UNIT_PRICE) OR IF (LINE_ITEM_TOTAL_TAX_C IS NULL, - 99999, LINE_ITEM_TOTAL_TAX_C) != IF (i_LINE_ITEM_TOTAL_TAX IS NULL, - 99999, i_LINE_ITEM_TOTAL_TAX) OR IF (PSVC_TOTAL_PRICE_FOR_POS_C IS NULL, - 99999, PSVC_TOTAL_PRICE_FOR_POS_C) != IF (i_POS_TOTAL_PRICE IS NULL, - 99999, i_POS_TOTAL_PRICE) OR IF (PSVC_TOTAL_GROOM_PAY_ELIGIBLE_PRICE_C IS NULL, - 99999, PSVC_TOTAL_GROOM_PAY_ELIGIBLE_PRICE_C) != IF (i_TOTAL_GROOM_PAY_ELIGIBLE_PRICE IS NULL, - 99999, i_TOTAL_GROOM_PAY_ELIGIBLE_PRICE) OR IF (PSVC_ORIGINAL_UNIT_PRICE_C IS NULL, - 99999, PSVC_ORIGINAL_UNIT_PRICE_C) != IF (i_ORIG_UNIT_PRICE IS NULL, - 99999, i_ORIG_UNIT_PRICE) OR IF (PSVC_IS_PREPAID_C IS NULL, - 99999, PSVC_IS_PREPAID_C) != IF (i_PREPAID_FLAG IS NULL, - 99999, i_PREPAID_FLAG) ) )").withColumn("sys_row_id", monotonically_increasing_id())

# COMMAND ----------
# Processing node EXP_SDS_ORDER_ITEM, type EXPRESSION 
# COLUMN COUNT: 50

# for each involved DataFrame, append the dataframe name to each column
FIL_SDS_ORDER_ITEM_temp = FIL_SDS_ORDER_ITEM.toDF(*["FIL_SDS_ORDER_ITEM___" + col for col in FIL_SDS_ORDER_ITEM.columns])

EXP_SDS_ORDER_ITEM = FIL_SDS_ORDER_ITEM_temp.selectExpr(
	"FIL_SDS_ORDER_ITEM___sys_row_id as sys_row_id",
	"FIL_SDS_ORDER_ITEM___ID as ID",
	"FIL_SDS_ORDER_ITEM___PRODUCT2_ID as PRODUCT2_ID",
	"FIL_SDS_ORDER_ITEM___IS_DELETED as IS_DELETED",
	"FIL_SDS_ORDER_ITEM___ORDER_ID as ORDER_ID",
	"FIL_SDS_ORDER_ITEM___PRICE_BOOK_ENTRY_ID as PRICE_BOOK_ENTRY_ID",
	"FIL_SDS_ORDER_ITEM___ORIGINAL_ORDER_ITEM_ID as ORIGINAL_ORDER_ITEM_ID",
	"FIL_SDS_ORDER_ITEM___QUOTE_LINE_ITEM_ID as QUOTE_LINE_ITEM_ID",
	"FIL_SDS_ORDER_ITEM___AVAILABLE_QUANTITY as AVAILABLE_QUANTITY",
	"FIL_SDS_ORDER_ITEM___QUANTITY as QUANTITY",
	"FIL_SDS_ORDER_ITEM___CURRENCY_ISO_CODE as CURRENCY_ISO_CODE",
	"FIL_SDS_ORDER_ITEM___UNIT_PRICE as UNIT_PRICE",
	"FIL_SDS_ORDER_ITEM___LIST_PRICE as LIST_PRICE",
	"FIL_SDS_ORDER_ITEM___TOTAL_PRICE as TOTAL_PRICE",
	"FIL_SDS_ORDER_ITEM___SERVICE_DATE as SERVICE_DATE",
	"FIL_SDS_ORDER_ITEM___END_DATE as END_DATE",
	"FIL_SDS_ORDER_ITEM___DESCRIPTION as DESCRIPTION",
	"FIL_SDS_ORDER_ITEM___CREATED_DATE as CREATED_DATE",
	"FIL_SDS_ORDER_ITEM___CREATED_BY_ID as CREATED_BY_ID",
	"FIL_SDS_ORDER_ITEM___LAST_MODIFIED_DATE as LAST_MODIFIED_DATE",
	"FIL_SDS_ORDER_ITEM___LAST_MODIFIED_BY_ID as LAST_MODIFIED_BY_ID",
	"FIL_SDS_ORDER_ITEM___SYSTEM_MOD_STAMP as SYSTEM_MOD_STAMP",
	"FIL_SDS_ORDER_ITEM___ORDER_ITEM_NUMBER as ORDER_ITEM_NUMBER",
	"FIL_SDS_ORDER_ITEM___PSVC_COMMISSION_AMOUNT_C as PSVC_COMMISSION_AMOUNT_C",
	"FIL_SDS_ORDER_ITEM___PSVC_IS_FOR_QUOTE_C as PSVC_IS_FOR_QUOTE_C",
	"FIL_SDS_ORDER_ITEM___PSVC_PRICE_MANUAL_ADJUSTMENT_REASON_C as PSVC_PRICE_MANUAL_ADJUSTMENT_REASON_C",
	"FIL_SDS_ORDER_ITEM___PSVC_WORK_ORDER_C as PSVC_WORK_ORDER_C",
	"FIL_SDS_ORDER_ITEM___PSVC_AUTO_CALCULATED_PRICE_C as PSVC_AUTO_CALCULATED_PRICE_C",
	"FIL_SDS_ORDER_ITEM___PSVC_DUPLICATION_C as PSVC_DUPLICATION_C",
	"FIL_SDS_ORDER_ITEM___PSVC_MANUAL_ADJUSTED_PRICE_C as PSVC_MANUAL_ADJUSTED_PRICE_C",
	"FIL_SDS_ORDER_ITEM___PSVC_APPOINTMENT_DATE_C as PSVC_APPOINTMENT_DATE_C",
	"FIL_SDS_ORDER_ITEM___PSVC_ASSOCIATE_C as PSVC_ASSOCIATE_C",
	"FIL_SDS_ORDER_ITEM___PSVC_AUTO_CALCULATED_PRICE_FORMULA_C as PSVC_AUTO_CALCULATED_PRICE_FORMULA_C",
	"FIL_SDS_ORDER_ITEM___PSVC_IS_HIDDEN_C as PSVC_IS_HIDDEN_C",
	"FIL_SDS_ORDER_ITEM___PSVC_CHANGE_COMMISSION_TO_C as PSVC_CHANGE_COMMISSION_TO_C",
	"FIL_SDS_ORDER_ITEM___PSVC_CHANGE_TO_COMMISSION_PERCENTAGE_C as PSVC_CHANGE_TO_COMMISSION_PERCENTAGE_C",
	"FIL_SDS_ORDER_ITEM___PSVC_COMMISSION_RECEIVER_C as PSVC_COMMISSION_RECEIVER_C",
	"FIL_SDS_ORDER_ITEM___PSVC_EXPRESS_C as PSVC_EXPRESS_C",
	"FIL_SDS_ORDER_ITEM___PSVC_RESOURCE_COMMISSION_C as PSVC_RESOURCE_COMMISSION_C",
	"FIL_SDS_ORDER_ITEM___PSVC_ORDER_PRODUCT_NUMBER_C as PSVC_ORDER_PRODUCT_NUMBER_C",
	"FIL_SDS_ORDER_ITEM___PSVC_ORDER_PRODUCT_SMS_ID_C as PSVC_ORDER_PRODUCT_SMS_ID_C",
	"FIL_SDS_ORDER_ITEM___PSVC_TOTAL_PRICE_FOR_POS_C as PSVC_TOTAL_PRICE_FOR_POS_C",
	"FIL_SDS_ORDER_ITEM___PSVC_UNIT_PRICE_FOR_POS_C as PSVC_UNIT_PRICE_FOR_POS_C",
	"FIL_SDS_ORDER_ITEM___LINE_ITEM_TOTAL_TAX_C as LINE_ITEM_TOTAL_TAX_C",
	"FIL_SDS_ORDER_ITEM___PSVC_TOTAL_GROOM_PAY_ELIGIBLE_PRICE_C as PSVC_TOTAL_GROOM_PAY_ELIGIBLE_PRICE_C",
	"FIL_SDS_ORDER_ITEM___PSVC_ORIGINAL_UNIT_PRICE_C as PSVC_ORIGINAL_UNIT_PRICE_C",
	"FIL_SDS_ORDER_ITEM___PSVC_IS_PREPAID_C as PSVC_IS_PREPAID_C",
	"0 as HARD_DELETED_FLAG",
	"CURRENT_TIMESTAMP as UPDATE_TSTMP",
	"IF (FIL_SDS_ORDER_ITEM___i_LOAD_TSTMP IS NULL, CURRENT_TIMESTAMP, FIL_SDS_ORDER_ITEM___i_LOAD_TSTMP) as LOAD_TSTMP",
	"IF (FIL_SDS_ORDER_ITEM___i_SDS_ORDER_ITEM_ID IS NULL, 1, 2) as o_UPDATE_VALIDATOR"
)

# COMMAND ----------
# Processing node UPD_SDS_ORDER_ITEM, type UPDATE_STRATEGY . Note: using additional SELECT to rename incoming columns
# COLUMN COUNT: 50

# for each involved DataFrame, append the dataframe name to each column
EXP_SDS_ORDER_ITEM_temp = EXP_SDS_ORDER_ITEM.toDF(*["EXP_SDS_ORDER_ITEM___" + col for col in EXP_SDS_ORDER_ITEM.columns])

UPD_SDS_ORDER_ITEM = EXP_SDS_ORDER_ITEM_temp.selectExpr(
	"EXP_SDS_ORDER_ITEM___ID as ID",
	"EXP_SDS_ORDER_ITEM___PRODUCT2_ID as PRODUCT2_ID",
	"EXP_SDS_ORDER_ITEM___IS_DELETED as IS_DELETED",
	"EXP_SDS_ORDER_ITEM___ORDER_ID as ORDER_ID",
	"EXP_SDS_ORDER_ITEM___PRICE_BOOK_ENTRY_ID as PRICE_BOOK_ENTRY_ID",
	"EXP_SDS_ORDER_ITEM___ORIGINAL_ORDER_ITEM_ID as ORIGINAL_ORDER_ITEM_ID",
	"EXP_SDS_ORDER_ITEM___QUOTE_LINE_ITEM_ID as QUOTE_LINE_ITEM_ID",
	"EXP_SDS_ORDER_ITEM___AVAILABLE_QUANTITY as AVAILABLE_QUANTITY",
	"EXP_SDS_ORDER_ITEM___QUANTITY as QUANTITY",
	"EXP_SDS_ORDER_ITEM___CURRENCY_ISO_CODE as CURRENCY_ISO_CODE",
	"EXP_SDS_ORDER_ITEM___UNIT_PRICE as UNIT_PRICE",
	"EXP_SDS_ORDER_ITEM___LIST_PRICE as LIST_PRICE",
	"EXP_SDS_ORDER_ITEM___TOTAL_PRICE as TOTAL_PRICE",
	"EXP_SDS_ORDER_ITEM___SERVICE_DATE as SERVICE_DATE",
	"EXP_SDS_ORDER_ITEM___END_DATE as END_DAT",
	"EXP_SDS_ORDER_ITEM___DESCRIPTION as DESCRIPTION",
	"EXP_SDS_ORDER_ITEM___CREATED_DATE as CREATED_DATE",
	"EXP_SDS_ORDER_ITEM___CREATED_BY_ID as CREATED_BY_ID",
	"EXP_SDS_ORDER_ITEM___LAST_MODIFIED_DATE as LAST_MODIFIED_DATE",
	"EXP_SDS_ORDER_ITEM___LAST_MODIFIED_BY_ID as LAST_MODIFIED_BY_ID",
	"EXP_SDS_ORDER_ITEM___SYSTEM_MOD_STAMP as SYSTEM_MOD_STAMP",
	"EXP_SDS_ORDER_ITEM___ORDER_ITEM_NUMBER as ORDER_ITEM_NUMBER",
	"EXP_SDS_ORDER_ITEM___PSVC_COMMISSION_AMOUNT_C as PSVC_COMMISSION_AMOUNT_C",
	"EXP_SDS_ORDER_ITEM___PSVC_IS_FOR_QUOTE_C as PSVC_IS_FOR_QUOTE_C",
	"EXP_SDS_ORDER_ITEM___PSVC_PRICE_MANUAL_ADJUSTMENT_REASON_C as PSVC_PRICE_MANUAL_ADJUSTMENT_REASON_C",
	"EXP_SDS_ORDER_ITEM___PSVC_WORK_ORDER_C as PSVC_WORK_ORDER_C",
	"EXP_SDS_ORDER_ITEM___PSVC_AUTO_CALCULATED_PRICE_C as PSVC_AUTO_CALCULATED_PRICE_C",
	"EXP_SDS_ORDER_ITEM___PSVC_DUPLICATION_C as PSVC_DUPLICATION_C",
	"EXP_SDS_ORDER_ITEM___PSVC_MANUAL_ADJUSTED_PRICE_C as PSVC_MANUAL_ADJUSTED_PRICE_C",
	"EXP_SDS_ORDER_ITEM___PSVC_APPOINTMENT_DATE_C as PSVC_APPOINTMENT_DATE_C",
	"EXP_SDS_ORDER_ITEM___PSVC_ASSOCIATE_C as PSVC_ASSOCIATE_C",
	"EXP_SDS_ORDER_ITEM___PSVC_AUTO_CALCULATED_PRICE_FORMULA_C as PSVC_AUTO_CALCULATED_PRICE_FORMULA_C",
	"EXP_SDS_ORDER_ITEM___PSVC_IS_HIDDEN_C as PSVC_IS_HIDDEN_C",
	"EXP_SDS_ORDER_ITEM___PSVC_CHANGE_COMMISSION_TO_C as PSVC_CHANGE_COMMISSION_TO_C",
	"EXP_SDS_ORDER_ITEM___PSVC_CHANGE_TO_COMMISSION_PERCENTAGE_C as PSVC_CHANGE_TO_COMMISSION_PERCENTAGE_C",
	"EXP_SDS_ORDER_ITEM___PSVC_COMMISSION_RECEIVER_C as PSVC_COMMISSION_RECEIVER_C",
	"EXP_SDS_ORDER_ITEM___PSVC_EXPRESS_C as PSVC_EXPRESS_C",
	"EXP_SDS_ORDER_ITEM___PSVC_RESOURCE_COMMISSION_C as PSVC_RESOURCE_COMMISSION_C",
	"EXP_SDS_ORDER_ITEM___PSVC_ORDER_PRODUCT_NUMBER_C as PSVC_ORDER_PRODUCT_NUMBER_C",
	"EXP_SDS_ORDER_ITEM___PSVC_ORDER_PRODUCT_SMS_ID_C as PSVC_ORDER_PRODUCT_SMS_ID_C",
	"EXP_SDS_ORDER_ITEM___PSVC_TOTAL_PRICE_FOR_POS_C as PSVC_TOTAL_PRICE_FOR_POS_C",
	"EXP_SDS_ORDER_ITEM___PSVC_UNIT_PRICE_FOR_POS_C as PSVC_UNIT_PRICE_FOR_POS_C",
	"EXP_SDS_ORDER_ITEM___LINE_ITEM_TOTAL_TAX_C as LINE_ITEM_TOTAL_TAX_C",
	"EXP_SDS_ORDER_ITEM___PSVC_TOTAL_GROOM_PAY_ELIGIBLE_PRICE_C as PSVC_TOTAL_GROOM_PAY_ELIGIBLE_PRICE_C",
	"EXP_SDS_ORDER_ITEM___PSVC_ORIGINAL_UNIT_PRICE_C as PSVC_ORIGINAL_UNIT_PRICE_C",
	"EXP_SDS_ORDER_ITEM___PSVC_IS_PREPAID_C as PSVC_IS_PREPAID_C",
	"EXP_SDS_ORDER_ITEM___HARD_DELETED_FLAG as HARD_DELETED_FLAG",
	"EXP_SDS_ORDER_ITEM___UPDATE_TSTMP as UPDATE_TSTMP",
	"EXP_SDS_ORDER_ITEM___LOAD_TSTMP as LOAD_TSTMP",
	"EXP_SDS_ORDER_ITEM___o_UPDATE_VALIDATOR as o_UPDATE_VALIDATOR")\
	.withColumn('pyspark_data_action', when(EXP_SDS_ORDER_ITEM_temp.o_UPDATE_VALIDATOR ==(lit(1)) , lit(0)) .when(EXP_SDS_ORDER_ITEM_temp.o_UPDATE_VALIDATOR ==(lit(2)) , lit(1)))

# COMMAND ----------
# Processing node Shortcut_to_SDS_ORDER_ITEM_3, type TARGET 
# COLUMN COUNT: 49


Shortcut_to_SDS_ORDER_ITEM_3 = UPD_SDS_ORDER_ITEM.selectExpr(
	"CAST(ID AS STRING) as SDS_ORDER_ITEM_ID",
	"CAST(DESCRIPTION AS STRING) as SDS_ORDER_ITEM_DESC",
	"CAST(ORDER_ID AS STRING) as SDS_ORDER_ID",
	"CAST(PSVC_WORK_ORDER_C AS STRING) as SDS_WORK_ORDER_ID",
	"CAST(PRODUCT2_ID AS STRING) as SDS_PRODUCT_ID",
	"CAST(ORDER_ITEM_NUMBER AS STRING) as SDS_ORDER_ITEM_NBR",
	"CAST(PSVC_ORDER_PRODUCT_NUMBER_C AS STRING) as SDS_ORDER_PRODUCT_NBR",
	"CAST(ORIGINAL_ORDER_ITEM_ID AS STRING) as SDS_ORIG_ORDER_ITEM_ID",
	"CAST(QUOTE_LINE_ITEM_ID AS STRING) as SDS_QUOTE_LINE_ITEM_ID",
	"CAST(PRICE_BOOK_ENTRY_ID AS STRING) as SDS_PRICEBOOK_ENTRY_ID",
	"CAST(PSVC_IS_PREPAID_C AS TINYINT) as PREPAID_FLAG",
	"CAST(AVAILABLE_QUANTITY AS DECIMAL(18,2)) as ORDER_ITEM_AVAILABLE_QTY",
	"CAST(QUANTITY AS DECIMAL(18,2)) as ORDER_ITEM_QTY",
	"CAST(UNIT_PRICE AS DECIMAL(18,2)) as UNIT_PRICE",
	"CAST(PSVC_UNIT_PRICE_FOR_POS_C AS DECIMAL(18,2)) as POS_UNIT_PRICE",
	"CAST(LIST_PRICE AS DECIMAL(18,2)) as LIST_PRICE",
	"CAST(PSVC_ORIGINAL_UNIT_PRICE_C AS DECIMAL(18,2)) as ORIG_UNIT_PRICE",
	"CAST(PSVC_MANUAL_ADJUSTED_PRICE_C AS DECIMAL(18,2)) as MANUAL_ADJUSTED_PRICE",
	"CAST(PSVC_PRICE_MANUAL_ADJUSTMENT_REASON_C AS STRING) as PRICE_MANUAL_ADJ_REASON",
	"CAST(PSVC_AUTO_CALCULATED_PRICE_C AS DECIMAL(18,2)) as AUTO_CALCULATED_PRICE",
	"CAST(LINE_ITEM_TOTAL_TAX_C AS DECIMAL(9,5)) as LINE_ITEM_TOTAL_TAX",
	"CAST(TOTAL_PRICE AS DECIMAL(18,2)) as TOTAL_PRICE",
	"CAST(PSVC_TOTAL_PRICE_FOR_POS_C AS DECIMAL(18,2)) as POS_TOTAL_PRICE",
	"CAST(PSVC_TOTAL_GROOM_PAY_ELIGIBLE_PRICE_C AS DECIMAL(18,2)) as TOTAL_GROOM_PAY_ELIGIBLE_PRICE",
	"CAST(PSVC_COMMISSION_AMOUNT_C AS DECIMAL(18,2)) as COMMISSION_AMT",
	"CAST(PSVC_CHANGE_COMMISSION_TO_C AS STRING) as CHANGED_COMMISSION_TO_SERVICE_RESOURCE_ID",
	"CAST(PSVC_COMMISSION_RECEIVER_C AS STRING) as COMMISSION_RECEIVER_ASSOCIATE_NAME",
	"CAST(PSVC_CHANGE_TO_COMMISSION_PERCENTAGE_C AS DECIMAL(6,2)) as CHANGED_TO_COMMISSION_PCT",
	"CAST(PSVC_RESOURCE_COMMISSION_C AS DECIMAL(18,2)) as RESOURCE_COMMISSION_AMT",
	"CAST(PSVC_DUPLICATION_C AS STRING) as DUPLICATION",
	"CAST(PSVC_APPOINTMENT_DATE_C AS TIMESTAMP) as APPOINTMENT_TSTMP",
	"CAST(PSVC_ASSOCIATE_C AS STRING) as ASSOCIATE_NAME",
	"CAST(PSVC_AUTO_CALCULATED_PRICE_FORMULA_C AS DECIMAL(18,2)) as AUTO_CALCULATED_PRICE_FORMULA",
	"CAST(PSVC_EXPRESS_C AS TINYINT) as EXPRESS_FLAG",
	"CAST(PSVC_IS_HIDDEN_C AS TINYINT) as HIDDEN_FLAG",
	"CAST(PSVC_IS_FOR_QUOTE_C AS TINYINT) as FOR_QUOTE_FLAG",
	"CAST(SERVICE_DATE AS TIMESTAMP) as SERVICE_TSTMP",
	"CAST(END_DAT AS TIMESTAMP) as END_TSTMP",
	"CAST(PSVC_ORDER_PRODUCT_SMS_ID_C AS STRING) as SMS_ORDER_ITEM_ID",
	"CAST(CURRENCY_ISO_CODE AS STRING) as CURRENCY_ISO_CD",
	"CAST(IS_DELETED AS TINYINT) as DELETED_FLAG",
	"CAST(HARD_DELETED_FLAG AS TINYINT) as HARD_DELETED_FLAG",
	"CAST(SYSTEM_MOD_STAMP AS TIMESTAMP) as SDS_SYSTEM_MODIFIED_TSTMP",
	"CAST(LAST_MODIFIED_DATE AS TIMESTAMP) as SDS_LAST_MODIFIED_TSTMP",
	"CAST(LAST_MODIFIED_BY_ID AS STRING) as SDS_LAST_MODIFIED_BY_ID",
	"CAST(CREATED_DATE AS TIMESTAMP) as SDS_CREATED_TSTMP",
	"CAST(CREATED_BY_ID AS STRING) as SDS_CREATED_BY_ID",
	"CAST(UPDATE_TSTMP AS TIMESTAMP) as UPDATE_TSTMP",
	"CAST(LOAD_TSTMP AS TIMESTAMP) as LOAD_TSTMP",
	"UPD_SDS_ORDER_ITEM.pyspark_data_action as pyspark_data_action"
)

try:
  primary_key = """source.SDS_ORDER_ITEM_ID = target.SDS_ORDER_ITEM_ID"""
  refined_perf_table = f"{legacy}.SDS_ORDER_ITEM"
  executeMerge(Shortcut_to_SDS_ORDER_ITEM_3, refined_perf_table, primary_key)
  logger.info(f"Merge with {refined_perf_table} completed]")
  logPrevRunDt("SDS_ORDER_ITEM", "SDS_ORDER_ITEM", "Completed", "N/A", f"{raw}.log_run_details")
except Exception as e:
  logPrevRunDt("SDS_ORDER_ITEM", "SDS_ORDER_ITEM","Failed",str(e), f"{raw}.log_run_details", )
  raise e
	