#Code converted on 2023-07-26 09:54:13
import os
import argparse
from pyspark.sql import *
from pyspark.sql.functions import *
from pyspark.sql.window import Window
from pyspark.sql.types import *
from datetime import datetime
from Datalake.utils.genericUtilities import *
from Datalake.utils.configs import *
from Datalake.utils.mergeUtils import *
from Datalake.utils.logger import *
# COMMAND ----------

parser = argparse.ArgumentParser()
spark = SparkSession.getActiveSession()
parser.add_argument('env', type=str, help='Env Variable')

args = parser.parse_args()
env = args.env

if env is None or env == '':
    raise ValueError('env is not set')

refine = getEnvPrefix(env) + 'refine'
raw = getEnvPrefix(env) + 'raw'
legacy = getEnvPrefix(env) + 'legacy'


# COMMAND ----------
# Processing node SQ_Shortcut_to_SALON_ACADEMY_ASSESSMENT_REASON, type SOURCE 
# COLUMN COUNT: 8

SQ_Shortcut_to_SALON_ACADEMY_ASSESSMENT_REASON = spark.sql(f"""SELECT
SALON_ACADEMY_ASSESSMENT_REASON.SALON_ACADEMY_ASSESSMENT_REASON_ID,
SALON_ACADEMY_ASSESSMENT_REASON.SALON_ACADEMY_ASSESSMENT_ID,
SALON_ACADEMY_ASSESSMENT_REASON.REASON_TEXT,
SALON_ACADEMY_ASSESSMENT_REASON.CREATED_TSTMP,
SALON_ACADEMY_ASSESSMENT_REASON.CREATED_BY,
SALON_ACADEMY_ASSESSMENT_REASON.MODIFIED_TSTMP,
SALON_ACADEMY_ASSESSMENT_REASON.MODIFIED_BY,
SALON_ACADEMY_ASSESSMENT_REASON.LOAD_TSTMP
FROM {legacy}.SALON_ACADEMY_ASSESSMENT_REASON""").withColumn("sys_row_id", monotonically_increasing_id())

# COMMAND ----------
# Processing node SQ_Shortcut_to_SALON_ACADEMY_ASSESSMENT_REASON_PRE, type SOURCE 
# COLUMN COUNT: 7

SQ_Shortcut_to_SALON_ACADEMY_ASSESSMENT_REASON_PRE = spark.sql(f"""SELECT
SALON_ACADEMY_ASSESSMENT_REASON_PRE.SALON_ACADEMY_ASSESSMENT_REASON_ID,
SALON_ACADEMY_ASSESSMENT_REASON_PRE.SALON_ACADEMY_ASSESSMENT_ID,
SALON_ACADEMY_ASSESSMENT_REASON_PRE.REASON_TEXT,
SALON_ACADEMY_ASSESSMENT_REASON_PRE.CREATED_TSTMP,
SALON_ACADEMY_ASSESSMENT_REASON_PRE.CREATED_BY,
SALON_ACADEMY_ASSESSMENT_REASON_PRE.MODIFIED_TSTMP,
SALON_ACADEMY_ASSESSMENT_REASON_PRE.MODIFIED_BY
FROM {raw}.SALON_ACADEMY_ASSESSMENT_REASON_PRE""").withColumn("sys_row_id", monotonically_increasing_id())

# COMMAND ----------
# Processing node JNR_SALON_ACADEMY_ASSESSMENT_REASON, type JOINER . Note: using additional SELECT to rename incoming columns
# COLUMN COUNT: 15

# for each involved DataFrame, append the dataframe name to each column
SQ_Shortcut_to_SALON_ACADEMY_ASSESSMENT_REASON_temp = SQ_Shortcut_to_SALON_ACADEMY_ASSESSMENT_REASON.toDF(*["SQ_Shortcut_to_SALON_ACADEMY_ASSESSMENT_REASON___" + col for col in SQ_Shortcut_to_SALON_ACADEMY_ASSESSMENT_REASON.columns])
SQ_Shortcut_to_SALON_ACADEMY_ASSESSMENT_REASON_PRE_temp = SQ_Shortcut_to_SALON_ACADEMY_ASSESSMENT_REASON_PRE.toDF(*["SQ_Shortcut_to_SALON_ACADEMY_ASSESSMENT_REASON_PRE___" + col for col in SQ_Shortcut_to_SALON_ACADEMY_ASSESSMENT_REASON_PRE.columns])

JNR_SALON_ACADEMY_ASSESSMENT_REASON = SQ_Shortcut_to_SALON_ACADEMY_ASSESSMENT_REASON_PRE_temp.join(SQ_Shortcut_to_SALON_ACADEMY_ASSESSMENT_REASON_temp,[SQ_Shortcut_to_SALON_ACADEMY_ASSESSMENT_REASON_PRE_temp.SQ_Shortcut_to_SALON_ACADEMY_ASSESSMENT_REASON_PRE___SALON_ACADEMY_ASSESSMENT_REASON_ID == SQ_Shortcut_to_SALON_ACADEMY_ASSESSMENT_REASON_temp.SQ_Shortcut_to_SALON_ACADEMY_ASSESSMENT_REASON___SALON_ACADEMY_ASSESSMENT_REASON_ID],'left_outer').selectExpr(
	"SQ_Shortcut_to_SALON_ACADEMY_ASSESSMENT_REASON_PRE___SALON_ACADEMY_ASSESSMENT_REASON_ID as SALON_ACADEMY_ASSESSMENT_REASON_ID",
	"SQ_Shortcut_to_SALON_ACADEMY_ASSESSMENT_REASON_PRE___SALON_ACADEMY_ASSESSMENT_ID as SALON_ACADEMY_ASSESSMENT_ID",
	"SQ_Shortcut_to_SALON_ACADEMY_ASSESSMENT_REASON_PRE___REASON_TEXT as REASON_TEXT",
	"SQ_Shortcut_to_SALON_ACADEMY_ASSESSMENT_REASON_PRE___CREATED_TSTMP as CREATED_TSTMP",
	"SQ_Shortcut_to_SALON_ACADEMY_ASSESSMENT_REASON_PRE___CREATED_BY as CREATED_BY",
	"SQ_Shortcut_to_SALON_ACADEMY_ASSESSMENT_REASON_PRE___MODIFIED_TSTMP as MODIFIED_TSTMP",
	"SQ_Shortcut_to_SALON_ACADEMY_ASSESSMENT_REASON_PRE___MODIFIED_BY as MODIFIED_BY",
	"SQ_Shortcut_to_SALON_ACADEMY_ASSESSMENT_REASON___SALON_ACADEMY_ASSESSMENT_REASON_ID as i_SALON_ACADEMY_ASSESSMENT_REASON_ID",
	"SQ_Shortcut_to_SALON_ACADEMY_ASSESSMENT_REASON___SALON_ACADEMY_ASSESSMENT_ID as i_SALON_ACADEMY_ASSESSMENT_ID",
	"SQ_Shortcut_to_SALON_ACADEMY_ASSESSMENT_REASON___REASON_TEXT as i_REASON_TEXT",
	"SQ_Shortcut_to_SALON_ACADEMY_ASSESSMENT_REASON___CREATED_TSTMP as i_CREATED_TSTMP",
	"SQ_Shortcut_to_SALON_ACADEMY_ASSESSMENT_REASON___CREATED_BY as i_CREATED_BY",
	"SQ_Shortcut_to_SALON_ACADEMY_ASSESSMENT_REASON___MODIFIED_TSTMP as i_MODIFIED_TSTMP",
	"SQ_Shortcut_to_SALON_ACADEMY_ASSESSMENT_REASON___MODIFIED_BY as i_MODIFIED_BY",
	"SQ_Shortcut_to_SALON_ACADEMY_ASSESSMENT_REASON___LOAD_TSTMP as i_LOAD_TSTMP")

# COMMAND ----------
# Processing node FIL_SALON_ACADEMY_ASSESSMENT_REASON, type FILTER 
# COLUMN COUNT: 15

# for each involved DataFrame, append the dataframe name to each column
JNR_SALON_ACADEMY_ASSESSMENT_REASON_temp = JNR_SALON_ACADEMY_ASSESSMENT_REASON.toDF(*["JNR_SALON_ACADEMY_ASSESSMENT_REASON___" + col for col in JNR_SALON_ACADEMY_ASSESSMENT_REASON.columns])

FIL_SALON_ACADEMY_ASSESSMENT_REASON = JNR_SALON_ACADEMY_ASSESSMENT_REASON_temp.selectExpr(
	"JNR_SALON_ACADEMY_ASSESSMENT_REASON___SALON_ACADEMY_ASSESSMENT_REASON_ID as SALON_ACADEMY_ASSESSMENT_REASON_ID",
	"JNR_SALON_ACADEMY_ASSESSMENT_REASON___SALON_ACADEMY_ASSESSMENT_ID as SALON_ACADEMY_ASSESSMENT_ID",
	"JNR_SALON_ACADEMY_ASSESSMENT_REASON___REASON_TEXT as REASON_TEXT",
	"JNR_SALON_ACADEMY_ASSESSMENT_REASON___CREATED_TSTMP as CREATED_TSTMP",
	"JNR_SALON_ACADEMY_ASSESSMENT_REASON___CREATED_BY as CREATED_BY",
	"JNR_SALON_ACADEMY_ASSESSMENT_REASON___MODIFIED_TSTMP as MODIFIED_TSTMP",
	"JNR_SALON_ACADEMY_ASSESSMENT_REASON___MODIFIED_BY as MODIFIED_BY",
	"JNR_SALON_ACADEMY_ASSESSMENT_REASON___i_SALON_ACADEMY_ASSESSMENT_REASON_ID as i_SALON_ACADEMY_ASSESSMENT_REASON_ID",
	"JNR_SALON_ACADEMY_ASSESSMENT_REASON___i_SALON_ACADEMY_ASSESSMENT_ID as i_SALON_ACADEMY_ASSESSMENT_ID",
	"JNR_SALON_ACADEMY_ASSESSMENT_REASON___i_REASON_TEXT as i_REASON_TEXT",
	"JNR_SALON_ACADEMY_ASSESSMENT_REASON___i_CREATED_TSTMP as i_CREATED_TSTMP",
	"JNR_SALON_ACADEMY_ASSESSMENT_REASON___i_CREATED_BY as i_CREATED_BY",
	"JNR_SALON_ACADEMY_ASSESSMENT_REASON___i_MODIFIED_TSTMP as i_MODIFIED_TSTMP",
	"JNR_SALON_ACADEMY_ASSESSMENT_REASON___i_MODIFIED_BY as i_MODIFIED_BY",
	"JNR_SALON_ACADEMY_ASSESSMENT_REASON___i_LOAD_TSTMP as i_LOAD_TSTMP").filter("i_SALON_ACADEMY_ASSESSMENT_REASON_ID IS NULL OR (NOT i_SALON_ACADEMY_ASSESSMENT_REASON_ID IS NULL AND (CASE WHEN SALON_ACADEMY_ASSESSMENT_ID IS NULL THEN 0 ELSE SALON_ACADEMY_ASSESSMENT_ID END) != (CASE WHEN i_SALON_ACADEMY_ASSESSMENT_ID IS NULL THEN 0 ELSE i_SALON_ACADEMY_ASSESSMENT_ID END) OR (CASE WHEN REASON_TEXT IS NULL THEN '' ELSE REASON_TEXT END) != (CASE WHEN i_REASON_TEXT IS NULL THEN '' ELSE i_REASON_TEXT END) OR (CASE WHEN CREATED_TSTMP IS NULL THEN date'9999-12-31' ELSE CREATED_TSTMP END) != (CASE WHEN i_CREATED_TSTMP IS NULL THEN date'9999-12-31' ELSE i_CREATED_TSTMP END) OR (CASE WHEN CREATED_BY IS NULL THEN '' ELSE CREATED_BY END) != (CASE WHEN i_CREATED_BY IS NULL THEN '' ELSE i_CREATED_BY END) OR (CASE WHEN MODIFIED_TSTMP IS NULL THEN date'9999-12-31' ELSE MODIFIED_TSTMP END) != (CASE WHEN i_MODIFIED_TSTMP IS NULL THEN date'9999-12-31' ELSE i_MODIFIED_TSTMP END) OR (CASE WHEN MODIFIED_BY IS NULL THEN '' ELSE MODIFIED_BY END) != (CASE WHEN i_MODIFIED_BY IS NULL THEN '' ELSE i_MODIFIED_BY END))").withColumn("sys_row_id", monotonically_increasing_id())


# COMMAND ----------
# Processing node EXP_SALON_ACADEMY_ASSESSMENT_REASON, type EXPRESSION 
# COLUMN COUNT: 10

# for each involved DataFrame, append the dataframe name to each column
FIL_SALON_ACADEMY_ASSESSMENT_REASON_temp = FIL_SALON_ACADEMY_ASSESSMENT_REASON.toDF(*["FIL_SALON_ACADEMY_ASSESSMENT_REASON___" + col for col in FIL_SALON_ACADEMY_ASSESSMENT_REASON.columns])

EXP_SALON_ACADEMY_ASSESSMENT_REASON = FIL_SALON_ACADEMY_ASSESSMENT_REASON_temp.selectExpr(
	"FIL_SALON_ACADEMY_ASSESSMENT_REASON___sys_row_id as sys_row_id",
	"FIL_SALON_ACADEMY_ASSESSMENT_REASON___SALON_ACADEMY_ASSESSMENT_REASON_ID as SALON_ACADEMY_ASSESSMENT_REASON_ID",
	"FIL_SALON_ACADEMY_ASSESSMENT_REASON___SALON_ACADEMY_ASSESSMENT_ID as SALON_ACADEMY_ASSESSMENT_ID",
	"FIL_SALON_ACADEMY_ASSESSMENT_REASON___REASON_TEXT as REASON_TEXT",
	"FIL_SALON_ACADEMY_ASSESSMENT_REASON___CREATED_TSTMP as CREATED_TSTMP",
	"FIL_SALON_ACADEMY_ASSESSMENT_REASON___CREATED_BY as CREATED_BY",
	"FIL_SALON_ACADEMY_ASSESSMENT_REASON___MODIFIED_TSTMP as MODIFIED_TSTMP",
	"FIL_SALON_ACADEMY_ASSESSMENT_REASON___MODIFIED_BY as MODIFIED_BY",
	"CURRENT_TIMESTAMP as UPDATE_TSTMP",
	"IF (FIL_SALON_ACADEMY_ASSESSMENT_REASON___i_LOAD_TSTMP IS NULL, CURRENT_TIMESTAMP, FIL_SALON_ACADEMY_ASSESSMENT_REASON___i_LOAD_TSTMP) as LOAD_TSTMP",
	"IF (FIL_SALON_ACADEMY_ASSESSMENT_REASON___i_SALON_ACADEMY_ASSESSMENT_REASON_ID IS NULL, 1, 2) as o_UPDATE_VALIDATOR"
)

# COMMAND ----------
# Processing node UPD_SALON_ACADEMY_ASSESSMENT_REASON, type UPDATE_STRATEGY 
# COLUMN COUNT: 10

# for each involved DataFrame, append the dataframe name to each column
EXP_SALON_ACADEMY_ASSESSMENT_REASON_temp = EXP_SALON_ACADEMY_ASSESSMENT_REASON.toDF(*["EXP_SALON_ACADEMY_ASSESSMENT_REASON___" + col for col in EXP_SALON_ACADEMY_ASSESSMENT_REASON.columns])

UPD_SALON_ACADEMY_ASSESSMENT_REASON = EXP_SALON_ACADEMY_ASSESSMENT_REASON_temp.selectExpr(
	"EXP_SALON_ACADEMY_ASSESSMENT_REASON___SALON_ACADEMY_ASSESSMENT_REASON_ID as SALON_ACADEMY_ASSESSMENT_REASON_ID",
	"EXP_SALON_ACADEMY_ASSESSMENT_REASON___SALON_ACADEMY_ASSESSMENT_ID as SALON_ACADEMY_ASSESSMENT_ID",
	"EXP_SALON_ACADEMY_ASSESSMENT_REASON___REASON_TEXT as REASON_TEXT",
	"EXP_SALON_ACADEMY_ASSESSMENT_REASON___CREATED_TSTMP as CREATED_TSTMP",
	"EXP_SALON_ACADEMY_ASSESSMENT_REASON___CREATED_BY as CREATED_BY",
	"EXP_SALON_ACADEMY_ASSESSMENT_REASON___MODIFIED_TSTMP as MODIFIED_TSTMP",
	"EXP_SALON_ACADEMY_ASSESSMENT_REASON___MODIFIED_BY as MODIFIED_BY",
	"EXP_SALON_ACADEMY_ASSESSMENT_REASON___UPDATE_TSTMP as UPDATE_TSTMP",
	"EXP_SALON_ACADEMY_ASSESSMENT_REASON___LOAD_TSTMP as LOAD_TSTMP",
	"EXP_SALON_ACADEMY_ASSESSMENT_REASON___o_UPDATE_VALIDATOR as o_UPDATE_VALIDATOR") \
	.withColumn('pyspark_data_action', when(col('o_UPDATE_VALIDATOR') ==(lit(1)) , lit(0)) .when(col('o_UPDATE_VALIDATOR') ==(lit(2)) , lit(1)))

# COMMAND ----------
# Processing node Shortcut_to_SALON_ACADEMY_ASSESSMENT_REASON, type TARGET 
# COLUMN COUNT: 9


Shortcut_to_SALON_ACADEMY_ASSESSMENT_REASON = UPD_SALON_ACADEMY_ASSESSMENT_REASON.selectExpr(
	"SALON_ACADEMY_ASSESSMENT_REASON_ID as SALON_ACADEMY_ASSESSMENT_REASON_ID",
	"SALON_ACADEMY_ASSESSMENT_ID as SALON_ACADEMY_ASSESSMENT_ID",
	"CAST(REASON_TEXT AS STRING) as REASON_TEXT",
	"CAST(CREATED_TSTMP AS TIMESTAMP) as CREATED_TSTMP",
	"CAST(CREATED_BY AS STRING) as CREATED_BY",
	"CAST(MODIFIED_TSTMP AS TIMESTAMP) as MODIFIED_TSTMP",
	"CAST(MODIFIED_BY AS STRING) as MODIFIED_BY",
	"CAST(UPDATE_TSTMP AS TIMESTAMP) as UPDATE_TSTMP",
	"CAST(LOAD_TSTMP AS TIMESTAMP) as LOAD_TSTMP",
	"pyspark_data_action as pyspark_data_action"
)

try:
	primary_key = """source.SALON_ACADEMY_ASSESSMENT_REASON_ID = target.SALON_ACADEMY_ASSESSMENT_REASON_ID"""
	refined_perf_table = f"{legacy}.SALON_ACADEMY_ASSESSMENT_REASON"
	executeMerge(Shortcut_to_SALON_ACADEMY_ASSESSMENT_REASON, refined_perf_table, primary_key)
	logger.info(f"Merge with {refined_perf_table} completed]")
	logPrevRunDt("SALON_ACADEMY_ASSESSMENT_REASON", "SALON_ACADEMY_ASSESSMENT_REASON", "Completed", "N/A", f"{raw}.log_run_details")
except Exception as e:
	logPrevRunDt("SALON_ACADEMY_ASSESSMENT_REASON", "SALON_ACADEMY_ASSESSMENT_REASON","Failed",str(e), f"{raw}.log_run_details")
	raise e
		