# Databricks notebook source
#Code converted on 2023-10-06 15:46:13
import os
from pyspark.sql import *
from pyspark.sql.functions import *
from datetime import datetime
from Datalake.utils.genericUtilities import *
from Datalake.utils.configs import *
from Datalake.utils.mergeUtils import *
from Datalake.utils.logger import *
from Datalake.utils.pk import *

# COMMAND ----------

spark = SparkSession.getActiveSession()
dbutils = DBUtils(spark)
dbutils.widgets.text(name = 'env', defaultValue = 'dev')
env = dbutils.widgets.get('env')

if env is None or env == '':
    raise ValueError('env is not set')

raw = getEnvPrefix(env) + 'raw'
legacy = getEnvPrefix(env) + 'legacy'
refine = getEnvPrefix(env) + 'refine'

# Set global variables
starttime = datetime.now() #start timestamp of the script


# COMMAND ----------

# Processing node SQ_Shortcut_to_DP_SITE_VEND_PRE1, type SOURCE 
# COLUMN COUNT: 81

SQ_Shortcut_to_DP_SITE_VEND_PRE1 = spark.sql(f"""SELECT SITE_PROFILE.LOCATION_ID, DP_SITE_VEND_PRE.STORE_NBR, DP_SITE_VEND_PRE.VENDOR_ID, decode(DP_SITE_VEND_PRE.VENDOR_SUBGROUP_ID,'',' ',DP_SITE_VEND_PRE.VENDOR_SUBGROUP_ID) VENDOR_SUBGROUP_ID, DP_SITE_VEND_PRE.DP_PURCH_GROUP_ID, DP_SITE_VEND_PRE.DUE_BASED_ON_CD, DP_SITE_VEND_PRE.ORDER_DAY_OF_WK_ARRAY, DP_SITE_VEND_PRE.WEEK_FREQ_CD, DP_SITE_VEND_PRE.QUOTED_LT_DAY_CNT, DP_SITE_VEND_PRE.LT_DAY_CNT, DP_SITE_VEND_PRE.LOAD_DT, DP_SITE_VEND_PRE.MANDT, DP_SITE_VEND_PRE.DPR_ORDER_ARRAY, DP_SITE_VEND_PRE.PROD_LEADTIME, DP_SITE_VEND_PRE.TRANSIT_LEADTIME, DP_SITE_VEND_PRE.ADJUST_TIME_SUN, DP_SITE_VEND_PRE.TRANSIT_TIME_SUN, DP_SITE_VEND_PRE.ADJUST_TIME_MON, DP_SITE_VEND_PRE.TRANSIT_TIME_MON, DP_SITE_VEND_PRE.ADJUST_TIME_TUE, DP_SITE_VEND_PRE.TRANSIT_TIME_TUE, DP_SITE_VEND_PRE.ADJUST_TIME_WED, DP_SITE_VEND_PRE.TRANSIT_TIME_WED, DP_SITE_VEND_PRE.ADJUST_TIME_THU, DP_SITE_VEND_PRE.TRANSIT_TIME_THU, DP_SITE_VEND_PRE.ADJUST_TIME_FRI, DP_SITE_VEND_PRE.TRANSIT_TIME_FRI, DP_SITE_VEND_PRE.ADJUST_TIME_SAT, DP_SITE_VEND_PRE.TRANSIT_TIME_SAT, DP_SITE_VEND_PRE.ALT_ORIGIN, DP_SITE_VEND_PRE.DEL_START_TIME_SUN, DP_SITE_VEND_PRE.DEL_END_TIME_SUN, DP_SITE_VEND_PRE.DEL_START_TIME_MON, DP_SITE_VEND_PRE.DEL_END_TIME_MON, DP_SITE_VEND_PRE.DEL_START_TIME_TUE, DP_SITE_VEND_PRE.DEL_END_TIME_TUE, DP_SITE_VEND_PRE.DEL_START_TIME_WED, DP_SITE_VEND_PRE.DEL_END_TIME_WED, DP_SITE_VEND_PRE.DEL_START_TIME_THU, DP_SITE_VEND_PRE.DEL_END_TIME_THU, DP_SITE_VEND_PRE.DEL_START_TIME_FRI, DP_SITE_VEND_PRE.DEL_END_TIME_FRI, DP_SITE_VEND_PRE.DEL_START_TIME_SAT, DP_SITE_VEND_PRE.DEL_END_TIME_SAT, DP_SITE_VEND_PRE.PICK_DAY1, DP_SITE_VEND_PRE.PICK_DAY2, DP_SITE_VEND_PRE.PICK_DAY3, DP_SITE_VEND_PRE.PICK_DAY4, DP_SITE_VEND_PRE.PICK_DAY5, DP_SITE_VEND_PRE.PICK_DAY6, DP_SITE_VEND_PRE.PICK_DAY7, DP_SITE_VEND_PRE.DEL_DAY1, DP_SITE_VEND_PRE.DEL_DAY2, DP_SITE_VEND_PRE.DEL_DAY3, DP_SITE_VEND_PRE.DEL_DAY4, DP_SITE_VEND_PRE.DEL_DAY5, DP_SITE_VEND_PRE.DEL_DAY6, DP_SITE_VEND_PRE.DEL_DAY7, DP_SITE_VEND_PRE.BLUE_GREEN_FLAG, DP_SITE_VEND_PRE.PROTECTION_LEVEL, DP_SITE_VEND_PRE.OVERRIDE_ORDER_WEIGHT, DP_SITE_VEND_PRE.OVERRIDE_ORDER_VOLUME, DP_SITE_VEND_PRE.CHANGE_DATE, DP_SITE_VEND_PRE.CHANGE_TIME, DP_SITE_VEND_PRE.NOTES, DP_SITE_VEND_PRE.OVERRIDE_FLAG, DP_SITE_VEND_PRE.CROSSDOCK_ID, DP_SITE_VEND_PRE.ALT_ORIGIN1, DP_SITE_VEND_PRE.ALT_ORIGIN2, DP_SITE_VEND_PRE.ALT_ORIGIN3, DP_SITE_VEND_PRE.ALT_ORIGIN4, DP_SITE_VEND_PRE.ALT_ORIGIN5, DP_SITE_VEND_PRE.ALT_ORIGIN6, DP_SITE_VEND_PRE.ALT_ORIGIN7, DP_SITE_VEND_PRE.CROSSDOCK_ID2, DP_SITE_VEND_PRE.CROSSDOCK_ID3, DP_SITE_VEND_PRE.CROSSDOCK_ID4, DP_SITE_VEND_PRE.CROSSDOCK_ID5, DP_SITE_VEND_PRE.CROSSDOCK_ID6, DP_SITE_VEND_PRE.CROSSDOCK_ID7,DP_SITE_VEND_PRE.ADJUST_LEADTIME

FROM

 {raw}.DP_SITE_VEND_PRE, {legacy}.SITE_PROFILE

WHERE DP_SITE_VEND_PRE.STORE_NBR=SITE_PROFILE.STORE_NBR""").withColumn("sys_row_id", monotonically_increasing_id())
# Conforming fields names to the component layout
SQ_Shortcut_to_DP_SITE_VEND_PRE1 = SQ_Shortcut_to_DP_SITE_VEND_PRE1 \
	.withColumnRenamed(SQ_Shortcut_to_DP_SITE_VEND_PRE1.columns[0],'LOCATION_ID') \
	.withColumnRenamed(SQ_Shortcut_to_DP_SITE_VEND_PRE1.columns[1],'STORE_NBR') \
	.withColumnRenamed(SQ_Shortcut_to_DP_SITE_VEND_PRE1.columns[2],'VENDOR_ID') \
	.withColumnRenamed(SQ_Shortcut_to_DP_SITE_VEND_PRE1.columns[3],'VENDOR_SUBGROUP_ID') \
	.withColumnRenamed(SQ_Shortcut_to_DP_SITE_VEND_PRE1.columns[4],'DP_PURCH_GROUP_ID') \
	.withColumnRenamed(SQ_Shortcut_to_DP_SITE_VEND_PRE1.columns[5],'DUE_BASED_ON_CD') \
	.withColumnRenamed(SQ_Shortcut_to_DP_SITE_VEND_PRE1.columns[6],'ORDER_DAY_OF_WK_ARRAY') \
	.withColumnRenamed(SQ_Shortcut_to_DP_SITE_VEND_PRE1.columns[7],'WEEK_FREQ_CD') \
	.withColumnRenamed(SQ_Shortcut_to_DP_SITE_VEND_PRE1.columns[8],'QUOTED_LT_DAY_CNT') \
	.withColumnRenamed(SQ_Shortcut_to_DP_SITE_VEND_PRE1.columns[9],'LT_DAY_CNT') \
	.withColumnRenamed(SQ_Shortcut_to_DP_SITE_VEND_PRE1.columns[10],'LOAD_DT') \
	.withColumnRenamed(SQ_Shortcut_to_DP_SITE_VEND_PRE1.columns[11],'MANDT') \
	.withColumnRenamed(SQ_Shortcut_to_DP_SITE_VEND_PRE1.columns[12],'DPR_ORDER_ARRAY') \
	.withColumnRenamed(SQ_Shortcut_to_DP_SITE_VEND_PRE1.columns[13],'PROD_LEADTIME') \
	.withColumnRenamed(SQ_Shortcut_to_DP_SITE_VEND_PRE1.columns[14],'TRANSIT_LEADTIME') \
	.withColumnRenamed(SQ_Shortcut_to_DP_SITE_VEND_PRE1.columns[15],'ADJUST_TIME_SUN') \
	.withColumnRenamed(SQ_Shortcut_to_DP_SITE_VEND_PRE1.columns[16],'TRANSIT_TIME_SUN') \
	.withColumnRenamed(SQ_Shortcut_to_DP_SITE_VEND_PRE1.columns[17],'ADJUST_TIME_MON') \
	.withColumnRenamed(SQ_Shortcut_to_DP_SITE_VEND_PRE1.columns[18],'TRANSIT_TIME_MON') \
	.withColumnRenamed(SQ_Shortcut_to_DP_SITE_VEND_PRE1.columns[19],'ADJUST_TIME_TUE') \
	.withColumnRenamed(SQ_Shortcut_to_DP_SITE_VEND_PRE1.columns[20],'TRANSIT_TIME_TUE') \
	.withColumnRenamed(SQ_Shortcut_to_DP_SITE_VEND_PRE1.columns[21],'ADJUST_TIME_WED') \
	.withColumnRenamed(SQ_Shortcut_to_DP_SITE_VEND_PRE1.columns[22],'TRANSIT_TIME_WED') \
	.withColumnRenamed(SQ_Shortcut_to_DP_SITE_VEND_PRE1.columns[23],'ADJUST_TIME_THU') \
	.withColumnRenamed(SQ_Shortcut_to_DP_SITE_VEND_PRE1.columns[24],'TRANSIT_TIME_THU') \
	.withColumnRenamed(SQ_Shortcut_to_DP_SITE_VEND_PRE1.columns[25],'ADJUST_TIME_FRI') \
	.withColumnRenamed(SQ_Shortcut_to_DP_SITE_VEND_PRE1.columns[26],'TRANSIT_TIME_FRI') \
	.withColumnRenamed(SQ_Shortcut_to_DP_SITE_VEND_PRE1.columns[27],'ADJUST_TIME_SAT') \
	.withColumnRenamed(SQ_Shortcut_to_DP_SITE_VEND_PRE1.columns[28],'TRANSIT_TIME_SAT') \
	.withColumnRenamed(SQ_Shortcut_to_DP_SITE_VEND_PRE1.columns[29],'ALT_ORIGIN') \
	.withColumnRenamed(SQ_Shortcut_to_DP_SITE_VEND_PRE1.columns[30],'DEL_START_TIME_SUN') \
	.withColumnRenamed(SQ_Shortcut_to_DP_SITE_VEND_PRE1.columns[31],'DEL_END_TIME_SUN') \
	.withColumnRenamed(SQ_Shortcut_to_DP_SITE_VEND_PRE1.columns[32],'DEL_START_TIME_MON') \
	.withColumnRenamed(SQ_Shortcut_to_DP_SITE_VEND_PRE1.columns[33],'DEL_END_TIME_MON') \
	.withColumnRenamed(SQ_Shortcut_to_DP_SITE_VEND_PRE1.columns[34],'DEL_START_TIME_TUE') \
	.withColumnRenamed(SQ_Shortcut_to_DP_SITE_VEND_PRE1.columns[35],'DEL_END_TIME_TUE') \
	.withColumnRenamed(SQ_Shortcut_to_DP_SITE_VEND_PRE1.columns[36],'DEL_START_TIME_WED') \
	.withColumnRenamed(SQ_Shortcut_to_DP_SITE_VEND_PRE1.columns[37],'DEL_END_TIME_WED') \
	.withColumnRenamed(SQ_Shortcut_to_DP_SITE_VEND_PRE1.columns[38],'DEL_START_TIME_THU') \
	.withColumnRenamed(SQ_Shortcut_to_DP_SITE_VEND_PRE1.columns[39],'DEL_END_TIME_THU') \
	.withColumnRenamed(SQ_Shortcut_to_DP_SITE_VEND_PRE1.columns[40],'DEL_START_TIME_FRI') \
	.withColumnRenamed(SQ_Shortcut_to_DP_SITE_VEND_PRE1.columns[41],'DEL_END_TIME_FRI') \
	.withColumnRenamed(SQ_Shortcut_to_DP_SITE_VEND_PRE1.columns[42],'DEL_START_TIME_SAT') \
	.withColumnRenamed(SQ_Shortcut_to_DP_SITE_VEND_PRE1.columns[43],'DEL_END_TIME_SAT') \
	.withColumnRenamed(SQ_Shortcut_to_DP_SITE_VEND_PRE1.columns[44],'PICK_DAY1') \
	.withColumnRenamed(SQ_Shortcut_to_DP_SITE_VEND_PRE1.columns[45],'PICK_DAY2') \
	.withColumnRenamed(SQ_Shortcut_to_DP_SITE_VEND_PRE1.columns[46],'PICK_DAY3') \
	.withColumnRenamed(SQ_Shortcut_to_DP_SITE_VEND_PRE1.columns[47],'PICK_DAY4') \
	.withColumnRenamed(SQ_Shortcut_to_DP_SITE_VEND_PRE1.columns[48],'PICK_DAY5') \
	.withColumnRenamed(SQ_Shortcut_to_DP_SITE_VEND_PRE1.columns[49],'PICK_DAY6') \
	.withColumnRenamed(SQ_Shortcut_to_DP_SITE_VEND_PRE1.columns[50],'PICK_DAY7') \
	.withColumnRenamed(SQ_Shortcut_to_DP_SITE_VEND_PRE1.columns[51],'DEL_DAY1') \
	.withColumnRenamed(SQ_Shortcut_to_DP_SITE_VEND_PRE1.columns[52],'DEL_DAY2') \
	.withColumnRenamed(SQ_Shortcut_to_DP_SITE_VEND_PRE1.columns[53],'DEL_DAY3') \
	.withColumnRenamed(SQ_Shortcut_to_DP_SITE_VEND_PRE1.columns[54],'DEL_DAY4') \
	.withColumnRenamed(SQ_Shortcut_to_DP_SITE_VEND_PRE1.columns[55],'DEL_DAY5') \
	.withColumnRenamed(SQ_Shortcut_to_DP_SITE_VEND_PRE1.columns[56],'DEL_DAY6') \
	.withColumnRenamed(SQ_Shortcut_to_DP_SITE_VEND_PRE1.columns[57],'DEL_DAY7') \
	.withColumnRenamed(SQ_Shortcut_to_DP_SITE_VEND_PRE1.columns[58],'BLUE_GREEN_FLAG') \
	.withColumnRenamed(SQ_Shortcut_to_DP_SITE_VEND_PRE1.columns[59],'PROTECTION_LEVEL') \
	.withColumnRenamed(SQ_Shortcut_to_DP_SITE_VEND_PRE1.columns[60],'OVERRIDE_ORDER_WEIGHT') \
	.withColumnRenamed(SQ_Shortcut_to_DP_SITE_VEND_PRE1.columns[61],'OVERRIDE_ORDER_VOLUME') \
	.withColumnRenamed(SQ_Shortcut_to_DP_SITE_VEND_PRE1.columns[62],'CHANGE_DATE') \
	.withColumnRenamed(SQ_Shortcut_to_DP_SITE_VEND_PRE1.columns[63],'CHANGE_TIME') \
	.withColumnRenamed(SQ_Shortcut_to_DP_SITE_VEND_PRE1.columns[64],'NOTES') \
	.withColumnRenamed(SQ_Shortcut_to_DP_SITE_VEND_PRE1.columns[65],'OVERRIDE_FLAG') \
	.withColumnRenamed(SQ_Shortcut_to_DP_SITE_VEND_PRE1.columns[66],'CROSSDOCK_ID') \
	.withColumnRenamed(SQ_Shortcut_to_DP_SITE_VEND_PRE1.columns[67],'ALT_ORIGIN1') \
	.withColumnRenamed(SQ_Shortcut_to_DP_SITE_VEND_PRE1.columns[68],'ALT_ORIGIN2') \
	.withColumnRenamed(SQ_Shortcut_to_DP_SITE_VEND_PRE1.columns[69],'ALT_ORIGIN3') \
	.withColumnRenamed(SQ_Shortcut_to_DP_SITE_VEND_PRE1.columns[70],'ALT_ORIGIN4') \
	.withColumnRenamed(SQ_Shortcut_to_DP_SITE_VEND_PRE1.columns[71],'ALT_ORIGIN5') \
	.withColumnRenamed(SQ_Shortcut_to_DP_SITE_VEND_PRE1.columns[72],'ALT_ORIGIN6') \
	.withColumnRenamed(SQ_Shortcut_to_DP_SITE_VEND_PRE1.columns[73],'ALT_ORIGIN7') \
	.withColumnRenamed(SQ_Shortcut_to_DP_SITE_VEND_PRE1.columns[74],'CROSSDOCK_ID2') \
	.withColumnRenamed(SQ_Shortcut_to_DP_SITE_VEND_PRE1.columns[75],'CROSSDOCK_ID3') \
	.withColumnRenamed(SQ_Shortcut_to_DP_SITE_VEND_PRE1.columns[76],'CROSSDOCK_ID4') \
	.withColumnRenamed(SQ_Shortcut_to_DP_SITE_VEND_PRE1.columns[77],'CROSSDOCK_ID5') \
	.withColumnRenamed(SQ_Shortcut_to_DP_SITE_VEND_PRE1.columns[78],'CROSSDOCK_ID6') \
	.withColumnRenamed(SQ_Shortcut_to_DP_SITE_VEND_PRE1.columns[79],'CROSSDOCK_ID7') \
	.withColumnRenamed(SQ_Shortcut_to_DP_SITE_VEND_PRE1.columns[80],'ADJUST_LEADTIME')

# COMMAND ----------

# Processing node EXP_SQ, type EXPRESSION . Note: using additional SELECT to rename incoming columns
# COLUMN COUNT: 82

# for each involved DataFrame, append the dataframe name to each column
SQ_Shortcut_to_DP_SITE_VEND_PRE1_temp = SQ_Shortcut_to_DP_SITE_VEND_PRE1.toDF(*["SQ_Shortcut_to_DP_SITE_VEND_PRE1___" + col for col in SQ_Shortcut_to_DP_SITE_VEND_PRE1.columns])

EXP_SQ = SQ_Shortcut_to_DP_SITE_VEND_PRE1_temp.selectExpr(
	"SQ_Shortcut_to_DP_SITE_VEND_PRE1___LOCATION_ID as STORE_NBR",
	"SQ_Shortcut_to_DP_SITE_VEND_PRE1___VENDOR_ID as VENDOR_ID",
	"SQ_Shortcut_to_DP_SITE_VEND_PRE1___VENDOR_SUBGROUP_ID as VENDOR_SUBGROUP_ID",
	"SQ_Shortcut_to_DP_SITE_VEND_PRE1___DP_PURCH_GROUP_ID as DP_PURCH_GROUP_ID",
	"SQ_Shortcut_to_DP_SITE_VEND_PRE1___QUOTED_LT_DAY_CNT as QUOTED_LT_DAY_CNT",
	"SQ_Shortcut_to_DP_SITE_VEND_PRE1___LT_DAY_CNT as LT_DAY_CNT",
	"SQ_Shortcut_to_DP_SITE_VEND_PRE1___LOAD_DT as LOAD_DT",
	"SQ_Shortcut_to_DP_SITE_VEND_PRE1___DUE_BASED_ON_CD as DUE_BASED_ON_CD",
	"SQ_Shortcut_to_DP_SITE_VEND_PRE1___ORDER_DAY_OF_WK_ARRAY as ORDER_DAY_OF_WK_ARRAY",
	"SQ_Shortcut_to_DP_SITE_VEND_PRE1___WEEK_FREQ_CD as WEEK_FREQ_CD",
	"SQ_Shortcut_to_DP_SITE_VEND_PRE1___STORE_NBR as STORE_NBR1",
	"SQ_Shortcut_to_DP_SITE_VEND_PRE1___LOAD_DT as LOAD_DT1",
	"SQ_Shortcut_to_DP_SITE_VEND_PRE1___MANDT as MANDT",
	"SQ_Shortcut_to_DP_SITE_VEND_PRE1___DPR_ORDER_ARRAY as DPR_ORDER_ARRAY",
	"SQ_Shortcut_to_DP_SITE_VEND_PRE1___PROD_LEADTIME as PROD_LEADTIME",
	"SQ_Shortcut_to_DP_SITE_VEND_PRE1___TRANSIT_LEADTIME as TRANSIT_LEADTIME",
	"SQ_Shortcut_to_DP_SITE_VEND_PRE1___ADJUST_TIME_SUN as ADJUST_TIME_SUN",
	"SQ_Shortcut_to_DP_SITE_VEND_PRE1___TRANSIT_TIME_SUN as TRANSIT_TIME_SUN",
	"SQ_Shortcut_to_DP_SITE_VEND_PRE1___ADJUST_TIME_MON as ADJUST_TIME_MON",
	"SQ_Shortcut_to_DP_SITE_VEND_PRE1___TRANSIT_TIME_MON as TRANSIT_TIME_MON",
	"SQ_Shortcut_to_DP_SITE_VEND_PRE1___ADJUST_TIME_TUE as ADJUST_TIME_TUE",
	"SQ_Shortcut_to_DP_SITE_VEND_PRE1___TRANSIT_TIME_TUE as TRANSIT_TIME_TUE",
	"SQ_Shortcut_to_DP_SITE_VEND_PRE1___ADJUST_TIME_WED as ADJUST_TIME_WED",
	"SQ_Shortcut_to_DP_SITE_VEND_PRE1___TRANSIT_TIME_WED as TRANSIT_TIME_WED",
	"SQ_Shortcut_to_DP_SITE_VEND_PRE1___ADJUST_TIME_THU as ADJUST_TIME_THU",
	"SQ_Shortcut_to_DP_SITE_VEND_PRE1___TRANSIT_TIME_THU as TRANSIT_TIME_THU",
	"SQ_Shortcut_to_DP_SITE_VEND_PRE1___ADJUST_TIME_FRI as ADJUST_TIME_FRI",
	"SQ_Shortcut_to_DP_SITE_VEND_PRE1___TRANSIT_TIME_FRI as TRANSIT_TIME_FRI",
	"SQ_Shortcut_to_DP_SITE_VEND_PRE1___ADJUST_TIME_SAT as ADJUST_TIME_SAT",
	"SQ_Shortcut_to_DP_SITE_VEND_PRE1___TRANSIT_TIME_SAT as TRANSIT_TIME_SAT",
	"SQ_Shortcut_to_DP_SITE_VEND_PRE1___ALT_ORIGIN as ALT_ORIGIN",
	"SQ_Shortcut_to_DP_SITE_VEND_PRE1___DEL_START_TIME_SUN as DEL_START_TIME_SUN",
	"SQ_Shortcut_to_DP_SITE_VEND_PRE1___DEL_END_TIME_SUN as DEL_END_TIME_SUN",
	"SQ_Shortcut_to_DP_SITE_VEND_PRE1___DEL_START_TIME_MON as DEL_START_TIME_MON",
	"SQ_Shortcut_to_DP_SITE_VEND_PRE1___DEL_END_TIME_MON as DEL_END_TIME_MON",
	"SQ_Shortcut_to_DP_SITE_VEND_PRE1___DEL_START_TIME_TUE as DEL_START_TIME_TUE",
	"SQ_Shortcut_to_DP_SITE_VEND_PRE1___DEL_END_TIME_TUE as DEL_END_TIME_TUE",
	"SQ_Shortcut_to_DP_SITE_VEND_PRE1___DEL_START_TIME_WED as DEL_START_TIME_WED",
	"SQ_Shortcut_to_DP_SITE_VEND_PRE1___DEL_END_TIME_WED as DEL_END_TIME_WED",
	"SQ_Shortcut_to_DP_SITE_VEND_PRE1___DEL_START_TIME_THU as DEL_START_TIME_THU",
	"SQ_Shortcut_to_DP_SITE_VEND_PRE1___DEL_END_TIME_THU as DEL_END_TIME_THU",
	"SQ_Shortcut_to_DP_SITE_VEND_PRE1___DEL_START_TIME_FRI as DEL_START_TIME_FRI",
	"SQ_Shortcut_to_DP_SITE_VEND_PRE1___DEL_END_TIME_FRI as DEL_END_TIME_FRI",
	"SQ_Shortcut_to_DP_SITE_VEND_PRE1___DEL_START_TIME_SAT as DEL_START_TIME_SAT",
	"SQ_Shortcut_to_DP_SITE_VEND_PRE1___DEL_END_TIME_SAT as DEL_END_TIME_SAT",
	"SQ_Shortcut_to_DP_SITE_VEND_PRE1___PICK_DAY1 as PICK_DAY1",
	"SQ_Shortcut_to_DP_SITE_VEND_PRE1___PICK_DAY2 as PICK_DAY2",
	"SQ_Shortcut_to_DP_SITE_VEND_PRE1___PICK_DAY3 as PICK_DAY3",
	"SQ_Shortcut_to_DP_SITE_VEND_PRE1___PICK_DAY4 as PICK_DAY4",
	"SQ_Shortcut_to_DP_SITE_VEND_PRE1___PICK_DAY5 as PICK_DAY5",
	"SQ_Shortcut_to_DP_SITE_VEND_PRE1___PICK_DAY6 as PICK_DAY6",
	"SQ_Shortcut_to_DP_SITE_VEND_PRE1___PICK_DAY7 as PICK_DAY7",
	"SQ_Shortcut_to_DP_SITE_VEND_PRE1___DEL_DAY1 as DEL_DAY1",
	"SQ_Shortcut_to_DP_SITE_VEND_PRE1___DEL_DAY2 as DEL_DAY2",
	"SQ_Shortcut_to_DP_SITE_VEND_PRE1___DEL_DAY3 as DEL_DAY3",
	"SQ_Shortcut_to_DP_SITE_VEND_PRE1___DEL_DAY4 as DEL_DAY4",
	"SQ_Shortcut_to_DP_SITE_VEND_PRE1___DEL_DAY5 as DEL_DAY5",
	"SQ_Shortcut_to_DP_SITE_VEND_PRE1___DEL_DAY6 as DEL_DAY6",
	"SQ_Shortcut_to_DP_SITE_VEND_PRE1___DEL_DAY7 as DEL_DAY7",
	"SQ_Shortcut_to_DP_SITE_VEND_PRE1___BLUE_GREEN_FLAG as BLUE_GREEN_FLAG",
	"SQ_Shortcut_to_DP_SITE_VEND_PRE1___PROTECTION_LEVEL as PROTECTION_LEVEL",
	"SQ_Shortcut_to_DP_SITE_VEND_PRE1___OVERRIDE_ORDER_WEIGHT as OVERRIDE_ORDER_WEIGHT",
	"SQ_Shortcut_to_DP_SITE_VEND_PRE1___OVERRIDE_ORDER_VOLUME as OVERRIDE_ORDER_VOLUME",
	"SQ_Shortcut_to_DP_SITE_VEND_PRE1___CHANGE_DATE as CHANGE_DATE",
	"SQ_Shortcut_to_DP_SITE_VEND_PRE1___CHANGE_TIME as CHANGE_TIME",
	"SQ_Shortcut_to_DP_SITE_VEND_PRE1___NOTES as NOTES",
	"SQ_Shortcut_to_DP_SITE_VEND_PRE1___OVERRIDE_FLAG as OVERRIDE_FLAG",
	"SQ_Shortcut_to_DP_SITE_VEND_PRE1___CROSSDOCK_ID as CROSSDOCK_ID",
	"SQ_Shortcut_to_DP_SITE_VEND_PRE1___ALT_ORIGIN1 as ALT_ORIGIN1",
	"SQ_Shortcut_to_DP_SITE_VEND_PRE1___ALT_ORIGIN2 as ALT_ORIGIN2",
	"SQ_Shortcut_to_DP_SITE_VEND_PRE1___ALT_ORIGIN3 as ALT_ORIGIN3",
	"SQ_Shortcut_to_DP_SITE_VEND_PRE1___ALT_ORIGIN4 as ALT_ORIGIN4",
	"SQ_Shortcut_to_DP_SITE_VEND_PRE1___ALT_ORIGIN5 as ALT_ORIGIN5",
	"SQ_Shortcut_to_DP_SITE_VEND_PRE1___ALT_ORIGIN6 as ALT_ORIGIN6",
	"SQ_Shortcut_to_DP_SITE_VEND_PRE1___ALT_ORIGIN7 as ALT_ORIGIN7",
	"SQ_Shortcut_to_DP_SITE_VEND_PRE1___CROSSDOCK_ID2 as CROSSDOCK_ID2",
	"SQ_Shortcut_to_DP_SITE_VEND_PRE1___CROSSDOCK_ID3 as CROSSDOCK_ID3",
	"SQ_Shortcut_to_DP_SITE_VEND_PRE1___CROSSDOCK_ID4 as CROSSDOCK_ID4",
	"SQ_Shortcut_to_DP_SITE_VEND_PRE1___CROSSDOCK_ID5 as CROSSDOCK_ID5",
	"SQ_Shortcut_to_DP_SITE_VEND_PRE1___CROSSDOCK_ID6 as CROSSDOCK_ID6",
	"SQ_Shortcut_to_DP_SITE_VEND_PRE1___CROSSDOCK_ID7 as CROSSDOCK_ID7",
	"SQ_Shortcut_to_DP_SITE_VEND_PRE1___ADJUST_LEADTIME as ADJUST_LEADTIME").selectExpr(
	# "SQ_Shortcut_to_DP_SITE_VEND_PRE1___sys_row_id as sys_row_id",
	"STORE_NBR as STORE_NBR",
	"VENDOR_ID as VENDOR_ID",
	"IF (VENDOR_SUBGROUP_ID IS NULL, ' ', VENDOR_SUBGROUP_ID) as VENDOR_SUBGROUP_ID1",
	"DP_PURCH_GROUP_ID as DP_PURCH_GROUP_ID",
	"QUOTED_LT_DAY_CNT as QUOTED_LT_DAY_CNT",
	"LT_DAY_CNT as LT_DAY_CNT",
	"LOAD_DT as LOAD_DT",
	"DUE_BASED_ON_CD as DUE_BASED_ON_CD",
	"ORDER_DAY_OF_WK_ARRAY as ORDER_DAY_OF_WK_ARRAY",
	"WEEK_FREQ_CD as WEEK_FREQ_CD",
	"STORE_NBR1 as STORE_NBR1",
	"LOAD_DT1 as LOAD_DT1",
	"MANDT as MANDT",
	"DPR_ORDER_ARRAY as DPR_ORDER_ARRAY",
	"PROD_LEADTIME as PROD_LEADTIME",
	"TRANSIT_LEADTIME as TRANSIT_LEADTIME",
	"ADJUST_TIME_SUN as ADJUST_TIME_SUN",
	"TRANSIT_TIME_SUN as TRANSIT_TIME_SUN",
	"ADJUST_TIME_MON as ADJUST_TIME_MON",
	"TRANSIT_TIME_MON as TRANSIT_TIME_MON",
	"ADJUST_TIME_TUE as ADJUST_TIME_TUE",
	"TRANSIT_TIME_TUE as TRANSIT_TIME_TUE",
	"ADJUST_TIME_WED as ADJUST_TIME_WED",
	"TRANSIT_TIME_WED as TRANSIT_TIME_WED",
	"ADJUST_TIME_THU as ADJUST_TIME_THU",
	"TRANSIT_TIME_THU as TRANSIT_TIME_THU",
	"ADJUST_TIME_FRI as ADJUST_TIME_FRI",
	"TRANSIT_TIME_FRI as TRANSIT_TIME_FRI",
	"ADJUST_TIME_SAT as ADJUST_TIME_SAT",
	"TRANSIT_TIME_SAT as TRANSIT_TIME_SAT",
	"ALT_ORIGIN as ALT_ORIGIN",
	"DEL_START_TIME_SUN as DEL_START_TIME_SUN",
	"DEL_END_TIME_SUN as DEL_END_TIME_SUN",
	"DEL_START_TIME_MON as DEL_START_TIME_MON",
	"DEL_END_TIME_MON as DEL_END_TIME_MON",
	"DEL_START_TIME_TUE as DEL_START_TIME_TUE",
	"DEL_END_TIME_TUE as DEL_END_TIME_TUE",
	"DEL_START_TIME_WED as DEL_START_TIME_WED",
	"DEL_END_TIME_WED as DEL_END_TIME_WED",
	"DEL_START_TIME_THU as DEL_START_TIME_THU",
	"DEL_END_TIME_THU as DEL_END_TIME_THU",
	"DEL_START_TIME_FRI as DEL_START_TIME_FRI",
	"DEL_END_TIME_FRI as DEL_END_TIME_FRI",
	"DEL_START_TIME_SAT as DEL_START_TIME_SAT",
	"DEL_END_TIME_SAT as DEL_END_TIME_SAT",
	"PICK_DAY1 as PICK_DAY1",
	"PICK_DAY2 as PICK_DAY2",
	"PICK_DAY3 as PICK_DAY3",
	"PICK_DAY4 as PICK_DAY4",
	"PICK_DAY5 as PICK_DAY5",
	"PICK_DAY6 as PICK_DAY6",
	"PICK_DAY7 as PICK_DAY7",
	"DEL_DAY1 as DEL_DAY1",
	"DEL_DAY2 as DEL_DAY2",
	"DEL_DAY3 as DEL_DAY3",
	"DEL_DAY4 as DEL_DAY4",
	"DEL_DAY5 as DEL_DAY5",
	"DEL_DAY6 as DEL_DAY6",
	"DEL_DAY7 as DEL_DAY7",
	"BLUE_GREEN_FLAG as BLUE_GREEN_FLAG",
	"PROTECTION_LEVEL as PROTECTION_LEVEL",
	"OVERRIDE_ORDER_WEIGHT as OVERRIDE_ORDER_WEIGHT",
	"OVERRIDE_ORDER_VOLUME as OVERRIDE_ORDER_VOLUME",
	"CHANGE_DATE as CHANGE_DATE",
	"CHANGE_TIME as CHANGE_TIME",
	"NOTES as NOTES",
	"OVERRIDE_FLAG as OVERRIDE_FLAG",
	"CROSSDOCK_ID as CROSSDOCK_ID",
	"ALT_ORIGIN1 as ALT_ORIGIN1",
	"ALT_ORIGIN2 as ALT_ORIGIN2",
	"ALT_ORIGIN3 as ALT_ORIGIN3",
	"ALT_ORIGIN4 as ALT_ORIGIN4",
	"ALT_ORIGIN5 as ALT_ORIGIN5",
	"ALT_ORIGIN6 as ALT_ORIGIN6",
	"ALT_ORIGIN7 as ALT_ORIGIN7",
	"CROSSDOCK_ID2 as CROSSDOCK_ID2",
	"CROSSDOCK_ID3 as CROSSDOCK_ID3",
	"CROSSDOCK_ID4 as CROSSDOCK_ID4",
	"CROSSDOCK_ID5 as CROSSDOCK_ID5",
	"CROSSDOCK_ID6 as CROSSDOCK_ID6",
	"CROSSDOCK_ID7 as CROSSDOCK_ID7",
	"ADJUST_LEADTIME as ADJUST_LEADTIME"
)

# COMMAND ----------

# Processing node Shortcut_to_DP_SITE_VEND_PROFILE, type TARGET 
# COLUMN COUNT: 81

Shortcut_to_DP_SITE_VEND_PROFILE = EXP_SQ.selectExpr(
	"CAST(STORE_NBR AS INT) as LOCATION_ID",
	"CAST(VENDOR_ID as bigint) as VENDOR_ID",
	"CAST(VENDOR_SUBGROUP_ID1 AS STRING) as VENDOR_SUBGROUP_ID",
	"CAST(DPR_ORDER_ARRAY AS STRING) as DPR_ORDER_ARRAY",
	"CAST(DP_PURCH_GROUP_ID AS STRING) as DP_PURCH_GROUP_ID",
	"CAST(PROD_LEADTIME AS SMALLINT) as PROD_LEADTIME",
	"CAST(ADJUST_LEADTIME AS DECIMAL(5,2)) as ADJUST_LEADTIME",
	"CAST(TRANSIT_LEADTIME AS SMALLINT) as TRANSIT_LEADTIME",
	"CAST(QUOTED_LT_DAY_CNT AS SMALLINT) as TOTAL_LEADTIME",
	"CAST(ADJUST_TIME_SUN AS DECIMAL(5,2)) as ADJUST_TIME_SUN",
	"CAST(TRANSIT_TIME_SUN AS SMALLINT) as TRANSIT_TIME_SUN",
	"CAST(ADJUST_TIME_MON AS DECIMAL(5,2)) as ADJUST_TIME_MON",
	"CAST(TRANSIT_TIME_MON AS SMALLINT) as TRANSIT_TIME_MON",
	"CAST(ADJUST_TIME_TUE AS DECIMAL(5,2)) as ADJUST_TIME_TUE",
	"CAST(TRANSIT_TIME_TUE AS SMALLINT) as TRANSIT_TIME_TUE",
	"CAST(ADJUST_TIME_WED AS DECIMAL(5,2)) as ADJUST_TIME_WED",
	"CAST(TRANSIT_TIME_WED AS SMALLINT) as TRANSIT_TIME_WED",
	"CAST(ADJUST_TIME_THU AS DECIMAL(5,2)) as ADJUST_TIME_THU",
	"CAST(TRANSIT_TIME_THU AS SMALLINT) as TRANSIT_TIME_THU",
	"CAST(ADJUST_TIME_FRI AS DECIMAL(5,2)) as ADJUST_TIME_FRI",
	"CAST(TRANSIT_TIME_FRI AS SMALLINT) as TRANSIT_TIME_FRI",
	"CAST(ADJUST_TIME_SAT AS DECIMAL(5,2)) as ADJUST_TIME_SAT",
	"CAST(TRANSIT_TIME_SAT AS SMALLINT) as TRANSIT_TIME_SAT",
	"CAST(ALT_ORIGIN AS STRING) as ALT_ORIGIN",
	"DEL_START_TIME_SUN as DEL_START_TIME_SUN",
	"DEL_END_TIME_SUN as DEL_END_TIME_SUN",
	"DEL_START_TIME_MON as DEL_START_TIME_MON",
	"DEL_END_TIME_MON as DEL_END_TIME_MON",
	"DEL_START_TIME_TUE as DEL_START_TIME_TUE",
	"DEL_END_TIME_TUE as DEL_END_TIME_TUE",
	"DEL_START_TIME_WED as DEL_START_TIME_WED",
	"DEL_END_TIME_WED as DEL_END_TIME_WED",
	"DEL_START_TIME_THU as DEL_START_TIME_THU",
	"DEL_END_TIME_THU as DEL_END_TIME_THU",
	"DEL_START_TIME_FRI as DEL_START_TIME_FRI",
	"DEL_END_TIME_FRI as DEL_END_TIME_FRI",
	"DEL_START_TIME_SAT as DEL_START_TIME_SAT",
	"DEL_END_TIME_SAT as DEL_END_TIME_SAT",
	"CAST(PICK_DAY1 AS STRING) as PICK_DAY1",
	"CAST(PICK_DAY2 AS STRING) as PICK_DAY2",
	"CAST(PICK_DAY3 AS STRING) as PICK_DAY3",
	"CAST(PICK_DAY4 AS STRING) as PICK_DAY4",
	"CAST(PICK_DAY5 AS STRING) as PICK_DAY5",
	"CAST(PICK_DAY6 AS STRING) as PICK_DAY6",
	"CAST(PICK_DAY7 AS STRING) as PICK_DAY7",
	"CAST(DEL_DAY1 AS STRING) as DEL_DAY1",
	"CAST(DEL_DAY2 AS STRING) as DEL_DAY2",
	"CAST(DEL_DAY3 AS STRING) as DEL_DAY3",
	"CAST(DEL_DAY4 AS STRING) as DEL_DAY4",
	"CAST(DEL_DAY5 AS STRING) as DEL_DAY5",
	"CAST(DEL_DAY6 AS STRING) as DEL_DAY6",
	"CAST(DEL_DAY7 AS STRING) as DEL_DAY7",
	"CAST(BLUE_GREEN_FLAG AS STRING) as BLUE_GREEN_FLAG",
	"CAST(PROTECTION_LEVEL AS STRING) as PROTECTION_LEVEL",
	"CAST(OVERRIDE_ORDER_WEIGHT AS DECIMAL(13,3)) as OVERRIDE_ORDER_WEIGHT",
	"CAST(OVERRIDE_ORDER_VOLUME AS DECIMAL(13,3)) as OVERRIDE_ORDER_VOLUME",
	"CAST(CHANGE_DATE AS TIMESTAMP) as CHANGE_DATE",
	"CHANGE_TIME as CHANGE_TIME",
	"CAST(NOTES AS STRING) as NOTES",
	"CAST(OVERRIDE_FLAG AS STRING) as OVERRIDE_FLAG",
	"CAST(CROSSDOCK_ID AS STRING) as CROSSDOCK_ID",
	"CAST(ALT_ORIGIN1 AS STRING) as ALT_ORIGIN1",
	"CAST(ALT_ORIGIN2 AS STRING) as ALT_ORIGIN2",
	"CAST(ALT_ORIGIN3 AS STRING) as ALT_ORIGIN3",
	"CAST(ALT_ORIGIN4 AS STRING) as ALT_ORIGIN4",
	"CAST(ALT_ORIGIN5 AS STRING) as ALT_ORIGIN5",
	"CAST(ALT_ORIGIN6 AS STRING) as ALT_ORIGIN6",
	"CAST(ALT_ORIGIN7 AS STRING) as ALT_ORIGIN7",
	"CAST(CROSSDOCK_ID2 AS STRING) as CROSSDOCK_ID2",
	"CAST(CROSSDOCK_ID3 AS STRING) as CROSSDOCK_ID3",
	"CAST(CROSSDOCK_ID4 AS STRING) as CROSSDOCK_ID4",
	"CAST(CROSSDOCK_ID5 AS STRING) as CROSSDOCK_ID5",
	"CAST(CROSSDOCK_ID6 AS STRING) as CROSSDOCK_ID6",
	"CAST(CROSSDOCK_ID7 AS STRING) as CROSSDOCK_ID7",
	"CAST(DUE_BASED_ON_CD AS STRING) as DUE_BASED_ON_CD",
	"CAST(ORDER_DAY_OF_WK_ARRAY AS STRING) as ORDER_DAY_OF_WK_ARRAY",
	"CAST(WEEK_FREQ_CD AS STRING) as WEEK_FREQ_CD",
	"CAST(QUOTED_LT_DAY_CNT as smallint) as QUOTED_LT_DAY_CNT",
	"CAST(LT_DAY_CNT AS DECIMAL(5,2)) as LT_DAY_CNT",
	"CAST(LOAD_DT AS TIMESTAMP) as LOAD_DT",
	"CAST(MANDT AS STRING) as MANDT"
)


# COMMAND ----------

try:
    # chk=DuplicateChecker()
    # chk.check_for_duplicate_primary_keys(spark,Shortcut_to_DP_SITE_VEND_PROFILE,key)
    Shortcut_to_DP_SITE_VEND_PROFILE.write.saveAsTable(f'{legacy}.DP_SITE_VEND_PROFILE', mode = 'overwrite')
    logPrevRunDt("DP_SITE_VEND_PROFILE", "DP_SITE_VEND_PROFILE", "Completed", "N/A", f"{raw}.log_run_details")
except Exception as e:
    logPrevRunDt("DP_SITE_VEND_PROFILE", "DP_SITE_VEND_PROFILE","Failed",str(e), f"{raw}.log_run_details", )
    raise e
