#Code converted on 2023-06-26 17:05:04
import os
import argparse
from pyspark.sql import *
from pyspark.sql.functions import *
from pyspark.sql.window import Window
from pyspark.sql.types import *
from datetime import datetime
from pyspark.dbutils import DBUtils
from Datalake.utils.genericUtilities import *
from Datalake.utils.configs import *
from Datalake.utils.mergeUtils import *
from Datalake.utils.logger import *
# COMMAND ----------

parser = argparse.ArgumentParser()
spark = SparkSession.getActiveSession()
dbutils = DBUtils(spark)

parser.add_argument('env', type=str, help='Env Variable')
args = parser.parse_args()
env = args.env

if env is None or env == '':
    raise ValueError('env is not set')

refine = getEnvPrefix(env) + 'refine'
raw = getEnvPrefix(env) + 'raw'
legacy = getEnvPrefix(env) + 'legacy'

# Set global variables
starttime = datetime.now() #start timestamp of the script
refined_perf_table = f"{refine}.WM_OUTPT_ORDERS"
raw_perf_table = f"{raw}.WM_OUTPT_ORDERS_PRE"
site_profile_table = f"{legacy}.SITE_PROFILE"

# Read in relation source variables
(username, password, connection_string) = getConfig(DC_NBR, env)

# COMMAND ----------
# Processing node SQ_Shortcut_to_WM_OUTPT_ORDERS, type SOURCE 
# COLUMN COUNT: 5

SQ_Shortcut_to_WM_OUTPT_ORDERS = spark.sql(f"""SELECT
LOCATION_ID,
WM_OUTPT_ORDERS_ID,
WM_CREATED_TSTMP,
WM_LAST_UPDATED_TSTMP,
LOAD_TSTMP
FROM {refined_perf_table}
WHERE WM_OUTPT_ORDERS_ID IN (SELECT OUTPT_ORDERS_ID FROM {raw_perf_table})""").withColumn("sys_row_id", monotonically_increasing_id())

# COMMAND ----------
# Processing node SQ_Shortcut_to_WM_OUTPT_ORDERS_PRE, type SOURCE 
# COLUMN COUNT: 171

SQ_Shortcut_to_WM_OUTPT_ORDERS_PRE = spark.sql(f"""SELECT
DC_NBR,
OUTPT_ORDERS_ID,
ACCT_RCVBL_ACCT_NBR,
ACCT_RCVBL_CODE,
ADDR_CODE,
BACKORDERED_QUANTITY,
BATCH_CTRL_NBR,
BILLING_METHOD,
BILL_ACCT_NBR,
BILL_FACILITY_ALIAS_ID,
BILL_FACILITY_ID,
BILL_OF_LADING_NUMBER,
BILL_TO_ADDRESS_1,
BILL_TO_ADDRESS_2,
BILL_TO_ADDRESS_3,
BILL_TO_CITY,
BILL_TO_CONTACT,
BILL_TO_CONTACT_NAME,
BILL_TO_COUNTRY_CODE,
BILL_TO_COUNTY,
BILL_TO_EMAIL,
BILL_TO_FACILITY_NAME,
BILL_TO_FAX_NUMBER,
BILL_TO_NAME,
BILL_TO_PHONE_NUMBER,
BILL_TO_POSTAL_CODE,
BILL_TO_STATE_PROV,
BILL_TO_TITLE,
BOL_BREAK_ATTR,
BOL_TYPE,
BUSINESS_PARTNER,
CREATED_DTTM,
CREATED_SOURCE,
CREATED_SOURCE_TYPE,
CURRENCY,
D_ADDRESS_1,
D_ADDRESS_2,
D_ADDRESS_3,
D_CITY,
D_CONTACT,
D_COUNTRY_CODE,
D_COUNTY,
D_DOCK_DOOR_ID,
D_DOCK_ID,
D_EMAIL,
D_FACILITY_ALIAS_ID,
D_FACILITY_ID,
D_FACILITY_NAME,
D_FAX_NUMBER,
D_NAME,
D_PHONE_NUMBER,
D_POSTAL_CODE,
D_STATE_PROV,
DC_CTR_NBR,
DELIVERY_START_DTTM,
DISTRIBUTION_SHIP_VIA,
DO_TYPE,
ORIGINAL_SHIP_VIA,
EXT_PURCHASE_ORDER,
FREIGHT_CLASS,
FREIGHT_FORWARDER_ACCT_NBR,
GLOBAL_LOCN_NBR,
HANDLING_CHARGES,
INCOTERM_FACILITY_ALIAS_ID,
INCOTERM_FACILITY_ID,
INCOTERM_ID,
INCOTERM_LOC_AVA_DTTM,
INCOTERM_LOC_AVA_TIME_ZONE_ID,
INCOTERM_NAME,
INSUR_CHRG,
INVC_BATCH_NBR,
IS_BACK_ORDERED,
LAST_UPDATED_DTTM,
LAST_UPDATED_SOURCE,
LAST_UPDATED_SOURCE_TYPE,
MAJOR_MINOR_ORDER,
MAJOR_ORDER_CTRL_NBR,
MAJOR_ORDER_GRP_ATTR,
MANIFEST_ID,
MERCHANDIZING_DEPARTMENT,
MISC_CHARGES,
MONETARY_VALUE,
MOVEMENT_OPTION,
MV_CURRENCY,
NON_MACHINEABLE,
O_ADDRESS_1,
O_ADDRESS_2,
O_ADDRESS_3,
O_CITY,
O_CONTACT,
O_COUNTRY_CODE,
O_COUNTY,
O_DOCK_DOOR_ID,
O_DOCK_ID,
O_EMAIL,
O_FACILITY_ALIAS_ID,
O_FACILITY_ID,
O_FACILITY_NAME,
O_FAX_NUMBER,
O_POSTAL_CODE,
O_STATE_PROV,
ORDER_DATE_DTTM,
ORDER_WEIGHT,
ORG_SHIP_FACILITY_ALIAS_ID,
ORG_SHIP_FACILITY_ID,
ORIGINAL_ASSIGNED_SHIP_VIA,
ORIGIN_SHIP_THRU_FACILITY_ID,
ORIGIN_SHIP_THRU_FAC_ALIAS_ID,
PICKUP_END_DTTM,
PICKUP_START_DTTM,
PLANNED_SHIP_DATE,
PRE_PACK_FLAG,
PRIORITY,
PRO_NUMBER,
PROC_DTTM,
PROC_STAT_CODE,
REC_XPANS_FIELD,
RTE_ID,
RTE_SHIPMENT_SEQ,
SCHED_DELIVERY_DTTM,
SHIPMENT_ID,
SHIP_DATE,
SHIP_GROUP_ID,
SHIP_GROUP_SEQUENCE,
SHPNG_CHRG,
ORDER_STATUS,
DO_STATUS,
STORE_NBR,
STORE_TYPE,
TAX_CHARGES,
TC_COMPANY_ID,
TC_ORDER_ID,
TC_SHIPMENT_ID,
TOTAL_NBR_OF_LPN,
TOTAL_NBR_OF_PLT,
TOTAL_NBR_OF_UNITS,
VERSION_NBR,
LINE_HAUL_SHIP_VIA,
PLAN_D_FACILITY_ALIAS_ID,
PLAN_D_FACILITY_ID,
PLAN_LEG_D_ALIAS_ID,
PLAN_LEG_D_ID,
PLAN_LEG_O_ALIAS_ID,
PLAN_LEG_O_ID,
PLAN_O_FACILITY_ALIAS_ID,
PLAN_O_FACILITY_ID,
SPL_INSTR_CODE_1,
SPL_INSTR_CODE_10,
SPL_INSTR_CODE_2,
SPL_INSTR_CODE_3,
SPL_INSTR_CODE_4,
SPL_INSTR_CODE_5,
SPL_INSTR_CODE_6,
SPL_INSTR_CODE_7,
SPL_INSTR_CODE_8,
SPL_INSTR_CODE_9,
PRE_BILL_STATUS,
PRTL_SHIP_CONF_FLAG,
PRTL_SHIP_CONF_STATUS,
PRE_BILLED_FLAG,
TAX_ID,
ALLOW_PRE_BILLING,
O_PHONE_NUMBER,
PURCHASE_ORDER_NBR,
MARK_FOR,
DISTRO_NUMBER,
REF_SHIPMENT_NBR,
REF_STOP_SEQ,
PO_TYPE_ATTR,
DSG_SHIP_VIA,
LOAD_TSTMP
FROM {raw_perf_table}""").withColumn("sys_row_id", monotonically_increasing_id())

# COMMAND ----------
# Processing node EXP_INT_CONV, type EXPRESSION 
# COLUMN COUNT: 171

# for each involved DataFrame, append the dataframe name to each column
SQ_Shortcut_to_WM_OUTPT_ORDERS_PRE_temp = SQ_Shortcut_to_WM_OUTPT_ORDERS_PRE.toDF(*["SQ_Shortcut_to_WM_OUTPT_ORDERS_PRE___" + col for col in SQ_Shortcut_to_WM_OUTPT_ORDERS_PRE.columns])

EXP_INT_CONV = SQ_Shortcut_to_WM_OUTPT_ORDERS_PRE_temp.selectExpr( \
	"SQ_Shortcut_to_WM_OUTPT_ORDERS_PRE___sys_row_id as sys_row_id", \
	"cast(SQ_Shortcut_to_WM_OUTPT_ORDERS_PRE___DC_NBR as int) as o_DC_NBR", \
	"SQ_Shortcut_to_WM_OUTPT_ORDERS_PRE___OUTPT_ORDERS_ID as OUTPT_ORDERS_ID", \
	"SQ_Shortcut_to_WM_OUTPT_ORDERS_PRE___ACCT_RCVBL_ACCT_NBR as ACCT_RCVBL_ACCT_NBR", \
	"SQ_Shortcut_to_WM_OUTPT_ORDERS_PRE___ACCT_RCVBL_CODE as ACCT_RCVBL_CODE", \
	"SQ_Shortcut_to_WM_OUTPT_ORDERS_PRE___ADDR_CODE as ADDR_CODE", \
	"SQ_Shortcut_to_WM_OUTPT_ORDERS_PRE___BACKORDERED_QUANTITY as BACKORDERED_QUANTITY", \
	"SQ_Shortcut_to_WM_OUTPT_ORDERS_PRE___BATCH_CTRL_NBR as BATCH_CTRL_NBR", \
	"SQ_Shortcut_to_WM_OUTPT_ORDERS_PRE___BILLING_METHOD as BILLING_METHOD", \
	"SQ_Shortcut_to_WM_OUTPT_ORDERS_PRE___BILL_ACCT_NBR as BILL_ACCT_NBR", \
	"SQ_Shortcut_to_WM_OUTPT_ORDERS_PRE___BILL_FACILITY_ALIAS_ID as BILL_FACILITY_ALIAS_ID", \
	"SQ_Shortcut_to_WM_OUTPT_ORDERS_PRE___BILL_FACILITY_ID as BILL_FACILITY_ID", \
	"SQ_Shortcut_to_WM_OUTPT_ORDERS_PRE___BILL_OF_LADING_NUMBER as BILL_OF_LADING_NUMBER", \
	"SQ_Shortcut_to_WM_OUTPT_ORDERS_PRE___BILL_TO_ADDRESS_1 as BILL_TO_ADDRESS_1", \
	"SQ_Shortcut_to_WM_OUTPT_ORDERS_PRE___BILL_TO_ADDRESS_2 as BILL_TO_ADDRESS_2", \
	"SQ_Shortcut_to_WM_OUTPT_ORDERS_PRE___BILL_TO_ADDRESS_3 as BILL_TO_ADDRESS_3", \
	"SQ_Shortcut_to_WM_OUTPT_ORDERS_PRE___BILL_TO_CITY as BILL_TO_CITY", \
	"SQ_Shortcut_to_WM_OUTPT_ORDERS_PRE___BILL_TO_CONTACT as BILL_TO_CONTACT", \
	"SQ_Shortcut_to_WM_OUTPT_ORDERS_PRE___BILL_TO_CONTACT_NAME as BILL_TO_CONTACT_NAME", \
	"SQ_Shortcut_to_WM_OUTPT_ORDERS_PRE___BILL_TO_COUNTRY_CODE as BILL_TO_COUNTRY_CODE", \
	"SQ_Shortcut_to_WM_OUTPT_ORDERS_PRE___BILL_TO_COUNTY as BILL_TO_COUNTY", \
	"SQ_Shortcut_to_WM_OUTPT_ORDERS_PRE___BILL_TO_EMAIL as BILL_TO_EMAIL", \
	"SQ_Shortcut_to_WM_OUTPT_ORDERS_PRE___BILL_TO_FACILITY_NAME as BILL_TO_FACILITY_NAME", \
	"SQ_Shortcut_to_WM_OUTPT_ORDERS_PRE___BILL_TO_FAX_NUMBER as BILL_TO_FAX_NUMBER", \
	"SQ_Shortcut_to_WM_OUTPT_ORDERS_PRE___BILL_TO_NAME as BILL_TO_NAME", \
	"SQ_Shortcut_to_WM_OUTPT_ORDERS_PRE___BILL_TO_PHONE_NUMBER as BILL_TO_PHONE_NUMBER", \
	"SQ_Shortcut_to_WM_OUTPT_ORDERS_PRE___BILL_TO_POSTAL_CODE as BILL_TO_POSTAL_CODE", \
	"SQ_Shortcut_to_WM_OUTPT_ORDERS_PRE___BILL_TO_STATE_PROV as BILL_TO_STATE_PROV", \
	"SQ_Shortcut_to_WM_OUTPT_ORDERS_PRE___BILL_TO_TITLE as BILL_TO_TITLE", \
	"SQ_Shortcut_to_WM_OUTPT_ORDERS_PRE___BOL_BREAK_ATTR as BOL_BREAK_ATTR", \
	"SQ_Shortcut_to_WM_OUTPT_ORDERS_PRE___BOL_TYPE as BOL_TYPE", \
	"SQ_Shortcut_to_WM_OUTPT_ORDERS_PRE___BUSINESS_PARTNER as BUSINESS_PARTNER", \
	"SQ_Shortcut_to_WM_OUTPT_ORDERS_PRE___CREATED_DTTM as CREATED_DTTM", \
	"SQ_Shortcut_to_WM_OUTPT_ORDERS_PRE___CREATED_SOURCE as CREATED_SOURCE", \
	"SQ_Shortcut_to_WM_OUTPT_ORDERS_PRE___CREATED_SOURCE_TYPE as CREATED_SOURCE_TYPE", \
	"SQ_Shortcut_to_WM_OUTPT_ORDERS_PRE___CURRENCY as CURRENCY", \
	"SQ_Shortcut_to_WM_OUTPT_ORDERS_PRE___D_ADDRESS_1 as D_ADDRESS_1", \
	"SQ_Shortcut_to_WM_OUTPT_ORDERS_PRE___D_ADDRESS_2 as D_ADDRESS_2", \
	"SQ_Shortcut_to_WM_OUTPT_ORDERS_PRE___D_ADDRESS_3 as D_ADDRESS_3", \
	"SQ_Shortcut_to_WM_OUTPT_ORDERS_PRE___D_CITY as D_CITY", \
	"SQ_Shortcut_to_WM_OUTPT_ORDERS_PRE___D_CONTACT as D_CONTACT", \
	"SQ_Shortcut_to_WM_OUTPT_ORDERS_PRE___D_COUNTRY_CODE as D_COUNTRY_CODE", \
	"SQ_Shortcut_to_WM_OUTPT_ORDERS_PRE___D_COUNTY as D_COUNTY", \
	"SQ_Shortcut_to_WM_OUTPT_ORDERS_PRE___D_DOCK_DOOR_ID as D_DOCK_DOOR_ID", \
	"SQ_Shortcut_to_WM_OUTPT_ORDERS_PRE___D_DOCK_ID as D_DOCK_ID", \
	"SQ_Shortcut_to_WM_OUTPT_ORDERS_PRE___D_EMAIL as D_EMAIL", \
	"SQ_Shortcut_to_WM_OUTPT_ORDERS_PRE___D_FACILITY_ALIAS_ID as D_FACILITY_ALIAS_ID", \
	"SQ_Shortcut_to_WM_OUTPT_ORDERS_PRE___D_FACILITY_ID as D_FACILITY_ID", \
	"SQ_Shortcut_to_WM_OUTPT_ORDERS_PRE___D_FACILITY_NAME as D_FACILITY_NAME", \
	"SQ_Shortcut_to_WM_OUTPT_ORDERS_PRE___D_FAX_NUMBER as D_FAX_NUMBER", \
	"SQ_Shortcut_to_WM_OUTPT_ORDERS_PRE___D_NAME as D_NAME", \
	"SQ_Shortcut_to_WM_OUTPT_ORDERS_PRE___D_PHONE_NUMBER as D_PHONE_NUMBER", \
	"SQ_Shortcut_to_WM_OUTPT_ORDERS_PRE___D_POSTAL_CODE as D_POSTAL_CODE", \
	"SQ_Shortcut_to_WM_OUTPT_ORDERS_PRE___D_STATE_PROV as D_STATE_PROV", \
	"SQ_Shortcut_to_WM_OUTPT_ORDERS_PRE___DC_CTR_NBR as DC_CTR_NBR", \
	"SQ_Shortcut_to_WM_OUTPT_ORDERS_PRE___DELIVERY_START_DTTM as DELIVERY_START_DTTM", \
	"SQ_Shortcut_to_WM_OUTPT_ORDERS_PRE___DISTRIBUTION_SHIP_VIA as DISTRIBUTION_SHIP_VIA", \
	"SQ_Shortcut_to_WM_OUTPT_ORDERS_PRE___DO_TYPE as DO_TYPE", \
	"SQ_Shortcut_to_WM_OUTPT_ORDERS_PRE___ORIGINAL_SHIP_VIA as ORIGINAL_SHIP_VIA", \
	"SQ_Shortcut_to_WM_OUTPT_ORDERS_PRE___EXT_PURCHASE_ORDER as EXT_PURCHASE_ORDER", \
	"SQ_Shortcut_to_WM_OUTPT_ORDERS_PRE___FREIGHT_CLASS as FREIGHT_CLASS", \
	"SQ_Shortcut_to_WM_OUTPT_ORDERS_PRE___FREIGHT_FORWARDER_ACCT_NBR as FREIGHT_FORWARDER_ACCT_NBR", \
	"SQ_Shortcut_to_WM_OUTPT_ORDERS_PRE___GLOBAL_LOCN_NBR as GLOBAL_LOCN_NBR", \
	"SQ_Shortcut_to_WM_OUTPT_ORDERS_PRE___HANDLING_CHARGES as HANDLING_CHARGES", \
	"SQ_Shortcut_to_WM_OUTPT_ORDERS_PRE___INCOTERM_FACILITY_ALIAS_ID as INCOTERM_FACILITY_ALIAS_ID", \
	"SQ_Shortcut_to_WM_OUTPT_ORDERS_PRE___INCOTERM_FACILITY_ID as INCOTERM_FACILITY_ID", \
	"SQ_Shortcut_to_WM_OUTPT_ORDERS_PRE___INCOTERM_ID as INCOTERM_ID", \
	"SQ_Shortcut_to_WM_OUTPT_ORDERS_PRE___INCOTERM_LOC_AVA_DTTM as INCOTERM_LOC_AVA_DTTM", \
	"SQ_Shortcut_to_WM_OUTPT_ORDERS_PRE___INCOTERM_LOC_AVA_TIME_ZONE_ID as INCOTERM_LOC_AVA_TIME_ZONE_ID", \
	"SQ_Shortcut_to_WM_OUTPT_ORDERS_PRE___INCOTERM_NAME as INCOTERM_NAME", \
	"SQ_Shortcut_to_WM_OUTPT_ORDERS_PRE___INSUR_CHRG as INSUR_CHRG", \
	"SQ_Shortcut_to_WM_OUTPT_ORDERS_PRE___INVC_BATCH_NBR as INVC_BATCH_NBR", \
	"SQ_Shortcut_to_WM_OUTPT_ORDERS_PRE___IS_BACK_ORDERED as IS_BACK_ORDERED", \
	"SQ_Shortcut_to_WM_OUTPT_ORDERS_PRE___LAST_UPDATED_DTTM as LAST_UPDATED_DTTM", \
	"SQ_Shortcut_to_WM_OUTPT_ORDERS_PRE___LAST_UPDATED_SOURCE as LAST_UPDATED_SOURCE", \
	"SQ_Shortcut_to_WM_OUTPT_ORDERS_PRE___LAST_UPDATED_SOURCE_TYPE as LAST_UPDATED_SOURCE_TYPE", \
	"SQ_Shortcut_to_WM_OUTPT_ORDERS_PRE___MAJOR_MINOR_ORDER as MAJOR_MINOR_ORDER", \
	"SQ_Shortcut_to_WM_OUTPT_ORDERS_PRE___MAJOR_ORDER_CTRL_NBR as MAJOR_ORDER_CTRL_NBR", \
	"SQ_Shortcut_to_WM_OUTPT_ORDERS_PRE___MAJOR_ORDER_GRP_ATTR as MAJOR_ORDER_GRP_ATTR", \
	"SQ_Shortcut_to_WM_OUTPT_ORDERS_PRE___MANIFEST_ID as MANIFEST_ID", \
	"SQ_Shortcut_to_WM_OUTPT_ORDERS_PRE___MERCHANDIZING_DEPARTMENT as MERCHANDIZING_DEPARTMENT", \
	"SQ_Shortcut_to_WM_OUTPT_ORDERS_PRE___MISC_CHARGES as MISC_CHARGES", \
	"SQ_Shortcut_to_WM_OUTPT_ORDERS_PRE___MONETARY_VALUE as MONETARY_VALUE", \
	"SQ_Shortcut_to_WM_OUTPT_ORDERS_PRE___MOVEMENT_OPTION as MOVEMENT_OPTION", \
	"SQ_Shortcut_to_WM_OUTPT_ORDERS_PRE___MV_CURRENCY as MV_CURRENCY", \
	"SQ_Shortcut_to_WM_OUTPT_ORDERS_PRE___NON_MACHINEABLE as NON_MACHINEABLE", \
	"SQ_Shortcut_to_WM_OUTPT_ORDERS_PRE___O_ADDRESS_1 as O_ADDRESS_1", \
	"SQ_Shortcut_to_WM_OUTPT_ORDERS_PRE___O_ADDRESS_2 as O_ADDRESS_2", \
	"SQ_Shortcut_to_WM_OUTPT_ORDERS_PRE___O_ADDRESS_3 as O_ADDRESS_3", \
	"SQ_Shortcut_to_WM_OUTPT_ORDERS_PRE___O_CITY as O_CITY", \
	"SQ_Shortcut_to_WM_OUTPT_ORDERS_PRE___O_CONTACT as O_CONTACT", \
	"SQ_Shortcut_to_WM_OUTPT_ORDERS_PRE___O_COUNTRY_CODE as O_COUNTRY_CODE", \
	"SQ_Shortcut_to_WM_OUTPT_ORDERS_PRE___O_COUNTY as O_COUNTY", \
	"SQ_Shortcut_to_WM_OUTPT_ORDERS_PRE___O_DOCK_DOOR_ID as O_DOCK_DOOR_ID", \
	"SQ_Shortcut_to_WM_OUTPT_ORDERS_PRE___O_DOCK_ID as O_DOCK_ID", \
	"SQ_Shortcut_to_WM_OUTPT_ORDERS_PRE___O_EMAIL as O_EMAIL", \
	"SQ_Shortcut_to_WM_OUTPT_ORDERS_PRE___O_FACILITY_ALIAS_ID as O_FACILITY_ALIAS_ID", \
	"SQ_Shortcut_to_WM_OUTPT_ORDERS_PRE___O_FACILITY_ID as O_FACILITY_ID", \
	"SQ_Shortcut_to_WM_OUTPT_ORDERS_PRE___O_FACILITY_NAME as O_FACILITY_NAME", \
	"SQ_Shortcut_to_WM_OUTPT_ORDERS_PRE___O_FAX_NUMBER as O_FAX_NUMBER", \
	"SQ_Shortcut_to_WM_OUTPT_ORDERS_PRE___O_POSTAL_CODE as O_POSTAL_CODE", \
	"SQ_Shortcut_to_WM_OUTPT_ORDERS_PRE___O_STATE_PROV as O_STATE_PROV", \
	"SQ_Shortcut_to_WM_OUTPT_ORDERS_PRE___ORDER_DATE_DTTM as ORDER_DATE_DTTM", \
	"SQ_Shortcut_to_WM_OUTPT_ORDERS_PRE___ORDER_WEIGHT as ORDER_WEIGHT", \
	"SQ_Shortcut_to_WM_OUTPT_ORDERS_PRE___ORG_SHIP_FACILITY_ALIAS_ID as ORG_SHIP_FACILITY_ALIAS_ID", \
	"SQ_Shortcut_to_WM_OUTPT_ORDERS_PRE___ORG_SHIP_FACILITY_ID as ORG_SHIP_FACILITY_ID", \
	"SQ_Shortcut_to_WM_OUTPT_ORDERS_PRE___ORIGINAL_ASSIGNED_SHIP_VIA as ORIGINAL_ASSIGNED_SHIP_VIA", \
	"SQ_Shortcut_to_WM_OUTPT_ORDERS_PRE___ORIGIN_SHIP_THRU_FACILITY_ID as ORIGIN_SHIP_THRU_FACILITY_ID", \
	"SQ_Shortcut_to_WM_OUTPT_ORDERS_PRE___ORIGIN_SHIP_THRU_FAC_ALIAS_ID as ORIGIN_SHIP_THRU_FAC_ALIAS_ID", \
	"SQ_Shortcut_to_WM_OUTPT_ORDERS_PRE___PICKUP_END_DTTM as PICKUP_END_DTTM", \
	"SQ_Shortcut_to_WM_OUTPT_ORDERS_PRE___PICKUP_START_DTTM as PICKUP_START_DTTM", \
	"SQ_Shortcut_to_WM_OUTPT_ORDERS_PRE___PLANNED_SHIP_DATE as PLANNED_SHIP_DATE", \
	"SQ_Shortcut_to_WM_OUTPT_ORDERS_PRE___PRE_PACK_FLAG as PRE_PACK_FLAG", \
	"SQ_Shortcut_to_WM_OUTPT_ORDERS_PRE___PRIORITY as PRIORITY", \
	"SQ_Shortcut_to_WM_OUTPT_ORDERS_PRE___PRO_NUMBER as PRO_NUMBER", \
	"SQ_Shortcut_to_WM_OUTPT_ORDERS_PRE___PROC_DTTM as PROC_DTTM", \
	"SQ_Shortcut_to_WM_OUTPT_ORDERS_PRE___PROC_STAT_CODE as PROC_STAT_CODE", \
	"SQ_Shortcut_to_WM_OUTPT_ORDERS_PRE___REC_XPANS_FIELD as REC_XPANS_FIELD", \
	"SQ_Shortcut_to_WM_OUTPT_ORDERS_PRE___RTE_ID as RTE_ID", \
	"SQ_Shortcut_to_WM_OUTPT_ORDERS_PRE___RTE_SHIPMENT_SEQ as RTE_SHIPMENT_SEQ", \
	"SQ_Shortcut_to_WM_OUTPT_ORDERS_PRE___SCHED_DELIVERY_DTTM as SCHED_DELIVERY_DTTM", \
	"SQ_Shortcut_to_WM_OUTPT_ORDERS_PRE___SHIPMENT_ID as SHIPMENT_ID", \
	"SQ_Shortcut_to_WM_OUTPT_ORDERS_PRE___SHIP_DATE as SHIP_DATE", \
	"SQ_Shortcut_to_WM_OUTPT_ORDERS_PRE___SHIP_GROUP_ID as SHIP_GROUP_ID", \
	"SQ_Shortcut_to_WM_OUTPT_ORDERS_PRE___SHIP_GROUP_SEQUENCE as SHIP_GROUP_SEQUENCE", \
	"SQ_Shortcut_to_WM_OUTPT_ORDERS_PRE___SHPNG_CHRG as SHPNG_CHRG", \
	"SQ_Shortcut_to_WM_OUTPT_ORDERS_PRE___ORDER_STATUS as ORDER_STATUS", \
	"SQ_Shortcut_to_WM_OUTPT_ORDERS_PRE___DO_STATUS as DO_STATUS", \
	"SQ_Shortcut_to_WM_OUTPT_ORDERS_PRE___STORE_NBR as STORE_NBR", \
	"SQ_Shortcut_to_WM_OUTPT_ORDERS_PRE___STORE_TYPE as STORE_TYPE", \
	"SQ_Shortcut_to_WM_OUTPT_ORDERS_PRE___TAX_CHARGES as TAX_CHARGES", \
	"SQ_Shortcut_to_WM_OUTPT_ORDERS_PRE___TC_COMPANY_ID as TC_COMPANY_ID", \
	"SQ_Shortcut_to_WM_OUTPT_ORDERS_PRE___TC_ORDER_ID as TC_ORDER_ID", \
	"SQ_Shortcut_to_WM_OUTPT_ORDERS_PRE___TC_SHIPMENT_ID as TC_SHIPMENT_ID", \
	"SQ_Shortcut_to_WM_OUTPT_ORDERS_PRE___TOTAL_NBR_OF_LPN as TOTAL_NBR_OF_LPN", \
	"SQ_Shortcut_to_WM_OUTPT_ORDERS_PRE___TOTAL_NBR_OF_PLT as TOTAL_NBR_OF_PLT", \
	"SQ_Shortcut_to_WM_OUTPT_ORDERS_PRE___TOTAL_NBR_OF_UNITS as TOTAL_NBR_OF_UNITS", \
	"SQ_Shortcut_to_WM_OUTPT_ORDERS_PRE___VERSION_NBR as VERSION_NBR", \
	"SQ_Shortcut_to_WM_OUTPT_ORDERS_PRE___LINE_HAUL_SHIP_VIA as LINE_HAUL_SHIP_VIA", \
	"SQ_Shortcut_to_WM_OUTPT_ORDERS_PRE___PLAN_D_FACILITY_ALIAS_ID as PLAN_D_FACILITY_ALIAS_ID", \
	"SQ_Shortcut_to_WM_OUTPT_ORDERS_PRE___PLAN_D_FACILITY_ID as PLAN_D_FACILITY_ID", \
	"SQ_Shortcut_to_WM_OUTPT_ORDERS_PRE___PLAN_LEG_D_ALIAS_ID as PLAN_LEG_D_ALIAS_ID", \
	"SQ_Shortcut_to_WM_OUTPT_ORDERS_PRE___PLAN_LEG_D_ID as PLAN_LEG_D_ID", \
	"SQ_Shortcut_to_WM_OUTPT_ORDERS_PRE___PLAN_LEG_O_ALIAS_ID as PLAN_LEG_O_ALIAS_ID", \
	"SQ_Shortcut_to_WM_OUTPT_ORDERS_PRE___PLAN_LEG_O_ID as PLAN_LEG_O_ID", \
	"SQ_Shortcut_to_WM_OUTPT_ORDERS_PRE___PLAN_O_FACILITY_ALIAS_ID as PLAN_O_FACILITY_ALIAS_ID", \
	"SQ_Shortcut_to_WM_OUTPT_ORDERS_PRE___PLAN_O_FACILITY_ID as PLAN_O_FACILITY_ID", \
	"SQ_Shortcut_to_WM_OUTPT_ORDERS_PRE___SPL_INSTR_CODE_1 as SPL_INSTR_CODE_1", \
	"SQ_Shortcut_to_WM_OUTPT_ORDERS_PRE___SPL_INSTR_CODE_10 as SPL_INSTR_CODE_10", \
	"SQ_Shortcut_to_WM_OUTPT_ORDERS_PRE___SPL_INSTR_CODE_2 as SPL_INSTR_CODE_2", \
	"SQ_Shortcut_to_WM_OUTPT_ORDERS_PRE___SPL_INSTR_CODE_3 as SPL_INSTR_CODE_3", \
	"SQ_Shortcut_to_WM_OUTPT_ORDERS_PRE___SPL_INSTR_CODE_4 as SPL_INSTR_CODE_4", \
	"SQ_Shortcut_to_WM_OUTPT_ORDERS_PRE___SPL_INSTR_CODE_5 as SPL_INSTR_CODE_5", \
	"SQ_Shortcut_to_WM_OUTPT_ORDERS_PRE___SPL_INSTR_CODE_6 as SPL_INSTR_CODE_6", \
	"SQ_Shortcut_to_WM_OUTPT_ORDERS_PRE___SPL_INSTR_CODE_7 as SPL_INSTR_CODE_7", \
	"SQ_Shortcut_to_WM_OUTPT_ORDERS_PRE___SPL_INSTR_CODE_8 as SPL_INSTR_CODE_8", \
	"SQ_Shortcut_to_WM_OUTPT_ORDERS_PRE___SPL_INSTR_CODE_9 as SPL_INSTR_CODE_9", \
	"SQ_Shortcut_to_WM_OUTPT_ORDERS_PRE___PRE_BILL_STATUS as PRE_BILL_STATUS", \
	"SQ_Shortcut_to_WM_OUTPT_ORDERS_PRE___PRTL_SHIP_CONF_FLAG as PRTL_SHIP_CONF_FLAG", \
	"SQ_Shortcut_to_WM_OUTPT_ORDERS_PRE___PRTL_SHIP_CONF_STATUS as PRTL_SHIP_CONF_STATUS", \
	"SQ_Shortcut_to_WM_OUTPT_ORDERS_PRE___PRE_BILLED_FLAG as PRE_BILLED_FLAG", \
	"SQ_Shortcut_to_WM_OUTPT_ORDERS_PRE___TAX_ID as TAX_ID", \
	"SQ_Shortcut_to_WM_OUTPT_ORDERS_PRE___ALLOW_PRE_BILLING as ALLOW_PRE_BILLING", \
	"SQ_Shortcut_to_WM_OUTPT_ORDERS_PRE___O_PHONE_NUMBER as O_PHONE_NUMBER", \
	"SQ_Shortcut_to_WM_OUTPT_ORDERS_PRE___PURCHASE_ORDER_NBR as PURCHASE_ORDER_NBR", \
	"SQ_Shortcut_to_WM_OUTPT_ORDERS_PRE___MARK_FOR as MARK_FOR", \
	"SQ_Shortcut_to_WM_OUTPT_ORDERS_PRE___DISTRO_NUMBER as DISTRO_NUMBER", \
	"SQ_Shortcut_to_WM_OUTPT_ORDERS_PRE___REF_SHIPMENT_NBR as REF_SHIPMENT_NBR", \
	"SQ_Shortcut_to_WM_OUTPT_ORDERS_PRE___REF_STOP_SEQ as REF_STOP_SEQ", \
	"SQ_Shortcut_to_WM_OUTPT_ORDERS_PRE___PO_TYPE_ATTR as PO_TYPE_ATTR", \
	"SQ_Shortcut_to_WM_OUTPT_ORDERS_PRE___DSG_SHIP_VIA as DSG_SHIP_VIA", \
	"SQ_Shortcut_to_WM_OUTPT_ORDERS_PRE___LOAD_TSTMP as LOAD_TSTMP" \
)

# COMMAND ----------
# Processing node SQ_Shortcut_to_SITE_PROFILE, type SOURCE 
# COLUMN COUNT: 2

SQ_Shortcut_to_SITE_PROFILE = spark.sql(f"""SELECT LOCATION_ID, STORE_NBR FROM {site_profile_table}""").withColumn("sys_row_id", monotonically_increasing_id())

# COMMAND ----------
# Processing node JNR_SITE_PROFILE, type JOINER . Note: using additional SELECT to rename incoming columns
# COLUMN COUNT: 172

# for each involved DataFrame, append the dataframe name to each column
EXP_INT_CONV_temp = EXP_INT_CONV.toDF(*["EXP_INT_CONV___" + col for col in EXP_INT_CONV.columns])
SQ_Shortcut_to_SITE_PROFILE_temp = SQ_Shortcut_to_SITE_PROFILE.toDF(*["SQ_Shortcut_to_SITE_PROFILE___" + col for col in SQ_Shortcut_to_SITE_PROFILE.columns])

JNR_SITE_PROFILE = SQ_Shortcut_to_SITE_PROFILE_temp.join(EXP_INT_CONV_temp,[SQ_Shortcut_to_SITE_PROFILE_temp.SQ_Shortcut_to_SITE_PROFILE___STORE_NBR == EXP_INT_CONV_temp.EXP_INT_CONV___o_DC_NBR],'inner').selectExpr( \
	"EXP_INT_CONV___o_DC_NBR as DC_NBR", \
	"EXP_INT_CONV___OUTPT_ORDERS_ID as OUTPT_ORDERS_ID", \
	"EXP_INT_CONV___ACCT_RCVBL_ACCT_NBR as ACCT_RCVBL_ACCT_NBR", \
	"EXP_INT_CONV___ACCT_RCVBL_CODE as ACCT_RCVBL_CODE", \
	"EXP_INT_CONV___ADDR_CODE as ADDR_CODE", \
	"EXP_INT_CONV___BACKORDERED_QUANTITY as BACKORDERED_QUANTITY", \
	"EXP_INT_CONV___BATCH_CTRL_NBR as BATCH_CTRL_NBR", \
	"EXP_INT_CONV___BILLING_METHOD as BILLING_METHOD", \
	"EXP_INT_CONV___BILL_ACCT_NBR as BILL_ACCT_NBR", \
	"EXP_INT_CONV___BILL_FACILITY_ALIAS_ID as BILL_FACILITY_ALIAS_ID", \
	"EXP_INT_CONV___BILL_FACILITY_ID as BILL_FACILITY_ID", \
	"EXP_INT_CONV___BILL_OF_LADING_NUMBER as BILL_OF_LADING_NUMBER", \
	"EXP_INT_CONV___BILL_TO_ADDRESS_1 as BILL_TO_ADDRESS_1", \
	"EXP_INT_CONV___BILL_TO_ADDRESS_2 as BILL_TO_ADDRESS_2", \
	"EXP_INT_CONV___BILL_TO_ADDRESS_3 as BILL_TO_ADDRESS_3", \
	"EXP_INT_CONV___BILL_TO_CITY as BILL_TO_CITY", \
	"EXP_INT_CONV___BILL_TO_CONTACT as BILL_TO_CONTACT", \
	"EXP_INT_CONV___BILL_TO_CONTACT_NAME as BILL_TO_CONTACT_NAME", \
	"EXP_INT_CONV___BILL_TO_COUNTRY_CODE as BILL_TO_COUNTRY_CODE", \
	"EXP_INT_CONV___BILL_TO_COUNTY as BILL_TO_COUNTY", \
	"EXP_INT_CONV___BILL_TO_EMAIL as BILL_TO_EMAIL", \
	"EXP_INT_CONV___BILL_TO_FACILITY_NAME as BILL_TO_FACILITY_NAME", \
	"EXP_INT_CONV___BILL_TO_FAX_NUMBER as BILL_TO_FAX_NUMBER", \
	"EXP_INT_CONV___BILL_TO_NAME as BILL_TO_NAME", \
	"EXP_INT_CONV___BILL_TO_PHONE_NUMBER as BILL_TO_PHONE_NUMBER", \
	"EXP_INT_CONV___BILL_TO_POSTAL_CODE as BILL_TO_POSTAL_CODE", \
	"EXP_INT_CONV___BILL_TO_STATE_PROV as BILL_TO_STATE_PROV", \
	"EXP_INT_CONV___BILL_TO_TITLE as BILL_TO_TITLE", \
	"EXP_INT_CONV___BOL_BREAK_ATTR as BOL_BREAK_ATTR", \
	"EXP_INT_CONV___BOL_TYPE as BOL_TYPE", \
	"EXP_INT_CONV___BUSINESS_PARTNER as BUSINESS_PARTNER", \
	"EXP_INT_CONV___CREATED_DTTM as CREATED_DTTM", \
	"EXP_INT_CONV___CREATED_SOURCE as CREATED_SOURCE", \
	"EXP_INT_CONV___CREATED_SOURCE_TYPE as CREATED_SOURCE_TYPE", \
	"EXP_INT_CONV___CURRENCY as CURRENCY", \
	"EXP_INT_CONV___D_ADDRESS_1 as D_ADDRESS_1", \
	"EXP_INT_CONV___D_ADDRESS_2 as D_ADDRESS_2", \
	"EXP_INT_CONV___D_ADDRESS_3 as D_ADDRESS_3", \
	"EXP_INT_CONV___D_CITY as D_CITY", \
	"EXP_INT_CONV___D_CONTACT as D_CONTACT", \
	"EXP_INT_CONV___D_COUNTRY_CODE as D_COUNTRY_CODE", \
	"EXP_INT_CONV___D_COUNTY as D_COUNTY", \
	"EXP_INT_CONV___D_DOCK_DOOR_ID as D_DOCK_DOOR_ID", \
	"EXP_INT_CONV___D_DOCK_ID as D_DOCK_ID", \
	"EXP_INT_CONV___D_EMAIL as D_EMAIL", \
	"EXP_INT_CONV___D_FACILITY_ALIAS_ID as D_FACILITY_ALIAS_ID", \
	"EXP_INT_CONV___D_FACILITY_ID as D_FACILITY_ID", \
	"EXP_INT_CONV___D_FACILITY_NAME as D_FACILITY_NAME", \
	"EXP_INT_CONV___D_FAX_NUMBER as D_FAX_NUMBER", \
	"EXP_INT_CONV___D_NAME as D_NAME", \
	"EXP_INT_CONV___D_PHONE_NUMBER as D_PHONE_NUMBER", \
	"EXP_INT_CONV___D_POSTAL_CODE as D_POSTAL_CODE", \
	"EXP_INT_CONV___D_STATE_PROV as D_STATE_PROV", \
	"EXP_INT_CONV___DC_CTR_NBR as DC_CTR_NBR", \
	"EXP_INT_CONV___DELIVERY_START_DTTM as DELIVERY_START_DTTM", \
	"EXP_INT_CONV___DISTRIBUTION_SHIP_VIA as DISTRIBUTION_SHIP_VIA", \
	"EXP_INT_CONV___DO_TYPE as DO_TYPE", \
	"EXP_INT_CONV___ORIGINAL_SHIP_VIA as ORIGINAL_SHIP_VIA", \
	"EXP_INT_CONV___EXT_PURCHASE_ORDER as EXT_PURCHASE_ORDER", \
	"EXP_INT_CONV___FREIGHT_CLASS as FREIGHT_CLASS", \
	"EXP_INT_CONV___FREIGHT_FORWARDER_ACCT_NBR as FREIGHT_FORWARDER_ACCT_NBR", \
	"EXP_INT_CONV___GLOBAL_LOCN_NBR as GLOBAL_LOCN_NBR", \
	"EXP_INT_CONV___HANDLING_CHARGES as HANDLING_CHARGES", \
	"EXP_INT_CONV___INCOTERM_FACILITY_ALIAS_ID as INCOTERM_FACILITY_ALIAS_ID", \
	"EXP_INT_CONV___INCOTERM_FACILITY_ID as INCOTERM_FACILITY_ID", \
	"EXP_INT_CONV___INCOTERM_ID as INCOTERM_ID", \
	"EXP_INT_CONV___INCOTERM_LOC_AVA_DTTM as INCOTERM_LOC_AVA_DTTM", \
	"EXP_INT_CONV___INCOTERM_LOC_AVA_TIME_ZONE_ID as INCOTERM_LOC_AVA_TIME_ZONE_ID", \
	"EXP_INT_CONV___INCOTERM_NAME as INCOTERM_NAME", \
	"EXP_INT_CONV___INSUR_CHRG as INSUR_CHRG", \
	"EXP_INT_CONV___INVC_BATCH_NBR as INVC_BATCH_NBR", \
	"EXP_INT_CONV___IS_BACK_ORDERED as IS_BACK_ORDERED", \
	"EXP_INT_CONV___LAST_UPDATED_DTTM as LAST_UPDATED_DTTM", \
	"EXP_INT_CONV___LAST_UPDATED_SOURCE as LAST_UPDATED_SOURCE", \
	"EXP_INT_CONV___LAST_UPDATED_SOURCE_TYPE as LAST_UPDATED_SOURCE_TYPE", \
	"EXP_INT_CONV___MAJOR_MINOR_ORDER as MAJOR_MINOR_ORDER", \
	"EXP_INT_CONV___MAJOR_ORDER_CTRL_NBR as MAJOR_ORDER_CTRL_NBR", \
	"EXP_INT_CONV___MAJOR_ORDER_GRP_ATTR as MAJOR_ORDER_GRP_ATTR", \
	"EXP_INT_CONV___MANIFEST_ID as MANIFEST_ID", \
	"EXP_INT_CONV___MERCHANDIZING_DEPARTMENT as MERCHANDIZING_DEPARTMENT", \
	"EXP_INT_CONV___MISC_CHARGES as MISC_CHARGES", \
	"EXP_INT_CONV___MONETARY_VALUE as MONETARY_VALUE", \
	"EXP_INT_CONV___MOVEMENT_OPTION as MOVEMENT_OPTION", \
	"EXP_INT_CONV___MV_CURRENCY as MV_CURRENCY", \
	"EXP_INT_CONV___NON_MACHINEABLE as NON_MACHINEABLE", \
	"EXP_INT_CONV___O_ADDRESS_1 as O_ADDRESS_1", \
	"EXP_INT_CONV___O_ADDRESS_2 as O_ADDRESS_2", \
	"EXP_INT_CONV___O_ADDRESS_3 as O_ADDRESS_3", \
	"EXP_INT_CONV___O_CITY as O_CITY", \
	"EXP_INT_CONV___O_CONTACT as O_CONTACT", \
	"EXP_INT_CONV___O_COUNTRY_CODE as O_COUNTRY_CODE", \
	"EXP_INT_CONV___O_COUNTY as O_COUNTY", \
	"EXP_INT_CONV___O_DOCK_DOOR_ID as O_DOCK_DOOR_ID", \
	"EXP_INT_CONV___O_DOCK_ID as O_DOCK_ID", \
	"EXP_INT_CONV___O_EMAIL as O_EMAIL", \
	"EXP_INT_CONV___O_FACILITY_ALIAS_ID as O_FACILITY_ALIAS_ID", \
	"EXP_INT_CONV___O_FACILITY_ID as O_FACILITY_ID", \
	"EXP_INT_CONV___O_FACILITY_NAME as O_FACILITY_NAME", \
	"EXP_INT_CONV___O_FAX_NUMBER as O_FAX_NUMBER", \
	"EXP_INT_CONV___O_POSTAL_CODE as O_POSTAL_CODE", \
	"EXP_INT_CONV___O_STATE_PROV as O_STATE_PROV", \
	"EXP_INT_CONV___ORDER_DATE_DTTM as ORDER_DATE_DTTM", \
	"EXP_INT_CONV___ORDER_WEIGHT as ORDER_WEIGHT", \
	"EXP_INT_CONV___ORG_SHIP_FACILITY_ALIAS_ID as ORG_SHIP_FACILITY_ALIAS_ID", \
	"EXP_INT_CONV___ORG_SHIP_FACILITY_ID as ORG_SHIP_FACILITY_ID", \
	"EXP_INT_CONV___ORIGINAL_ASSIGNED_SHIP_VIA as ORIGINAL_ASSIGNED_SHIP_VIA", \
	"EXP_INT_CONV___ORIGIN_SHIP_THRU_FACILITY_ID as ORIGIN_SHIP_THRU_FACILITY_ID", \
	"EXP_INT_CONV___ORIGIN_SHIP_THRU_FAC_ALIAS_ID as ORIGIN_SHIP_THRU_FAC_ALIAS_ID", \
	"EXP_INT_CONV___PICKUP_END_DTTM as PICKUP_END_DTTM", \
	"EXP_INT_CONV___PICKUP_START_DTTM as PICKUP_START_DTTM", \
	"EXP_INT_CONV___PLANNED_SHIP_DATE as PLANNED_SHIP_DATE", \
	"EXP_INT_CONV___PRE_PACK_FLAG as PRE_PACK_FLAG", \
	"EXP_INT_CONV___PRIORITY as PRIORITY", \
	"EXP_INT_CONV___PRO_NUMBER as PRO_NUMBER", \
	"EXP_INT_CONV___PROC_DTTM as PROC_DTTM", \
	"EXP_INT_CONV___PROC_STAT_CODE as PROC_STAT_CODE", \
	"EXP_INT_CONV___REC_XPANS_FIELD as REC_XPANS_FIELD", \
	"EXP_INT_CONV___RTE_ID as RTE_ID", \
	"EXP_INT_CONV___RTE_SHIPMENT_SEQ as RTE_SHIPMENT_SEQ", \
	"EXP_INT_CONV___SCHED_DELIVERY_DTTM as SCHED_DELIVERY_DTTM", \
	"EXP_INT_CONV___SHIPMENT_ID as SHIPMENT_ID", \
	"EXP_INT_CONV___SHIP_DATE as SHIP_DATE", \
	"EXP_INT_CONV___SHIP_GROUP_ID as SHIP_GROUP_ID", \
	"EXP_INT_CONV___SHIP_GROUP_SEQUENCE as SHIP_GROUP_SEQUENCE", \
	"EXP_INT_CONV___SHPNG_CHRG as SHPNG_CHRG", \
	"EXP_INT_CONV___ORDER_STATUS as ORDER_STATUS", \
	"EXP_INT_CONV___DO_STATUS as DO_STATUS", \
	"EXP_INT_CONV___STORE_NBR as STORE_NBR", \
	"EXP_INT_CONV___STORE_TYPE as STORE_TYPE", \
	"EXP_INT_CONV___TAX_CHARGES as TAX_CHARGES", \
	"EXP_INT_CONV___TC_COMPANY_ID as TC_COMPANY_ID", \
	"EXP_INT_CONV___TC_ORDER_ID as TC_ORDER_ID", \
	"EXP_INT_CONV___TC_SHIPMENT_ID as TC_SHIPMENT_ID", \
	"EXP_INT_CONV___TOTAL_NBR_OF_LPN as TOTAL_NBR_OF_LPN", \
	"EXP_INT_CONV___TOTAL_NBR_OF_PLT as TOTAL_NBR_OF_PLT", \
	"EXP_INT_CONV___TOTAL_NBR_OF_UNITS as TOTAL_NBR_OF_UNITS", \
	"EXP_INT_CONV___VERSION_NBR as VERSION_NBR", \
	"EXP_INT_CONV___LINE_HAUL_SHIP_VIA as LINE_HAUL_SHIP_VIA", \
	"EXP_INT_CONV___PLAN_D_FACILITY_ALIAS_ID as PLAN_D_FACILITY_ALIAS_ID", \
	"EXP_INT_CONV___PLAN_D_FACILITY_ID as PLAN_D_FACILITY_ID", \
	"EXP_INT_CONV___PLAN_LEG_D_ALIAS_ID as PLAN_LEG_D_ALIAS_ID", \
	"EXP_INT_CONV___PLAN_LEG_D_ID as PLAN_LEG_D_ID", \
	"EXP_INT_CONV___PLAN_LEG_O_ALIAS_ID as PLAN_LEG_O_ALIAS_ID", \
	"EXP_INT_CONV___PLAN_LEG_O_ID as PLAN_LEG_O_ID", \
	"EXP_INT_CONV___PLAN_O_FACILITY_ALIAS_ID as PLAN_O_FACILITY_ALIAS_ID", \
	"EXP_INT_CONV___PLAN_O_FACILITY_ID as PLAN_O_FACILITY_ID", \
	"EXP_INT_CONV___SPL_INSTR_CODE_1 as SPL_INSTR_CODE_1", \
	"EXP_INT_CONV___SPL_INSTR_CODE_10 as SPL_INSTR_CODE_10", \
	"EXP_INT_CONV___SPL_INSTR_CODE_2 as SPL_INSTR_CODE_2", \
	"EXP_INT_CONV___SPL_INSTR_CODE_3 as SPL_INSTR_CODE_3", \
	"EXP_INT_CONV___SPL_INSTR_CODE_4 as SPL_INSTR_CODE_4", \
	"EXP_INT_CONV___SPL_INSTR_CODE_5 as SPL_INSTR_CODE_5", \
	"EXP_INT_CONV___SPL_INSTR_CODE_6 as SPL_INSTR_CODE_6", \
	"EXP_INT_CONV___SPL_INSTR_CODE_7 as SPL_INSTR_CODE_7", \
	"EXP_INT_CONV___SPL_INSTR_CODE_8 as SPL_INSTR_CODE_8", \
	"EXP_INT_CONV___SPL_INSTR_CODE_9 as SPL_INSTR_CODE_9", \
	"EXP_INT_CONV___PRE_BILL_STATUS as PRE_BILL_STATUS", \
	"EXP_INT_CONV___PRTL_SHIP_CONF_FLAG as PRTL_SHIP_CONF_FLAG", \
	"EXP_INT_CONV___PRTL_SHIP_CONF_STATUS as PRTL_SHIP_CONF_STATUS", \
	"EXP_INT_CONV___PRE_BILLED_FLAG as PRE_BILLED_FLAG", \
	"EXP_INT_CONV___TAX_ID as TAX_ID", \
	"EXP_INT_CONV___ALLOW_PRE_BILLING as ALLOW_PRE_BILLING", \
	"EXP_INT_CONV___O_PHONE_NUMBER as O_PHONE_NUMBER", \
	"EXP_INT_CONV___PURCHASE_ORDER_NBR as PURCHASE_ORDER_NBR", \
	"EXP_INT_CONV___MARK_FOR as MARK_FOR", \
	"EXP_INT_CONV___DISTRO_NUMBER as DISTRO_NUMBER", \
	"EXP_INT_CONV___REF_SHIPMENT_NBR as REF_SHIPMENT_NBR", \
	"EXP_INT_CONV___REF_STOP_SEQ as REF_STOP_SEQ", \
	"EXP_INT_CONV___PO_TYPE_ATTR as PO_TYPE_ATTR", \
	"EXP_INT_CONV___DSG_SHIP_VIA as DSG_SHIP_VIA", \
	"SQ_Shortcut_to_SITE_PROFILE___LOCATION_ID as LOCATION_ID", \
	"SQ_Shortcut_to_SITE_PROFILE___STORE_NBR as in_STORE_NBR")

# COMMAND ----------
# Processing node JNR_WM_OUTPUT_ORDERS, type JOINER . Note: using additional SELECT to rename incoming columns
# COLUMN COUNT: 175

# for each involved DataFrame, append the dataframe name to each column
SQ_Shortcut_to_WM_OUTPT_ORDERS_temp = SQ_Shortcut_to_WM_OUTPT_ORDERS.toDF(*["SQ_Shortcut_to_WM_OUTPT_ORDERS___" + col for col in SQ_Shortcut_to_WM_OUTPT_ORDERS.columns])
JNR_SITE_PROFILE_temp = JNR_SITE_PROFILE.toDF(*["JNR_SITE_PROFILE___" + col for col in JNR_SITE_PROFILE.columns])

JNR_WM_OUTPUT_ORDERS = SQ_Shortcut_to_WM_OUTPT_ORDERS_temp.join(JNR_SITE_PROFILE_temp,[SQ_Shortcut_to_WM_OUTPT_ORDERS_temp.SQ_Shortcut_to_WM_OUTPT_ORDERS___LOCATION_ID == JNR_SITE_PROFILE_temp.JNR_SITE_PROFILE___LOCATION_ID, SQ_Shortcut_to_WM_OUTPT_ORDERS_temp.SQ_Shortcut_to_WM_OUTPT_ORDERS___WM_OUTPT_ORDERS_ID == JNR_SITE_PROFILE_temp.JNR_SITE_PROFILE___OUTPT_ORDERS_ID],'right_outer').selectExpr( \
	"JNR_SITE_PROFILE___LOCATION_ID as LOCATION_ID", \
	"JNR_SITE_PROFILE___OUTPT_ORDERS_ID as OUTPT_ORDERS_ID", \
	"JNR_SITE_PROFILE___ACCT_RCVBL_ACCT_NBR as ACCT_RCVBL_ACCT_NBR", \
	"JNR_SITE_PROFILE___ACCT_RCVBL_CODE as ACCT_RCVBL_CODE", \
	"JNR_SITE_PROFILE___ADDR_CODE as ADDR_CODE", \
	"JNR_SITE_PROFILE___BACKORDERED_QUANTITY as BACKORDERED_QUANTITY", \
	"JNR_SITE_PROFILE___BATCH_CTRL_NBR as BATCH_CTRL_NBR", \
	"JNR_SITE_PROFILE___BILLING_METHOD as BILLING_METHOD", \
	"JNR_SITE_PROFILE___BILL_ACCT_NBR as BILL_ACCT_NBR", \
	"JNR_SITE_PROFILE___BILL_FACILITY_ALIAS_ID as BILL_FACILITY_ALIAS_ID", \
	"JNR_SITE_PROFILE___BILL_FACILITY_ID as BILL_FACILITY_ID", \
	"JNR_SITE_PROFILE___BILL_OF_LADING_NUMBER as BILL_OF_LADING_NUMBER", \
	"JNR_SITE_PROFILE___BILL_TO_ADDRESS_1 as BILL_TO_ADDRESS_1", \
	"JNR_SITE_PROFILE___BILL_TO_ADDRESS_2 as BILL_TO_ADDRESS_2", \
	"JNR_SITE_PROFILE___BILL_TO_ADDRESS_3 as BILL_TO_ADDRESS_3", \
	"JNR_SITE_PROFILE___BILL_TO_CITY as BILL_TO_CITY", \
	"JNR_SITE_PROFILE___BILL_TO_CONTACT as BILL_TO_CONTACT", \
	"JNR_SITE_PROFILE___BILL_TO_CONTACT_NAME as BILL_TO_CONTACT_NAME", \
	"JNR_SITE_PROFILE___BILL_TO_COUNTRY_CODE as BILL_TO_COUNTRY_CODE", \
	"JNR_SITE_PROFILE___BILL_TO_COUNTY as BILL_TO_COUNTY", \
	"JNR_SITE_PROFILE___BILL_TO_EMAIL as BILL_TO_EMAIL", \
	"JNR_SITE_PROFILE___BILL_TO_FACILITY_NAME as BILL_TO_FACILITY_NAME", \
	"JNR_SITE_PROFILE___BILL_TO_FAX_NUMBER as BILL_TO_FAX_NUMBER", \
	"JNR_SITE_PROFILE___BILL_TO_NAME as BILL_TO_NAME", \
	"JNR_SITE_PROFILE___BILL_TO_PHONE_NUMBER as BILL_TO_PHONE_NUMBER", \
	"JNR_SITE_PROFILE___BILL_TO_POSTAL_CODE as BILL_TO_POSTAL_CODE", \
	"JNR_SITE_PROFILE___BILL_TO_STATE_PROV as BILL_TO_STATE_PROV", \
	"JNR_SITE_PROFILE___BILL_TO_TITLE as BILL_TO_TITLE", \
	"JNR_SITE_PROFILE___BOL_BREAK_ATTR as BOL_BREAK_ATTR", \
	"JNR_SITE_PROFILE___BOL_TYPE as BOL_TYPE", \
	"JNR_SITE_PROFILE___BUSINESS_PARTNER as BUSINESS_PARTNER", \
	"JNR_SITE_PROFILE___CREATED_DTTM as CREATED_DTTM", \
	"JNR_SITE_PROFILE___CREATED_SOURCE as CREATED_SOURCE", \
	"JNR_SITE_PROFILE___CREATED_SOURCE_TYPE as CREATED_SOURCE_TYPE", \
	"JNR_SITE_PROFILE___CURRENCY as CURRENCY", \
	"JNR_SITE_PROFILE___D_ADDRESS_1 as D_ADDRESS_1", \
	"JNR_SITE_PROFILE___D_ADDRESS_2 as D_ADDRESS_2", \
	"JNR_SITE_PROFILE___D_ADDRESS_3 as D_ADDRESS_3", \
	"JNR_SITE_PROFILE___D_CITY as D_CITY", \
	"JNR_SITE_PROFILE___D_CONTACT as D_CONTACT", \
	"JNR_SITE_PROFILE___D_COUNTRY_CODE as D_COUNTRY_CODE", \
	"JNR_SITE_PROFILE___D_COUNTY as D_COUNTY", \
	"JNR_SITE_PROFILE___D_DOCK_DOOR_ID as D_DOCK_DOOR_ID", \
	"JNR_SITE_PROFILE___D_DOCK_ID as D_DOCK_ID", \
	"JNR_SITE_PROFILE___D_EMAIL as D_EMAIL", \
	"JNR_SITE_PROFILE___D_FACILITY_ALIAS_ID as D_FACILITY_ALIAS_ID", \
	"JNR_SITE_PROFILE___D_FACILITY_ID as D_FACILITY_ID", \
	"JNR_SITE_PROFILE___D_FACILITY_NAME as D_FACILITY_NAME", \
	"JNR_SITE_PROFILE___D_FAX_NUMBER as D_FAX_NUMBER", \
	"JNR_SITE_PROFILE___D_NAME as D_NAME", \
	"JNR_SITE_PROFILE___D_PHONE_NUMBER as D_PHONE_NUMBER", \
	"JNR_SITE_PROFILE___D_POSTAL_CODE as D_POSTAL_CODE", \
	"JNR_SITE_PROFILE___D_STATE_PROV as D_STATE_PROV", \
	"JNR_SITE_PROFILE___DC_CTR_NBR as DC_CTR_NBR", \
	"JNR_SITE_PROFILE___DELIVERY_START_DTTM as DELIVERY_START_DTTM", \
	"JNR_SITE_PROFILE___DISTRIBUTION_SHIP_VIA as DISTRIBUTION_SHIP_VIA", \
	"JNR_SITE_PROFILE___DO_TYPE as DO_TYPE", \
	"JNR_SITE_PROFILE___ORIGINAL_SHIP_VIA as ORIGINAL_SHIP_VIA", \
	"JNR_SITE_PROFILE___EXT_PURCHASE_ORDER as EXT_PURCHASE_ORDER", \
	"JNR_SITE_PROFILE___FREIGHT_CLASS as FREIGHT_CLASS", \
	"JNR_SITE_PROFILE___FREIGHT_FORWARDER_ACCT_NBR as FREIGHT_FORWARDER_ACCT_NBR", \
	"JNR_SITE_PROFILE___GLOBAL_LOCN_NBR as GLOBAL_LOCN_NBR", \
	"JNR_SITE_PROFILE___HANDLING_CHARGES as HANDLING_CHARGES", \
	"JNR_SITE_PROFILE___INCOTERM_FACILITY_ALIAS_ID as INCOTERM_FACILITY_ALIAS_ID", \
	"JNR_SITE_PROFILE___INCOTERM_FACILITY_ID as INCOTERM_FACILITY_ID", \
	"JNR_SITE_PROFILE___INCOTERM_ID as INCOTERM_ID", \
	"JNR_SITE_PROFILE___INCOTERM_LOC_AVA_DTTM as INCOTERM_LOC_AVA_DTTM", \
	"JNR_SITE_PROFILE___INCOTERM_LOC_AVA_TIME_ZONE_ID as INCOTERM_LOC_AVA_TIME_ZONE_ID", \
	"JNR_SITE_PROFILE___INCOTERM_NAME as INCOTERM_NAME", \
	"JNR_SITE_PROFILE___INSUR_CHRG as INSUR_CHRG", \
	"JNR_SITE_PROFILE___INVC_BATCH_NBR as INVC_BATCH_NBR", \
	"JNR_SITE_PROFILE___IS_BACK_ORDERED as IS_BACK_ORDERED", \
	"JNR_SITE_PROFILE___LAST_UPDATED_DTTM as LAST_UPDATED_DTTM", \
	"JNR_SITE_PROFILE___LAST_UPDATED_SOURCE as LAST_UPDATED_SOURCE", \
	"JNR_SITE_PROFILE___LAST_UPDATED_SOURCE_TYPE as LAST_UPDATED_SOURCE_TYPE", \
	"JNR_SITE_PROFILE___MAJOR_MINOR_ORDER as MAJOR_MINOR_ORDER", \
	"JNR_SITE_PROFILE___MAJOR_ORDER_CTRL_NBR as MAJOR_ORDER_CTRL_NBR", \
	"JNR_SITE_PROFILE___MAJOR_ORDER_GRP_ATTR as MAJOR_ORDER_GRP_ATTR", \
	"JNR_SITE_PROFILE___MANIFEST_ID as MANIFEST_ID", \
	"JNR_SITE_PROFILE___MERCHANDIZING_DEPARTMENT as MERCHANDIZING_DEPARTMENT", \
	"JNR_SITE_PROFILE___MISC_CHARGES as MISC_CHARGES", \
	"JNR_SITE_PROFILE___MONETARY_VALUE as MONETARY_VALUE", \
	"JNR_SITE_PROFILE___MOVEMENT_OPTION as MOVEMENT_OPTION", \
	"JNR_SITE_PROFILE___MV_CURRENCY as MV_CURRENCY", \
	"JNR_SITE_PROFILE___NON_MACHINEABLE as NON_MACHINEABLE", \
	"JNR_SITE_PROFILE___O_ADDRESS_1 as O_ADDRESS_1", \
	"JNR_SITE_PROFILE___O_ADDRESS_2 as O_ADDRESS_2", \
	"JNR_SITE_PROFILE___O_ADDRESS_3 as O_ADDRESS_3", \
	"JNR_SITE_PROFILE___O_CITY as O_CITY", \
	"JNR_SITE_PROFILE___O_CONTACT as O_CONTACT", \
	"JNR_SITE_PROFILE___O_COUNTRY_CODE as O_COUNTRY_CODE", \
	"JNR_SITE_PROFILE___O_COUNTY as O_COUNTY", \
	"JNR_SITE_PROFILE___O_DOCK_DOOR_ID as O_DOCK_DOOR_ID", \
	"JNR_SITE_PROFILE___O_DOCK_ID as O_DOCK_ID", \
	"JNR_SITE_PROFILE___O_EMAIL as O_EMAIL", \
	"JNR_SITE_PROFILE___O_FACILITY_ALIAS_ID as O_FACILITY_ALIAS_ID", \
	"JNR_SITE_PROFILE___O_FACILITY_ID as O_FACILITY_ID", \
	"JNR_SITE_PROFILE___O_FACILITY_NAME as O_FACILITY_NAME", \
	"JNR_SITE_PROFILE___O_FAX_NUMBER as O_FAX_NUMBER", \
	"JNR_SITE_PROFILE___O_POSTAL_CODE as O_POSTAL_CODE", \
	"JNR_SITE_PROFILE___O_STATE_PROV as O_STATE_PROV", \
	"JNR_SITE_PROFILE___ORDER_DATE_DTTM as ORDER_DATE_DTTM", \
	"JNR_SITE_PROFILE___ORDER_WEIGHT as ORDER_WEIGHT", \
	"JNR_SITE_PROFILE___ORG_SHIP_FACILITY_ALIAS_ID as ORG_SHIP_FACILITY_ALIAS_ID", \
	"JNR_SITE_PROFILE___ORG_SHIP_FACILITY_ID as ORG_SHIP_FACILITY_ID", \
	"JNR_SITE_PROFILE___ORIGINAL_ASSIGNED_SHIP_VIA as ORIGINAL_ASSIGNED_SHIP_VIA", \
	"JNR_SITE_PROFILE___ORIGIN_SHIP_THRU_FACILITY_ID as ORIGIN_SHIP_THRU_FACILITY_ID", \
	"JNR_SITE_PROFILE___ORIGIN_SHIP_THRU_FAC_ALIAS_ID as ORIGIN_SHIP_THRU_FAC_ALIAS_ID", \
	"JNR_SITE_PROFILE___PICKUP_END_DTTM as PICKUP_END_DTTM", \
	"JNR_SITE_PROFILE___PICKUP_START_DTTM as PICKUP_START_DTTM", \
	"JNR_SITE_PROFILE___PLANNED_SHIP_DATE as PLANNED_SHIP_DATE", \
	"JNR_SITE_PROFILE___PRE_PACK_FLAG as PRE_PACK_FLAG", \
	"JNR_SITE_PROFILE___PRIORITY as PRIORITY", \
	"JNR_SITE_PROFILE___PRO_NUMBER as PRO_NUMBER", \
	"JNR_SITE_PROFILE___PROC_DTTM as PROC_DTTM", \
	"JNR_SITE_PROFILE___PROC_STAT_CODE as PROC_STAT_CODE", \
	"JNR_SITE_PROFILE___REC_XPANS_FIELD as REC_XPANS_FIELD", \
	"JNR_SITE_PROFILE___RTE_ID as RTE_ID", \
	"JNR_SITE_PROFILE___RTE_SHIPMENT_SEQ as RTE_SHIPMENT_SEQ", \
	"JNR_SITE_PROFILE___SCHED_DELIVERY_DTTM as SCHED_DELIVERY_DTTM", \
	"JNR_SITE_PROFILE___SHIPMENT_ID as SHIPMENT_ID", \
	"JNR_SITE_PROFILE___SHIP_DATE as SHIP_DATE", \
	"JNR_SITE_PROFILE___SHIP_GROUP_ID as SHIP_GROUP_ID", \
	"JNR_SITE_PROFILE___SHIP_GROUP_SEQUENCE as SHIP_GROUP_SEQUENCE", \
	"JNR_SITE_PROFILE___SHPNG_CHRG as SHPNG_CHRG", \
	"JNR_SITE_PROFILE___ORDER_STATUS as ORDER_STATUS", \
	"JNR_SITE_PROFILE___DO_STATUS as DO_STATUS", \
	"JNR_SITE_PROFILE___STORE_NBR as STORE_NBR", \
	"JNR_SITE_PROFILE___STORE_TYPE as STORE_TYPE", \
	"JNR_SITE_PROFILE___TAX_CHARGES as TAX_CHARGES", \
	"JNR_SITE_PROFILE___TC_COMPANY_ID as TC_COMPANY_ID", \
	"JNR_SITE_PROFILE___TC_ORDER_ID as TC_ORDER_ID", \
	"JNR_SITE_PROFILE___TC_SHIPMENT_ID as TC_SHIPMENT_ID", \
	"JNR_SITE_PROFILE___TOTAL_NBR_OF_LPN as TOTAL_NBR_OF_LPN", \
	"JNR_SITE_PROFILE___TOTAL_NBR_OF_PLT as TOTAL_NBR_OF_PLT", \
	"JNR_SITE_PROFILE___TOTAL_NBR_OF_UNITS as TOTAL_NBR_OF_UNITS", \
	"JNR_SITE_PROFILE___VERSION_NBR as VERSION_NBR", \
	"JNR_SITE_PROFILE___LINE_HAUL_SHIP_VIA as LINE_HAUL_SHIP_VIA", \
	"JNR_SITE_PROFILE___PLAN_D_FACILITY_ALIAS_ID as PLAN_D_FACILITY_ALIAS_ID", \
	"JNR_SITE_PROFILE___PLAN_D_FACILITY_ID as PLAN_D_FACILITY_ID", \
	"JNR_SITE_PROFILE___PLAN_LEG_D_ALIAS_ID as PLAN_LEG_D_ALIAS_ID", \
	"JNR_SITE_PROFILE___PLAN_LEG_D_ID as PLAN_LEG_D_ID", \
	"JNR_SITE_PROFILE___PLAN_LEG_O_ALIAS_ID as PLAN_LEG_O_ALIAS_ID", \
	"JNR_SITE_PROFILE___PLAN_LEG_O_ID as PLAN_LEG_O_ID", \
	"JNR_SITE_PROFILE___PLAN_O_FACILITY_ALIAS_ID as PLAN_O_FACILITY_ALIAS_ID", \
	"JNR_SITE_PROFILE___PLAN_O_FACILITY_ID as PLAN_O_FACILITY_ID", \
	"JNR_SITE_PROFILE___SPL_INSTR_CODE_1 as SPL_INSTR_CODE_1", \
	"JNR_SITE_PROFILE___SPL_INSTR_CODE_10 as SPL_INSTR_CODE_10", \
	"JNR_SITE_PROFILE___SPL_INSTR_CODE_2 as SPL_INSTR_CODE_2", \
	"JNR_SITE_PROFILE___SPL_INSTR_CODE_3 as SPL_INSTR_CODE_3", \
	"JNR_SITE_PROFILE___SPL_INSTR_CODE_4 as SPL_INSTR_CODE_4", \
	"JNR_SITE_PROFILE___SPL_INSTR_CODE_5 as SPL_INSTR_CODE_5", \
	"JNR_SITE_PROFILE___SPL_INSTR_CODE_6 as SPL_INSTR_CODE_6", \
	"JNR_SITE_PROFILE___SPL_INSTR_CODE_7 as SPL_INSTR_CODE_7", \
	"JNR_SITE_PROFILE___SPL_INSTR_CODE_8 as SPL_INSTR_CODE_8", \
	"JNR_SITE_PROFILE___SPL_INSTR_CODE_9 as SPL_INSTR_CODE_9", \
	"JNR_SITE_PROFILE___PRE_BILL_STATUS as PRE_BILL_STATUS", \
	"JNR_SITE_PROFILE___PRTL_SHIP_CONF_FLAG as PRTL_SHIP_CONF_FLAG", \
	"JNR_SITE_PROFILE___PRTL_SHIP_CONF_STATUS as PRTL_SHIP_CONF_STATUS", \
	"JNR_SITE_PROFILE___PRE_BILLED_FLAG as PRE_BILLED_FLAG", \
	"JNR_SITE_PROFILE___TAX_ID as TAX_ID", \
	"JNR_SITE_PROFILE___ALLOW_PRE_BILLING as ALLOW_PRE_BILLING", \
	"JNR_SITE_PROFILE___O_PHONE_NUMBER as O_PHONE_NUMBER", \
	"JNR_SITE_PROFILE___PURCHASE_ORDER_NBR as PURCHASE_ORDER_NBR", \
	"JNR_SITE_PROFILE___MARK_FOR as MARK_FOR", \
	"JNR_SITE_PROFILE___DISTRO_NUMBER as DISTRO_NUMBER", \
	"JNR_SITE_PROFILE___REF_SHIPMENT_NBR as REF_SHIPMENT_NBR", \
	"JNR_SITE_PROFILE___REF_STOP_SEQ as REF_STOP_SEQ", \
	"JNR_SITE_PROFILE___PO_TYPE_ATTR as PO_TYPE_ATTR", \
	"JNR_SITE_PROFILE___DSG_SHIP_VIA as DSG_SHIP_VIA", \
	"SQ_Shortcut_to_WM_OUTPT_ORDERS___LOCATION_ID as in_LOCATION_ID", \
	"SQ_Shortcut_to_WM_OUTPT_ORDERS___WM_OUTPT_ORDERS_ID as in_WM_OUTPT_ORDERS_ID", \
	"SQ_Shortcut_to_WM_OUTPT_ORDERS___WM_CREATED_TSTMP as in_WM_CREATED_TSTMP", \
	"SQ_Shortcut_to_WM_OUTPT_ORDERS___WM_LAST_UPDATED_TSTMP as in_WM_LAST_UPDATED_TSTMP", \
	"SQ_Shortcut_to_WM_OUTPT_ORDERS___LOAD_TSTMP as in_LOAD_TSTMP")

# COMMAND ----------
# Processing node FIL_UNCHANGED_REC, type FILTER 
# COLUMN COUNT: 175

# for each involved DataFrame, append the dataframe name to each column
JNR_WM_OUTPUT_ORDERS_temp = JNR_WM_OUTPUT_ORDERS.toDF(*["JNR_WM_OUTPUT_ORDERS___" + col for col in JNR_WM_OUTPUT_ORDERS.columns])

FIL_UNCHANGED_REC = JNR_WM_OUTPUT_ORDERS_temp.selectExpr( \
	"JNR_WM_OUTPUT_ORDERS___LOCATION_ID as LOCATION_ID", \
	"JNR_WM_OUTPUT_ORDERS___OUTPT_ORDERS_ID as OUTPT_ORDERS_ID", \
	"JNR_WM_OUTPUT_ORDERS___ACCT_RCVBL_ACCT_NBR as ACCT_RCVBL_ACCT_NBR", \
	"JNR_WM_OUTPUT_ORDERS___ACCT_RCVBL_CODE as ACCT_RCVBL_CODE", \
	"JNR_WM_OUTPUT_ORDERS___ADDR_CODE as ADDR_CODE", \
	"JNR_WM_OUTPUT_ORDERS___BACKORDERED_QUANTITY as BACKORDERED_QUANTITY", \
	"JNR_WM_OUTPUT_ORDERS___BATCH_CTRL_NBR as BATCH_CTRL_NBR", \
	"JNR_WM_OUTPUT_ORDERS___BILLING_METHOD as BILLING_METHOD", \
	"JNR_WM_OUTPUT_ORDERS___BILL_ACCT_NBR as BILL_ACCT_NBR", \
	"JNR_WM_OUTPUT_ORDERS___BILL_FACILITY_ALIAS_ID as BILL_FACILITY_ALIAS_ID", \
	"JNR_WM_OUTPUT_ORDERS___BILL_FACILITY_ID as BILL_FACILITY_ID", \
	"JNR_WM_OUTPUT_ORDERS___BILL_OF_LADING_NUMBER as BILL_OF_LADING_NUMBER", \
	"JNR_WM_OUTPUT_ORDERS___BILL_TO_ADDRESS_1 as BILL_TO_ADDRESS_1", \
	"JNR_WM_OUTPUT_ORDERS___BILL_TO_ADDRESS_2 as BILL_TO_ADDRESS_2", \
	"JNR_WM_OUTPUT_ORDERS___BILL_TO_ADDRESS_3 as BILL_TO_ADDRESS_3", \
	"JNR_WM_OUTPUT_ORDERS___BILL_TO_CITY as BILL_TO_CITY", \
	"JNR_WM_OUTPUT_ORDERS___BILL_TO_CONTACT as BILL_TO_CONTACT", \
	"JNR_WM_OUTPUT_ORDERS___BILL_TO_CONTACT_NAME as BILL_TO_CONTACT_NAME", \
	"JNR_WM_OUTPUT_ORDERS___BILL_TO_COUNTRY_CODE as BILL_TO_COUNTRY_CODE", \
	"JNR_WM_OUTPUT_ORDERS___BILL_TO_COUNTY as BILL_TO_COUNTY", \
	"JNR_WM_OUTPUT_ORDERS___BILL_TO_EMAIL as BILL_TO_EMAIL", \
	"JNR_WM_OUTPUT_ORDERS___BILL_TO_FACILITY_NAME as BILL_TO_FACILITY_NAME", \
	"JNR_WM_OUTPUT_ORDERS___BILL_TO_FAX_NUMBER as BILL_TO_FAX_NUMBER", \
	"JNR_WM_OUTPUT_ORDERS___BILL_TO_NAME as BILL_TO_NAME", \
	"JNR_WM_OUTPUT_ORDERS___BILL_TO_PHONE_NUMBER as BILL_TO_PHONE_NUMBER", \
	"JNR_WM_OUTPUT_ORDERS___BILL_TO_POSTAL_CODE as BILL_TO_POSTAL_CODE", \
	"JNR_WM_OUTPUT_ORDERS___BILL_TO_STATE_PROV as BILL_TO_STATE_PROV", \
	"JNR_WM_OUTPUT_ORDERS___BILL_TO_TITLE as BILL_TO_TITLE", \
	"JNR_WM_OUTPUT_ORDERS___BOL_BREAK_ATTR as BOL_BREAK_ATTR", \
	"JNR_WM_OUTPUT_ORDERS___BOL_TYPE as BOL_TYPE", \
	"JNR_WM_OUTPUT_ORDERS___BUSINESS_PARTNER as BUSINESS_PARTNER", \
	"JNR_WM_OUTPUT_ORDERS___CREATED_DTTM as CREATED_DTTM", \
	"JNR_WM_OUTPUT_ORDERS___CREATED_SOURCE as CREATED_SOURCE", \
	"JNR_WM_OUTPUT_ORDERS___CREATED_SOURCE_TYPE as CREATED_SOURCE_TYPE", \
	"JNR_WM_OUTPUT_ORDERS___CURRENCY as CURRENCY", \
	"JNR_WM_OUTPUT_ORDERS___D_ADDRESS_1 as D_ADDRESS_1", \
	"JNR_WM_OUTPUT_ORDERS___D_ADDRESS_2 as D_ADDRESS_2", \
	"JNR_WM_OUTPUT_ORDERS___D_ADDRESS_3 as D_ADDRESS_3", \
	"JNR_WM_OUTPUT_ORDERS___D_CITY as D_CITY", \
	"JNR_WM_OUTPUT_ORDERS___D_CONTACT as D_CONTACT", \
	"JNR_WM_OUTPUT_ORDERS___D_COUNTRY_CODE as D_COUNTRY_CODE", \
	"JNR_WM_OUTPUT_ORDERS___D_COUNTY as D_COUNTY", \
	"JNR_WM_OUTPUT_ORDERS___D_DOCK_DOOR_ID as D_DOCK_DOOR_ID", \
	"JNR_WM_OUTPUT_ORDERS___D_DOCK_ID as D_DOCK_ID", \
	"JNR_WM_OUTPUT_ORDERS___D_EMAIL as D_EMAIL", \
	"JNR_WM_OUTPUT_ORDERS___D_FACILITY_ALIAS_ID as D_FACILITY_ALIAS_ID", \
	"JNR_WM_OUTPUT_ORDERS___D_FACILITY_ID as D_FACILITY_ID", \
	"JNR_WM_OUTPUT_ORDERS___D_FACILITY_NAME as D_FACILITY_NAME", \
	"JNR_WM_OUTPUT_ORDERS___D_FAX_NUMBER as D_FAX_NUMBER", \
	"JNR_WM_OUTPUT_ORDERS___D_NAME as D_NAME", \
	"JNR_WM_OUTPUT_ORDERS___D_PHONE_NUMBER as D_PHONE_NUMBER", \
	"JNR_WM_OUTPUT_ORDERS___D_POSTAL_CODE as D_POSTAL_CODE", \
	"JNR_WM_OUTPUT_ORDERS___D_STATE_PROV as D_STATE_PROV", \
	"JNR_WM_OUTPUT_ORDERS___DC_CTR_NBR as DC_CTR_NBR", \
	"JNR_WM_OUTPUT_ORDERS___DELIVERY_START_DTTM as DELIVERY_START_DTTM", \
	"JNR_WM_OUTPUT_ORDERS___DISTRIBUTION_SHIP_VIA as DISTRIBUTION_SHIP_VIA", \
	"JNR_WM_OUTPUT_ORDERS___DO_TYPE as DO_TYPE", \
	"JNR_WM_OUTPUT_ORDERS___ORIGINAL_SHIP_VIA as ORIGINAL_SHIP_VIA", \
	"JNR_WM_OUTPUT_ORDERS___EXT_PURCHASE_ORDER as EXT_PURCHASE_ORDER", \
	"JNR_WM_OUTPUT_ORDERS___FREIGHT_CLASS as FREIGHT_CLASS", \
	"JNR_WM_OUTPUT_ORDERS___FREIGHT_FORWARDER_ACCT_NBR as FREIGHT_FORWARDER_ACCT_NBR", \
	"JNR_WM_OUTPUT_ORDERS___GLOBAL_LOCN_NBR as GLOBAL_LOCN_NBR", \
	"JNR_WM_OUTPUT_ORDERS___HANDLING_CHARGES as HANDLING_CHARGES", \
	"JNR_WM_OUTPUT_ORDERS___INCOTERM_FACILITY_ALIAS_ID as INCOTERM_FACILITY_ALIAS_ID", \
	"JNR_WM_OUTPUT_ORDERS___INCOTERM_FACILITY_ID as INCOTERM_FACILITY_ID", \
	"JNR_WM_OUTPUT_ORDERS___INCOTERM_ID as INCOTERM_ID", \
	"JNR_WM_OUTPUT_ORDERS___INCOTERM_LOC_AVA_DTTM as INCOTERM_LOC_AVA_DTTM", \
	"JNR_WM_OUTPUT_ORDERS___INCOTERM_LOC_AVA_TIME_ZONE_ID as INCOTERM_LOC_AVA_TIME_ZONE_ID", \
	"JNR_WM_OUTPUT_ORDERS___INCOTERM_NAME as INCOTERM_NAME", \
	"JNR_WM_OUTPUT_ORDERS___INSUR_CHRG as INSUR_CHRG", \
	"JNR_WM_OUTPUT_ORDERS___INVC_BATCH_NBR as INVC_BATCH_NBR", \
	"JNR_WM_OUTPUT_ORDERS___IS_BACK_ORDERED as IS_BACK_ORDERED", \
	"JNR_WM_OUTPUT_ORDERS___LAST_UPDATED_DTTM as LAST_UPDATED_DTTM", \
	"JNR_WM_OUTPUT_ORDERS___LAST_UPDATED_SOURCE as LAST_UPDATED_SOURCE", \
	"JNR_WM_OUTPUT_ORDERS___LAST_UPDATED_SOURCE_TYPE as LAST_UPDATED_SOURCE_TYPE", \
	"JNR_WM_OUTPUT_ORDERS___MAJOR_MINOR_ORDER as MAJOR_MINOR_ORDER", \
	"JNR_WM_OUTPUT_ORDERS___MAJOR_ORDER_CTRL_NBR as MAJOR_ORDER_CTRL_NBR", \
	"JNR_WM_OUTPUT_ORDERS___MAJOR_ORDER_GRP_ATTR as MAJOR_ORDER_GRP_ATTR", \
	"JNR_WM_OUTPUT_ORDERS___MANIFEST_ID as MANIFEST_ID", \
	"JNR_WM_OUTPUT_ORDERS___MERCHANDIZING_DEPARTMENT as MERCHANDIZING_DEPARTMENT", \
	"JNR_WM_OUTPUT_ORDERS___MISC_CHARGES as MISC_CHARGES", \
	"JNR_WM_OUTPUT_ORDERS___MONETARY_VALUE as MONETARY_VALUE", \
	"JNR_WM_OUTPUT_ORDERS___MOVEMENT_OPTION as MOVEMENT_OPTION", \
	"JNR_WM_OUTPUT_ORDERS___MV_CURRENCY as MV_CURRENCY", \
	"JNR_WM_OUTPUT_ORDERS___NON_MACHINEABLE as NON_MACHINEABLE", \
	"JNR_WM_OUTPUT_ORDERS___O_ADDRESS_1 as O_ADDRESS_1", \
	"JNR_WM_OUTPUT_ORDERS___O_ADDRESS_2 as O_ADDRESS_2", \
	"JNR_WM_OUTPUT_ORDERS___O_ADDRESS_3 as O_ADDRESS_3", \
	"JNR_WM_OUTPUT_ORDERS___O_CITY as O_CITY", \
	"JNR_WM_OUTPUT_ORDERS___O_CONTACT as O_CONTACT", \
	"JNR_WM_OUTPUT_ORDERS___O_COUNTRY_CODE as O_COUNTRY_CODE", \
	"JNR_WM_OUTPUT_ORDERS___O_COUNTY as O_COUNTY", \
	"JNR_WM_OUTPUT_ORDERS___O_DOCK_DOOR_ID as O_DOCK_DOOR_ID", \
	"JNR_WM_OUTPUT_ORDERS___O_DOCK_ID as O_DOCK_ID", \
	"JNR_WM_OUTPUT_ORDERS___O_EMAIL as O_EMAIL", \
	"JNR_WM_OUTPUT_ORDERS___O_FACILITY_ALIAS_ID as O_FACILITY_ALIAS_ID", \
	"JNR_WM_OUTPUT_ORDERS___O_FACILITY_ID as O_FACILITY_ID", \
	"JNR_WM_OUTPUT_ORDERS___O_FACILITY_NAME as O_FACILITY_NAME", \
	"JNR_WM_OUTPUT_ORDERS___O_FAX_NUMBER as O_FAX_NUMBER", \
	"JNR_WM_OUTPUT_ORDERS___O_POSTAL_CODE as O_POSTAL_CODE", \
	"JNR_WM_OUTPUT_ORDERS___O_STATE_PROV as O_STATE_PROV", \
	"JNR_WM_OUTPUT_ORDERS___ORDER_DATE_DTTM as ORDER_DATE_DTTM", \
	"JNR_WM_OUTPUT_ORDERS___ORDER_WEIGHT as ORDER_WEIGHT", \
	"JNR_WM_OUTPUT_ORDERS___ORG_SHIP_FACILITY_ALIAS_ID as ORG_SHIP_FACILITY_ALIAS_ID", \
	"JNR_WM_OUTPUT_ORDERS___ORG_SHIP_FACILITY_ID as ORG_SHIP_FACILITY_ID", \
	"JNR_WM_OUTPUT_ORDERS___ORIGINAL_ASSIGNED_SHIP_VIA as ORIGINAL_ASSIGNED_SHIP_VIA", \
	"JNR_WM_OUTPUT_ORDERS___ORIGIN_SHIP_THRU_FACILITY_ID as ORIGIN_SHIP_THRU_FACILITY_ID", \
	"JNR_WM_OUTPUT_ORDERS___ORIGIN_SHIP_THRU_FAC_ALIAS_ID as ORIGIN_SHIP_THRU_FAC_ALIAS_ID", \
	"JNR_WM_OUTPUT_ORDERS___PICKUP_END_DTTM as PICKUP_END_DTTM", \
	"JNR_WM_OUTPUT_ORDERS___PICKUP_START_DTTM as PICKUP_START_DTTM", \
	"JNR_WM_OUTPUT_ORDERS___PLANNED_SHIP_DATE as PLANNED_SHIP_DATE", \
	"JNR_WM_OUTPUT_ORDERS___PRE_PACK_FLAG as PRE_PACK_FLAG", \
	"JNR_WM_OUTPUT_ORDERS___PRIORITY as PRIORITY", \
	"JNR_WM_OUTPUT_ORDERS___PRO_NUMBER as PRO_NUMBER", \
	"JNR_WM_OUTPUT_ORDERS___PROC_DTTM as PROC_DTTM", \
	"JNR_WM_OUTPUT_ORDERS___PROC_STAT_CODE as PROC_STAT_CODE", \
	"JNR_WM_OUTPUT_ORDERS___REC_XPANS_FIELD as REC_XPANS_FIELD", \
	"JNR_WM_OUTPUT_ORDERS___RTE_ID as RTE_ID", \
	"JNR_WM_OUTPUT_ORDERS___RTE_SHIPMENT_SEQ as RTE_SHIPMENT_SEQ", \
	"JNR_WM_OUTPUT_ORDERS___SCHED_DELIVERY_DTTM as SCHED_DELIVERY_DTTM", \
	"JNR_WM_OUTPUT_ORDERS___SHIPMENT_ID as SHIPMENT_ID", \
	"JNR_WM_OUTPUT_ORDERS___SHIP_DATE as SHIP_DATE", \
	"JNR_WM_OUTPUT_ORDERS___SHIP_GROUP_ID as SHIP_GROUP_ID", \
	"JNR_WM_OUTPUT_ORDERS___SHIP_GROUP_SEQUENCE as SHIP_GROUP_SEQUENCE", \
	"JNR_WM_OUTPUT_ORDERS___SHPNG_CHRG as SHPNG_CHRG", \
	"JNR_WM_OUTPUT_ORDERS___ORDER_STATUS as ORDER_STATUS", \
	"JNR_WM_OUTPUT_ORDERS___DO_STATUS as DO_STATUS", \
	"JNR_WM_OUTPUT_ORDERS___STORE_NBR as STORE_NBR", \
	"JNR_WM_OUTPUT_ORDERS___STORE_TYPE as STORE_TYPE", \
	"JNR_WM_OUTPUT_ORDERS___TAX_CHARGES as TAX_CHARGES", \
	"JNR_WM_OUTPUT_ORDERS___TC_COMPANY_ID as TC_COMPANY_ID", \
	"JNR_WM_OUTPUT_ORDERS___TC_ORDER_ID as TC_ORDER_ID", \
	"JNR_WM_OUTPUT_ORDERS___TC_SHIPMENT_ID as TC_SHIPMENT_ID", \
	"JNR_WM_OUTPUT_ORDERS___TOTAL_NBR_OF_LPN as TOTAL_NBR_OF_LPN", \
	"JNR_WM_OUTPUT_ORDERS___TOTAL_NBR_OF_PLT as TOTAL_NBR_OF_PLT", \
	"JNR_WM_OUTPUT_ORDERS___TOTAL_NBR_OF_UNITS as TOTAL_NBR_OF_UNITS", \
	"JNR_WM_OUTPUT_ORDERS___VERSION_NBR as VERSION_NBR", \
	"JNR_WM_OUTPUT_ORDERS___LINE_HAUL_SHIP_VIA as LINE_HAUL_SHIP_VIA", \
	"JNR_WM_OUTPUT_ORDERS___PLAN_D_FACILITY_ALIAS_ID as PLAN_D_FACILITY_ALIAS_ID", \
	"JNR_WM_OUTPUT_ORDERS___PLAN_D_FACILITY_ID as PLAN_D_FACILITY_ID", \
	"JNR_WM_OUTPUT_ORDERS___PLAN_LEG_D_ALIAS_ID as PLAN_LEG_D_ALIAS_ID", \
	"JNR_WM_OUTPUT_ORDERS___PLAN_LEG_D_ID as PLAN_LEG_D_ID", \
	"JNR_WM_OUTPUT_ORDERS___PLAN_LEG_O_ALIAS_ID as PLAN_LEG_O_ALIAS_ID", \
	"JNR_WM_OUTPUT_ORDERS___PLAN_LEG_O_ID as PLAN_LEG_O_ID", \
	"JNR_WM_OUTPUT_ORDERS___PLAN_O_FACILITY_ALIAS_ID as PLAN_O_FACILITY_ALIAS_ID", \
	"JNR_WM_OUTPUT_ORDERS___PLAN_O_FACILITY_ID as PLAN_O_FACILITY_ID", \
	"JNR_WM_OUTPUT_ORDERS___SPL_INSTR_CODE_1 as SPL_INSTR_CODE_1", \
	"JNR_WM_OUTPUT_ORDERS___SPL_INSTR_CODE_10 as SPL_INSTR_CODE_10", \
	"JNR_WM_OUTPUT_ORDERS___SPL_INSTR_CODE_2 as SPL_INSTR_CODE_2", \
	"JNR_WM_OUTPUT_ORDERS___SPL_INSTR_CODE_3 as SPL_INSTR_CODE_3", \
	"JNR_WM_OUTPUT_ORDERS___SPL_INSTR_CODE_4 as SPL_INSTR_CODE_4", \
	"JNR_WM_OUTPUT_ORDERS___SPL_INSTR_CODE_5 as SPL_INSTR_CODE_5", \
	"JNR_WM_OUTPUT_ORDERS___SPL_INSTR_CODE_6 as SPL_INSTR_CODE_6", \
	"JNR_WM_OUTPUT_ORDERS___SPL_INSTR_CODE_7 as SPL_INSTR_CODE_7", \
	"JNR_WM_OUTPUT_ORDERS___SPL_INSTR_CODE_8 as SPL_INSTR_CODE_8", \
	"JNR_WM_OUTPUT_ORDERS___SPL_INSTR_CODE_9 as SPL_INSTR_CODE_9", \
	"JNR_WM_OUTPUT_ORDERS___PRE_BILL_STATUS as PRE_BILL_STATUS", \
	"JNR_WM_OUTPUT_ORDERS___PRTL_SHIP_CONF_FLAG as PRTL_SHIP_CONF_FLAG", \
	"JNR_WM_OUTPUT_ORDERS___PRTL_SHIP_CONF_STATUS as PRTL_SHIP_CONF_STATUS", \
	"JNR_WM_OUTPUT_ORDERS___PRE_BILLED_FLAG as PRE_BILLED_FLAG", \
	"JNR_WM_OUTPUT_ORDERS___TAX_ID as TAX_ID", \
	"JNR_WM_OUTPUT_ORDERS___ALLOW_PRE_BILLING as ALLOW_PRE_BILLING", \
	"JNR_WM_OUTPUT_ORDERS___O_PHONE_NUMBER as O_PHONE_NUMBER", \
	"JNR_WM_OUTPUT_ORDERS___PURCHASE_ORDER_NBR as PURCHASE_ORDER_NBR", \
	"JNR_WM_OUTPUT_ORDERS___MARK_FOR as MARK_FOR", \
	"JNR_WM_OUTPUT_ORDERS___DISTRO_NUMBER as DISTRO_NUMBER", \
	"JNR_WM_OUTPUT_ORDERS___REF_SHIPMENT_NBR as REF_SHIPMENT_NBR", \
	"JNR_WM_OUTPUT_ORDERS___REF_STOP_SEQ as REF_STOP_SEQ", \
	"JNR_WM_OUTPUT_ORDERS___PO_TYPE_ATTR as PO_TYPE_ATTR", \
	"JNR_WM_OUTPUT_ORDERS___DSG_SHIP_VIA as DSG_SHIP_VIA", \
	"JNR_WM_OUTPUT_ORDERS___in_LOCATION_ID as in_LOCATION_ID", \
	"JNR_WM_OUTPUT_ORDERS___in_WM_OUTPT_ORDERS_ID as in_WM_OUTPT_ORDERS_ID", \
	"JNR_WM_OUTPUT_ORDERS___in_WM_CREATED_TSTMP as in_WM_CREATED_TSTMP", \
	"JNR_WM_OUTPUT_ORDERS___in_WM_LAST_UPDATED_TSTMP as in_WM_LAST_UPDATED_TSTMP", \
	"JNR_WM_OUTPUT_ORDERS___in_LOAD_TSTMP as in_LOAD_TSTMP") \
    .filter("in_WM_OUTPT_ORDERS_ID is Null OR (  in_WM_OUTPT_ORDERS_ID is NOT Null AND ( COALESCE(CREATED_DTTM, date'1900-01-01') != COALESCE(in_WM_CREATED_TSTMP, date'1900-01-01') \
             OR COALESCE(LAST_UPDATED_DTTM, date'1900-01-01') != COALESCE(in_WM_LAST_UPDATED_TSTMP, date'1900-01-01')))").withColumn("sys_row_id", monotonically_increasing_id())


# COMMAND ----------
# Processing node EXP_EVALUATE, type EXPRESSION 
# COLUMN COUNT: 176

# for each involved DataFrame, append the dataframe name to each column
FIL_UNCHANGED_REC_temp = FIL_UNCHANGED_REC.toDF(*["FIL_UNCHANGED_REC___" + col for col in FIL_UNCHANGED_REC.columns])

EXP_EVALUATE = FIL_UNCHANGED_REC_temp.selectExpr( \
	"FIL_UNCHANGED_REC___sys_row_id as sys_row_id", \
	"FIL_UNCHANGED_REC___LOCATION_ID as LOCATION_ID", \
	"FIL_UNCHANGED_REC___OUTPT_ORDERS_ID as OUTPT_ORDERS_ID", \
	"FIL_UNCHANGED_REC___ACCT_RCVBL_ACCT_NBR as ACCT_RCVBL_ACCT_NBR", \
	"FIL_UNCHANGED_REC___ACCT_RCVBL_CODE as ACCT_RCVBL_CODE", \
	"FIL_UNCHANGED_REC___ADDR_CODE as ADDR_CODE", \
	"FIL_UNCHANGED_REC___BACKORDERED_QUANTITY as BACKORDERED_QUANTITY", \
	"FIL_UNCHANGED_REC___BATCH_CTRL_NBR as BATCH_CTRL_NBR", \
	"FIL_UNCHANGED_REC___BILLING_METHOD as BILLING_METHOD", \
	"FIL_UNCHANGED_REC___BILL_ACCT_NBR as BILL_ACCT_NBR", \
	"FIL_UNCHANGED_REC___BILL_FACILITY_ALIAS_ID as BILL_FACILITY_ALIAS_ID", \
	"FIL_UNCHANGED_REC___BILL_FACILITY_ID as BILL_FACILITY_ID", \
	"FIL_UNCHANGED_REC___BILL_OF_LADING_NUMBER as BILL_OF_LADING_NUMBER", \
	"FIL_UNCHANGED_REC___BILL_TO_ADDRESS_1 as BILL_TO_ADDRESS_1", \
	"FIL_UNCHANGED_REC___BILL_TO_ADDRESS_2 as BILL_TO_ADDRESS_2", \
	"FIL_UNCHANGED_REC___BILL_TO_ADDRESS_3 as BILL_TO_ADDRESS_3", \
	"FIL_UNCHANGED_REC___BILL_TO_CITY as BILL_TO_CITY", \
	"FIL_UNCHANGED_REC___BILL_TO_CONTACT as BILL_TO_CONTACT", \
	"FIL_UNCHANGED_REC___BILL_TO_CONTACT_NAME as BILL_TO_CONTACT_NAME", \
	"FIL_UNCHANGED_REC___BILL_TO_COUNTRY_CODE as BILL_TO_COUNTRY_CODE", \
	"FIL_UNCHANGED_REC___BILL_TO_COUNTY as BILL_TO_COUNTY", \
	"FIL_UNCHANGED_REC___BILL_TO_EMAIL as BILL_TO_EMAIL", \
	"FIL_UNCHANGED_REC___BILL_TO_FACILITY_NAME as BILL_TO_FACILITY_NAME", \
	"FIL_UNCHANGED_REC___BILL_TO_FAX_NUMBER as BILL_TO_FAX_NUMBER", \
	"FIL_UNCHANGED_REC___BILL_TO_NAME as BILL_TO_NAME", \
	"FIL_UNCHANGED_REC___BILL_TO_PHONE_NUMBER as BILL_TO_PHONE_NUMBER", \
	"FIL_UNCHANGED_REC___BILL_TO_POSTAL_CODE as BILL_TO_POSTAL_CODE", \
	"FIL_UNCHANGED_REC___BILL_TO_STATE_PROV as BILL_TO_STATE_PROV", \
	"FIL_UNCHANGED_REC___BILL_TO_TITLE as BILL_TO_TITLE", \
	"FIL_UNCHANGED_REC___BOL_BREAK_ATTR as BOL_BREAK_ATTR", \
	"FIL_UNCHANGED_REC___BOL_TYPE as BOL_TYPE", \
	"FIL_UNCHANGED_REC___BUSINESS_PARTNER as BUSINESS_PARTNER", \
	"FIL_UNCHANGED_REC___CREATED_DTTM as CREATED_DTTM", \
	"FIL_UNCHANGED_REC___CREATED_SOURCE as CREATED_SOURCE", \
	"FIL_UNCHANGED_REC___CREATED_SOURCE_TYPE as CREATED_SOURCE_TYPE", \
	"FIL_UNCHANGED_REC___CURRENCY as CURRENCY", \
	"FIL_UNCHANGED_REC___D_ADDRESS_1 as D_ADDRESS_1", \
	"FIL_UNCHANGED_REC___D_ADDRESS_2 as D_ADDRESS_2", \
	"FIL_UNCHANGED_REC___D_ADDRESS_3 as D_ADDRESS_3", \
	"FIL_UNCHANGED_REC___D_CITY as D_CITY", \
	"FIL_UNCHANGED_REC___D_CONTACT as D_CONTACT", \
	"FIL_UNCHANGED_REC___D_COUNTRY_CODE as D_COUNTRY_CODE", \
	"FIL_UNCHANGED_REC___D_COUNTY as D_COUNTY", \
	"FIL_UNCHANGED_REC___D_DOCK_DOOR_ID as D_DOCK_DOOR_ID", \
	"FIL_UNCHANGED_REC___D_DOCK_ID as D_DOCK_ID", \
	"FIL_UNCHANGED_REC___D_EMAIL as D_EMAIL", \
	"FIL_UNCHANGED_REC___D_FACILITY_ALIAS_ID as D_FACILITY_ALIAS_ID", \
	"FIL_UNCHANGED_REC___D_FACILITY_ID as D_FACILITY_ID", \
	"FIL_UNCHANGED_REC___D_FACILITY_NAME as D_FACILITY_NAME", \
	"FIL_UNCHANGED_REC___D_FAX_NUMBER as D_FAX_NUMBER", \
	"FIL_UNCHANGED_REC___D_NAME as D_NAME", \
	"FIL_UNCHANGED_REC___D_PHONE_NUMBER as D_PHONE_NUMBER", \
	"FIL_UNCHANGED_REC___D_POSTAL_CODE as D_POSTAL_CODE", \
	"FIL_UNCHANGED_REC___D_STATE_PROV as D_STATE_PROV", \
	"FIL_UNCHANGED_REC___DC_CTR_NBR as DC_CTR_NBR", \
	"FIL_UNCHANGED_REC___DELIVERY_START_DTTM as DELIVERY_START_DTTM", \
	"FIL_UNCHANGED_REC___DISTRIBUTION_SHIP_VIA as DISTRIBUTION_SHIP_VIA", \
	"FIL_UNCHANGED_REC___DO_TYPE as DO_TYPE", \
	"FIL_UNCHANGED_REC___ORIGINAL_SHIP_VIA as ORIGINAL_SHIP_VIA", \
	"FIL_UNCHANGED_REC___EXT_PURCHASE_ORDER as EXT_PURCHASE_ORDER", \
	"FIL_UNCHANGED_REC___FREIGHT_CLASS as FREIGHT_CLASS", \
	"FIL_UNCHANGED_REC___FREIGHT_FORWARDER_ACCT_NBR as FREIGHT_FORWARDER_ACCT_NBR", \
	"FIL_UNCHANGED_REC___GLOBAL_LOCN_NBR as GLOBAL_LOCN_NBR", \
	"FIL_UNCHANGED_REC___HANDLING_CHARGES as HANDLING_CHARGES", \
	"FIL_UNCHANGED_REC___INCOTERM_FACILITY_ALIAS_ID as INCOTERM_FACILITY_ALIAS_ID", \
	"FIL_UNCHANGED_REC___INCOTERM_FACILITY_ID as INCOTERM_FACILITY_ID", \
	"FIL_UNCHANGED_REC___INCOTERM_ID as INCOTERM_ID", \
	"FIL_UNCHANGED_REC___INCOTERM_LOC_AVA_DTTM as INCOTERM_LOC_AVA_DTTM", \
	"FIL_UNCHANGED_REC___INCOTERM_LOC_AVA_TIME_ZONE_ID as INCOTERM_LOC_AVA_TIME_ZONE_ID", \
	"FIL_UNCHANGED_REC___INCOTERM_NAME as INCOTERM_NAME", \
	"FIL_UNCHANGED_REC___INSUR_CHRG as INSUR_CHRG", \
	"FIL_UNCHANGED_REC___INVC_BATCH_NBR as INVC_BATCH_NBR", \
	"FIL_UNCHANGED_REC___IS_BACK_ORDERED as IS_BACK_ORDERED", \
	"FIL_UNCHANGED_REC___LAST_UPDATED_DTTM as LAST_UPDATED_DTTM", \
	"FIL_UNCHANGED_REC___LAST_UPDATED_SOURCE as LAST_UPDATED_SOURCE", \
	"FIL_UNCHANGED_REC___LAST_UPDATED_SOURCE_TYPE as LAST_UPDATED_SOURCE_TYPE", \
	"FIL_UNCHANGED_REC___MAJOR_MINOR_ORDER as MAJOR_MINOR_ORDER", \
	"FIL_UNCHANGED_REC___MAJOR_ORDER_CTRL_NBR as MAJOR_ORDER_CTRL_NBR", \
	"FIL_UNCHANGED_REC___MAJOR_ORDER_GRP_ATTR as MAJOR_ORDER_GRP_ATTR", \
	"FIL_UNCHANGED_REC___MANIFEST_ID as MANIFEST_ID", \
	"FIL_UNCHANGED_REC___MERCHANDIZING_DEPARTMENT as MERCHANDIZING_DEPARTMENT", \
	"FIL_UNCHANGED_REC___MISC_CHARGES as MISC_CHARGES", \
	"FIL_UNCHANGED_REC___MONETARY_VALUE as MONETARY_VALUE", \
	"FIL_UNCHANGED_REC___MOVEMENT_OPTION as MOVEMENT_OPTION", \
	"FIL_UNCHANGED_REC___MV_CURRENCY as MV_CURRENCY", \
	"FIL_UNCHANGED_REC___NON_MACHINEABLE as NON_MACHINEABLE", \
	"FIL_UNCHANGED_REC___O_ADDRESS_1 as O_ADDRESS_1", \
	"FIL_UNCHANGED_REC___O_ADDRESS_2 as O_ADDRESS_2", \
	"FIL_UNCHANGED_REC___O_ADDRESS_3 as O_ADDRESS_3", \
	"FIL_UNCHANGED_REC___O_CITY as O_CITY", \
	"FIL_UNCHANGED_REC___O_CONTACT as O_CONTACT", \
	"FIL_UNCHANGED_REC___O_COUNTRY_CODE as O_COUNTRY_CODE", \
	"FIL_UNCHANGED_REC___O_COUNTY as O_COUNTY", \
	"FIL_UNCHANGED_REC___O_DOCK_DOOR_ID as O_DOCK_DOOR_ID", \
	"FIL_UNCHANGED_REC___O_DOCK_ID as O_DOCK_ID", \
	"FIL_UNCHANGED_REC___O_EMAIL as O_EMAIL", \
	"FIL_UNCHANGED_REC___O_FACILITY_ALIAS_ID as O_FACILITY_ALIAS_ID", \
	"FIL_UNCHANGED_REC___O_FACILITY_ID as O_FACILITY_ID", \
	"FIL_UNCHANGED_REC___O_FACILITY_NAME as O_FACILITY_NAME", \
	"FIL_UNCHANGED_REC___O_FAX_NUMBER as O_FAX_NUMBER", \
	"FIL_UNCHANGED_REC___O_POSTAL_CODE as O_POSTAL_CODE", \
	"FIL_UNCHANGED_REC___O_STATE_PROV as O_STATE_PROV", \
	"FIL_UNCHANGED_REC___ORDER_DATE_DTTM as ORDER_DATE_DTTM", \
	"FIL_UNCHANGED_REC___ORDER_WEIGHT as ORDER_WEIGHT", \
	"FIL_UNCHANGED_REC___ORG_SHIP_FACILITY_ALIAS_ID as ORG_SHIP_FACILITY_ALIAS_ID", \
	"FIL_UNCHANGED_REC___ORG_SHIP_FACILITY_ID as ORG_SHIP_FACILITY_ID", \
	"FIL_UNCHANGED_REC___ORIGINAL_ASSIGNED_SHIP_VIA as ORIGINAL_ASSIGNED_SHIP_VIA", \
	"FIL_UNCHANGED_REC___ORIGIN_SHIP_THRU_FACILITY_ID as ORIGIN_SHIP_THRU_FACILITY_ID", \
	"FIL_UNCHANGED_REC___ORIGIN_SHIP_THRU_FAC_ALIAS_ID as ORIGIN_SHIP_THRU_FAC_ALIAS_ID", \
	"FIL_UNCHANGED_REC___PICKUP_END_DTTM as PICKUP_END_DTTM", \
	"FIL_UNCHANGED_REC___PICKUP_START_DTTM as PICKUP_START_DTTM", \
	"FIL_UNCHANGED_REC___PLANNED_SHIP_DATE as PLANNED_SHIP_DATE", \
	"FIL_UNCHANGED_REC___PRE_PACK_FLAG as PRE_PACK_FLAG", \
	"FIL_UNCHANGED_REC___PRIORITY as PRIORITY", \
	"FIL_UNCHANGED_REC___PRO_NUMBER as PRO_NUMBER", \
	"FIL_UNCHANGED_REC___PROC_DTTM as PROC_DTTM", \
	"FIL_UNCHANGED_REC___PROC_STAT_CODE as PROC_STAT_CODE", \
	"FIL_UNCHANGED_REC___REC_XPANS_FIELD as REC_XPANS_FIELD", \
	"FIL_UNCHANGED_REC___RTE_ID as RTE_ID", \
	"FIL_UNCHANGED_REC___RTE_SHIPMENT_SEQ as RTE_SHIPMENT_SEQ", \
	"FIL_UNCHANGED_REC___SCHED_DELIVERY_DTTM as SCHED_DELIVERY_DTTM", \
	"FIL_UNCHANGED_REC___SHIPMENT_ID as SHIPMENT_ID", \
	"FIL_UNCHANGED_REC___SHIP_DATE as SHIP_DATE", \
	"FIL_UNCHANGED_REC___SHIP_GROUP_ID as SHIP_GROUP_ID", \
	"FIL_UNCHANGED_REC___SHIP_GROUP_SEQUENCE as SHIP_GROUP_SEQUENCE", \
	"FIL_UNCHANGED_REC___SHPNG_CHRG as SHPNG_CHRG", \
	"FIL_UNCHANGED_REC___ORDER_STATUS as ORDER_STATUS", \
	"FIL_UNCHANGED_REC___DO_STATUS as DO_STATUS", \
	"FIL_UNCHANGED_REC___STORE_NBR as STORE_NBR", \
	"FIL_UNCHANGED_REC___STORE_TYPE as STORE_TYPE", \
	"FIL_UNCHANGED_REC___TAX_CHARGES as TAX_CHARGES", \
	"FIL_UNCHANGED_REC___TC_COMPANY_ID as TC_COMPANY_ID", \
	"FIL_UNCHANGED_REC___TC_ORDER_ID as TC_ORDER_ID", \
	"FIL_UNCHANGED_REC___TC_SHIPMENT_ID as TC_SHIPMENT_ID", \
	"FIL_UNCHANGED_REC___TOTAL_NBR_OF_LPN as TOTAL_NBR_OF_LPN", \
	"FIL_UNCHANGED_REC___TOTAL_NBR_OF_PLT as TOTAL_NBR_OF_PLT", \
	"FIL_UNCHANGED_REC___TOTAL_NBR_OF_UNITS as TOTAL_NBR_OF_UNITS", \
	"FIL_UNCHANGED_REC___VERSION_NBR as VERSION_NBR", \
	"FIL_UNCHANGED_REC___LINE_HAUL_SHIP_VIA as LINE_HAUL_SHIP_VIA", \
	"FIL_UNCHANGED_REC___PLAN_D_FACILITY_ALIAS_ID as PLAN_D_FACILITY_ALIAS_ID", \
	"FIL_UNCHANGED_REC___PLAN_D_FACILITY_ID as PLAN_D_FACILITY_ID", \
	"FIL_UNCHANGED_REC___PLAN_LEG_D_ALIAS_ID as PLAN_LEG_D_ALIAS_ID", \
	"FIL_UNCHANGED_REC___PLAN_LEG_D_ID as PLAN_LEG_D_ID", \
	"FIL_UNCHANGED_REC___PLAN_LEG_O_ALIAS_ID as PLAN_LEG_O_ALIAS_ID", \
	"FIL_UNCHANGED_REC___PLAN_LEG_O_ID as PLAN_LEG_O_ID", \
	"FIL_UNCHANGED_REC___PLAN_O_FACILITY_ALIAS_ID as PLAN_O_FACILITY_ALIAS_ID", \
	"FIL_UNCHANGED_REC___PLAN_O_FACILITY_ID as PLAN_O_FACILITY_ID", \
	"FIL_UNCHANGED_REC___SPL_INSTR_CODE_1 as SPL_INSTR_CODE_1", \
	"FIL_UNCHANGED_REC___SPL_INSTR_CODE_10 as SPL_INSTR_CODE_10", \
	"FIL_UNCHANGED_REC___SPL_INSTR_CODE_2 as SPL_INSTR_CODE_2", \
	"FIL_UNCHANGED_REC___SPL_INSTR_CODE_3 as SPL_INSTR_CODE_3", \
	"FIL_UNCHANGED_REC___SPL_INSTR_CODE_4 as SPL_INSTR_CODE_4", \
	"FIL_UNCHANGED_REC___SPL_INSTR_CODE_5 as SPL_INSTR_CODE_5", \
	"FIL_UNCHANGED_REC___SPL_INSTR_CODE_6 as SPL_INSTR_CODE_6", \
	"FIL_UNCHANGED_REC___SPL_INSTR_CODE_7 as SPL_INSTR_CODE_7", \
	"FIL_UNCHANGED_REC___SPL_INSTR_CODE_8 as SPL_INSTR_CODE_8", \
	"FIL_UNCHANGED_REC___SPL_INSTR_CODE_9 as SPL_INSTR_CODE_9", \
	"FIL_UNCHANGED_REC___PRE_BILL_STATUS as PRE_BILL_STATUS", \
	"FIL_UNCHANGED_REC___PRTL_SHIP_CONF_FLAG as PRTL_SHIP_CONF_FLAG", \
	"FIL_UNCHANGED_REC___PRTL_SHIP_CONF_STATUS as PRTL_SHIP_CONF_STATUS", \
	"FIL_UNCHANGED_REC___PRE_BILLED_FLAG as PRE_BILLED_FLAG", \
	"FIL_UNCHANGED_REC___TAX_ID as TAX_ID", \
	"FIL_UNCHANGED_REC___ALLOW_PRE_BILLING as ALLOW_PRE_BILLING", \
	"FIL_UNCHANGED_REC___O_PHONE_NUMBER as O_PHONE_NUMBER", \
	"FIL_UNCHANGED_REC___PURCHASE_ORDER_NBR as PURCHASE_ORDER_NBR", \
	"FIL_UNCHANGED_REC___MARK_FOR as MARK_FOR", \
	"FIL_UNCHANGED_REC___DISTRO_NUMBER as DISTRO_NUMBER", \
	"FIL_UNCHANGED_REC___REF_SHIPMENT_NBR as REF_SHIPMENT_NBR", \
	"FIL_UNCHANGED_REC___REF_STOP_SEQ as REF_STOP_SEQ", \
	"FIL_UNCHANGED_REC___PO_TYPE_ATTR as PO_TYPE_ATTR", \
	"FIL_UNCHANGED_REC___DSG_SHIP_VIA as DSG_SHIP_VIA", \
	"FIL_UNCHANGED_REC___in_LOCATION_ID as in_LOCATION_ID", \
	"FIL_UNCHANGED_REC___in_WM_OUTPT_ORDERS_ID as in_WM_OUTPT_ORDERS_ID", \
	"FIL_UNCHANGED_REC___in_WM_CREATED_TSTMP as in_WM_CREATED_TSTMP", \
	"FIL_UNCHANGED_REC___in_WM_LAST_UPDATED_TSTMP as in_WM_LAST_UPDATED_TSTMP", \
	"IF(FIL_UNCHANGED_REC___in_LOAD_TSTMP IS NULL, CURRENT_TIMESTAMP, FIL_UNCHANGED_REC___in_LOAD_TSTMP) as LOAD_TSTMP", \
	"CURRENT_TIMESTAMP as UPDATE_TSTMP" \
)

# COMMAND ----------
# Processing node UPD_INS_UPD, type UPDATE_STRATEGY 
# COLUMN COUNT: 173

# for each involved DataFrame, append the dataframe name to each column
EXP_EVALUATE_temp = EXP_EVALUATE.toDF(*["EXP_EVALUATE___" + col for col in EXP_EVALUATE.columns])

UPD_INS_UPD = EXP_EVALUATE_temp.selectExpr( \
	"EXP_EVALUATE___LOCATION_ID as LOCATION_ID", \
	"EXP_EVALUATE___OUTPT_ORDERS_ID as OUTPT_ORDERS_ID", \
	"EXP_EVALUATE___ACCT_RCVBL_ACCT_NBR as ACCT_RCVBL_ACCT_NBR", \
	"EXP_EVALUATE___ACCT_RCVBL_CODE as ACCT_RCVBL_CODE", \
	"EXP_EVALUATE___ADDR_CODE as ADDR_CODE", \
	"EXP_EVALUATE___BACKORDERED_QUANTITY as BACKORDERED_QUANTITY", \
	"EXP_EVALUATE___BATCH_CTRL_NBR as BATCH_CTRL_NBR", \
	"EXP_EVALUATE___BILLING_METHOD as BILLING_METHOD", \
	"EXP_EVALUATE___BILL_ACCT_NBR as BILL_ACCT_NBR", \
	"EXP_EVALUATE___BILL_FACILITY_ALIAS_ID as BILL_FACILITY_ALIAS_ID", \
	"EXP_EVALUATE___BILL_FACILITY_ID as BILL_FACILITY_ID", \
	"EXP_EVALUATE___BILL_OF_LADING_NUMBER as BILL_OF_LADING_NUMBER", \
	"EXP_EVALUATE___BILL_TO_ADDRESS_1 as BILL_TO_ADDRESS_1", \
	"EXP_EVALUATE___BILL_TO_ADDRESS_2 as BILL_TO_ADDRESS_2", \
	"EXP_EVALUATE___BILL_TO_ADDRESS_3 as BILL_TO_ADDRESS_3", \
	"EXP_EVALUATE___BILL_TO_CITY as BILL_TO_CITY", \
	"EXP_EVALUATE___BILL_TO_CONTACT as BILL_TO_CONTACT", \
	"EXP_EVALUATE___BILL_TO_CONTACT_NAME as BILL_TO_CONTACT_NAME", \
	"EXP_EVALUATE___BILL_TO_COUNTRY_CODE as BILL_TO_COUNTRY_CODE", \
	"EXP_EVALUATE___BILL_TO_COUNTY as BILL_TO_COUNTY", \
	"EXP_EVALUATE___BILL_TO_EMAIL as BILL_TO_EMAIL", \
	"EXP_EVALUATE___BILL_TO_FACILITY_NAME as BILL_TO_FACILITY_NAME", \
	"EXP_EVALUATE___BILL_TO_FAX_NUMBER as BILL_TO_FAX_NUMBER", \
	"EXP_EVALUATE___BILL_TO_NAME as BILL_TO_NAME", \
	"EXP_EVALUATE___BILL_TO_PHONE_NUMBER as BILL_TO_PHONE_NUMBER", \
	"EXP_EVALUATE___BILL_TO_POSTAL_CODE as BILL_TO_POSTAL_CODE", \
	"EXP_EVALUATE___BILL_TO_STATE_PROV as BILL_TO_STATE_PROV", \
	"EXP_EVALUATE___BILL_TO_TITLE as BILL_TO_TITLE", \
	"EXP_EVALUATE___BOL_BREAK_ATTR as BOL_BREAK_ATTR", \
	"EXP_EVALUATE___BOL_TYPE as BOL_TYPE", \
	"EXP_EVALUATE___BUSINESS_PARTNER as BUSINESS_PARTNER", \
	"EXP_EVALUATE___CREATED_DTTM as CREATED_DTTM", \
	"EXP_EVALUATE___CREATED_SOURCE as CREATED_SOURCE", \
	"EXP_EVALUATE___CREATED_SOURCE_TYPE as CREATED_SOURCE_TYPE", \
	"EXP_EVALUATE___CURRENCY as CURRENCY", \
	"EXP_EVALUATE___D_ADDRESS_1 as D_ADDRESS_1", \
	"EXP_EVALUATE___D_ADDRESS_2 as D_ADDRESS_2", \
	"EXP_EVALUATE___D_ADDRESS_3 as D_ADDRESS_3", \
	"EXP_EVALUATE___D_CITY as D_CITY", \
	"EXP_EVALUATE___D_CONTACT as D_CONTACT", \
	"EXP_EVALUATE___D_COUNTRY_CODE as D_COUNTRY_CODE", \
	"EXP_EVALUATE___D_COUNTY as D_COUNTY", \
	"EXP_EVALUATE___D_DOCK_DOOR_ID as D_DOCK_DOOR_ID", \
	"EXP_EVALUATE___D_DOCK_ID as D_DOCK_ID", \
	"EXP_EVALUATE___D_EMAIL as D_EMAIL", \
	"EXP_EVALUATE___D_FACILITY_ALIAS_ID as D_FACILITY_ALIAS_ID", \
	"EXP_EVALUATE___D_FACILITY_ID as D_FACILITY_ID", \
	"EXP_EVALUATE___D_FACILITY_NAME as D_FACILITY_NAME", \
	"EXP_EVALUATE___D_FAX_NUMBER as D_FAX_NUMBER", \
	"EXP_EVALUATE___D_NAME as D_NAME", \
	"EXP_EVALUATE___D_PHONE_NUMBER as D_PHONE_NUMBER", \
	"EXP_EVALUATE___D_POSTAL_CODE as D_POSTAL_CODE", \
	"EXP_EVALUATE___D_STATE_PROV as D_STATE_PROV", \
	"EXP_EVALUATE___DC_CTR_NBR as DC_CTR_NBR", \
	"EXP_EVALUATE___DELIVERY_START_DTTM as DELIVERY_START_DTTM", \
	"EXP_EVALUATE___DISTRIBUTION_SHIP_VIA as DISTRIBUTION_SHIP_VIA", \
	"EXP_EVALUATE___DO_TYPE as DO_TYPE", \
	"EXP_EVALUATE___ORIGINAL_SHIP_VIA as ORIGINAL_SHIP_VIA", \
	"EXP_EVALUATE___EXT_PURCHASE_ORDER as EXT_PURCHASE_ORDER", \
	"EXP_EVALUATE___FREIGHT_CLASS as FREIGHT_CLASS", \
	"EXP_EVALUATE___FREIGHT_FORWARDER_ACCT_NBR as FREIGHT_FORWARDER_ACCT_NBR", \
	"EXP_EVALUATE___GLOBAL_LOCN_NBR as GLOBAL_LOCN_NBR", \
	"EXP_EVALUATE___HANDLING_CHARGES as HANDLING_CHARGES", \
	"EXP_EVALUATE___INCOTERM_FACILITY_ALIAS_ID as INCOTERM_FACILITY_ALIAS_ID", \
	"EXP_EVALUATE___INCOTERM_FACILITY_ID as INCOTERM_FACILITY_ID", \
	"EXP_EVALUATE___INCOTERM_ID as INCOTERM_ID", \
	"EXP_EVALUATE___INCOTERM_LOC_AVA_DTTM as INCOTERM_LOC_AVA_DTTM", \
	"EXP_EVALUATE___INCOTERM_LOC_AVA_TIME_ZONE_ID as INCOTERM_LOC_AVA_TIME_ZONE_ID", \
	"EXP_EVALUATE___INCOTERM_NAME as INCOTERM_NAME", \
	"EXP_EVALUATE___INSUR_CHRG as INSUR_CHRG", \
	"EXP_EVALUATE___INVC_BATCH_NBR as INVC_BATCH_NBR", \
	"EXP_EVALUATE___IS_BACK_ORDERED as IS_BACK_ORDERED", \
	"EXP_EVALUATE___LAST_UPDATED_DTTM as LAST_UPDATED_DTTM", \
	"EXP_EVALUATE___LAST_UPDATED_SOURCE as LAST_UPDATED_SOURCE", \
	"EXP_EVALUATE___LAST_UPDATED_SOURCE_TYPE as LAST_UPDATED_SOURCE_TYPE", \
	"EXP_EVALUATE___MAJOR_MINOR_ORDER as MAJOR_MINOR_ORDER", \
	"EXP_EVALUATE___MAJOR_ORDER_CTRL_NBR as MAJOR_ORDER_CTRL_NBR", \
	"EXP_EVALUATE___MAJOR_ORDER_GRP_ATTR as MAJOR_ORDER_GRP_ATTR", \
	"EXP_EVALUATE___MANIFEST_ID as MANIFEST_ID", \
	"EXP_EVALUATE___MERCHANDIZING_DEPARTMENT as MERCHANDIZING_DEPARTMENT", \
	"EXP_EVALUATE___MISC_CHARGES as MISC_CHARGES", \
	"EXP_EVALUATE___MONETARY_VALUE as MONETARY_VALUE", \
	"EXP_EVALUATE___MOVEMENT_OPTION as MOVEMENT_OPTION", \
	"EXP_EVALUATE___MV_CURRENCY as MV_CURRENCY", \
	"EXP_EVALUATE___NON_MACHINEABLE as NON_MACHINEABLE", \
	"EXP_EVALUATE___O_ADDRESS_1 as O_ADDRESS_1", \
	"EXP_EVALUATE___O_ADDRESS_2 as O_ADDRESS_2", \
	"EXP_EVALUATE___O_ADDRESS_3 as O_ADDRESS_3", \
	"EXP_EVALUATE___O_CITY as O_CITY", \
	"EXP_EVALUATE___O_CONTACT as O_CONTACT", \
	"EXP_EVALUATE___O_COUNTRY_CODE as O_COUNTRY_CODE", \
	"EXP_EVALUATE___O_COUNTY as O_COUNTY", \
	"EXP_EVALUATE___O_DOCK_DOOR_ID as O_DOCK_DOOR_ID", \
	"EXP_EVALUATE___O_DOCK_ID as O_DOCK_ID", \
	"EXP_EVALUATE___O_EMAIL as O_EMAIL", \
	"EXP_EVALUATE___O_FACILITY_ALIAS_ID as O_FACILITY_ALIAS_ID", \
	"EXP_EVALUATE___O_FACILITY_ID as O_FACILITY_ID", \
	"EXP_EVALUATE___O_FACILITY_NAME as O_FACILITY_NAME", \
	"EXP_EVALUATE___O_FAX_NUMBER as O_FAX_NUMBER", \
	"EXP_EVALUATE___O_POSTAL_CODE as O_POSTAL_CODE", \
	"EXP_EVALUATE___O_STATE_PROV as O_STATE_PROV", \
	"EXP_EVALUATE___ORDER_DATE_DTTM as ORDER_DATE_DTTM", \
	"EXP_EVALUATE___ORDER_WEIGHT as ORDER_WEIGHT", \
	"EXP_EVALUATE___ORG_SHIP_FACILITY_ALIAS_ID as ORG_SHIP_FACILITY_ALIAS_ID", \
	"EXP_EVALUATE___ORG_SHIP_FACILITY_ID as ORG_SHIP_FACILITY_ID", \
	"EXP_EVALUATE___ORIGINAL_ASSIGNED_SHIP_VIA as ORIGINAL_ASSIGNED_SHIP_VIA", \
	"EXP_EVALUATE___ORIGIN_SHIP_THRU_FACILITY_ID as ORIGIN_SHIP_THRU_FACILITY_ID", \
	"EXP_EVALUATE___ORIGIN_SHIP_THRU_FAC_ALIAS_ID as ORIGIN_SHIP_THRU_FAC_ALIAS_ID", \
	"EXP_EVALUATE___PICKUP_END_DTTM as PICKUP_END_DTTM", \
	"EXP_EVALUATE___PICKUP_START_DTTM as PICKUP_START_DTTM", \
	"EXP_EVALUATE___PLANNED_SHIP_DATE as PLANNED_SHIP_DATE", \
	"EXP_EVALUATE___PRE_PACK_FLAG as PRE_PACK_FLAG", \
	"EXP_EVALUATE___PRIORITY as PRIORITY", \
	"EXP_EVALUATE___PRO_NUMBER as PRO_NUMBER", \
	"EXP_EVALUATE___PROC_DTTM as PROC_DTTM", \
	"EXP_EVALUATE___PROC_STAT_CODE as PROC_STAT_CODE", \
	"EXP_EVALUATE___REC_XPANS_FIELD as REC_XPANS_FIELD", \
	"EXP_EVALUATE___RTE_ID as RTE_ID", \
	"EXP_EVALUATE___RTE_SHIPMENT_SEQ as RTE_SHIPMENT_SEQ", \
	"EXP_EVALUATE___SCHED_DELIVERY_DTTM as SCHED_DELIVERY_DTTM", \
	"EXP_EVALUATE___SHIPMENT_ID as SHIPMENT_ID", \
	"EXP_EVALUATE___SHIP_DATE as SHIP_DATE", \
	"EXP_EVALUATE___SHIP_GROUP_ID as SHIP_GROUP_ID", \
	"EXP_EVALUATE___SHIP_GROUP_SEQUENCE as SHIP_GROUP_SEQUENCE", \
	"EXP_EVALUATE___SHPNG_CHRG as SHPNG_CHRG", \
	"EXP_EVALUATE___ORDER_STATUS as ORDER_STATUS", \
	"EXP_EVALUATE___DO_STATUS as DO_STATUS", \
	"EXP_EVALUATE___STORE_NBR as STORE_NBR", \
	"EXP_EVALUATE___STORE_TYPE as STORE_TYPE", \
	"EXP_EVALUATE___TAX_CHARGES as TAX_CHARGES", \
	"EXP_EVALUATE___TC_COMPANY_ID as TC_COMPANY_ID", \
	"EXP_EVALUATE___TC_ORDER_ID as TC_ORDER_ID", \
	"EXP_EVALUATE___TC_SHIPMENT_ID as TC_SHIPMENT_ID", \
	"EXP_EVALUATE___TOTAL_NBR_OF_LPN as TOTAL_NBR_OF_LPN", \
	"EXP_EVALUATE___TOTAL_NBR_OF_PLT as TOTAL_NBR_OF_PLT", \
	"EXP_EVALUATE___TOTAL_NBR_OF_UNITS as TOTAL_NBR_OF_UNITS", \
	"EXP_EVALUATE___VERSION_NBR as VERSION_NBR", \
	"EXP_EVALUATE___LINE_HAUL_SHIP_VIA as LINE_HAUL_SHIP_VIA", \
	"EXP_EVALUATE___PLAN_D_FACILITY_ALIAS_ID as PLAN_D_FACILITY_ALIAS_ID", \
	"EXP_EVALUATE___PLAN_D_FACILITY_ID as PLAN_D_FACILITY_ID", \
	"EXP_EVALUATE___PLAN_LEG_D_ALIAS_ID as PLAN_LEG_D_ALIAS_ID", \
	"EXP_EVALUATE___PLAN_LEG_D_ID as PLAN_LEG_D_ID", \
	"EXP_EVALUATE___PLAN_LEG_O_ALIAS_ID as PLAN_LEG_O_ALIAS_ID", \
	"EXP_EVALUATE___PLAN_LEG_O_ID as PLAN_LEG_O_ID", \
	"EXP_EVALUATE___PLAN_O_FACILITY_ALIAS_ID as PLAN_O_FACILITY_ALIAS_ID", \
	"EXP_EVALUATE___PLAN_O_FACILITY_ID as PLAN_O_FACILITY_ID", \
	"EXP_EVALUATE___SPL_INSTR_CODE_1 as SPL_INSTR_CODE_1", \
	"EXP_EVALUATE___SPL_INSTR_CODE_10 as SPL_INSTR_CODE_10", \
	"EXP_EVALUATE___SPL_INSTR_CODE_2 as SPL_INSTR_CODE_2", \
	"EXP_EVALUATE___SPL_INSTR_CODE_3 as SPL_INSTR_CODE_3", \
	"EXP_EVALUATE___SPL_INSTR_CODE_4 as SPL_INSTR_CODE_4", \
	"EXP_EVALUATE___SPL_INSTR_CODE_5 as SPL_INSTR_CODE_5", \
	"EXP_EVALUATE___SPL_INSTR_CODE_6 as SPL_INSTR_CODE_6", \
	"EXP_EVALUATE___SPL_INSTR_CODE_7 as SPL_INSTR_CODE_7", \
	"EXP_EVALUATE___SPL_INSTR_CODE_8 as SPL_INSTR_CODE_8", \
	"EXP_EVALUATE___SPL_INSTR_CODE_9 as SPL_INSTR_CODE_9", \
	"EXP_EVALUATE___PRE_BILL_STATUS as PRE_BILL_STATUS", \
	"EXP_EVALUATE___PRTL_SHIP_CONF_FLAG as PRTL_SHIP_CONF_FLAG", \
	"EXP_EVALUATE___PRTL_SHIP_CONF_STATUS as PRTL_SHIP_CONF_STATUS", \
	"EXP_EVALUATE___PRE_BILLED_FLAG as PRE_BILLED_FLAG", \
	"EXP_EVALUATE___TAX_ID as TAX_ID", \
	"EXP_EVALUATE___ALLOW_PRE_BILLING as ALLOW_PRE_BILLING", \
	"EXP_EVALUATE___O_PHONE_NUMBER as O_PHONE_NUMBER", \
	"EXP_EVALUATE___PURCHASE_ORDER_NBR as PURCHASE_ORDER_NBR", \
	"EXP_EVALUATE___MARK_FOR as MARK_FOR", \
	"EXP_EVALUATE___DISTRO_NUMBER as DISTRO_NUMBER", \
	"EXP_EVALUATE___REF_SHIPMENT_NBR as REF_SHIPMENT_NBR", \
	"EXP_EVALUATE___REF_STOP_SEQ as REF_STOP_SEQ", \
	"EXP_EVALUATE___PO_TYPE_ATTR as PO_TYPE_ATTR", \
	"EXP_EVALUATE___DSG_SHIP_VIA as DSG_SHIP_VIA", \
	"EXP_EVALUATE___in_WM_OUTPT_ORDERS_ID as in_WM_OUTPT_ORDERS_ID", \
	"EXP_EVALUATE___LOAD_TSTMP as LOAD_TSTMP", \
	"EXP_EVALUATE___UPDATE_TSTMP as UPDATE_TSTMP") \
	.withColumn('pyspark_data_action', when((in_WM_OUTPT_ORDERS_ID.isNull()) ,(lit(0))) .otherwise(lit(1)))

# COMMAND ----------
# Processing node Shortcut_to_WM_OUTPT_ORDERS, type TARGET 
# COLUMN COUNT: 172


Shortcut_to_WM_OUTPT_ORDERS = UPD_INS_UPD.selectExpr( \
	"CAST(LOCATION_ID AS BIGINT) as LOCATION_ID", \
	"CAST(OUTPT_ORDERS_ID AS BIGINT) as WM_OUTPT_ORDERS_ID", \
	"CAST(TC_COMPANY_ID AS BIGINT) as WM_TC_COMPANY_ID", \
	"CAST(TC_ORDER_ID AS STRING) as WM_TC_ORDER_ID", \
	"CAST(ORDER_STATUS AS BIGINT) as WM_ORDER_STATUS", \
	"CAST(DO_TYPE AS BIGINT) as WM_DO_TYPE", \
	"CAST(PO_TYPE_ATTR AS STRING) as WM_PO_TYPE_ATTR", \
	"CAST(DO_STATUS AS BIGINT) as WM_DO_STATUS", \
	"CAST(TC_SHIPMENT_ID AS STRING) as WM_TC_SHIPMENT_ID", \
	"CAST(PURCHASE_ORDER_NBR AS STRING) as WM_PURCHASE_ORDER_NBR", \
	"CAST(EXT_PURCHASE_ORDER AS STRING) as WM_EXT_PURCHASE_ORDER", \
	"CAST(SHIPMENT_ID AS BIGINT) as WM_SHIPMENT_ID", \
	"CAST(REF_SHIPMENT_NBR AS STRING) as WM_REF_SHIPMENT_NBR", \
	"CAST(SHIP_GROUP_ID AS STRING) as WM_SHIP_GROUP_ID", \
	"CAST(SHIP_GROUP_SEQUENCE AS BIGINT) as SHIP_GROUP_SEQ", \
	"CAST(INVC_BATCH_NBR AS BIGINT) as WM_INVC_BATCH_NBR", \
	"CAST(BATCH_CTRL_NBR AS STRING) as WM_BATCH_CTRL_NBR", \
	"CAST(BILL_OF_LADING_NUMBER AS STRING) as BILL_OF_LADING_NBR", \
	"CAST(BOL_BREAK_ATTR AS STRING) as BOL_BREAK_ATTR", \
	"CAST(BOL_TYPE AS STRING) as WM_BOL_TYPE", \
	"CAST(BUSINESS_PARTNER AS STRING) as BUSINESS_PARTNER", \
	"CAST(PROC_DTTM AS TIMESTAMP) as WM_PROC_TSTMP", \
	"CAST(PROC_STAT_CODE AS BIGINT) as WM_PROC_STAT_CD", \
	"CAST(IS_BACK_ORDERED AS STRING) as BACK_ORDERED_IND", \
	"CAST(RTE_ID AS STRING) as WM_RTE_ID", \
	"CAST(RTE_SHIPMENT_SEQ AS BIGINT) as RTE_SHIPMENT_SEQ", \
	"CAST(DISTRO_NUMBER AS STRING) as WM_DISTRO_NBR", \
	"CAST(REF_STOP_SEQ AS BIGINT) as REF_STOP_SEQ", \
	"CAST(ACCT_RCVBL_ACCT_NBR AS STRING) as WM_ACCT_RCVBL_ACCT_NBR", \
	"CAST(ACCT_RCVBL_CODE AS STRING) as WM_ACCT_RCVBL_CD", \
	"CAST(FREIGHT_FORWARDER_ACCT_NBR AS STRING) as WM_FREIGHT_FORWARDER_ACCT_NBR", \
	"CAST(GLOBAL_LOCN_NBR AS STRING) as WM_GLOBAL_LOCN_NBR", \
	"CAST(ADDR_CODE AS STRING) as WM_ADDR_CD", \
	"CAST(TAX_ID AS STRING) as WM_TAX_ID", \
	"CAST(BILLING_METHOD AS BIGINT) as WM_BILLING_METHOD", \
	"CAST(ALLOW_PRE_BILLING AS BIGINT) as ALLOW_PRE_BILLING_FLAG", \
	"CAST(PRE_BILLED_FLAG AS BIGINT) as PRE_BILLED_FLAG", \
	"CAST(PRE_BILL_STATUS AS BIGINT) as WM_PRE_BILL_STATUS", \
	"CAST(PRTL_SHIP_CONF_FLAG AS BIGINT) as PRTL_SHIP_CONF_FLAG", \
	"CAST(PRTL_SHIP_CONF_STATUS AS BIGINT) as WM_PRTL_SHIP_CONF_STATUS", \
	"CAST(MARK_FOR AS STRING) as MARK_FOR", \
	"CAST(ORIGINAL_SHIP_VIA AS STRING) as ORIGINAL_SHIP_VIA", \
	"CAST(DISTRIBUTION_SHIP_VIA AS STRING) as DISTRIBUTION_SHIP_VIA", \
	"CAST(LINE_HAUL_SHIP_VIA AS STRING) as LINE_HAUL_SHIP_VIA", \
	"CAST(FREIGHT_CLASS AS BIGINT) as FREIGHT_CLASS", \
	"CAST(INCOTERM_ID AS BIGINT) as WM_INCOTERM_ID", \
	"CAST(INCOTERM_NAME AS STRING) as INCOTERM_NAME", \
	"CAST(INCOTERM_FACILITY_ID AS BIGINT) as WM_INCOTERM_FACILITY_ID", \
	"CAST(INCOTERM_FACILITY_ALIAS_ID AS STRING) as WM_INCOTERM_FACILITY_ALIAS_ID", \
	"CAST(INCOTERM_LOC_AVA_DTTM AS TIMESTAMP) as INCOTERM_LOC_AVA_TSTMP", \
	"CAST(INCOTERM_LOC_AVA_TIME_ZONE_ID AS BIGINT) as WM_INCOTERM_LOC_AVA_TIME_ZONE_ID", \
	"CAST(MAJOR_MINOR_ORDER AS STRING) as WM_MAJOR_MINOR_ORDER", \
	"CAST(MAJOR_ORDER_CTRL_NBR AS STRING) as WM_MAJOR_ORDER_CTRL_NBR", \
	"CAST(MAJOR_ORDER_GRP_ATTR AS STRING) as WM_MAJOR_ORDER_GRP_ATTR", \
	"CAST(PRO_NUMBER AS STRING) as WM_PRO_NBR", \
	"CAST(MANIFEST_ID AS STRING) as WM_MANIFEST_ID", \
	"CAST(ORDER_DATE_DTTM AS TIMESTAMP) as ORDER_DT_TSTMP", \
	"CAST(PICKUP_START_DTTM AS TIMESTAMP) as PICKUP_START_TSTMP", \
	"CAST(PICKUP_END_DTTM AS TIMESTAMP) as PICKUP_END_TSTMP", \
	"CAST(SCHED_DELIVERY_DTTM AS TIMESTAMP) as SCHED_DELIVERY_TSTMP", \
	"CAST(DELIVERY_START_DTTM AS TIMESTAMP) as DELIVERY_START_TSTMP", \
	"CAST(PLANNED_SHIP_DATE AS TIMESTAMP) as PLANNED_SHIP_TSTMP", \
	"CAST(SHIP_DATE AS TIMESTAMP) as SHIP_TSTMP", \
	"CAST(PRE_PACK_FLAG AS BIGINT) as PRE_PACK_FLAG", \
	"CAST(PRIORITY AS BIGINT) as PRIORITY", \
	"CAST(REC_XPANS_FIELD AS STRING) as REC_XPANS_FIELD", \
	"CAST(DC_CTR_NBR AS STRING) as DC_CTR_NBR", \
	"CAST(STORE_NBR AS STRING) as STORE_NBR", \
	"CAST(STORE_TYPE AS STRING) as STORE_TYPE", \
	"CAST(MERCHANDIZING_DEPARTMENT AS STRING) as MERCHANDIZING_DEPT", \
	"CAST(MOVEMENT_OPTION AS BIGINT) as MOVEMENT_OPTION", \
	"CAST(NON_MACHINEABLE AS BIGINT) as NON_MACHINEABLE", \
	"CAST(DSG_SHIP_VIA AS STRING) as DSG_SHIP_VIA", \
	"CAST(ORG_SHIP_FACILITY_ALIAS_ID AS STRING) as WM_ORG_SHIP_FACILITY_ALIAS_ID", \
	"CAST(ORG_SHIP_FACILITY_ID AS BIGINT) as WM_ORG_SHIP_FACILITY_ID", \
	"CAST(ORIGINAL_ASSIGNED_SHIP_VIA AS STRING) as ORIGINAL_ASSIGNED_SHIP_VIA", \
	"CAST(ORIGIN_SHIP_THRU_FACILITY_ID AS BIGINT) as WM_ORIGIN_SHIP_THRU_FACILITY_ID", \
	"CAST(ORIGIN_SHIP_THRU_FAC_ALIAS_ID AS STRING) as WM_ORIGIN_SHIP_THRU_FAC_ALIAS_ID", \
	"CAST(PLAN_D_FACILITY_ALIAS_ID AS STRING) as WM_PLAN_D_FACILITY_ALIAS_ID", \
	"CAST(PLAN_D_FACILITY_ID AS BIGINT) as WM_PLAN_D_FACILITY_ID", \
	"CAST(PLAN_LEG_D_ALIAS_ID AS STRING) as WM_PLAN_LEG_D_ALIAS_ID", \
	"CAST(PLAN_LEG_D_ID AS BIGINT) as WM_PLAN_LEG_D_ID", \
	"CAST(PLAN_LEG_O_ALIAS_ID AS STRING) as WM_PLAN_LEG_O_ALIAS_ID", \
	"CAST(PLAN_LEG_O_ID AS BIGINT) as WM_PLAN_LEG_O_ID", \
	"CAST(PLAN_O_FACILITY_ALIAS_ID AS STRING) as WM_PLAN_O_FACILITY_ALIAS_ID", \
	"CAST(PLAN_O_FACILITY_ID AS BIGINT) as WM_PLAN_O_FACILITY_ID", \
	"CAST(BILL_ACCT_NBR AS STRING) as WM_BILL_ACCT_NBR", \
	"CAST(BILL_FACILITY_ID AS BIGINT) as WM_BILL_FACILITY_ID", \
	"CAST(BILL_FACILITY_ALIAS_ID AS STRING) as WM_BILL_FACILITY_ALIAS_ID", \
	"CAST(BILL_TO_NAME AS STRING) as BILL_TO_NAME", \
	"CAST(BILL_TO_TITLE AS STRING) as BILL_TO_TITLE", \
	"CAST(BILL_TO_CONTACT AS STRING) as BILL_TO_CONTACT", \
	"CAST(BILL_TO_CONTACT_NAME AS STRING) as BILL_TO_CONTACT_NAME", \
	"CAST(BILL_TO_FACILITY_NAME AS STRING) as BILL_TO_FACILITY_NAME", \
	"CAST(BILL_TO_ADDRESS_1 AS STRING) as BILL_TO_ADDR_1", \
	"CAST(BILL_TO_ADDRESS_2 AS STRING) as BILL_TO_ADDR_2", \
	"CAST(BILL_TO_ADDRESS_3 AS STRING) as BILL_TO_ADDR_3", \
	"CAST(BILL_TO_CITY AS STRING) as BILL_TO_CITY", \
	"CAST(BILL_TO_STATE_PROV AS STRING) as BILL_TO_STATE_PROV", \
	"CAST(BILL_TO_POSTAL_CODE AS STRING) as BILL_TO_POSTAL_CD", \
	"CAST(BILL_TO_COUNTY AS STRING) as BILL_TO_COUNTY", \
	"CAST(BILL_TO_COUNTRY_CODE AS STRING) as BILL_TO_COUNTRY_CD", \
	"CAST(BILL_TO_PHONE_NUMBER AS STRING) as BILL_TO_PHONE_NBR", \
	"CAST(BILL_TO_FAX_NUMBER AS STRING) as BILL_TO_FAX_NBR", \
	"CAST(BILL_TO_EMAIL AS STRING) as BILL_TO_EMAIL", \
	"CAST(D_NAME AS STRING) as D_NAME", \
	"CAST(D_CONTACT AS STRING) as D_CONTACT", \
	"CAST(D_FACILITY_ID AS BIGINT) as WM_D_FACILITY_ID", \
	"CAST(D_FACILITY_ALIAS_ID AS STRING) as WM_D_FACILITY_ALIAS_ID", \
	"CAST(D_FACILITY_NAME AS STRING) as D_FACILITY_NAME", \
	"CAST(D_ADDRESS_1 AS STRING) as D_ADDR_1", \
	"CAST(D_ADDRESS_2 AS STRING) as D_ADDR_2", \
	"CAST(D_ADDRESS_3 AS STRING) as D_ADDR_3", \
	"CAST(D_CITY AS STRING) as D_CITY", \
	"CAST(D_STATE_PROV AS STRING) as D_STATE_PROV", \
	"CAST(D_POSTAL_CODE AS STRING) as D_POSTAL_CD", \
	"CAST(D_COUNTY AS STRING) as D_COUNTY", \
	"CAST(D_COUNTRY_CODE AS STRING) as D_COUNTRY_CD", \
	"CAST(D_PHONE_NUMBER AS STRING) as D_PHONE_NBR", \
	"CAST(D_FAX_NUMBER AS STRING) as D_FAX_NBR", \
	"CAST(D_EMAIL AS STRING) as D_EMAIL", \
	"CAST(D_DOCK_ID AS STRING) as WM_D_DOCK_ID", \
	"CAST(D_DOCK_DOOR_ID AS BIGINT) as WM_D_DOCK_DOOR_ID", \
	"CAST(O_CONTACT AS STRING) as O_CONTACT", \
	"CAST(O_FACILITY_ID AS BIGINT) as WM_O_FACILITY_ID", \
	"CAST(O_FACILITY_ALIAS_ID AS STRING) as WM_O_FACILITY_ALIAS_ID", \
	"CAST(O_FACILITY_NAME AS STRING) as O_FACILITY_NAME", \
	"CAST(O_ADDRESS_1 AS STRING) as O_ADDR_1", \
	"CAST(O_ADDRESS_2 AS STRING) as O_ADDR_2", \
	"CAST(O_ADDRESS_3 AS STRING) as O_ADDR_3", \
	"CAST(O_CITY AS STRING) as O_CITY", \
	"CAST(O_STATE_PROV AS STRING) as O_STATE_PROV", \
	"CAST(O_POSTAL_CODE AS STRING) as O_POSTAL_CD", \
	"CAST(O_COUNTY AS STRING) as O_COUNTY", \
	"CAST(O_COUNTRY_CODE AS STRING) as O_COUNTRY_CD", \
	"CAST(O_PHONE_NUMBER AS STRING) as O_PHONE_NBR", \
	"CAST(O_FAX_NUMBER AS STRING) as O_FAX_NBR", \
	"CAST(O_EMAIL AS STRING) as O_EMAIL", \
	"CAST(O_DOCK_ID AS STRING) as WM_O_DOCK_ID", \
	"CAST(O_DOCK_DOOR_ID AS BIGINT) as WM_O_DOCK_DOOR_ID", \
	"CAST(TOTAL_NBR_OF_LPN AS BIGINT) as TOTAL_NBR_OF_LPN", \
	"CAST(TOTAL_NBR_OF_PLT AS BIGINT) as TOTAL_NBR_OF_PLT", \
	"CAST(TOTAL_NBR_OF_UNITS AS BIGINT) as TOTAL_NBR_OF_UNITS", \
	"CAST(BACKORDERED_QUANTITY AS BIGINT) as BACK_ORDERED_QTY", \
	"CAST(ORDER_WEIGHT AS BIGINT) as ORDER_WEIGHT", \
	"CAST(MONETARY_VALUE AS BIGINT) as MONETARY_VALUE", \
	"CAST(TAX_CHARGES AS BIGINT) as TAX_CHARGES_AMT", \
	"CAST(SHPNG_CHRG AS BIGINT) as SHIPPING_CHARGES_AMT", \
	"CAST(HANDLING_CHARGES AS BIGINT) as HANDLING_CHARGES_AMT", \
	"CAST(INSUR_CHRG AS BIGINT) as INSURANCE_CHARGES_AMT", \
	"CAST(MISC_CHARGES AS BIGINT) as MISC_CHARGES_AMT", \
	"CAST(CURRENCY AS STRING) as CURRENCY", \
	"CAST(MV_CURRENCY AS STRING) as MV_CURRENCY", \
	"CAST(SPL_INSTR_CODE_1 AS STRING) as SPL_INSTR_CD_1", \
	"CAST(SPL_INSTR_CODE_2 AS STRING) as SPL_INSTR_CD_2", \
	"CAST(SPL_INSTR_CODE_3 AS STRING) as SPL_INSTR_CD_3", \
	"CAST(SPL_INSTR_CODE_4 AS STRING) as SPL_INSTR_CD_4", \
	"CAST(SPL_INSTR_CODE_5 AS STRING) as SPL_INSTR_CD_5", \
	"CAST(SPL_INSTR_CODE_6 AS STRING) as SPL_INSTR_CD_6", \
	"CAST(SPL_INSTR_CODE_7 AS STRING) as SPL_INSTR_CD_7", \
	"CAST(SPL_INSTR_CODE_8 AS STRING) as SPL_INSTR_CD_8", \
	"CAST(SPL_INSTR_CODE_9 AS STRING) as SPL_INSTR_CD_9", \
	"CAST(SPL_INSTR_CODE_10 AS STRING) as SPL_INSTR_CD_10", \
	"CAST(VERSION_NBR AS BIGINT) as WM_VERSION_NBR", \
	"CAST(CREATED_SOURCE_TYPE AS BIGINT) as WM_CREATED_SOURCE_TYPE", \
	"CAST(CREATED_SOURCE AS STRING) as WM_CREATED_SOURCE", \
	"CAST(CREATED_DTTM AS TIMESTAMP) as WM_CREATED_TSTMP", \
	"CAST(LAST_UPDATED_SOURCE_TYPE AS BIGINT) as WM_LAST_UPDATED_SOURCE_TYPE", \
	"CAST(LAST_UPDATED_SOURCE AS STRING) as WM_LAST_UPDATED_SOURCE", \
	"CAST(LAST_UPDATED_DTTM AS TIMESTAMP) as WM_LAST_UPDATED_TSTMP", \
	"CAST(UPDATE_TSTMP AS TIMESTAMP) as UPDATE_TSTMP", \
	"CAST(LOAD_TSTMP AS TIMESTAMP) as LOAD_TSTMP" \
)
Shortcut_to_WM_OUTPT_ORDERS.write.saveAsTable(f'{raw}.WM_OUTPT_ORDERS')