#Code converted on 2023-06-20 18:37:36
import os
import argparse
from pyspark.sql import *
from pyspark.sql.functions import *
from pyspark.sql.window import Window
from pyspark.sql.types import *
from datetime import datetime
from pyspark.dbutils import DBUtils
from Datalake.utils.genericUtilities import *
from Datalake.utils.configs import *
from Datalake.utils.mergeUtils import *
from Datalake.utils.logger import *
# COMMAND ----------

parser = argparse.ArgumentParser()
spark = SparkSession.getActiveSession()
dbutils = DBUtils(spark)

parser.add_argument('env', type=str, help='Env Variable')
args = parser.parse_args()
env = args.env
# env = 'dev'

if env is None or env == '':
    raise ValueError('env is not set')

refine = getEnvPrefix(env) + 'refine'
raw = getEnvPrefix(env) + 'raw'
legacy = getEnvPrefix(env) + 'legacy'

# Set global variables
starttime = datetime.now() #start timestamp of the script
refined_perf_table = f"{refine}.WM_CARRIER_CODE"
raw_perf_table = f"{raw}.WM_CARRIER_CODE_PRE"
site_profile_table = f"{legacy}.SITE_PROFILE"


# COMMAND ----------
# Processing node SQ_Shortcut_to_WM_CARRIER_CODE, type SOURCE 
# COLUMN COUNT: 103

SQ_Shortcut_to_WM_CARRIER_CODE = spark.sql(f"""SELECT
LOCATION_ID,
WM_CARRIER_ID,
WM_CARRIER_CD,
WM_CARRIER_CD_NAME,
WM_CARRIER_CD_STATUS,
WM_TC_COMPANY_ID,
WM_TP_COMPANY_ID,
WM_TP_COMPANY_NAME,
ADDRESS,
CITY,
STATE_PROV,
POSTAL_CD,
COUNTRY_CD,
CARRIER_ADDR_FOR_CL,
WM_CARRIER_TYPE_ID,
WM_EPI_CARRIER_CD,
WM_SCAC_CD,
PAYMENT_METHOD,
PAYMENT_REFERENCE_NBR,
PREPAY_FLAG,
AUTO_CREATE_INVOICE_FLAG,
INVOICE_PAYMENT_TERMS,
VALIDATE_INVOICE,
MATCH_PAY_EMAIL,
PAYEE_FLAG,
WM_TARIFF_ID,
WM_TAX_ID,
HAZMAT_FLAG,
HAZMAT_REG_NBR,
EXPIRY_DT,
DAYS_TO_DISPUTE_CLAIM,
COMM_METHOD,
MOTOR_CARRIER_NBR,
FREIGHT_FRWRDR_NBR,
PRO_NBR_LEVEL,
DEFAULT_PALLET_TYPE,
AWB_UOM,
TRANS_EXCEL,
DOT_NBR,
BENCHMARK_FLAG,
UNION_FLAG,
AUTO_DELIVER_FLAG,
AUTO_ACCEPT_TYPE,
ACCEPT_MSG_REQD_FLAG,
APPT_MSG_REQD_FLAG,
DEPART_MSG_REQD_FLAG,
ARRIVE_MSG_REQD_FLAG,
CONFIRM_RECALL_REQD_FLAG,
CONFIRM_UPDATE_REQD_FLAG,
BROKER_FLAG,
BROKER_RECEIVE_UPDATES_FLAG,
ALLOW_BOL_ENTRY_FLAG,
AUTO_DELIVER_DELAY_HOURS,
DOCK_SCHEDULE_PERMISSION,
ALLOW_LOAD_COMPLETION_FLAG,
RECEIVES_DOCK_INFO_FLAG,
ALLOW_TRAILER_ENTRY_FLAG,
ALLOW_TRACTOR_ENTRY_FLAG,
ALLOW_CARRIER_CHARGES_VIEW_FLAG,
SUPPORTS_PARCEL,
RECEIVE_FACILITY_INFO_FLAG,
PRIVATE_FLEET_FLAG,
PREFERRED_FLAG,
CUT_PARCEL_INVOICE_FLAG,
USE_CARRIER_ADDR_FLAG,
CLAIM_ON_DETENTION_APPROVAL,
RES_BASED_COSTING_ALLOWED_FLAG,
ACTIVITY_BASED_COSTING_FLAG,
PCT_OVER_CAPACITY,
ALLOW_CARRIER_BOOKING_REF_FLAG,
ALLOW_FORWARDER_AWB_FLAG,
ALLOW_MASTER_AWB_FLAG,
MAX_FLEET_APPROVED_AMT,
CHECK_NON_MACHINABLE_FLAG,
INV_ON_CARR_SIZES_FLAG,
PRO_NUMBER_REQD_FLAG,
ALLOW_TENDER_REJECT_FLAG,
ALLOW_COUNTER_OFFER_FLAG,
DEPART_MSG_REQD_AT_FIRST_STOP_FLAG,
EPI_SUPPORTS_HOLD_PROCESS_FLAG,
EPI_SUPPORTS_EOD_FLAG,
LOAD_PRO_NEXT_UP_COUNTER,
STOP_PRO_NEXT_UP_COUNTER,
MOBILE_SHIP_TRACK_FLAG,
WM_LANGUAGE_ID,
REF_FIELD_1,
REF_FIELD_2,
REF_FIELD_3,
REF_FIELD_4,
REF_FIELD_5,
REF_NUM_1,
REF_NUM_2,
REF_NUM_3,
REF_NUM_4,
REF_NUM_5,
MARK_FOR_DELETION_FLAG,
WM_CREATED_SOURCE_TYPE,
WM_CREATED_SOURCE,
WM_CREATED_TSTMP,
WM_LAST_UPDATED_SOURCE_TYPE,
WM_LAST_UPDATED_SOURCE,
WM_LAST_UPDATED_TSTMP,
LOAD_TSTMP
FROM {refined_perf_table}
WHERE WM_CARRIER_ID IN ( SELECT CARRIER_ID FROM {raw_perf_table} )""").withColumn("sys_row_id", monotonically_increasing_id())

# COMMAND ----------
# Processing node SQ_Shortcut_to_WM_CARRIER_CODE_PRE, type SOURCE 
# COLUMN COUNT: 102

SQ_Shortcut_to_WM_CARRIER_CODE_PRE = spark.sql(f"""SELECT
DC_NBR,
CARRIER_ID,
CARRIER_CODE,
CARRIER_CODE_NAME,
CARRIER_CODE_STATUS,
TC_COMPANY_ID,
TP_COMPANY_ID,
TP_COMPANY_NAME,
ADDRESS,
CITY,
STATE_PROV,
POSTAL_CODE,
COUNTRY_CODE,
CARRIER_ADDR_FOR_CL,
CARRIER_TYPE_ID,
EPI_CARRIER_CODE,
SCAC_CODE,
PAYMENT_METHOD,
PAYMENT_REFERENCE_NUMBER,
IS_PREPAY,
IS_AUTO_CREATE_INVOICE,
INVOICE_PAYMENT_TERMS,
VALIDATE_INVOICE,
MATCH_PAY_EMAIL,
IS_PAYEE,
TARIFF_ID,
TAX_ID,
HAS_HAZMAT,
HAZMAT_REG_NBR,
EXPIRY_DATE,
DAYS_TO_DISPUTE_CLAIM,
COMM_METHOD,
MOTOR_CARRIER_NBR,
FREIGHT_FRWRDR_NBR,
PRO_NUMBER_LEVEL,
DEFAULT_PALLET_TYPE,
AWB_UOM,
TRANS_EXCEL,
DOT_NUMBER,
IS_BENCHMARK,
IS_UNION,
IS_AUTO_DELIVER,
AUTO_ACCEPT_TYPE,
ACCEPT_MSG_REQD,
APPT_MSG_REQD,
DEPART_MSG_REQD,
ARRIVE_MSG_REQD,
CONFIRM_RECALL_REQD,
CONFIRM_UPDATE_REQD,
IS_BROKER,
BROKER_RECEIVE_UPDATES,
ALLOW_BOL_ENTRY,
AUTO_DELIVER_DELAY_HOURS,
DOCK_SCHEDULE_PERMISSION,
ALLOW_LOAD_COMPLETION,
RECEIVES_DOCK_INFO,
ALLOW_TRAILER_ENTRY,
ALLOW_TRACTOR_ENTRY,
ALLOW_CARRIER_CHARGES_VIEW,
SUPPORTS_PARCEL,
DOES_RECEIVE_FACILITY_INFO,
IS_PRIVATE_FLEET,
IS_PREFERRED,
CUT_PARCEL_INVOICE,
USE_CARRIER_ADDR,
CLAIM_ON_DETENTION_APPROVAL,
IS_RES_BASED_COSTING_ALLOWED,
IS_ACTIVITY_BASED_COSTING,
PCT_OVER_CAPACITY,
ALLOW_CARRIER_BOOKING_REF,
ALLOW_FORWARDER_AWB,
ALLOW_MASTER_AWB,
MAX_FLEET_APPROVED_AMOUNT,
CHECK_NON_MACHINABLE,
INV_ON_CARR_SIZES,
PRO_NUMBER_REQD,
ALLOW_COUNTER_OFFER,
ALLOW_TENDER_REJECT,
DEPART_MSG_REQD_AT_FIRST_STOP,
EPI_SUPPORTS_HOLD_PROCESS,
EPI_SUPPORTS_EOD,
LOAD_PRO_NEXT_UP_COUNTER,
STOP_PRO_NEXT_UP_COUNTER,
MOBILE_SHIP_TRACK,
LANG_ID,
REF_FIELD1,
REF_FIELD2,
REF_FIELD3,
REF_FIELD4,
REF_FIELD5,
REF_NUM1,
REF_NUM2,
REF_NUM3,
REF_NUM4,
REF_NUM5,
MARK_FOR_DELETION,
CREATED_SOURCE_TYPE,
CREATED_SOURCE,
CREATED_DTTM,
LAST_UPDATED_SOURCE_TYPE,
LAST_UPDATED_SOURCE,
LAST_UPDATED_DTTM
FROM {raw_perf_table}""").withColumn("sys_row_id", monotonically_increasing_id())

# COMMAND ----------
# Processing node EXP_INT_CONVERSION, type EXPRESSION 
# COLUMN COUNT: 102

# for each involved DataFrame, append the dataframe name to each column
SQ_Shortcut_to_WM_CARRIER_CODE_PRE_temp = SQ_Shortcut_to_WM_CARRIER_CODE_PRE.toDF(*["SQ_Shortcut_to_WM_CARRIER_CODE_PRE___" + col for col in SQ_Shortcut_to_WM_CARRIER_CODE_PRE.columns])

EXP_INT_CONVERSION = SQ_Shortcut_to_WM_CARRIER_CODE_PRE_temp.selectExpr( \
	"SQ_Shortcut_to_WM_CARRIER_CODE_PRE___sys_row_id as sys_row_id", \
	"cast(SQ_Shortcut_to_WM_CARRIER_CODE_PRE___DC_NBR as int) as o_DC_NBR", \
	"SQ_Shortcut_to_WM_CARRIER_CODE_PRE___CARRIER_ID as CARRIER_ID", \
	"SQ_Shortcut_to_WM_CARRIER_CODE_PRE___CARRIER_CODE as CARRIER_CODE", \
	"SQ_Shortcut_to_WM_CARRIER_CODE_PRE___CARRIER_CODE_NAME as CARRIER_CODE_NAME", \
	"SQ_Shortcut_to_WM_CARRIER_CODE_PRE___CARRIER_CODE_STATUS as CARRIER_CODE_STATUS", \
	"SQ_Shortcut_to_WM_CARRIER_CODE_PRE___TC_COMPANY_ID as TC_COMPANY_ID", \
	"SQ_Shortcut_to_WM_CARRIER_CODE_PRE___TP_COMPANY_ID as TP_COMPANY_ID", \
	"SQ_Shortcut_to_WM_CARRIER_CODE_PRE___TP_COMPANY_NAME as TP_COMPANY_NAME", \
	"SQ_Shortcut_to_WM_CARRIER_CODE_PRE___ADDRESS as ADDRESS", \
	"SQ_Shortcut_to_WM_CARRIER_CODE_PRE___CITY as CITY", \
	"SQ_Shortcut_to_WM_CARRIER_CODE_PRE___STATE_PROV as STATE_PROV", \
	"SQ_Shortcut_to_WM_CARRIER_CODE_PRE___POSTAL_CODE as POSTAL_CODE", \
	"SQ_Shortcut_to_WM_CARRIER_CODE_PRE___COUNTRY_CODE as COUNTRY_CODE", \
	"SQ_Shortcut_to_WM_CARRIER_CODE_PRE___CARRIER_ADDR_FOR_CL as CARRIER_ADDR_FOR_CL", \
	"SQ_Shortcut_to_WM_CARRIER_CODE_PRE___CARRIER_TYPE_ID as CARRIER_TYPE_ID", \
	"SQ_Shortcut_to_WM_CARRIER_CODE_PRE___EPI_CARRIER_CODE as EPI_CARRIER_CODE", \
	"SQ_Shortcut_to_WM_CARRIER_CODE_PRE___SCAC_CODE as SCAC_CODE", \
	"SQ_Shortcut_to_WM_CARRIER_CODE_PRE___PAYMENT_METHOD as PAYMENT_METHOD", \
	"SQ_Shortcut_to_WM_CARRIER_CODE_PRE___PAYMENT_REFERENCE_NUMBER as PAYMENT_REFERENCE_NUMBER", \
	"SQ_Shortcut_to_WM_CARRIER_CODE_PRE___IS_PREPAY as IS_PREPAY", \
	"SQ_Shortcut_to_WM_CARRIER_CODE_PRE___IS_AUTO_CREATE_INVOICE as IS_AUTO_CREATE_INVOICE", \
	"SQ_Shortcut_to_WM_CARRIER_CODE_PRE___INVOICE_PAYMENT_TERMS as INVOICE_PAYMENT_TERMS", \
	"SQ_Shortcut_to_WM_CARRIER_CODE_PRE___VALIDATE_INVOICE as VALIDATE_INVOICE", \
	"SQ_Shortcut_to_WM_CARRIER_CODE_PRE___MATCH_PAY_EMAIL as MATCH_PAY_EMAIL", \
	"SQ_Shortcut_to_WM_CARRIER_CODE_PRE___IS_PAYEE as IS_PAYEE", \
	"SQ_Shortcut_to_WM_CARRIER_CODE_PRE___TARIFF_ID as TARIFF_ID", \
	"SQ_Shortcut_to_WM_CARRIER_CODE_PRE___TAX_ID as TAX_ID", \
	"SQ_Shortcut_to_WM_CARRIER_CODE_PRE___HAS_HAZMAT as HAS_HAZMAT", \
	"SQ_Shortcut_to_WM_CARRIER_CODE_PRE___HAZMAT_REG_NBR as HAZMAT_REG_NBR", \
	"SQ_Shortcut_to_WM_CARRIER_CODE_PRE___EXPIRY_DATE as EXPIRY_DATE", \
	"SQ_Shortcut_to_WM_CARRIER_CODE_PRE___DAYS_TO_DISPUTE_CLAIM as DAYS_TO_DISPUTE_CLAIM", \
	"SQ_Shortcut_to_WM_CARRIER_CODE_PRE___COMM_METHOD as COMM_METHOD", \
	"SQ_Shortcut_to_WM_CARRIER_CODE_PRE___MOTOR_CARRIER_NBR as MOTOR_CARRIER_NBR", \
	"SQ_Shortcut_to_WM_CARRIER_CODE_PRE___FREIGHT_FRWRDR_NBR as FREIGHT_FRWRDR_NBR", \
	"SQ_Shortcut_to_WM_CARRIER_CODE_PRE___PRO_NUMBER_LEVEL as PRO_NUMBER_LEVEL", \
	"SQ_Shortcut_to_WM_CARRIER_CODE_PRE___DEFAULT_PALLET_TYPE as DEFAULT_PALLET_TYPE", \
	"SQ_Shortcut_to_WM_CARRIER_CODE_PRE___AWB_UOM as AWB_UOM", \
	"SQ_Shortcut_to_WM_CARRIER_CODE_PRE___TRANS_EXCEL as TRANS_EXCEL", \
	"SQ_Shortcut_to_WM_CARRIER_CODE_PRE___DOT_NUMBER as DOT_NUMBER", \
	"SQ_Shortcut_to_WM_CARRIER_CODE_PRE___IS_BENCHMARK as IS_BENCHMARK", \
	"SQ_Shortcut_to_WM_CARRIER_CODE_PRE___IS_UNION as IS_UNION", \
	"SQ_Shortcut_to_WM_CARRIER_CODE_PRE___IS_AUTO_DELIVER as IS_AUTO_DELIVER", \
	"SQ_Shortcut_to_WM_CARRIER_CODE_PRE___AUTO_ACCEPT_TYPE as AUTO_ACCEPT_TYPE", \
	"SQ_Shortcut_to_WM_CARRIER_CODE_PRE___ACCEPT_MSG_REQD as ACCEPT_MSG_REQD", \
	"SQ_Shortcut_to_WM_CARRIER_CODE_PRE___APPT_MSG_REQD as APPT_MSG_REQD", \
	"SQ_Shortcut_to_WM_CARRIER_CODE_PRE___DEPART_MSG_REQD as DEPART_MSG_REQD", \
	"SQ_Shortcut_to_WM_CARRIER_CODE_PRE___ARRIVE_MSG_REQD as ARRIVE_MSG_REQD", \
	"SQ_Shortcut_to_WM_CARRIER_CODE_PRE___CONFIRM_RECALL_REQD as CONFIRM_RECALL_REQD", \
	"SQ_Shortcut_to_WM_CARRIER_CODE_PRE___CONFIRM_UPDATE_REQD as CONFIRM_UPDATE_REQD", \
	"SQ_Shortcut_to_WM_CARRIER_CODE_PRE___IS_BROKER as IS_BROKER", \
	"SQ_Shortcut_to_WM_CARRIER_CODE_PRE___BROKER_RECEIVE_UPDATES as BROKER_RECEIVE_UPDATES", \
	"SQ_Shortcut_to_WM_CARRIER_CODE_PRE___ALLOW_BOL_ENTRY as ALLOW_BOL_ENTRY", \
	"SQ_Shortcut_to_WM_CARRIER_CODE_PRE___AUTO_DELIVER_DELAY_HOURS as AUTO_DELIVER_DELAY_HOURS", \
	"SQ_Shortcut_to_WM_CARRIER_CODE_PRE___DOCK_SCHEDULE_PERMISSION as DOCK_SCHEDULE_PERMISSION", \
	"SQ_Shortcut_to_WM_CARRIER_CODE_PRE___ALLOW_LOAD_COMPLETION as ALLOW_LOAD_COMPLETION", \
	"SQ_Shortcut_to_WM_CARRIER_CODE_PRE___RECEIVES_DOCK_INFO as RECEIVES_DOCK_INFO", \
	"SQ_Shortcut_to_WM_CARRIER_CODE_PRE___ALLOW_TRAILER_ENTRY as ALLOW_TRAILER_ENTRY", \
	"SQ_Shortcut_to_WM_CARRIER_CODE_PRE___ALLOW_TRACTOR_ENTRY as ALLOW_TRACTOR_ENTRY", \
	"SQ_Shortcut_to_WM_CARRIER_CODE_PRE___ALLOW_CARRIER_CHARGES_VIEW as ALLOW_CARRIER_CHARGES_VIEW", \
	"SQ_Shortcut_to_WM_CARRIER_CODE_PRE___SUPPORTS_PARCEL as SUPPORTS_PARCEL", \
	"SQ_Shortcut_to_WM_CARRIER_CODE_PRE___DOES_RECEIVE_FACILITY_INFO as DOES_RECEIVE_FACILITY_INFO", \
	"SQ_Shortcut_to_WM_CARRIER_CODE_PRE___IS_PRIVATE_FLEET as IS_PRIVATE_FLEET", \
	"SQ_Shortcut_to_WM_CARRIER_CODE_PRE___IS_PREFERRED as IS_PREFERRED", \
	"SQ_Shortcut_to_WM_CARRIER_CODE_PRE___CUT_PARCEL_INVOICE as CUT_PARCEL_INVOICE", \
	"SQ_Shortcut_to_WM_CARRIER_CODE_PRE___USE_CARRIER_ADDR as USE_CARRIER_ADDR", \
	"SQ_Shortcut_to_WM_CARRIER_CODE_PRE___CLAIM_ON_DETENTION_APPROVAL as CLAIM_ON_DETENTION_APPROVAL", \
	"SQ_Shortcut_to_WM_CARRIER_CODE_PRE___IS_RES_BASED_COSTING_ALLOWED as IS_RES_BASED_COSTING_ALLOWED", \
	"SQ_Shortcut_to_WM_CARRIER_CODE_PRE___IS_ACTIVITY_BASED_COSTING as IS_ACTIVITY_BASED_COSTING", \
	"SQ_Shortcut_to_WM_CARRIER_CODE_PRE___PCT_OVER_CAPACITY as PCT_OVER_CAPACITY", \
	"SQ_Shortcut_to_WM_CARRIER_CODE_PRE___ALLOW_CARRIER_BOOKING_REF as ALLOW_CARRIER_BOOKING_REF", \
	"SQ_Shortcut_to_WM_CARRIER_CODE_PRE___ALLOW_FORWARDER_AWB as ALLOW_FORWARDER_AWB", \
	"SQ_Shortcut_to_WM_CARRIER_CODE_PRE___ALLOW_MASTER_AWB as ALLOW_MASTER_AWB", \
	"SQ_Shortcut_to_WM_CARRIER_CODE_PRE___MAX_FLEET_APPROVED_AMOUNT as MAX_FLEET_APPROVED_AMOUNT", \
	"SQ_Shortcut_to_WM_CARRIER_CODE_PRE___CHECK_NON_MACHINABLE as CHECK_NON_MACHINABLE", \
	"SQ_Shortcut_to_WM_CARRIER_CODE_PRE___INV_ON_CARR_SIZES as INV_ON_CARR_SIZES", \
	"SQ_Shortcut_to_WM_CARRIER_CODE_PRE___PRO_NUMBER_REQD as PRO_NUMBER_REQD", \
	"SQ_Shortcut_to_WM_CARRIER_CODE_PRE___ALLOW_COUNTER_OFFER as ALLOW_COUNTER_OFFER", \
	"SQ_Shortcut_to_WM_CARRIER_CODE_PRE___ALLOW_TENDER_REJECT as ALLOW_TENDER_REJECT", \
	"SQ_Shortcut_to_WM_CARRIER_CODE_PRE___DEPART_MSG_REQD_AT_FIRST_STOP as DEPART_MSG_REQD_AT_FIRST_STOP", \
	"SQ_Shortcut_to_WM_CARRIER_CODE_PRE___EPI_SUPPORTS_HOLD_PROCESS as EPI_SUPPORTS_HOLD_PROCESS", \
	"SQ_Shortcut_to_WM_CARRIER_CODE_PRE___EPI_SUPPORTS_EOD as EPI_SUPPORTS_EOD", \
	"SQ_Shortcut_to_WM_CARRIER_CODE_PRE___LOAD_PRO_NEXT_UP_COUNTER as LOAD_PRO_NEXT_UP_COUNTER", \
	"SQ_Shortcut_to_WM_CARRIER_CODE_PRE___STOP_PRO_NEXT_UP_COUNTER as STOP_PRO_NEXT_UP_COUNTER", \
	"SQ_Shortcut_to_WM_CARRIER_CODE_PRE___MOBILE_SHIP_TRACK as MOBILE_SHIP_TRACK", \
	"SQ_Shortcut_to_WM_CARRIER_CODE_PRE___LANG_ID as LANG_ID", \
	"SQ_Shortcut_to_WM_CARRIER_CODE_PRE___REF_FIELD1 as REF_FIELD1", \
	"SQ_Shortcut_to_WM_CARRIER_CODE_PRE___REF_FIELD2 as REF_FIELD2", \
	"SQ_Shortcut_to_WM_CARRIER_CODE_PRE___REF_FIELD3 as REF_FIELD3", \
	"SQ_Shortcut_to_WM_CARRIER_CODE_PRE___REF_FIELD4 as REF_FIELD4", \
	"SQ_Shortcut_to_WM_CARRIER_CODE_PRE___REF_FIELD5 as REF_FIELD5", \
	"SQ_Shortcut_to_WM_CARRIER_CODE_PRE___REF_NUM1 as REF_NUM1", \
	"SQ_Shortcut_to_WM_CARRIER_CODE_PRE___REF_NUM2 as REF_NUM2", \
	"SQ_Shortcut_to_WM_CARRIER_CODE_PRE___REF_NUM3 as REF_NUM3", \
	"SQ_Shortcut_to_WM_CARRIER_CODE_PRE___REF_NUM4 as REF_NUM4", \
	"SQ_Shortcut_to_WM_CARRIER_CODE_PRE___REF_NUM5 as REF_NUM5", \
	"SQ_Shortcut_to_WM_CARRIER_CODE_PRE___MARK_FOR_DELETION as MARK_FOR_DELETION", \
	"SQ_Shortcut_to_WM_CARRIER_CODE_PRE___CREATED_SOURCE_TYPE as CREATED_SOURCE_TYPE", \
	"SQ_Shortcut_to_WM_CARRIER_CODE_PRE___CREATED_SOURCE as CREATED_SOURCE", \
	"SQ_Shortcut_to_WM_CARRIER_CODE_PRE___CREATED_DTTM as CREATED_DTTM", \
	"SQ_Shortcut_to_WM_CARRIER_CODE_PRE___LAST_UPDATED_SOURCE_TYPE as LAST_UPDATED_SOURCE_TYPE", \
	"SQ_Shortcut_to_WM_CARRIER_CODE_PRE___LAST_UPDATED_SOURCE as LAST_UPDATED_SOURCE", \
	"SQ_Shortcut_to_WM_CARRIER_CODE_PRE___LAST_UPDATED_DTTM as LAST_UPDATED_DTTM" \
)

# COMMAND ----------
# Processing node SQ_Shortcut_to_SITE_PROFILE, type SOURCE 
# COLUMN COUNT: 2

SQ_Shortcut_to_SITE_PROFILE = spark.sql(f"""SELECT LOCATION_ID, STORE_NBR FROM {site_profile_table}""").withColumn("sys_row_id", monotonically_increasing_id())

# COMMAND ----------
# Processing node JNR_SITE_PROFILE, type JOINER 
# COLUMN COUNT: 104

JNR_SITE_PROFILE = SQ_Shortcut_to_SITE_PROFILE.join(EXP_INT_CONVERSION,[SQ_Shortcut_to_SITE_PROFILE.STORE_NBR == EXP_INT_CONVERSION.o_DC_NBR],'inner')

# COMMAND ----------
# Processing node JNR_WM_CARRIER_CODE, type JOINER . Note: using additional SELECT to rename incoming columns
# COLUMN COUNT: 205

# for each involved DataFrame, append the dataframe name to each column
JNR_SITE_PROFILE_temp = JNR_SITE_PROFILE.toDF(*["JNR_SITE_PROFILE___" + col for col in JNR_SITE_PROFILE.columns])
SQ_Shortcut_to_WM_CARRIER_CODE_temp = SQ_Shortcut_to_WM_CARRIER_CODE.toDF(*["SQ_Shortcut_to_WM_CARRIER_CODE___" + col for col in SQ_Shortcut_to_WM_CARRIER_CODE.columns])

JNR_WM_CARRIER_CODE = SQ_Shortcut_to_WM_CARRIER_CODE_temp.join(JNR_SITE_PROFILE_temp,[SQ_Shortcut_to_WM_CARRIER_CODE_temp.SQ_Shortcut_to_WM_CARRIER_CODE___LOCATION_ID == JNR_SITE_PROFILE_temp.JNR_SITE_PROFILE___LOCATION_ID, SQ_Shortcut_to_WM_CARRIER_CODE_temp.SQ_Shortcut_to_WM_CARRIER_CODE___WM_CARRIER_ID == JNR_SITE_PROFILE_temp.JNR_SITE_PROFILE___CARRIER_ID],'right_outer').selectExpr( \
	"JNR_SITE_PROFILE___CARRIER_ID as CARRIER_ID", \
	"JNR_SITE_PROFILE___CARRIER_CODE as CARRIER_CODE", \
	"JNR_SITE_PROFILE___CARRIER_CODE_NAME as CARRIER_CODE_NAME", \
	"JNR_SITE_PROFILE___CARRIER_CODE_STATUS as CARRIER_CODE_STATUS", \
	"JNR_SITE_PROFILE___TC_COMPANY_ID as TC_COMPANY_ID", \
	"JNR_SITE_PROFILE___TP_COMPANY_ID as TP_COMPANY_ID", \
	"JNR_SITE_PROFILE___TP_COMPANY_NAME as TP_COMPANY_NAME", \
	"JNR_SITE_PROFILE___ADDRESS as ADDRESS", \
	"JNR_SITE_PROFILE___CITY as CITY", \
	"JNR_SITE_PROFILE___STATE_PROV as STATE_PROV", \
	"JNR_SITE_PROFILE___POSTAL_CODE as POSTAL_CODE", \
	"JNR_SITE_PROFILE___COUNTRY_CODE as COUNTRY_CODE", \
	"JNR_SITE_PROFILE___CARRIER_ADDR_FOR_CL as CARRIER_ADDR_FOR_CL", \
	"JNR_SITE_PROFILE___CARRIER_TYPE_ID as CARRIER_TYPE_ID", \
	"JNR_SITE_PROFILE___EPI_CARRIER_CODE as EPI_CARRIER_CODE", \
	"JNR_SITE_PROFILE___SCAC_CODE as SCAC_CODE", \
	"JNR_SITE_PROFILE___PAYMENT_METHOD as PAYMENT_METHOD", \
	"JNR_SITE_PROFILE___PAYMENT_REFERENCE_NUMBER as PAYMENT_REFERENCE_NUMBER", \
	"JNR_SITE_PROFILE___IS_PREPAY as IS_PREPAY", \
	"JNR_SITE_PROFILE___IS_AUTO_CREATE_INVOICE as IS_AUTO_CREATE_INVOICE", \
	"JNR_SITE_PROFILE___INVOICE_PAYMENT_TERMS as INVOICE_PAYMENT_TERMS", \
	"JNR_SITE_PROFILE___VALIDATE_INVOICE as VALIDATE_INVOICE", \
	"JNR_SITE_PROFILE___MATCH_PAY_EMAIL as MATCH_PAY_EMAIL", \
	"JNR_SITE_PROFILE___IS_PAYEE as IS_PAYEE", \
	"JNR_SITE_PROFILE___TARIFF_ID as TARIFF_ID", \
	"JNR_SITE_PROFILE___TAX_ID as TAX_ID", \
	"JNR_SITE_PROFILE___HAS_HAZMAT as HAS_HAZMAT", \
	"JNR_SITE_PROFILE___HAZMAT_REG_NBR as HAZMAT_REG_NBR", \
	"JNR_SITE_PROFILE___EXPIRY_DATE as EXPIRY_DATE", \
	"JNR_SITE_PROFILE___DAYS_TO_DISPUTE_CLAIM as DAYS_TO_DISPUTE_CLAIM", \
	"JNR_SITE_PROFILE___COMM_METHOD as COMM_METHOD", \
	"JNR_SITE_PROFILE___MOTOR_CARRIER_NBR as MOTOR_CARRIER_NBR", \
	"JNR_SITE_PROFILE___FREIGHT_FRWRDR_NBR as FREIGHT_FRWRDR_NBR", \
	"JNR_SITE_PROFILE___PRO_NUMBER_LEVEL as PRO_NUMBER_LEVEL", \
	"JNR_SITE_PROFILE___DEFAULT_PALLET_TYPE as DEFAULT_PALLET_TYPE", \
	"JNR_SITE_PROFILE___AWB_UOM as AWB_UOM", \
	"JNR_SITE_PROFILE___TRANS_EXCEL as TRANS_EXCEL", \
	"JNR_SITE_PROFILE___DOT_NUMBER as DOT_NUMBER", \
	"JNR_SITE_PROFILE___IS_BENCHMARK as IS_BENCHMARK", \
	"JNR_SITE_PROFILE___IS_UNION as IS_UNION", \
	"JNR_SITE_PROFILE___IS_AUTO_DELIVER as IS_AUTO_DELIVER", \
	"JNR_SITE_PROFILE___AUTO_ACCEPT_TYPE as AUTO_ACCEPT_TYPE", \
	"JNR_SITE_PROFILE___ACCEPT_MSG_REQD as ACCEPT_MSG_REQD", \
	"JNR_SITE_PROFILE___APPT_MSG_REQD as APPT_MSG_REQD", \
	"JNR_SITE_PROFILE___DEPART_MSG_REQD as DEPART_MSG_REQD", \
	"JNR_SITE_PROFILE___ARRIVE_MSG_REQD as ARRIVE_MSG_REQD", \
	"JNR_SITE_PROFILE___CONFIRM_RECALL_REQD as CONFIRM_RECALL_REQD", \
	"JNR_SITE_PROFILE___CONFIRM_UPDATE_REQD as CONFIRM_UPDATE_REQD", \
	"JNR_SITE_PROFILE___IS_BROKER as IS_BROKER", \
	"JNR_SITE_PROFILE___BROKER_RECEIVE_UPDATES as BROKER_RECEIVE_UPDATES", \
	"JNR_SITE_PROFILE___ALLOW_BOL_ENTRY as ALLOW_BOL_ENTRY", \
	"JNR_SITE_PROFILE___AUTO_DELIVER_DELAY_HOURS as AUTO_DELIVER_DELAY_HOURS", \
	"JNR_SITE_PROFILE___DOCK_SCHEDULE_PERMISSION as DOCK_SCHEDULE_PERMISSION", \
	"JNR_SITE_PROFILE___ALLOW_LOAD_COMPLETION as ALLOW_LOAD_COMPLETION", \
	"JNR_SITE_PROFILE___RECEIVES_DOCK_INFO as RECEIVES_DOCK_INFO", \
	"JNR_SITE_PROFILE___ALLOW_TRAILER_ENTRY as ALLOW_TRAILER_ENTRY", \
	"JNR_SITE_PROFILE___ALLOW_TRACTOR_ENTRY as ALLOW_TRACTOR_ENTRY", \
	"JNR_SITE_PROFILE___ALLOW_CARRIER_CHARGES_VIEW as ALLOW_CARRIER_CHARGES_VIEW", \
	"JNR_SITE_PROFILE___SUPPORTS_PARCEL as SUPPORTS_PARCEL", \
	"JNR_SITE_PROFILE___DOES_RECEIVE_FACILITY_INFO as DOES_RECEIVE_FACILITY_INFO", \
	"JNR_SITE_PROFILE___IS_PRIVATE_FLEET as IS_PRIVATE_FLEET", \
	"JNR_SITE_PROFILE___IS_PREFERRED as IS_PREFERRED", \
	"JNR_SITE_PROFILE___CUT_PARCEL_INVOICE as CUT_PARCEL_INVOICE", \
	"JNR_SITE_PROFILE___USE_CARRIER_ADDR as USE_CARRIER_ADDR", \
	"JNR_SITE_PROFILE___CLAIM_ON_DETENTION_APPROVAL as CLAIM_ON_DETENTION_APPROVAL", \
	"JNR_SITE_PROFILE___IS_RES_BASED_COSTING_ALLOWED as IS_RES_BASED_COSTING_ALLOWED", \
	"JNR_SITE_PROFILE___IS_ACTIVITY_BASED_COSTING as IS_ACTIVITY_BASED_COSTING", \
	"JNR_SITE_PROFILE___PCT_OVER_CAPACITY as PCT_OVER_CAPACITY", \
	"JNR_SITE_PROFILE___ALLOW_CARRIER_BOOKING_REF as ALLOW_CARRIER_BOOKING_REF", \
	"JNR_SITE_PROFILE___ALLOW_FORWARDER_AWB as ALLOW_FORWARDER_AWB", \
	"JNR_SITE_PROFILE___ALLOW_MASTER_AWB as ALLOW_MASTER_AWB", \
	"JNR_SITE_PROFILE___MAX_FLEET_APPROVED_AMOUNT as MAX_FLEET_APPROVED_AMOUNT", \
	"JNR_SITE_PROFILE___CHECK_NON_MACHINABLE as CHECK_NON_MACHINABLE", \
	"JNR_SITE_PROFILE___INV_ON_CARR_SIZES as INV_ON_CARR_SIZES", \
	"JNR_SITE_PROFILE___PRO_NUMBER_REQD as PRO_NUMBER_REQD", \
	"JNR_SITE_PROFILE___ALLOW_COUNTER_OFFER as ALLOW_COUNTER_OFFER", \
	"JNR_SITE_PROFILE___ALLOW_TENDER_REJECT as ALLOW_TENDER_REJECT", \
	"JNR_SITE_PROFILE___DEPART_MSG_REQD_AT_FIRST_STOP as DEPART_MSG_REQD_AT_FIRST_STOP", \
	"JNR_SITE_PROFILE___EPI_SUPPORTS_HOLD_PROCESS as EPI_SUPPORTS_HOLD_PROCESS", \
	"JNR_SITE_PROFILE___EPI_SUPPORTS_EOD as EPI_SUPPORTS_EOD", \
	"JNR_SITE_PROFILE___LOAD_PRO_NEXT_UP_COUNTER as LOAD_PRO_NEXT_UP_COUNTER", \
	"JNR_SITE_PROFILE___STOP_PRO_NEXT_UP_COUNTER as STOP_PRO_NEXT_UP_COUNTER", \
	"JNR_SITE_PROFILE___MOBILE_SHIP_TRACK as MOBILE_SHIP_TRACK", \
	"JNR_SITE_PROFILE___LANG_ID as LANG_ID", \
	"JNR_SITE_PROFILE___REF_FIELD1 as REF_FIELD1", \
	"JNR_SITE_PROFILE___REF_FIELD2 as REF_FIELD2", \
	"JNR_SITE_PROFILE___REF_FIELD3 as REF_FIELD3", \
	"JNR_SITE_PROFILE___REF_FIELD4 as REF_FIELD4", \
	"JNR_SITE_PROFILE___REF_FIELD5 as REF_FIELD5", \
	"JNR_SITE_PROFILE___REF_NUM1 as REF_NUM1", \
	"JNR_SITE_PROFILE___REF_NUM2 as REF_NUM2", \
	"JNR_SITE_PROFILE___REF_NUM3 as REF_NUM3", \
	"JNR_SITE_PROFILE___REF_NUM4 as REF_NUM4", \
	"JNR_SITE_PROFILE___REF_NUM5 as REF_NUM5", \
	"JNR_SITE_PROFILE___MARK_FOR_DELETION as MARK_FOR_DELETION", \
	"JNR_SITE_PROFILE___CREATED_SOURCE_TYPE as CREATED_SOURCE_TYPE", \
	"JNR_SITE_PROFILE___CREATED_SOURCE as CREATED_SOURCE", \
	"JNR_SITE_PROFILE___CREATED_DTTM as CREATED_DTTM", \
	"JNR_SITE_PROFILE___LAST_UPDATED_SOURCE_TYPE as LAST_UPDATED_SOURCE_TYPE", \
	"JNR_SITE_PROFILE___LAST_UPDATED_SOURCE as LAST_UPDATED_SOURCE", \
	"JNR_SITE_PROFILE___LAST_UPDATED_DTTM as LAST_UPDATED_DTTM", \
	"JNR_SITE_PROFILE___LOCATION_ID as LOCATION_ID", \
	"SQ_Shortcut_to_WM_CARRIER_CODE___LOCATION_ID as in_LOCATION_ID", \
	"SQ_Shortcut_to_WM_CARRIER_CODE___WM_CARRIER_ID as WM_CARRIER_ID", \
	"SQ_Shortcut_to_WM_CARRIER_CODE___WM_CARRIER_CD as WM_CARRIER_CD", \
	"SQ_Shortcut_to_WM_CARRIER_CODE___WM_CARRIER_CD_NAME as WM_CARRIER_CD_NAME", \
	"SQ_Shortcut_to_WM_CARRIER_CODE___WM_CARRIER_CD_STATUS as WM_CARRIER_CD_STATUS", \
	"SQ_Shortcut_to_WM_CARRIER_CODE___WM_TC_COMPANY_ID as WM_TC_COMPANY_ID", \
	"SQ_Shortcut_to_WM_CARRIER_CODE___WM_TP_COMPANY_ID as WM_TP_COMPANY_ID", \
	"SQ_Shortcut_to_WM_CARRIER_CODE___WM_TP_COMPANY_NAME as WM_TP_COMPANY_NAME", \
	"SQ_Shortcut_to_WM_CARRIER_CODE___ADDRESS as ADDRESS1", \
	"SQ_Shortcut_to_WM_CARRIER_CODE___CITY as CITY1", \
	"SQ_Shortcut_to_WM_CARRIER_CODE___STATE_PROV as STATE_PROV1", \
	"SQ_Shortcut_to_WM_CARRIER_CODE___POSTAL_CD as POSTAL_CD", \
	"SQ_Shortcut_to_WM_CARRIER_CODE___COUNTRY_CD as COUNTRY_CD", \
	"SQ_Shortcut_to_WM_CARRIER_CODE___CARRIER_ADDR_FOR_CL as CARRIER_ADDR_FOR_CL1", \
	"SQ_Shortcut_to_WM_CARRIER_CODE___WM_CARRIER_TYPE_ID as WM_CARRIER_TYPE_ID", \
	"SQ_Shortcut_to_WM_CARRIER_CODE___WM_EPI_CARRIER_CD as WM_EPI_CARRIER_CD", \
	"SQ_Shortcut_to_WM_CARRIER_CODE___WM_SCAC_CD as WM_SCAC_CD", \
	"SQ_Shortcut_to_WM_CARRIER_CODE___PAYMENT_METHOD as PAYMENT_METHOD1", \
	"SQ_Shortcut_to_WM_CARRIER_CODE___PAYMENT_REFERENCE_NBR as PAYMENT_REFERENCE_NBR", \
	"SQ_Shortcut_to_WM_CARRIER_CODE___PREPAY_FLAG as PREPAY_FLAG", \
	"SQ_Shortcut_to_WM_CARRIER_CODE___AUTO_CREATE_INVOICE_FLAG as AUTO_CREATE_INVOICE_FLAG", \
	"SQ_Shortcut_to_WM_CARRIER_CODE___INVOICE_PAYMENT_TERMS as INVOICE_PAYMENT_TERMS1", \
	"SQ_Shortcut_to_WM_CARRIER_CODE___VALIDATE_INVOICE as VALIDATE_INVOICE1", \
	"SQ_Shortcut_to_WM_CARRIER_CODE___MATCH_PAY_EMAIL as MATCH_PAY_EMAIL1", \
	"SQ_Shortcut_to_WM_CARRIER_CODE___PAYEE_FLAG as PAYEE_FLAG", \
	"SQ_Shortcut_to_WM_CARRIER_CODE___WM_TARIFF_ID as WM_TARIFF_ID", \
	"SQ_Shortcut_to_WM_CARRIER_CODE___WM_TAX_ID as WM_TAX_ID", \
	"SQ_Shortcut_to_WM_CARRIER_CODE___HAZMAT_FLAG as HAZMAT_FLAG", \
	"SQ_Shortcut_to_WM_CARRIER_CODE___HAZMAT_REG_NBR as HAZMAT_REG_NBR1", \
	"SQ_Shortcut_to_WM_CARRIER_CODE___EXPIRY_DT as EXPIRY_DT", \
	"SQ_Shortcut_to_WM_CARRIER_CODE___DAYS_TO_DISPUTE_CLAIM as DAYS_TO_DISPUTE_CLAIM1", \
	"SQ_Shortcut_to_WM_CARRIER_CODE___COMM_METHOD as COMM_METHOD1", \
	"SQ_Shortcut_to_WM_CARRIER_CODE___MOTOR_CARRIER_NBR as MOTOR_CARRIER_NBR1", \
	"SQ_Shortcut_to_WM_CARRIER_CODE___FREIGHT_FRWRDR_NBR as FREIGHT_FRWRDR_NBR1", \
	"SQ_Shortcut_to_WM_CARRIER_CODE___PRO_NBR_LEVEL as PRO_NBR_LEVEL", \
	"SQ_Shortcut_to_WM_CARRIER_CODE___DEFAULT_PALLET_TYPE as DEFAULT_PALLET_TYPE1", \
	"SQ_Shortcut_to_WM_CARRIER_CODE___AWB_UOM as AWB_UOM1", \
	"SQ_Shortcut_to_WM_CARRIER_CODE___TRANS_EXCEL as TRANS_EXCEL1", \
	"SQ_Shortcut_to_WM_CARRIER_CODE___DOT_NBR as DOT_NBR", \
	"SQ_Shortcut_to_WM_CARRIER_CODE___BENCHMARK_FLAG as BENCHMARK_FLAG", \
	"SQ_Shortcut_to_WM_CARRIER_CODE___UNION_FLAG as UNION_FLAG", \
	"SQ_Shortcut_to_WM_CARRIER_CODE___AUTO_DELIVER_FLAG as AUTO_DELIVER_FLAG", \
	"SQ_Shortcut_to_WM_CARRIER_CODE___AUTO_ACCEPT_TYPE as AUTO_ACCEPT_TYPE1", \
	"SQ_Shortcut_to_WM_CARRIER_CODE___ACCEPT_MSG_REQD_FLAG as ACCEPT_MSG_REQD_FLAG", \
	"SQ_Shortcut_to_WM_CARRIER_CODE___APPT_MSG_REQD_FLAG as APPT_MSG_REQD_FLAG", \
	"SQ_Shortcut_to_WM_CARRIER_CODE___DEPART_MSG_REQD_FLAG as DEPART_MSG_REQD_FLAG", \
	"SQ_Shortcut_to_WM_CARRIER_CODE___ARRIVE_MSG_REQD_FLAG as ARRIVE_MSG_REQD_FLAG", \
	"SQ_Shortcut_to_WM_CARRIER_CODE___CONFIRM_RECALL_REQD_FLAG as CONFIRM_RECALL_REQD_FLAG", \
	"SQ_Shortcut_to_WM_CARRIER_CODE___CONFIRM_UPDATE_REQD_FLAG as CONFIRM_UPDATE_REQD_FLAG", \
	"SQ_Shortcut_to_WM_CARRIER_CODE___BROKER_FLAG as BROKER_FLAG", \
	"SQ_Shortcut_to_WM_CARRIER_CODE___BROKER_RECEIVE_UPDATES_FLAG as BROKER_RECEIVE_UPDATES_FLAG", \
	"SQ_Shortcut_to_WM_CARRIER_CODE___ALLOW_BOL_ENTRY_FLAG as ALLOW_BOL_ENTRY_FLAG", \
	"SQ_Shortcut_to_WM_CARRIER_CODE___AUTO_DELIVER_DELAY_HOURS as AUTO_DELIVER_DELAY_HOURS1", \
	"SQ_Shortcut_to_WM_CARRIER_CODE___DOCK_SCHEDULE_PERMISSION as DOCK_SCHEDULE_PERMISSION1", \
	"SQ_Shortcut_to_WM_CARRIER_CODE___ALLOW_LOAD_COMPLETION_FLAG as ALLOW_LOAD_COMPLETION_FLAG", \
	"SQ_Shortcut_to_WM_CARRIER_CODE___RECEIVES_DOCK_INFO_FLAG as RECEIVES_DOCK_INFO_FLAG", \
	"SQ_Shortcut_to_WM_CARRIER_CODE___ALLOW_TRAILER_ENTRY_FLAG as ALLOW_TRAILER_ENTRY_FLAG", \
	"SQ_Shortcut_to_WM_CARRIER_CODE___ALLOW_TRACTOR_ENTRY_FLAG as ALLOW_TRACTOR_ENTRY_FLAG", \
	"SQ_Shortcut_to_WM_CARRIER_CODE___ALLOW_CARRIER_CHARGES_VIEW_FLAG as ALLOW_CARRIER_CHARGES_VIEW_FLAG", \
	"SQ_Shortcut_to_WM_CARRIER_CODE___SUPPORTS_PARCEL as SUPPORTS_PARCEL1", \
	"SQ_Shortcut_to_WM_CARRIER_CODE___RECEIVE_FACILITY_INFO_FLAG as RECEIVE_FACILITY_INFO_FLAG", \
	"SQ_Shortcut_to_WM_CARRIER_CODE___PRIVATE_FLEET_FLAG as PRIVATE_FLEET_FLAG", \
	"SQ_Shortcut_to_WM_CARRIER_CODE___PREFERRED_FLAG as PREFERRED_FLAG", \
	"SQ_Shortcut_to_WM_CARRIER_CODE___CUT_PARCEL_INVOICE_FLAG as CUT_PARCEL_INVOICE_FLAG", \
	"SQ_Shortcut_to_WM_CARRIER_CODE___USE_CARRIER_ADDR_FLAG as USE_CARRIER_ADDR_FLAG", \
	"SQ_Shortcut_to_WM_CARRIER_CODE___CLAIM_ON_DETENTION_APPROVAL as CLAIM_ON_DETENTION_APPROVAL1", \
	"SQ_Shortcut_to_WM_CARRIER_CODE___RES_BASED_COSTING_ALLOWED_FLAG as RES_BASED_COSTING_ALLOWED_FLAG", \
	"SQ_Shortcut_to_WM_CARRIER_CODE___ACTIVITY_BASED_COSTING_FLAG as ACTIVITY_BASED_COSTING_FLAG", \
	"SQ_Shortcut_to_WM_CARRIER_CODE___PCT_OVER_CAPACITY as PCT_OVER_CAPACITY1", \
	"SQ_Shortcut_to_WM_CARRIER_CODE___ALLOW_CARRIER_BOOKING_REF_FLAG as ALLOW_CARRIER_BOOKING_REF_FLAG", \
	"SQ_Shortcut_to_WM_CARRIER_CODE___ALLOW_FORWARDER_AWB_FLAG as ALLOW_FORWARDER_AWB_FLAG", \
	"SQ_Shortcut_to_WM_CARRIER_CODE___ALLOW_MASTER_AWB_FLAG as ALLOW_MASTER_AWB_FLAG", \
	"SQ_Shortcut_to_WM_CARRIER_CODE___MAX_FLEET_APPROVED_AMT as MAX_FLEET_APPROVED_AMT", \
	"SQ_Shortcut_to_WM_CARRIER_CODE___CHECK_NON_MACHINABLE_FLAG as CHECK_NON_MACHINABLE_FLAG", \
	"SQ_Shortcut_to_WM_CARRIER_CODE___INV_ON_CARR_SIZES_FLAG as INV_ON_CARR_SIZES_FLAG", \
	"SQ_Shortcut_to_WM_CARRIER_CODE___PRO_NUMBER_REQD_FLAG as PRO_NUMBER_REQD_FLAG", \
	"SQ_Shortcut_to_WM_CARRIER_CODE___ALLOW_TENDER_REJECT_FLAG as ALLOW_TENDER_REJECT_FLAG", \
	"SQ_Shortcut_to_WM_CARRIER_CODE___ALLOW_COUNTER_OFFER_FLAG as ALLOW_COUNTER_OFFER_FLAG", \
	"SQ_Shortcut_to_WM_CARRIER_CODE___DEPART_MSG_REQD_AT_FIRST_STOP_FLAG as DEPART_MSG_REQD_AT_FIRST_STOP_FLAG", \
	"SQ_Shortcut_to_WM_CARRIER_CODE___EPI_SUPPORTS_HOLD_PROCESS_FLAG as EPI_SUPPORTS_HOLD_PROCESS_FLAG", \
	"SQ_Shortcut_to_WM_CARRIER_CODE___EPI_SUPPORTS_EOD_FLAG as EPI_SUPPORTS_EOD_FLAG", \
	"SQ_Shortcut_to_WM_CARRIER_CODE___LOAD_PRO_NEXT_UP_COUNTER as LOAD_PRO_NEXT_UP_COUNTER1", \
	"SQ_Shortcut_to_WM_CARRIER_CODE___STOP_PRO_NEXT_UP_COUNTER as STOP_PRO_NEXT_UP_COUNTER1", \
	"SQ_Shortcut_to_WM_CARRIER_CODE___MOBILE_SHIP_TRACK_FLAG as MOBILE_SHIP_TRACK_FLAG", \
	"SQ_Shortcut_to_WM_CARRIER_CODE___WM_LANGUAGE_ID as WM_LANGUAGE_ID", \
	"SQ_Shortcut_to_WM_CARRIER_CODE___REF_FIELD_1 as REF_FIELD_1", \
	"SQ_Shortcut_to_WM_CARRIER_CODE___REF_FIELD_2 as REF_FIELD_2", \
	"SQ_Shortcut_to_WM_CARRIER_CODE___REF_FIELD_3 as REF_FIELD_3", \
	"SQ_Shortcut_to_WM_CARRIER_CODE___REF_FIELD_4 as REF_FIELD_4", \
	"SQ_Shortcut_to_WM_CARRIER_CODE___REF_FIELD_5 as REF_FIELD_5", \
	"SQ_Shortcut_to_WM_CARRIER_CODE___REF_NUM_1 as REF_NUM_1", \
	"SQ_Shortcut_to_WM_CARRIER_CODE___REF_NUM_2 as REF_NUM_2", \
	"SQ_Shortcut_to_WM_CARRIER_CODE___REF_NUM_3 as REF_NUM_3", \
	"SQ_Shortcut_to_WM_CARRIER_CODE___REF_NUM_4 as REF_NUM_4", \
	"SQ_Shortcut_to_WM_CARRIER_CODE___REF_NUM_5 as REF_NUM_5", \
	"SQ_Shortcut_to_WM_CARRIER_CODE___MARK_FOR_DELETION_FLAG as MARK_FOR_DELETION_FLAG", \
	"SQ_Shortcut_to_WM_CARRIER_CODE___WM_CREATED_SOURCE_TYPE as WM_CREATED_SOURCE_TYPE", \
	"SQ_Shortcut_to_WM_CARRIER_CODE___WM_CREATED_SOURCE as WM_CREATED_SOURCE", \
	"SQ_Shortcut_to_WM_CARRIER_CODE___WM_CREATED_TSTMP as WM_CREATED_TSTMP", \
	"SQ_Shortcut_to_WM_CARRIER_CODE___WM_LAST_UPDATED_SOURCE_TYPE as WM_LAST_UPDATED_SOURCE_TYPE", \
	"SQ_Shortcut_to_WM_CARRIER_CODE___WM_LAST_UPDATED_SOURCE as WM_LAST_UPDATED_SOURCE", \
	"SQ_Shortcut_to_WM_CARRIER_CODE___WM_LAST_UPDATED_TSTMP as WM_LAST_UPDATED_TSTMP", \
	"SQ_Shortcut_to_WM_CARRIER_CODE___LOAD_TSTMP as in_LOAD_TSTMP")

# COMMAND ----------
# Processing node FIL_UNCHANGED_REC, type FILTER 
# COLUMN COUNT: 205

# for each involved DataFrame, append the dataframe name to each column
JNR_WM_CARRIER_CODE_temp = JNR_WM_CARRIER_CODE.toDF(*["JNR_WM_CARRIER_CODE___" + col for col in JNR_WM_CARRIER_CODE.columns])

FIL_UNCHANGED_REC = JNR_WM_CARRIER_CODE_temp.selectExpr( \
	"JNR_WM_CARRIER_CODE___CARRIER_ID as CARRIER_ID", \
	"JNR_WM_CARRIER_CODE___CARRIER_CODE as CARRIER_CODE", \
	"JNR_WM_CARRIER_CODE___CARRIER_CODE_NAME as CARRIER_CODE_NAME", \
	"JNR_WM_CARRIER_CODE___CARRIER_CODE_STATUS as CARRIER_CODE_STATUS", \
	"JNR_WM_CARRIER_CODE___TC_COMPANY_ID as TC_COMPANY_ID", \
	"JNR_WM_CARRIER_CODE___TP_COMPANY_ID as TP_COMPANY_ID", \
	"JNR_WM_CARRIER_CODE___TP_COMPANY_NAME as TP_COMPANY_NAME", \
	"JNR_WM_CARRIER_CODE___ADDRESS as ADDRESS", \
	"JNR_WM_CARRIER_CODE___CITY as CITY", \
	"JNR_WM_CARRIER_CODE___STATE_PROV as STATE_PROV", \
	"JNR_WM_CARRIER_CODE___POSTAL_CODE as POSTAL_CODE", \
	"JNR_WM_CARRIER_CODE___COUNTRY_CODE as COUNTRY_CODE", \
	"JNR_WM_CARRIER_CODE___CARRIER_ADDR_FOR_CL as CARRIER_ADDR_FOR_CL", \
	"JNR_WM_CARRIER_CODE___CARRIER_TYPE_ID as CARRIER_TYPE_ID", \
	"JNR_WM_CARRIER_CODE___EPI_CARRIER_CODE as EPI_CARRIER_CODE", \
	"JNR_WM_CARRIER_CODE___SCAC_CODE as SCAC_CODE", \
	"JNR_WM_CARRIER_CODE___PAYMENT_METHOD as PAYMENT_METHOD", \
	"JNR_WM_CARRIER_CODE___PAYMENT_REFERENCE_NUMBER as PAYMENT_REFERENCE_NUMBER", \
	"JNR_WM_CARRIER_CODE___IS_PREPAY as IS_PREPAY", \
	"JNR_WM_CARRIER_CODE___IS_AUTO_CREATE_INVOICE as IS_AUTO_CREATE_INVOICE", \
	"JNR_WM_CARRIER_CODE___INVOICE_PAYMENT_TERMS as INVOICE_PAYMENT_TERMS", \
	"JNR_WM_CARRIER_CODE___VALIDATE_INVOICE as VALIDATE_INVOICE", \
	"JNR_WM_CARRIER_CODE___MATCH_PAY_EMAIL as MATCH_PAY_EMAIL", \
	"JNR_WM_CARRIER_CODE___IS_PAYEE as IS_PAYEE", \
	"JNR_WM_CARRIER_CODE___TARIFF_ID as TARIFF_ID", \
	"JNR_WM_CARRIER_CODE___TAX_ID as TAX_ID", \
	"JNR_WM_CARRIER_CODE___HAS_HAZMAT as HAS_HAZMAT", \
	"JNR_WM_CARRIER_CODE___HAZMAT_REG_NBR as HAZMAT_REG_NBR", \
	"JNR_WM_CARRIER_CODE___EXPIRY_DATE as EXPIRY_DATE", \
	"JNR_WM_CARRIER_CODE___DAYS_TO_DISPUTE_CLAIM as DAYS_TO_DISPUTE_CLAIM", \
	"JNR_WM_CARRIER_CODE___COMM_METHOD as COMM_METHOD", \
	"JNR_WM_CARRIER_CODE___MOTOR_CARRIER_NBR as MOTOR_CARRIER_NBR", \
	"JNR_WM_CARRIER_CODE___FREIGHT_FRWRDR_NBR as FREIGHT_FRWRDR_NBR", \
	"JNR_WM_CARRIER_CODE___PRO_NUMBER_LEVEL as PRO_NUMBER_LEVEL", \
	"JNR_WM_CARRIER_CODE___DEFAULT_PALLET_TYPE as DEFAULT_PALLET_TYPE", \
	"JNR_WM_CARRIER_CODE___AWB_UOM as AWB_UOM", \
	"JNR_WM_CARRIER_CODE___TRANS_EXCEL as TRANS_EXCEL", \
	"JNR_WM_CARRIER_CODE___DOT_NUMBER as DOT_NUMBER", \
	"JNR_WM_CARRIER_CODE___IS_BENCHMARK as IS_BENCHMARK", \
	"JNR_WM_CARRIER_CODE___IS_UNION as IS_UNION", \
	"JNR_WM_CARRIER_CODE___IS_AUTO_DELIVER as IS_AUTO_DELIVER", \
	"JNR_WM_CARRIER_CODE___AUTO_ACCEPT_TYPE as AUTO_ACCEPT_TYPE", \
	"JNR_WM_CARRIER_CODE___ACCEPT_MSG_REQD as ACCEPT_MSG_REQD", \
	"JNR_WM_CARRIER_CODE___APPT_MSG_REQD as APPT_MSG_REQD", \
	"JNR_WM_CARRIER_CODE___DEPART_MSG_REQD as DEPART_MSG_REQD", \
	"JNR_WM_CARRIER_CODE___ARRIVE_MSG_REQD as ARRIVE_MSG_REQD", \
	"JNR_WM_CARRIER_CODE___CONFIRM_RECALL_REQD as CONFIRM_RECALL_REQD", \
	"JNR_WM_CARRIER_CODE___CONFIRM_UPDATE_REQD as CONFIRM_UPDATE_REQD", \
	"JNR_WM_CARRIER_CODE___IS_BROKER as IS_BROKER", \
	"JNR_WM_CARRIER_CODE___BROKER_RECEIVE_UPDATES as BROKER_RECEIVE_UPDATES", \
	"JNR_WM_CARRIER_CODE___ALLOW_BOL_ENTRY as ALLOW_BOL_ENTRY", \
	"JNR_WM_CARRIER_CODE___AUTO_DELIVER_DELAY_HOURS as AUTO_DELIVER_DELAY_HOURS", \
	"JNR_WM_CARRIER_CODE___DOCK_SCHEDULE_PERMISSION as DOCK_SCHEDULE_PERMISSION", \
	"JNR_WM_CARRIER_CODE___ALLOW_LOAD_COMPLETION as ALLOW_LOAD_COMPLETION", \
	"JNR_WM_CARRIER_CODE___RECEIVES_DOCK_INFO as RECEIVES_DOCK_INFO", \
	"JNR_WM_CARRIER_CODE___ALLOW_TRAILER_ENTRY as ALLOW_TRAILER_ENTRY", \
	"JNR_WM_CARRIER_CODE___ALLOW_TRACTOR_ENTRY as ALLOW_TRACTOR_ENTRY", \
	"JNR_WM_CARRIER_CODE___ALLOW_CARRIER_CHARGES_VIEW as ALLOW_CARRIER_CHARGES_VIEW", \
	"JNR_WM_CARRIER_CODE___SUPPORTS_PARCEL as SUPPORTS_PARCEL", \
	"JNR_WM_CARRIER_CODE___DOES_RECEIVE_FACILITY_INFO as DOES_RECEIVE_FACILITY_INFO", \
	"JNR_WM_CARRIER_CODE___IS_PRIVATE_FLEET as IS_PRIVATE_FLEET", \
	"JNR_WM_CARRIER_CODE___IS_PREFERRED as IS_PREFERRED", \
	"JNR_WM_CARRIER_CODE___CUT_PARCEL_INVOICE as CUT_PARCEL_INVOICE", \
	"JNR_WM_CARRIER_CODE___USE_CARRIER_ADDR as USE_CARRIER_ADDR", \
	"JNR_WM_CARRIER_CODE___CLAIM_ON_DETENTION_APPROVAL as CLAIM_ON_DETENTION_APPROVAL", \
	"JNR_WM_CARRIER_CODE___IS_RES_BASED_COSTING_ALLOWED as IS_RES_BASED_COSTING_ALLOWED", \
	"JNR_WM_CARRIER_CODE___IS_ACTIVITY_BASED_COSTING as IS_ACTIVITY_BASED_COSTING", \
	"JNR_WM_CARRIER_CODE___PCT_OVER_CAPACITY as PCT_OVER_CAPACITY", \
	"JNR_WM_CARRIER_CODE___ALLOW_CARRIER_BOOKING_REF as ALLOW_CARRIER_BOOKING_REF", \
	"JNR_WM_CARRIER_CODE___ALLOW_FORWARDER_AWB as ALLOW_FORWARDER_AWB", \
	"JNR_WM_CARRIER_CODE___ALLOW_MASTER_AWB as ALLOW_MASTER_AWB", \
	"JNR_WM_CARRIER_CODE___MAX_FLEET_APPROVED_AMOUNT as MAX_FLEET_APPROVED_AMOUNT", \
	"JNR_WM_CARRIER_CODE___CHECK_NON_MACHINABLE as CHECK_NON_MACHINABLE", \
	"JNR_WM_CARRIER_CODE___INV_ON_CARR_SIZES as INV_ON_CARR_SIZES", \
	"JNR_WM_CARRIER_CODE___PRO_NUMBER_REQD as PRO_NUMBER_REQD", \
	"JNR_WM_CARRIER_CODE___ALLOW_COUNTER_OFFER as ALLOW_COUNTER_OFFER", \
	"JNR_WM_CARRIER_CODE___ALLOW_TENDER_REJECT as ALLOW_TENDER_REJECT", \
	"JNR_WM_CARRIER_CODE___DEPART_MSG_REQD_AT_FIRST_STOP as DEPART_MSG_REQD_AT_FIRST_STOP", \
	"JNR_WM_CARRIER_CODE___EPI_SUPPORTS_HOLD_PROCESS as EPI_SUPPORTS_HOLD_PROCESS", \
	"JNR_WM_CARRIER_CODE___EPI_SUPPORTS_EOD as EPI_SUPPORTS_EOD", \
	"JNR_WM_CARRIER_CODE___LOAD_PRO_NEXT_UP_COUNTER as LOAD_PRO_NEXT_UP_COUNTER", \
	"JNR_WM_CARRIER_CODE___STOP_PRO_NEXT_UP_COUNTER as STOP_PRO_NEXT_UP_COUNTER", \
	"JNR_WM_CARRIER_CODE___MOBILE_SHIP_TRACK as MOBILE_SHIP_TRACK", \
	"JNR_WM_CARRIER_CODE___LANG_ID as LANG_ID", \
	"JNR_WM_CARRIER_CODE___REF_FIELD1 as REF_FIELD1", \
	"JNR_WM_CARRIER_CODE___REF_FIELD2 as REF_FIELD2", \
	"JNR_WM_CARRIER_CODE___REF_FIELD3 as REF_FIELD3", \
	"JNR_WM_CARRIER_CODE___REF_FIELD4 as REF_FIELD4", \
	"JNR_WM_CARRIER_CODE___REF_FIELD5 as REF_FIELD5", \
	"JNR_WM_CARRIER_CODE___REF_NUM1 as REF_NUM1", \
	"JNR_WM_CARRIER_CODE___REF_NUM2 as REF_NUM2", \
	"JNR_WM_CARRIER_CODE___REF_NUM3 as REF_NUM3", \
	"JNR_WM_CARRIER_CODE___REF_NUM4 as REF_NUM4", \
	"JNR_WM_CARRIER_CODE___REF_NUM5 as REF_NUM5", \
	"JNR_WM_CARRIER_CODE___MARK_FOR_DELETION as MARK_FOR_DELETION", \
	"JNR_WM_CARRIER_CODE___CREATED_SOURCE_TYPE as CREATED_SOURCE_TYPE", \
	"JNR_WM_CARRIER_CODE___CREATED_SOURCE as CREATED_SOURCE", \
	"JNR_WM_CARRIER_CODE___CREATED_DTTM as CREATED_DTTM", \
	"JNR_WM_CARRIER_CODE___LAST_UPDATED_SOURCE_TYPE as LAST_UPDATED_SOURCE_TYPE", \
	"JNR_WM_CARRIER_CODE___LAST_UPDATED_SOURCE as LAST_UPDATED_SOURCE", \
	"JNR_WM_CARRIER_CODE___LAST_UPDATED_DTTM as LAST_UPDATED_DTTM", \
	"JNR_WM_CARRIER_CODE___LOCATION_ID as LOCATION_ID", \
	"JNR_WM_CARRIER_CODE___in_LOCATION_ID as in_LOCATION_ID", \
	"JNR_WM_CARRIER_CODE___WM_CARRIER_ID as WM_CARRIER_ID", \
	"JNR_WM_CARRIER_CODE___WM_CARRIER_CD as WM_CARRIER_CD", \
	"JNR_WM_CARRIER_CODE___WM_CARRIER_CD_NAME as WM_CARRIER_CD_NAME", \
	"JNR_WM_CARRIER_CODE___WM_CARRIER_CD_STATUS as WM_CARRIER_CD_STATUS", \
	"JNR_WM_CARRIER_CODE___WM_TC_COMPANY_ID as WM_TC_COMPANY_ID", \
	"JNR_WM_CARRIER_CODE___WM_TP_COMPANY_ID as WM_TP_COMPANY_ID", \
	"JNR_WM_CARRIER_CODE___WM_TP_COMPANY_NAME as WM_TP_COMPANY_NAME", \
	"JNR_WM_CARRIER_CODE___ADDRESS1 as ADDRESS1", \
	"JNR_WM_CARRIER_CODE___CITY1 as CITY1", \
	"JNR_WM_CARRIER_CODE___STATE_PROV1 as STATE_PROV1", \
	"JNR_WM_CARRIER_CODE___POSTAL_CD as POSTAL_CD", \
	"JNR_WM_CARRIER_CODE___COUNTRY_CD as COUNTRY_CD", \
	"JNR_WM_CARRIER_CODE___CARRIER_ADDR_FOR_CL1 as CARRIER_ADDR_FOR_CL1", \
	"JNR_WM_CARRIER_CODE___WM_CARRIER_TYPE_ID as WM_CARRIER_TYPE_ID", \
	"JNR_WM_CARRIER_CODE___WM_EPI_CARRIER_CD as WM_EPI_CARRIER_CD", \
	"JNR_WM_CARRIER_CODE___WM_SCAC_CD as WM_SCAC_CD", \
	"JNR_WM_CARRIER_CODE___PAYMENT_METHOD1 as PAYMENT_METHOD1", \
	"JNR_WM_CARRIER_CODE___PAYMENT_REFERENCE_NBR as PAYMENT_REFERENCE_NBR", \
	"JNR_WM_CARRIER_CODE___PREPAY_FLAG as PREPAY_FLAG", \
	"JNR_WM_CARRIER_CODE___AUTO_CREATE_INVOICE_FLAG as AUTO_CREATE_INVOICE_FLAG", \
	"JNR_WM_CARRIER_CODE___INVOICE_PAYMENT_TERMS1 as INVOICE_PAYMENT_TERMS1", \
	"JNR_WM_CARRIER_CODE___VALIDATE_INVOICE1 as VALIDATE_INVOICE1", \
	"JNR_WM_CARRIER_CODE___MATCH_PAY_EMAIL1 as MATCH_PAY_EMAIL1", \
	"JNR_WM_CARRIER_CODE___PAYEE_FLAG as PAYEE_FLAG", \
	"JNR_WM_CARRIER_CODE___WM_TARIFF_ID as WM_TARIFF_ID", \
	"JNR_WM_CARRIER_CODE___WM_TAX_ID as WM_TAX_ID", \
	"JNR_WM_CARRIER_CODE___HAZMAT_FLAG as HAZMAT_FLAG", \
	"JNR_WM_CARRIER_CODE___HAZMAT_REG_NBR1 as HAZMAT_REG_NBR1", \
	"JNR_WM_CARRIER_CODE___EXPIRY_DT as EXPIRY_DT", \
	"JNR_WM_CARRIER_CODE___DAYS_TO_DISPUTE_CLAIM1 as DAYS_TO_DISPUTE_CLAIM1", \
	"JNR_WM_CARRIER_CODE___COMM_METHOD1 as COMM_METHOD1", \
	"JNR_WM_CARRIER_CODE___MOTOR_CARRIER_NBR1 as MOTOR_CARRIER_NBR1", \
	"JNR_WM_CARRIER_CODE___FREIGHT_FRWRDR_NBR1 as FREIGHT_FRWRDR_NBR1", \
	"JNR_WM_CARRIER_CODE___PRO_NBR_LEVEL as PRO_NBR_LEVEL", \
	"JNR_WM_CARRIER_CODE___DEFAULT_PALLET_TYPE1 as DEFAULT_PALLET_TYPE1", \
	"JNR_WM_CARRIER_CODE___AWB_UOM1 as AWB_UOM1", \
	"JNR_WM_CARRIER_CODE___TRANS_EXCEL1 as TRANS_EXCEL1", \
	"JNR_WM_CARRIER_CODE___DOT_NBR as DOT_NBR", \
	"JNR_WM_CARRIER_CODE___BENCHMARK_FLAG as BENCHMARK_FLAG", \
	"JNR_WM_CARRIER_CODE___UNION_FLAG as UNION_FLAG", \
	"JNR_WM_CARRIER_CODE___AUTO_DELIVER_FLAG as AUTO_DELIVER_FLAG", \
	"JNR_WM_CARRIER_CODE___AUTO_ACCEPT_TYPE1 as AUTO_ACCEPT_TYPE1", \
	"JNR_WM_CARRIER_CODE___ACCEPT_MSG_REQD_FLAG as ACCEPT_MSG_REQD_FLAG", \
	"JNR_WM_CARRIER_CODE___APPT_MSG_REQD_FLAG as APPT_MSG_REQD_FLAG", \
	"JNR_WM_CARRIER_CODE___DEPART_MSG_REQD_FLAG as DEPART_MSG_REQD_FLAG", \
	"JNR_WM_CARRIER_CODE___ARRIVE_MSG_REQD_FLAG as ARRIVE_MSG_REQD_FLAG", \
	"JNR_WM_CARRIER_CODE___CONFIRM_RECALL_REQD_FLAG as CONFIRM_RECALL_REQD_FLAG", \
	"JNR_WM_CARRIER_CODE___CONFIRM_UPDATE_REQD_FLAG as CONFIRM_UPDATE_REQD_FLAG", \
	"JNR_WM_CARRIER_CODE___BROKER_FLAG as BROKER_FLAG", \
	"JNR_WM_CARRIER_CODE___BROKER_RECEIVE_UPDATES_FLAG as BROKER_RECEIVE_UPDATES_FLAG", \
	"JNR_WM_CARRIER_CODE___ALLOW_BOL_ENTRY_FLAG as ALLOW_BOL_ENTRY_FLAG", \
	"JNR_WM_CARRIER_CODE___AUTO_DELIVER_DELAY_HOURS1 as AUTO_DELIVER_DELAY_HOURS1", \
	"JNR_WM_CARRIER_CODE___DOCK_SCHEDULE_PERMISSION1 as DOCK_SCHEDULE_PERMISSION1", \
	"JNR_WM_CARRIER_CODE___ALLOW_LOAD_COMPLETION_FLAG as ALLOW_LOAD_COMPLETION_FLAG", \
	"JNR_WM_CARRIER_CODE___RECEIVES_DOCK_INFO_FLAG as RECEIVES_DOCK_INFO_FLAG", \
	"JNR_WM_CARRIER_CODE___ALLOW_TRAILER_ENTRY_FLAG as ALLOW_TRAILER_ENTRY_FLAG", \
	"JNR_WM_CARRIER_CODE___ALLOW_TRACTOR_ENTRY_FLAG as ALLOW_TRACTOR_ENTRY_FLAG", \
	"JNR_WM_CARRIER_CODE___ALLOW_CARRIER_CHARGES_VIEW_FLAG as ALLOW_CARRIER_CHARGES_VIEW_FLAG", \
	"JNR_WM_CARRIER_CODE___SUPPORTS_PARCEL1 as SUPPORTS_PARCEL1", \
	"JNR_WM_CARRIER_CODE___RECEIVE_FACILITY_INFO_FLAG as RECEIVE_FACILITY_INFO_FLAG", \
	"JNR_WM_CARRIER_CODE___PRIVATE_FLEET_FLAG as PRIVATE_FLEET_FLAG", \
	"JNR_WM_CARRIER_CODE___PREFERRED_FLAG as PREFERRED_FLAG", \
	"JNR_WM_CARRIER_CODE___CUT_PARCEL_INVOICE_FLAG as CUT_PARCEL_INVOICE_FLAG", \
	"JNR_WM_CARRIER_CODE___USE_CARRIER_ADDR_FLAG as USE_CARRIER_ADDR_FLAG", \
	"JNR_WM_CARRIER_CODE___CLAIM_ON_DETENTION_APPROVAL1 as CLAIM_ON_DETENTION_APPROVAL1", \
	"JNR_WM_CARRIER_CODE___RES_BASED_COSTING_ALLOWED_FLAG as RES_BASED_COSTING_ALLOWED_FLAG", \
	"JNR_WM_CARRIER_CODE___ACTIVITY_BASED_COSTING_FLAG as ACTIVITY_BASED_COSTING_FLAG", \
	"JNR_WM_CARRIER_CODE___PCT_OVER_CAPACITY1 as PCT_OVER_CAPACITY1", \
	"JNR_WM_CARRIER_CODE___ALLOW_CARRIER_BOOKING_REF_FLAG as ALLOW_CARRIER_BOOKING_REF_FLAG", \
	"JNR_WM_CARRIER_CODE___ALLOW_FORWARDER_AWB_FLAG as ALLOW_FORWARDER_AWB_FLAG", \
	"JNR_WM_CARRIER_CODE___ALLOW_MASTER_AWB_FLAG as ALLOW_MASTER_AWB_FLAG", \
	"JNR_WM_CARRIER_CODE___MAX_FLEET_APPROVED_AMT as MAX_FLEET_APPROVED_AMT", \
	"JNR_WM_CARRIER_CODE___CHECK_NON_MACHINABLE_FLAG as CHECK_NON_MACHINABLE_FLAG", \
	"JNR_WM_CARRIER_CODE___INV_ON_CARR_SIZES_FLAG as INV_ON_CARR_SIZES_FLAG", \
	"JNR_WM_CARRIER_CODE___PRO_NUMBER_REQD_FLAG as PRO_NUMBER_REQD_FLAG", \
	"JNR_WM_CARRIER_CODE___ALLOW_TENDER_REJECT_FLAG as ALLOW_TENDER_REJECT_FLAG", \
	"JNR_WM_CARRIER_CODE___ALLOW_COUNTER_OFFER_FLAG as ALLOW_COUNTER_OFFER_FLAG", \
	"JNR_WM_CARRIER_CODE___DEPART_MSG_REQD_AT_FIRST_STOP_FLAG as DEPART_MSG_REQD_AT_FIRST_STOP_FLAG", \
	"JNR_WM_CARRIER_CODE___EPI_SUPPORTS_HOLD_PROCESS_FLAG as EPI_SUPPORTS_HOLD_PROCESS_FLAG", \
	"JNR_WM_CARRIER_CODE___EPI_SUPPORTS_EOD_FLAG as EPI_SUPPORTS_EOD_FLAG", \
	"JNR_WM_CARRIER_CODE___LOAD_PRO_NEXT_UP_COUNTER1 as LOAD_PRO_NEXT_UP_COUNTER1", \
	"JNR_WM_CARRIER_CODE___STOP_PRO_NEXT_UP_COUNTER1 as STOP_PRO_NEXT_UP_COUNTER1", \
	"JNR_WM_CARRIER_CODE___MOBILE_SHIP_TRACK_FLAG as MOBILE_SHIP_TRACK_FLAG", \
	"JNR_WM_CARRIER_CODE___WM_LANGUAGE_ID as WM_LANGUAGE_ID", \
	"JNR_WM_CARRIER_CODE___REF_FIELD_1 as REF_FIELD_1", \
	"JNR_WM_CARRIER_CODE___REF_FIELD_2 as REF_FIELD_2", \
	"JNR_WM_CARRIER_CODE___REF_FIELD_3 as REF_FIELD_3", \
	"JNR_WM_CARRIER_CODE___REF_FIELD_4 as REF_FIELD_4", \
	"JNR_WM_CARRIER_CODE___REF_FIELD_5 as REF_FIELD_5", \
	"JNR_WM_CARRIER_CODE___REF_NUM_1 as REF_NUM_1", \
	"JNR_WM_CARRIER_CODE___REF_NUM_2 as REF_NUM_2", \
	"JNR_WM_CARRIER_CODE___REF_NUM_3 as REF_NUM_3", \
	"JNR_WM_CARRIER_CODE___REF_NUM_4 as REF_NUM_4", \
	"JNR_WM_CARRIER_CODE___REF_NUM_5 as REF_NUM_5", \
	"JNR_WM_CARRIER_CODE___MARK_FOR_DELETION_FLAG as MARK_FOR_DELETION_FLAG", \
	"JNR_WM_CARRIER_CODE___WM_CREATED_SOURCE_TYPE as WM_CREATED_SOURCE_TYPE", \
	"JNR_WM_CARRIER_CODE___WM_CREATED_SOURCE as WM_CREATED_SOURCE", \
	"JNR_WM_CARRIER_CODE___WM_CREATED_TSTMP as WM_CREATED_TSTMP", \
	"JNR_WM_CARRIER_CODE___WM_LAST_UPDATED_SOURCE_TYPE as WM_LAST_UPDATED_SOURCE_TYPE", \
	"JNR_WM_CARRIER_CODE___WM_LAST_UPDATED_SOURCE as WM_LAST_UPDATED_SOURCE", \
	"JNR_WM_CARRIER_CODE___WM_LAST_UPDATED_TSTMP as WM_LAST_UPDATED_TSTMP", \
	"JNR_WM_CARRIER_CODE___in_LOAD_TSTMP as in_LOAD_TSTMP") \
    .filter("WM_CARRIER_ID is Null OR (  WM_CARRIER_ID is not Null AND \
             ( COALESCE(CREATED_DTTM, date'1900-01-01') != COALESCE(WM_CREATED_TSTMP, date'1900-01-01') \
             OR COALESCE(LAST_UPDATED_DTTM, date'1900-01-01') != COALESCE(WM_LAST_UPDATED_TSTMP, date'1900-01-01')))").withColumn("sys_row_id", monotonically_increasing_id())


# COMMAND ----------
# Processing node EXP_UPD_VALIDATOR, type EXPRESSION 
# COLUMN COUNT: 208

# for each involved DataFrame, append the dataframe name to each column
FIL_UNCHANGED_REC_temp = FIL_UNCHANGED_REC.toDF(*["FIL_UNCHANGED_REC___" + col for col in FIL_UNCHANGED_REC.columns])

EXP_UPD_VALIDATOR = FIL_UNCHANGED_REC_temp.selectExpr( \
	"FIL_UNCHANGED_REC___sys_row_id as sys_row_id", \
	"FIL_UNCHANGED_REC___CARRIER_ID as CARRIER_ID", \
	"FIL_UNCHANGED_REC___CARRIER_CODE as CARRIER_CODE", \
	"FIL_UNCHANGED_REC___CARRIER_CODE_NAME as CARRIER_CODE_NAME", \
	"FIL_UNCHANGED_REC___CARRIER_CODE_STATUS as CARRIER_CODE_STATUS", \
	"FIL_UNCHANGED_REC___TC_COMPANY_ID as TC_COMPANY_ID", \
	"FIL_UNCHANGED_REC___TP_COMPANY_ID as TP_COMPANY_ID", \
	"FIL_UNCHANGED_REC___TP_COMPANY_NAME as TP_COMPANY_NAME", \
	"FIL_UNCHANGED_REC___ADDRESS as ADDRESS", \
	"FIL_UNCHANGED_REC___CITY as CITY", \
	"FIL_UNCHANGED_REC___STATE_PROV as STATE_PROV", \
	"FIL_UNCHANGED_REC___POSTAL_CODE as POSTAL_CODE", \
	"FIL_UNCHANGED_REC___COUNTRY_CODE as COUNTRY_CODE", \
	"FIL_UNCHANGED_REC___CARRIER_ADDR_FOR_CL as CARRIER_ADDR_FOR_CL", \
	"FIL_UNCHANGED_REC___CARRIER_TYPE_ID as CARRIER_TYPE_ID", \
	"FIL_UNCHANGED_REC___EPI_CARRIER_CODE as EPI_CARRIER_CODE", \
	"FIL_UNCHANGED_REC___SCAC_CODE as SCAC_CODE", \
	"FIL_UNCHANGED_REC___PAYMENT_METHOD as PAYMENT_METHOD", \
	"FIL_UNCHANGED_REC___PAYMENT_REFERENCE_NUMBER as PAYMENT_REFERENCE_NUMBER", \
	"FIL_UNCHANGED_REC___IS_PREPAY as IS_PREPAY", \
	"FIL_UNCHANGED_REC___IS_AUTO_CREATE_INVOICE as IS_AUTO_CREATE_INVOICE", \
	"FIL_UNCHANGED_REC___INVOICE_PAYMENT_TERMS as INVOICE_PAYMENT_TERMS", \
	"FIL_UNCHANGED_REC___VALIDATE_INVOICE as VALIDATE_INVOICE", \
	"FIL_UNCHANGED_REC___MATCH_PAY_EMAIL as MATCH_PAY_EMAIL", \
	"FIL_UNCHANGED_REC___IS_PAYEE as IS_PAYEE", \
	"FIL_UNCHANGED_REC___TARIFF_ID as TARIFF_ID", \
	"FIL_UNCHANGED_REC___TAX_ID as TAX_ID", \
	"FIL_UNCHANGED_REC___HAS_HAZMAT as HAS_HAZMAT", \
	"FIL_UNCHANGED_REC___HAZMAT_REG_NBR as HAZMAT_REG_NBR", \
	"FIL_UNCHANGED_REC___EXPIRY_DATE as EXPIRY_DATE", \
	"FIL_UNCHANGED_REC___DAYS_TO_DISPUTE_CLAIM as DAYS_TO_DISPUTE_CLAIM", \
	"FIL_UNCHANGED_REC___COMM_METHOD as COMM_METHOD", \
	"FIL_UNCHANGED_REC___MOTOR_CARRIER_NBR as MOTOR_CARRIER_NBR", \
	"FIL_UNCHANGED_REC___FREIGHT_FRWRDR_NBR as FREIGHT_FRWRDR_NBR", \
	"FIL_UNCHANGED_REC___PRO_NUMBER_LEVEL as PRO_NUMBER_LEVEL", \
	"FIL_UNCHANGED_REC___DEFAULT_PALLET_TYPE as DEFAULT_PALLET_TYPE", \
	"FIL_UNCHANGED_REC___AWB_UOM as AWB_UOM", \
	"FIL_UNCHANGED_REC___TRANS_EXCEL as TRANS_EXCEL", \
	"FIL_UNCHANGED_REC___DOT_NUMBER as DOT_NUMBER", \
	"FIL_UNCHANGED_REC___IS_BENCHMARK as IS_BENCHMARK", \
	"FIL_UNCHANGED_REC___IS_UNION as IS_UNION", \
	"FIL_UNCHANGED_REC___IS_AUTO_DELIVER as IS_AUTO_DELIVER", \
	"FIL_UNCHANGED_REC___AUTO_ACCEPT_TYPE as AUTO_ACCEPT_TYPE", \
	"FIL_UNCHANGED_REC___ACCEPT_MSG_REQD as ACCEPT_MSG_REQD", \
	"FIL_UNCHANGED_REC___APPT_MSG_REQD as APPT_MSG_REQD", \
	"FIL_UNCHANGED_REC___DEPART_MSG_REQD as DEPART_MSG_REQD", \
	"FIL_UNCHANGED_REC___ARRIVE_MSG_REQD as ARRIVE_MSG_REQD", \
	"FIL_UNCHANGED_REC___CONFIRM_RECALL_REQD as CONFIRM_RECALL_REQD", \
	"FIL_UNCHANGED_REC___CONFIRM_UPDATE_REQD as CONFIRM_UPDATE_REQD", \
	"FIL_UNCHANGED_REC___IS_BROKER as IS_BROKER", \
	"FIL_UNCHANGED_REC___BROKER_RECEIVE_UPDATES as BROKER_RECEIVE_UPDATES", \
	"FIL_UNCHANGED_REC___ALLOW_BOL_ENTRY as ALLOW_BOL_ENTRY", \
	"FIL_UNCHANGED_REC___AUTO_DELIVER_DELAY_HOURS as AUTO_DELIVER_DELAY_HOURS", \
	"FIL_UNCHANGED_REC___DOCK_SCHEDULE_PERMISSION as DOCK_SCHEDULE_PERMISSION", \
	"FIL_UNCHANGED_REC___ALLOW_LOAD_COMPLETION as ALLOW_LOAD_COMPLETION", \
	"FIL_UNCHANGED_REC___RECEIVES_DOCK_INFO as RECEIVES_DOCK_INFO", \
	"FIL_UNCHANGED_REC___ALLOW_TRAILER_ENTRY as ALLOW_TRAILER_ENTRY", \
	"FIL_UNCHANGED_REC___ALLOW_TRACTOR_ENTRY as ALLOW_TRACTOR_ENTRY", \
	"FIL_UNCHANGED_REC___ALLOW_CARRIER_CHARGES_VIEW as ALLOW_CARRIER_CHARGES_VIEW", \
	"FIL_UNCHANGED_REC___SUPPORTS_PARCEL as SUPPORTS_PARCEL", \
	"FIL_UNCHANGED_REC___DOES_RECEIVE_FACILITY_INFO as DOES_RECEIVE_FACILITY_INFO", \
	"FIL_UNCHANGED_REC___IS_PRIVATE_FLEET as IS_PRIVATE_FLEET", \
	"FIL_UNCHANGED_REC___IS_PREFERRED as IS_PREFERRED", \
	"FIL_UNCHANGED_REC___CUT_PARCEL_INVOICE as CUT_PARCEL_INVOICE", \
	"FIL_UNCHANGED_REC___USE_CARRIER_ADDR as USE_CARRIER_ADDR", \
	"FIL_UNCHANGED_REC___CLAIM_ON_DETENTION_APPROVAL as CLAIM_ON_DETENTION_APPROVAL", \
	"FIL_UNCHANGED_REC___IS_RES_BASED_COSTING_ALLOWED as IS_RES_BASED_COSTING_ALLOWED", \
	"FIL_UNCHANGED_REC___IS_ACTIVITY_BASED_COSTING as IS_ACTIVITY_BASED_COSTING", \
	"FIL_UNCHANGED_REC___PCT_OVER_CAPACITY as PCT_OVER_CAPACITY", \
	"FIL_UNCHANGED_REC___ALLOW_CARRIER_BOOKING_REF as ALLOW_CARRIER_BOOKING_REF", \
	"FIL_UNCHANGED_REC___ALLOW_FORWARDER_AWB as ALLOW_FORWARDER_AWB", \
	"FIL_UNCHANGED_REC___ALLOW_MASTER_AWB as ALLOW_MASTER_AWB", \
	"FIL_UNCHANGED_REC___MAX_FLEET_APPROVED_AMOUNT as MAX_FLEET_APPROVED_AMOUNT", \
	"FIL_UNCHANGED_REC___CHECK_NON_MACHINABLE as CHECK_NON_MACHINABLE", \
	"FIL_UNCHANGED_REC___INV_ON_CARR_SIZES as INV_ON_CARR_SIZES", \
	"FIL_UNCHANGED_REC___PRO_NUMBER_REQD as PRO_NUMBER_REQD", \
	"FIL_UNCHANGED_REC___ALLOW_COUNTER_OFFER as ALLOW_COUNTER_OFFER", \
	"FIL_UNCHANGED_REC___ALLOW_TENDER_REJECT as ALLOW_TENDER_REJECT", \
	"FIL_UNCHANGED_REC___DEPART_MSG_REQD_AT_FIRST_STOP as DEPART_MSG_REQD_AT_FIRST_STOP", \
	"FIL_UNCHANGED_REC___EPI_SUPPORTS_HOLD_PROCESS as EPI_SUPPORTS_HOLD_PROCESS", \
	"FIL_UNCHANGED_REC___EPI_SUPPORTS_EOD as EPI_SUPPORTS_EOD", \
	"FIL_UNCHANGED_REC___LOAD_PRO_NEXT_UP_COUNTER as LOAD_PRO_NEXT_UP_COUNTER", \
	"FIL_UNCHANGED_REC___STOP_PRO_NEXT_UP_COUNTER as STOP_PRO_NEXT_UP_COUNTER", \
	"FIL_UNCHANGED_REC___MOBILE_SHIP_TRACK as MOBILE_SHIP_TRACK", \
	"FIL_UNCHANGED_REC___LANG_ID as LANG_ID", \
	"FIL_UNCHANGED_REC___REF_FIELD1 as REF_FIELD1", \
	"FIL_UNCHANGED_REC___REF_FIELD2 as REF_FIELD2", \
	"FIL_UNCHANGED_REC___REF_FIELD3 as REF_FIELD3", \
	"FIL_UNCHANGED_REC___REF_FIELD4 as REF_FIELD4", \
	"FIL_UNCHANGED_REC___REF_FIELD5 as REF_FIELD5", \
	"FIL_UNCHANGED_REC___REF_NUM1 as REF_NUM1", \
	"FIL_UNCHANGED_REC___REF_NUM2 as REF_NUM2", \
	"FIL_UNCHANGED_REC___REF_NUM3 as REF_NUM3", \
	"FIL_UNCHANGED_REC___REF_NUM4 as REF_NUM4", \
	"FIL_UNCHANGED_REC___REF_NUM5 as REF_NUM5", \
	"FIL_UNCHANGED_REC___MARK_FOR_DELETION as MARK_FOR_DELETION", \
	"FIL_UNCHANGED_REC___CREATED_SOURCE_TYPE as CREATED_SOURCE_TYPE", \
	"FIL_UNCHANGED_REC___CREATED_SOURCE as CREATED_SOURCE", \
	"FIL_UNCHANGED_REC___CREATED_DTTM as CREATED_DTTM", \
	"FIL_UNCHANGED_REC___LAST_UPDATED_SOURCE_TYPE as LAST_UPDATED_SOURCE_TYPE", \
	"FIL_UNCHANGED_REC___LAST_UPDATED_SOURCE as LAST_UPDATED_SOURCE", \
	"FIL_UNCHANGED_REC___LAST_UPDATED_DTTM as LAST_UPDATED_DTTM", \
	"FIL_UNCHANGED_REC___LOCATION_ID as LOCATION_ID", \
	"FIL_UNCHANGED_REC___in_LOCATION_ID as in_LOCATION_ID", \
	"FIL_UNCHANGED_REC___WM_CARRIER_ID as WM_CARRIER_ID", \
	"FIL_UNCHANGED_REC___WM_CARRIER_CD as WM_CARRIER_CD", \
	"FIL_UNCHANGED_REC___WM_CARRIER_CD_NAME as WM_CARRIER_CD_NAME", \
	"FIL_UNCHANGED_REC___WM_CARRIER_CD_STATUS as WM_CARRIER_CD_STATUS", \
	"FIL_UNCHANGED_REC___WM_TC_COMPANY_ID as WM_TC_COMPANY_ID", \
	"FIL_UNCHANGED_REC___WM_TP_COMPANY_ID as WM_TP_COMPANY_ID", \
	"FIL_UNCHANGED_REC___WM_TP_COMPANY_NAME as WM_TP_COMPANY_NAME", \
	"FIL_UNCHANGED_REC___ADDRESS1 as ADDRESS1", \
	"FIL_UNCHANGED_REC___CITY1 as CITY1", \
	"FIL_UNCHANGED_REC___STATE_PROV1 as STATE_PROV1", \
	"FIL_UNCHANGED_REC___POSTAL_CD as POSTAL_CD", \
	"FIL_UNCHANGED_REC___COUNTRY_CD as COUNTRY_CD", \
	"FIL_UNCHANGED_REC___CARRIER_ADDR_FOR_CL1 as CARRIER_ADDR_FOR_CL1", \
	"FIL_UNCHANGED_REC___WM_CARRIER_TYPE_ID as WM_CARRIER_TYPE_ID", \
	"FIL_UNCHANGED_REC___WM_EPI_CARRIER_CD as WM_EPI_CARRIER_CD", \
	"FIL_UNCHANGED_REC___WM_SCAC_CD as WM_SCAC_CD", \
	"FIL_UNCHANGED_REC___PAYMENT_METHOD1 as PAYMENT_METHOD1", \
	"FIL_UNCHANGED_REC___PAYMENT_REFERENCE_NBR as PAYMENT_REFERENCE_NBR", \
	"FIL_UNCHANGED_REC___PREPAY_FLAG as PREPAY_FLAG", \
	"FIL_UNCHANGED_REC___AUTO_CREATE_INVOICE_FLAG as AUTO_CREATE_INVOICE_FLAG", \
	"FIL_UNCHANGED_REC___INVOICE_PAYMENT_TERMS1 as INVOICE_PAYMENT_TERMS1", \
	"FIL_UNCHANGED_REC___VALIDATE_INVOICE1 as VALIDATE_INVOICE1", \
	"FIL_UNCHANGED_REC___MATCH_PAY_EMAIL1 as MATCH_PAY_EMAIL1", \
	"FIL_UNCHANGED_REC___PAYEE_FLAG as PAYEE_FLAG", \
	"FIL_UNCHANGED_REC___WM_TARIFF_ID as WM_TARIFF_ID", \
	"FIL_UNCHANGED_REC___WM_TAX_ID as WM_TAX_ID", \
	"FIL_UNCHANGED_REC___HAZMAT_FLAG as HAZMAT_FLAG", \
	"FIL_UNCHANGED_REC___HAZMAT_REG_NBR1 as HAZMAT_REG_NBR1", \
	"FIL_UNCHANGED_REC___EXPIRY_DT as EXPIRY_DT", \
	"FIL_UNCHANGED_REC___DAYS_TO_DISPUTE_CLAIM1 as DAYS_TO_DISPUTE_CLAIM1", \
	"FIL_UNCHANGED_REC___COMM_METHOD1 as COMM_METHOD1", \
	"FIL_UNCHANGED_REC___MOTOR_CARRIER_NBR1 as MOTOR_CARRIER_NBR1", \
	"FIL_UNCHANGED_REC___FREIGHT_FRWRDR_NBR1 as FREIGHT_FRWRDR_NBR1", \
	"FIL_UNCHANGED_REC___PRO_NBR_LEVEL as PRO_NBR_LEVEL", \
	"FIL_UNCHANGED_REC___DEFAULT_PALLET_TYPE1 as DEFAULT_PALLET_TYPE1", \
	"FIL_UNCHANGED_REC___AWB_UOM1 as AWB_UOM1", \
	"FIL_UNCHANGED_REC___TRANS_EXCEL1 as TRANS_EXCEL1", \
	"FIL_UNCHANGED_REC___DOT_NBR as DOT_NBR", \
	"FIL_UNCHANGED_REC___BENCHMARK_FLAG as BENCHMARK_FLAG", \
	"FIL_UNCHANGED_REC___UNION_FLAG as UNION_FLAG", \
	"FIL_UNCHANGED_REC___AUTO_DELIVER_FLAG as AUTO_DELIVER_FLAG", \
	"FIL_UNCHANGED_REC___AUTO_ACCEPT_TYPE1 as AUTO_ACCEPT_TYPE1", \
	"FIL_UNCHANGED_REC___ACCEPT_MSG_REQD_FLAG as ACCEPT_MSG_REQD_FLAG", \
	"FIL_UNCHANGED_REC___APPT_MSG_REQD_FLAG as APPT_MSG_REQD_FLAG", \
	"FIL_UNCHANGED_REC___DEPART_MSG_REQD_FLAG as DEPART_MSG_REQD_FLAG", \
	"FIL_UNCHANGED_REC___ARRIVE_MSG_REQD_FLAG as ARRIVE_MSG_REQD_FLAG", \
	"FIL_UNCHANGED_REC___CONFIRM_RECALL_REQD_FLAG as CONFIRM_RECALL_REQD_FLAG", \
	"FIL_UNCHANGED_REC___CONFIRM_UPDATE_REQD_FLAG as CONFIRM_UPDATE_REQD_FLAG", \
	"FIL_UNCHANGED_REC___BROKER_FLAG as BROKER_FLAG", \
	"FIL_UNCHANGED_REC___BROKER_RECEIVE_UPDATES_FLAG as BROKER_RECEIVE_UPDATES_FLAG", \
	"FIL_UNCHANGED_REC___ALLOW_BOL_ENTRY_FLAG as ALLOW_BOL_ENTRY_FLAG", \
	"FIL_UNCHANGED_REC___AUTO_DELIVER_DELAY_HOURS1 as AUTO_DELIVER_DELAY_HOURS1", \
	"FIL_UNCHANGED_REC___DOCK_SCHEDULE_PERMISSION1 as DOCK_SCHEDULE_PERMISSION1", \
	"FIL_UNCHANGED_REC___ALLOW_LOAD_COMPLETION_FLAG as ALLOW_LOAD_COMPLETION_FLAG", \
	"FIL_UNCHANGED_REC___RECEIVES_DOCK_INFO_FLAG as RECEIVES_DOCK_INFO_FLAG", \
	"FIL_UNCHANGED_REC___ALLOW_TRAILER_ENTRY_FLAG as ALLOW_TRAILER_ENTRY_FLAG", \
	"FIL_UNCHANGED_REC___ALLOW_TRACTOR_ENTRY_FLAG as ALLOW_TRACTOR_ENTRY_FLAG", \
	"FIL_UNCHANGED_REC___ALLOW_CARRIER_CHARGES_VIEW_FLAG as ALLOW_CARRIER_CHARGES_VIEW_FLAG", \
	"FIL_UNCHANGED_REC___SUPPORTS_PARCEL1 as SUPPORTS_PARCEL1", \
	"FIL_UNCHANGED_REC___RECEIVE_FACILITY_INFO_FLAG as RECEIVE_FACILITY_INFO_FLAG", \
	"FIL_UNCHANGED_REC___PRIVATE_FLEET_FLAG as PRIVATE_FLEET_FLAG", \
	"FIL_UNCHANGED_REC___PREFERRED_FLAG as PREFERRED_FLAG", \
	"FIL_UNCHANGED_REC___CUT_PARCEL_INVOICE_FLAG as CUT_PARCEL_INVOICE_FLAG", \
	"FIL_UNCHANGED_REC___USE_CARRIER_ADDR_FLAG as USE_CARRIER_ADDR_FLAG", \
	"FIL_UNCHANGED_REC___CLAIM_ON_DETENTION_APPROVAL1 as CLAIM_ON_DETENTION_APPROVAL1", \
	"FIL_UNCHANGED_REC___RES_BASED_COSTING_ALLOWED_FLAG as RES_BASED_COSTING_ALLOWED_FLAG", \
	"FIL_UNCHANGED_REC___ACTIVITY_BASED_COSTING_FLAG as ACTIVITY_BASED_COSTING_FLAG", \
	"FIL_UNCHANGED_REC___PCT_OVER_CAPACITY1 as PCT_OVER_CAPACITY1", \
	"FIL_UNCHANGED_REC___ALLOW_CARRIER_BOOKING_REF_FLAG as ALLOW_CARRIER_BOOKING_REF_FLAG", \
	"FIL_UNCHANGED_REC___ALLOW_FORWARDER_AWB_FLAG as ALLOW_FORWARDER_AWB_FLAG", \
	"FIL_UNCHANGED_REC___ALLOW_MASTER_AWB_FLAG as ALLOW_MASTER_AWB_FLAG", \
	"FIL_UNCHANGED_REC___MAX_FLEET_APPROVED_AMT as MAX_FLEET_APPROVED_AMT", \
	"FIL_UNCHANGED_REC___CHECK_NON_MACHINABLE_FLAG as CHECK_NON_MACHINABLE_FLAG", \
	"FIL_UNCHANGED_REC___INV_ON_CARR_SIZES_FLAG as INV_ON_CARR_SIZES_FLAG", \
	"FIL_UNCHANGED_REC___PRO_NUMBER_REQD_FLAG as PRO_NUMBER_REQD_FLAG", \
	"FIL_UNCHANGED_REC___ALLOW_TENDER_REJECT_FLAG as ALLOW_TENDER_REJECT_FLAG", \
	"FIL_UNCHANGED_REC___ALLOW_COUNTER_OFFER_FLAG as ALLOW_COUNTER_OFFER_FLAG", \
	"FIL_UNCHANGED_REC___DEPART_MSG_REQD_AT_FIRST_STOP_FLAG as DEPART_MSG_REQD_AT_FIRST_STOP_FLAG", \
	"FIL_UNCHANGED_REC___EPI_SUPPORTS_HOLD_PROCESS_FLAG as EPI_SUPPORTS_HOLD_PROCESS_FLAG", \
	"FIL_UNCHANGED_REC___EPI_SUPPORTS_EOD_FLAG as EPI_SUPPORTS_EOD_FLAG", \
	"FIL_UNCHANGED_REC___LOAD_PRO_NEXT_UP_COUNTER1 as LOAD_PRO_NEXT_UP_COUNTER1", \
	"FIL_UNCHANGED_REC___STOP_PRO_NEXT_UP_COUNTER1 as STOP_PRO_NEXT_UP_COUNTER1", \
	"FIL_UNCHANGED_REC___MOBILE_SHIP_TRACK_FLAG as MOBILE_SHIP_TRACK_FLAG", \
	"FIL_UNCHANGED_REC___WM_LANGUAGE_ID as WM_LANGUAGE_ID", \
	"FIL_UNCHANGED_REC___REF_FIELD_1 as REF_FIELD_1", \
	"FIL_UNCHANGED_REC___REF_FIELD_2 as REF_FIELD_2", \
	"FIL_UNCHANGED_REC___REF_FIELD_3 as REF_FIELD_3", \
	"FIL_UNCHANGED_REC___REF_FIELD_4 as REF_FIELD_4", \
	"FIL_UNCHANGED_REC___REF_FIELD_5 as REF_FIELD_5", \
	"FIL_UNCHANGED_REC___REF_NUM_1 as REF_NUM_1", \
	"FIL_UNCHANGED_REC___REF_NUM_2 as REF_NUM_2", \
	"FIL_UNCHANGED_REC___REF_NUM_3 as REF_NUM_3", \
	"FIL_UNCHANGED_REC___REF_NUM_4 as REF_NUM_4", \
	"FIL_UNCHANGED_REC___REF_NUM_5 as REF_NUM_5", \
	"FIL_UNCHANGED_REC___MARK_FOR_DELETION_FLAG as MARK_FOR_DELETION_FLAG", \
	"FIL_UNCHANGED_REC___WM_CREATED_SOURCE_TYPE as WM_CREATED_SOURCE_TYPE", \
	"FIL_UNCHANGED_REC___WM_CREATED_SOURCE as WM_CREATED_SOURCE", \
	"FIL_UNCHANGED_REC___WM_CREATED_TSTMP as WM_CREATED_TSTMP", \
	"FIL_UNCHANGED_REC___WM_LAST_UPDATED_SOURCE_TYPE as WM_LAST_UPDATED_SOURCE_TYPE", \
	"FIL_UNCHANGED_REC___WM_LAST_UPDATED_SOURCE as WM_LAST_UPDATED_SOURCE", \
	"FIL_UNCHANGED_REC___WM_LAST_UPDATED_TSTMP as WM_LAST_UPDATED_TSTMP", \
	"FIL_UNCHANGED_REC___in_LOAD_TSTMP as in_LOAD_TSTMP", \
	"CURRENT_TIMESTAMP() as UPDATE_TSTMP", \
	"IF(FIL_UNCHANGED_REC___in_LOAD_TSTMP IS NULL, CURRENT_TIMESTAMP(), FIL_UNCHANGED_REC___in_LOAD_TSTMP) as LOAD_TSTMP_exp", \
	"IF(FIL_UNCHANGED_REC___WM_CARRIER_ID IS NULL, 1, 2) as o_UPD_VALIDATOR" \
)

# COMMAND ----------
# Processing node UPD_INS_UPD, type UPDATE_STRATEGY 
# COLUMN COUNT: 208

# for each involved DataFrame, append the dataframe name to each column
EXP_UPD_VALIDATOR_temp = EXP_UPD_VALIDATOR.toDF(*["EXP_UPD_VALIDATOR___" + col for col in EXP_UPD_VALIDATOR.columns])

UPD_INS_UPD = EXP_UPD_VALIDATOR_temp.selectExpr( \
	"EXP_UPD_VALIDATOR___LOCATION_ID as LOCATION_ID", \
	"EXP_UPD_VALIDATOR___CARRIER_ID as CARRIER_ID", \
	"EXP_UPD_VALIDATOR___CARRIER_CODE as CARRIER_CODE", \
	"EXP_UPD_VALIDATOR___CARRIER_CODE_NAME as CARRIER_CODE_NAME", \
	"EXP_UPD_VALIDATOR___CARRIER_CODE_STATUS as CARRIER_CODE_STATUS", \
	"EXP_UPD_VALIDATOR___TC_COMPANY_ID as TC_COMPANY_ID", \
	"EXP_UPD_VALIDATOR___TP_COMPANY_ID as TP_COMPANY_ID", \
	"EXP_UPD_VALIDATOR___TP_COMPANY_NAME as TP_COMPANY_NAME", \
	"EXP_UPD_VALIDATOR___ADDRESS as ADDRESS", \
	"EXP_UPD_VALIDATOR___CITY as CITY", \
	"EXP_UPD_VALIDATOR___STATE_PROV as STATE_PROV", \
	"EXP_UPD_VALIDATOR___POSTAL_CODE as POSTAL_CODE", \
	"EXP_UPD_VALIDATOR___COUNTRY_CODE as COUNTRY_CODE", \
	"EXP_UPD_VALIDATOR___CARRIER_ADDR_FOR_CL as CARRIER_ADDR_FOR_CL", \
	"EXP_UPD_VALIDATOR___CARRIER_TYPE_ID as CARRIER_TYPE_ID", \
	"EXP_UPD_VALIDATOR___EPI_CARRIER_CODE as EPI_CARRIER_CODE", \
	"EXP_UPD_VALIDATOR___SCAC_CODE as SCAC_CODE", \
	"EXP_UPD_VALIDATOR___PAYMENT_METHOD as PAYMENT_METHOD", \
	"EXP_UPD_VALIDATOR___PAYMENT_REFERENCE_NUMBER as PAYMENT_REFERENCE_NUMBER", \
	"EXP_UPD_VALIDATOR___IS_PREPAY as IS_PREPAY", \
	"EXP_UPD_VALIDATOR___IS_AUTO_CREATE_INVOICE as IS_AUTO_CREATE_INVOICE", \
	"EXP_UPD_VALIDATOR___INVOICE_PAYMENT_TERMS as INVOICE_PAYMENT_TERMS", \
	"EXP_UPD_VALIDATOR___VALIDATE_INVOICE as VALIDATE_INVOICE", \
	"EXP_UPD_VALIDATOR___MATCH_PAY_EMAIL as MATCH_PAY_EMAIL", \
	"EXP_UPD_VALIDATOR___IS_PAYEE as IS_PAYEE", \
	"EXP_UPD_VALIDATOR___TARIFF_ID as TARIFF_ID", \
	"EXP_UPD_VALIDATOR___TAX_ID as TAX_ID", \
	"EXP_UPD_VALIDATOR___HAS_HAZMAT as HAS_HAZMAT", \
	"EXP_UPD_VALIDATOR___HAZMAT_REG_NBR as HAZMAT_REG_NBR", \
	"EXP_UPD_VALIDATOR___EXPIRY_DATE as EXPIRY_DATE", \
	"EXP_UPD_VALIDATOR___DAYS_TO_DISPUTE_CLAIM as DAYS_TO_DISPUTE_CLAIM", \
	"EXP_UPD_VALIDATOR___COMM_METHOD as COMM_METHOD", \
	"EXP_UPD_VALIDATOR___MOTOR_CARRIER_NBR as MOTOR_CARRIER_NBR", \
	"EXP_UPD_VALIDATOR___FREIGHT_FRWRDR_NBR as FREIGHT_FRWRDR_NBR", \
	"EXP_UPD_VALIDATOR___PRO_NUMBER_LEVEL as PRO_NUMBER_LEVEL", \
	"EXP_UPD_VALIDATOR___DEFAULT_PALLET_TYPE as DEFAULT_PALLET_TYPE", \
	"EXP_UPD_VALIDATOR___AWB_UOM as AWB_UOM", \
	"EXP_UPD_VALIDATOR___TRANS_EXCEL as TRANS_EXCEL", \
	"EXP_UPD_VALIDATOR___DOT_NUMBER as DOT_NUMBER", \
	"EXP_UPD_VALIDATOR___IS_BENCHMARK as IS_BENCHMARK", \
	"EXP_UPD_VALIDATOR___IS_UNION as IS_UNION", \
	"EXP_UPD_VALIDATOR___IS_AUTO_DELIVER as IS_AUTO_DELIVER", \
	"EXP_UPD_VALIDATOR___AUTO_ACCEPT_TYPE as AUTO_ACCEPT_TYPE", \
	"EXP_UPD_VALIDATOR___ACCEPT_MSG_REQD as ACCEPT_MSG_REQD", \
	"EXP_UPD_VALIDATOR___APPT_MSG_REQD as APPT_MSG_REQD", \
	"EXP_UPD_VALIDATOR___DEPART_MSG_REQD as DEPART_MSG_REQD", \
	"EXP_UPD_VALIDATOR___ARRIVE_MSG_REQD as ARRIVE_MSG_REQD", \
	"EXP_UPD_VALIDATOR___CONFIRM_RECALL_REQD as CONFIRM_RECALL_REQD", \
	"EXP_UPD_VALIDATOR___CONFIRM_UPDATE_REQD as CONFIRM_UPDATE_REQD", \
	"EXP_UPD_VALIDATOR___IS_BROKER as IS_BROKER", \
	"EXP_UPD_VALIDATOR___BROKER_RECEIVE_UPDATES as BROKER_RECEIVE_UPDATES", \
	"EXP_UPD_VALIDATOR___ALLOW_BOL_ENTRY as ALLOW_BOL_ENTRY", \
	"EXP_UPD_VALIDATOR___AUTO_DELIVER_DELAY_HOURS as AUTO_DELIVER_DELAY_HOURS", \
	"EXP_UPD_VALIDATOR___DOCK_SCHEDULE_PERMISSION as DOCK_SCHEDULE_PERMISSION", \
	"EXP_UPD_VALIDATOR___ALLOW_LOAD_COMPLETION as ALLOW_LOAD_COMPLETION", \
	"EXP_UPD_VALIDATOR___RECEIVES_DOCK_INFO as RECEIVES_DOCK_INFO", \
	"EXP_UPD_VALIDATOR___ALLOW_TRAILER_ENTRY as ALLOW_TRAILER_ENTRY", \
	"EXP_UPD_VALIDATOR___ALLOW_TRACTOR_ENTRY as ALLOW_TRACTOR_ENTRY", \
	"EXP_UPD_VALIDATOR___ALLOW_CARRIER_CHARGES_VIEW as ALLOW_CARRIER_CHARGES_VIEW", \
	"EXP_UPD_VALIDATOR___SUPPORTS_PARCEL as SUPPORTS_PARCEL", \
	"EXP_UPD_VALIDATOR___DOES_RECEIVE_FACILITY_INFO as DOES_RECEIVE_FACILITY_INFO", \
	"EXP_UPD_VALIDATOR___IS_PRIVATE_FLEET as IS_PRIVATE_FLEET", \
	"EXP_UPD_VALIDATOR___IS_PREFERRED as IS_PREFERRED", \
	"EXP_UPD_VALIDATOR___CUT_PARCEL_INVOICE as CUT_PARCEL_INVOICE", \
	"EXP_UPD_VALIDATOR___USE_CARRIER_ADDR as USE_CARRIER_ADDR", \
	"EXP_UPD_VALIDATOR___CLAIM_ON_DETENTION_APPROVAL as CLAIM_ON_DETENTION_APPROVAL", \
	"EXP_UPD_VALIDATOR___IS_RES_BASED_COSTING_ALLOWED as IS_RES_BASED_COSTING_ALLOWED", \
	"EXP_UPD_VALIDATOR___IS_ACTIVITY_BASED_COSTING as IS_ACTIVITY_BASED_COSTING", \
	"EXP_UPD_VALIDATOR___PCT_OVER_CAPACITY as PCT_OVER_CAPACITY", \
	"EXP_UPD_VALIDATOR___ALLOW_CARRIER_BOOKING_REF as ALLOW_CARRIER_BOOKING_REF", \
	"EXP_UPD_VALIDATOR___ALLOW_FORWARDER_AWB as ALLOW_FORWARDER_AWB", \
	"EXP_UPD_VALIDATOR___ALLOW_MASTER_AWB as ALLOW_MASTER_AWB", \
	"EXP_UPD_VALIDATOR___MAX_FLEET_APPROVED_AMOUNT as MAX_FLEET_APPROVED_AMOUNT", \
	"EXP_UPD_VALIDATOR___CHECK_NON_MACHINABLE as CHECK_NON_MACHINABLE", \
	"EXP_UPD_VALIDATOR___INV_ON_CARR_SIZES as INV_ON_CARR_SIZES", \
	"EXP_UPD_VALIDATOR___PRO_NUMBER_REQD as PRO_NUMBER_REQD", \
	"EXP_UPD_VALIDATOR___ALLOW_COUNTER_OFFER as ALLOW_COUNTER_OFFER", \
	"EXP_UPD_VALIDATOR___ALLOW_TENDER_REJECT as ALLOW_TENDER_REJECT", \
	"EXP_UPD_VALIDATOR___DEPART_MSG_REQD_AT_FIRST_STOP as DEPART_MSG_REQD_AT_FIRST_STOP", \
	"EXP_UPD_VALIDATOR___EPI_SUPPORTS_HOLD_PROCESS as EPI_SUPPORTS_HOLD_PROCESS", \
	"EXP_UPD_VALIDATOR___EPI_SUPPORTS_EOD as EPI_SUPPORTS_EOD", \
	"EXP_UPD_VALIDATOR___LOAD_PRO_NEXT_UP_COUNTER as LOAD_PRO_NEXT_UP_COUNTER", \
	"EXP_UPD_VALIDATOR___STOP_PRO_NEXT_UP_COUNTER as STOP_PRO_NEXT_UP_COUNTER", \
	"EXP_UPD_VALIDATOR___MOBILE_SHIP_TRACK as MOBILE_SHIP_TRACK", \
	"EXP_UPD_VALIDATOR___LANG_ID as LANG_ID", \
	"EXP_UPD_VALIDATOR___REF_FIELD1 as REF_FIELD1", \
	"EXP_UPD_VALIDATOR___REF_FIELD2 as REF_FIELD2", \
	"EXP_UPD_VALIDATOR___REF_FIELD3 as REF_FIELD3", \
	"EXP_UPD_VALIDATOR___REF_FIELD4 as REF_FIELD4", \
	"EXP_UPD_VALIDATOR___REF_FIELD5 as REF_FIELD5", \
	"EXP_UPD_VALIDATOR___REF_NUM1 as REF_NUM1", \
	"EXP_UPD_VALIDATOR___REF_NUM2 as REF_NUM2", \
	"EXP_UPD_VALIDATOR___REF_NUM3 as REF_NUM3", \
	"EXP_UPD_VALIDATOR___REF_NUM4 as REF_NUM4", \
	"EXP_UPD_VALIDATOR___REF_NUM5 as REF_NUM5", \
	"EXP_UPD_VALIDATOR___MARK_FOR_DELETION as MARK_FOR_DELETION", \
	"EXP_UPD_VALIDATOR___CREATED_SOURCE_TYPE as CREATED_SOURCE_TYPE", \
	"EXP_UPD_VALIDATOR___CREATED_SOURCE as CREATED_SOURCE", \
	"EXP_UPD_VALIDATOR___CREATED_DTTM as CREATED_DTTM", \
	"EXP_UPD_VALIDATOR___LAST_UPDATED_SOURCE_TYPE as LAST_UPDATED_SOURCE_TYPE", \
	"EXP_UPD_VALIDATOR___LAST_UPDATED_SOURCE as LAST_UPDATED_SOURCE", \
	"EXP_UPD_VALIDATOR___LAST_UPDATED_DTTM as LAST_UPDATED_DTTM", \
	"EXP_UPD_VALIDATOR___in_LOCATION_ID as in_LOCATION_ID", \
	"EXP_UPD_VALIDATOR___WM_CARRIER_ID as WM_CARRIER_ID", \
	"EXP_UPD_VALIDATOR___WM_CARRIER_CD as WM_CARRIER_CD", \
	"EXP_UPD_VALIDATOR___WM_CARRIER_CD_NAME as WM_CARRIER_CD_NAME", \
	"EXP_UPD_VALIDATOR___WM_CARRIER_CD_STATUS as WM_CARRIER_CD_STATUS", \
	"EXP_UPD_VALIDATOR___WM_TC_COMPANY_ID as WM_TC_COMPANY_ID", \
	"EXP_UPD_VALIDATOR___WM_TP_COMPANY_ID as WM_TP_COMPANY_ID", \
	"EXP_UPD_VALIDATOR___WM_TP_COMPANY_NAME as WM_TP_COMPANY_NAME", \
	"EXP_UPD_VALIDATOR___ADDRESS1 as ADDRESS1", \
	"EXP_UPD_VALIDATOR___CITY1 as CITY1", \
	"EXP_UPD_VALIDATOR___STATE_PROV1 as STATE_PROV1", \
	"EXP_UPD_VALIDATOR___POSTAL_CD as POSTAL_CD", \
	"EXP_UPD_VALIDATOR___COUNTRY_CD as COUNTRY_CD", \
	"EXP_UPD_VALIDATOR___CARRIER_ADDR_FOR_CL1 as CARRIER_ADDR_FOR_CL1", \
	"EXP_UPD_VALIDATOR___WM_CARRIER_TYPE_ID as WM_CARRIER_TYPE_ID", \
	"EXP_UPD_VALIDATOR___WM_EPI_CARRIER_CD as WM_EPI_CARRIER_CD", \
	"EXP_UPD_VALIDATOR___WM_SCAC_CD as WM_SCAC_CD", \
	"EXP_UPD_VALIDATOR___PAYMENT_METHOD1 as PAYMENT_METHOD1", \
	"EXP_UPD_VALIDATOR___PAYMENT_REFERENCE_NBR as PAYMENT_REFERENCE_NBR", \
	"EXP_UPD_VALIDATOR___PREPAY_FLAG as PREPAY_FLAG", \
	"EXP_UPD_VALIDATOR___AUTO_CREATE_INVOICE_FLAG as AUTO_CREATE_INVOICE_FLAG", \
	"EXP_UPD_VALIDATOR___INVOICE_PAYMENT_TERMS1 as INVOICE_PAYMENT_TERMS1", \
	"EXP_UPD_VALIDATOR___VALIDATE_INVOICE1 as VALIDATE_INVOICE1", \
	"EXP_UPD_VALIDATOR___MATCH_PAY_EMAIL1 as MATCH_PAY_EMAIL1", \
	"EXP_UPD_VALIDATOR___PAYEE_FLAG as PAYEE_FLAG", \
	"EXP_UPD_VALIDATOR___WM_TARIFF_ID as WM_TARIFF_ID", \
	"EXP_UPD_VALIDATOR___WM_TAX_ID as WM_TAX_ID", \
	"EXP_UPD_VALIDATOR___HAZMAT_FLAG as HAZMAT_FLAG", \
	"EXP_UPD_VALIDATOR___HAZMAT_REG_NBR1 as HAZMAT_REG_NBR1", \
	"EXP_UPD_VALIDATOR___EXPIRY_DT as EXPIRY_DT", \
	"EXP_UPD_VALIDATOR___DAYS_TO_DISPUTE_CLAIM1 as DAYS_TO_DISPUTE_CLAIM1", \
	"EXP_UPD_VALIDATOR___COMM_METHOD1 as COMM_METHOD1", \
	"EXP_UPD_VALIDATOR___MOTOR_CARRIER_NBR1 as MOTOR_CARRIER_NBR1", \
	"EXP_UPD_VALIDATOR___FREIGHT_FRWRDR_NBR1 as FREIGHT_FRWRDR_NBR1", \
	"EXP_UPD_VALIDATOR___PRO_NBR_LEVEL as PRO_NBR_LEVEL", \
	"EXP_UPD_VALIDATOR___DEFAULT_PALLET_TYPE1 as DEFAULT_PALLET_TYPE1", \
	"EXP_UPD_VALIDATOR___AWB_UOM1 as AWB_UOM1", \
	"EXP_UPD_VALIDATOR___TRANS_EXCEL1 as TRANS_EXCEL1", \
	"EXP_UPD_VALIDATOR___DOT_NBR as DOT_NBR", \
	"EXP_UPD_VALIDATOR___BENCHMARK_FLAG as BENCHMARK_FLAG", \
	"EXP_UPD_VALIDATOR___UNION_FLAG as UNION_FLAG", \
	"EXP_UPD_VALIDATOR___AUTO_DELIVER_FLAG as AUTO_DELIVER_FLAG", \
	"EXP_UPD_VALIDATOR___AUTO_ACCEPT_TYPE1 as AUTO_ACCEPT_TYPE1", \
	"EXP_UPD_VALIDATOR___ACCEPT_MSG_REQD_FLAG as ACCEPT_MSG_REQD_FLAG", \
	"EXP_UPD_VALIDATOR___APPT_MSG_REQD_FLAG as APPT_MSG_REQD_FLAG", \
	"EXP_UPD_VALIDATOR___DEPART_MSG_REQD_FLAG as DEPART_MSG_REQD_FLAG", \
	"EXP_UPD_VALIDATOR___ARRIVE_MSG_REQD_FLAG as ARRIVE_MSG_REQD_FLAG", \
	"EXP_UPD_VALIDATOR___CONFIRM_RECALL_REQD_FLAG as CONFIRM_RECALL_REQD_FLAG", \
	"EXP_UPD_VALIDATOR___CONFIRM_UPDATE_REQD_FLAG as CONFIRM_UPDATE_REQD_FLAG", \
	"EXP_UPD_VALIDATOR___BROKER_FLAG as BROKER_FLAG", \
	"EXP_UPD_VALIDATOR___BROKER_RECEIVE_UPDATES_FLAG as BROKER_RECEIVE_UPDATES_FLAG", \
	"EXP_UPD_VALIDATOR___ALLOW_BOL_ENTRY_FLAG as ALLOW_BOL_ENTRY_FLAG", \
	"EXP_UPD_VALIDATOR___AUTO_DELIVER_DELAY_HOURS1 as AUTO_DELIVER_DELAY_HOURS1", \
	"EXP_UPD_VALIDATOR___DOCK_SCHEDULE_PERMISSION1 as DOCK_SCHEDULE_PERMISSION1", \
	"EXP_UPD_VALIDATOR___ALLOW_LOAD_COMPLETION_FLAG as ALLOW_LOAD_COMPLETION_FLAG", \
	"EXP_UPD_VALIDATOR___RECEIVES_DOCK_INFO_FLAG as RECEIVES_DOCK_INFO_FLAG", \
	"EXP_UPD_VALIDATOR___ALLOW_TRAILER_ENTRY_FLAG as ALLOW_TRAILER_ENTRY_FLAG", \
	"EXP_UPD_VALIDATOR___ALLOW_TRACTOR_ENTRY_FLAG as ALLOW_TRACTOR_ENTRY_FLAG", \
	"EXP_UPD_VALIDATOR___ALLOW_CARRIER_CHARGES_VIEW_FLAG as ALLOW_CARRIER_CHARGES_VIEW_FLAG", \
	"EXP_UPD_VALIDATOR___SUPPORTS_PARCEL1 as SUPPORTS_PARCEL1", \
	"EXP_UPD_VALIDATOR___RECEIVE_FACILITY_INFO_FLAG as RECEIVE_FACILITY_INFO_FLAG", \
	"EXP_UPD_VALIDATOR___PRIVATE_FLEET_FLAG as PRIVATE_FLEET_FLAG", \
	"EXP_UPD_VALIDATOR___PREFERRED_FLAG as PREFERRED_FLAG", \
	"EXP_UPD_VALIDATOR___CUT_PARCEL_INVOICE_FLAG as CUT_PARCEL_INVOICE_FLAG", \
	"EXP_UPD_VALIDATOR___USE_CARRIER_ADDR_FLAG as USE_CARRIER_ADDR_FLAG", \
	"EXP_UPD_VALIDATOR___CLAIM_ON_DETENTION_APPROVAL1 as CLAIM_ON_DETENTION_APPROVAL1", \
	"EXP_UPD_VALIDATOR___RES_BASED_COSTING_ALLOWED_FLAG as RES_BASED_COSTING_ALLOWED_FLAG", \
	"EXP_UPD_VALIDATOR___ACTIVITY_BASED_COSTING_FLAG as ACTIVITY_BASED_COSTING_FLAG", \
	"EXP_UPD_VALIDATOR___PCT_OVER_CAPACITY1 as PCT_OVER_CAPACITY1", \
	"EXP_UPD_VALIDATOR___ALLOW_CARRIER_BOOKING_REF_FLAG as ALLOW_CARRIER_BOOKING_REF_FLAG", \
	"EXP_UPD_VALIDATOR___ALLOW_FORWARDER_AWB_FLAG as ALLOW_FORWARDER_AWB_FLAG", \
	"EXP_UPD_VALIDATOR___ALLOW_MASTER_AWB_FLAG as ALLOW_MASTER_AWB_FLAG", \
	"EXP_UPD_VALIDATOR___MAX_FLEET_APPROVED_AMT as MAX_FLEET_APPROVED_AMT", \
	"EXP_UPD_VALIDATOR___CHECK_NON_MACHINABLE_FLAG as CHECK_NON_MACHINABLE_FLAG", \
	"EXP_UPD_VALIDATOR___INV_ON_CARR_SIZES_FLAG as INV_ON_CARR_SIZES_FLAG", \
	"EXP_UPD_VALIDATOR___PRO_NUMBER_REQD_FLAG as PRO_NUMBER_REQD_FLAG", \
	"EXP_UPD_VALIDATOR___ALLOW_TENDER_REJECT_FLAG as ALLOW_TENDER_REJECT_FLAG", \
	"EXP_UPD_VALIDATOR___ALLOW_COUNTER_OFFER_FLAG as ALLOW_COUNTER_OFFER_FLAG", \
	"EXP_UPD_VALIDATOR___DEPART_MSG_REQD_AT_FIRST_STOP_FLAG as DEPART_MSG_REQD_AT_FIRST_STOP_FLAG", \
	"EXP_UPD_VALIDATOR___EPI_SUPPORTS_HOLD_PROCESS_FLAG as EPI_SUPPORTS_HOLD_PROCESS_FLAG", \
	"EXP_UPD_VALIDATOR___EPI_SUPPORTS_EOD_FLAG as EPI_SUPPORTS_EOD_FLAG", \
	"EXP_UPD_VALIDATOR___LOAD_PRO_NEXT_UP_COUNTER1 as LOAD_PRO_NEXT_UP_COUNTER1", \
	"EXP_UPD_VALIDATOR___STOP_PRO_NEXT_UP_COUNTER1 as STOP_PRO_NEXT_UP_COUNTER1", \
	"EXP_UPD_VALIDATOR___MOBILE_SHIP_TRACK_FLAG as MOBILE_SHIP_TRACK_FLAG", \
	"EXP_UPD_VALIDATOR___WM_LANGUAGE_ID as WM_LANGUAGE_ID", \
	"EXP_UPD_VALIDATOR___REF_FIELD_1 as REF_FIELD_1", \
	"EXP_UPD_VALIDATOR___REF_FIELD_2 as REF_FIELD_2", \
	"EXP_UPD_VALIDATOR___REF_FIELD_3 as REF_FIELD_3", \
	"EXP_UPD_VALIDATOR___REF_FIELD_4 as REF_FIELD_4", \
	"EXP_UPD_VALIDATOR___REF_FIELD_5 as REF_FIELD_5", \
	"EXP_UPD_VALIDATOR___REF_NUM_1 as REF_NUM_1", \
	"EXP_UPD_VALIDATOR___REF_NUM_2 as REF_NUM_2", \
	"EXP_UPD_VALIDATOR___REF_NUM_3 as REF_NUM_3", \
	"EXP_UPD_VALIDATOR___REF_NUM_4 as REF_NUM_4", \
	"EXP_UPD_VALIDATOR___REF_NUM_5 as REF_NUM_5", \
	"EXP_UPD_VALIDATOR___MARK_FOR_DELETION_FLAG as MARK_FOR_DELETION_FLAG", \
	"EXP_UPD_VALIDATOR___WM_CREATED_SOURCE_TYPE as WM_CREATED_SOURCE_TYPE", \
	"EXP_UPD_VALIDATOR___WM_CREATED_SOURCE as WM_CREATED_SOURCE", \
	"EXP_UPD_VALIDATOR___WM_CREATED_TSTMP as WM_CREATED_TSTMP", \
	"EXP_UPD_VALIDATOR___WM_LAST_UPDATED_SOURCE_TYPE as WM_LAST_UPDATED_SOURCE_TYPE", \
	"EXP_UPD_VALIDATOR___WM_LAST_UPDATED_SOURCE as WM_LAST_UPDATED_SOURCE", \
	"EXP_UPD_VALIDATOR___WM_LAST_UPDATED_TSTMP as WM_LAST_UPDATED_TSTMP", \
	"EXP_UPD_VALIDATOR___in_LOAD_TSTMP as in_LOAD_TSTMP", \
	"EXP_UPD_VALIDATOR___UPDATE_TSTMP as UPDATE_TSTMP", \
	"EXP_UPD_VALIDATOR___LOAD_TSTMP_exp as LOAD_TSTMP_exp", \
	"EXP_UPD_VALIDATOR___o_UPD_VALIDATOR as o_UPD_VALIDATOR") \
	.withColumn('pyspark_data_action', when(col('o_UPD_VALIDATOR') ==(lit(1)), lit(0)).when(col('o_UPD_VALIDATOR') ==(lit(2)), lit(1)))

# COMMAND ----------
# Processing node Shortcut_to_WM_CARRIER_CODE1, type TARGET 
# COLUMN COUNT: 104


Shortcut_to_WM_CARRIER_CODE1 = UPD_INS_UPD.selectExpr(
	"CAST(LOCATION_ID AS BIGINT) as LOCATION_ID",
	"CAST(CARRIER_ID AS BIGINT) as WM_CARRIER_ID",
	"CAST(CARRIER_CODE AS STRING) as WM_CARRIER_CD",
	"CAST(CARRIER_CODE_NAME AS STRING) as WM_CARRIER_CD_NAME",
	"CAST(CARRIER_CODE_STATUS AS TINYINT) as WM_CARRIER_CD_STATUS",
	"CAST(TC_COMPANY_ID AS INT) as WM_TC_COMPANY_ID",
	"CAST(TP_COMPANY_ID AS INT) as WM_TP_COMPANY_ID",
	"CAST(TP_COMPANY_NAME AS STRING) as WM_TP_COMPANY_NAME",
	"CAST(ADDRESS AS STRING) as ADDRESS",
	"CAST(CITY AS STRING) as CITY",
	"CAST(STATE_PROV AS STRING) as STATE_PROV",
	"CAST(POSTAL_CODE AS STRING) as POSTAL_CD",
	"CAST(COUNTRY_CODE AS STRING) as COUNTRY_CD",
	"CAST(CARRIER_ADDR_FOR_CL AS STRING) as CARRIER_ADDR_FOR_CL",
	"CAST(CARRIER_TYPE_ID AS SMALLINT) as WM_CARRIER_TYPE_ID",
	"CAST(EPI_CARRIER_CODE AS STRING) as WM_EPI_CARRIER_CD",
	"CAST(SCAC_CODE AS STRING) as WM_SCAC_CD",
	"CAST(PAYMENT_METHOD AS STRING) as PAYMENT_METHOD",
	"CAST(PAYMENT_REFERENCE_NUMBER AS STRING) as PAYMENT_REFERENCE_NBR",
	"CAST(IS_PREPAY AS TINYINT) as PREPAY_FLAG",
	"CAST(IS_AUTO_CREATE_INVOICE AS TINYINT) as AUTO_CREATE_INVOICE_FLAG",
	"CAST(INVOICE_PAYMENT_TERMS AS STRING) as INVOICE_PAYMENT_TERMS",
	"CAST(VALIDATE_INVOICE AS INT) as VALIDATE_INVOICE",
	"CAST(MATCH_PAY_EMAIL AS STRING) as MATCH_PAY_EMAIL",
	"CAST(IS_PAYEE AS TINYINT) as PAYEE_FLAG",
	"CAST(TARIFF_ID AS STRING) as WM_TARIFF_ID",
	"CAST(TAX_ID AS STRING) as WM_TAX_ID",
	"CAST(HAS_HAZMAT AS TINYINT) as HAZMAT_FLAG",
	"CAST(HAZMAT_REG_NBR AS STRING) as HAZMAT_REG_NBR",
	"CAST(EXPIRY_DATE AS TIMESTAMP) as EXPIRY_DT",
	"CAST(DAYS_TO_DISPUTE_CLAIM AS INT) as DAYS_TO_DISPUTE_CLAIM",
	"CAST(COMM_METHOD AS STRING) as COMM_METHOD",
	"CAST(MOTOR_CARRIER_NBR AS INT) as MOTOR_CARRIER_NBR",
	"CAST(FREIGHT_FRWRDR_NBR AS INT) as FREIGHT_FRWRDR_NBR",
	"CAST(PRO_NUMBER_LEVEL AS STRING) as PRO_NBR_LEVEL",
	"CAST(DEFAULT_PALLET_TYPE AS STRING) as DEFAULT_PALLET_TYPE",
	"CAST(AWB_UOM AS STRING) as AWB_UOM",
	"CAST(TRANS_EXCEL AS SMALLINT) as TRANS_EXCEL",
	"CAST(DOT_NUMBER AS STRING) as DOT_NBR",
	"CAST(IS_BENCHMARK AS TINYINT) as BENCHMARK_FLAG",
	"CAST(IS_UNION AS TINYINT) as UNION_FLAG",
	"CAST(IS_AUTO_DELIVER AS TINYINT) as AUTO_DELIVER_FLAG",
	"CAST(AUTO_ACCEPT_TYPE AS TINYINT) as AUTO_ACCEPT_TYPE",
	"CAST(ACCEPT_MSG_REQD AS TINYINT) as ACCEPT_MSG_REQD_FLAG",
	"CAST(APPT_MSG_REQD AS TINYINT) as APPT_MSG_REQD_FLAG",
	"CAST(DEPART_MSG_REQD AS TINYINT) as DEPART_MSG_REQD_FLAG",
	"CAST(ARRIVE_MSG_REQD AS TINYINT) as ARRIVE_MSG_REQD_FLAG",
	"CAST(CONFIRM_RECALL_REQD AS TINYINT) as CONFIRM_RECALL_REQD_FLAG",
	"CAST(CONFIRM_UPDATE_REQD AS TINYINT) as CONFIRM_UPDATE_REQD_FLAG",
	"CAST(IS_BROKER AS TINYINT) as BROKER_FLAG",
	"CAST(BROKER_RECEIVE_UPDATES AS TINYINT) as BROKER_RECEIVE_UPDATES_FLAG",
	"CAST(ALLOW_BOL_ENTRY AS TINYINT) as ALLOW_BOL_ENTRY_FLAG",
	"CAST(AUTO_DELIVER_DELAY_HOURS AS INT) as AUTO_DELIVER_DELAY_HOURS",
	"CAST(DOCK_SCHEDULE_PERMISSION AS TINYINT) as DOCK_SCHEDULE_PERMISSION",
	"CAST(ALLOW_LOAD_COMPLETION AS TINYINT) as ALLOW_LOAD_COMPLETION_FLAG",
	"CAST(RECEIVES_DOCK_INFO AS TINYINT) as RECEIVES_DOCK_INFO_FLAG",
	"CAST(ALLOW_TRAILER_ENTRY AS TINYINT) as ALLOW_TRAILER_ENTRY_FLAG",
	"CAST(ALLOW_TRACTOR_ENTRY AS TINYINT) as ALLOW_TRACTOR_ENTRY_FLAG",
	"CAST(ALLOW_CARRIER_CHARGES_VIEW AS TINYINT) as ALLOW_CARRIER_CHARGES_VIEW_FLAG",
	"CAST(SUPPORTS_PARCEL AS TINYINT) as SUPPORTS_PARCEL",
	"CAST(DOES_RECEIVE_FACILITY_INFO AS TINYINT) as RECEIVE_FACILITY_INFO_FLAG",
	"CAST(IS_PRIVATE_FLEET AS TINYINT) as PRIVATE_FLEET_FLAG",
	"CAST(IS_PREFERRED AS TINYINT) as PREFERRED_FLAG",
	"CAST(CUT_PARCEL_INVOICE AS TINYINT) as CUT_PARCEL_INVOICE_FLAG",
	"CAST(USE_CARRIER_ADDR AS TINYINT) as USE_CARRIER_ADDR_FLAG",
	"CAST(CLAIM_ON_DETENTION_APPROVAL AS TINYINT) as CLAIM_ON_DETENTION_APPROVAL",
	"CAST(IS_RES_BASED_COSTING_ALLOWED AS TINYINT) as RES_BASED_COSTING_ALLOWED_FLAG",
	"CAST(IS_ACTIVITY_BASED_COSTING AS TINYINT) as ACTIVITY_BASED_COSTING_FLAG",
	"CAST(PCT_OVER_CAPACITY AS DECIMAL(13,4)) as PCT_OVER_CAPACITY",
	"CAST(ALLOW_CARRIER_BOOKING_REF AS TINYINT) as ALLOW_CARRIER_BOOKING_REF_FLAG",
	"CAST(ALLOW_FORWARDER_AWB AS TINYINT) as ALLOW_FORWARDER_AWB_FLAG",
	"CAST(ALLOW_MASTER_AWB AS TINYINT) as ALLOW_MASTER_AWB_FLAG",
	"CAST(MAX_FLEET_APPROVED_AMOUNT AS DECIMAL(13,2)) as MAX_FLEET_APPROVED_AMT",
	"CAST(CHECK_NON_MACHINABLE AS TINYINT) as CHECK_NON_MACHINABLE_FLAG",
	"CAST(INV_ON_CARR_SIZES AS TINYINT) as INV_ON_CARR_SIZES_FLAG",
	"CAST(PRO_NUMBER_REQD AS TINYINT) as PRO_NUMBER_REQD_FLAG",
	"CAST(ALLOW_COUNTER_OFFER AS TINYINT) as ALLOW_TENDER_REJECT_FLAG",
	"CAST(ALLOW_TENDER_REJECT AS TINYINT) as ALLOW_COUNTER_OFFER_FLAG",
	"CAST(DEPART_MSG_REQD_AT_FIRST_STOP AS TINYINT) as DEPART_MSG_REQD_AT_FIRST_STOP_FLAG",
	"CAST(EPI_SUPPORTS_HOLD_PROCESS AS TINYINT) as EPI_SUPPORTS_HOLD_PROCESS_FLAG",
	"CAST(EPI_SUPPORTS_EOD AS TINYINT) as EPI_SUPPORTS_EOD_FLAG",
	"CAST(LOAD_PRO_NEXT_UP_COUNTER AS STRING) as LOAD_PRO_NEXT_UP_COUNTER",
	"CAST(STOP_PRO_NEXT_UP_COUNTER AS STRING) as STOP_PRO_NEXT_UP_COUNTER",
	"CAST(MOBILE_SHIP_TRACK AS TINYINT) as MOBILE_SHIP_TRACK_FLAG",
	"CAST(LANG_ID AS STRING) as WM_LANGUAGE_ID",
	"CAST(REF_FIELD1 AS STRING) as REF_FIELD_1",
	"CAST(REF_FIELD2 AS STRING) as REF_FIELD_2",
	"CAST(REF_FIELD3 AS STRING) as REF_FIELD_3",
	"CAST(REF_FIELD4 AS STRING) as REF_FIELD_4",
	"CAST(REF_FIELD5 AS STRING) as REF_FIELD_5",
	"CAST(REF_NUM1 AS DECIMAL(13,5)) as REF_NUM_1",
	"CAST(REF_NUM2 AS DECIMAL(13,5)) as REF_NUM_2",
	"CAST(REF_NUM3 AS DECIMAL(13,5)) as REF_NUM_3",
	"CAST(REF_NUM4 AS DECIMAL(13,5)) as REF_NUM_4",
	"CAST(REF_NUM5 AS DECIMAL(13,5)) as REF_NUM_5",
	"CAST(MARK_FOR_DELETION AS TINYINT) as MARK_FOR_DELETION_FLAG",
	"CAST(CREATED_SOURCE_TYPE AS TINYINT) as WM_CREATED_SOURCE_TYPE",
	"CAST(CREATED_SOURCE AS STRING) as WM_CREATED_SOURCE",
	"CAST(CREATED_DTTM AS TIMESTAMP) as WM_CREATED_TSTMP",
	"CAST(LAST_UPDATED_SOURCE_TYPE AS TINYINT) as WM_LAST_UPDATED_SOURCE_TYPE",
	"CAST(LAST_UPDATED_SOURCE AS STRING) as WM_LAST_UPDATED_SOURCE",
	"CAST(LAST_UPDATED_DTTM AS TIMESTAMP) as WM_LAST_UPDATED_TSTMP",
	"CAST(UPDATE_TSTMP AS TIMESTAMP) as UPDATE_TSTMP",
	"CAST(LOAD_TSTMP_exp AS TIMESTAMP) as LOAD_TSTMP", 
    "pyspark_data_action" 
)

try:
  primary_key = """source.LOCATION_ID = target.LOCATION_ID AND source.WM_CARRIER_ID = target.WM_CARRIER_ID"""
#   refined_perf_table = "WM_CARRIER_CODE"
  executeMerge(Shortcut_to_WM_CARRIER_CODE1, refined_perf_table, primary_key)
  logger.info(f"Merge with {refined_perf_table} completed]")
  logPrevRunDt("WM_CARRIER_CODE", "WM_CARRIER_CODE", "Completed", "N/A", f"{raw}.log_run_details")
except Exception as e:
  logPrevRunDt("WM_CARRIER_CODE", "WM_CARRIER_CODE","Failed",str(e), f"{raw}.log_run_details", )
  raise e
	