#Code converted on 2023-06-26 17:58:52
import os
import argparse
from pyspark.sql import *
from pyspark.sql.functions import *
from pyspark.sql.window import Window
from pyspark.sql.types import *
from datetime import datetime
from pyspark.dbutils import DBUtils
from utils.genericUtilities import *
from utils.configs import *
from utils.mergeUtils import *
from utils.logger import *
# COMMAND ----------

parser = argparse.ArgumentParser()
spark = SparkSession.getActiveSession()
dbutils = DBUtils(spark)
parser.add_argument('env', type=str, help='Env Variable')
args = parser.parse_args()
env = args.env

if env is None or env == '':
    raise ValueError('env is not set')

refine = getEnvPrefix(env) + 'refine'
raw = getEnvPrefix(env) + 'raw'
legacy = getEnvPrefix(env) + 'legacy'

# Set global variables
starttime = datetime.now() #start timestamp of the script

# COMMAND ----------
# Processing node SQ_Shortcut_to_WM_ORDER_LINE_ITEM, type SOURCE 
# COLUMN COUNT: 6

SQ_Shortcut_to_WM_ORDER_LINE_ITEM = spark.sql(f"""SELECT
WM_ORDER_LINE_ITEM.LOCATION_ID,
WM_ORDER_LINE_ITEM.WM_ORDER_ID,
WM_ORDER_LINE_ITEM.WM_LINE_ITEM_ID,
WM_ORDER_LINE_ITEM.WM_CREATED_TSTMP,
WM_ORDER_LINE_ITEM.WM_LAST_UPDATED_TSTMP,
WM_ORDER_LINE_ITEM.LOAD_TSTMP
FROM WM_ORDER_LINE_ITEM
WHERE WM_ORDER_ID IN (SELECT ORDER_ID FROM WM_ORDER_LINE_ITEM_PRE)""").withColumn("sys_row_id", monotonically_increasing_id())

# COMMAND ----------
# Processing node SQ_Shortcut_to_WM_ORDER_LINE_ITEM_PRE, type SOURCE 
# COLUMN COUNT: 209

SQ_Shortcut_to_WM_ORDER_LINE_ITEM_PRE = spark.sql(f"""SELECT
WM_ORDER_LINE_ITEM_PRE.DC_NBR,
WM_ORDER_LINE_ITEM_PRE.ORDER_ID,
WM_ORDER_LINE_ITEM_PRE.LINE_ITEM_ID,
WM_ORDER_LINE_ITEM_PRE.PARENT_LINE_ITEM_ID,
WM_ORDER_LINE_ITEM_PRE.TC_COMPANY_ID,
WM_ORDER_LINE_ITEM_PRE.COMMODITY_CLASS,
WM_ORDER_LINE_ITEM_PRE.REF_FIELD1,
WM_ORDER_LINE_ITEM_PRE.REF_FIELD2,
WM_ORDER_LINE_ITEM_PRE.REF_FIELD3,
WM_ORDER_LINE_ITEM_PRE.EXT_SYS_LINE_ITEM_ID,
WM_ORDER_LINE_ITEM_PRE.MASTER_ORDER_ID,
WM_ORDER_LINE_ITEM_PRE.MO_LINE_ITEM_ID,
WM_ORDER_LINE_ITEM_PRE.IS_HAZMAT,
WM_ORDER_LINE_ITEM_PRE.IS_STACKABLE,
WM_ORDER_LINE_ITEM_PRE.HAS_ERRORS,
WM_ORDER_LINE_ITEM_PRE.ORIG_BUDG_COST,
WM_ORDER_LINE_ITEM_PRE.BUDG_COST_CURRENCY_CODE,
WM_ORDER_LINE_ITEM_PRE.BUDG_COST,
WM_ORDER_LINE_ITEM_PRE.ACTUAL_COST_CURRENCY_CODE,
WM_ORDER_LINE_ITEM_PRE.TOTAL_MONETARY_VALUE,
WM_ORDER_LINE_ITEM_PRE.UNIT_MONETARY_VALUE,
WM_ORDER_LINE_ITEM_PRE.UNIT_TAX_AMOUNT,
WM_ORDER_LINE_ITEM_PRE.RTS_ID,
WM_ORDER_LINE_ITEM_PRE.RTS_LINE_ITEM_ID,
WM_ORDER_LINE_ITEM_PRE.STD_PACK_QTY,
WM_ORDER_LINE_ITEM_PRE.PRODUCT_CLASS_ID,
WM_ORDER_LINE_ITEM_PRE.PROTECTION_LEVEL_ID,
WM_ORDER_LINE_ITEM_PRE.PACKAGE_TYPE_ID,
WM_ORDER_LINE_ITEM_PRE.COMMODITY_CODE_ID,
WM_ORDER_LINE_ITEM_PRE.MV_SIZE_UOM_ID,
WM_ORDER_LINE_ITEM_PRE.QTY_UOM_ID_BASE,
WM_ORDER_LINE_ITEM_PRE.MV_CURRENCY_CODE,
WM_ORDER_LINE_ITEM_PRE.SHIPPED_QTY,
WM_ORDER_LINE_ITEM_PRE.RECEIVED_QTY,
WM_ORDER_LINE_ITEM_PRE.PRIORITY,
WM_ORDER_LINE_ITEM_PRE.MERCHANDIZING_DEPARTMENT_ID,
WM_ORDER_LINE_ITEM_PRE.UN_NUMBER_ID,
WM_ORDER_LINE_ITEM_PRE.PICKUP_REFERENCE_NUMBER,
WM_ORDER_LINE_ITEM_PRE.DELIVERY_REFERENCE_NUMBER,
WM_ORDER_LINE_ITEM_PRE.CNTRY_OF_ORGN,
WM_ORDER_LINE_ITEM_PRE.PROD_STAT,
WM_ORDER_LINE_ITEM_PRE.STACK_RANK,
WM_ORDER_LINE_ITEM_PRE.STACK_LENGTH_VALUE,
WM_ORDER_LINE_ITEM_PRE.STACK_LENGTH_STANDARD_UOM,
WM_ORDER_LINE_ITEM_PRE.STACK_WIDTH_VALUE,
WM_ORDER_LINE_ITEM_PRE.STACK_WIDTH_STANDARD_UOM,
WM_ORDER_LINE_ITEM_PRE.STACK_HEIGHT_VALUE,
WM_ORDER_LINE_ITEM_PRE.STACK_HEIGHT_STANDARD_UOM,
WM_ORDER_LINE_ITEM_PRE.STACK_DIAMETER_VALUE,
WM_ORDER_LINE_ITEM_PRE.STACK_DIAMETER_STANDARD_UOM,
WM_ORDER_LINE_ITEM_PRE.CREATED_SOURCE_TYPE,
WM_ORDER_LINE_ITEM_PRE.CREATED_SOURCE,
WM_ORDER_LINE_ITEM_PRE.CREATED_DTTM,
WM_ORDER_LINE_ITEM_PRE.LAST_UPDATED_SOURCE_TYPE,
WM_ORDER_LINE_ITEM_PRE.LAST_UPDATED_SOURCE,
WM_ORDER_LINE_ITEM_PRE.LAST_UPDATED_DTTM,
WM_ORDER_LINE_ITEM_PRE.HIBERNATE_VERSION,
WM_ORDER_LINE_ITEM_PRE.CUBE_MULTIPLE_QTY,
WM_ORDER_LINE_ITEM_PRE.DO_DTL_STATUS,
WM_ORDER_LINE_ITEM_PRE.INTERNAL_ORDER_SEQ_NBR,
WM_ORDER_LINE_ITEM_PRE.IS_EMERGENCY,
WM_ORDER_LINE_ITEM_PRE.LPN_SIZE,
WM_ORDER_LINE_ITEM_PRE.MANUFACTURING_DTTM,
WM_ORDER_LINE_ITEM_PRE.ORDER_LINE_ID,
WM_ORDER_LINE_ITEM_PRE.PACK_RATE,
WM_ORDER_LINE_ITEM_PRE.ALLOCATED_QTY,
WM_ORDER_LINE_ITEM_PRE.PLANNED_SHIP_DATE,
WM_ORDER_LINE_ITEM_PRE.PPACK_QTY,
WM_ORDER_LINE_ITEM_PRE.STD_BUNDLE_QTY,
WM_ORDER_LINE_ITEM_PRE.STD_LPN_QTY,
WM_ORDER_LINE_ITEM_PRE.STD_LPN_VOL,
WM_ORDER_LINE_ITEM_PRE.STD_LPN_WT,
WM_ORDER_LINE_ITEM_PRE.UNIT_COST,
WM_ORDER_LINE_ITEM_PRE.UNIT_PRICE_AMOUNT,
WM_ORDER_LINE_ITEM_PRE.UNIT_VOL,
WM_ORDER_LINE_ITEM_PRE.UNIT_WT,
WM_ORDER_LINE_ITEM_PRE.USER_CANCELED_QTY,
WM_ORDER_LINE_ITEM_PRE.WAVE_PROC_TYPE,
WM_ORDER_LINE_ITEM_PRE.DELIVERY_END_DTTM,
WM_ORDER_LINE_ITEM_PRE.DELIVERY_START_DTTM,
WM_ORDER_LINE_ITEM_PRE.EVENT_CODE,
WM_ORDER_LINE_ITEM_PRE.REASON_CODE,
WM_ORDER_LINE_ITEM_PRE.EXP_INFO_CODE,
WM_ORDER_LINE_ITEM_PRE.PARTL_FILL,
WM_ORDER_LINE_ITEM_PRE.LINE_TYPE,
WM_ORDER_LINE_ITEM_PRE.REPL_PROC_TYPE,
WM_ORDER_LINE_ITEM_PRE.ORDER_QTY,
WM_ORDER_LINE_ITEM_PRE.ORIG_ORDER_QTY,
WM_ORDER_LINE_ITEM_PRE.RTL_TO_BE_DISTROED_QTY,
WM_ORDER_LINE_ITEM_PRE.PRICE,
WM_ORDER_LINE_ITEM_PRE.RETAIL_PRICE,
WM_ORDER_LINE_ITEM_PRE.UNITS_PAKD,
WM_ORDER_LINE_ITEM_PRE.MINOR_ORDER_NBR,
WM_ORDER_LINE_ITEM_PRE.ITEM_ID,
WM_ORDER_LINE_ITEM_PRE.TC_ORDER_LINE_ID,
WM_ORDER_LINE_ITEM_PRE.ACTUAL_SHIPPED_DTTM,
WM_ORDER_LINE_ITEM_PRE.QTY_UOM_ID,
WM_ORDER_LINE_ITEM_PRE.PICKUP_END_DTTM,
WM_ORDER_LINE_ITEM_PRE.PURCHASE_ORDER_LINE_NUMBER,
WM_ORDER_LINE_ITEM_PRE.PICKUP_START_DTTM,
WM_ORDER_LINE_ITEM_PRE.REFERENCE_LINE_ITEM_ID,
WM_ORDER_LINE_ITEM_PRE.REFERENCE_ORDER_ID,
WM_ORDER_LINE_ITEM_PRE.REPL_WAVE_RUN,
WM_ORDER_LINE_ITEM_PRE.STD_PALLET_QTY,
WM_ORDER_LINE_ITEM_PRE.STD_SUB_PACK_QTY,
WM_ORDER_LINE_ITEM_PRE.STORE_DEPT,
WM_ORDER_LINE_ITEM_PRE.ALLOC_TYPE,
WM_ORDER_LINE_ITEM_PRE.BATCH_NBR,
WM_ORDER_LINE_ITEM_PRE.BATCH_REQUIREMENT_TYPE,
WM_ORDER_LINE_ITEM_PRE.CHUTE_ASSIGN_TYPE,
WM_ORDER_LINE_ITEM_PRE.CUSTOM_TAG,
WM_ORDER_LINE_ITEM_PRE.CUSTOMER_ITEM,
WM_ORDER_LINE_ITEM_PRE.INTERNAL_ORDER_ID,
WM_ORDER_LINE_ITEM_PRE.INVN_TYPE,
WM_ORDER_LINE_ITEM_PRE.ITEM_ATTR_1,
WM_ORDER_LINE_ITEM_PRE.ITEM_ATTR_2,
WM_ORDER_LINE_ITEM_PRE.ITEM_ATTR_3,
WM_ORDER_LINE_ITEM_PRE.ITEM_ATTR_4,
WM_ORDER_LINE_ITEM_PRE.ITEM_ATTR_5,
WM_ORDER_LINE_ITEM_PRE.LPN_BRK_ATTRIB,
WM_ORDER_LINE_ITEM_PRE.MERCH_GRP,
WM_ORDER_LINE_ITEM_PRE.MERCH_TYPE,
WM_ORDER_LINE_ITEM_PRE.PACK_ZONE,
WM_ORDER_LINE_ITEM_PRE.PALLET_TYPE,
WM_ORDER_LINE_ITEM_PRE.PICK_LOCN_ASSIGN_TYPE,
WM_ORDER_LINE_ITEM_PRE.PICK_LOCN_ID,
WM_ORDER_LINE_ITEM_PRE.PPACK_GRP_CODE,
WM_ORDER_LINE_ITEM_PRE.PRICE_TKT_TYPE,
WM_ORDER_LINE_ITEM_PRE.SERIAL_NUMBER_REQUIRED_FLAG,
WM_ORDER_LINE_ITEM_PRE.SKU_GTIN,
WM_ORDER_LINE_ITEM_PRE.SKU_SUB_CODE_ID,
WM_ORDER_LINE_ITEM_PRE.SKU_SUB_CODE_VALUE,
WM_ORDER_LINE_ITEM_PRE.VAS_PROCESS_TYPE,
WM_ORDER_LINE_ITEM_PRE.SUBSTITUTED_PARENT_LINE_ID,
WM_ORDER_LINE_ITEM_PRE.IS_CANCELLED,
WM_ORDER_LINE_ITEM_PRE.ITEM_NAME,
WM_ORDER_LINE_ITEM_PRE.ALLOC_LINE_ID,
WM_ORDER_LINE_ITEM_PRE.ALLOCATION_SOURCE_ID,
WM_ORDER_LINE_ITEM_PRE.ALLOCATION_SOURCE_LINE_ID,
WM_ORDER_LINE_ITEM_PRE.ALLOCATION_SOURCE,
WM_ORDER_LINE_ITEM_PRE.SHELF_DAYS,
WM_ORDER_LINE_ITEM_PRE.FULFILLMENT_TYPE,
WM_ORDER_LINE_ITEM_PRE.WAVE_NBR,
WM_ORDER_LINE_ITEM_PRE.SHIP_WAVE_NBR,
WM_ORDER_LINE_ITEM_PRE.REPL_WAVE_NBR,
WM_ORDER_LINE_ITEM_PRE.SINGLE_UNIT_FLAG,
WM_ORDER_LINE_ITEM_PRE.ACTUAL_COST,
WM_ORDER_LINE_ITEM_PRE.QTY_CONV_FACTOR,
WM_ORDER_LINE_ITEM_PRE.PLANNED_WEIGHT,
WM_ORDER_LINE_ITEM_PRE.RECEIVED_WEIGHT,
WM_ORDER_LINE_ITEM_PRE.SHIPPED_WEIGHT,
WM_ORDER_LINE_ITEM_PRE.WEIGHT_UOM_ID_BASE,
WM_ORDER_LINE_ITEM_PRE.WEIGHT_UOM_ID,
WM_ORDER_LINE_ITEM_PRE.PLANNED_VOLUME,
WM_ORDER_LINE_ITEM_PRE.RECEIVED_VOLUME,
WM_ORDER_LINE_ITEM_PRE.SHIPPED_VOLUME,
WM_ORDER_LINE_ITEM_PRE.VOLUME_UOM_ID_BASE,
WM_ORDER_LINE_ITEM_PRE.VOLUME_UOM_ID,
WM_ORDER_LINE_ITEM_PRE.SIZE1_UOM_ID,
WM_ORDER_LINE_ITEM_PRE.SIZE1_VALUE,
WM_ORDER_LINE_ITEM_PRE.RECEIVED_SIZE1,
WM_ORDER_LINE_ITEM_PRE.SHIPPED_SIZE1,
WM_ORDER_LINE_ITEM_PRE.SIZE2_UOM_ID,
WM_ORDER_LINE_ITEM_PRE.SIZE2_VALUE,
WM_ORDER_LINE_ITEM_PRE.RECEIVED_SIZE2,
WM_ORDER_LINE_ITEM_PRE.SHIPPED_SIZE2,
WM_ORDER_LINE_ITEM_PRE.LPN_TYPE,
WM_ORDER_LINE_ITEM_PRE.ORDER_CONSOL_ATTR,
WM_ORDER_LINE_ITEM_PRE.SKU_BREAK_ATTR,
WM_ORDER_LINE_ITEM_PRE.PURCHASE_ORDER_NUMBER,
WM_ORDER_LINE_ITEM_PRE.EXT_PURCHASE_ORDER,
WM_ORDER_LINE_ITEM_PRE.CRITCL_DIM_1,
WM_ORDER_LINE_ITEM_PRE.CRITCL_DIM_2,
WM_ORDER_LINE_ITEM_PRE.CRITCL_DIM_3,
WM_ORDER_LINE_ITEM_PRE.ASSORT_NBR,
WM_ORDER_LINE_ITEM_PRE.DESCRIPTION,
WM_ORDER_LINE_ITEM_PRE.ORIGINAL_ORDERED_ITEM_ID,
WM_ORDER_LINE_ITEM_PRE.SUBSTITUTION_TYPE,
WM_ORDER_LINE_ITEM_PRE.BACK_ORD_REASON,
WM_ORDER_LINE_ITEM_PRE.FREIGHT_REVENUE_CURRENCY_CODE,
WM_ORDER_LINE_ITEM_PRE.FREIGHT_REVENUE,
WM_ORDER_LINE_ITEM_PRE.IS_CHASE_CREATED_LINE,
WM_ORDER_LINE_ITEM_PRE.REF_FIELD4,
WM_ORDER_LINE_ITEM_PRE.REF_FIELD5,
WM_ORDER_LINE_ITEM_PRE.REF_FIELD6,
WM_ORDER_LINE_ITEM_PRE.REF_FIELD7,
WM_ORDER_LINE_ITEM_PRE.REF_FIELD8,
WM_ORDER_LINE_ITEM_PRE.REF_FIELD9,
WM_ORDER_LINE_ITEM_PRE.REF_FIELD10,
WM_ORDER_LINE_ITEM_PRE.REF_NUM1,
WM_ORDER_LINE_ITEM_PRE.REF_NUM2,
WM_ORDER_LINE_ITEM_PRE.REF_NUM3,
WM_ORDER_LINE_ITEM_PRE.REF_NUM4,
WM_ORDER_LINE_ITEM_PRE.REF_NUM5,
WM_ORDER_LINE_ITEM_PRE.IS_GIFT,
WM_ORDER_LINE_ITEM_PRE.ADJUSTED_ORDER_QTY,
WM_ORDER_LINE_ITEM_PRE.PRE_RECEIPT_STATUS,
WM_ORDER_LINE_ITEM_PRE.ALLOW_REVIVAL_RECEIPT_ALLOC,
WM_ORDER_LINE_ITEM_PRE.SEGMENT_NAME,
WM_ORDER_LINE_ITEM_PRE.EFFECTIVE_RANK,
WM_ORDER_LINE_ITEM_PRE.WM_RECEIPT_ALLOCATED,
WM_ORDER_LINE_ITEM_PRE.GIFT_CARD_VALUE,
WM_ORDER_LINE_ITEM_PRE.REF_BOOLEAN1,
WM_ORDER_LINE_ITEM_PRE.REF_BOOLEAN2,
WM_ORDER_LINE_ITEM_PRE.REF_SYSCODE1,
WM_ORDER_LINE_ITEM_PRE.REF_SYSCODE2,
WM_ORDER_LINE_ITEM_PRE.REF_SYSCODE3,
WM_ORDER_LINE_ITEM_PRE.HARD_ALLOC_REASON_CODE,
WM_ORDER_LINE_ITEM_PRE.LOCKED
FROM WM_ORDER_LINE_ITEM_PRE""").withColumn("sys_row_id", monotonically_increasing_id())

# COMMAND ----------
# Processing node EXP_INT_CONVERSION, type EXPRESSION 
# COLUMN COUNT: 209

# for each involved DataFrame, append the dataframe name to each column
SQ_Shortcut_to_WM_ORDER_LINE_ITEM_PRE_temp = SQ_Shortcut_to_WM_ORDER_LINE_ITEM_PRE.toDF(*["SQ_Shortcut_to_WM_ORDER_LINE_ITEM_PRE___" + col for col in SQ_Shortcut_to_WM_ORDER_LINE_ITEM_PRE.columns])

EXP_INT_CONVERSION = SQ_Shortcut_to_WM_ORDER_LINE_ITEM_PRE_temp.selectExpr( \
	"SQ_Shortcut_to_WM_ORDER_LINE_ITEM_PRE___sys_row_id as sys_row_id", \
	"cast(SQ_Shortcut_to_WM_ORDER_LINE_ITEM_PRE___DC_NBR as int) as o_DC_NBR", \
	"SQ_Shortcut_to_WM_ORDER_LINE_ITEM_PRE___ORDER_ID as ORDER_ID", \
	"SQ_Shortcut_to_WM_ORDER_LINE_ITEM_PRE___LINE_ITEM_ID as LINE_ITEM_ID", \
	"SQ_Shortcut_to_WM_ORDER_LINE_ITEM_PRE___PARENT_LINE_ITEM_ID as PARENT_LINE_ITEM_ID", \
	"SQ_Shortcut_to_WM_ORDER_LINE_ITEM_PRE___TC_COMPANY_ID as TC_COMPANY_ID", \
	"SQ_Shortcut_to_WM_ORDER_LINE_ITEM_PRE___COMMODITY_CLASS as COMMODITY_CLASS", \
	"SQ_Shortcut_to_WM_ORDER_LINE_ITEM_PRE___REF_FIELD1 as REF_FIELD1", \
	"SQ_Shortcut_to_WM_ORDER_LINE_ITEM_PRE___REF_FIELD2 as REF_FIELD2", \
	"SQ_Shortcut_to_WM_ORDER_LINE_ITEM_PRE___REF_FIELD3 as REF_FIELD3", \
	"SQ_Shortcut_to_WM_ORDER_LINE_ITEM_PRE___EXT_SYS_LINE_ITEM_ID as EXT_SYS_LINE_ITEM_ID", \
	"SQ_Shortcut_to_WM_ORDER_LINE_ITEM_PRE___MASTER_ORDER_ID as MASTER_ORDER_ID", \
	"SQ_Shortcut_to_WM_ORDER_LINE_ITEM_PRE___MO_LINE_ITEM_ID as MO_LINE_ITEM_ID", \
	"SQ_Shortcut_to_WM_ORDER_LINE_ITEM_PRE___IS_HAZMAT as IS_HAZMAT", \
	"SQ_Shortcut_to_WM_ORDER_LINE_ITEM_PRE___IS_STACKABLE as IS_STACKABLE", \
	"SQ_Shortcut_to_WM_ORDER_LINE_ITEM_PRE___HAS_ERRORS as HAS_ERRORS", \
	"SQ_Shortcut_to_WM_ORDER_LINE_ITEM_PRE___ORIG_BUDG_COST as ORIG_BUDG_COST", \
	"SQ_Shortcut_to_WM_ORDER_LINE_ITEM_PRE___BUDG_COST_CURRENCY_CODE as BUDG_COST_CURRENCY_CODE", \
	"SQ_Shortcut_to_WM_ORDER_LINE_ITEM_PRE___BUDG_COST as BUDG_COST", \
	"SQ_Shortcut_to_WM_ORDER_LINE_ITEM_PRE___ACTUAL_COST_CURRENCY_CODE as ACTUAL_COST_CURRENCY_CODE", \
	"SQ_Shortcut_to_WM_ORDER_LINE_ITEM_PRE___TOTAL_MONETARY_VALUE as TOTAL_MONETARY_VALUE", \
	"SQ_Shortcut_to_WM_ORDER_LINE_ITEM_PRE___UNIT_MONETARY_VALUE as UNIT_MONETARY_VALUE", \
	"SQ_Shortcut_to_WM_ORDER_LINE_ITEM_PRE___UNIT_TAX_AMOUNT as UNIT_TAX_AMOUNT", \
	"SQ_Shortcut_to_WM_ORDER_LINE_ITEM_PRE___RTS_ID as RTS_ID", \
	"SQ_Shortcut_to_WM_ORDER_LINE_ITEM_PRE___RTS_LINE_ITEM_ID as RTS_LINE_ITEM_ID", \
	"SQ_Shortcut_to_WM_ORDER_LINE_ITEM_PRE___STD_PACK_QTY as STD_PACK_QTY", \
	"SQ_Shortcut_to_WM_ORDER_LINE_ITEM_PRE___PRODUCT_CLASS_ID as PRODUCT_CLASS_ID", \
	"SQ_Shortcut_to_WM_ORDER_LINE_ITEM_PRE___PROTECTION_LEVEL_ID as PROTECTION_LEVEL_ID", \
	"SQ_Shortcut_to_WM_ORDER_LINE_ITEM_PRE___PACKAGE_TYPE_ID as PACKAGE_TYPE_ID", \
	"SQ_Shortcut_to_WM_ORDER_LINE_ITEM_PRE___COMMODITY_CODE_ID as COMMODITY_CODE_ID", \
	"SQ_Shortcut_to_WM_ORDER_LINE_ITEM_PRE___MV_SIZE_UOM_ID as MV_SIZE_UOM_ID", \
	"SQ_Shortcut_to_WM_ORDER_LINE_ITEM_PRE___QTY_UOM_ID_BASE as QTY_UOM_ID_BASE", \
	"SQ_Shortcut_to_WM_ORDER_LINE_ITEM_PRE___MV_CURRENCY_CODE as MV_CURRENCY_CODE", \
	"SQ_Shortcut_to_WM_ORDER_LINE_ITEM_PRE___SHIPPED_QTY as SHIPPED_QTY", \
	"SQ_Shortcut_to_WM_ORDER_LINE_ITEM_PRE___RECEIVED_QTY as RECEIVED_QTY", \
	"SQ_Shortcut_to_WM_ORDER_LINE_ITEM_PRE___PRIORITY as PRIORITY", \
	"SQ_Shortcut_to_WM_ORDER_LINE_ITEM_PRE___MERCHANDIZING_DEPARTMENT_ID as MERCHANDIZING_DEPARTMENT_ID", \
	"SQ_Shortcut_to_WM_ORDER_LINE_ITEM_PRE___UN_NUMBER_ID as UN_NUMBER_ID", \
	"SQ_Shortcut_to_WM_ORDER_LINE_ITEM_PRE___PICKUP_REFERENCE_NUMBER as PICKUP_REFERENCE_NUMBER", \
	"SQ_Shortcut_to_WM_ORDER_LINE_ITEM_PRE___DELIVERY_REFERENCE_NUMBER as DELIVERY_REFERENCE_NUMBER", \
	"SQ_Shortcut_to_WM_ORDER_LINE_ITEM_PRE___CNTRY_OF_ORGN as CNTRY_OF_ORGN", \
	"SQ_Shortcut_to_WM_ORDER_LINE_ITEM_PRE___PROD_STAT as PROD_STAT", \
	"SQ_Shortcut_to_WM_ORDER_LINE_ITEM_PRE___STACK_RANK as STACK_RANK", \
	"SQ_Shortcut_to_WM_ORDER_LINE_ITEM_PRE___STACK_LENGTH_VALUE as STACK_LENGTH_VALUE", \
	"SQ_Shortcut_to_WM_ORDER_LINE_ITEM_PRE___STACK_LENGTH_STANDARD_UOM as STACK_LENGTH_STANDARD_UOM", \
	"SQ_Shortcut_to_WM_ORDER_LINE_ITEM_PRE___STACK_WIDTH_VALUE as STACK_WIDTH_VALUE", \
	"SQ_Shortcut_to_WM_ORDER_LINE_ITEM_PRE___STACK_WIDTH_STANDARD_UOM as STACK_WIDTH_STANDARD_UOM", \
	"SQ_Shortcut_to_WM_ORDER_LINE_ITEM_PRE___STACK_HEIGHT_VALUE as STACK_HEIGHT_VALUE", \
	"SQ_Shortcut_to_WM_ORDER_LINE_ITEM_PRE___STACK_HEIGHT_STANDARD_UOM as STACK_HEIGHT_STANDARD_UOM", \
	"SQ_Shortcut_to_WM_ORDER_LINE_ITEM_PRE___STACK_DIAMETER_VALUE as STACK_DIAMETER_VALUE", \
	"SQ_Shortcut_to_WM_ORDER_LINE_ITEM_PRE___STACK_DIAMETER_STANDARD_UOM as STACK_DIAMETER_STANDARD_UOM", \
	"SQ_Shortcut_to_WM_ORDER_LINE_ITEM_PRE___CREATED_SOURCE_TYPE as CREATED_SOURCE_TYPE", \
	"SQ_Shortcut_to_WM_ORDER_LINE_ITEM_PRE___CREATED_SOURCE as CREATED_SOURCE", \
	"SQ_Shortcut_to_WM_ORDER_LINE_ITEM_PRE___CREATED_DTTM as CREATED_DTTM", \
	"SQ_Shortcut_to_WM_ORDER_LINE_ITEM_PRE___LAST_UPDATED_SOURCE_TYPE as LAST_UPDATED_SOURCE_TYPE", \
	"SQ_Shortcut_to_WM_ORDER_LINE_ITEM_PRE___LAST_UPDATED_SOURCE as LAST_UPDATED_SOURCE", \
	"SQ_Shortcut_to_WM_ORDER_LINE_ITEM_PRE___LAST_UPDATED_DTTM as LAST_UPDATED_DTTM", \
	"SQ_Shortcut_to_WM_ORDER_LINE_ITEM_PRE___HIBERNATE_VERSION as HIBERNATE_VERSION", \
	"SQ_Shortcut_to_WM_ORDER_LINE_ITEM_PRE___CUBE_MULTIPLE_QTY as CUBE_MULTIPLE_QTY", \
	"SQ_Shortcut_to_WM_ORDER_LINE_ITEM_PRE___DO_DTL_STATUS as DO_DTL_STATUS", \
	"SQ_Shortcut_to_WM_ORDER_LINE_ITEM_PRE___INTERNAL_ORDER_SEQ_NBR as INTERNAL_ORDER_SEQ_NBR", \
	"SQ_Shortcut_to_WM_ORDER_LINE_ITEM_PRE___IS_EMERGENCY as IS_EMERGENCY", \
	"SQ_Shortcut_to_WM_ORDER_LINE_ITEM_PRE___LPN_SIZE as LPN_SIZE", \
	"SQ_Shortcut_to_WM_ORDER_LINE_ITEM_PRE___MANUFACTURING_DTTM as MANUFACTURING_DTTM", \
	"SQ_Shortcut_to_WM_ORDER_LINE_ITEM_PRE___ORDER_LINE_ID as ORDER_LINE_ID", \
	"SQ_Shortcut_to_WM_ORDER_LINE_ITEM_PRE___PACK_RATE as PACK_RATE", \
	"SQ_Shortcut_to_WM_ORDER_LINE_ITEM_PRE___ALLOCATED_QTY as ALLOCATED_QTY", \
	"SQ_Shortcut_to_WM_ORDER_LINE_ITEM_PRE___PLANNED_SHIP_DATE as PLANNED_SHIP_DATE", \
	"SQ_Shortcut_to_WM_ORDER_LINE_ITEM_PRE___PPACK_QTY as PPACK_QTY", \
	"SQ_Shortcut_to_WM_ORDER_LINE_ITEM_PRE___STD_BUNDLE_QTY as STD_BUNDLE_QTY", \
	"SQ_Shortcut_to_WM_ORDER_LINE_ITEM_PRE___STD_LPN_QTY as STD_LPN_QTY", \
	"SQ_Shortcut_to_WM_ORDER_LINE_ITEM_PRE___STD_LPN_VOL as STD_LPN_VOL", \
	"SQ_Shortcut_to_WM_ORDER_LINE_ITEM_PRE___STD_LPN_WT as STD_LPN_WT", \
	"SQ_Shortcut_to_WM_ORDER_LINE_ITEM_PRE___UNIT_COST as UNIT_COST", \
	"SQ_Shortcut_to_WM_ORDER_LINE_ITEM_PRE___UNIT_PRICE_AMOUNT as UNIT_PRICE_AMOUNT", \
	"SQ_Shortcut_to_WM_ORDER_LINE_ITEM_PRE___UNIT_VOL as UNIT_VOL", \
	"SQ_Shortcut_to_WM_ORDER_LINE_ITEM_PRE___UNIT_WT as UNIT_WT", \
	"SQ_Shortcut_to_WM_ORDER_LINE_ITEM_PRE___USER_CANCELED_QTY as USER_CANCELED_QTY", \
	"SQ_Shortcut_to_WM_ORDER_LINE_ITEM_PRE___WAVE_PROC_TYPE as WAVE_PROC_TYPE", \
	"SQ_Shortcut_to_WM_ORDER_LINE_ITEM_PRE___DELIVERY_END_DTTM as DELIVERY_END_DTTM", \
	"SQ_Shortcut_to_WM_ORDER_LINE_ITEM_PRE___DELIVERY_START_DTTM as DELIVERY_START_DTTM", \
	"SQ_Shortcut_to_WM_ORDER_LINE_ITEM_PRE___EVENT_CODE as EVENT_CODE", \
	"SQ_Shortcut_to_WM_ORDER_LINE_ITEM_PRE___REASON_CODE as REASON_CODE", \
	"SQ_Shortcut_to_WM_ORDER_LINE_ITEM_PRE___EXP_INFO_CODE as EXP_INFO_CODE", \
	"SQ_Shortcut_to_WM_ORDER_LINE_ITEM_PRE___PARTL_FILL as PARTL_FILL", \
	"SQ_Shortcut_to_WM_ORDER_LINE_ITEM_PRE___LINE_TYPE as LINE_TYPE", \
	"SQ_Shortcut_to_WM_ORDER_LINE_ITEM_PRE___REPL_PROC_TYPE as REPL_PROC_TYPE", \
	"SQ_Shortcut_to_WM_ORDER_LINE_ITEM_PRE___ORDER_QTY as ORDER_QTY", \
	"SQ_Shortcut_to_WM_ORDER_LINE_ITEM_PRE___ORIG_ORDER_QTY as ORIG_ORDER_QTY", \
	"SQ_Shortcut_to_WM_ORDER_LINE_ITEM_PRE___RTL_TO_BE_DISTROED_QTY as RTL_TO_BE_DISTROED_QTY", \
	"SQ_Shortcut_to_WM_ORDER_LINE_ITEM_PRE___PRICE as PRICE", \
	"SQ_Shortcut_to_WM_ORDER_LINE_ITEM_PRE___RETAIL_PRICE as RETAIL_PRICE", \
	"SQ_Shortcut_to_WM_ORDER_LINE_ITEM_PRE___UNITS_PAKD as UNITS_PAKD", \
	"SQ_Shortcut_to_WM_ORDER_LINE_ITEM_PRE___MINOR_ORDER_NBR as MINOR_ORDER_NBR", \
	"SQ_Shortcut_to_WM_ORDER_LINE_ITEM_PRE___ITEM_ID as ITEM_ID", \
	"SQ_Shortcut_to_WM_ORDER_LINE_ITEM_PRE___TC_ORDER_LINE_ID as TC_ORDER_LINE_ID", \
	"SQ_Shortcut_to_WM_ORDER_LINE_ITEM_PRE___ACTUAL_SHIPPED_DTTM as ACTUAL_SHIPPED_DTTM", \
	"SQ_Shortcut_to_WM_ORDER_LINE_ITEM_PRE___QTY_UOM_ID as QTY_UOM_ID", \
	"SQ_Shortcut_to_WM_ORDER_LINE_ITEM_PRE___PICKUP_END_DTTM as PICKUP_END_DTTM", \
	"SQ_Shortcut_to_WM_ORDER_LINE_ITEM_PRE___PURCHASE_ORDER_LINE_NUMBER as PURCHASE_ORDER_LINE_NUMBER", \
	"SQ_Shortcut_to_WM_ORDER_LINE_ITEM_PRE___PICKUP_START_DTTM as PICKUP_START_DTTM", \
	"SQ_Shortcut_to_WM_ORDER_LINE_ITEM_PRE___REFERENCE_LINE_ITEM_ID as REFERENCE_LINE_ITEM_ID", \
	"SQ_Shortcut_to_WM_ORDER_LINE_ITEM_PRE___REFERENCE_ORDER_ID as REFERENCE_ORDER_ID", \
	"SQ_Shortcut_to_WM_ORDER_LINE_ITEM_PRE___REPL_WAVE_RUN as REPL_WAVE_RUN", \
	"SQ_Shortcut_to_WM_ORDER_LINE_ITEM_PRE___STD_PALLET_QTY as STD_PALLET_QTY", \
	"SQ_Shortcut_to_WM_ORDER_LINE_ITEM_PRE___STD_SUB_PACK_QTY as STD_SUB_PACK_QTY", \
	"SQ_Shortcut_to_WM_ORDER_LINE_ITEM_PRE___STORE_DEPT as STORE_DEPT", \
	"SQ_Shortcut_to_WM_ORDER_LINE_ITEM_PRE___ALLOC_TYPE as ALLOC_TYPE", \
	"SQ_Shortcut_to_WM_ORDER_LINE_ITEM_PRE___BATCH_NBR as BATCH_NBR", \
	"SQ_Shortcut_to_WM_ORDER_LINE_ITEM_PRE___BATCH_REQUIREMENT_TYPE as BATCH_REQUIREMENT_TYPE", \
	"SQ_Shortcut_to_WM_ORDER_LINE_ITEM_PRE___CHUTE_ASSIGN_TYPE as CHUTE_ASSIGN_TYPE", \
	"SQ_Shortcut_to_WM_ORDER_LINE_ITEM_PRE___CUSTOM_TAG as CUSTOM_TAG", \
	"SQ_Shortcut_to_WM_ORDER_LINE_ITEM_PRE___CUSTOMER_ITEM as CUSTOMER_ITEM", \
	"SQ_Shortcut_to_WM_ORDER_LINE_ITEM_PRE___INTERNAL_ORDER_ID as INTERNAL_ORDER_ID", \
	"SQ_Shortcut_to_WM_ORDER_LINE_ITEM_PRE___INVN_TYPE as INVN_TYPE", \
	"SQ_Shortcut_to_WM_ORDER_LINE_ITEM_PRE___ITEM_ATTR_1 as ITEM_ATTR_1", \
	"SQ_Shortcut_to_WM_ORDER_LINE_ITEM_PRE___ITEM_ATTR_2 as ITEM_ATTR_2", \
	"SQ_Shortcut_to_WM_ORDER_LINE_ITEM_PRE___ITEM_ATTR_3 as ITEM_ATTR_3", \
	"SQ_Shortcut_to_WM_ORDER_LINE_ITEM_PRE___ITEM_ATTR_4 as ITEM_ATTR_4", \
	"SQ_Shortcut_to_WM_ORDER_LINE_ITEM_PRE___ITEM_ATTR_5 as ITEM_ATTR_5", \
	"SQ_Shortcut_to_WM_ORDER_LINE_ITEM_PRE___LPN_BRK_ATTRIB as LPN_BRK_ATTRIB", \
	"SQ_Shortcut_to_WM_ORDER_LINE_ITEM_PRE___MERCH_GRP as MERCH_GRP", \
	"SQ_Shortcut_to_WM_ORDER_LINE_ITEM_PRE___MERCH_TYPE as MERCH_TYPE", \
	"SQ_Shortcut_to_WM_ORDER_LINE_ITEM_PRE___PACK_ZONE as PACK_ZONE", \
	"SQ_Shortcut_to_WM_ORDER_LINE_ITEM_PRE___PALLET_TYPE as PALLET_TYPE", \
	"SQ_Shortcut_to_WM_ORDER_LINE_ITEM_PRE___PICK_LOCN_ASSIGN_TYPE as PICK_LOCN_ASSIGN_TYPE", \
	"SQ_Shortcut_to_WM_ORDER_LINE_ITEM_PRE___PICK_LOCN_ID as PICK_LOCN_ID", \
	"SQ_Shortcut_to_WM_ORDER_LINE_ITEM_PRE___PPACK_GRP_CODE as PPACK_GRP_CODE", \
	"SQ_Shortcut_to_WM_ORDER_LINE_ITEM_PRE___PRICE_TKT_TYPE as PRICE_TKT_TYPE", \
	"SQ_Shortcut_to_WM_ORDER_LINE_ITEM_PRE___SERIAL_NUMBER_REQUIRED_FLAG as SERIAL_NUMBER_REQUIRED_FLAG", \
	"SQ_Shortcut_to_WM_ORDER_LINE_ITEM_PRE___SKU_GTIN as SKU_GTIN", \
	"SQ_Shortcut_to_WM_ORDER_LINE_ITEM_PRE___SKU_SUB_CODE_ID as SKU_SUB_CODE_ID", \
	"SQ_Shortcut_to_WM_ORDER_LINE_ITEM_PRE___SKU_SUB_CODE_VALUE as SKU_SUB_CODE_VALUE", \
	"SQ_Shortcut_to_WM_ORDER_LINE_ITEM_PRE___VAS_PROCESS_TYPE as VAS_PROCESS_TYPE", \
	"SQ_Shortcut_to_WM_ORDER_LINE_ITEM_PRE___SUBSTITUTED_PARENT_LINE_ID as SUBSTITUTED_PARENT_LINE_ID", \
	"SQ_Shortcut_to_WM_ORDER_LINE_ITEM_PRE___IS_CANCELLED as IS_CANCELLED", \
	"SQ_Shortcut_to_WM_ORDER_LINE_ITEM_PRE___ITEM_NAME as ITEM_NAME", \
	"SQ_Shortcut_to_WM_ORDER_LINE_ITEM_PRE___ALLOC_LINE_ID as ALLOC_LINE_ID", \
	"SQ_Shortcut_to_WM_ORDER_LINE_ITEM_PRE___ALLOCATION_SOURCE_ID as ALLOCATION_SOURCE_ID", \
	"SQ_Shortcut_to_WM_ORDER_LINE_ITEM_PRE___ALLOCATION_SOURCE_LINE_ID as ALLOCATION_SOURCE_LINE_ID", \
	"SQ_Shortcut_to_WM_ORDER_LINE_ITEM_PRE___ALLOCATION_SOURCE as ALLOCATION_SOURCE", \
	"SQ_Shortcut_to_WM_ORDER_LINE_ITEM_PRE___SHELF_DAYS as SHELF_DAYS", \
	"SQ_Shortcut_to_WM_ORDER_LINE_ITEM_PRE___FULFILLMENT_TYPE as FULFILLMENT_TYPE", \
	"SQ_Shortcut_to_WM_ORDER_LINE_ITEM_PRE___WAVE_NBR as WAVE_NBR", \
	"SQ_Shortcut_to_WM_ORDER_LINE_ITEM_PRE___SHIP_WAVE_NBR as SHIP_WAVE_NBR", \
	"SQ_Shortcut_to_WM_ORDER_LINE_ITEM_PRE___REPL_WAVE_NBR as REPL_WAVE_NBR", \
	"SQ_Shortcut_to_WM_ORDER_LINE_ITEM_PRE___SINGLE_UNIT_FLAG as SINGLE_UNIT_FLAG", \
	"SQ_Shortcut_to_WM_ORDER_LINE_ITEM_PRE___ACTUAL_COST as ACTUAL_COST", \
	"SQ_Shortcut_to_WM_ORDER_LINE_ITEM_PRE___QTY_CONV_FACTOR as QTY_CONV_FACTOR", \
	"SQ_Shortcut_to_WM_ORDER_LINE_ITEM_PRE___PLANNED_WEIGHT as PLANNED_WEIGHT", \
	"SQ_Shortcut_to_WM_ORDER_LINE_ITEM_PRE___RECEIVED_WEIGHT as RECEIVED_WEIGHT", \
	"SQ_Shortcut_to_WM_ORDER_LINE_ITEM_PRE___SHIPPED_WEIGHT as SHIPPED_WEIGHT", \
	"SQ_Shortcut_to_WM_ORDER_LINE_ITEM_PRE___WEIGHT_UOM_ID_BASE as WEIGHT_UOM_ID_BASE", \
	"SQ_Shortcut_to_WM_ORDER_LINE_ITEM_PRE___WEIGHT_UOM_ID as WEIGHT_UOM_ID", \
	"SQ_Shortcut_to_WM_ORDER_LINE_ITEM_PRE___PLANNED_VOLUME as PLANNED_VOLUME", \
	"SQ_Shortcut_to_WM_ORDER_LINE_ITEM_PRE___RECEIVED_VOLUME as RECEIVED_VOLUME", \
	"SQ_Shortcut_to_WM_ORDER_LINE_ITEM_PRE___SHIPPED_VOLUME as SHIPPED_VOLUME", \
	"SQ_Shortcut_to_WM_ORDER_LINE_ITEM_PRE___VOLUME_UOM_ID_BASE as VOLUME_UOM_ID_BASE", \
	"SQ_Shortcut_to_WM_ORDER_LINE_ITEM_PRE___VOLUME_UOM_ID as VOLUME_UOM_ID", \
	"SQ_Shortcut_to_WM_ORDER_LINE_ITEM_PRE___SIZE1_UOM_ID as SIZE1_UOM_ID", \
	"SQ_Shortcut_to_WM_ORDER_LINE_ITEM_PRE___SIZE1_VALUE as SIZE1_VALUE", \
	"SQ_Shortcut_to_WM_ORDER_LINE_ITEM_PRE___RECEIVED_SIZE1 as RECEIVED_SIZE1", \
	"SQ_Shortcut_to_WM_ORDER_LINE_ITEM_PRE___SHIPPED_SIZE1 as SHIPPED_SIZE1", \
	"SQ_Shortcut_to_WM_ORDER_LINE_ITEM_PRE___SIZE2_UOM_ID as SIZE2_UOM_ID", \
	"SQ_Shortcut_to_WM_ORDER_LINE_ITEM_PRE___SIZE2_VALUE as SIZE2_VALUE", \
	"SQ_Shortcut_to_WM_ORDER_LINE_ITEM_PRE___RECEIVED_SIZE2 as RECEIVED_SIZE2", \
	"SQ_Shortcut_to_WM_ORDER_LINE_ITEM_PRE___SHIPPED_SIZE2 as SHIPPED_SIZE2", \
	"SQ_Shortcut_to_WM_ORDER_LINE_ITEM_PRE___LPN_TYPE as LPN_TYPE", \
	"SQ_Shortcut_to_WM_ORDER_LINE_ITEM_PRE___ORDER_CONSOL_ATTR as ORDER_CONSOL_ATTR", \
	"SQ_Shortcut_to_WM_ORDER_LINE_ITEM_PRE___SKU_BREAK_ATTR as SKU_BREAK_ATTR", \
	"SQ_Shortcut_to_WM_ORDER_LINE_ITEM_PRE___PURCHASE_ORDER_NUMBER as PURCHASE_ORDER_NUMBER", \
	"SQ_Shortcut_to_WM_ORDER_LINE_ITEM_PRE___EXT_PURCHASE_ORDER as EXT_PURCHASE_ORDER", \
	"SQ_Shortcut_to_WM_ORDER_LINE_ITEM_PRE___CRITCL_DIM_1 as CRITCL_DIM_1", \
	"SQ_Shortcut_to_WM_ORDER_LINE_ITEM_PRE___CRITCL_DIM_2 as CRITCL_DIM_2", \
	"SQ_Shortcut_to_WM_ORDER_LINE_ITEM_PRE___CRITCL_DIM_3 as CRITCL_DIM_3", \
	"SQ_Shortcut_to_WM_ORDER_LINE_ITEM_PRE___ASSORT_NBR as ASSORT_NBR", \
	"SQ_Shortcut_to_WM_ORDER_LINE_ITEM_PRE___DESCRIPTION as DESCRIPTION", \
	"SQ_Shortcut_to_WM_ORDER_LINE_ITEM_PRE___ORIGINAL_ORDERED_ITEM_ID as ORIGINAL_ORDERED_ITEM_ID", \
	"SQ_Shortcut_to_WM_ORDER_LINE_ITEM_PRE___SUBSTITUTION_TYPE as SUBSTITUTION_TYPE", \
	"SQ_Shortcut_to_WM_ORDER_LINE_ITEM_PRE___BACK_ORD_REASON as BACK_ORD_REASON", \
	"SQ_Shortcut_to_WM_ORDER_LINE_ITEM_PRE___FREIGHT_REVENUE_CURRENCY_CODE as FREIGHT_REVENUE_CURRENCY_CODE", \
	"SQ_Shortcut_to_WM_ORDER_LINE_ITEM_PRE___FREIGHT_REVENUE as FREIGHT_REVENUE", \
	"SQ_Shortcut_to_WM_ORDER_LINE_ITEM_PRE___IS_CHASE_CREATED_LINE as IS_CHASE_CREATED_LINE", \
	"SQ_Shortcut_to_WM_ORDER_LINE_ITEM_PRE___REF_FIELD4 as REF_FIELD4", \
	"SQ_Shortcut_to_WM_ORDER_LINE_ITEM_PRE___REF_FIELD5 as REF_FIELD5", \
	"SQ_Shortcut_to_WM_ORDER_LINE_ITEM_PRE___REF_FIELD6 as REF_FIELD6", \
	"SQ_Shortcut_to_WM_ORDER_LINE_ITEM_PRE___REF_FIELD7 as REF_FIELD7", \
	"SQ_Shortcut_to_WM_ORDER_LINE_ITEM_PRE___REF_FIELD8 as REF_FIELD8", \
	"SQ_Shortcut_to_WM_ORDER_LINE_ITEM_PRE___REF_FIELD9 as REF_FIELD9", \
	"SQ_Shortcut_to_WM_ORDER_LINE_ITEM_PRE___REF_FIELD10 as REF_FIELD10", \
	"SQ_Shortcut_to_WM_ORDER_LINE_ITEM_PRE___REF_NUM1 as REF_NUM1", \
	"SQ_Shortcut_to_WM_ORDER_LINE_ITEM_PRE___REF_NUM2 as REF_NUM2", \
	"SQ_Shortcut_to_WM_ORDER_LINE_ITEM_PRE___REF_NUM3 as REF_NUM3", \
	"SQ_Shortcut_to_WM_ORDER_LINE_ITEM_PRE___REF_NUM4 as REF_NUM4", \
	"SQ_Shortcut_to_WM_ORDER_LINE_ITEM_PRE___REF_NUM5 as REF_NUM5", \
	"SQ_Shortcut_to_WM_ORDER_LINE_ITEM_PRE___IS_GIFT as IS_GIFT", \
	"SQ_Shortcut_to_WM_ORDER_LINE_ITEM_PRE___ADJUSTED_ORDER_QTY as ADJUSTED_ORDER_QTY", \
	"SQ_Shortcut_to_WM_ORDER_LINE_ITEM_PRE___PRE_RECEIPT_STATUS as PRE_RECEIPT_STATUS", \
	"SQ_Shortcut_to_WM_ORDER_LINE_ITEM_PRE___ALLOW_REVIVAL_RECEIPT_ALLOC as ALLOW_REVIVAL_RECEIPT_ALLOC", \
	"SQ_Shortcut_to_WM_ORDER_LINE_ITEM_PRE___SEGMENT_NAME as SEGMENT_NAME", \
	"SQ_Shortcut_to_WM_ORDER_LINE_ITEM_PRE___EFFECTIVE_RANK as EFFECTIVE_RANK", \
	"SQ_Shortcut_to_WM_ORDER_LINE_ITEM_PRE___WM_RECEIPT_ALLOCATED as WM_RECEIPT_ALLOCATED", \
	"SQ_Shortcut_to_WM_ORDER_LINE_ITEM_PRE___GIFT_CARD_VALUE as GIFT_CARD_VALUE", \
	"SQ_Shortcut_to_WM_ORDER_LINE_ITEM_PRE___REF_BOOLEAN1 as REF_BOOLEAN1", \
	"SQ_Shortcut_to_WM_ORDER_LINE_ITEM_PRE___REF_BOOLEAN2 as REF_BOOLEAN2", \
	"SQ_Shortcut_to_WM_ORDER_LINE_ITEM_PRE___REF_SYSCODE1 as REF_SYSCODE1", \
	"SQ_Shortcut_to_WM_ORDER_LINE_ITEM_PRE___REF_SYSCODE2 as REF_SYSCODE2", \
	"SQ_Shortcut_to_WM_ORDER_LINE_ITEM_PRE___REF_SYSCODE3 as REF_SYSCODE3", \
	"SQ_Shortcut_to_WM_ORDER_LINE_ITEM_PRE___HARD_ALLOC_REASON_CODE as HARD_ALLOC_REASON_CODE", \
	"SQ_Shortcut_to_WM_ORDER_LINE_ITEM_PRE___LOCKED as LOCKED" \
)

# COMMAND ----------
# Processing node SQ_Shortcut_to_SITE_PROFILE, type SOURCE 
# COLUMN COUNT: 2

SQ_Shortcut_to_SITE_PROFILE = spark.sql(f"""SELECT
SITE_PROFILE.LOCATION_ID,
SITE_PROFILE.STORE_NBR
FROM SITE_PROFILE""").withColumn("sys_row_id", monotonically_increasing_id())

# COMMAND ----------
# Processing node JNR_SITE_PROFILE, type JOINER 
# COLUMN COUNT: 211

JNR_SITE_PROFILE = SQ_Shortcut_to_SITE_PROFILE.join(EXP_INT_CONVERSION,[SQ_Shortcut_to_SITE_PROFILE.STORE_NBR == EXP_INT_CONVERSION.o_DC_NBR],'inner')

# COMMAND ----------
# Processing node JNR_WM_ORDER_LINE_ITEM, type JOINER . Note: using additional SELECT to rename incoming columns
# COLUMN COUNT: 215

# for each involved DataFrame, append the dataframe name to each column
JNR_SITE_PROFILE_temp = JNR_SITE_PROFILE.toDF(*["JNR_SITE_PROFILE___" + col for col in JNR_SITE_PROFILE.columns])
SQ_Shortcut_to_WM_ORDER_LINE_ITEM_temp = SQ_Shortcut_to_WM_ORDER_LINE_ITEM.toDF(*["SQ_Shortcut_to_WM_ORDER_LINE_ITEM___" + col for col in SQ_Shortcut_to_WM_ORDER_LINE_ITEM.columns])

JNR_WM_ORDER_LINE_ITEM = SQ_Shortcut_to_WM_ORDER_LINE_ITEM_temp.join(JNR_SITE_PROFILE_temp,[SQ_Shortcut_to_WM_ORDER_LINE_ITEM_temp.SQ_Shortcut_to_WM_ORDER_LINE_ITEM___LOCATION_ID == JNR_SITE_PROFILE_temp.JNR_SITE_PROFILE___LOCATION_ID, SQ_Shortcut_to_WM_ORDER_LINE_ITEM_temp.SQ_Shortcut_to_WM_ORDER_LINE_ITEM___WM_ORDER_ID == JNR_SITE_PROFILE_temp.JNR_SITE_PROFILE___ORDER_ID, SQ_Shortcut_to_WM_ORDER_LINE_ITEM_temp.SQ_Shortcut_to_WM_ORDER_LINE_ITEM___WM_LINE_ITEM_ID == JNR_SITE_PROFILE_temp.JNR_SITE_PROFILE___LINE_ITEM_ID],'right_outer').selectExpr( \
	"JNR_SITE_PROFILE___LOCATION_ID as LOCATION_ID", \
	"JNR_SITE_PROFILE___ORDER_ID as ORDER_ID", \
	"JNR_SITE_PROFILE___LINE_ITEM_ID as LINE_ITEM_ID", \
	"JNR_SITE_PROFILE___PARENT_LINE_ITEM_ID as PARENT_LINE_ITEM_ID", \
	"JNR_SITE_PROFILE___TC_COMPANY_ID as TC_COMPANY_ID", \
	"JNR_SITE_PROFILE___COMMODITY_CLASS as COMMODITY_CLASS", \
	"JNR_SITE_PROFILE___REF_FIELD1 as REF_FIELD1", \
	"JNR_SITE_PROFILE___REF_FIELD2 as REF_FIELD2", \
	"JNR_SITE_PROFILE___REF_FIELD3 as REF_FIELD3", \
	"JNR_SITE_PROFILE___EXT_SYS_LINE_ITEM_ID as EXT_SYS_LINE_ITEM_ID", \
	"JNR_SITE_PROFILE___MASTER_ORDER_ID as MASTER_ORDER_ID", \
	"JNR_SITE_PROFILE___MO_LINE_ITEM_ID as MO_LINE_ITEM_ID", \
	"JNR_SITE_PROFILE___IS_HAZMAT as IS_HAZMAT", \
	"JNR_SITE_PROFILE___IS_STACKABLE as IS_STACKABLE", \
	"JNR_SITE_PROFILE___HAS_ERRORS as HAS_ERRORS", \
	"JNR_SITE_PROFILE___ORIG_BUDG_COST as ORIG_BUDG_COST", \
	"JNR_SITE_PROFILE___BUDG_COST_CURRENCY_CODE as BUDG_COST_CURRENCY_CODE", \
	"JNR_SITE_PROFILE___BUDG_COST as BUDG_COST", \
	"JNR_SITE_PROFILE___ACTUAL_COST_CURRENCY_CODE as ACTUAL_COST_CURRENCY_CODE", \
	"JNR_SITE_PROFILE___TOTAL_MONETARY_VALUE as TOTAL_MONETARY_VALUE", \
	"JNR_SITE_PROFILE___UNIT_MONETARY_VALUE as UNIT_MONETARY_VALUE", \
	"JNR_SITE_PROFILE___UNIT_TAX_AMOUNT as UNIT_TAX_AMOUNT", \
	"JNR_SITE_PROFILE___RTS_ID as RTS_ID", \
	"JNR_SITE_PROFILE___RTS_LINE_ITEM_ID as RTS_LINE_ITEM_ID", \
	"JNR_SITE_PROFILE___STD_PACK_QTY as STD_PACK_QTY", \
	"JNR_SITE_PROFILE___PRODUCT_CLASS_ID as PRODUCT_CLASS_ID", \
	"JNR_SITE_PROFILE___PROTECTION_LEVEL_ID as PROTECTION_LEVEL_ID", \
	"JNR_SITE_PROFILE___PACKAGE_TYPE_ID as PACKAGE_TYPE_ID", \
	"JNR_SITE_PROFILE___COMMODITY_CODE_ID as COMMODITY_CODE_ID", \
	"JNR_SITE_PROFILE___MV_SIZE_UOM_ID as MV_SIZE_UOM_ID", \
	"JNR_SITE_PROFILE___QTY_UOM_ID_BASE as QTY_UOM_ID_BASE", \
	"JNR_SITE_PROFILE___MV_CURRENCY_CODE as MV_CURRENCY_CODE", \
	"JNR_SITE_PROFILE___SHIPPED_QTY as SHIPPED_QTY", \
	"JNR_SITE_PROFILE___RECEIVED_QTY as RECEIVED_QTY", \
	"JNR_SITE_PROFILE___PRIORITY as PRIORITY", \
	"JNR_SITE_PROFILE___MERCHANDIZING_DEPARTMENT_ID as MERCHANDIZING_DEPARTMENT_ID", \
	"JNR_SITE_PROFILE___UN_NUMBER_ID as UN_NUMBER_ID", \
	"JNR_SITE_PROFILE___PICKUP_REFERENCE_NUMBER as PICKUP_REFERENCE_NUMBER", \
	"JNR_SITE_PROFILE___DELIVERY_REFERENCE_NUMBER as DELIVERY_REFERENCE_NUMBER", \
	"JNR_SITE_PROFILE___CNTRY_OF_ORGN as CNTRY_OF_ORGN", \
	"JNR_SITE_PROFILE___PROD_STAT as PROD_STAT", \
	"JNR_SITE_PROFILE___STACK_RANK as STACK_RANK", \
	"JNR_SITE_PROFILE___STACK_LENGTH_VALUE as STACK_LENGTH_VALUE", \
	"JNR_SITE_PROFILE___STACK_LENGTH_STANDARD_UOM as STACK_LENGTH_STANDARD_UOM", \
	"JNR_SITE_PROFILE___STACK_WIDTH_VALUE as STACK_WIDTH_VALUE", \
	"JNR_SITE_PROFILE___STACK_WIDTH_STANDARD_UOM as STACK_WIDTH_STANDARD_UOM", \
	"JNR_SITE_PROFILE___STACK_HEIGHT_VALUE as STACK_HEIGHT_VALUE", \
	"JNR_SITE_PROFILE___STACK_HEIGHT_STANDARD_UOM as STACK_HEIGHT_STANDARD_UOM", \
	"JNR_SITE_PROFILE___STACK_DIAMETER_VALUE as STACK_DIAMETER_VALUE", \
	"JNR_SITE_PROFILE___STACK_DIAMETER_STANDARD_UOM as STACK_DIAMETER_STANDARD_UOM", \
	"JNR_SITE_PROFILE___CREATED_SOURCE_TYPE as CREATED_SOURCE_TYPE", \
	"JNR_SITE_PROFILE___CREATED_SOURCE as CREATED_SOURCE", \
	"JNR_SITE_PROFILE___CREATED_DTTM as CREATED_DTTM", \
	"JNR_SITE_PROFILE___LAST_UPDATED_SOURCE_TYPE as LAST_UPDATED_SOURCE_TYPE", \
	"JNR_SITE_PROFILE___LAST_UPDATED_SOURCE as LAST_UPDATED_SOURCE", \
	"JNR_SITE_PROFILE___LAST_UPDATED_DTTM as LAST_UPDATED_DTTM", \
	"JNR_SITE_PROFILE___HIBERNATE_VERSION as HIBERNATE_VERSION", \
	"JNR_SITE_PROFILE___CUBE_MULTIPLE_QTY as CUBE_MULTIPLE_QTY", \
	"JNR_SITE_PROFILE___DO_DTL_STATUS as DO_DTL_STATUS", \
	"JNR_SITE_PROFILE___INTERNAL_ORDER_SEQ_NBR as INTERNAL_ORDER_SEQ_NBR", \
	"JNR_SITE_PROFILE___IS_EMERGENCY as IS_EMERGENCY", \
	"JNR_SITE_PROFILE___LPN_SIZE as LPN_SIZE", \
	"JNR_SITE_PROFILE___MANUFACTURING_DTTM as MANUFACTURING_DTTM", \
	"JNR_SITE_PROFILE___ORDER_LINE_ID as ORDER_LINE_ID", \
	"JNR_SITE_PROFILE___PACK_RATE as PACK_RATE", \
	"JNR_SITE_PROFILE___ALLOCATED_QTY as ALLOCATED_QTY", \
	"JNR_SITE_PROFILE___PLANNED_SHIP_DATE as PLANNED_SHIP_DATE", \
	"JNR_SITE_PROFILE___PPACK_QTY as PPACK_QTY", \
	"JNR_SITE_PROFILE___STD_BUNDLE_QTY as STD_BUNDLE_QTY", \
	"JNR_SITE_PROFILE___STD_LPN_QTY as STD_LPN_QTY", \
	"JNR_SITE_PROFILE___STD_LPN_VOL as STD_LPN_VOL", \
	"JNR_SITE_PROFILE___STD_LPN_WT as STD_LPN_WT", \
	"JNR_SITE_PROFILE___UNIT_COST as UNIT_COST", \
	"JNR_SITE_PROFILE___UNIT_PRICE_AMOUNT as UNIT_PRICE_AMOUNT", \
	"JNR_SITE_PROFILE___UNIT_VOL as UNIT_VOL", \
	"JNR_SITE_PROFILE___UNIT_WT as UNIT_WT", \
	"JNR_SITE_PROFILE___USER_CANCELED_QTY as USER_CANCELED_QTY", \
	"JNR_SITE_PROFILE___WAVE_PROC_TYPE as WAVE_PROC_TYPE", \
	"JNR_SITE_PROFILE___DELIVERY_END_DTTM as DELIVERY_END_DTTM", \
	"JNR_SITE_PROFILE___DELIVERY_START_DTTM as DELIVERY_START_DTTM", \
	"JNR_SITE_PROFILE___EVENT_CODE as EVENT_CODE", \
	"JNR_SITE_PROFILE___REASON_CODE as REASON_CODE", \
	"JNR_SITE_PROFILE___EXP_INFO_CODE as EXP_INFO_CODE", \
	"JNR_SITE_PROFILE___PARTL_FILL as PARTL_FILL", \
	"JNR_SITE_PROFILE___LINE_TYPE as LINE_TYPE", \
	"JNR_SITE_PROFILE___REPL_PROC_TYPE as REPL_PROC_TYPE", \
	"JNR_SITE_PROFILE___ORDER_QTY as ORDER_QTY", \
	"JNR_SITE_PROFILE___ORIG_ORDER_QTY as ORIG_ORDER_QTY", \
	"JNR_SITE_PROFILE___RTL_TO_BE_DISTROED_QTY as RTL_TO_BE_DISTROED_QTY", \
	"JNR_SITE_PROFILE___PRICE as PRICE", \
	"JNR_SITE_PROFILE___RETAIL_PRICE as RETAIL_PRICE", \
	"JNR_SITE_PROFILE___UNITS_PAKD as UNITS_PAKD", \
	"JNR_SITE_PROFILE___MINOR_ORDER_NBR as MINOR_ORDER_NBR", \
	"JNR_SITE_PROFILE___ITEM_ID as ITEM_ID", \
	"JNR_SITE_PROFILE___TC_ORDER_LINE_ID as TC_ORDER_LINE_ID", \
	"JNR_SITE_PROFILE___ACTUAL_SHIPPED_DTTM as ACTUAL_SHIPPED_DTTM", \
	"JNR_SITE_PROFILE___QTY_UOM_ID as QTY_UOM_ID", \
	"JNR_SITE_PROFILE___PICKUP_END_DTTM as PICKUP_END_DTTM", \
	"JNR_SITE_PROFILE___PURCHASE_ORDER_LINE_NUMBER as PURCHASE_ORDER_LINE_NUMBER", \
	"JNR_SITE_PROFILE___PICKUP_START_DTTM as PICKUP_START_DTTM", \
	"JNR_SITE_PROFILE___REFERENCE_LINE_ITEM_ID as REFERENCE_LINE_ITEM_ID", \
	"JNR_SITE_PROFILE___REFERENCE_ORDER_ID as REFERENCE_ORDER_ID", \
	"JNR_SITE_PROFILE___REPL_WAVE_RUN as REPL_WAVE_RUN", \
	"JNR_SITE_PROFILE___STD_PALLET_QTY as STD_PALLET_QTY", \
	"JNR_SITE_PROFILE___STD_SUB_PACK_QTY as STD_SUB_PACK_QTY", \
	"JNR_SITE_PROFILE___STORE_DEPT as STORE_DEPT", \
	"JNR_SITE_PROFILE___ALLOC_TYPE as ALLOC_TYPE", \
	"JNR_SITE_PROFILE___BATCH_NBR as BATCH_NBR", \
	"JNR_SITE_PROFILE___BATCH_REQUIREMENT_TYPE as BATCH_REQUIREMENT_TYPE", \
	"JNR_SITE_PROFILE___CHUTE_ASSIGN_TYPE as CHUTE_ASSIGN_TYPE", \
	"JNR_SITE_PROFILE___CUSTOM_TAG as CUSTOM_TAG", \
	"JNR_SITE_PROFILE___CUSTOMER_ITEM as CUSTOMER_ITEM", \
	"JNR_SITE_PROFILE___INTERNAL_ORDER_ID as INTERNAL_ORDER_ID", \
	"JNR_SITE_PROFILE___INVN_TYPE as INVN_TYPE", \
	"JNR_SITE_PROFILE___ITEM_ATTR_1 as ITEM_ATTR_1", \
	"JNR_SITE_PROFILE___ITEM_ATTR_2 as ITEM_ATTR_2", \
	"JNR_SITE_PROFILE___ITEM_ATTR_3 as ITEM_ATTR_3", \
	"JNR_SITE_PROFILE___ITEM_ATTR_4 as ITEM_ATTR_4", \
	"JNR_SITE_PROFILE___ITEM_ATTR_5 as ITEM_ATTR_5", \
	"JNR_SITE_PROFILE___LPN_BRK_ATTRIB as LPN_BRK_ATTRIB", \
	"JNR_SITE_PROFILE___MERCH_GRP as MERCH_GRP", \
	"JNR_SITE_PROFILE___MERCH_TYPE as MERCH_TYPE", \
	"JNR_SITE_PROFILE___PACK_ZONE as PACK_ZONE", \
	"JNR_SITE_PROFILE___PALLET_TYPE as PALLET_TYPE", \
	"JNR_SITE_PROFILE___PICK_LOCN_ASSIGN_TYPE as PICK_LOCN_ASSIGN_TYPE", \
	"JNR_SITE_PROFILE___PICK_LOCN_ID as PICK_LOCN_ID", \
	"JNR_SITE_PROFILE___PPACK_GRP_CODE as PPACK_GRP_CODE", \
	"JNR_SITE_PROFILE___PRICE_TKT_TYPE as PRICE_TKT_TYPE", \
	"JNR_SITE_PROFILE___SERIAL_NUMBER_REQUIRED_FLAG as SERIAL_NUMBER_REQUIRED_FLAG", \
	"JNR_SITE_PROFILE___SKU_GTIN as SKU_GTIN", \
	"JNR_SITE_PROFILE___SKU_SUB_CODE_ID as SKU_SUB_CODE_ID", \
	"JNR_SITE_PROFILE___SKU_SUB_CODE_VALUE as SKU_SUB_CODE_VALUE", \
	"JNR_SITE_PROFILE___VAS_PROCESS_TYPE as VAS_PROCESS_TYPE", \
	"JNR_SITE_PROFILE___SUBSTITUTED_PARENT_LINE_ID as SUBSTITUTED_PARENT_LINE_ID", \
	"JNR_SITE_PROFILE___IS_CANCELLED as IS_CANCELLED", \
	"JNR_SITE_PROFILE___ITEM_NAME as ITEM_NAME", \
	"JNR_SITE_PROFILE___ALLOC_LINE_ID as ALLOC_LINE_ID", \
	"JNR_SITE_PROFILE___ALLOCATION_SOURCE_ID as ALLOCATION_SOURCE_ID", \
	"JNR_SITE_PROFILE___ALLOCATION_SOURCE_LINE_ID as ALLOCATION_SOURCE_LINE_ID", \
	"JNR_SITE_PROFILE___ALLOCATION_SOURCE as ALLOCATION_SOURCE", \
	"JNR_SITE_PROFILE___SHELF_DAYS as SHELF_DAYS", \
	"JNR_SITE_PROFILE___FULFILLMENT_TYPE as FULFILLMENT_TYPE", \
	"JNR_SITE_PROFILE___WAVE_NBR as WAVE_NBR", \
	"JNR_SITE_PROFILE___SHIP_WAVE_NBR as SHIP_WAVE_NBR", \
	"JNR_SITE_PROFILE___REPL_WAVE_NBR as REPL_WAVE_NBR", \
	"JNR_SITE_PROFILE___SINGLE_UNIT_FLAG as SINGLE_UNIT_FLAG", \
	"JNR_SITE_PROFILE___ACTUAL_COST as ACTUAL_COST", \
	"JNR_SITE_PROFILE___QTY_CONV_FACTOR as QTY_CONV_FACTOR", \
	"JNR_SITE_PROFILE___PLANNED_WEIGHT as PLANNED_WEIGHT", \
	"JNR_SITE_PROFILE___RECEIVED_WEIGHT as RECEIVED_WEIGHT", \
	"JNR_SITE_PROFILE___SHIPPED_WEIGHT as SHIPPED_WEIGHT", \
	"JNR_SITE_PROFILE___WEIGHT_UOM_ID_BASE as WEIGHT_UOM_ID_BASE", \
	"JNR_SITE_PROFILE___WEIGHT_UOM_ID as WEIGHT_UOM_ID", \
	"JNR_SITE_PROFILE___PLANNED_VOLUME as PLANNED_VOLUME", \
	"JNR_SITE_PROFILE___RECEIVED_VOLUME as RECEIVED_VOLUME", \
	"JNR_SITE_PROFILE___SHIPPED_VOLUME as SHIPPED_VOLUME", \
	"JNR_SITE_PROFILE___VOLUME_UOM_ID_BASE as VOLUME_UOM_ID_BASE", \
	"JNR_SITE_PROFILE___VOLUME_UOM_ID as VOLUME_UOM_ID", \
	"JNR_SITE_PROFILE___SIZE1_UOM_ID as SIZE1_UOM_ID", \
	"JNR_SITE_PROFILE___SIZE1_VALUE as SIZE1_VALUE", \
	"JNR_SITE_PROFILE___RECEIVED_SIZE1 as RECEIVED_SIZE1", \
	"JNR_SITE_PROFILE___SHIPPED_SIZE1 as SHIPPED_SIZE1", \
	"JNR_SITE_PROFILE___SIZE2_UOM_ID as SIZE2_UOM_ID", \
	"JNR_SITE_PROFILE___SIZE2_VALUE as SIZE2_VALUE", \
	"JNR_SITE_PROFILE___RECEIVED_SIZE2 as RECEIVED_SIZE2", \
	"JNR_SITE_PROFILE___SHIPPED_SIZE2 as SHIPPED_SIZE2", \
	"JNR_SITE_PROFILE___LPN_TYPE as LPN_TYPE", \
	"JNR_SITE_PROFILE___ORDER_CONSOL_ATTR as ORDER_CONSOL_ATTR", \
	"JNR_SITE_PROFILE___SKU_BREAK_ATTR as SKU_BREAK_ATTR", \
	"JNR_SITE_PROFILE___PURCHASE_ORDER_NUMBER as PURCHASE_ORDER_NUMBER", \
	"JNR_SITE_PROFILE___EXT_PURCHASE_ORDER as EXT_PURCHASE_ORDER", \
	"JNR_SITE_PROFILE___CRITCL_DIM_1 as CRITCL_DIM_1", \
	"JNR_SITE_PROFILE___CRITCL_DIM_2 as CRITCL_DIM_2", \
	"JNR_SITE_PROFILE___CRITCL_DIM_3 as CRITCL_DIM_3", \
	"JNR_SITE_PROFILE___ASSORT_NBR as ASSORT_NBR", \
	"JNR_SITE_PROFILE___DESCRIPTION as DESCRIPTION", \
	"JNR_SITE_PROFILE___ORIGINAL_ORDERED_ITEM_ID as ORIGINAL_ORDERED_ITEM_ID", \
	"JNR_SITE_PROFILE___SUBSTITUTION_TYPE as SUBSTITUTION_TYPE", \
	"JNR_SITE_PROFILE___BACK_ORD_REASON as BACK_ORD_REASON", \
	"JNR_SITE_PROFILE___FREIGHT_REVENUE_CURRENCY_CODE as FREIGHT_REVENUE_CURRENCY_CODE", \
	"JNR_SITE_PROFILE___FREIGHT_REVENUE as FREIGHT_REVENUE", \
	"JNR_SITE_PROFILE___IS_CHASE_CREATED_LINE as IS_CHASE_CREATED_LINE", \
	"JNR_SITE_PROFILE___REF_FIELD4 as REF_FIELD4", \
	"JNR_SITE_PROFILE___REF_FIELD5 as REF_FIELD5", \
	"JNR_SITE_PROFILE___REF_FIELD6 as REF_FIELD6", \
	"JNR_SITE_PROFILE___REF_FIELD7 as REF_FIELD7", \
	"JNR_SITE_PROFILE___REF_FIELD8 as REF_FIELD8", \
	"JNR_SITE_PROFILE___REF_FIELD9 as REF_FIELD9", \
	"JNR_SITE_PROFILE___REF_FIELD10 as REF_FIELD10", \
	"JNR_SITE_PROFILE___REF_NUM1 as REF_NUM1", \
	"JNR_SITE_PROFILE___REF_NUM2 as REF_NUM2", \
	"JNR_SITE_PROFILE___REF_NUM3 as REF_NUM3", \
	"JNR_SITE_PROFILE___REF_NUM4 as REF_NUM4", \
	"JNR_SITE_PROFILE___REF_NUM5 as REF_NUM5", \
	"JNR_SITE_PROFILE___IS_GIFT as IS_GIFT", \
	"JNR_SITE_PROFILE___ADJUSTED_ORDER_QTY as ADJUSTED_ORDER_QTY", \
	"JNR_SITE_PROFILE___PRE_RECEIPT_STATUS as PRE_RECEIPT_STATUS", \
	"JNR_SITE_PROFILE___ALLOW_REVIVAL_RECEIPT_ALLOC as ALLOW_REVIVAL_RECEIPT_ALLOC", \
	"JNR_SITE_PROFILE___SEGMENT_NAME as SEGMENT_NAME", \
	"JNR_SITE_PROFILE___EFFECTIVE_RANK as EFFECTIVE_RANK", \
	"JNR_SITE_PROFILE___WM_RECEIPT_ALLOCATED as WM_RECEIPT_ALLOCATED", \
	"JNR_SITE_PROFILE___GIFT_CARD_VALUE as GIFT_CARD_VALUE", \
	"JNR_SITE_PROFILE___REF_BOOLEAN1 as REF_BOOLEAN1", \
	"JNR_SITE_PROFILE___REF_BOOLEAN2 as REF_BOOLEAN2", \
	"JNR_SITE_PROFILE___REF_SYSCODE1 as REF_SYSCODE1", \
	"JNR_SITE_PROFILE___REF_SYSCODE2 as REF_SYSCODE2", \
	"JNR_SITE_PROFILE___REF_SYSCODE3 as REF_SYSCODE3", \
	"JNR_SITE_PROFILE___HARD_ALLOC_REASON_CODE as HARD_ALLOC_REASON_CODE", \
	"JNR_SITE_PROFILE___LOCKED as LOCKED", \
	"SQ_Shortcut_to_WM_ORDER_LINE_ITEM___LOCATION_ID as i_LOCATION_ID", \
	"SQ_Shortcut_to_WM_ORDER_LINE_ITEM___WM_ORDER_ID as i_WM_ORDER_ID", \
	"SQ_Shortcut_to_WM_ORDER_LINE_ITEM___WM_LINE_ITEM_ID as i_WM_LINE_ITEM_ID", \
	"SQ_Shortcut_to_WM_ORDER_LINE_ITEM___WM_CREATED_TSTMP as i_WM_CREATED_TSTMP", \
	"SQ_Shortcut_to_WM_ORDER_LINE_ITEM___WM_LAST_UPDATED_TSTMP as i_WM_LAST_UPDATED_TSTMP", \
	"SQ_Shortcut_to_WM_ORDER_LINE_ITEM___LOAD_TSTMP as i_LOAD_TSTMP")

# COMMAND ----------
# Processing node FIL_UNCHANGED_RECORDS, type FILTER 
# COLUMN COUNT: 214

# for each involved DataFrame, append the dataframe name to each column
JNR_WM_ORDER_LINE_ITEM_temp = JNR_WM_ORDER_LINE_ITEM.toDF(*["JNR_WM_ORDER_LINE_ITEM___" + col for col in JNR_WM_ORDER_LINE_ITEM.columns])

FIL_UNCHANGED_RECORDS = JNR_WM_ORDER_LINE_ITEM_temp.selectExpr( \
	"JNR_WM_ORDER_LINE_ITEM___LOCATION_ID as LOCATION_ID", \
	"JNR_WM_ORDER_LINE_ITEM___ORDER_ID as ORDER_ID", \
	"JNR_WM_ORDER_LINE_ITEM___LINE_ITEM_ID as LINE_ITEM_ID", \
	"JNR_WM_ORDER_LINE_ITEM___PARENT_LINE_ITEM_ID as PARENT_LINE_ITEM_ID", \
	"JNR_WM_ORDER_LINE_ITEM___TC_COMPANY_ID as TC_COMPANY_ID", \
	"JNR_WM_ORDER_LINE_ITEM___COMMODITY_CLASS as COMMODITY_CLASS", \
	"JNR_WM_ORDER_LINE_ITEM___REF_FIELD1 as REF_FIELD1", \
	"JNR_WM_ORDER_LINE_ITEM___REF_FIELD2 as REF_FIELD2", \
	"JNR_WM_ORDER_LINE_ITEM___REF_FIELD3 as REF_FIELD3", \
	"JNR_WM_ORDER_LINE_ITEM___EXT_SYS_LINE_ITEM_ID as EXT_SYS_LINE_ITEM_ID", \
	"JNR_WM_ORDER_LINE_ITEM___MASTER_ORDER_ID as MASTER_ORDER_ID", \
	"JNR_WM_ORDER_LINE_ITEM___MO_LINE_ITEM_ID as MO_LINE_ITEM_ID", \
	"JNR_WM_ORDER_LINE_ITEM___IS_HAZMAT as IS_HAZMAT", \
	"JNR_WM_ORDER_LINE_ITEM___IS_STACKABLE as IS_STACKABLE", \
	"JNR_WM_ORDER_LINE_ITEM___HAS_ERRORS as HAS_ERRORS", \
	"JNR_WM_ORDER_LINE_ITEM___ORIG_BUDG_COST as ORIG_BUDG_COST", \
	"JNR_WM_ORDER_LINE_ITEM___BUDG_COST_CURRENCY_CODE as BUDG_COST_CURRENCY_CODE", \
	"JNR_WM_ORDER_LINE_ITEM___BUDG_COST as BUDG_COST", \
	"JNR_WM_ORDER_LINE_ITEM___ACTUAL_COST_CURRENCY_CODE as ACTUAL_COST_CURRENCY_CODE", \
	"JNR_WM_ORDER_LINE_ITEM___TOTAL_MONETARY_VALUE as TOTAL_MONETARY_VALUE", \
	"JNR_WM_ORDER_LINE_ITEM___UNIT_MONETARY_VALUE as UNIT_MONETARY_VALUE", \
	"JNR_WM_ORDER_LINE_ITEM___UNIT_TAX_AMOUNT as UNIT_TAX_AMOUNT", \
	"JNR_WM_ORDER_LINE_ITEM___RTS_ID as RTS_ID", \
	"JNR_WM_ORDER_LINE_ITEM___RTS_LINE_ITEM_ID as RTS_LINE_ITEM_ID", \
	"JNR_WM_ORDER_LINE_ITEM___STD_PACK_QTY as STD_PACK_QTY", \
	"JNR_WM_ORDER_LINE_ITEM___PRODUCT_CLASS_ID as PRODUCT_CLASS_ID", \
	"JNR_WM_ORDER_LINE_ITEM___PROTECTION_LEVEL_ID as PROTECTION_LEVEL_ID", \
	"JNR_WM_ORDER_LINE_ITEM___PACKAGE_TYPE_ID as PACKAGE_TYPE_ID", \
	"JNR_WM_ORDER_LINE_ITEM___COMMODITY_CODE_ID as COMMODITY_CODE_ID", \
	"JNR_WM_ORDER_LINE_ITEM___MV_SIZE_UOM_ID as MV_SIZE_UOM_ID", \
	"JNR_WM_ORDER_LINE_ITEM___QTY_UOM_ID_BASE as QTY_UOM_ID_BASE", \
	"JNR_WM_ORDER_LINE_ITEM___MV_CURRENCY_CODE as MV_CURRENCY_CODE", \
	"JNR_WM_ORDER_LINE_ITEM___SHIPPED_QTY as SHIPPED_QTY", \
	"JNR_WM_ORDER_LINE_ITEM___RECEIVED_QTY as RECEIVED_QTY", \
	"JNR_WM_ORDER_LINE_ITEM___PRIORITY as PRIORITY", \
	"JNR_WM_ORDER_LINE_ITEM___MERCHANDIZING_DEPARTMENT_ID as MERCHANDIZING_DEPARTMENT_ID", \
	"JNR_WM_ORDER_LINE_ITEM___UN_NUMBER_ID as UN_NUMBER_ID", \
	"JNR_WM_ORDER_LINE_ITEM___PICKUP_REFERENCE_NUMBER as PICKUP_REFERENCE_NUMBER", \
	"JNR_WM_ORDER_LINE_ITEM___DELIVERY_REFERENCE_NUMBER as DELIVERY_REFERENCE_NUMBER", \
	"JNR_WM_ORDER_LINE_ITEM___CNTRY_OF_ORGN as CNTRY_OF_ORGN", \
	"JNR_WM_ORDER_LINE_ITEM___PROD_STAT as PROD_STAT", \
	"JNR_WM_ORDER_LINE_ITEM___STACK_RANK as STACK_RANK", \
	"JNR_WM_ORDER_LINE_ITEM___STACK_LENGTH_VALUE as STACK_LENGTH_VALUE", \
	"JNR_WM_ORDER_LINE_ITEM___STACK_LENGTH_STANDARD_UOM as STACK_LENGTH_STANDARD_UOM", \
	"JNR_WM_ORDER_LINE_ITEM___STACK_WIDTH_VALUE as STACK_WIDTH_VALUE", \
	"JNR_WM_ORDER_LINE_ITEM___STACK_WIDTH_STANDARD_UOM as STACK_WIDTH_STANDARD_UOM", \
	"JNR_WM_ORDER_LINE_ITEM___STACK_HEIGHT_VALUE as STACK_HEIGHT_VALUE", \
	"JNR_WM_ORDER_LINE_ITEM___STACK_HEIGHT_STANDARD_UOM as STACK_HEIGHT_STANDARD_UOM", \
	"JNR_WM_ORDER_LINE_ITEM___STACK_DIAMETER_VALUE as STACK_DIAMETER_VALUE", \
	"JNR_WM_ORDER_LINE_ITEM___STACK_DIAMETER_STANDARD_UOM as STACK_DIAMETER_STANDARD_UOM", \
	"JNR_WM_ORDER_LINE_ITEM___CREATED_SOURCE_TYPE as CREATED_SOURCE_TYPE", \
	"JNR_WM_ORDER_LINE_ITEM___CREATED_SOURCE as CREATED_SOURCE", \
	"JNR_WM_ORDER_LINE_ITEM___CREATED_DTTM as CREATED_DTTM", \
	"JNR_WM_ORDER_LINE_ITEM___LAST_UPDATED_SOURCE_TYPE as LAST_UPDATED_SOURCE_TYPE", \
	"JNR_WM_ORDER_LINE_ITEM___LAST_UPDATED_SOURCE as LAST_UPDATED_SOURCE", \
	"JNR_WM_ORDER_LINE_ITEM___LAST_UPDATED_DTTM as LAST_UPDATED_DTTM", \
	"JNR_WM_ORDER_LINE_ITEM___HIBERNATE_VERSION as HIBERNATE_VERSION", \
	"JNR_WM_ORDER_LINE_ITEM___CUBE_MULTIPLE_QTY as CUBE_MULTIPLE_QTY", \
	"JNR_WM_ORDER_LINE_ITEM___DO_DTL_STATUS as DO_DTL_STATUS", \
	"JNR_WM_ORDER_LINE_ITEM___INTERNAL_ORDER_SEQ_NBR as INTERNAL_ORDER_SEQ_NBR", \
	"JNR_WM_ORDER_LINE_ITEM___IS_EMERGENCY as IS_EMERGENCY", \
	"JNR_WM_ORDER_LINE_ITEM___LPN_SIZE as LPN_SIZE", \
	"JNR_WM_ORDER_LINE_ITEM___MANUFACTURING_DTTM as MANUFACTURING_DTTM", \
	"JNR_WM_ORDER_LINE_ITEM___ORDER_LINE_ID as ORDER_LINE_ID", \
	"JNR_WM_ORDER_LINE_ITEM___PACK_RATE as PACK_RATE", \
	"JNR_WM_ORDER_LINE_ITEM___ALLOCATED_QTY as ALLOCATED_QTY", \
	"JNR_WM_ORDER_LINE_ITEM___PLANNED_SHIP_DATE as PLANNED_SHIP_DATE", \
	"JNR_WM_ORDER_LINE_ITEM___PPACK_QTY as PPACK_QTY", \
	"JNR_WM_ORDER_LINE_ITEM___STD_BUNDLE_QTY as STD_BUNDLE_QTY", \
	"JNR_WM_ORDER_LINE_ITEM___STD_LPN_QTY as STD_LPN_QTY", \
	"JNR_WM_ORDER_LINE_ITEM___STD_LPN_VOL as STD_LPN_VOL", \
	"JNR_WM_ORDER_LINE_ITEM___STD_LPN_WT as STD_LPN_WT", \
	"JNR_WM_ORDER_LINE_ITEM___UNIT_COST as UNIT_COST", \
	"JNR_WM_ORDER_LINE_ITEM___UNIT_PRICE_AMOUNT as UNIT_PRICE_AMOUNT", \
	"JNR_WM_ORDER_LINE_ITEM___UNIT_VOL as UNIT_VOL", \
	"JNR_WM_ORDER_LINE_ITEM___UNIT_WT as UNIT_WT", \
	"JNR_WM_ORDER_LINE_ITEM___USER_CANCELED_QTY as USER_CANCELED_QTY", \
	"JNR_WM_ORDER_LINE_ITEM___WAVE_PROC_TYPE as WAVE_PROC_TYPE", \
	"JNR_WM_ORDER_LINE_ITEM___DELIVERY_END_DTTM as DELIVERY_END_DTTM", \
	"JNR_WM_ORDER_LINE_ITEM___DELIVERY_START_DTTM as DELIVERY_START_DTTM", \
	"JNR_WM_ORDER_LINE_ITEM___EVENT_CODE as EVENT_CODE", \
	"JNR_WM_ORDER_LINE_ITEM___REASON_CODE as REASON_CODE", \
	"JNR_WM_ORDER_LINE_ITEM___EXP_INFO_CODE as EXP_INFO_CODE", \
	"JNR_WM_ORDER_LINE_ITEM___PARTL_FILL as PARTL_FILL", \
	"JNR_WM_ORDER_LINE_ITEM___LINE_TYPE as LINE_TYPE", \
	"JNR_WM_ORDER_LINE_ITEM___REPL_PROC_TYPE as REPL_PROC_TYPE", \
	"JNR_WM_ORDER_LINE_ITEM___ORDER_QTY as ORDER_QTY", \
	"JNR_WM_ORDER_LINE_ITEM___ORIG_ORDER_QTY as ORIG_ORDER_QTY", \
	"JNR_WM_ORDER_LINE_ITEM___RTL_TO_BE_DISTROED_QTY as RTL_TO_BE_DISTROED_QTY", \
	"JNR_WM_ORDER_LINE_ITEM___PRICE as PRICE", \
	"JNR_WM_ORDER_LINE_ITEM___RETAIL_PRICE as RETAIL_PRICE", \
	"JNR_WM_ORDER_LINE_ITEM___UNITS_PAKD as UNITS_PAKD", \
	"JNR_WM_ORDER_LINE_ITEM___MINOR_ORDER_NBR as MINOR_ORDER_NBR", \
	"JNR_WM_ORDER_LINE_ITEM___ITEM_ID as ITEM_ID", \
	"JNR_WM_ORDER_LINE_ITEM___TC_ORDER_LINE_ID as TC_ORDER_LINE_ID", \
	"JNR_WM_ORDER_LINE_ITEM___ACTUAL_SHIPPED_DTTM as ACTUAL_SHIPPED_DTTM", \
	"JNR_WM_ORDER_LINE_ITEM___QTY_UOM_ID as QTY_UOM_ID", \
	"JNR_WM_ORDER_LINE_ITEM___PICKUP_END_DTTM as PICKUP_END_DTTM", \
	"JNR_WM_ORDER_LINE_ITEM___PURCHASE_ORDER_LINE_NUMBER as PURCHASE_ORDER_LINE_NUMBER", \
	"JNR_WM_ORDER_LINE_ITEM___PICKUP_START_DTTM as PICKUP_START_DTTM", \
	"JNR_WM_ORDER_LINE_ITEM___REFERENCE_LINE_ITEM_ID as REFERENCE_LINE_ITEM_ID", \
	"JNR_WM_ORDER_LINE_ITEM___REFERENCE_ORDER_ID as REFERENCE_ORDER_ID", \
	"JNR_WM_ORDER_LINE_ITEM___REPL_WAVE_RUN as REPL_WAVE_RUN", \
	"JNR_WM_ORDER_LINE_ITEM___STD_PALLET_QTY as STD_PALLET_QTY", \
	"JNR_WM_ORDER_LINE_ITEM___STD_SUB_PACK_QTY as STD_SUB_PACK_QTY", \
	"JNR_WM_ORDER_LINE_ITEM___STORE_DEPT as STORE_DEPT", \
	"JNR_WM_ORDER_LINE_ITEM___ALLOC_TYPE as ALLOC_TYPE", \
	"JNR_WM_ORDER_LINE_ITEM___BATCH_NBR as BATCH_NBR", \
	"JNR_WM_ORDER_LINE_ITEM___BATCH_REQUIREMENT_TYPE as BATCH_REQUIREMENT_TYPE", \
	"JNR_WM_ORDER_LINE_ITEM___CHUTE_ASSIGN_TYPE as CHUTE_ASSIGN_TYPE", \
	"JNR_WM_ORDER_LINE_ITEM___CUSTOM_TAG as CUSTOM_TAG", \
	"JNR_WM_ORDER_LINE_ITEM___CUSTOMER_ITEM as CUSTOMER_ITEM", \
	"JNR_WM_ORDER_LINE_ITEM___INTERNAL_ORDER_ID as INTERNAL_ORDER_ID", \
	"JNR_WM_ORDER_LINE_ITEM___INVN_TYPE as INVN_TYPE", \
	"JNR_WM_ORDER_LINE_ITEM___ITEM_ATTR_1 as ITEM_ATTR_1", \
	"JNR_WM_ORDER_LINE_ITEM___ITEM_ATTR_2 as ITEM_ATTR_2", \
	"JNR_WM_ORDER_LINE_ITEM___ITEM_ATTR_3 as ITEM_ATTR_3", \
	"JNR_WM_ORDER_LINE_ITEM___ITEM_ATTR_4 as ITEM_ATTR_4", \
	"JNR_WM_ORDER_LINE_ITEM___ITEM_ATTR_5 as ITEM_ATTR_5", \
	"JNR_WM_ORDER_LINE_ITEM___LPN_BRK_ATTRIB as LPN_BRK_ATTRIB", \
	"JNR_WM_ORDER_LINE_ITEM___MERCH_GRP as MERCH_GRP", \
	"JNR_WM_ORDER_LINE_ITEM___MERCH_TYPE as MERCH_TYPE", \
	"JNR_WM_ORDER_LINE_ITEM___PACK_ZONE as PACK_ZONE", \
	"JNR_WM_ORDER_LINE_ITEM___PALLET_TYPE as PALLET_TYPE", \
	"JNR_WM_ORDER_LINE_ITEM___PICK_LOCN_ASSIGN_TYPE as PICK_LOCN_ASSIGN_TYPE", \
	"JNR_WM_ORDER_LINE_ITEM___PICK_LOCN_ID as PICK_LOCN_ID", \
	"JNR_WM_ORDER_LINE_ITEM___PPACK_GRP_CODE as PPACK_GRP_CODE", \
	"JNR_WM_ORDER_LINE_ITEM___PRICE_TKT_TYPE as PRICE_TKT_TYPE", \
	"JNR_WM_ORDER_LINE_ITEM___SERIAL_NUMBER_REQUIRED_FLAG as SERIAL_NUMBER_REQUIRED_FLAG", \
	"JNR_WM_ORDER_LINE_ITEM___SKU_GTIN as SKU_GTIN", \
	"JNR_WM_ORDER_LINE_ITEM___SKU_SUB_CODE_ID as SKU_SUB_CODE_ID", \
	"JNR_WM_ORDER_LINE_ITEM___SKU_SUB_CODE_VALUE as SKU_SUB_CODE_VALUE", \
	"JNR_WM_ORDER_LINE_ITEM___VAS_PROCESS_TYPE as VAS_PROCESS_TYPE", \
	"JNR_WM_ORDER_LINE_ITEM___SUBSTITUTED_PARENT_LINE_ID as SUBSTITUTED_PARENT_LINE_ID", \
	"JNR_WM_ORDER_LINE_ITEM___IS_CANCELLED as IS_CANCELLED", \
	"JNR_WM_ORDER_LINE_ITEM___ITEM_NAME as ITEM_NAME", \
	"JNR_WM_ORDER_LINE_ITEM___ALLOC_LINE_ID as ALLOC_LINE_ID", \
	"JNR_WM_ORDER_LINE_ITEM___ALLOCATION_SOURCE_ID as ALLOCATION_SOURCE_ID", \
	"JNR_WM_ORDER_LINE_ITEM___ALLOCATION_SOURCE_LINE_ID as ALLOCATION_SOURCE_LINE_ID", \
	"JNR_WM_ORDER_LINE_ITEM___ALLOCATION_SOURCE as ALLOCATION_SOURCE", \
	"JNR_WM_ORDER_LINE_ITEM___SHELF_DAYS as SHELF_DAYS", \
	"JNR_WM_ORDER_LINE_ITEM___FULFILLMENT_TYPE as FULFILLMENT_TYPE", \
	"JNR_WM_ORDER_LINE_ITEM___WAVE_NBR as WAVE_NBR", \
	"JNR_WM_ORDER_LINE_ITEM___SHIP_WAVE_NBR as SHIP_WAVE_NBR", \
	"JNR_WM_ORDER_LINE_ITEM___REPL_WAVE_NBR as REPL_WAVE_NBR", \
	"JNR_WM_ORDER_LINE_ITEM___SINGLE_UNIT_FLAG as SINGLE_UNIT_FLAG", \
	"JNR_WM_ORDER_LINE_ITEM___ACTUAL_COST as ACTUAL_COST", \
	"JNR_WM_ORDER_LINE_ITEM___QTY_CONV_FACTOR as QTY_CONV_FACTOR", \
	"JNR_WM_ORDER_LINE_ITEM___PLANNED_WEIGHT as PLANNED_WEIGHT", \
	"JNR_WM_ORDER_LINE_ITEM___RECEIVED_WEIGHT as RECEIVED_WEIGHT", \
	"JNR_WM_ORDER_LINE_ITEM___SHIPPED_WEIGHT as SHIPPED_WEIGHT", \
	"JNR_WM_ORDER_LINE_ITEM___WEIGHT_UOM_ID_BASE as WEIGHT_UOM_ID_BASE", \
	"JNR_WM_ORDER_LINE_ITEM___WEIGHT_UOM_ID as WEIGHT_UOM_ID", \
	"JNR_WM_ORDER_LINE_ITEM___PLANNED_VOLUME as PLANNED_VOLUME", \
	"JNR_WM_ORDER_LINE_ITEM___RECEIVED_VOLUME as RECEIVED_VOLUME", \
	"JNR_WM_ORDER_LINE_ITEM___SHIPPED_VOLUME as SHIPPED_VOLUME", \
	"JNR_WM_ORDER_LINE_ITEM___VOLUME_UOM_ID_BASE as VOLUME_UOM_ID_BASE", \
	"JNR_WM_ORDER_LINE_ITEM___VOLUME_UOM_ID as VOLUME_UOM_ID", \
	"JNR_WM_ORDER_LINE_ITEM___SIZE1_UOM_ID as SIZE1_UOM_ID", \
	"JNR_WM_ORDER_LINE_ITEM___SIZE1_VALUE as SIZE1_VALUE", \
	"JNR_WM_ORDER_LINE_ITEM___RECEIVED_SIZE1 as RECEIVED_SIZE1", \
	"JNR_WM_ORDER_LINE_ITEM___SHIPPED_SIZE1 as SHIPPED_SIZE1", \
	"JNR_WM_ORDER_LINE_ITEM___SIZE2_UOM_ID as SIZE2_UOM_ID", \
	"JNR_WM_ORDER_LINE_ITEM___SIZE2_VALUE as SIZE2_VALUE", \
	"JNR_WM_ORDER_LINE_ITEM___RECEIVED_SIZE2 as RECEIVED_SIZE2", \
	"JNR_WM_ORDER_LINE_ITEM___SHIPPED_SIZE2 as SHIPPED_SIZE2", \
	"JNR_WM_ORDER_LINE_ITEM___LPN_TYPE as LPN_TYPE", \
	"JNR_WM_ORDER_LINE_ITEM___ORDER_CONSOL_ATTR as ORDER_CONSOL_ATTR", \
	"JNR_WM_ORDER_LINE_ITEM___SKU_BREAK_ATTR as SKU_BREAK_ATTR", \
	"JNR_WM_ORDER_LINE_ITEM___PURCHASE_ORDER_NUMBER as PURCHASE_ORDER_NUMBER", \
	"JNR_WM_ORDER_LINE_ITEM___EXT_PURCHASE_ORDER as EXT_PURCHASE_ORDER", \
	"JNR_WM_ORDER_LINE_ITEM___CRITCL_DIM_1 as CRITCL_DIM_1", \
	"JNR_WM_ORDER_LINE_ITEM___CRITCL_DIM_2 as CRITCL_DIM_2", \
	"JNR_WM_ORDER_LINE_ITEM___CRITCL_DIM_3 as CRITCL_DIM_3", \
	"JNR_WM_ORDER_LINE_ITEM___ASSORT_NBR as ASSORT_NBR", \
	"JNR_WM_ORDER_LINE_ITEM___DESCRIPTION as DESCRIPTION", \
	"JNR_WM_ORDER_LINE_ITEM___ORIGINAL_ORDERED_ITEM_ID as ORIGINAL_ORDERED_ITEM_ID", \
	"JNR_WM_ORDER_LINE_ITEM___SUBSTITUTION_TYPE as SUBSTITUTION_TYPE", \
	"JNR_WM_ORDER_LINE_ITEM___BACK_ORD_REASON as BACK_ORD_REASON", \
	"JNR_WM_ORDER_LINE_ITEM___FREIGHT_REVENUE_CURRENCY_CODE as FREIGHT_REVENUE_CURRENCY_CODE", \
	"JNR_WM_ORDER_LINE_ITEM___FREIGHT_REVENUE as FREIGHT_REVENUE", \
	"JNR_WM_ORDER_LINE_ITEM___IS_CHASE_CREATED_LINE as IS_CHASE_CREATED_LINE", \
	"JNR_WM_ORDER_LINE_ITEM___REF_FIELD4 as REF_FIELD4", \
	"JNR_WM_ORDER_LINE_ITEM___REF_FIELD5 as REF_FIELD5", \
	"JNR_WM_ORDER_LINE_ITEM___REF_FIELD6 as REF_FIELD6", \
	"JNR_WM_ORDER_LINE_ITEM___REF_FIELD7 as REF_FIELD7", \
	"JNR_WM_ORDER_LINE_ITEM___REF_FIELD8 as REF_FIELD8", \
	"JNR_WM_ORDER_LINE_ITEM___REF_FIELD9 as REF_FIELD9", \
	"JNR_WM_ORDER_LINE_ITEM___REF_FIELD10 as REF_FIELD10", \
	"JNR_WM_ORDER_LINE_ITEM___REF_NUM1 as REF_NUM1", \
	"JNR_WM_ORDER_LINE_ITEM___REF_NUM2 as REF_NUM2", \
	"JNR_WM_ORDER_LINE_ITEM___REF_NUM3 as REF_NUM3", \
	"JNR_WM_ORDER_LINE_ITEM___REF_NUM4 as REF_NUM4", \
	"JNR_WM_ORDER_LINE_ITEM___REF_NUM5 as REF_NUM5", \
	"JNR_WM_ORDER_LINE_ITEM___IS_GIFT as IS_GIFT", \
	"JNR_WM_ORDER_LINE_ITEM___ADJUSTED_ORDER_QTY as ADJUSTED_ORDER_QTY", \
	"JNR_WM_ORDER_LINE_ITEM___PRE_RECEIPT_STATUS as PRE_RECEIPT_STATUS", \
	"JNR_WM_ORDER_LINE_ITEM___ALLOW_REVIVAL_RECEIPT_ALLOC as ALLOW_REVIVAL_RECEIPT_ALLOC", \
	"JNR_WM_ORDER_LINE_ITEM___SEGMENT_NAME as SEGMENT_NAME", \
	"JNR_WM_ORDER_LINE_ITEM___EFFECTIVE_RANK as EFFECTIVE_RANK", \
	"JNR_WM_ORDER_LINE_ITEM___WM_RECEIPT_ALLOCATED as WM_RECEIPT_ALLOCATED", \
	"JNR_WM_ORDER_LINE_ITEM___GIFT_CARD_VALUE as GIFT_CARD_VALUE", \
	"JNR_WM_ORDER_LINE_ITEM___REF_BOOLEAN1 as REF_BOOLEAN1", \
	"JNR_WM_ORDER_LINE_ITEM___REF_BOOLEAN2 as REF_BOOLEAN2", \
	"JNR_WM_ORDER_LINE_ITEM___REF_SYSCODE1 as REF_SYSCODE1", \
	"JNR_WM_ORDER_LINE_ITEM___REF_SYSCODE2 as REF_SYSCODE2", \
	"JNR_WM_ORDER_LINE_ITEM___REF_SYSCODE3 as REF_SYSCODE3", \
	"JNR_WM_ORDER_LINE_ITEM___HARD_ALLOC_REASON_CODE as HARD_ALLOC_REASON_CODE", \
	"JNR_WM_ORDER_LINE_ITEM___LOCKED as LOCKED", \
	"JNR_WM_ORDER_LINE_ITEM___i_WM_ORDER_ID as i_WM_ORDER_ID", \
	"JNR_WM_ORDER_LINE_ITEM___i_WM_LINE_ITEM_ID as i_WM_LINE_ITEM_ID", \
	"JNR_WM_ORDER_LINE_ITEM___i_WM_CREATED_TSTMP as i_WM_CREATED_TSTMP", \
	"JNR_WM_ORDER_LINE_ITEM___i_WM_LAST_UPDATED_TSTMP as i_WM_LAST_UPDATED_TSTMP", \
	"JNR_WM_ORDER_LINE_ITEM___i_LOAD_TSTMP as i_LOAD_TSTMP")\
    .filter("i_WM_ORDER_ID is Null OR (  i_WM_ORDER_ID is NOT Null AND ( COALESCE(CREATED_DTTM, date'1900-01-01') != COALESCE(i_WM_CREATED_TSTMP, date'1900-01-01') \
             OR COALESCE(LAST_UPDATED_DTTM, date'1900-01-01') != COALESCE(i_WM_LAST_UPDATED_TSTMP, date'1900-01-01')))").withColumn("sys_row_id", monotonically_increasing_id())

# COMMAND ----------
# Processing node EXP_UPD_VALIDATOR, type EXPRESSION 
# COLUMN COUNT: 212

# for each involved DataFrame, append the dataframe name to each column
FIL_UNCHANGED_RECORDS_temp = FIL_UNCHANGED_RECORDS.toDF(*["FIL_UNCHANGED_RECORDS___" + col for col in FIL_UNCHANGED_RECORDS.columns])

EXP_UPD_VALIDATOR = FIL_UNCHANGED_RECORDS_temp.selectExpr( \
	"FIL_UNCHANGED_RECORDS___sys_row_id as sys_row_id", \
	"FIL_UNCHANGED_RECORDS___LOCATION_ID as LOCATION_ID", \
	"FIL_UNCHANGED_RECORDS___ORDER_ID as ORDER_ID", \
	"FIL_UNCHANGED_RECORDS___LINE_ITEM_ID as LINE_ITEM_ID", \
	"FIL_UNCHANGED_RECORDS___PARENT_LINE_ITEM_ID as PARENT_LINE_ITEM_ID", \
	"FIL_UNCHANGED_RECORDS___TC_COMPANY_ID as TC_COMPANY_ID", \
	"FIL_UNCHANGED_RECORDS___COMMODITY_CLASS as COMMODITY_CLASS", \
	"FIL_UNCHANGED_RECORDS___REF_FIELD1 as REF_FIELD1", \
	"FIL_UNCHANGED_RECORDS___REF_FIELD2 as REF_FIELD2", \
	"FIL_UNCHANGED_RECORDS___REF_FIELD3 as REF_FIELD3", \
	"FIL_UNCHANGED_RECORDS___EXT_SYS_LINE_ITEM_ID as EXT_SYS_LINE_ITEM_ID", \
	"FIL_UNCHANGED_RECORDS___MASTER_ORDER_ID as MASTER_ORDER_ID", \
	"FIL_UNCHANGED_RECORDS___MO_LINE_ITEM_ID as MO_LINE_ITEM_ID", \
	"FIL_UNCHANGED_RECORDS___IS_HAZMAT as IS_HAZMAT", \
	"FIL_UNCHANGED_RECORDS___IS_STACKABLE as IS_STACKABLE", \
	"FIL_UNCHANGED_RECORDS___HAS_ERRORS as HAS_ERRORS", \
	"FIL_UNCHANGED_RECORDS___ORIG_BUDG_COST as ORIG_BUDG_COST", \
	"FIL_UNCHANGED_RECORDS___BUDG_COST_CURRENCY_CODE as BUDG_COST_CURRENCY_CODE", \
	"FIL_UNCHANGED_RECORDS___BUDG_COST as BUDG_COST", \
	"FIL_UNCHANGED_RECORDS___ACTUAL_COST_CURRENCY_CODE as ACTUAL_COST_CURRENCY_CODE", \
	"FIL_UNCHANGED_RECORDS___TOTAL_MONETARY_VALUE as TOTAL_MONETARY_VALUE", \
	"FIL_UNCHANGED_RECORDS___UNIT_MONETARY_VALUE as UNIT_MONETARY_VALUE", \
	"FIL_UNCHANGED_RECORDS___UNIT_TAX_AMOUNT as UNIT_TAX_AMOUNT", \
	"FIL_UNCHANGED_RECORDS___RTS_ID as RTS_ID", \
	"FIL_UNCHANGED_RECORDS___RTS_LINE_ITEM_ID as RTS_LINE_ITEM_ID", \
	"FIL_UNCHANGED_RECORDS___STD_PACK_QTY as STD_PACK_QTY", \
	"FIL_UNCHANGED_RECORDS___PRODUCT_CLASS_ID as PRODUCT_CLASS_ID", \
	"FIL_UNCHANGED_RECORDS___PROTECTION_LEVEL_ID as PROTECTION_LEVEL_ID", \
	"FIL_UNCHANGED_RECORDS___PACKAGE_TYPE_ID as PACKAGE_TYPE_ID", \
	"FIL_UNCHANGED_RECORDS___COMMODITY_CODE_ID as COMMODITY_CODE_ID", \
	"FIL_UNCHANGED_RECORDS___MV_SIZE_UOM_ID as MV_SIZE_UOM_ID", \
	"FIL_UNCHANGED_RECORDS___QTY_UOM_ID_BASE as QTY_UOM_ID_BASE", \
	"FIL_UNCHANGED_RECORDS___MV_CURRENCY_CODE as MV_CURRENCY_CODE", \
	"FIL_UNCHANGED_RECORDS___SHIPPED_QTY as SHIPPED_QTY", \
	"FIL_UNCHANGED_RECORDS___RECEIVED_QTY as RECEIVED_QTY", \
	"FIL_UNCHANGED_RECORDS___PRIORITY as PRIORITY", \
	"FIL_UNCHANGED_RECORDS___MERCHANDIZING_DEPARTMENT_ID as MERCHANDIZING_DEPARTMENT_ID", \
	"FIL_UNCHANGED_RECORDS___UN_NUMBER_ID as UN_NUMBER_ID", \
	"FIL_UNCHANGED_RECORDS___PICKUP_REFERENCE_NUMBER as PICKUP_REFERENCE_NUMBER", \
	"FIL_UNCHANGED_RECORDS___DELIVERY_REFERENCE_NUMBER as DELIVERY_REFERENCE_NUMBER", \
	"FIL_UNCHANGED_RECORDS___CNTRY_OF_ORGN as CNTRY_OF_ORGN", \
	"FIL_UNCHANGED_RECORDS___PROD_STAT as PROD_STAT", \
	"FIL_UNCHANGED_RECORDS___STACK_RANK as STACK_RANK", \
	"FIL_UNCHANGED_RECORDS___STACK_LENGTH_VALUE as STACK_LENGTH_VALUE", \
	"FIL_UNCHANGED_RECORDS___STACK_LENGTH_STANDARD_UOM as STACK_LENGTH_STANDARD_UOM", \
	"FIL_UNCHANGED_RECORDS___STACK_WIDTH_VALUE as STACK_WIDTH_VALUE", \
	"FIL_UNCHANGED_RECORDS___STACK_WIDTH_STANDARD_UOM as STACK_WIDTH_STANDARD_UOM", \
	"FIL_UNCHANGED_RECORDS___STACK_HEIGHT_VALUE as STACK_HEIGHT_VALUE", \
	"FIL_UNCHANGED_RECORDS___STACK_HEIGHT_STANDARD_UOM as STACK_HEIGHT_STANDARD_UOM", \
	"FIL_UNCHANGED_RECORDS___STACK_DIAMETER_VALUE as STACK_DIAMETER_VALUE", \
	"FIL_UNCHANGED_RECORDS___STACK_DIAMETER_STANDARD_UOM as STACK_DIAMETER_STANDARD_UOM", \
	"FIL_UNCHANGED_RECORDS___CREATED_SOURCE_TYPE as CREATED_SOURCE_TYPE", \
	"FIL_UNCHANGED_RECORDS___CREATED_SOURCE as CREATED_SOURCE", \
	"FIL_UNCHANGED_RECORDS___CREATED_DTTM as CREATED_DTTM", \
	"FIL_UNCHANGED_RECORDS___LAST_UPDATED_SOURCE_TYPE as LAST_UPDATED_SOURCE_TYPE", \
	"FIL_UNCHANGED_RECORDS___LAST_UPDATED_SOURCE as LAST_UPDATED_SOURCE", \
	"FIL_UNCHANGED_RECORDS___LAST_UPDATED_DTTM as LAST_UPDATED_DTTM", \
	"FIL_UNCHANGED_RECORDS___HIBERNATE_VERSION as HIBERNATE_VERSION", \
	"FIL_UNCHANGED_RECORDS___CUBE_MULTIPLE_QTY as CUBE_MULTIPLE_QTY", \
	"FIL_UNCHANGED_RECORDS___DO_DTL_STATUS as DO_DTL_STATUS", \
	"FIL_UNCHANGED_RECORDS___INTERNAL_ORDER_SEQ_NBR as INTERNAL_ORDER_SEQ_NBR", \
	"DECODE ( LTRIM ( RTRIM ( UPPER ( FIL_UNCHANGED_RECORDS___IS_EMERGENCY ) ) ) , 'Y','1' , '1','1','0' ) as o_EMERGENCY_FLAG", \
	"FIL_UNCHANGED_RECORDS___LPN_SIZE as LPN_SIZE", \
	"FIL_UNCHANGED_RECORDS___MANUFACTURING_DTTM as MANUFACTURING_DTTM", \
	"FIL_UNCHANGED_RECORDS___ORDER_LINE_ID as ORDER_LINE_ID", \
	"FIL_UNCHANGED_RECORDS___PACK_RATE as PACK_RATE", \
	"FIL_UNCHANGED_RECORDS___ALLOCATED_QTY as ALLOCATED_QTY", \
	"FIL_UNCHANGED_RECORDS___PLANNED_SHIP_DATE as PLANNED_SHIP_DATE", \
	"FIL_UNCHANGED_RECORDS___PPACK_QTY as PPACK_QTY", \
	"FIL_UNCHANGED_RECORDS___STD_BUNDLE_QTY as STD_BUNDLE_QTY", \
	"FIL_UNCHANGED_RECORDS___STD_LPN_QTY as STD_LPN_QTY", \
	"FIL_UNCHANGED_RECORDS___STD_LPN_VOL as STD_LPN_VOL", \
	"FIL_UNCHANGED_RECORDS___STD_LPN_WT as STD_LPN_WT", \
	"FIL_UNCHANGED_RECORDS___UNIT_COST as UNIT_COST", \
	"FIL_UNCHANGED_RECORDS___UNIT_PRICE_AMOUNT as UNIT_PRICE_AMOUNT", \
	"FIL_UNCHANGED_RECORDS___UNIT_VOL as UNIT_VOL", \
	"FIL_UNCHANGED_RECORDS___UNIT_WT as UNIT_WT", \
	"FIL_UNCHANGED_RECORDS___USER_CANCELED_QTY as USER_CANCELED_QTY", \
	"FIL_UNCHANGED_RECORDS___WAVE_PROC_TYPE as WAVE_PROC_TYPE", \
	"FIL_UNCHANGED_RECORDS___DELIVERY_END_DTTM as DELIVERY_END_DTTM", \
	"FIL_UNCHANGED_RECORDS___DELIVERY_START_DTTM as DELIVERY_START_DTTM", \
	"FIL_UNCHANGED_RECORDS___EVENT_CODE as EVENT_CODE", \
	"FIL_UNCHANGED_RECORDS___REASON_CODE as REASON_CODE", \
	"FIL_UNCHANGED_RECORDS___EXP_INFO_CODE as EXP_INFO_CODE", \
	"DECODE ( LTRIM ( RTRIM ( UPPER ( FIL_UNCHANGED_RECORDS___PARTL_FILL ) ) ) , 'Y','1' , '1','1','0' ) as o_PARTL_FILL", \
	"FIL_UNCHANGED_RECORDS___LINE_TYPE as LINE_TYPE", \
	"FIL_UNCHANGED_RECORDS___REPL_PROC_TYPE as REPL_PROC_TYPE", \
	"FIL_UNCHANGED_RECORDS___ORDER_QTY as ORDER_QTY", \
	"FIL_UNCHANGED_RECORDS___ORIG_ORDER_QTY as ORIG_ORDER_QTY", \
	"FIL_UNCHANGED_RECORDS___RTL_TO_BE_DISTROED_QTY as RTL_TO_BE_DISTROED_QTY", \
	"FIL_UNCHANGED_RECORDS___PRICE as PRICE", \
	"FIL_UNCHANGED_RECORDS___RETAIL_PRICE as RETAIL_PRICE", \
	"FIL_UNCHANGED_RECORDS___UNITS_PAKD as UNITS_PAKD", \
	"FIL_UNCHANGED_RECORDS___MINOR_ORDER_NBR as MINOR_ORDER_NBR", \
	"FIL_UNCHANGED_RECORDS___ITEM_ID as ITEM_ID", \
	"FIL_UNCHANGED_RECORDS___TC_ORDER_LINE_ID as TC_ORDER_LINE_ID", \
	"FIL_UNCHANGED_RECORDS___ACTUAL_SHIPPED_DTTM as ACTUAL_SHIPPED_DTTM", \
	"FIL_UNCHANGED_RECORDS___QTY_UOM_ID as QTY_UOM_ID", \
	"FIL_UNCHANGED_RECORDS___PICKUP_END_DTTM as PICKUP_END_DTTM", \
	"FIL_UNCHANGED_RECORDS___PURCHASE_ORDER_LINE_NUMBER as PURCHASE_ORDER_LINE_NUMBER", \
	"FIL_UNCHANGED_RECORDS___PICKUP_START_DTTM as PICKUP_START_DTTM", \
	"FIL_UNCHANGED_RECORDS___REFERENCE_LINE_ITEM_ID as REFERENCE_LINE_ITEM_ID", \
	"FIL_UNCHANGED_RECORDS___REFERENCE_ORDER_ID as REFERENCE_ORDER_ID", \
	"DECODE ( LTRIM ( RTRIM ( UPPER ( FIL_UNCHANGED_RECORDS___REPL_WAVE_RUN ) ) ) , 'Y','1' , '1','1','0' ) as o_REPL_WAVE_RUN", \
	"FIL_UNCHANGED_RECORDS___STD_PALLET_QTY as STD_PALLET_QTY", \
	"FIL_UNCHANGED_RECORDS___STD_SUB_PACK_QTY as STD_SUB_PACK_QTY", \
	"FIL_UNCHANGED_RECORDS___STORE_DEPT as STORE_DEPT", \
	"FIL_UNCHANGED_RECORDS___ALLOC_TYPE as ALLOC_TYPE", \
	"FIL_UNCHANGED_RECORDS___BATCH_NBR as BATCH_NBR", \
	"FIL_UNCHANGED_RECORDS___BATCH_REQUIREMENT_TYPE as BATCH_REQUIREMENT_TYPE", \
	"FIL_UNCHANGED_RECORDS___CHUTE_ASSIGN_TYPE as CHUTE_ASSIGN_TYPE", \
	"FIL_UNCHANGED_RECORDS___CUSTOM_TAG as CUSTOM_TAG", \
	"FIL_UNCHANGED_RECORDS___CUSTOMER_ITEM as CUSTOMER_ITEM", \
	"FIL_UNCHANGED_RECORDS___INTERNAL_ORDER_ID as INTERNAL_ORDER_ID", \
	"FIL_UNCHANGED_RECORDS___INVN_TYPE as INVN_TYPE", \
	"FIL_UNCHANGED_RECORDS___ITEM_ATTR_1 as ITEM_ATTR_1", \
	"FIL_UNCHANGED_RECORDS___ITEM_ATTR_2 as ITEM_ATTR_2", \
	"FIL_UNCHANGED_RECORDS___ITEM_ATTR_3 as ITEM_ATTR_3", \
	"FIL_UNCHANGED_RECORDS___ITEM_ATTR_4 as ITEM_ATTR_4", \
	"FIL_UNCHANGED_RECORDS___ITEM_ATTR_5 as ITEM_ATTR_5", \
	"FIL_UNCHANGED_RECORDS___LPN_BRK_ATTRIB as LPN_BRK_ATTRIB", \
	"FIL_UNCHANGED_RECORDS___MERCH_GRP as MERCH_GRP", \
	"FIL_UNCHANGED_RECORDS___MERCH_TYPE as MERCH_TYPE", \
	"FIL_UNCHANGED_RECORDS___PACK_ZONE as PACK_ZONE", \
	"FIL_UNCHANGED_RECORDS___PALLET_TYPE as PALLET_TYPE", \
	"FIL_UNCHANGED_RECORDS___PICK_LOCN_ASSIGN_TYPE as PICK_LOCN_ASSIGN_TYPE", \
	"FIL_UNCHANGED_RECORDS___PICK_LOCN_ID as PICK_LOCN_ID", \
	"FIL_UNCHANGED_RECORDS___PPACK_GRP_CODE as PPACK_GRP_CODE", \
	"FIL_UNCHANGED_RECORDS___PRICE_TKT_TYPE as PRICE_TKT_TYPE", \
	"DECODE ( LTRIM ( RTRIM ( UPPER ( FIL_UNCHANGED_RECORDS___SERIAL_NUMBER_REQUIRED_FLAG ) ) ) , 'Y','1' , '1','1','0' ) as o_SERIAL_NUMBER_REQUIRED_FLAG", \
	"FIL_UNCHANGED_RECORDS___SKU_GTIN as SKU_GTIN", \
	"FIL_UNCHANGED_RECORDS___SKU_SUB_CODE_ID as SKU_SUB_CODE_ID", \
	"FIL_UNCHANGED_RECORDS___SKU_SUB_CODE_VALUE as SKU_SUB_CODE_VALUE", \
	"FIL_UNCHANGED_RECORDS___VAS_PROCESS_TYPE as VAS_PROCESS_TYPE", \
	"FIL_UNCHANGED_RECORDS___SUBSTITUTED_PARENT_LINE_ID as SUBSTITUTED_PARENT_LINE_ID", \
	"DECODE ( LTRIM ( RTRIM ( UPPER ( FIL_UNCHANGED_RECORDS___IS_CANCELLED ) ) ) , 'Y','1' , '1','1','0' ) as o_CANCELLED_FLAG", \
	"FIL_UNCHANGED_RECORDS___ITEM_NAME as ITEM_NAME", \
	"FIL_UNCHANGED_RECORDS___ALLOC_LINE_ID as ALLOC_LINE_ID", \
	"FIL_UNCHANGED_RECORDS___ALLOCATION_SOURCE_ID as ALLOCATION_SOURCE_ID", \
	"FIL_UNCHANGED_RECORDS___ALLOCATION_SOURCE_LINE_ID as ALLOCATION_SOURCE_LINE_ID", \
	"FIL_UNCHANGED_RECORDS___ALLOCATION_SOURCE as ALLOCATION_SOURCE", \
	"FIL_UNCHANGED_RECORDS___SHELF_DAYS as SHELF_DAYS", \
	"FIL_UNCHANGED_RECORDS___FULFILLMENT_TYPE as FULFILLMENT_TYPE", \
	"FIL_UNCHANGED_RECORDS___WAVE_NBR as WAVE_NBR", \
	"FIL_UNCHANGED_RECORDS___SHIP_WAVE_NBR as SHIP_WAVE_NBR", \
	"FIL_UNCHANGED_RECORDS___REPL_WAVE_NBR as REPL_WAVE_NBR", \
	"DECODE ( LTRIM ( RTRIM ( UPPER ( FIL_UNCHANGED_RECORDS___SINGLE_UNIT_FLAG ) ) ) , 'Y','1' , '1','1','0' ) as o_SINGLE_UNIT_FLAG", \
	"FIL_UNCHANGED_RECORDS___ACTUAL_COST as ACTUAL_COST", \
	"FIL_UNCHANGED_RECORDS___QTY_CONV_FACTOR as QTY_CONV_FACTOR", \
	"FIL_UNCHANGED_RECORDS___PLANNED_WEIGHT as PLANNED_WEIGHT", \
	"FIL_UNCHANGED_RECORDS___RECEIVED_WEIGHT as RECEIVED_WEIGHT", \
	"FIL_UNCHANGED_RECORDS___SHIPPED_WEIGHT as SHIPPED_WEIGHT", \
	"FIL_UNCHANGED_RECORDS___WEIGHT_UOM_ID_BASE as WEIGHT_UOM_ID_BASE", \
	"FIL_UNCHANGED_RECORDS___WEIGHT_UOM_ID as WEIGHT_UOM_ID", \
	"FIL_UNCHANGED_RECORDS___PLANNED_VOLUME as PLANNED_VOLUME", \
	"FIL_UNCHANGED_RECORDS___RECEIVED_VOLUME as RECEIVED_VOLUME", \
	"FIL_UNCHANGED_RECORDS___SHIPPED_VOLUME as SHIPPED_VOLUME", \
	"FIL_UNCHANGED_RECORDS___VOLUME_UOM_ID_BASE as VOLUME_UOM_ID_BASE", \
	"FIL_UNCHANGED_RECORDS___VOLUME_UOM_ID as VOLUME_UOM_ID", \
	"FIL_UNCHANGED_RECORDS___SIZE1_UOM_ID as SIZE1_UOM_ID", \
	"FIL_UNCHANGED_RECORDS___SIZE1_VALUE as SIZE1_VALUE", \
	"FIL_UNCHANGED_RECORDS___RECEIVED_SIZE1 as RECEIVED_SIZE1", \
	"FIL_UNCHANGED_RECORDS___SHIPPED_SIZE1 as SHIPPED_SIZE1", \
	"FIL_UNCHANGED_RECORDS___SIZE2_UOM_ID as SIZE2_UOM_ID", \
	"FIL_UNCHANGED_RECORDS___SIZE2_VALUE as SIZE2_VALUE", \
	"FIL_UNCHANGED_RECORDS___RECEIVED_SIZE2 as RECEIVED_SIZE2", \
	"FIL_UNCHANGED_RECORDS___SHIPPED_SIZE2 as SHIPPED_SIZE2", \
	"FIL_UNCHANGED_RECORDS___LPN_TYPE as LPN_TYPE", \
	"FIL_UNCHANGED_RECORDS___ORDER_CONSOL_ATTR as ORDER_CONSOL_ATTR", \
	"FIL_UNCHANGED_RECORDS___SKU_BREAK_ATTR as SKU_BREAK_ATTR", \
	"FIL_UNCHANGED_RECORDS___PURCHASE_ORDER_NUMBER as PURCHASE_ORDER_NUMBER", \
	"FIL_UNCHANGED_RECORDS___EXT_PURCHASE_ORDER as EXT_PURCHASE_ORDER", \
	"FIL_UNCHANGED_RECORDS___CRITCL_DIM_1 as CRITCL_DIM_1", \
	"FIL_UNCHANGED_RECORDS___CRITCL_DIM_2 as CRITCL_DIM_2", \
	"FIL_UNCHANGED_RECORDS___CRITCL_DIM_3 as CRITCL_DIM_3", \
	"FIL_UNCHANGED_RECORDS___ASSORT_NBR as ASSORT_NBR", \
	"FIL_UNCHANGED_RECORDS___DESCRIPTION as DESCRIPTION", \
	"FIL_UNCHANGED_RECORDS___ORIGINAL_ORDERED_ITEM_ID as ORIGINAL_ORDERED_ITEM_ID", \
	"FIL_UNCHANGED_RECORDS___SUBSTITUTION_TYPE as SUBSTITUTION_TYPE", \
	"FIL_UNCHANGED_RECORDS___BACK_ORD_REASON as BACK_ORD_REASON", \
	"FIL_UNCHANGED_RECORDS___FREIGHT_REVENUE_CURRENCY_CODE as FREIGHT_REVENUE_CURRENCY_CODE", \
	"FIL_UNCHANGED_RECORDS___FREIGHT_REVENUE as FREIGHT_REVENUE", \
	"FIL_UNCHANGED_RECORDS___IS_CHASE_CREATED_LINE as IS_CHASE_CREATED_LINE", \
	"FIL_UNCHANGED_RECORDS___REF_FIELD4 as REF_FIELD4", \
	"FIL_UNCHANGED_RECORDS___REF_FIELD5 as REF_FIELD5", \
	"FIL_UNCHANGED_RECORDS___REF_FIELD6 as REF_FIELD6", \
	"FIL_UNCHANGED_RECORDS___REF_FIELD7 as REF_FIELD7", \
	"FIL_UNCHANGED_RECORDS___REF_FIELD8 as REF_FIELD8", \
	"FIL_UNCHANGED_RECORDS___REF_FIELD9 as REF_FIELD9", \
	"FIL_UNCHANGED_RECORDS___REF_FIELD10 as REF_FIELD10", \
	"FIL_UNCHANGED_RECORDS___REF_NUM1 as REF_NUM1", \
	"FIL_UNCHANGED_RECORDS___REF_NUM2 as REF_NUM2", \
	"FIL_UNCHANGED_RECORDS___REF_NUM3 as REF_NUM3", \
	"FIL_UNCHANGED_RECORDS___REF_NUM4 as REF_NUM4", \
	"FIL_UNCHANGED_RECORDS___REF_NUM5 as REF_NUM5", \
	"FIL_UNCHANGED_RECORDS___IS_GIFT as IS_GIFT", \
	"FIL_UNCHANGED_RECORDS___ADJUSTED_ORDER_QTY as ADJUSTED_ORDER_QTY", \
	"FIL_UNCHANGED_RECORDS___PRE_RECEIPT_STATUS as PRE_RECEIPT_STATUS", \
	"FIL_UNCHANGED_RECORDS___ALLOW_REVIVAL_RECEIPT_ALLOC as ALLOW_REVIVAL_RECEIPT_ALLOC", \
	"FIL_UNCHANGED_RECORDS___SEGMENT_NAME as SEGMENT_NAME", \
	"FIL_UNCHANGED_RECORDS___EFFECTIVE_RANK as EFFECTIVE_RANK", \
	"FIL_UNCHANGED_RECORDS___WM_RECEIPT_ALLOCATED as WM_RECEIPT_ALLOCATED", \
	"FIL_UNCHANGED_RECORDS___GIFT_CARD_VALUE as GIFT_CARD_VALUE", \
	"FIL_UNCHANGED_RECORDS___REF_BOOLEAN1 as REF_BOOLEAN1", \
	"FIL_UNCHANGED_RECORDS___REF_BOOLEAN2 as REF_BOOLEAN2", \
	"FIL_UNCHANGED_RECORDS___REF_SYSCODE1 as REF_SYSCODE1", \
	"FIL_UNCHANGED_RECORDS___REF_SYSCODE2 as REF_SYSCODE2", \
	"FIL_UNCHANGED_RECORDS___REF_SYSCODE3 as REF_SYSCODE3", \
	"FIL_UNCHANGED_RECORDS___HARD_ALLOC_REASON_CODE as HARD_ALLOC_REASON_CODE", \
	"FIL_UNCHANGED_RECORDS___LOCKED as LOCKED", \
	"CURRENT_TIMESTAMP as UPDATE_TSTMP", \
	"IF (FIL_UNCHANGED_RECORDS___i_LOAD_TSTMP IS NULL, CURRENT_TIMESTAMP, FIL_UNCHANGED_RECORDS___i_LOAD_TSTMP) as LOAD_TSTMP", \
	"IF (FIL_UNCHANGED_RECORDS___i_WM_ORDER_ID IS NULL, 1, 2) as o_UPDATE_VALIDATOR" \
)

# COMMAND ----------
# Processing node UPD_INS_UPD, type UPDATE_STRATEGY 
# COLUMN COUNT: 212

# for each involved DataFrame, append the dataframe name to each column
EXP_UPD_VALIDATOR_temp = EXP_UPD_VALIDATOR.toDF(*["EXP_UPD_VALIDATOR___" + col for col in EXP_UPD_VALIDATOR.columns])

UPD_INS_UPD = EXP_UPD_VALIDATOR_temp.selectExpr( \
	"EXP_UPD_VALIDATOR___LOCATION_ID as LOCATION_ID", \
	"EXP_UPD_VALIDATOR___ORDER_ID as ORDER_ID", \
	"EXP_UPD_VALIDATOR___LINE_ITEM_ID as LINE_ITEM_ID", \
	"EXP_UPD_VALIDATOR___PARENT_LINE_ITEM_ID as PARENT_LINE_ITEM_ID", \
	"EXP_UPD_VALIDATOR___TC_COMPANY_ID as TC_COMPANY_ID", \
	"EXP_UPD_VALIDATOR___COMMODITY_CLASS as COMMODITY_CLASS", \
	"EXP_UPD_VALIDATOR___REF_FIELD1 as REF_FIELD1", \
	"EXP_UPD_VALIDATOR___REF_FIELD2 as REF_FIELD2", \
	"EXP_UPD_VALIDATOR___REF_FIELD3 as REF_FIELD3", \
	"EXP_UPD_VALIDATOR___EXT_SYS_LINE_ITEM_ID as EXT_SYS_LINE_ITEM_ID", \
	"EXP_UPD_VALIDATOR___MASTER_ORDER_ID as MASTER_ORDER_ID", \
	"EXP_UPD_VALIDATOR___MO_LINE_ITEM_ID as MO_LINE_ITEM_ID", \
	"EXP_UPD_VALIDATOR___IS_HAZMAT as IS_HAZMAT", \
	"EXP_UPD_VALIDATOR___IS_STACKABLE as IS_STACKABLE", \
	"EXP_UPD_VALIDATOR___HAS_ERRORS as HAS_ERRORS", \
	"EXP_UPD_VALIDATOR___ORIG_BUDG_COST as ORIG_BUDG_COST", \
	"EXP_UPD_VALIDATOR___BUDG_COST_CURRENCY_CODE as BUDG_COST_CURRENCY_CODE", \
	"EXP_UPD_VALIDATOR___BUDG_COST as BUDG_COST", \
	"EXP_UPD_VALIDATOR___ACTUAL_COST_CURRENCY_CODE as ACTUAL_COST_CURRENCY_CODE", \
	"EXP_UPD_VALIDATOR___TOTAL_MONETARY_VALUE as TOTAL_MONETARY_VALUE", \
	"EXP_UPD_VALIDATOR___UNIT_MONETARY_VALUE as UNIT_MONETARY_VALUE", \
	"EXP_UPD_VALIDATOR___UNIT_TAX_AMOUNT as UNIT_TAX_AMOUNT", \
	"EXP_UPD_VALIDATOR___RTS_ID as RTS_ID", \
	"EXP_UPD_VALIDATOR___RTS_LINE_ITEM_ID as RTS_LINE_ITEM_ID", \
	"EXP_UPD_VALIDATOR___STD_PACK_QTY as STD_PACK_QTY", \
	"EXP_UPD_VALIDATOR___PRODUCT_CLASS_ID as PRODUCT_CLASS_ID", \
	"EXP_UPD_VALIDATOR___PROTECTION_LEVEL_ID as PROTECTION_LEVEL_ID", \
	"EXP_UPD_VALIDATOR___PACKAGE_TYPE_ID as PACKAGE_TYPE_ID", \
	"EXP_UPD_VALIDATOR___COMMODITY_CODE_ID as COMMODITY_CODE_ID", \
	"EXP_UPD_VALIDATOR___MV_SIZE_UOM_ID as MV_SIZE_UOM_ID", \
	"EXP_UPD_VALIDATOR___QTY_UOM_ID_BASE as QTY_UOM_ID_BASE", \
	"EXP_UPD_VALIDATOR___MV_CURRENCY_CODE as MV_CURRENCY_CODE", \
	"EXP_UPD_VALIDATOR___SHIPPED_QTY as SHIPPED_QTY", \
	"EXP_UPD_VALIDATOR___RECEIVED_QTY as RECEIVED_QTY", \
	"EXP_UPD_VALIDATOR___PRIORITY as PRIORITY", \
	"EXP_UPD_VALIDATOR___MERCHANDIZING_DEPARTMENT_ID as MERCHANDIZING_DEPARTMENT_ID", \
	"EXP_UPD_VALIDATOR___UN_NUMBER_ID as UN_NUMBER_ID", \
	"EXP_UPD_VALIDATOR___PICKUP_REFERENCE_NUMBER as PICKUP_REFERENCE_NUMBER", \
	"EXP_UPD_VALIDATOR___DELIVERY_REFERENCE_NUMBER as DELIVERY_REFERENCE_NUMBER", \
	"EXP_UPD_VALIDATOR___CNTRY_OF_ORGN as CNTRY_OF_ORGN", \
	"EXP_UPD_VALIDATOR___PROD_STAT as PROD_STAT", \
	"EXP_UPD_VALIDATOR___STACK_RANK as STACK_RANK", \
	"EXP_UPD_VALIDATOR___STACK_LENGTH_VALUE as STACK_LENGTH_VALUE", \
	"EXP_UPD_VALIDATOR___STACK_LENGTH_STANDARD_UOM as STACK_LENGTH_STANDARD_UOM", \
	"EXP_UPD_VALIDATOR___STACK_WIDTH_VALUE as STACK_WIDTH_VALUE", \
	"EXP_UPD_VALIDATOR___STACK_WIDTH_STANDARD_UOM as STACK_WIDTH_STANDARD_UOM", \
	"EXP_UPD_VALIDATOR___STACK_HEIGHT_VALUE as STACK_HEIGHT_VALUE", \
	"EXP_UPD_VALIDATOR___STACK_HEIGHT_STANDARD_UOM as STACK_HEIGHT_STANDARD_UOM", \
	"EXP_UPD_VALIDATOR___STACK_DIAMETER_VALUE as STACK_DIAMETER_VALUE", \
	"EXP_UPD_VALIDATOR___STACK_DIAMETER_STANDARD_UOM as STACK_DIAMETER_STANDARD_UOM", \
	"EXP_UPD_VALIDATOR___CREATED_SOURCE_TYPE as CREATED_SOURCE_TYPE", \
	"EXP_UPD_VALIDATOR___CREATED_SOURCE as CREATED_SOURCE", \
	"EXP_UPD_VALIDATOR___CREATED_DTTM as CREATED_DTTM", \
	"EXP_UPD_VALIDATOR___LAST_UPDATED_SOURCE_TYPE as LAST_UPDATED_SOURCE_TYPE", \
	"EXP_UPD_VALIDATOR___LAST_UPDATED_SOURCE as LAST_UPDATED_SOURCE", \
	"EXP_UPD_VALIDATOR___LAST_UPDATED_DTTM as LAST_UPDATED_DTTM", \
	"EXP_UPD_VALIDATOR___HIBERNATE_VERSION as HIBERNATE_VERSION", \
	"EXP_UPD_VALIDATOR___CUBE_MULTIPLE_QTY as CUBE_MULTIPLE_QTY", \
	"EXP_UPD_VALIDATOR___DO_DTL_STATUS as DO_DTL_STATUS", \
	"EXP_UPD_VALIDATOR___INTERNAL_ORDER_SEQ_NBR as INTERNAL_ORDER_SEQ_NBR", \
	"EXP_UPD_VALIDATOR___o_EMERGENCY_FLAG as o_EMERGENCY_FLAG", \
	"EXP_UPD_VALIDATOR___LPN_SIZE as LPN_SIZE", \
	"EXP_UPD_VALIDATOR___MANUFACTURING_DTTM as MANUFACTURING_DTTM", \
	"EXP_UPD_VALIDATOR___ORDER_LINE_ID as ORDER_LINE_ID", \
	"EXP_UPD_VALIDATOR___PACK_RATE as PACK_RATE", \
	"EXP_UPD_VALIDATOR___ALLOCATED_QTY as ALLOCATED_QTY", \
	"EXP_UPD_VALIDATOR___PLANNED_SHIP_DATE as PLANNED_SHIP_DATE", \
	"EXP_UPD_VALIDATOR___PPACK_QTY as PPACK_QTY", \
	"EXP_UPD_VALIDATOR___STD_BUNDLE_QTY as STD_BUNDLE_QTY", \
	"EXP_UPD_VALIDATOR___STD_LPN_QTY as STD_LPN_QTY", \
	"EXP_UPD_VALIDATOR___STD_LPN_VOL as STD_LPN_VOL", \
	"EXP_UPD_VALIDATOR___STD_LPN_WT as STD_LPN_WT", \
	"EXP_UPD_VALIDATOR___UNIT_COST as UNIT_COST", \
	"EXP_UPD_VALIDATOR___UNIT_PRICE_AMOUNT as UNIT_PRICE_AMOUNT", \
	"EXP_UPD_VALIDATOR___UNIT_VOL as UNIT_VOL", \
	"EXP_UPD_VALIDATOR___UNIT_WT as UNIT_WT", \
	"EXP_UPD_VALIDATOR___USER_CANCELED_QTY as USER_CANCELED_QTY", \
	"EXP_UPD_VALIDATOR___WAVE_PROC_TYPE as WAVE_PROC_TYPE", \
	"EXP_UPD_VALIDATOR___DELIVERY_END_DTTM as DELIVERY_END_DTTM", \
	"EXP_UPD_VALIDATOR___DELIVERY_START_DTTM as DELIVERY_START_DTTM", \
	"EXP_UPD_VALIDATOR___EVENT_CODE as EVENT_CODE", \
	"EXP_UPD_VALIDATOR___REASON_CODE as REASON_CODE", \
	"EXP_UPD_VALIDATOR___EXP_INFO_CODE as EXP_INFO_CODE", \
	"EXP_UPD_VALIDATOR___o_PARTL_FILL as o_PARTL_FILL", \
	"EXP_UPD_VALIDATOR___LINE_TYPE as LINE_TYPE", \
	"EXP_UPD_VALIDATOR___REPL_PROC_TYPE as REPL_PROC_TYPE", \
	"EXP_UPD_VALIDATOR___ORDER_QTY as ORDER_QTY", \
	"EXP_UPD_VALIDATOR___ORIG_ORDER_QTY as ORIG_ORDER_QTY", \
	"EXP_UPD_VALIDATOR___RTL_TO_BE_DISTROED_QTY as RTL_TO_BE_DISTROED_QTY", \
	"EXP_UPD_VALIDATOR___PRICE as PRICE", \
	"EXP_UPD_VALIDATOR___RETAIL_PRICE as RETAIL_PRICE", \
	"EXP_UPD_VALIDATOR___UNITS_PAKD as UNITS_PAKD", \
	"EXP_UPD_VALIDATOR___MINOR_ORDER_NBR as MINOR_ORDER_NBR", \
	"EXP_UPD_VALIDATOR___ITEM_ID as ITEM_ID", \
	"EXP_UPD_VALIDATOR___TC_ORDER_LINE_ID as TC_ORDER_LINE_ID", \
	"EXP_UPD_VALIDATOR___ACTUAL_SHIPPED_DTTM as ACTUAL_SHIPPED_DTTM", \
	"EXP_UPD_VALIDATOR___QTY_UOM_ID as QTY_UOM_ID", \
	"EXP_UPD_VALIDATOR___PICKUP_END_DTTM as PICKUP_END_DTTM", \
	"EXP_UPD_VALIDATOR___PURCHASE_ORDER_LINE_NUMBER as PURCHASE_ORDER_LINE_NUMBER", \
	"EXP_UPD_VALIDATOR___PICKUP_START_DTTM as PICKUP_START_DTTM", \
	"EXP_UPD_VALIDATOR___REFERENCE_LINE_ITEM_ID as REFERENCE_LINE_ITEM_ID", \
	"EXP_UPD_VALIDATOR___REFERENCE_ORDER_ID as REFERENCE_ORDER_ID", \
	"EXP_UPD_VALIDATOR___o_REPL_WAVE_RUN as o_REPL_WAVE_RUN", \
	"EXP_UPD_VALIDATOR___STD_PALLET_QTY as STD_PALLET_QTY", \
	"EXP_UPD_VALIDATOR___STD_SUB_PACK_QTY as STD_SUB_PACK_QTY", \
	"EXP_UPD_VALIDATOR___STORE_DEPT as STORE_DEPT", \
	"EXP_UPD_VALIDATOR___ALLOC_TYPE as ALLOC_TYPE", \
	"EXP_UPD_VALIDATOR___BATCH_NBR as BATCH_NBR", \
	"EXP_UPD_VALIDATOR___BATCH_REQUIREMENT_TYPE as BATCH_REQUIREMENT_TYPE", \
	"EXP_UPD_VALIDATOR___CHUTE_ASSIGN_TYPE as CHUTE_ASSIGN_TYPE", \
	"EXP_UPD_VALIDATOR___CUSTOM_TAG as CUSTOM_TAG", \
	"EXP_UPD_VALIDATOR___CUSTOMER_ITEM as CUSTOMER_ITEM", \
	"EXP_UPD_VALIDATOR___INTERNAL_ORDER_ID as INTERNAL_ORDER_ID", \
	"EXP_UPD_VALIDATOR___INVN_TYPE as INVN_TYPE", \
	"EXP_UPD_VALIDATOR___ITEM_ATTR_1 as ITEM_ATTR_1", \
	"EXP_UPD_VALIDATOR___ITEM_ATTR_2 as ITEM_ATTR_2", \
	"EXP_UPD_VALIDATOR___ITEM_ATTR_3 as ITEM_ATTR_3", \
	"EXP_UPD_VALIDATOR___ITEM_ATTR_4 as ITEM_ATTR_4", \
	"EXP_UPD_VALIDATOR___ITEM_ATTR_5 as ITEM_ATTR_5", \
	"EXP_UPD_VALIDATOR___LPN_BRK_ATTRIB as LPN_BRK_ATTRIB", \
	"EXP_UPD_VALIDATOR___MERCH_GRP as MERCH_GRP", \
	"EXP_UPD_VALIDATOR___MERCH_TYPE as MERCH_TYPE", \
	"EXP_UPD_VALIDATOR___PACK_ZONE as PACK_ZONE", \
	"EXP_UPD_VALIDATOR___PALLET_TYPE as PALLET_TYPE", \
	"EXP_UPD_VALIDATOR___PICK_LOCN_ASSIGN_TYPE as PICK_LOCN_ASSIGN_TYPE", \
	"EXP_UPD_VALIDATOR___PICK_LOCN_ID as PICK_LOCN_ID", \
	"EXP_UPD_VALIDATOR___PPACK_GRP_CODE as PPACK_GRP_CODE", \
	"EXP_UPD_VALIDATOR___PRICE_TKT_TYPE as PRICE_TKT_TYPE", \
	"EXP_UPD_VALIDATOR___o_SERIAL_NUMBER_REQUIRED_FLAG as o_SERIAL_NUMBER_REQUIRED_FLAG", \
	"EXP_UPD_VALIDATOR___SKU_GTIN as SKU_GTIN", \
	"EXP_UPD_VALIDATOR___SKU_SUB_CODE_ID as SKU_SUB_CODE_ID", \
	"EXP_UPD_VALIDATOR___SKU_SUB_CODE_VALUE as SKU_SUB_CODE_VALUE", \
	"EXP_UPD_VALIDATOR___VAS_PROCESS_TYPE as VAS_PROCESS_TYPE", \
	"EXP_UPD_VALIDATOR___SUBSTITUTED_PARENT_LINE_ID as SUBSTITUTED_PARENT_LINE_ID", \
	"EXP_UPD_VALIDATOR___o_CANCELLED_FLAG as o_CANCELLED_FLAG", \
	"EXP_UPD_VALIDATOR___ITEM_NAME as ITEM_NAME", \
	"EXP_UPD_VALIDATOR___ALLOC_LINE_ID as ALLOC_LINE_ID", \
	"EXP_UPD_VALIDATOR___ALLOCATION_SOURCE_ID as ALLOCATION_SOURCE_ID", \
	"EXP_UPD_VALIDATOR___ALLOCATION_SOURCE_LINE_ID as ALLOCATION_SOURCE_LINE_ID", \
	"EXP_UPD_VALIDATOR___ALLOCATION_SOURCE as ALLOCATION_SOURCE", \
	"EXP_UPD_VALIDATOR___SHELF_DAYS as SHELF_DAYS", \
	"EXP_UPD_VALIDATOR___FULFILLMENT_TYPE as FULFILLMENT_TYPE", \
	"EXP_UPD_VALIDATOR___WAVE_NBR as WAVE_NBR", \
	"EXP_UPD_VALIDATOR___SHIP_WAVE_NBR as SHIP_WAVE_NBR", \
	"EXP_UPD_VALIDATOR___REPL_WAVE_NBR as REPL_WAVE_NBR", \
	"EXP_UPD_VALIDATOR___o_SINGLE_UNIT_FLAG as o_SINGLE_UNIT_FLAG", \
	"EXP_UPD_VALIDATOR___ACTUAL_COST as ACTUAL_COST", \
	"EXP_UPD_VALIDATOR___QTY_CONV_FACTOR as QTY_CONV_FACTOR", \
	"EXP_UPD_VALIDATOR___PLANNED_WEIGHT as PLANNED_WEIGHT", \
	"EXP_UPD_VALIDATOR___RECEIVED_WEIGHT as RECEIVED_WEIGHT", \
	"EXP_UPD_VALIDATOR___SHIPPED_WEIGHT as SHIPPED_WEIGHT", \
	"EXP_UPD_VALIDATOR___WEIGHT_UOM_ID_BASE as WEIGHT_UOM_ID_BASE", \
	"EXP_UPD_VALIDATOR___WEIGHT_UOM_ID as WEIGHT_UOM_ID", \
	"EXP_UPD_VALIDATOR___PLANNED_VOLUME as PLANNED_VOLUME", \
	"EXP_UPD_VALIDATOR___RECEIVED_VOLUME as RECEIVED_VOLUME", \
	"EXP_UPD_VALIDATOR___SHIPPED_VOLUME as SHIPPED_VOLUME", \
	"EXP_UPD_VALIDATOR___VOLUME_UOM_ID_BASE as VOLUME_UOM_ID_BASE", \
	"EXP_UPD_VALIDATOR___VOLUME_UOM_ID as VOLUME_UOM_ID", \
	"EXP_UPD_VALIDATOR___SIZE1_UOM_ID as SIZE1_UOM_ID", \
	"EXP_UPD_VALIDATOR___SIZE1_VALUE as SIZE1_VALUE", \
	"EXP_UPD_VALIDATOR___RECEIVED_SIZE1 as RECEIVED_SIZE1", \
	"EXP_UPD_VALIDATOR___SHIPPED_SIZE1 as SHIPPED_SIZE1", \
	"EXP_UPD_VALIDATOR___SIZE2_UOM_ID as SIZE2_UOM_ID", \
	"EXP_UPD_VALIDATOR___SIZE2_VALUE as SIZE2_VALUE", \
	"EXP_UPD_VALIDATOR___RECEIVED_SIZE2 as RECEIVED_SIZE2", \
	"EXP_UPD_VALIDATOR___SHIPPED_SIZE2 as SHIPPED_SIZE2", \
	"EXP_UPD_VALIDATOR___LPN_TYPE as LPN_TYPE", \
	"EXP_UPD_VALIDATOR___ORDER_CONSOL_ATTR as ORDER_CONSOL_ATTR", \
	"EXP_UPD_VALIDATOR___SKU_BREAK_ATTR as SKU_BREAK_ATTR", \
	"EXP_UPD_VALIDATOR___PURCHASE_ORDER_NUMBER as PURCHASE_ORDER_NUMBER", \
	"EXP_UPD_VALIDATOR___EXT_PURCHASE_ORDER as EXT_PURCHASE_ORDER", \
	"EXP_UPD_VALIDATOR___CRITCL_DIM_1 as CRITCL_DIM_1", \
	"EXP_UPD_VALIDATOR___CRITCL_DIM_2 as CRITCL_DIM_2", \
	"EXP_UPD_VALIDATOR___CRITCL_DIM_3 as CRITCL_DIM_3", \
	"EXP_UPD_VALIDATOR___ASSORT_NBR as ASSORT_NBR", \
	"EXP_UPD_VALIDATOR___DESCRIPTION as DESCRIPTION", \
	"EXP_UPD_VALIDATOR___ORIGINAL_ORDERED_ITEM_ID as ORIGINAL_ORDERED_ITEM_ID", \
	"EXP_UPD_VALIDATOR___SUBSTITUTION_TYPE as SUBSTITUTION_TYPE", \
	"EXP_UPD_VALIDATOR___BACK_ORD_REASON as BACK_ORD_REASON", \
	"EXP_UPD_VALIDATOR___FREIGHT_REVENUE_CURRENCY_CODE as FREIGHT_REVENUE_CURRENCY_CODE", \
	"EXP_UPD_VALIDATOR___FREIGHT_REVENUE as FREIGHT_REVENUE", \
	"EXP_UPD_VALIDATOR___IS_CHASE_CREATED_LINE as IS_CHASE_CREATED_LINE", \
	"EXP_UPD_VALIDATOR___REF_FIELD4 as REF_FIELD4", \
	"EXP_UPD_VALIDATOR___REF_FIELD5 as REF_FIELD5", \
	"EXP_UPD_VALIDATOR___REF_FIELD6 as REF_FIELD6", \
	"EXP_UPD_VALIDATOR___REF_FIELD7 as REF_FIELD7", \
	"EXP_UPD_VALIDATOR___REF_FIELD8 as REF_FIELD8", \
	"EXP_UPD_VALIDATOR___REF_FIELD9 as REF_FIELD9", \
	"EXP_UPD_VALIDATOR___REF_FIELD10 as REF_FIELD10", \
	"EXP_UPD_VALIDATOR___REF_NUM1 as REF_NUM1", \
	"EXP_UPD_VALIDATOR___REF_NUM2 as REF_NUM2", \
	"EXP_UPD_VALIDATOR___REF_NUM3 as REF_NUM3", \
	"EXP_UPD_VALIDATOR___REF_NUM4 as REF_NUM4", \
	"EXP_UPD_VALIDATOR___REF_NUM5 as REF_NUM5", \
	"EXP_UPD_VALIDATOR___IS_GIFT as IS_GIFT", \
	"EXP_UPD_VALIDATOR___ADJUSTED_ORDER_QTY as ADJUSTED_ORDER_QTY", \
	"EXP_UPD_VALIDATOR___PRE_RECEIPT_STATUS as PRE_RECEIPT_STATUS", \
	"EXP_UPD_VALIDATOR___ALLOW_REVIVAL_RECEIPT_ALLOC as ALLOW_REVIVAL_RECEIPT_ALLOC", \
	"EXP_UPD_VALIDATOR___SEGMENT_NAME as SEGMENT_NAME", \
	"EXP_UPD_VALIDATOR___EFFECTIVE_RANK as EFFECTIVE_RANK", \
	"EXP_UPD_VALIDATOR___WM_RECEIPT_ALLOCATED as WM_RECEIPT_ALLOCATED", \
	"EXP_UPD_VALIDATOR___GIFT_CARD_VALUE as GIFT_CARD_VALUE", \
	"EXP_UPD_VALIDATOR___REF_BOOLEAN1 as REF_BOOLEAN1", \
	"EXP_UPD_VALIDATOR___REF_BOOLEAN2 as REF_BOOLEAN2", \
	"EXP_UPD_VALIDATOR___REF_SYSCODE1 as REF_SYSCODE1", \
	"EXP_UPD_VALIDATOR___REF_SYSCODE2 as REF_SYSCODE2", \
	"EXP_UPD_VALIDATOR___REF_SYSCODE3 as REF_SYSCODE3", \
	"EXP_UPD_VALIDATOR___HARD_ALLOC_REASON_CODE as HARD_ALLOC_REASON_CODE", \
	"EXP_UPD_VALIDATOR___LOCKED as LOCKED", \
	"EXP_UPD_VALIDATOR___UPDATE_TSTMP as UPDATE_TSTMP", \
	"EXP_UPD_VALIDATOR___LOAD_TSTMP as LOAD_TSTMP", \
	"EXP_UPD_VALIDATOR___o_UPDATE_VALIDATOR as o_UPDATE_VALIDATOR") \
	.withColumn('pyspark_data_action', when(EXP_UPD_VALIDATOR.o_UPDATE_VALIDATOR ==(lit(1)) , lit(0)) .when(EXP_UPD_VALIDATOR.o_UPDATE_VALIDATOR ==(lit(2)) , lit(1)))

# COMMAND ----------
# Processing node Shortcut_to_WM_ORDER_LINE_ITEM1, type TARGET 
# COLUMN COUNT: 211

try:
  primary_key = """source.LOCATION_ID = target.LOCATION_ID AND source.WM_ORDER_ID = target.WM_ORDER_ID AND source.WM_LINE_ITEM_ID = target.WM_LINE_ITEM_ID"""
  refined_perf_table = "WM_ORDER_LINE_ITEM"
  executeMerge(UPD_INS_UPD, refined_perf_table, primary_key)
  logger.info(f"Merge with {refined_perf_table} completed]")
  logPrevRunDt("WM_ORDER_LINE_ITEM", "WM_ORDER_LINE_ITEM", "Completed", "N/A", f"{raw}.log_run_details")
except Exception as e:
  logPrevRunDt("WM_ORDER_LINE_ITEM", "WM_ORDER_LINE_ITEM","Failed",str(e), f"{raw}.log_run_details", )
  raise e
	