#Code converted on 2023-06-27 10:22:31
import os
import argparse
from pyspark.sql import *
from pyspark.sql.functions import *
from pyspark.sql.window import Window
from pyspark.sql.types import *
from datetime import datetime
from pyspark.dbutils import DBUtils
from Datalake.utils.genericUtilities import *
from Datalake.utils.configs import *
from Datalake.utils.mergeUtils import *
from Datalake.utils.logger import *
# COMMAND ----------

parser = argparse.ArgumentParser()
spark = SparkSession.getActiveSession()
dbutils = DBUtils(spark)
parser.add_argument('env', type=str, help='Env Variable')
args = parser.parse_args()
env = args.env

if env is None or env == '':
    raise ValueError('env is not set')

refine = getEnvPrefix(env) + 'refine'
raw = getEnvPrefix(env) + 'raw'
legacy = getEnvPrefix(env) + 'legacy'

# Set global variables
starttime = datetime.now() #start timestamp of the script


# COMMAND ----------
pre_perf_table = f"{raw}.WM_E_EVNT_SMRY_HDR_PRE"
refined_perf_table = f"{refine}.WM_E_EVNT_SMRY_HDR"
site_profile_table = f"{legacy}.SITE_PROFILE"

Prev_Run_Dt=genPrevRunDt(refined_perf_table, refine,raw)
Del_Logic=args.Del_Logic
soft_delete_logic_Wm_E_Evnt_Smry_Hdr=args.soft_delete_logic_Wm_E_Evnt_Smry_Hdr

# COMMAND ----------
# Processing node SQ_Shortcut_to_WM_E_EVNT_SMRY_HDR_PRE, type SOURCE 
# COLUMN COUNT: 80

SQ_Shortcut_to_WM_E_EVNT_SMRY_HDR_PRE = spark.sql(f"""SELECT
WM_E_EVNT_SMRY_HDR_PRE.DC_NBR,
WM_E_EVNT_SMRY_HDR_PRE.ELS_TRAN_ID,
WM_E_EVNT_SMRY_HDR_PRE.WHSE,
WM_E_EVNT_SMRY_HDR_PRE.TRAN_NBR,
WM_E_EVNT_SMRY_HDR_PRE.CO,
WM_E_EVNT_SMRY_HDR_PRE.DIV,
WM_E_EVNT_SMRY_HDR_PRE.SCHED_START_DATE,
WM_E_EVNT_SMRY_HDR_PRE.REF_CODE,
WM_E_EVNT_SMRY_HDR_PRE.REF_NBR,
WM_E_EVNT_SMRY_HDR_PRE.LOGIN_USER_ID,
WM_E_EVNT_SMRY_HDR_PRE.DEPT_CODE,
WM_E_EVNT_SMRY_HDR_PRE.VHCL_TYPE,
WM_E_EVNT_SMRY_HDR_PRE.SHIFT_CODE,
WM_E_EVNT_SMRY_HDR_PRE.USER_DEF_FIELD_1,
WM_E_EVNT_SMRY_HDR_PRE.USER_DEF_FIELD_2,
WM_E_EVNT_SMRY_HDR_PRE.STD_TIME_ALLOW,
WM_E_EVNT_SMRY_HDR_PRE.EMP_PERF_ALLOW,
WM_E_EVNT_SMRY_HDR_PRE.PERF_ADJ_AMT,
WM_E_EVNT_SMRY_HDR_PRE.SCHED_ADJ_AMT,
WM_E_EVNT_SMRY_HDR_PRE.SCHED_UNITS_QTY,
WM_E_EVNT_SMRY_HDR_PRE.ACTL_TIME,
WM_E_EVNT_SMRY_HDR_PRE.ERROR_CNT,
WM_E_EVNT_SMRY_HDR_PRE.EVNT_STAT_CODE,
WM_E_EVNT_SMRY_HDR_PRE.CREATE_DATE_TIME,
WM_E_EVNT_SMRY_HDR_PRE.MOD_DATE_TIME,
WM_E_EVNT_SMRY_HDR_PRE.USER_ID,
WM_E_EVNT_SMRY_HDR_PRE.TMU_RECALC_COUNT,
WM_E_EVNT_SMRY_HDR_PRE.MISC,
WM_E_EVNT_SMRY_HDR_PRE.LABOR_TYPE_ID,
WM_E_EVNT_SMRY_HDR_PRE.SOURCE,
WM_E_EVNT_SMRY_HDR_PRE.EVENT_TYPE,
WM_E_EVNT_SMRY_HDR_PRE.TOTAL_WEIGHT,
WM_E_EVNT_SMRY_HDR_PRE.TEAM_STD_SMRY_ID,
WM_E_EVNT_SMRY_HDR_PRE.TEAM_CODE,
WM_E_EVNT_SMRY_HDR_PRE.ORIG_LOGIN_USER_ID,
WM_E_EVNT_SMRY_HDR_PRE.MISC_TXT_1,
WM_E_EVNT_SMRY_HDR_PRE.MISC_TXT_2,
WM_E_EVNT_SMRY_HDR_PRE.MISC_NUM_1,
WM_E_EVNT_SMRY_HDR_PRE.MISC_NUM_2,
WM_E_EVNT_SMRY_HDR_PRE.PROC_ZONE_ID,
WM_E_EVNT_SMRY_HDR_PRE.LAST_MOD_BY,
WM_E_EVNT_SMRY_HDR_PRE.EVNT_CTGRY_1,
WM_E_EVNT_SMRY_HDR_PRE.EVNT_CTGRY_2,
WM_E_EVNT_SMRY_HDR_PRE.EVNT_CTGRY_3,
WM_E_EVNT_SMRY_HDR_PRE.EVNT_CTGRY_4,
WM_E_EVNT_SMRY_HDR_PRE.EVNT_CTGRY_5,
WM_E_EVNT_SMRY_HDR_PRE.SYS_UPDATED_FLAG,
WM_E_EVNT_SMRY_HDR_PRE.APRV_SPVSR,
WM_E_EVNT_SMRY_HDR_PRE.APRV_SPVSR_DATE_TIME,
WM_E_EVNT_SMRY_HDR_PRE.VERSION_ID,
WM_E_EVNT_SMRY_HDR_PRE.TEAM_CHG_ID,
WM_E_EVNT_SMRY_HDR_PRE.ACTUAL_END_DATE,
WM_E_EVNT_SMRY_HDR_PRE.SPVSR_LOGIN_USER_ID,
WM_E_EVNT_SMRY_HDR_PRE.PAID_BRK_OVERLAP,
WM_E_EVNT_SMRY_HDR_PRE.UNPAID_BRK_OVERLAP,
WM_E_EVNT_SMRY_HDR_PRE.EMP_PERF_SMRY_ID,
WM_E_EVNT_SMRY_HDR_PRE.HDR_MSG_ID,
WM_E_EVNT_SMRY_HDR_PRE.ACT_ID,
WM_E_EVNT_SMRY_HDR_PRE.PERF_SMRY_TRAN_ID,
WM_E_EVNT_SMRY_HDR_PRE.ORIG_EVNT_START_TIME,
WM_E_EVNT_SMRY_HDR_PRE.ORIG_EVNT_END_TIME,
WM_E_EVNT_SMRY_HDR_PRE.ADJ_REASON_CODE,
WM_E_EVNT_SMRY_HDR_PRE.ADJ_REF_TRAN_NBR,
WM_E_EVNT_SMRY_HDR_PRE.CONFLICT,
WM_E_EVNT_SMRY_HDR_PRE.TEAM_BEGIN_TIME,
WM_E_EVNT_SMRY_HDR_PRE.THRUPUT_GOAL,
WM_E_EVNT_SMRY_HDR_PRE.THRUPUT_MIN,
WM_E_EVNT_SMRY_HDR_PRE.DISPLAY_UOM,
WM_E_EVNT_SMRY_HDR_PRE.DISPLAY_UOM_QTY,
WM_E_EVNT_SMRY_HDR_PRE.UNIT_MIN,
WM_E_EVNT_SMRY_HDR_PRE.CONSOL_EVNT_TIME,
WM_E_EVNT_SMRY_HDR_PRE.LOCN_GRP_ATTR,
WM_E_EVNT_SMRY_HDR_PRE.RESOURCE_GROUP_ID,
WM_E_EVNT_SMRY_HDR_PRE.JOB_FUNC_ID,
WM_E_EVNT_SMRY_HDR_PRE.COMP_EMPLOYEE_DAY_ID,
WM_E_EVNT_SMRY_HDR_PRE.COMP_EVENT_SUMMARY_HEADER_ID,
WM_E_EVNT_SMRY_HDR_PRE.ASSIGNMENT_START_TIME,
WM_E_EVNT_SMRY_HDR_PRE.ASSIGNMENT_END_TIME,
WM_E_EVNT_SMRY_HDR_PRE.REFLECTIVE_CODE,
WM_E_EVNT_SMRY_HDR_PRE.COMP_ASSIGNMENT_ID
FROM {pre_perf_table}""").withColumn("sys_row_id", monotonically_increasing_id())

# COMMAND ----------
# Processing node EXP_TRANS, type EXPRESSION 
# COLUMN COUNT: 81

# for each involved DataFrame, append the dataframe name to each column
SQ_Shortcut_to_WM_E_EVNT_SMRY_HDR_PRE_temp = SQ_Shortcut_to_WM_E_EVNT_SMRY_HDR_PRE.toDF(*["SQ_Shortcut_to_WM_E_EVNT_SMRY_HDR_PRE___" + col for col in SQ_Shortcut_to_WM_E_EVNT_SMRY_HDR_PRE.columns])

EXP_TRANS = SQ_Shortcut_to_WM_E_EVNT_SMRY_HDR_PRE_temp.selectExpr( \
	"SQ_Shortcut_to_WM_E_EVNT_SMRY_HDR_PRE___sys_row_id as sys_row_id", \
	"SQ_Shortcut_to_WM_E_EVNT_SMRY_HDR_PRE___DC_NBR as DC_NBR", \
	"cast(SQ_Shortcut_to_WM_E_EVNT_SMRY_HDR_PRE___DC_NBR as int) as o_DC_NBR", \
	"SQ_Shortcut_to_WM_E_EVNT_SMRY_HDR_PRE___ELS_TRAN_ID as ELS_TRAN_ID", \
	"SQ_Shortcut_to_WM_E_EVNT_SMRY_HDR_PRE___WHSE as WHSE", \
	"SQ_Shortcut_to_WM_E_EVNT_SMRY_HDR_PRE___TRAN_NBR as TRAN_NBR", \
	"SQ_Shortcut_to_WM_E_EVNT_SMRY_HDR_PRE___CO as CO", \
	"SQ_Shortcut_to_WM_E_EVNT_SMRY_HDR_PRE___DIV as DIV", \
	"SQ_Shortcut_to_WM_E_EVNT_SMRY_HDR_PRE___SCHED_START_DATE as SCHED_START_DATE", \
	"SQ_Shortcut_to_WM_E_EVNT_SMRY_HDR_PRE___REF_CODE as REF_CODE", \
	"SQ_Shortcut_to_WM_E_EVNT_SMRY_HDR_PRE___REF_NBR as REF_NBR", \
	"SQ_Shortcut_to_WM_E_EVNT_SMRY_HDR_PRE___LOGIN_USER_ID as LOGIN_USER_ID", \
	"SQ_Shortcut_to_WM_E_EVNT_SMRY_HDR_PRE___DEPT_CODE as DEPT_CODE", \
	"SQ_Shortcut_to_WM_E_EVNT_SMRY_HDR_PRE___VHCL_TYPE as VHCL_TYPE", \
	"SQ_Shortcut_to_WM_E_EVNT_SMRY_HDR_PRE___SHIFT_CODE as SHIFT_CODE", \
	"SQ_Shortcut_to_WM_E_EVNT_SMRY_HDR_PRE___USER_DEF_FIELD_1 as USER_DEF_FIELD_1", \
	"SQ_Shortcut_to_WM_E_EVNT_SMRY_HDR_PRE___USER_DEF_FIELD_2 as USER_DEF_FIELD_2", \
	"SQ_Shortcut_to_WM_E_EVNT_SMRY_HDR_PRE___STD_TIME_ALLOW as STD_TIME_ALLOW", \
	"SQ_Shortcut_to_WM_E_EVNT_SMRY_HDR_PRE___EMP_PERF_ALLOW as EMP_PERF_ALLOW", \
	"SQ_Shortcut_to_WM_E_EVNT_SMRY_HDR_PRE___PERF_ADJ_AMT as PERF_ADJ_AMT", \
	"SQ_Shortcut_to_WM_E_EVNT_SMRY_HDR_PRE___SCHED_ADJ_AMT as SCHED_ADJ_AMT", \
	"SQ_Shortcut_to_WM_E_EVNT_SMRY_HDR_PRE___SCHED_UNITS_QTY as SCHED_UNITS_QTY", \
	"SQ_Shortcut_to_WM_E_EVNT_SMRY_HDR_PRE___ACTL_TIME as ACTL_TIME", \
	"SQ_Shortcut_to_WM_E_EVNT_SMRY_HDR_PRE___ERROR_CNT as ERROR_CNT", \
	"SQ_Shortcut_to_WM_E_EVNT_SMRY_HDR_PRE___EVNT_STAT_CODE as EVNT_STAT_CODE", \
	"SQ_Shortcut_to_WM_E_EVNT_SMRY_HDR_PRE___CREATE_DATE_TIME as CREATE_DATE_TIME", \
	"SQ_Shortcut_to_WM_E_EVNT_SMRY_HDR_PRE___MOD_DATE_TIME as MOD_DATE_TIME", \
	"SQ_Shortcut_to_WM_E_EVNT_SMRY_HDR_PRE___USER_ID as USER_ID", \
	"SQ_Shortcut_to_WM_E_EVNT_SMRY_HDR_PRE___TMU_RECALC_COUNT as TMU_RECALC_COUNT", \
	"SQ_Shortcut_to_WM_E_EVNT_SMRY_HDR_PRE___MISC as MISC", \
	"SQ_Shortcut_to_WM_E_EVNT_SMRY_HDR_PRE___LABOR_TYPE_ID as LABOR_TYPE_ID", \
	"SQ_Shortcut_to_WM_E_EVNT_SMRY_HDR_PRE___SOURCE as SOURCE", \
	"SQ_Shortcut_to_WM_E_EVNT_SMRY_HDR_PRE___EVENT_TYPE as EVENT_TYPE", \
	"SQ_Shortcut_to_WM_E_EVNT_SMRY_HDR_PRE___TOTAL_WEIGHT as TOTAL_WEIGHT", \
	"SQ_Shortcut_to_WM_E_EVNT_SMRY_HDR_PRE___TEAM_STD_SMRY_ID as TEAM_STD_SMRY_ID", \
	"SQ_Shortcut_to_WM_E_EVNT_SMRY_HDR_PRE___TEAM_CODE as TEAM_CODE", \
	"SQ_Shortcut_to_WM_E_EVNT_SMRY_HDR_PRE___ORIG_LOGIN_USER_ID as ORIG_LOGIN_USER_ID", \
	"SQ_Shortcut_to_WM_E_EVNT_SMRY_HDR_PRE___MISC_TXT_1 as MISC_TXT_1", \
	"SQ_Shortcut_to_WM_E_EVNT_SMRY_HDR_PRE___MISC_TXT_2 as MISC_TXT_2", \
	"SQ_Shortcut_to_WM_E_EVNT_SMRY_HDR_PRE___MISC_NUM_1 as MISC_NUM_1", \
	"SQ_Shortcut_to_WM_E_EVNT_SMRY_HDR_PRE___MISC_NUM_2 as MISC_NUM_2", \
	"SQ_Shortcut_to_WM_E_EVNT_SMRY_HDR_PRE___PROC_ZONE_ID as PROC_ZONE_ID", \
	"SQ_Shortcut_to_WM_E_EVNT_SMRY_HDR_PRE___LAST_MOD_BY as LAST_MOD_BY", \
	"SQ_Shortcut_to_WM_E_EVNT_SMRY_HDR_PRE___EVNT_CTGRY_1 as EVNT_CTGRY_1", \
	"SQ_Shortcut_to_WM_E_EVNT_SMRY_HDR_PRE___EVNT_CTGRY_2 as EVNT_CTGRY_2", \
	"SQ_Shortcut_to_WM_E_EVNT_SMRY_HDR_PRE___EVNT_CTGRY_3 as EVNT_CTGRY_3", \
	"SQ_Shortcut_to_WM_E_EVNT_SMRY_HDR_PRE___EVNT_CTGRY_4 as EVNT_CTGRY_4", \
	"SQ_Shortcut_to_WM_E_EVNT_SMRY_HDR_PRE___EVNT_CTGRY_5 as EVNT_CTGRY_5", \
	"SQ_Shortcut_to_WM_E_EVNT_SMRY_HDR_PRE___SYS_UPDATED_FLAG as SYS_UPDATED_FLAG", \
	"SQ_Shortcut_to_WM_E_EVNT_SMRY_HDR_PRE___APRV_SPVSR as APRV_SPVSR", \
	"SQ_Shortcut_to_WM_E_EVNT_SMRY_HDR_PRE___APRV_SPVSR_DATE_TIME as APRV_SPVSR_DATE_TIME", \
	"SQ_Shortcut_to_WM_E_EVNT_SMRY_HDR_PRE___VERSION_ID as VERSION_ID", \
	"SQ_Shortcut_to_WM_E_EVNT_SMRY_HDR_PRE___TEAM_CHG_ID as TEAM_CHG_ID", \
	"SQ_Shortcut_to_WM_E_EVNT_SMRY_HDR_PRE___ACTUAL_END_DATE as ACTUAL_END_DATE", \
	"SQ_Shortcut_to_WM_E_EVNT_SMRY_HDR_PRE___SPVSR_LOGIN_USER_ID as SPVSR_LOGIN_USER_ID", \
	"SQ_Shortcut_to_WM_E_EVNT_SMRY_HDR_PRE___PAID_BRK_OVERLAP as PAID_BRK_OVERLAP", \
	"SQ_Shortcut_to_WM_E_EVNT_SMRY_HDR_PRE___UNPAID_BRK_OVERLAP as UNPAID_BRK_OVERLAP", \
	"SQ_Shortcut_to_WM_E_EVNT_SMRY_HDR_PRE___EMP_PERF_SMRY_ID as EMP_PERF_SMRY_ID", \
	"SQ_Shortcut_to_WM_E_EVNT_SMRY_HDR_PRE___HDR_MSG_ID as HDR_MSG_ID", \
	"SQ_Shortcut_to_WM_E_EVNT_SMRY_HDR_PRE___ACT_ID as ACT_ID", \
	"SQ_Shortcut_to_WM_E_EVNT_SMRY_HDR_PRE___PERF_SMRY_TRAN_ID as PERF_SMRY_TRAN_ID", \
	"SQ_Shortcut_to_WM_E_EVNT_SMRY_HDR_PRE___ORIG_EVNT_START_TIME as ORIG_EVNT_START_TIME", \
	"SQ_Shortcut_to_WM_E_EVNT_SMRY_HDR_PRE___ORIG_EVNT_END_TIME as ORIG_EVNT_END_TIME", \
	"SQ_Shortcut_to_WM_E_EVNT_SMRY_HDR_PRE___ADJ_REASON_CODE as ADJ_REASON_CODE", \
	"SQ_Shortcut_to_WM_E_EVNT_SMRY_HDR_PRE___ADJ_REF_TRAN_NBR as ADJ_REF_TRAN_NBR", \
	"SQ_Shortcut_to_WM_E_EVNT_SMRY_HDR_PRE___CONFLICT as CONFLICT", \
	"SQ_Shortcut_to_WM_E_EVNT_SMRY_HDR_PRE___TEAM_BEGIN_TIME as TEAM_BEGIN_TIME", \
	"SQ_Shortcut_to_WM_E_EVNT_SMRY_HDR_PRE___THRUPUT_GOAL as THRUPUT_GOAL", \
	"SQ_Shortcut_to_WM_E_EVNT_SMRY_HDR_PRE___THRUPUT_MIN as THRUPUT_MIN", \
	"SQ_Shortcut_to_WM_E_EVNT_SMRY_HDR_PRE___DISPLAY_UOM as DISPLAY_UOM", \
	"SQ_Shortcut_to_WM_E_EVNT_SMRY_HDR_PRE___DISPLAY_UOM_QTY as DISPLAY_UOM_QTY", \
	"SQ_Shortcut_to_WM_E_EVNT_SMRY_HDR_PRE___UNIT_MIN as UNIT_MIN", \
	"SQ_Shortcut_to_WM_E_EVNT_SMRY_HDR_PRE___CONSOL_EVNT_TIME as CONSOL_EVNT_TIME", \
	"SQ_Shortcut_to_WM_E_EVNT_SMRY_HDR_PRE___LOCN_GRP_ATTR as LOCN_GRP_ATTR", \
	"SQ_Shortcut_to_WM_E_EVNT_SMRY_HDR_PRE___RESOURCE_GROUP_ID as RESOURCE_GROUP_ID", \
	"SQ_Shortcut_to_WM_E_EVNT_SMRY_HDR_PRE___JOB_FUNC_ID as JOB_FUNC_ID", \
	"SQ_Shortcut_to_WM_E_EVNT_SMRY_HDR_PRE___COMP_EMPLOYEE_DAY_ID as COMP_EMPLOYEE_DAY_ID", \
	"SQ_Shortcut_to_WM_E_EVNT_SMRY_HDR_PRE___COMP_EVENT_SUMMARY_HEADER_ID as COMP_EVENT_SUMMARY_HEADER_ID", \
	"SQ_Shortcut_to_WM_E_EVNT_SMRY_HDR_PRE___ASSIGNMENT_START_TIME as ASSIGNMENT_START_TIME", \
	"SQ_Shortcut_to_WM_E_EVNT_SMRY_HDR_PRE___ASSIGNMENT_END_TIME as ASSIGNMENT_END_TIME", \
	"SQ_Shortcut_to_WM_E_EVNT_SMRY_HDR_PRE___REFLECTIVE_CODE as REFLECTIVE_CODE", \
	"SQ_Shortcut_to_WM_E_EVNT_SMRY_HDR_PRE___COMP_ASSIGNMENT_ID as COMP_ASSIGNMENT_ID" \
)

# COMMAND ----------
# Processing node SQ_Shortcut_to_WM_E_EVNT_SMRY_HDR, type SOURCE 
# COLUMN COUNT: 83

SQ_Shortcut_to_WM_E_EVNT_SMRY_HDR = spark.sql(f"""SELECT
WM_E_EVNT_SMRY_HDR.LOCATION_ID,
WM_E_EVNT_SMRY_HDR.WM_ELS_TRAN_ID,
WM_E_EVNT_SMRY_HDR.WM_WHSE,
WM_E_EVNT_SMRY_HDR.WM_LOGIN_USER_ID,
WM_E_EVNT_SMRY_HDR.WM_SHIFT_CD,
WM_E_EVNT_SMRY_HDR.WM_ORIG_EVNT_START_TSTMP,
WM_E_EVNT_SMRY_HDR.WM_ORIG_EVNT_END_TSTMP,
WM_E_EVNT_SMRY_HDR.WM_SCHED_START_TSTMP,
WM_E_EVNT_SMRY_HDR.WM_ACTUAL_END_TSTMP,
WM_E_EVNT_SMRY_HDR.WM_EVNT_STAT_CD,
WM_E_EVNT_SMRY_HDR.WM_LABOR_TYPE_ID,
WM_E_EVNT_SMRY_HDR.WM_JOB_FUNC_ID,
WM_E_EVNT_SMRY_HDR.WM_DEPT_CD,
WM_E_EVNT_SMRY_HDR.WM_RESOURCE_GROUP_ID,
WM_E_EVNT_SMRY_HDR.WM_LOCN_GRP_ATTR,
WM_E_EVNT_SMRY_HDR.WM_EMP_PERF_SMRY_ID,
WM_E_EVNT_SMRY_HDR.WM_HDR_MSG_ID,
WM_E_EVNT_SMRY_HDR.WM_ACT_ID,
WM_E_EVNT_SMRY_HDR.WM_PERF_SMRY_TRAN_ID,
WM_E_EVNT_SMRY_HDR.WM_SPVSR_LOGIN_USER_ID,
WM_E_EVNT_SMRY_HDR.WM_ORIG_LOGIN_USER_ID,
WM_E_EVNT_SMRY_HDR.WM_TRAN_NBR,
WM_E_EVNT_SMRY_HDR.WM_COMP_EMPLOYEE_DAY_ID,
WM_E_EVNT_SMRY_HDR.WM_COMP_EVENT_SUMMARY_HEADER_ID,
WM_E_EVNT_SMRY_HDR.ASSIGNMENT_START_TSTMP,
WM_E_EVNT_SMRY_HDR.ASSIGNMENT_END_TSTMP,
WM_E_EVNT_SMRY_HDR.WM_REFLECTIVE_CD,
WM_E_EVNT_SMRY_HDR.WM_COMP_ASSIGNMENT_ID,
WM_E_EVNT_SMRY_HDR.WM_ADJ_REASON_CD,
WM_E_EVNT_SMRY_HDR.WM_ADJ_REF_TRAN_NBR,
WM_E_EVNT_SMRY_HDR.WM_CO,
WM_E_EVNT_SMRY_HDR.WM_DIV,
WM_E_EVNT_SMRY_HDR.WM_REF_CD,
WM_E_EVNT_SMRY_HDR.WM_REF_NBR,
WM_E_EVNT_SMRY_HDR.WM_TEAM_STD_SMRY_ID,
WM_E_EVNT_SMRY_HDR.WM_TEAM_CD,
WM_E_EVNT_SMRY_HDR.TEAM_BEGIN_TSTMP,
WM_E_EVNT_SMRY_HDR.WM_PROC_ZONE_ID,
WM_E_EVNT_SMRY_HDR.WM_EVENT_TYPE,
WM_E_EVNT_SMRY_HDR.WM_EVNT_CTGRY_1,
WM_E_EVNT_SMRY_HDR.WM_EVNT_CTGRY_2,
WM_E_EVNT_SMRY_HDR.WM_EVNT_CTGRY_3,
WM_E_EVNT_SMRY_HDR.WM_EVNT_CTGRY_4,
WM_E_EVNT_SMRY_HDR.WM_EVNT_CTGRY_5,
WM_E_EVNT_SMRY_HDR.CONFLICT,
WM_E_EVNT_SMRY_HDR.WM_APRV_SPVSR,
WM_E_EVNT_SMRY_HDR.WM_APRV_SPVSR_TSTMP,
WM_E_EVNT_SMRY_HDR.WM_TEAM_CHG_ID,
WM_E_EVNT_SMRY_HDR.VHCL_TYPE,
WM_E_EVNT_SMRY_HDR.CONSOL_EVNT_TIME,
WM_E_EVNT_SMRY_HDR.ACTL_TIME,
WM_E_EVNT_SMRY_HDR.STD_TIME_ALLOW,
WM_E_EVNT_SMRY_HDR.EMP_PERF_ALLOW,
WM_E_EVNT_SMRY_HDR.PERF_ADJ_AMT,
WM_E_EVNT_SMRY_HDR.SCHED_ADJ_AMT,
WM_E_EVNT_SMRY_HDR.SCHED_UNITS_QTY,
WM_E_EVNT_SMRY_HDR.TMU_RECALC_CNT,
WM_E_EVNT_SMRY_HDR.TOTAL_WEIGHT,
WM_E_EVNT_SMRY_HDR.PAID_BRK_OVERLAP,
WM_E_EVNT_SMRY_HDR.UNPAID_BRK_OVERLAP,
WM_E_EVNT_SMRY_HDR.THRUPUT_GOAL,
WM_E_EVNT_SMRY_HDR.THRUPUT_MIN,
WM_E_EVNT_SMRY_HDR.DISPLAY_UOM,
WM_E_EVNT_SMRY_HDR.DISPLAY_UOM_QTY,
WM_E_EVNT_SMRY_HDR.UNIT_MIN,
WM_E_EVNT_SMRY_HDR.ERROR_CNT,
WM_E_EVNT_SMRY_HDR.USER_DEF_FIELD_1,
WM_E_EVNT_SMRY_HDR.USER_DEF_FIELD_2,
WM_E_EVNT_SMRY_HDR.MISC,
WM_E_EVNT_SMRY_HDR.MISC_TXT_1,
WM_E_EVNT_SMRY_HDR.MISC_TXT_2,
WM_E_EVNT_SMRY_HDR.MISC_NUM_1,
WM_E_EVNT_SMRY_HDR.MISC_NUM_2,
WM_E_EVNT_SMRY_HDR.SOURCE,
WM_E_EVNT_SMRY_HDR.WM_SYS_UPDATED_FLAG,
WM_E_EVNT_SMRY_HDR.LAST_MOD_BY,
WM_E_EVNT_SMRY_HDR.WM_USER_ID,
WM_E_EVNT_SMRY_HDR.WM_VERSION_ID,
WM_E_EVNT_SMRY_HDR.WM_CREATE_TSTMP,
WM_E_EVNT_SMRY_HDR.WM_MOD_TSTMP,
WM_E_EVNT_SMRY_HDR.DELETE_FLAG,
WM_E_EVNT_SMRY_HDR.UPDATE_TSTMP,
WM_E_EVNT_SMRY_HDR.LOAD_TSTMP
FROM {refined_perf_table}
WHERE {Del_Logic} 1=0 and 

DELETE_FLAG = 0""").withColumn("sys_row_id", monotonically_increasing_id())

# COMMAND ----------
# Processing node SQ_Shortcut_to_SITE_PROFILE, type SOURCE 
# COLUMN COUNT: 2

SQ_Shortcut_to_SITE_PROFILE = spark.sql(f"""SELECT
SITE_PROFILE.LOCATION_ID,
SITE_PROFILE.STORE_NBR
FROM {site_profile_table}""").withColumn("sys_row_id", monotonically_increasing_id())

# COMMAND ----------
# Processing node JNR_SITE_PROFILE, type JOINER 
# COLUMN COUNT: 82

JNR_SITE_PROFILE = SQ_Shortcut_to_SITE_PROFILE.join(EXP_TRANS,[SQ_Shortcut_to_SITE_PROFILE.STORE_NBR == EXP_TRANS.o_DC_NBR],'inner')

# COMMAND ----------
# Processing node JNR_WM_E_EVNT_SMRY_HDR, type JOINER . Note: using additional SELECT to rename incoming columns
# COLUMN COUNT: 163

# for each involved DataFrame, append the dataframe name to each column
SQ_Shortcut_to_WM_E_EVNT_SMRY_HDR_temp = SQ_Shortcut_to_WM_E_EVNT_SMRY_HDR.toDF(*["SQ_Shortcut_to_WM_E_EVNT_SMRY_HDR___" + col for col in SQ_Shortcut_to_WM_E_EVNT_SMRY_HDR.columns])
JNR_SITE_PROFILE_temp = JNR_SITE_PROFILE.toDF(*["JNR_SITE_PROFILE___" + col for col in JNR_SITE_PROFILE.columns])

JNR_WM_E_EVNT_SMRY_HDR = SQ_Shortcut_to_WM_E_EVNT_SMRY_HDR_temp.join(JNR_SITE_PROFILE_temp,[SQ_Shortcut_to_WM_E_EVNT_SMRY_HDR_temp.SQ_Shortcut_to_WM_E_EVNT_SMRY_HDR___LOCATION_ID == JNR_SITE_PROFILE_temp.JNR_SITE_PROFILE___LOCATION_ID, SQ_Shortcut_to_WM_E_EVNT_SMRY_HDR_temp.SQ_Shortcut_to_WM_E_EVNT_SMRY_HDR___WM_ELS_TRAN_ID == JNR_SITE_PROFILE_temp.JNR_SITE_PROFILE___ELS_TRAN_ID],'right_outer').selectExpr( \
	"JNR_SITE_PROFILE___LOCATION_ID as LOCATION_ID", \
	"JNR_SITE_PROFILE___ELS_TRAN_ID as ELS_TRAN_ID", \
	"JNR_SITE_PROFILE___WHSE as WHSE", \
	"JNR_SITE_PROFILE___TRAN_NBR as TRAN_NBR", \
	"JNR_SITE_PROFILE___CO as CO", \
	"JNR_SITE_PROFILE___DIV as DIV", \
	"JNR_SITE_PROFILE___SCHED_START_DATE as SCHED_START_DATE", \
	"JNR_SITE_PROFILE___REF_CODE as REF_CODE", \
	"JNR_SITE_PROFILE___REF_NBR as REF_NBR", \
	"JNR_SITE_PROFILE___LOGIN_USER_ID as LOGIN_USER_ID", \
	"JNR_SITE_PROFILE___DEPT_CODE as DEPT_CODE", \
	"JNR_SITE_PROFILE___VHCL_TYPE as VHCL_TYPE", \
	"JNR_SITE_PROFILE___SHIFT_CODE as SHIFT_CODE", \
	"JNR_SITE_PROFILE___USER_DEF_FIELD_1 as USER_DEF_FIELD_1", \
	"JNR_SITE_PROFILE___USER_DEF_FIELD_2 as USER_DEF_FIELD_2", \
	"JNR_SITE_PROFILE___STD_TIME_ALLOW as STD_TIME_ALLOW", \
	"JNR_SITE_PROFILE___EMP_PERF_ALLOW as EMP_PERF_ALLOW", \
	"JNR_SITE_PROFILE___PERF_ADJ_AMT as PERF_ADJ_AMT", \
	"JNR_SITE_PROFILE___SCHED_ADJ_AMT as SCHED_ADJ_AMT", \
	"JNR_SITE_PROFILE___SCHED_UNITS_QTY as SCHED_UNITS_QTY", \
	"JNR_SITE_PROFILE___ACTL_TIME as ACTL_TIME", \
	"JNR_SITE_PROFILE___ERROR_CNT as ERROR_CNT", \
	"JNR_SITE_PROFILE___EVNT_STAT_CODE as EVNT_STAT_CODE", \
	"JNR_SITE_PROFILE___CREATE_DATE_TIME as CREATE_DATE_TIME", \
	"JNR_SITE_PROFILE___MOD_DATE_TIME as MOD_DATE_TIME", \
	"JNR_SITE_PROFILE___USER_ID as USER_ID", \
	"JNR_SITE_PROFILE___TMU_RECALC_COUNT as TMU_RECALC_COUNT", \
	"JNR_SITE_PROFILE___MISC as MISC", \
	"JNR_SITE_PROFILE___LABOR_TYPE_ID as LABOR_TYPE_ID", \
	"JNR_SITE_PROFILE___SOURCE as SOURCE", \
	"JNR_SITE_PROFILE___EVENT_TYPE as EVENT_TYPE", \
	"JNR_SITE_PROFILE___TOTAL_WEIGHT as TOTAL_WEIGHT", \
	"JNR_SITE_PROFILE___TEAM_STD_SMRY_ID as TEAM_STD_SMRY_ID", \
	"JNR_SITE_PROFILE___TEAM_CODE as TEAM_CODE", \
	"JNR_SITE_PROFILE___ORIG_LOGIN_USER_ID as ORIG_LOGIN_USER_ID", \
	"JNR_SITE_PROFILE___MISC_TXT_1 as MISC_TXT_1", \
	"JNR_SITE_PROFILE___MISC_TXT_2 as MISC_TXT_2", \
	"JNR_SITE_PROFILE___MISC_NUM_1 as MISC_NUM_1", \
	"JNR_SITE_PROFILE___MISC_NUM_2 as MISC_NUM_2", \
	"JNR_SITE_PROFILE___PROC_ZONE_ID as PROC_ZONE_ID", \
	"JNR_SITE_PROFILE___LAST_MOD_BY as LAST_MOD_BY", \
	"JNR_SITE_PROFILE___EVNT_CTGRY_1 as EVNT_CTGRY_1", \
	"JNR_SITE_PROFILE___EVNT_CTGRY_2 as EVNT_CTGRY_2", \
	"JNR_SITE_PROFILE___EVNT_CTGRY_3 as EVNT_CTGRY_3", \
	"JNR_SITE_PROFILE___EVNT_CTGRY_4 as EVNT_CTGRY_4", \
	"JNR_SITE_PROFILE___EVNT_CTGRY_5 as EVNT_CTGRY_5", \
	"JNR_SITE_PROFILE___SYS_UPDATED_FLAG as SYS_UPDATED_FLAG", \
	"JNR_SITE_PROFILE___APRV_SPVSR as APRV_SPVSR", \
	"JNR_SITE_PROFILE___APRV_SPVSR_DATE_TIME as APRV_SPVSR_DATE_TIME", \
	"JNR_SITE_PROFILE___VERSION_ID as VERSION_ID", \
	"JNR_SITE_PROFILE___TEAM_CHG_ID as TEAM_CHG_ID", \
	"JNR_SITE_PROFILE___ACTUAL_END_DATE as ACTUAL_END_DATE", \
	"JNR_SITE_PROFILE___SPVSR_LOGIN_USER_ID as SPVSR_LOGIN_USER_ID", \
	"JNR_SITE_PROFILE___PAID_BRK_OVERLAP as PAID_BRK_OVERLAP", \
	"JNR_SITE_PROFILE___UNPAID_BRK_OVERLAP as UNPAID_BRK_OVERLAP", \
	"JNR_SITE_PROFILE___EMP_PERF_SMRY_ID as EMP_PERF_SMRY_ID", \
	"JNR_SITE_PROFILE___HDR_MSG_ID as HDR_MSG_ID", \
	"JNR_SITE_PROFILE___ACT_ID as ACT_ID", \
	"JNR_SITE_PROFILE___PERF_SMRY_TRAN_ID as PERF_SMRY_TRAN_ID", \
	"JNR_SITE_PROFILE___ORIG_EVNT_START_TIME as ORIG_EVNT_START_TIME", \
	"JNR_SITE_PROFILE___ORIG_EVNT_END_TIME as ORIG_EVNT_END_TIME", \
	"JNR_SITE_PROFILE___ADJ_REASON_CODE as ADJ_REASON_CODE", \
	"JNR_SITE_PROFILE___ADJ_REF_TRAN_NBR as ADJ_REF_TRAN_NBR", \
	"JNR_SITE_PROFILE___CONFLICT as CONFLICT", \
	"JNR_SITE_PROFILE___TEAM_BEGIN_TIME as TEAM_BEGIN_TIME", \
	"JNR_SITE_PROFILE___THRUPUT_GOAL as THRUPUT_GOAL", \
	"JNR_SITE_PROFILE___THRUPUT_MIN as THRUPUT_MIN", \
	"JNR_SITE_PROFILE___DISPLAY_UOM as DISPLAY_UOM", \
	"JNR_SITE_PROFILE___DISPLAY_UOM_QTY as DISPLAY_UOM_QTY", \
	"JNR_SITE_PROFILE___UNIT_MIN as UNIT_MIN", \
	"JNR_SITE_PROFILE___CONSOL_EVNT_TIME as CONSOL_EVNT_TIME", \
	"JNR_SITE_PROFILE___LOCN_GRP_ATTR as LOCN_GRP_ATTR", \
	"JNR_SITE_PROFILE___RESOURCE_GROUP_ID as RESOURCE_GROUP_ID", \
	"JNR_SITE_PROFILE___JOB_FUNC_ID as JOB_FUNC_ID", \
	"JNR_SITE_PROFILE___COMP_EMPLOYEE_DAY_ID as COMP_EMPLOYEE_DAY_ID", \
	"JNR_SITE_PROFILE___COMP_EVENT_SUMMARY_HEADER_ID as COMP_EVENT_SUMMARY_HEADER_ID", \
	"JNR_SITE_PROFILE___ASSIGNMENT_START_TIME as ASSIGNMENT_START_TIME", \
	"JNR_SITE_PROFILE___ASSIGNMENT_END_TIME as ASSIGNMENT_END_TIME", \
	"JNR_SITE_PROFILE___REFLECTIVE_CODE as REFLECTIVE_CODE", \
	"JNR_SITE_PROFILE___COMP_ASSIGNMENT_ID as COMP_ASSIGNMENT_ID", \
	"SQ_Shortcut_to_WM_E_EVNT_SMRY_HDR___LOCATION_ID as i_LOCATION_ID", \
	"SQ_Shortcut_to_WM_E_EVNT_SMRY_HDR___WM_ELS_TRAN_ID as i_WM_ELS_TRAN_ID", \
	"SQ_Shortcut_to_WM_E_EVNT_SMRY_HDR___WM_WHSE as i_WM_WHSE", \
	"SQ_Shortcut_to_WM_E_EVNT_SMRY_HDR___WM_LOGIN_USER_ID as i_WM_LOGIN_USER_ID", \
	"SQ_Shortcut_to_WM_E_EVNT_SMRY_HDR___WM_SHIFT_CD as i_WM_SHIFT_CD", \
	"SQ_Shortcut_to_WM_E_EVNT_SMRY_HDR___WM_ORIG_EVNT_START_TSTMP as i_WM_ORIG_EVNT_START_TSTMP", \
	"SQ_Shortcut_to_WM_E_EVNT_SMRY_HDR___WM_ORIG_EVNT_END_TSTMP as i_WM_ORIG_EVNT_END_TSTMP", \
	"SQ_Shortcut_to_WM_E_EVNT_SMRY_HDR___WM_SCHED_START_TSTMP as i_WM_SCHED_START_TSTMP", \
	"SQ_Shortcut_to_WM_E_EVNT_SMRY_HDR___WM_ACTUAL_END_TSTMP as i_WM_ACTUAL_END_TSTMP", \
	"SQ_Shortcut_to_WM_E_EVNT_SMRY_HDR___WM_EVNT_STAT_CD as i_WM_EVNT_STAT_CD", \
	"SQ_Shortcut_to_WM_E_EVNT_SMRY_HDR___WM_LABOR_TYPE_ID as i_WM_LABOR_TYPE_ID", \
	"SQ_Shortcut_to_WM_E_EVNT_SMRY_HDR___WM_JOB_FUNC_ID as i_WM_JOB_FUNC_ID", \
	"SQ_Shortcut_to_WM_E_EVNT_SMRY_HDR___WM_DEPT_CD as i_WM_DEPT_CD", \
	"SQ_Shortcut_to_WM_E_EVNT_SMRY_HDR___WM_RESOURCE_GROUP_ID as i_WM_RESOURCE_GROUP_ID", \
	"SQ_Shortcut_to_WM_E_EVNT_SMRY_HDR___WM_LOCN_GRP_ATTR as i_WM_LOCN_GRP_ATTR", \
	"SQ_Shortcut_to_WM_E_EVNT_SMRY_HDR___WM_EMP_PERF_SMRY_ID as i_WM_EMP_PERF_SMRY_ID", \
	"SQ_Shortcut_to_WM_E_EVNT_SMRY_HDR___WM_HDR_MSG_ID as i_WM_HDR_MSG_ID", \
	"SQ_Shortcut_to_WM_E_EVNT_SMRY_HDR___WM_ACT_ID as i_WM_ACT_ID", \
	"SQ_Shortcut_to_WM_E_EVNT_SMRY_HDR___WM_PERF_SMRY_TRAN_ID as i_WM_PERF_SMRY_TRAN_ID", \
	"SQ_Shortcut_to_WM_E_EVNT_SMRY_HDR___WM_SPVSR_LOGIN_USER_ID as i_WM_SPVSR_LOGIN_USER_ID", \
	"SQ_Shortcut_to_WM_E_EVNT_SMRY_HDR___WM_ORIG_LOGIN_USER_ID as i_WM_ORIG_LOGIN_USER_ID", \
	"SQ_Shortcut_to_WM_E_EVNT_SMRY_HDR___WM_TRAN_NBR as i_WM_TRAN_NBR", \
	"SQ_Shortcut_to_WM_E_EVNT_SMRY_HDR___WM_COMP_EMPLOYEE_DAY_ID as i_WM_COMP_EMPLOYEE_DAY_ID", \
	"SQ_Shortcut_to_WM_E_EVNT_SMRY_HDR___WM_COMP_EVENT_SUMMARY_HEADER_ID as i_WM_COMP_EVENT_SUMMARY_HEADER_ID", \
	"SQ_Shortcut_to_WM_E_EVNT_SMRY_HDR___ASSIGNMENT_START_TSTMP as i_ASSIGNMENT_START_TSTMP", \
	"SQ_Shortcut_to_WM_E_EVNT_SMRY_HDR___ASSIGNMENT_END_TSTMP as i_ASSIGNMENT_END_TSTMP", \
	"SQ_Shortcut_to_WM_E_EVNT_SMRY_HDR___WM_REFLECTIVE_CD as i_WM_REFLECTIVE_CD", \
	"SQ_Shortcut_to_WM_E_EVNT_SMRY_HDR___WM_COMP_ASSIGNMENT_ID as i_WM_COMP_ASSIGNMENT_ID", \
	"SQ_Shortcut_to_WM_E_EVNT_SMRY_HDR___WM_ADJ_REASON_CD as i_WM_ADJ_REASON_CD", \
	"SQ_Shortcut_to_WM_E_EVNT_SMRY_HDR___WM_ADJ_REF_TRAN_NBR as i_WM_ADJ_REF_TRAN_NBR", \
	"SQ_Shortcut_to_WM_E_EVNT_SMRY_HDR___WM_CO as i_WM_CO", \
	"SQ_Shortcut_to_WM_E_EVNT_SMRY_HDR___WM_DIV as i_WM_DIV", \
	"SQ_Shortcut_to_WM_E_EVNT_SMRY_HDR___WM_REF_CD as i_WM_REF_CD", \
	"SQ_Shortcut_to_WM_E_EVNT_SMRY_HDR___WM_REF_NBR as i_WM_REF_NBR", \
	"SQ_Shortcut_to_WM_E_EVNT_SMRY_HDR___WM_TEAM_STD_SMRY_ID as i_WM_TEAM_STD_SMRY_ID", \
	"SQ_Shortcut_to_WM_E_EVNT_SMRY_HDR___WM_TEAM_CD as i_WM_TEAM_CD", \
	"SQ_Shortcut_to_WM_E_EVNT_SMRY_HDR___TEAM_BEGIN_TSTMP as i_TEAM_BEGIN_TSTMP", \
	"SQ_Shortcut_to_WM_E_EVNT_SMRY_HDR___WM_PROC_ZONE_ID as i_WM_PROC_ZONE_ID", \
	"SQ_Shortcut_to_WM_E_EVNT_SMRY_HDR___WM_EVENT_TYPE as i_WM_EVENT_TYPE", \
	"SQ_Shortcut_to_WM_E_EVNT_SMRY_HDR___WM_EVNT_CTGRY_1 as i_WM_EVNT_CTGRY_1", \
	"SQ_Shortcut_to_WM_E_EVNT_SMRY_HDR___WM_EVNT_CTGRY_2 as i_WM_EVNT_CTGRY_2", \
	"SQ_Shortcut_to_WM_E_EVNT_SMRY_HDR___WM_EVNT_CTGRY_3 as i_WM_EVNT_CTGRY_3", \
	"SQ_Shortcut_to_WM_E_EVNT_SMRY_HDR___WM_EVNT_CTGRY_4 as i_WM_EVNT_CTGRY_4", \
	"SQ_Shortcut_to_WM_E_EVNT_SMRY_HDR___WM_EVNT_CTGRY_5 as i_WM_EVNT_CTGRY_5", \
	"SQ_Shortcut_to_WM_E_EVNT_SMRY_HDR___CONFLICT as i_CONFLICT1", \
	"SQ_Shortcut_to_WM_E_EVNT_SMRY_HDR___WM_APRV_SPVSR as i_WM_APRV_SPVSR", \
	"SQ_Shortcut_to_WM_E_EVNT_SMRY_HDR___WM_APRV_SPVSR_TSTMP as i_WM_APRV_SPVSR_TSTMP", \
	"SQ_Shortcut_to_WM_E_EVNT_SMRY_HDR___WM_TEAM_CHG_ID as i_WM_TEAM_CHG_ID", \
	"SQ_Shortcut_to_WM_E_EVNT_SMRY_HDR___VHCL_TYPE as i_VHCL_TYPE1", \
	"SQ_Shortcut_to_WM_E_EVNT_SMRY_HDR___CONSOL_EVNT_TIME as i_CONSOL_EVNT_TIME1", \
	"SQ_Shortcut_to_WM_E_EVNT_SMRY_HDR___ACTL_TIME as i_ACTL_TIME1", \
	"SQ_Shortcut_to_WM_E_EVNT_SMRY_HDR___STD_TIME_ALLOW as i_STD_TIME_ALLOW1", \
	"SQ_Shortcut_to_WM_E_EVNT_SMRY_HDR___EMP_PERF_ALLOW as i_EMP_PERF_ALLOW1", \
	"SQ_Shortcut_to_WM_E_EVNT_SMRY_HDR___PERF_ADJ_AMT as i_PERF_ADJ_AMT1", \
	"SQ_Shortcut_to_WM_E_EVNT_SMRY_HDR___SCHED_ADJ_AMT as i_SCHED_ADJ_AMT1", \
	"SQ_Shortcut_to_WM_E_EVNT_SMRY_HDR___SCHED_UNITS_QTY as i_SCHED_UNITS_QTY1", \
	"SQ_Shortcut_to_WM_E_EVNT_SMRY_HDR___TMU_RECALC_CNT as i_TMU_RECALC_CNT", \
	"SQ_Shortcut_to_WM_E_EVNT_SMRY_HDR___TOTAL_WEIGHT as i_TOTAL_WEIGHT1", \
	"SQ_Shortcut_to_WM_E_EVNT_SMRY_HDR___PAID_BRK_OVERLAP as i_PAID_BRK_OVERLAP1", \
	"SQ_Shortcut_to_WM_E_EVNT_SMRY_HDR___UNPAID_BRK_OVERLAP as i_UNPAID_BRK_OVERLAP1", \
	"SQ_Shortcut_to_WM_E_EVNT_SMRY_HDR___THRUPUT_GOAL as i_THRUPUT_GOAL1", \
	"SQ_Shortcut_to_WM_E_EVNT_SMRY_HDR___THRUPUT_MIN as i_THRUPUT_MIN1", \
	"SQ_Shortcut_to_WM_E_EVNT_SMRY_HDR___DISPLAY_UOM as i_DISPLAY_UOM1", \
	"SQ_Shortcut_to_WM_E_EVNT_SMRY_HDR___DISPLAY_UOM_QTY as i_DISPLAY_UOM_QTY1", \
	"SQ_Shortcut_to_WM_E_EVNT_SMRY_HDR___UNIT_MIN as i_UNIT_MIN1", \
	"SQ_Shortcut_to_WM_E_EVNT_SMRY_HDR___ERROR_CNT as i_ERROR_CNT1", \
	"SQ_Shortcut_to_WM_E_EVNT_SMRY_HDR___USER_DEF_FIELD_1 as i_USER_DEF_FIELD_11", \
	"SQ_Shortcut_to_WM_E_EVNT_SMRY_HDR___USER_DEF_FIELD_2 as i_USER_DEF_FIELD_21", \
	"SQ_Shortcut_to_WM_E_EVNT_SMRY_HDR___MISC as i_MISC1", \
	"SQ_Shortcut_to_WM_E_EVNT_SMRY_HDR___MISC_TXT_1 as i_MISC_TXT_11", \
	"SQ_Shortcut_to_WM_E_EVNT_SMRY_HDR___MISC_TXT_2 as i_MISC_TXT_21", \
	"SQ_Shortcut_to_WM_E_EVNT_SMRY_HDR___MISC_NUM_1 as i_MISC_NUM_11", \
	"SQ_Shortcut_to_WM_E_EVNT_SMRY_HDR___MISC_NUM_2 as i_MISC_NUM_21", \
	"SQ_Shortcut_to_WM_E_EVNT_SMRY_HDR___SOURCE as i_SOURCE1", \
	"SQ_Shortcut_to_WM_E_EVNT_SMRY_HDR___WM_SYS_UPDATED_FLAG as i_WM_SYS_UPDATED_FLAG", \
	"SQ_Shortcut_to_WM_E_EVNT_SMRY_HDR___LAST_MOD_BY as i_LAST_MOD_BY1", \
	"SQ_Shortcut_to_WM_E_EVNT_SMRY_HDR___WM_USER_ID as i_WM_USER_ID", \
	"SQ_Shortcut_to_WM_E_EVNT_SMRY_HDR___WM_VERSION_ID as i_WM_VERSION_ID", \
	"SQ_Shortcut_to_WM_E_EVNT_SMRY_HDR___WM_CREATE_TSTMP as i_WM_CREATE_TSTMP", \
	"SQ_Shortcut_to_WM_E_EVNT_SMRY_HDR___WM_MOD_TSTMP as i_WM_MOD_TSTMP", \
	"SQ_Shortcut_to_WM_E_EVNT_SMRY_HDR___DELETE_FLAG as i_DELETE_FLAG", \
	"SQ_Shortcut_to_WM_E_EVNT_SMRY_HDR___UPDATE_TSTMP as i_UPDATE_TSTMP", \
	"SQ_Shortcut_to_WM_E_EVNT_SMRY_HDR___LOAD_TSTMP as i_LOAD_TSTMP")

# COMMAND ----------
# Processing node FIL_UNCHANGED_RECORDS, type FILTER 
# COLUMN COUNT: 163

# for each involved DataFrame, append the dataframe name to each column
JNR_WM_E_EVNT_SMRY_HDR_temp = JNR_WM_E_EVNT_SMRY_HDR.toDF(*["JNR_WM_E_EVNT_SMRY_HDR___" + col for col in JNR_WM_E_EVNT_SMRY_HDR.columns])

FIL_UNCHANGED_RECORDS = JNR_WM_E_EVNT_SMRY_HDR_temp.selectExpr( \
	"JNR_WM_E_EVNT_SMRY_HDR___LOCATION_ID as LOCATION_ID", \
	"JNR_WM_E_EVNT_SMRY_HDR___ELS_TRAN_ID as ELS_TRAN_ID", \
	"JNR_WM_E_EVNT_SMRY_HDR___WHSE as WHSE", \
	"JNR_WM_E_EVNT_SMRY_HDR___TRAN_NBR as TRAN_NBR", \
	"JNR_WM_E_EVNT_SMRY_HDR___CO as CO", \
	"JNR_WM_E_EVNT_SMRY_HDR___DIV as DIV", \
	"JNR_WM_E_EVNT_SMRY_HDR___SCHED_START_DATE as SCHED_START_DATE", \
	"JNR_WM_E_EVNT_SMRY_HDR___REF_CODE as REF_CODE", \
	"JNR_WM_E_EVNT_SMRY_HDR___REF_NBR as REF_NBR", \
	"JNR_WM_E_EVNT_SMRY_HDR___LOGIN_USER_ID as LOGIN_USER_ID", \
	"JNR_WM_E_EVNT_SMRY_HDR___DEPT_CODE as DEPT_CODE", \
	"JNR_WM_E_EVNT_SMRY_HDR___VHCL_TYPE as VHCL_TYPE", \
	"JNR_WM_E_EVNT_SMRY_HDR___SHIFT_CODE as SHIFT_CODE", \
	"JNR_WM_E_EVNT_SMRY_HDR___USER_DEF_FIELD_1 as USER_DEF_FIELD_1", \
	"JNR_WM_E_EVNT_SMRY_HDR___USER_DEF_FIELD_2 as USER_DEF_FIELD_2", \
	"JNR_WM_E_EVNT_SMRY_HDR___STD_TIME_ALLOW as STD_TIME_ALLOW", \
	"JNR_WM_E_EVNT_SMRY_HDR___EMP_PERF_ALLOW as EMP_PERF_ALLOW", \
	"JNR_WM_E_EVNT_SMRY_HDR___PERF_ADJ_AMT as PERF_ADJ_AMT", \
	"JNR_WM_E_EVNT_SMRY_HDR___SCHED_ADJ_AMT as SCHED_ADJ_AMT", \
	"JNR_WM_E_EVNT_SMRY_HDR___SCHED_UNITS_QTY as SCHED_UNITS_QTY", \
	"JNR_WM_E_EVNT_SMRY_HDR___ACTL_TIME as ACTL_TIME", \
	"JNR_WM_E_EVNT_SMRY_HDR___ERROR_CNT as ERROR_CNT", \
	"JNR_WM_E_EVNT_SMRY_HDR___EVNT_STAT_CODE as EVNT_STAT_CODE", \
	"JNR_WM_E_EVNT_SMRY_HDR___CREATE_DATE_TIME as CREATE_DATE_TIME", \
	"JNR_WM_E_EVNT_SMRY_HDR___MOD_DATE_TIME as MOD_DATE_TIME", \
	"JNR_WM_E_EVNT_SMRY_HDR___USER_ID as USER_ID", \
	"JNR_WM_E_EVNT_SMRY_HDR___TMU_RECALC_COUNT as TMU_RECALC_COUNT", \
	"JNR_WM_E_EVNT_SMRY_HDR___MISC as MISC", \
	"JNR_WM_E_EVNT_SMRY_HDR___LABOR_TYPE_ID as LABOR_TYPE_ID", \
	"JNR_WM_E_EVNT_SMRY_HDR___SOURCE as SOURCE", \
	"JNR_WM_E_EVNT_SMRY_HDR___EVENT_TYPE as EVENT_TYPE", \
	"JNR_WM_E_EVNT_SMRY_HDR___TOTAL_WEIGHT as TOTAL_WEIGHT", \
	"JNR_WM_E_EVNT_SMRY_HDR___TEAM_STD_SMRY_ID as TEAM_STD_SMRY_ID", \
	"JNR_WM_E_EVNT_SMRY_HDR___TEAM_CODE as TEAM_CODE", \
	"JNR_WM_E_EVNT_SMRY_HDR___ORIG_LOGIN_USER_ID as ORIG_LOGIN_USER_ID", \
	"JNR_WM_E_EVNT_SMRY_HDR___MISC_TXT_1 as MISC_TXT_1", \
	"JNR_WM_E_EVNT_SMRY_HDR___MISC_TXT_2 as MISC_TXT_2", \
	"JNR_WM_E_EVNT_SMRY_HDR___MISC_NUM_1 as MISC_NUM_1", \
	"JNR_WM_E_EVNT_SMRY_HDR___MISC_NUM_2 as MISC_NUM_2", \
	"JNR_WM_E_EVNT_SMRY_HDR___PROC_ZONE_ID as PROC_ZONE_ID", \
	"JNR_WM_E_EVNT_SMRY_HDR___LAST_MOD_BY as LAST_MOD_BY", \
	"JNR_WM_E_EVNT_SMRY_HDR___EVNT_CTGRY_1 as EVNT_CTGRY_1", \
	"JNR_WM_E_EVNT_SMRY_HDR___EVNT_CTGRY_2 as EVNT_CTGRY_2", \
	"JNR_WM_E_EVNT_SMRY_HDR___EVNT_CTGRY_3 as EVNT_CTGRY_3", \
	"JNR_WM_E_EVNT_SMRY_HDR___EVNT_CTGRY_4 as EVNT_CTGRY_4", \
	"JNR_WM_E_EVNT_SMRY_HDR___EVNT_CTGRY_5 as EVNT_CTGRY_5", \
	"JNR_WM_E_EVNT_SMRY_HDR___SYS_UPDATED_FLAG as SYS_UPDATED_FLAG", \
	"JNR_WM_E_EVNT_SMRY_HDR___APRV_SPVSR as APRV_SPVSR", \
	"JNR_WM_E_EVNT_SMRY_HDR___APRV_SPVSR_DATE_TIME as APRV_SPVSR_DATE_TIME", \
	"JNR_WM_E_EVNT_SMRY_HDR___VERSION_ID as VERSION_ID", \
	"JNR_WM_E_EVNT_SMRY_HDR___TEAM_CHG_ID as TEAM_CHG_ID", \
	"JNR_WM_E_EVNT_SMRY_HDR___ACTUAL_END_DATE as ACTUAL_END_DATE", \
	"JNR_WM_E_EVNT_SMRY_HDR___SPVSR_LOGIN_USER_ID as SPVSR_LOGIN_USER_ID", \
	"JNR_WM_E_EVNT_SMRY_HDR___PAID_BRK_OVERLAP as PAID_BRK_OVERLAP", \
	"JNR_WM_E_EVNT_SMRY_HDR___UNPAID_BRK_OVERLAP as UNPAID_BRK_OVERLAP", \
	"JNR_WM_E_EVNT_SMRY_HDR___EMP_PERF_SMRY_ID as EMP_PERF_SMRY_ID", \
	"JNR_WM_E_EVNT_SMRY_HDR___HDR_MSG_ID as HDR_MSG_ID", \
	"JNR_WM_E_EVNT_SMRY_HDR___ACT_ID as ACT_ID", \
	"JNR_WM_E_EVNT_SMRY_HDR___PERF_SMRY_TRAN_ID as PERF_SMRY_TRAN_ID", \
	"JNR_WM_E_EVNT_SMRY_HDR___ORIG_EVNT_START_TIME as ORIG_EVNT_START_TIME", \
	"JNR_WM_E_EVNT_SMRY_HDR___ORIG_EVNT_END_TIME as ORIG_EVNT_END_TIME", \
	"JNR_WM_E_EVNT_SMRY_HDR___ADJ_REASON_CODE as ADJ_REASON_CODE", \
	"JNR_WM_E_EVNT_SMRY_HDR___ADJ_REF_TRAN_NBR as ADJ_REF_TRAN_NBR", \
	"JNR_WM_E_EVNT_SMRY_HDR___CONFLICT as CONFLICT", \
	"JNR_WM_E_EVNT_SMRY_HDR___TEAM_BEGIN_TIME as TEAM_BEGIN_TIME", \
	"JNR_WM_E_EVNT_SMRY_HDR___THRUPUT_GOAL as THRUPUT_GOAL", \
	"JNR_WM_E_EVNT_SMRY_HDR___THRUPUT_MIN as THRUPUT_MIN", \
	"JNR_WM_E_EVNT_SMRY_HDR___DISPLAY_UOM as DISPLAY_UOM", \
	"JNR_WM_E_EVNT_SMRY_HDR___DISPLAY_UOM_QTY as DISPLAY_UOM_QTY", \
	"JNR_WM_E_EVNT_SMRY_HDR___UNIT_MIN as UNIT_MIN", \
	"JNR_WM_E_EVNT_SMRY_HDR___CONSOL_EVNT_TIME as CONSOL_EVNT_TIME", \
	"JNR_WM_E_EVNT_SMRY_HDR___LOCN_GRP_ATTR as LOCN_GRP_ATTR", \
	"JNR_WM_E_EVNT_SMRY_HDR___RESOURCE_GROUP_ID as RESOURCE_GROUP_ID", \
	"JNR_WM_E_EVNT_SMRY_HDR___JOB_FUNC_ID as JOB_FUNC_ID", \
	"JNR_WM_E_EVNT_SMRY_HDR___COMP_EMPLOYEE_DAY_ID as COMP_EMPLOYEE_DAY_ID", \
	"JNR_WM_E_EVNT_SMRY_HDR___COMP_EVENT_SUMMARY_HEADER_ID as COMP_EVENT_SUMMARY_HEADER_ID", \
	"JNR_WM_E_EVNT_SMRY_HDR___ASSIGNMENT_START_TIME as ASSIGNMENT_START_TIME", \
	"JNR_WM_E_EVNT_SMRY_HDR___ASSIGNMENT_END_TIME as ASSIGNMENT_END_TIME", \
	"JNR_WM_E_EVNT_SMRY_HDR___REFLECTIVE_CODE as REFLECTIVE_CODE", \
	"JNR_WM_E_EVNT_SMRY_HDR___COMP_ASSIGNMENT_ID as COMP_ASSIGNMENT_ID", \
	"JNR_WM_E_EVNT_SMRY_HDR___i_LOCATION_ID as i_LOCATION_ID", \
	"JNR_WM_E_EVNT_SMRY_HDR___i_WM_ELS_TRAN_ID as i_WM_ELS_TRAN_ID", \
	"JNR_WM_E_EVNT_SMRY_HDR___i_WM_WHSE as i_WM_WHSE", \
	"JNR_WM_E_EVNT_SMRY_HDR___i_WM_LOGIN_USER_ID as i_WM_LOGIN_USER_ID", \
	"JNR_WM_E_EVNT_SMRY_HDR___i_WM_SHIFT_CD as i_WM_SHIFT_CD", \
	"JNR_WM_E_EVNT_SMRY_HDR___i_WM_ORIG_EVNT_START_TSTMP as i_WM_ORIG_EVNT_START_TSTMP", \
	"JNR_WM_E_EVNT_SMRY_HDR___i_WM_ORIG_EVNT_END_TSTMP as i_WM_ORIG_EVNT_END_TSTMP", \
	"JNR_WM_E_EVNT_SMRY_HDR___i_WM_SCHED_START_TSTMP as i_WM_SCHED_START_TSTMP", \
	"JNR_WM_E_EVNT_SMRY_HDR___i_WM_ACTUAL_END_TSTMP as i_WM_ACTUAL_END_TSTMP", \
	"JNR_WM_E_EVNT_SMRY_HDR___i_WM_EVNT_STAT_CD as i_WM_EVNT_STAT_CD", \
	"JNR_WM_E_EVNT_SMRY_HDR___i_WM_LABOR_TYPE_ID as i_WM_LABOR_TYPE_ID", \
	"JNR_WM_E_EVNT_SMRY_HDR___i_WM_JOB_FUNC_ID as i_WM_JOB_FUNC_ID", \
	"JNR_WM_E_EVNT_SMRY_HDR___i_WM_DEPT_CD as i_WM_DEPT_CD", \
	"JNR_WM_E_EVNT_SMRY_HDR___i_WM_RESOURCE_GROUP_ID as i_WM_RESOURCE_GROUP_ID", \
	"JNR_WM_E_EVNT_SMRY_HDR___i_WM_LOCN_GRP_ATTR as i_WM_LOCN_GRP_ATTR", \
	"JNR_WM_E_EVNT_SMRY_HDR___i_WM_EMP_PERF_SMRY_ID as i_WM_EMP_PERF_SMRY_ID", \
	"JNR_WM_E_EVNT_SMRY_HDR___i_WM_HDR_MSG_ID as i_WM_HDR_MSG_ID", \
	"JNR_WM_E_EVNT_SMRY_HDR___i_WM_ACT_ID as i_WM_ACT_ID", \
	"JNR_WM_E_EVNT_SMRY_HDR___i_WM_PERF_SMRY_TRAN_ID as i_WM_PERF_SMRY_TRAN_ID", \
	"JNR_WM_E_EVNT_SMRY_HDR___i_WM_SPVSR_LOGIN_USER_ID as i_WM_SPVSR_LOGIN_USER_ID", \
	"JNR_WM_E_EVNT_SMRY_HDR___i_WM_ORIG_LOGIN_USER_ID as i_WM_ORIG_LOGIN_USER_ID", \
	"JNR_WM_E_EVNT_SMRY_HDR___i_WM_TRAN_NBR as i_WM_TRAN_NBR", \
	"JNR_WM_E_EVNT_SMRY_HDR___i_WM_COMP_EMPLOYEE_DAY_ID as i_WM_COMP_EMPLOYEE_DAY_ID", \
	"JNR_WM_E_EVNT_SMRY_HDR___i_WM_COMP_EVENT_SUMMARY_HEADER_ID as i_WM_COMP_EVENT_SUMMARY_HEADER_ID", \
	"JNR_WM_E_EVNT_SMRY_HDR___i_ASSIGNMENT_START_TSTMP as i_ASSIGNMENT_START_TSTMP", \
	"JNR_WM_E_EVNT_SMRY_HDR___i_ASSIGNMENT_END_TSTMP as i_ASSIGNMENT_END_TSTMP", \
	"JNR_WM_E_EVNT_SMRY_HDR___i_WM_REFLECTIVE_CD as i_WM_REFLECTIVE_CD", \
	"JNR_WM_E_EVNT_SMRY_HDR___i_WM_COMP_ASSIGNMENT_ID as i_WM_COMP_ASSIGNMENT_ID", \
	"JNR_WM_E_EVNT_SMRY_HDR___i_WM_ADJ_REASON_CD as i_WM_ADJ_REASON_CD", \
	"JNR_WM_E_EVNT_SMRY_HDR___i_WM_ADJ_REF_TRAN_NBR as i_WM_ADJ_REF_TRAN_NBR", \
	"JNR_WM_E_EVNT_SMRY_HDR___i_WM_CO as i_WM_CO", \
	"JNR_WM_E_EVNT_SMRY_HDR___i_WM_DIV as i_WM_DIV", \
	"JNR_WM_E_EVNT_SMRY_HDR___i_WM_REF_CD as i_WM_REF_CD", \
	"JNR_WM_E_EVNT_SMRY_HDR___i_WM_REF_NBR as i_WM_REF_NBR", \
	"JNR_WM_E_EVNT_SMRY_HDR___i_WM_TEAM_STD_SMRY_ID as i_WM_TEAM_STD_SMRY_ID", \
	"JNR_WM_E_EVNT_SMRY_HDR___i_WM_TEAM_CD as i_WM_TEAM_CD", \
	"JNR_WM_E_EVNT_SMRY_HDR___i_TEAM_BEGIN_TSTMP as i_TEAM_BEGIN_TSTMP", \
	"JNR_WM_E_EVNT_SMRY_HDR___i_WM_PROC_ZONE_ID as i_WM_PROC_ZONE_ID", \
	"JNR_WM_E_EVNT_SMRY_HDR___i_WM_EVENT_TYPE as i_WM_EVENT_TYPE", \
	"JNR_WM_E_EVNT_SMRY_HDR___i_WM_EVNT_CTGRY_1 as i_WM_EVNT_CTGRY_1", \
	"JNR_WM_E_EVNT_SMRY_HDR___i_WM_EVNT_CTGRY_2 as i_WM_EVNT_CTGRY_2", \
	"JNR_WM_E_EVNT_SMRY_HDR___i_WM_EVNT_CTGRY_3 as i_WM_EVNT_CTGRY_3", \
	"JNR_WM_E_EVNT_SMRY_HDR___i_WM_EVNT_CTGRY_4 as i_WM_EVNT_CTGRY_4", \
	"JNR_WM_E_EVNT_SMRY_HDR___i_WM_EVNT_CTGRY_5 as i_WM_EVNT_CTGRY_5", \
	"JNR_WM_E_EVNT_SMRY_HDR___i_CONFLICT1 as i_CONFLICT1", \
	"JNR_WM_E_EVNT_SMRY_HDR___i_WM_APRV_SPVSR as i_WM_APRV_SPVSR", \
	"JNR_WM_E_EVNT_SMRY_HDR___i_WM_APRV_SPVSR_TSTMP as i_WM_APRV_SPVSR_TSTMP", \
	"JNR_WM_E_EVNT_SMRY_HDR___i_WM_TEAM_CHG_ID as i_WM_TEAM_CHG_ID", \
	"JNR_WM_E_EVNT_SMRY_HDR___i_VHCL_TYPE1 as i_VHCL_TYPE1", \
	"JNR_WM_E_EVNT_SMRY_HDR___i_CONSOL_EVNT_TIME1 as i_CONSOL_EVNT_TIME1", \
	"JNR_WM_E_EVNT_SMRY_HDR___i_ACTL_TIME1 as i_ACTL_TIME1", \
	"JNR_WM_E_EVNT_SMRY_HDR___i_STD_TIME_ALLOW1 as i_STD_TIME_ALLOW1", \
	"JNR_WM_E_EVNT_SMRY_HDR___i_EMP_PERF_ALLOW1 as i_EMP_PERF_ALLOW1", \
	"JNR_WM_E_EVNT_SMRY_HDR___i_PERF_ADJ_AMT1 as i_PERF_ADJ_AMT1", \
	"JNR_WM_E_EVNT_SMRY_HDR___i_SCHED_ADJ_AMT1 as i_SCHED_ADJ_AMT1", \
	"JNR_WM_E_EVNT_SMRY_HDR___i_SCHED_UNITS_QTY1 as i_SCHED_UNITS_QTY1", \
	"JNR_WM_E_EVNT_SMRY_HDR___i_TMU_RECALC_CNT as i_TMU_RECALC_CNT", \
	"JNR_WM_E_EVNT_SMRY_HDR___i_TOTAL_WEIGHT1 as i_TOTAL_WEIGHT1", \
	"JNR_WM_E_EVNT_SMRY_HDR___i_PAID_BRK_OVERLAP1 as i_PAID_BRK_OVERLAP1", \
	"JNR_WM_E_EVNT_SMRY_HDR___i_UNPAID_BRK_OVERLAP1 as i_UNPAID_BRK_OVERLAP1", \
	"JNR_WM_E_EVNT_SMRY_HDR___i_THRUPUT_GOAL1 as i_THRUPUT_GOAL1", \
	"JNR_WM_E_EVNT_SMRY_HDR___i_THRUPUT_MIN1 as i_THRUPUT_MIN1", \
	"JNR_WM_E_EVNT_SMRY_HDR___i_DISPLAY_UOM1 as i_DISPLAY_UOM1", \
	"JNR_WM_E_EVNT_SMRY_HDR___i_DISPLAY_UOM_QTY1 as i_DISPLAY_UOM_QTY1", \
	"JNR_WM_E_EVNT_SMRY_HDR___i_UNIT_MIN1 as i_UNIT_MIN1", \
	"JNR_WM_E_EVNT_SMRY_HDR___i_ERROR_CNT1 as i_ERROR_CNT1", \
	"JNR_WM_E_EVNT_SMRY_HDR___i_USER_DEF_FIELD_11 as i_USER_DEF_FIELD_11", \
	"JNR_WM_E_EVNT_SMRY_HDR___i_USER_DEF_FIELD_21 as i_USER_DEF_FIELD_21", \
	"JNR_WM_E_EVNT_SMRY_HDR___i_MISC1 as i_MISC1", \
	"JNR_WM_E_EVNT_SMRY_HDR___i_MISC_TXT_11 as i_MISC_TXT_11", \
	"JNR_WM_E_EVNT_SMRY_HDR___i_MISC_TXT_21 as i_MISC_TXT_21", \
	"JNR_WM_E_EVNT_SMRY_HDR___i_MISC_NUM_11 as i_MISC_NUM_11", \
	"JNR_WM_E_EVNT_SMRY_HDR___i_MISC_NUM_21 as i_MISC_NUM_21", \
	"JNR_WM_E_EVNT_SMRY_HDR___i_SOURCE1 as i_SOURCE1", \
	"JNR_WM_E_EVNT_SMRY_HDR___i_WM_SYS_UPDATED_FLAG as i_WM_SYS_UPDATED_FLAG", \
	"JNR_WM_E_EVNT_SMRY_HDR___i_LAST_MOD_BY1 as i_LAST_MOD_BY1", \
	"JNR_WM_E_EVNT_SMRY_HDR___i_WM_USER_ID as i_WM_USER_ID", \
	"JNR_WM_E_EVNT_SMRY_HDR___i_WM_VERSION_ID as i_WM_VERSION_ID", \
	"JNR_WM_E_EVNT_SMRY_HDR___i_WM_CREATE_TSTMP as i_WM_CREATE_TSTMP", \
	"JNR_WM_E_EVNT_SMRY_HDR___i_WM_MOD_TSTMP as i_WM_MOD_TSTMP", \
	"JNR_WM_E_EVNT_SMRY_HDR___i_DELETE_FLAG as i_DELETE_FLAG", \
	"JNR_WM_E_EVNT_SMRY_HDR___i_UPDATE_TSTMP as i_UPDATE_TSTMP", \
	"JNR_WM_E_EVNT_SMRY_HDR___i_LOAD_TSTMP as i_LOAD_TSTMP")\
	.filter("ELS_TRAN_ID is Null OR i_WM_ELS_TRAN_ID is Null() OR (  i_WM_ELS_TRAN_ID is NOT Null AND ( COALESCE(CREATE_DATE_TIME, date'1900-01-01') != COALESCE(i_WM_CREATE_TSTMP, date'1900-01-01') \
          OR OR COALESCE(MOD_DATE_TIME, date'1900-01-01') != COALESCE(i_WM_MOD_TSTMP, date'1900-01-01')))").withColumn("sys_row_id", monotonically_increasing_id())


# COMMAND ----------
# Processing node EXP_UPD_VALIDATOR, type EXPRESSION 
# COLUMN COUNT: 167

# for each involved DataFrame, append the dataframe name to each column
FIL_UNCHANGED_RECORDS_temp = FIL_UNCHANGED_RECORDS.toDF(*["FIL_UNCHANGED_RECORDS___" + col for col in FIL_UNCHANGED_RECORDS.columns])\
.withColumn("v_CREATE_DATE_TIME", expr("""IF (CREATE_DATE_TIME IS NULL, TO_DATE ( '01/01/1900' , 'MM/DD/YYYY' ), CREATE_DATE_TIME)""")) \
	.withColumn("v_MOD_DATE_TIME", expr("""IF (MOD_DATE_TIME IS NULL, TO_DATE ( '01/01/1900' , 'MM/DD/YYYY' ), MOD_DATE_TIME)""")) \
	.withColumn("v_i_WM_CREATE_TSTMP", expr("""IF (i_WM_CREATE_TSTMP IS NULL, TO_DATE ( '01/01/1900' , 'MM/DD/YYYY' ), i_WM_CREATE_TSTMP)""")) \
	.withColumn("v_i_WM_MOD_TSTMP", expr("""IF (i_WM_MOD_TSTMP IS NULL, TO_DATE ( '01/01/1900' , 'MM/DD/YYYY' ), i_WM_MOD_TSTMP)"""))
             
EXP_UPD_VALIDATOR = FIL_UNCHANGED_RECORDS_temp.selectExpr( \
	"FIL_UNCHANGED_RECORDS___sys_row_id as sys_row_id", \
	"FIL_UNCHANGED_RECORDS___LOCATION_ID as LOCATION_ID", \
	"FIL_UNCHANGED_RECORDS___ELS_TRAN_ID as ELS_TRAN_ID", \
	"FIL_UNCHANGED_RECORDS___WHSE as WHSE", \
	"FIL_UNCHANGED_RECORDS___TRAN_NBR as TRAN_NBR", \
	"FIL_UNCHANGED_RECORDS___CO as CO", \
	"FIL_UNCHANGED_RECORDS___DIV as DIV", \
	"FIL_UNCHANGED_RECORDS___SCHED_START_DATE as SCHED_START_DATE", \
	"FIL_UNCHANGED_RECORDS___REF_CODE as REF_CODE", \
	"FIL_UNCHANGED_RECORDS___REF_NBR as REF_NBR", \
	"FIL_UNCHANGED_RECORDS___LOGIN_USER_ID as LOGIN_USER_ID", \
	"FIL_UNCHANGED_RECORDS___DEPT_CODE as DEPT_CODE", \
	"FIL_UNCHANGED_RECORDS___VHCL_TYPE as VHCL_TYPE", \
	"FIL_UNCHANGED_RECORDS___SHIFT_CODE as SHIFT_CODE", \
	"FIL_UNCHANGED_RECORDS___USER_DEF_FIELD_1 as USER_DEF_FIELD_1", \
	"FIL_UNCHANGED_RECORDS___USER_DEF_FIELD_2 as USER_DEF_FIELD_2", \
	"FIL_UNCHANGED_RECORDS___STD_TIME_ALLOW as STD_TIME_ALLOW", \
	"FIL_UNCHANGED_RECORDS___EMP_PERF_ALLOW as EMP_PERF_ALLOW", \
	"FIL_UNCHANGED_RECORDS___PERF_ADJ_AMT as PERF_ADJ_AMT", \
	"FIL_UNCHANGED_RECORDS___SCHED_ADJ_AMT as SCHED_ADJ_AMT", \
	"FIL_UNCHANGED_RECORDS___SCHED_UNITS_QTY as SCHED_UNITS_QTY", \
	"FIL_UNCHANGED_RECORDS___ACTL_TIME as ACTL_TIME", \
	"FIL_UNCHANGED_RECORDS___ERROR_CNT as ERROR_CNT", \
	"FIL_UNCHANGED_RECORDS___EVNT_STAT_CODE as EVNT_STAT_CODE", \
	"FIL_UNCHANGED_RECORDS___CREATE_DATE_TIME as CREATE_DATE_TIME", \
	"FIL_UNCHANGED_RECORDS___MOD_DATE_TIME as MOD_DATE_TIME", \
	"FIL_UNCHANGED_RECORDS___USER_ID as USER_ID", \
	"FIL_UNCHANGED_RECORDS___TMU_RECALC_COUNT as TMU_RECALC_COUNT", \
	"FIL_UNCHANGED_RECORDS___MISC as MISC", \
	"FIL_UNCHANGED_RECORDS___LABOR_TYPE_ID as LABOR_TYPE_ID", \
	"FIL_UNCHANGED_RECORDS___SOURCE as SOURCE", \
	"FIL_UNCHANGED_RECORDS___EVENT_TYPE as EVENT_TYPE", \
	"FIL_UNCHANGED_RECORDS___TOTAL_WEIGHT as TOTAL_WEIGHT", \
	"FIL_UNCHANGED_RECORDS___TEAM_STD_SMRY_ID as TEAM_STD_SMRY_ID", \
	"FIL_UNCHANGED_RECORDS___TEAM_CODE as TEAM_CODE", \
	"FIL_UNCHANGED_RECORDS___ORIG_LOGIN_USER_ID as ORIG_LOGIN_USER_ID", \
	"FIL_UNCHANGED_RECORDS___MISC_TXT_1 as MISC_TXT_1", \
	"FIL_UNCHANGED_RECORDS___MISC_TXT_2 as MISC_TXT_2", \
	"FIL_UNCHANGED_RECORDS___MISC_NUM_1 as MISC_NUM_1", \
	"FIL_UNCHANGED_RECORDS___MISC_NUM_2 as MISC_NUM_2", \
	"FIL_UNCHANGED_RECORDS___PROC_ZONE_ID as PROC_ZONE_ID", \
	"FIL_UNCHANGED_RECORDS___LAST_MOD_BY as LAST_MOD_BY", \
	"FIL_UNCHANGED_RECORDS___EVNT_CTGRY_1 as EVNT_CTGRY_1", \
	"FIL_UNCHANGED_RECORDS___EVNT_CTGRY_2 as EVNT_CTGRY_2", \
	"FIL_UNCHANGED_RECORDS___EVNT_CTGRY_3 as EVNT_CTGRY_3", \
	"FIL_UNCHANGED_RECORDS___EVNT_CTGRY_4 as EVNT_CTGRY_4", \
	"FIL_UNCHANGED_RECORDS___EVNT_CTGRY_5 as EVNT_CTGRY_5", \
	"FIL_UNCHANGED_RECORDS___SYS_UPDATED_FLAG as SYS_UPDATED_FLAG", \
	"FIL_UNCHANGED_RECORDS___APRV_SPVSR as APRV_SPVSR", \
	"FIL_UNCHANGED_RECORDS___APRV_SPVSR_DATE_TIME as APRV_SPVSR_DATE_TIME", \
	"FIL_UNCHANGED_RECORDS___VERSION_ID as VERSION_ID", \
	"FIL_UNCHANGED_RECORDS___TEAM_CHG_ID as TEAM_CHG_ID", \
	"FIL_UNCHANGED_RECORDS___ACTUAL_END_DATE as ACTUAL_END_DATE", \
	"FIL_UNCHANGED_RECORDS___SPVSR_LOGIN_USER_ID as SPVSR_LOGIN_USER_ID", \
	"FIL_UNCHANGED_RECORDS___PAID_BRK_OVERLAP as PAID_BRK_OVERLAP", \
	"FIL_UNCHANGED_RECORDS___UNPAID_BRK_OVERLAP as UNPAID_BRK_OVERLAP", \
	"FIL_UNCHANGED_RECORDS___EMP_PERF_SMRY_ID as EMP_PERF_SMRY_ID", \
	"FIL_UNCHANGED_RECORDS___HDR_MSG_ID as HDR_MSG_ID", \
	"FIL_UNCHANGED_RECORDS___ACT_ID as ACT_ID", \
	"FIL_UNCHANGED_RECORDS___PERF_SMRY_TRAN_ID as PERF_SMRY_TRAN_ID", \
	"FIL_UNCHANGED_RECORDS___ORIG_EVNT_START_TIME as ORIG_EVNT_START_TIME", \
	"FIL_UNCHANGED_RECORDS___ORIG_EVNT_END_TIME as ORIG_EVNT_END_TIME", \
	"FIL_UNCHANGED_RECORDS___ADJ_REASON_CODE as ADJ_REASON_CODE", \
	"FIL_UNCHANGED_RECORDS___ADJ_REF_TRAN_NBR as ADJ_REF_TRAN_NBR", \
	"FIL_UNCHANGED_RECORDS___CONFLICT as CONFLICT", \
	"FIL_UNCHANGED_RECORDS___TEAM_BEGIN_TIME as TEAM_BEGIN_TIME", \
	"FIL_UNCHANGED_RECORDS___THRUPUT_GOAL as THRUPUT_GOAL", \
	"FIL_UNCHANGED_RECORDS___THRUPUT_MIN as THRUPUT_MIN", \
	"FIL_UNCHANGED_RECORDS___DISPLAY_UOM as DISPLAY_UOM", \
	"FIL_UNCHANGED_RECORDS___DISPLAY_UOM_QTY as DISPLAY_UOM_QTY", \
	"FIL_UNCHANGED_RECORDS___UNIT_MIN as UNIT_MIN", \
	"FIL_UNCHANGED_RECORDS___CONSOL_EVNT_TIME as CONSOL_EVNT_TIME", \
	"FIL_UNCHANGED_RECORDS___LOCN_GRP_ATTR as LOCN_GRP_ATTR", \
	"FIL_UNCHANGED_RECORDS___RESOURCE_GROUP_ID as RESOURCE_GROUP_ID", \
	"FIL_UNCHANGED_RECORDS___JOB_FUNC_ID as JOB_FUNC_ID", \
	"FIL_UNCHANGED_RECORDS___COMP_EMPLOYEE_DAY_ID as COMP_EMPLOYEE_DAY_ID", \
	"FIL_UNCHANGED_RECORDS___COMP_EVENT_SUMMARY_HEADER_ID as COMP_EVENT_SUMMARY_HEADER_ID", \
	"FIL_UNCHANGED_RECORDS___ASSIGNMENT_START_TIME as ASSIGNMENT_START_TIME", \
	"FIL_UNCHANGED_RECORDS___ASSIGNMENT_END_TIME as ASSIGNMENT_END_TIME", \
	"FIL_UNCHANGED_RECORDS___REFLECTIVE_CODE as REFLECTIVE_CODE", \
	"FIL_UNCHANGED_RECORDS___COMP_ASSIGNMENT_ID as COMP_ASSIGNMENT_ID", \
	"FIL_UNCHANGED_RECORDS___i_LOCATION_ID as i_LOCATION_ID", \
	"FIL_UNCHANGED_RECORDS___i_WM_ELS_TRAN_ID as i_WM_ELS_TRAN_ID", \
	"FIL_UNCHANGED_RECORDS___i_WM_WHSE as i_WM_WHSE", \
	"FIL_UNCHANGED_RECORDS___i_WM_LOGIN_USER_ID as i_WM_LOGIN_USER_ID", \
	"FIL_UNCHANGED_RECORDS___i_WM_SHIFT_CD as i_WM_SHIFT_CD", \
	"FIL_UNCHANGED_RECORDS___i_WM_ORIG_EVNT_START_TSTMP as i_WM_ORIG_EVNT_START_TSTMP", \
	"FIL_UNCHANGED_RECORDS___i_WM_ORIG_EVNT_END_TSTMP as i_WM_ORIG_EVNT_END_TSTMP", \
	"FIL_UNCHANGED_RECORDS___i_WM_SCHED_START_TSTMP as i_WM_SCHED_START_TSTMP", \
	"FIL_UNCHANGED_RECORDS___i_WM_ACTUAL_END_TSTMP as i_WM_ACTUAL_END_TSTMP", \
	"FIL_UNCHANGED_RECORDS___i_WM_EVNT_STAT_CD as i_WM_EVNT_STAT_CD", \
	"FIL_UNCHANGED_RECORDS___i_WM_LABOR_TYPE_ID as i_WM_LABOR_TYPE_ID", \
	"FIL_UNCHANGED_RECORDS___i_WM_JOB_FUNC_ID as i_WM_JOB_FUNC_ID", \
	"FIL_UNCHANGED_RECORDS___i_WM_DEPT_CD as i_WM_DEPT_CD", \
	"FIL_UNCHANGED_RECORDS___i_WM_RESOURCE_GROUP_ID as i_WM_RESOURCE_GROUP_ID", \
	"FIL_UNCHANGED_RECORDS___i_WM_LOCN_GRP_ATTR as i_WM_LOCN_GRP_ATTR", \
	"FIL_UNCHANGED_RECORDS___i_WM_EMP_PERF_SMRY_ID as i_WM_EMP_PERF_SMRY_ID", \
	"FIL_UNCHANGED_RECORDS___i_WM_HDR_MSG_ID as i_WM_HDR_MSG_ID", \
	"FIL_UNCHANGED_RECORDS___i_WM_ACT_ID as i_WM_ACT_ID", \
	"FIL_UNCHANGED_RECORDS___i_WM_PERF_SMRY_TRAN_ID as i_WM_PERF_SMRY_TRAN_ID", \
	"FIL_UNCHANGED_RECORDS___i_WM_SPVSR_LOGIN_USER_ID as i_WM_SPVSR_LOGIN_USER_ID", \
	"FIL_UNCHANGED_RECORDS___i_WM_ORIG_LOGIN_USER_ID as i_WM_ORIG_LOGIN_USER_ID", \
	"FIL_UNCHANGED_RECORDS___i_WM_TRAN_NBR as i_WM_TRAN_NBR", \
	"FIL_UNCHANGED_RECORDS___i_WM_COMP_EMPLOYEE_DAY_ID as i_WM_COMP_EMPLOYEE_DAY_ID", \
	"FIL_UNCHANGED_RECORDS___i_WM_COMP_EVENT_SUMMARY_HEADER_ID as i_WM_COMP_EVENT_SUMMARY_HEADER_ID", \
	"FIL_UNCHANGED_RECORDS___i_ASSIGNMENT_START_TSTMP as i_ASSIGNMENT_START_TSTMP", \
	"FIL_UNCHANGED_RECORDS___i_ASSIGNMENT_END_TSTMP as i_ASSIGNMENT_END_TSTMP", \
	"FIL_UNCHANGED_RECORDS___i_WM_REFLECTIVE_CD as i_WM_REFLECTIVE_CD", \
	"FIL_UNCHANGED_RECORDS___i_WM_COMP_ASSIGNMENT_ID as i_WM_COMP_ASSIGNMENT_ID", \
	"FIL_UNCHANGED_RECORDS___i_WM_ADJ_REASON_CD as i_WM_ADJ_REASON_CD", \
	"FIL_UNCHANGED_RECORDS___i_WM_ADJ_REF_TRAN_NBR as i_WM_ADJ_REF_TRAN_NBR", \
	"FIL_UNCHANGED_RECORDS___i_WM_CO as i_WM_CO", \
	"FIL_UNCHANGED_RECORDS___i_WM_DIV as i_WM_DIV", \
	"FIL_UNCHANGED_RECORDS___i_WM_REF_CD as i_WM_REF_CD", \
	"FIL_UNCHANGED_RECORDS___i_WM_REF_NBR as i_WM_REF_NBR", \
	"FIL_UNCHANGED_RECORDS___i_WM_TEAM_STD_SMRY_ID as i_WM_TEAM_STD_SMRY_ID", \
	"FIL_UNCHANGED_RECORDS___i_WM_TEAM_CD as i_WM_TEAM_CD", \
	"FIL_UNCHANGED_RECORDS___i_TEAM_BEGIN_TSTMP as i_TEAM_BEGIN_TSTMP", \
	"FIL_UNCHANGED_RECORDS___i_WM_PROC_ZONE_ID as i_WM_PROC_ZONE_ID", \
	"FIL_UNCHANGED_RECORDS___i_WM_EVENT_TYPE as i_WM_EVENT_TYPE", \
	"FIL_UNCHANGED_RECORDS___i_WM_EVNT_CTGRY_1 as i_WM_EVNT_CTGRY_1", \
	"FIL_UNCHANGED_RECORDS___i_WM_EVNT_CTGRY_2 as i_WM_EVNT_CTGRY_2", \
	"FIL_UNCHANGED_RECORDS___i_WM_EVNT_CTGRY_3 as i_WM_EVNT_CTGRY_3", \
	"FIL_UNCHANGED_RECORDS___i_WM_EVNT_CTGRY_4 as i_WM_EVNT_CTGRY_4", \
	"FIL_UNCHANGED_RECORDS___i_WM_EVNT_CTGRY_5 as i_WM_EVNT_CTGRY_5", \
	"FIL_UNCHANGED_RECORDS___i_CONFLICT1 as i_CONFLICT1", \
	"FIL_UNCHANGED_RECORDS___i_WM_APRV_SPVSR as i_WM_APRV_SPVSR", \
	"FIL_UNCHANGED_RECORDS___i_WM_APRV_SPVSR_TSTMP as i_WM_APRV_SPVSR_TSTMP", \
	"FIL_UNCHANGED_RECORDS___i_WM_TEAM_CHG_ID as i_WM_TEAM_CHG_ID", \
	"FIL_UNCHANGED_RECORDS___i_VHCL_TYPE1 as i_VHCL_TYPE1", \
	"FIL_UNCHANGED_RECORDS___i_CONSOL_EVNT_TIME1 as i_CONSOL_EVNT_TIME1", \
	"FIL_UNCHANGED_RECORDS___i_ACTL_TIME1 as i_ACTL_TIME1", \
	"FIL_UNCHANGED_RECORDS___i_STD_TIME_ALLOW1 as i_STD_TIME_ALLOW1", \
	"FIL_UNCHANGED_RECORDS___i_EMP_PERF_ALLOW1 as i_EMP_PERF_ALLOW1", \
	"FIL_UNCHANGED_RECORDS___i_PERF_ADJ_AMT1 as i_PERF_ADJ_AMT1", \
	"FIL_UNCHANGED_RECORDS___i_SCHED_ADJ_AMT1 as i_SCHED_ADJ_AMT1", \
	"FIL_UNCHANGED_RECORDS___i_SCHED_UNITS_QTY1 as i_SCHED_UNITS_QTY1", \
	"FIL_UNCHANGED_RECORDS___i_TMU_RECALC_CNT as i_TMU_RECALC_CNT", \
	"FIL_UNCHANGED_RECORDS___i_TOTAL_WEIGHT1 as i_TOTAL_WEIGHT1", \
	"FIL_UNCHANGED_RECORDS___i_PAID_BRK_OVERLAP1 as i_PAID_BRK_OVERLAP1", \
	"FIL_UNCHANGED_RECORDS___i_UNPAID_BRK_OVERLAP1 as i_UNPAID_BRK_OVERLAP1", \
	"FIL_UNCHANGED_RECORDS___i_THRUPUT_GOAL1 as i_THRUPUT_GOAL1", \
	"FIL_UNCHANGED_RECORDS___i_THRUPUT_MIN1 as i_THRUPUT_MIN1", \
	"FIL_UNCHANGED_RECORDS___i_DISPLAY_UOM1 as i_DISPLAY_UOM1", \
	"FIL_UNCHANGED_RECORDS___i_DISPLAY_UOM_QTY1 as i_DISPLAY_UOM_QTY1", \
	"FIL_UNCHANGED_RECORDS___i_UNIT_MIN1 as i_UNIT_MIN1", \
	"FIL_UNCHANGED_RECORDS___i_ERROR_CNT1 as i_ERROR_CNT1", \
	"FIL_UNCHANGED_RECORDS___i_USER_DEF_FIELD_11 as i_USER_DEF_FIELD_11", \
	"FIL_UNCHANGED_RECORDS___i_USER_DEF_FIELD_21 as i_USER_DEF_FIELD_21", \
	"FIL_UNCHANGED_RECORDS___i_MISC1 as i_MISC1", \
	"FIL_UNCHANGED_RECORDS___i_MISC_TXT_11 as i_MISC_TXT_11", \
	"FIL_UNCHANGED_RECORDS___i_MISC_TXT_21 as i_MISC_TXT_21", \
	"FIL_UNCHANGED_RECORDS___i_MISC_NUM_11 as i_MISC_NUM_11", \
	"FIL_UNCHANGED_RECORDS___i_MISC_NUM_21 as i_MISC_NUM_21", \
	"FIL_UNCHANGED_RECORDS___i_SOURCE1 as i_SOURCE1", \
	"FIL_UNCHANGED_RECORDS___i_WM_SYS_UPDATED_FLAG as i_WM_SYS_UPDATED_FLAG", \
	"FIL_UNCHANGED_RECORDS___i_LAST_MOD_BY1 as i_LAST_MOD_BY1", \
	"FIL_UNCHANGED_RECORDS___i_WM_USER_ID as i_WM_USER_ID", \
	"FIL_UNCHANGED_RECORDS___i_WM_VERSION_ID as i_WM_VERSION_ID", \
	"FIL_UNCHANGED_RECORDS___i_WM_CREATE_TSTMP as i_WM_CREATE_TSTMP", \
	"FIL_UNCHANGED_RECORDS___i_WM_MOD_TSTMP as i_WM_MOD_TSTMP", \
	"FIL_UNCHANGED_RECORDS___i_DELETE_FLAG as i_DELETE_FLAG", \
	"FIL_UNCHANGED_RECORDS___i_UPDATE_TSTMP as i_UPDATE_TSTMP", \
	"FIL_UNCHANGED_RECORDS___i_LOAD_TSTMP as i_LOAD_TSTMP", \
	"IF (FIL_UNCHANGED_RECORDS___ELS_TRAN_ID IS NULL AND FIL_UNCHANGED_RECORDS___i_WM_ELS_TRAN_ID IS NOT NULL, 1, 0) as DELETE_FLAG", \
	"IF (FIL_UNCHANGED_RECORDS___i_LOAD_TSTMP IS NULL, CURRENT_TIMESTAMP, FIL_UNCHANGED_RECORDS___i_LOAD_TSTMP) as LOAD_TSTMP", \
	"CURRENT_TIMESTAMP as UPDATE_TSTMP", \
	"IF (FIL_UNCHANGED_RECORDS___ELS_TRAN_ID IS NOT NULL AND FIL_UNCHANGED_RECORDS___i_WM_ELS_TRAN_ID IS NULL, 'INSERT', IF (FIL_UNCHANGED_RECORDS___ELS_TRAN_ID IS NOT NULL AND FIL_UNCHANGED_RECORDS___i_WM_ELS_TRAN_ID IS NOT NULL AND ( FIL_UNCHANGED_RECORDS___v_i_WM_CREATE_TSTMP <> FIL_UNCHANGED_RECORDS___v_CREATE_DATE_TIME OR FIL_UNCHANGED_RECORDS___v_i_WM_MOD_TSTMP <> FIL_UNCHANGED_RECORDS___v_MOD_DATE_TIME ), 'UPDATE', NULL)) as o_UPDATE_VALIDATOR" \
)

# COMMAND ----------
# Processing node UPD_INS_UPD_DEL, type UPDATE_STRATEGY . Note: using additional SELECT to rename incoming columns
# COLUMN COUNT: 84

# for each involved DataFrame, append the dataframe name to each column
EXP_UPD_VALIDATOR_temp = EXP_UPD_VALIDATOR.toDF(*["EXP_UPD_VALIDATOR___" + col for col in EXP_UPD_VALIDATOR.columns])

UPD_INS_UPD_DEL = EXP_UPD_VALIDATOR_temp.selectExpr( \
	"EXP_UPD_VALIDATOR___LOCATION_ID as LOCATION_ID1", \
	"EXP_UPD_VALIDATOR___ELS_TRAN_ID as ELS_TRAN_ID1", \
	"EXP_UPD_VALIDATOR___WHSE as WHSE1", \
	"EXP_UPD_VALIDATOR___TRAN_NBR as TRAN_NBR1", \
	"EXP_UPD_VALIDATOR___CO as CO1", \
	"EXP_UPD_VALIDATOR___DIV as DIV1", \
	"EXP_UPD_VALIDATOR___SCHED_START_DATE as SCHED_START_DATE1", \
	"EXP_UPD_VALIDATOR___REF_CODE as REF_CODE1", \
	"EXP_UPD_VALIDATOR___REF_NBR as REF_NBR1", \
	"EXP_UPD_VALIDATOR___LOGIN_USER_ID as LOGIN_USER_ID1", \
	"EXP_UPD_VALIDATOR___DEPT_CODE as DEPT_CODE1", \
	"EXP_UPD_VALIDATOR___VHCL_TYPE as VHCL_TYPE1", \
	"EXP_UPD_VALIDATOR___SHIFT_CODE as SHIFT_CODE1", \
	"EXP_UPD_VALIDATOR___USER_DEF_FIELD_1 as USER_DEF_FIELD_11", \
	"EXP_UPD_VALIDATOR___USER_DEF_FIELD_2 as USER_DEF_FIELD_21", \
	"EXP_UPD_VALIDATOR___STD_TIME_ALLOW as STD_TIME_ALLOW1", \
	"EXP_UPD_VALIDATOR___EMP_PERF_ALLOW as EMP_PERF_ALLOW1", \
	"EXP_UPD_VALIDATOR___PERF_ADJ_AMT as PERF_ADJ_AMT1", \
	"EXP_UPD_VALIDATOR___SCHED_ADJ_AMT as SCHED_ADJ_AMT1", \
	"EXP_UPD_VALIDATOR___SCHED_UNITS_QTY as SCHED_UNITS_QTY1", \
	"EXP_UPD_VALIDATOR___ACTL_TIME as ACTL_TIME1", \
	"EXP_UPD_VALIDATOR___ERROR_CNT as ERROR_CNT1", \
	"EXP_UPD_VALIDATOR___EVNT_STAT_CODE as EVNT_STAT_CODE1", \
	"EXP_UPD_VALIDATOR___CREATE_DATE_TIME as CREATE_DATE_TIME1", \
	"EXP_UPD_VALIDATOR___MOD_DATE_TIME as MOD_DATE_TIME1", \
	"EXP_UPD_VALIDATOR___USER_ID as USER_ID1", \
	"EXP_UPD_VALIDATOR___TMU_RECALC_COUNT as TMU_RECALC_COUNT1", \
	"EXP_UPD_VALIDATOR___MISC as MISC1", \
	"EXP_UPD_VALIDATOR___LABOR_TYPE_ID as LABOR_TYPE_ID1", \
	"EXP_UPD_VALIDATOR___SOURCE as SOURCE1", \
	"EXP_UPD_VALIDATOR___EVENT_TYPE as EVENT_TYPE1", \
	"EXP_UPD_VALIDATOR___TOTAL_WEIGHT as TOTAL_WEIGHT1", \
	"EXP_UPD_VALIDATOR___TEAM_STD_SMRY_ID as TEAM_STD_SMRY_ID1", \
	"EXP_UPD_VALIDATOR___TEAM_CODE as TEAM_CODE1", \
	"EXP_UPD_VALIDATOR___ORIG_LOGIN_USER_ID as ORIG_LOGIN_USER_ID1", \
	"EXP_UPD_VALIDATOR___MISC_TXT_1 as MISC_TXT_11", \
	"EXP_UPD_VALIDATOR___MISC_TXT_2 as MISC_TXT_21", \
	"EXP_UPD_VALIDATOR___MISC_NUM_1 as MISC_NUM_11", \
	"EXP_UPD_VALIDATOR___MISC_NUM_2 as MISC_NUM_21", \
	"EXP_UPD_VALIDATOR___PROC_ZONE_ID as PROC_ZONE_ID1", \
	"EXP_UPD_VALIDATOR___LAST_MOD_BY as LAST_MOD_BY1", \
	"EXP_UPD_VALIDATOR___EVNT_CTGRY_1 as EVNT_CTGRY_11", \
	"EXP_UPD_VALIDATOR___EVNT_CTGRY_2 as EVNT_CTGRY_21", \
	"EXP_UPD_VALIDATOR___EVNT_CTGRY_3 as EVNT_CTGRY_31", \
	"EXP_UPD_VALIDATOR___EVNT_CTGRY_4 as EVNT_CTGRY_41", \
	"EXP_UPD_VALIDATOR___EVNT_CTGRY_5 as EVNT_CTGRY_51", \
	"EXP_UPD_VALIDATOR___SYS_UPDATED_FLAG as SYS_UPDATED_FLAG1", \
	"EXP_UPD_VALIDATOR___APRV_SPVSR as APRV_SPVSR1", \
	"EXP_UPD_VALIDATOR___APRV_SPVSR_DATE_TIME as APRV_SPVSR_DATE_TIME1", \
	"EXP_UPD_VALIDATOR___VERSION_ID as VERSION_ID1", \
	"EXP_UPD_VALIDATOR___TEAM_CHG_ID as TEAM_CHG_ID1", \
	"EXP_UPD_VALIDATOR___ACTUAL_END_DATE as ACTUAL_END_DATE1", \
	"EXP_UPD_VALIDATOR___SPVSR_LOGIN_USER_ID as SPVSR_LOGIN_USER_ID1", \
	"EXP_UPD_VALIDATOR___PAID_BRK_OVERLAP as PAID_BRK_OVERLAP1", \
	"EXP_UPD_VALIDATOR___UNPAID_BRK_OVERLAP as UNPAID_BRK_OVERLAP1", \
	"EXP_UPD_VALIDATOR___EMP_PERF_SMRY_ID as EMP_PERF_SMRY_ID1", \
	"EXP_UPD_VALIDATOR___HDR_MSG_ID as HDR_MSG_ID1", \
	"EXP_UPD_VALIDATOR___ACT_ID as ACT_ID1", \
	"EXP_UPD_VALIDATOR___PERF_SMRY_TRAN_ID as PERF_SMRY_TRAN_ID1", \
	"EXP_UPD_VALIDATOR___ORIG_EVNT_START_TIME as ORIG_EVNT_START_TIME1", \
	"EXP_UPD_VALIDATOR___ORIG_EVNT_END_TIME as ORIG_EVNT_END_TIME1", \
	"EXP_UPD_VALIDATOR___ADJ_REASON_CODE as ADJ_REASON_CODE1", \
	"EXP_UPD_VALIDATOR___ADJ_REF_TRAN_NBR as ADJ_REF_TRAN_NBR1", \
	"EXP_UPD_VALIDATOR___CONFLICT as CONFLICT1", \
	"EXP_UPD_VALIDATOR___TEAM_BEGIN_TIME as TEAM_BEGIN_TIME1", \
	"EXP_UPD_VALIDATOR___THRUPUT_GOAL as THRUPUT_GOAL1", \
	"EXP_UPD_VALIDATOR___THRUPUT_MIN as THRUPUT_MIN1", \
	"EXP_UPD_VALIDATOR___DISPLAY_UOM as DISPLAY_UOM1", \
	"EXP_UPD_VALIDATOR___DISPLAY_UOM_QTY as DISPLAY_UOM_QTY1", \
	"EXP_UPD_VALIDATOR___UNIT_MIN as UNIT_MIN1", \
	"EXP_UPD_VALIDATOR___CONSOL_EVNT_TIME as CONSOL_EVNT_TIME1", \
	"EXP_UPD_VALIDATOR___LOCN_GRP_ATTR as LOCN_GRP_ATTR1", \
	"EXP_UPD_VALIDATOR___RESOURCE_GROUP_ID as RESOURCE_GROUP_ID1", \
	"EXP_UPD_VALIDATOR___JOB_FUNC_ID as JOB_FUNC_ID1", \
	"EXP_UPD_VALIDATOR___COMP_EMPLOYEE_DAY_ID as COMP_EMPLOYEE_DAY_ID1", \
	"EXP_UPD_VALIDATOR___COMP_EVENT_SUMMARY_HEADER_ID as COMP_EVENT_SUMMARY_HEADER_ID1", \
	"EXP_UPD_VALIDATOR___ASSIGNMENT_START_TIME as ASSIGNMENT_START_TIME1", \
	"EXP_UPD_VALIDATOR___ASSIGNMENT_END_TIME as ASSIGNMENT_END_TIME1", \
	"EXP_UPD_VALIDATOR___REFLECTIVE_CODE as REFLECTIVE_CODE1", \
	"EXP_UPD_VALIDATOR___COMP_ASSIGNMENT_ID as COMP_ASSIGNMENT_ID1", \
	"EXP_UPD_VALIDATOR___DELETE_FLAG as DELETE_FLAG1", \
	"EXP_UPD_VALIDATOR___LOAD_TSTMP as LOAD_TSTMP1", \
	"EXP_UPD_VALIDATOR___UPDATE_TSTMP as UPDATE_TSTMP1", \
	"EXP_UPD_VALIDATOR___o_UPDATE_VALIDATOR as o_UPDATE_VALIDATOR1") \
	.withColumn('pyspark_data_action', when(EXP_UPD_VALIDATOR.o_UPDATE_VALIDATOR ==(lit('INSERT')) , lit(0)).when(EXP_UPD_VALIDATOR.o_UPDATE_VALIDATOR ==(lit('UPDATE')) , lit(1)))

# COMMAND ----------
# Processing node Shortcut_to_WM_E_EVNT_SMRY_HDR11, type TARGET 
# COLUMN COUNT: 83

try:
  primary_key = """source.LOCATION_ID = target.LOCATION_ID AND source.WM_ELS_TRAN_ID = target.WM_ELS_TRAN_ID"""
#   refined_perf_table = "WM_E_EVNT_SMRY_HDR"
  executeMerge(UPD_INS_UPD_DEL, refined_perf_table, primary_key)
  logger.info(f"Merge with {refined_perf_table} completed]")
  logPrevRunDt("WM_E_EVNT_SMRY_HDR", "WM_E_EVNT_SMRY_HDR", "Completed", "N/A", f"{raw}.log_run_details")
except Exception as e:
  logPrevRunDt("WM_E_EVNT_SMRY_HDR", "WM_E_EVNT_SMRY_HDR","Failed",str(e), f"{raw}.log_run_details", )
  raise e
	