#Code converted on 2023-06-26 10:19:09
import os
import argparse
from pyspark.sql import *
from pyspark.sql.functions import *
from pyspark.sql.window import Window
from pyspark.sql.types import *
from datetime import datetime
from pyspark.dbutils import DBUtils
from utils.genericUtilities import *
from utils.configs import *
from utils.mergeUtils import *
from utils.logger import *
# COMMAND ----------

parser = argparse.ArgumentParser()
spark = SparkSession.getActiveSession()
dbutils = DBUtils(spark)
parser.add_argument('env', type=str, help='Env Variable')
args = parser.parse_args()
env = args.env

if env is None or env == '':
    raise ValueError('env is not set')

refine = getEnvPrefix(env) + 'refine'
raw = getEnvPrefix(env) + 'raw'
legacy = getEnvPrefix(env) + 'legacy'

# Set global variables
starttime = datetime.now() #start timestamp of the script

# COMMAND ----------
# Processing node SQ_Shortcut_to_WM_LABOR_MSG_DTL_PRE, type SOURCE 
# COLUMN COUNT: 69

SQ_Shortcut_to_WM_LABOR_MSG_DTL_PRE = spark.sql(f"""SELECT
WM_LABOR_MSG_DTL_PRE.DC_NBR,
WM_LABOR_MSG_DTL_PRE.LABOR_MSG_DTL_ID,
WM_LABOR_MSG_DTL_PRE.LABOR_MSG_ID,
WM_LABOR_MSG_DTL_PRE.TRAN_NBR,
WM_LABOR_MSG_DTL_PRE.TRAN_SEQ_NBR,
WM_LABOR_MSG_DTL_PRE.MSG_STAT_CODE,
WM_LABOR_MSG_DTL_PRE.SEQ_NBR,
WM_LABOR_MSG_DTL_PRE.HNDL_ATTR,
WM_LABOR_MSG_DTL_PRE.QTY_PER_GRAB,
WM_LABOR_MSG_DTL_PRE.LOCN_CLASS,
WM_LABOR_MSG_DTL_PRE.QTY,
WM_LABOR_MSG_DTL_PRE.TC_ILPN_ID,
WM_LABOR_MSG_DTL_PRE.TC_OLPN_ID,
WM_LABOR_MSG_DTL_PRE.PALLET_ID,
WM_LABOR_MSG_DTL_PRE.LOCN_SLOT_TYPE,
WM_LABOR_MSG_DTL_PRE.LOCN_X_COORD,
WM_LABOR_MSG_DTL_PRE.LOCN_Y_COORD,
WM_LABOR_MSG_DTL_PRE.LOCN_Z_COORD,
WM_LABOR_MSG_DTL_PRE.LOCN_TRAV_AISLE,
WM_LABOR_MSG_DTL_PRE.LOCN_TRAV_ZONE,
WM_LABOR_MSG_DTL_PRE.BOX_QTY,
WM_LABOR_MSG_DTL_PRE.INNERPACK_QTY,
WM_LABOR_MSG_DTL_PRE.PACK_QTY,
WM_LABOR_MSG_DTL_PRE.CASE_QTY,
WM_LABOR_MSG_DTL_PRE.TIER_QTY,
WM_LABOR_MSG_DTL_PRE.PALLET_QTY,
WM_LABOR_MSG_DTL_PRE.MISC,
WM_LABOR_MSG_DTL_PRE.CO,
WM_LABOR_MSG_DTL_PRE.DIV,
WM_LABOR_MSG_DTL_PRE.DSP_LOCN,
WM_LABOR_MSG_DTL_PRE.ITEM_BAR_CODE,
WM_LABOR_MSG_DTL_PRE.WEIGHT,
WM_LABOR_MSG_DTL_PRE.VOLUME,
WM_LABOR_MSG_DTL_PRE.CRIT_DIM1,
WM_LABOR_MSG_DTL_PRE.CRIT_DIM2,
WM_LABOR_MSG_DTL_PRE.CRIT_DIM3,
WM_LABOR_MSG_DTL_PRE.START_DATE_TIME,
WM_LABOR_MSG_DTL_PRE.HANDLING_UOM,
WM_LABOR_MSG_DTL_PRE.SEASON,
WM_LABOR_MSG_DTL_PRE.SEASON_YR,
WM_LABOR_MSG_DTL_PRE.STYLE,
WM_LABOR_MSG_DTL_PRE.STYLE_SFX,
WM_LABOR_MSG_DTL_PRE.COLOR,
WM_LABOR_MSG_DTL_PRE.COLOR_SFX,
WM_LABOR_MSG_DTL_PRE.SEC_DIM,
WM_LABOR_MSG_DTL_PRE.QUAL,
WM_LABOR_MSG_DTL_PRE.SIZE_RNGE_CODE,
WM_LABOR_MSG_DTL_PRE.SIZE_REL_POSN_IN_TABLE,
WM_LABOR_MSG_DTL_PRE.MISC_NUM_1,
WM_LABOR_MSG_DTL_PRE.MISC_NUM_2,
WM_LABOR_MSG_DTL_PRE.MISC_2,
WM_LABOR_MSG_DTL_PRE.LOADED,
WM_LABOR_MSG_DTL_PRE.PUTAWAY_ZONE,
WM_LABOR_MSG_DTL_PRE.PICK_DETERMINATION_ZONE,
WM_LABOR_MSG_DTL_PRE.WORK_GROUP,
WM_LABOR_MSG_DTL_PRE.WORK_AREA,
WM_LABOR_MSG_DTL_PRE.PULL_ZONE,
WM_LABOR_MSG_DTL_PRE.ASSIGNMENT_ZONE,
WM_LABOR_MSG_DTL_PRE.CREATED_SOURCE_TYPE,
WM_LABOR_MSG_DTL_PRE.CREATED_SOURCE,
WM_LABOR_MSG_DTL_PRE.CREATED_DTTM,
WM_LABOR_MSG_DTL_PRE.LAST_UPDATED_SOURCE_TYPE,
WM_LABOR_MSG_DTL_PRE.LAST_UPDATED_SOURCE,
WM_LABOR_MSG_DTL_PRE.LAST_UPDATED_DTTM,
WM_LABOR_MSG_DTL_PRE.HIBERNATE_VERSION,
WM_LABOR_MSG_DTL_PRE.ITEM_NAME,
WM_LABOR_MSG_DTL_PRE.LOCN_GRP_ATTR,
WM_LABOR_MSG_DTL_PRE.RESOURCE_GROUP_ID,
WM_LABOR_MSG_DTL_PRE.LOAD_TSTMP
FROM WM_LABOR_MSG_DTL_PRE""").withColumn("sys_row_id", monotonically_increasing_id())

# COMMAND ----------
# Processing node SQ_Shortcut_to_WM_LABOR_MSG_DTL, type SOURCE 
# COLUMN COUNT: 70

SQ_Shortcut_to_WM_LABOR_MSG_DTL = spark.sql(f"""SELECT
WM_LABOR_MSG_DTL.LOCATION_ID,
WM_LABOR_MSG_DTL.WM_LABOR_MSG_DTL_ID,
WM_LABOR_MSG_DTL.WM_LABOR_MSG_ID,
WM_LABOR_MSG_DTL.WM_TRAN_NBR,
WM_LABOR_MSG_DTL.WM_TRAN_SEQ_NBR,
WM_LABOR_MSG_DTL.WM_MSG_STAT_CD,
WM_LABOR_MSG_DTL.SEQ_NBR,
WM_LABOR_MSG_DTL.WM_COMPANY,
WM_LABOR_MSG_DTL.WM_DIVISION,
WM_LABOR_MSG_DTL.WM_START_TSTMP,
WM_LABOR_MSG_DTL.WM_TC_ILPN_ID,
WM_LABOR_MSG_DTL.WM_TC_OLPN_ID,
WM_LABOR_MSG_DTL.WM_PUTAWAY_ZONE,
WM_LABOR_MSG_DTL.WM_PICK_DETERMINATION_ZONE,
WM_LABOR_MSG_DTL.WM_WORK_GROUP,
WM_LABOR_MSG_DTL.WM_WORK_AREA,
WM_LABOR_MSG_DTL.WM_PULL_ZONE,
WM_LABOR_MSG_DTL.WM_ASSIGNMENT_ZONE,
WM_LABOR_MSG_DTL.WM_RESOURCE_GROUP_ID,
WM_LABOR_MSG_DTL.LOADED_FLAG,
WM_LABOR_MSG_DTL.WM_ITEM_BAR_CD,
WM_LABOR_MSG_DTL.WM_ITEM_NAME,
WM_LABOR_MSG_DTL.SEC_DIM,
WM_LABOR_MSG_DTL.WEIGHT,
WM_LABOR_MSG_DTL.VOLUME,
WM_LABOR_MSG_DTL.SEASON,
WM_LABOR_MSG_DTL.SEASON_YR,
WM_LABOR_MSG_DTL.STYLE,
WM_LABOR_MSG_DTL.STYLE_SFX,
WM_LABOR_MSG_DTL.COLOR,
WM_LABOR_MSG_DTL.COLOR_SFX,
WM_LABOR_MSG_DTL.WM_PALLET_ID,
WM_LABOR_MSG_DTL.WM_SIZE_RANGE_CD,
WM_LABOR_MSG_DTL.SIZE_REL_POSN_IN_TABLE,
WM_LABOR_MSG_DTL.WM_LOCN_SLOT_TYPE,
WM_LABOR_MSG_DTL.WM_LOCN_CLASS,
WM_LABOR_MSG_DTL.WM_LOCN_GRP_ATTR,
WM_LABOR_MSG_DTL.DSP_LOCN,
WM_LABOR_MSG_DTL.LOCN_X_COORD,
WM_LABOR_MSG_DTL.LOCN_Y_COORD,
WM_LABOR_MSG_DTL.LOCN_Z_COORD,
WM_LABOR_MSG_DTL.LOCN_TRAV_AISLE,
WM_LABOR_MSG_DTL.LOCN_TRAV_ZONE,
WM_LABOR_MSG_DTL.WM_HANDLING_ATTR,
WM_LABOR_MSG_DTL.WM_HANDLING_UOM,
WM_LABOR_MSG_DTL.QUAL,
WM_LABOR_MSG_DTL.QTY_PER_GRAB,
WM_LABOR_MSG_DTL.QTY,
WM_LABOR_MSG_DTL.BOX_QTY,
WM_LABOR_MSG_DTL.INNERPACK_QTY,
WM_LABOR_MSG_DTL.PACK_QTY,
WM_LABOR_MSG_DTL.CASE_QTY,
WM_LABOR_MSG_DTL.TIER_QTY,
WM_LABOR_MSG_DTL.PALLET_QTY,
WM_LABOR_MSG_DTL.CRIT_DIM1,
WM_LABOR_MSG_DTL.CRIT_DIM2,
WM_LABOR_MSG_DTL.CRIT_DIM3,
WM_LABOR_MSG_DTL.MISC,
WM_LABOR_MSG_DTL.MISC_2,
WM_LABOR_MSG_DTL.MISC_NUM_1,
WM_LABOR_MSG_DTL.MISC_NUM_2,
WM_LABOR_MSG_DTL.WM_HIBERNATE_VERSION,
WM_LABOR_MSG_DTL.WM_CREATED_SOURCE_TYPE,
WM_LABOR_MSG_DTL.WM_CREATED_SOURCE,
WM_LABOR_MSG_DTL.WM_CREATED_TSTMP,
WM_LABOR_MSG_DTL.WM_LAST_UPDATED_SOURCE_TYPE,
WM_LABOR_MSG_DTL.WM_LAST_UPDATED_SOURCE,
WM_LABOR_MSG_DTL.WM_LAST_UPDATED_TSTMP,
WM_LABOR_MSG_DTL.UPDATE_TSTMP,
WM_LABOR_MSG_DTL.LOAD_TSTMP
FROM WM_LABOR_MSG_DTL
WHERE WM_LABOR_MSG_DTL_ID IN (SELECT LABOR_MSG_DTL_ID  FROM WM_LABOR_MSG_DTL_PRE)""").withColumn("sys_row_id", monotonically_increasing_id())

# COMMAND ----------
# Processing node EXP_INT_CONV, type EXPRESSION 
# COLUMN COUNT: 69

# for each involved DataFrame, append the dataframe name to each column
SQ_Shortcut_to_WM_LABOR_MSG_DTL_PRE_temp = SQ_Shortcut_to_WM_LABOR_MSG_DTL_PRE.toDF(*["SQ_Shortcut_to_WM_LABOR_MSG_DTL_PRE___" + col for col in SQ_Shortcut_to_WM_LABOR_MSG_DTL_PRE.columns])

EXP_INT_CONV = SQ_Shortcut_to_WM_LABOR_MSG_DTL_PRE_temp.selectExpr( \
	"SQ_Shortcut_to_WM_LABOR_MSG_DTL_PRE___sys_row_id as sys_row_id", \
	"cast(SQ_Shortcut_to_WM_LABOR_MSG_DTL_PRE___DC_NBR as int) as o_DC_NBR", \
	"SQ_Shortcut_to_WM_LABOR_MSG_DTL_PRE___LABOR_MSG_DTL_ID as LABOR_MSG_DTL_ID", \
	"SQ_Shortcut_to_WM_LABOR_MSG_DTL_PRE___LABOR_MSG_ID as LABOR_MSG_ID", \
	"SQ_Shortcut_to_WM_LABOR_MSG_DTL_PRE___TRAN_NBR as TRAN_NBR", \
	"SQ_Shortcut_to_WM_LABOR_MSG_DTL_PRE___TRAN_SEQ_NBR as TRAN_SEQ_NBR", \
	"SQ_Shortcut_to_WM_LABOR_MSG_DTL_PRE___MSG_STAT_CODE as MSG_STAT_CODE", \
	"SQ_Shortcut_to_WM_LABOR_MSG_DTL_PRE___SEQ_NBR as SEQ_NBR", \
	"SQ_Shortcut_to_WM_LABOR_MSG_DTL_PRE___HNDL_ATTR as HNDL_ATTR", \
	"SQ_Shortcut_to_WM_LABOR_MSG_DTL_PRE___QTY_PER_GRAB as QTY_PER_GRAB", \
	"SQ_Shortcut_to_WM_LABOR_MSG_DTL_PRE___LOCN_CLASS as LOCN_CLASS", \
	"SQ_Shortcut_to_WM_LABOR_MSG_DTL_PRE___QTY as QTY", \
	"SQ_Shortcut_to_WM_LABOR_MSG_DTL_PRE___TC_ILPN_ID as TC_ILPN_ID", \
	"SQ_Shortcut_to_WM_LABOR_MSG_DTL_PRE___TC_OLPN_ID as TC_OLPN_ID", \
	"SQ_Shortcut_to_WM_LABOR_MSG_DTL_PRE___PALLET_ID as PALLET_ID", \
	"SQ_Shortcut_to_WM_LABOR_MSG_DTL_PRE___LOCN_SLOT_TYPE as LOCN_SLOT_TYPE", \
	"SQ_Shortcut_to_WM_LABOR_MSG_DTL_PRE___LOCN_X_COORD as LOCN_X_COORD", \
	"SQ_Shortcut_to_WM_LABOR_MSG_DTL_PRE___LOCN_Y_COORD as LOCN_Y_COORD", \
	"SQ_Shortcut_to_WM_LABOR_MSG_DTL_PRE___LOCN_Z_COORD as LOCN_Z_COORD", \
	"SQ_Shortcut_to_WM_LABOR_MSG_DTL_PRE___LOCN_TRAV_AISLE as LOCN_TRAV_AISLE", \
	"SQ_Shortcut_to_WM_LABOR_MSG_DTL_PRE___LOCN_TRAV_ZONE as LOCN_TRAV_ZONE", \
	"SQ_Shortcut_to_WM_LABOR_MSG_DTL_PRE___BOX_QTY as BOX_QTY", \
	"SQ_Shortcut_to_WM_LABOR_MSG_DTL_PRE___INNERPACK_QTY as INNERPACK_QTY", \
	"SQ_Shortcut_to_WM_LABOR_MSG_DTL_PRE___PACK_QTY as PACK_QTY", \
	"SQ_Shortcut_to_WM_LABOR_MSG_DTL_PRE___CASE_QTY as CASE_QTY", \
	"SQ_Shortcut_to_WM_LABOR_MSG_DTL_PRE___TIER_QTY as TIER_QTY", \
	"SQ_Shortcut_to_WM_LABOR_MSG_DTL_PRE___PALLET_QTY as PALLET_QTY", \
	"SQ_Shortcut_to_WM_LABOR_MSG_DTL_PRE___MISC as MISC", \
	"SQ_Shortcut_to_WM_LABOR_MSG_DTL_PRE___CO as CO", \
	"SQ_Shortcut_to_WM_LABOR_MSG_DTL_PRE___DIV as DIV", \
	"SQ_Shortcut_to_WM_LABOR_MSG_DTL_PRE___DSP_LOCN as DSP_LOCN", \
	"SQ_Shortcut_to_WM_LABOR_MSG_DTL_PRE___ITEM_BAR_CODE as ITEM_BAR_CODE", \
	"SQ_Shortcut_to_WM_LABOR_MSG_DTL_PRE___WEIGHT as WEIGHT", \
	"SQ_Shortcut_to_WM_LABOR_MSG_DTL_PRE___VOLUME as VOLUME", \
	"SQ_Shortcut_to_WM_LABOR_MSG_DTL_PRE___CRIT_DIM1 as CRIT_DIM1", \
	"SQ_Shortcut_to_WM_LABOR_MSG_DTL_PRE___CRIT_DIM2 as CRIT_DIM2", \
	"SQ_Shortcut_to_WM_LABOR_MSG_DTL_PRE___CRIT_DIM3 as CRIT_DIM3", \
	"SQ_Shortcut_to_WM_LABOR_MSG_DTL_PRE___START_DATE_TIME as START_DATE_TIME", \
	"SQ_Shortcut_to_WM_LABOR_MSG_DTL_PRE___HANDLING_UOM as HANDLING_UOM", \
	"SQ_Shortcut_to_WM_LABOR_MSG_DTL_PRE___SEASON as SEASON", \
	"SQ_Shortcut_to_WM_LABOR_MSG_DTL_PRE___SEASON_YR as SEASON_YR", \
	"SQ_Shortcut_to_WM_LABOR_MSG_DTL_PRE___STYLE as STYLE", \
	"SQ_Shortcut_to_WM_LABOR_MSG_DTL_PRE___STYLE_SFX as STYLE_SFX", \
	"SQ_Shortcut_to_WM_LABOR_MSG_DTL_PRE___COLOR as COLOR", \
	"SQ_Shortcut_to_WM_LABOR_MSG_DTL_PRE___COLOR_SFX as COLOR_SFX", \
	"SQ_Shortcut_to_WM_LABOR_MSG_DTL_PRE___SEC_DIM as SEC_DIM", \
	"SQ_Shortcut_to_WM_LABOR_MSG_DTL_PRE___QUAL as QUAL", \
	"SQ_Shortcut_to_WM_LABOR_MSG_DTL_PRE___SIZE_RNGE_CODE as SIZE_RNGE_CODE", \
	"SQ_Shortcut_to_WM_LABOR_MSG_DTL_PRE___SIZE_REL_POSN_IN_TABLE as SIZE_REL_POSN_IN_TABLE", \
	"SQ_Shortcut_to_WM_LABOR_MSG_DTL_PRE___MISC_NUM_1 as MISC_NUM_1", \
	"SQ_Shortcut_to_WM_LABOR_MSG_DTL_PRE___MISC_NUM_2 as MISC_NUM_2", \
	"SQ_Shortcut_to_WM_LABOR_MSG_DTL_PRE___MISC_2 as MISC_2", \
	"SQ_Shortcut_to_WM_LABOR_MSG_DTL_PRE___LOADED as LOADED", \
	"SQ_Shortcut_to_WM_LABOR_MSG_DTL_PRE___PUTAWAY_ZONE as PUTAWAY_ZONE", \
	"SQ_Shortcut_to_WM_LABOR_MSG_DTL_PRE___PICK_DETERMINATION_ZONE as PICK_DETERMINATION_ZONE", \
	"SQ_Shortcut_to_WM_LABOR_MSG_DTL_PRE___WORK_GROUP as WORK_GROUP", \
	"SQ_Shortcut_to_WM_LABOR_MSG_DTL_PRE___WORK_AREA as WORK_AREA", \
	"SQ_Shortcut_to_WM_LABOR_MSG_DTL_PRE___PULL_ZONE as PULL_ZONE", \
	"SQ_Shortcut_to_WM_LABOR_MSG_DTL_PRE___ASSIGNMENT_ZONE as ASSIGNMENT_ZONE", \
	"SQ_Shortcut_to_WM_LABOR_MSG_DTL_PRE___CREATED_SOURCE_TYPE as CREATED_SOURCE_TYPE", \
	"SQ_Shortcut_to_WM_LABOR_MSG_DTL_PRE___CREATED_SOURCE as CREATED_SOURCE", \
	"SQ_Shortcut_to_WM_LABOR_MSG_DTL_PRE___CREATED_DTTM as CREATED_DTTM", \
	"SQ_Shortcut_to_WM_LABOR_MSG_DTL_PRE___LAST_UPDATED_SOURCE_TYPE as LAST_UPDATED_SOURCE_TYPE", \
	"SQ_Shortcut_to_WM_LABOR_MSG_DTL_PRE___LAST_UPDATED_SOURCE as LAST_UPDATED_SOURCE", \
	"SQ_Shortcut_to_WM_LABOR_MSG_DTL_PRE___LAST_UPDATED_DTTM as LAST_UPDATED_DTTM", \
	"SQ_Shortcut_to_WM_LABOR_MSG_DTL_PRE___HIBERNATE_VERSION as HIBERNATE_VERSION", \
	"SQ_Shortcut_to_WM_LABOR_MSG_DTL_PRE___ITEM_NAME as ITEM_NAME", \
	"SQ_Shortcut_to_WM_LABOR_MSG_DTL_PRE___LOCN_GRP_ATTR as LOCN_GRP_ATTR", \
	"SQ_Shortcut_to_WM_LABOR_MSG_DTL_PRE___RESOURCE_GROUP_ID as RESOURCE_GROUP_ID", \
	"SQ_Shortcut_to_WM_LABOR_MSG_DTL_PRE___LOAD_TSTMP as LOAD_TSTMP" \
)

# COMMAND ----------
# Processing node SQ_Shortcut_to_SITE_PROFILE, type SOURCE 
# COLUMN COUNT: 2

SQ_Shortcut_to_SITE_PROFILE = spark.sql(f"""SELECT
SITE_PROFILE.LOCATION_ID,
SITE_PROFILE.STORE_NBR
FROM SITE_PROFILE""").withColumn("sys_row_id", monotonically_increasing_id())

# COMMAND ----------
# Processing node JNR_SITE_PROFILE, type JOINER 
# COLUMN COUNT: 71

JNR_SITE_PROFILE = SQ_Shortcut_to_SITE_PROFILE.join(EXP_INT_CONV,[SQ_Shortcut_to_SITE_PROFILE.STORE_NBR == EXP_INT_CONV.o_DC_NBR],'inner')

# COMMAND ----------
# Processing node JNR_WM_LABORE_MSG_DTL, type JOINER . Note: using additional SELECT to rename incoming columns
# COLUMN COUNT: 141

# for each involved DataFrame, append the dataframe name to each column
SQ_Shortcut_to_WM_LABOR_MSG_DTL_temp = SQ_Shortcut_to_WM_LABOR_MSG_DTL.toDF(*["SQ_Shortcut_to_WM_LABOR_MSG_DTL___" + col for col in SQ_Shortcut_to_WM_LABOR_MSG_DTL.columns])
JNR_SITE_PROFILE_temp = JNR_SITE_PROFILE.toDF(*["JNR_SITE_PROFILE___" + col for col in JNR_SITE_PROFILE.columns])

JNR_WM_LABORE_MSG_DTL = SQ_Shortcut_to_WM_LABOR_MSG_DTL_temp.join([SQ_Shortcut_to_WM_LABOR_MSG_DTL_temp.SQ_Shortcut_to_WM_LABOR_MSG_DTL___WM_LABOR_MSG_DTL_ID == JNR_SITE_PROFILE_temp.JNR_SITE_PROFILE___LABOR_MSG_DTL_ID, SQ_Shortcut_to_WM_LABOR_MSG_DTL_temp.SQ_Shortcut_to_WM_LABOR_MSG_DTL___LOCATION_ID == JNR_SITE_PROFILE_temp.JNR_SITE_PROFILE___LOCATION_ID],'right_outer').selectExpr( \
	"JNR_SITE_PROFILE___o_DC_NBR as o_DC_NBR", \
	"JNR_SITE_PROFILE___LABOR_MSG_DTL_ID as LABOR_MSG_DTL_ID", \
	"JNR_SITE_PROFILE___LABOR_MSG_ID as LABOR_MSG_ID", \
	"JNR_SITE_PROFILE___TRAN_NBR as TRAN_NBR", \
	"JNR_SITE_PROFILE___TRAN_SEQ_NBR as TRAN_SEQ_NBR", \
	"JNR_SITE_PROFILE___MSG_STAT_CODE as MSG_STAT_CODE", \
	"JNR_SITE_PROFILE___SEQ_NBR as SEQ_NBR", \
	"JNR_SITE_PROFILE___HNDL_ATTR as HNDL_ATTR", \
	"JNR_SITE_PROFILE___QTY_PER_GRAB as QTY_PER_GRAB", \
	"JNR_SITE_PROFILE___LOCN_CLASS as LOCN_CLASS", \
	"JNR_SITE_PROFILE___QTY as QTY", \
	"JNR_SITE_PROFILE___TC_ILPN_ID as TC_ILPN_ID", \
	"JNR_SITE_PROFILE___TC_OLPN_ID as TC_OLPN_ID", \
	"JNR_SITE_PROFILE___PALLET_ID as PALLET_ID", \
	"JNR_SITE_PROFILE___LOCN_SLOT_TYPE as LOCN_SLOT_TYPE", \
	"JNR_SITE_PROFILE___LOCN_X_COORD as LOCN_X_COORD", \
	"JNR_SITE_PROFILE___LOCN_Y_COORD as LOCN_Y_COORD", \
	"JNR_SITE_PROFILE___LOCN_Z_COORD as LOCN_Z_COORD", \
	"JNR_SITE_PROFILE___LOCN_TRAV_AISLE as LOCN_TRAV_AISLE", \
	"JNR_SITE_PROFILE___LOCN_TRAV_ZONE as LOCN_TRAV_ZONE", \
	"JNR_SITE_PROFILE___BOX_QTY as BOX_QTY", \
	"JNR_SITE_PROFILE___INNERPACK_QTY as INNERPACK_QTY", \
	"JNR_SITE_PROFILE___PACK_QTY as PACK_QTY", \
	"JNR_SITE_PROFILE___CASE_QTY as CASE_QTY", \
	"JNR_SITE_PROFILE___TIER_QTY as TIER_QTY", \
	"JNR_SITE_PROFILE___PALLET_QTY as PALLET_QTY", \
	"JNR_SITE_PROFILE___MISC as MISC", \
	"JNR_SITE_PROFILE___CO as CO", \
	"JNR_SITE_PROFILE___DIV as DIV", \
	"JNR_SITE_PROFILE___DSP_LOCN as DSP_LOCN", \
	"JNR_SITE_PROFILE___ITEM_BAR_CODE as ITEM_BAR_CODE", \
	"JNR_SITE_PROFILE___WEIGHT as WEIGHT", \
	"JNR_SITE_PROFILE___VOLUME as VOLUME", \
	"JNR_SITE_PROFILE___CRIT_DIM1 as CRIT_DIM1", \
	"JNR_SITE_PROFILE___CRIT_DIM2 as CRIT_DIM2", \
	"JNR_SITE_PROFILE___CRIT_DIM3 as CRIT_DIM3", \
	"JNR_SITE_PROFILE___START_DATE_TIME as START_DATE_TIME", \
	"JNR_SITE_PROFILE___HANDLING_UOM as HANDLING_UOM", \
	"JNR_SITE_PROFILE___SEASON as SEASON", \
	"JNR_SITE_PROFILE___SEASON_YR as SEASON_YR", \
	"JNR_SITE_PROFILE___STYLE as STYLE", \
	"JNR_SITE_PROFILE___STYLE_SFX as STYLE_SFX", \
	"JNR_SITE_PROFILE___COLOR as COLOR", \
	"JNR_SITE_PROFILE___COLOR_SFX as COLOR_SFX", \
	"JNR_SITE_PROFILE___SEC_DIM as SEC_DIM", \
	"JNR_SITE_PROFILE___QUAL as QUAL", \
	"JNR_SITE_PROFILE___SIZE_RNGE_CODE as SIZE_RNGE_CODE", \
	"JNR_SITE_PROFILE___SIZE_REL_POSN_IN_TABLE as SIZE_REL_POSN_IN_TABLE", \
	"JNR_SITE_PROFILE___MISC_NUM_1 as MISC_NUM_1", \
	"JNR_SITE_PROFILE___MISC_NUM_2 as MISC_NUM_2", \
	"JNR_SITE_PROFILE___MISC_2 as MISC_2", \
	"JNR_SITE_PROFILE___LOADED as LOADED", \
	"JNR_SITE_PROFILE___PUTAWAY_ZONE as PUTAWAY_ZONE", \
	"JNR_SITE_PROFILE___PICK_DETERMINATION_ZONE as PICK_DETERMINATION_ZONE", \
	"JNR_SITE_PROFILE___WORK_GROUP as WORK_GROUP", \
	"JNR_SITE_PROFILE___WORK_AREA as WORK_AREA", \
	"JNR_SITE_PROFILE___PULL_ZONE as PULL_ZONE", \
	"JNR_SITE_PROFILE___ASSIGNMENT_ZONE as ASSIGNMENT_ZONE", \
	"JNR_SITE_PROFILE___CREATED_SOURCE_TYPE as CREATED_SOURCE_TYPE", \
	"JNR_SITE_PROFILE___CREATED_SOURCE as CREATED_SOURCE", \
	"JNR_SITE_PROFILE___CREATED_DTTM as CREATED_DTTM", \
	"JNR_SITE_PROFILE___LAST_UPDATED_SOURCE_TYPE as LAST_UPDATED_SOURCE_TYPE", \
	"JNR_SITE_PROFILE___LAST_UPDATED_SOURCE as LAST_UPDATED_SOURCE", \
	"JNR_SITE_PROFILE___LAST_UPDATED_DTTM as LAST_UPDATED_DTTM", \
	"JNR_SITE_PROFILE___HIBERNATE_VERSION as HIBERNATE_VERSION", \
	"JNR_SITE_PROFILE___ITEM_NAME as ITEM_NAME", \
	"JNR_SITE_PROFILE___LOCN_GRP_ATTR as LOCN_GRP_ATTR", \
	"JNR_SITE_PROFILE___LOAD_TSTMP as LOAD_TSTMP", \
	"JNR_SITE_PROFILE___LOCATION_ID as LOCATION_ID", \
	"SQ_Shortcut_to_WM_LABOR_MSG_DTL___LOCATION_ID as in_LOCATION_ID", \
	"SQ_Shortcut_to_WM_LABOR_MSG_DTL___WM_LABOR_MSG_DTL_ID as WM_LABOR_MSG_DTL_ID", \
	"SQ_Shortcut_to_WM_LABOR_MSG_DTL___WM_LABOR_MSG_ID as WM_LABOR_MSG_ID", \
	"SQ_Shortcut_to_WM_LABOR_MSG_DTL___WM_TRAN_NBR as WM_TRAN_NBR", \
	"SQ_Shortcut_to_WM_LABOR_MSG_DTL___WM_TRAN_SEQ_NBR as WM_TRAN_SEQ_NBR", \
	"SQ_Shortcut_to_WM_LABOR_MSG_DTL___WM_MSG_STAT_CD as WM_MSG_STAT_CD", \
	"SQ_Shortcut_to_WM_LABOR_MSG_DTL___SEQ_NBR as SEQ_NBR1", \
	"SQ_Shortcut_to_WM_LABOR_MSG_DTL___WM_COMPANY as WM_COMPANY", \
	"SQ_Shortcut_to_WM_LABOR_MSG_DTL___WM_DIVISION as WM_DIVISION", \
	"SQ_Shortcut_to_WM_LABOR_MSG_DTL___WM_START_TSTMP as WM_START_TSTMP", \
	"SQ_Shortcut_to_WM_LABOR_MSG_DTL___WM_TC_ILPN_ID as WM_TC_ILPN_ID", \
	"SQ_Shortcut_to_WM_LABOR_MSG_DTL___WM_TC_OLPN_ID as WM_TC_OLPN_ID", \
	"SQ_Shortcut_to_WM_LABOR_MSG_DTL___WM_PUTAWAY_ZONE as WM_PUTAWAY_ZONE", \
	"SQ_Shortcut_to_WM_LABOR_MSG_DTL___WM_PICK_DETERMINATION_ZONE as WM_PICK_DETERMINATION_ZONE", \
	"SQ_Shortcut_to_WM_LABOR_MSG_DTL___WM_WORK_GROUP as WM_WORK_GROUP", \
	"SQ_Shortcut_to_WM_LABOR_MSG_DTL___WM_WORK_AREA as WM_WORK_AREA", \
	"SQ_Shortcut_to_WM_LABOR_MSG_DTL___WM_PULL_ZONE as WM_PULL_ZONE", \
	"SQ_Shortcut_to_WM_LABOR_MSG_DTL___WM_ASSIGNMENT_ZONE as WM_ASSIGNMENT_ZONE", \
	"SQ_Shortcut_to_WM_LABOR_MSG_DTL___WM_RESOURCE_GROUP_ID as WM_RESOURCE_GROUP_ID", \
	"SQ_Shortcut_to_WM_LABOR_MSG_DTL___LOADED_FLAG as LOADED_FLAG", \
	"SQ_Shortcut_to_WM_LABOR_MSG_DTL___WM_ITEM_BAR_CD as WM_ITEM_BAR_CD", \
	"SQ_Shortcut_to_WM_LABOR_MSG_DTL___WM_ITEM_NAME as WM_ITEM_NAME", \
	"SQ_Shortcut_to_WM_LABOR_MSG_DTL___SEC_DIM as in_SEC_DIM", \
	"SQ_Shortcut_to_WM_LABOR_MSG_DTL___WEIGHT as in_WEIGHT", \
	"SQ_Shortcut_to_WM_LABOR_MSG_DTL___VOLUME as in_VOLUME", \
	"SQ_Shortcut_to_WM_LABOR_MSG_DTL___SEASON as in_SEASON", \
	"SQ_Shortcut_to_WM_LABOR_MSG_DTL___SEASON_YR as in_SEASON_YR", \
	"SQ_Shortcut_to_WM_LABOR_MSG_DTL___STYLE as in_STYLE", \
	"SQ_Shortcut_to_WM_LABOR_MSG_DTL___STYLE_SFX as in_STYLE_SFX", \
	"SQ_Shortcut_to_WM_LABOR_MSG_DTL___COLOR as in_COLOR", \
	"SQ_Shortcut_to_WM_LABOR_MSG_DTL___COLOR_SFX as in_COLOR_SFX", \
	"SQ_Shortcut_to_WM_LABOR_MSG_DTL___WM_PALLET_ID as WM_PALLET_ID", \
	"SQ_Shortcut_to_WM_LABOR_MSG_DTL___WM_SIZE_RANGE_CD as WM_SIZE_RANGE_CD", \
	"SQ_Shortcut_to_WM_LABOR_MSG_DTL___SIZE_REL_POSN_IN_TABLE as SIZE_REL_POSN_IN_TABLE1", \
	"SQ_Shortcut_to_WM_LABOR_MSG_DTL___WM_LOCN_SLOT_TYPE as WM_LOCN_SLOT_TYPE", \
	"SQ_Shortcut_to_WM_LABOR_MSG_DTL___WM_LOCN_CLASS as WM_LOCN_CLASS", \
	"SQ_Shortcut_to_WM_LABOR_MSG_DTL___WM_LOCN_GRP_ATTR as WM_LOCN_GRP_ATTR", \
	"SQ_Shortcut_to_WM_LABOR_MSG_DTL___DSP_LOCN as in_DSP_LOCN", \
	"SQ_Shortcut_to_WM_LABOR_MSG_DTL___LOCN_X_COORD as in_LOCN_X_COORD", \
	"SQ_Shortcut_to_WM_LABOR_MSG_DTL___LOCN_Y_COORD as in_LOCN_Y_COORD", \
	"SQ_Shortcut_to_WM_LABOR_MSG_DTL___LOCN_Z_COORD as in_LOCN_Z_COORD", \
	"SQ_Shortcut_to_WM_LABOR_MSG_DTL___LOCN_TRAV_AISLE as in_LOCN_TRAV_AISLE", \
	"SQ_Shortcut_to_WM_LABOR_MSG_DTL___LOCN_TRAV_ZONE as in_LOCN_TRAV_ZONE", \
	"SQ_Shortcut_to_WM_LABOR_MSG_DTL___WM_HANDLING_ATTR as WM_HANDLING_ATTR", \
	"SQ_Shortcut_to_WM_LABOR_MSG_DTL___WM_HANDLING_UOM as WM_HANDLING_UOM", \
	"SQ_Shortcut_to_WM_LABOR_MSG_DTL___QUAL as in_QUAL", \
	"SQ_Shortcut_to_WM_LABOR_MSG_DTL___QTY_PER_GRAB as in_QTY_PER_GRAB", \
	"SQ_Shortcut_to_WM_LABOR_MSG_DTL___QTY as in_QTY", \
	"SQ_Shortcut_to_WM_LABOR_MSG_DTL___BOX_QTY as in_BOX_QTY", \
	"SQ_Shortcut_to_WM_LABOR_MSG_DTL___INNERPACK_QTY as in_INNERPACK_QTY", \
	"SQ_Shortcut_to_WM_LABOR_MSG_DTL___PACK_QTY as in_PACK_QTY", \
	"SQ_Shortcut_to_WM_LABOR_MSG_DTL___CASE_QTY as in_CASE_QTY", \
	"SQ_Shortcut_to_WM_LABOR_MSG_DTL___TIER_QTY as in_TIER_QTY", \
	"SQ_Shortcut_to_WM_LABOR_MSG_DTL___PALLET_QTY as in_PALLET_QTY", \
	"SQ_Shortcut_to_WM_LABOR_MSG_DTL___CRIT_DIM1 as in_CRIT_DIM1", \
	"SQ_Shortcut_to_WM_LABOR_MSG_DTL___CRIT_DIM2 as in_CRIT_DIM2", \
	"SQ_Shortcut_to_WM_LABOR_MSG_DTL___CRIT_DIM3 as in_CRIT_DIM3", \
	"SQ_Shortcut_to_WM_LABOR_MSG_DTL___MISC as in_MISC", \
	"SQ_Shortcut_to_WM_LABOR_MSG_DTL___MISC_2 as in_MISC_2", \
	"SQ_Shortcut_to_WM_LABOR_MSG_DTL___MISC_NUM_1 as in_MISC_NUM_1", \
	"SQ_Shortcut_to_WM_LABOR_MSG_DTL___MISC_NUM_2 as in_MISC_NUM_2", \
	"SQ_Shortcut_to_WM_LABOR_MSG_DTL___WM_HIBERNATE_VERSION as WM_HIBERNATE_VERSION", \
	"SQ_Shortcut_to_WM_LABOR_MSG_DTL___WM_CREATED_SOURCE_TYPE as WM_CREATED_SOURCE_TYPE", \
	"SQ_Shortcut_to_WM_LABOR_MSG_DTL___WM_CREATED_SOURCE as WM_CREATED_SOURCE", \
	"SQ_Shortcut_to_WM_LABOR_MSG_DTL___WM_CREATED_TSTMP as WM_CREATED_TSTMP", \
	"SQ_Shortcut_to_WM_LABOR_MSG_DTL___WM_LAST_UPDATED_SOURCE_TYPE as WM_LAST_UPDATED_SOURCE_TYPE", \
	"SQ_Shortcut_to_WM_LABOR_MSG_DTL___WM_LAST_UPDATED_SOURCE as WM_LAST_UPDATED_SOURCE", \
	"SQ_Shortcut_to_WM_LABOR_MSG_DTL___WM_LAST_UPDATED_TSTMP as WM_LAST_UPDATED_TSTMP", \
	"SQ_Shortcut_to_WM_LABOR_MSG_DTL___UPDATE_TSTMP as in_UPDATE_TSTMP", \
	"SQ_Shortcut_to_WM_LABOR_MSG_DTL___LOAD_TSTMP as in_LOAD_TSTMP") \
	.withColumn('RESOURCE_GROUP_ID', lit(None)) \
	.withColumn('STORE_NBR', lit(None)) \
	

# COMMAND ----------
# Processing node FIL_NEW_CHANGE_REC, type FILTER 
# COLUMN COUNT: 139

# for each involved DataFrame, append the dataframe name to each column
JNR_WM_LABORE_MSG_DTL_temp = JNR_WM_LABORE_MSG_DTL.toDF(*["JNR_WM_LABORE_MSG_DTL___" + col for col in JNR_WM_LABORE_MSG_DTL.columns])

FIL_NEW_CHANGE_REC = JNR_WM_LABORE_MSG_DTL_temp.selectExpr( \
	"JNR_WM_LABORE_MSG_DTL___o_DC_NBR as o_DC_NBR", \
	"JNR_WM_LABORE_MSG_DTL___LABOR_MSG_DTL_ID as LABOR_MSG_DTL_ID", \
	"JNR_WM_LABORE_MSG_DTL___LABOR_MSG_ID as LABOR_MSG_ID", \
	"JNR_WM_LABORE_MSG_DTL___TRAN_NBR as TRAN_NBR", \
	"JNR_WM_LABORE_MSG_DTL___TRAN_SEQ_NBR as TRAN_SEQ_NBR", \
	"JNR_WM_LABORE_MSG_DTL___MSG_STAT_CODE as MSG_STAT_CODE", \
	"JNR_WM_LABORE_MSG_DTL___SEQ_NBR as SEQ_NBR", \
	"JNR_WM_LABORE_MSG_DTL___HNDL_ATTR as HNDL_ATTR", \
	"JNR_WM_LABORE_MSG_DTL___QTY_PER_GRAB as QTY_PER_GRAB", \
	"JNR_WM_LABORE_MSG_DTL___LOCN_CLASS as LOCN_CLASS", \
	"JNR_WM_LABORE_MSG_DTL___QTY as QTY", \
	"JNR_WM_LABORE_MSG_DTL___TC_ILPN_ID as TC_ILPN_ID", \
	"JNR_WM_LABORE_MSG_DTL___TC_OLPN_ID as TC_OLPN_ID", \
	"JNR_WM_LABORE_MSG_DTL___PALLET_ID as PALLET_ID", \
	"JNR_WM_LABORE_MSG_DTL___LOCN_SLOT_TYPE as LOCN_SLOT_TYPE", \
	"JNR_WM_LABORE_MSG_DTL___LOCN_X_COORD as LOCN_X_COORD", \
	"JNR_WM_LABORE_MSG_DTL___LOCN_Y_COORD as LOCN_Y_COORD", \
	"JNR_WM_LABORE_MSG_DTL___LOCN_Z_COORD as LOCN_Z_COORD", \
	"JNR_WM_LABORE_MSG_DTL___LOCN_TRAV_AISLE as LOCN_TRAV_AISLE", \
	"JNR_WM_LABORE_MSG_DTL___LOCN_TRAV_ZONE as LOCN_TRAV_ZONE", \
	"JNR_WM_LABORE_MSG_DTL___BOX_QTY as BOX_QTY", \
	"JNR_WM_LABORE_MSG_DTL___INNERPACK_QTY as INNERPACK_QTY", \
	"JNR_WM_LABORE_MSG_DTL___PACK_QTY as PACK_QTY", \
	"JNR_WM_LABORE_MSG_DTL___CASE_QTY as CASE_QTY", \
	"JNR_WM_LABORE_MSG_DTL___TIER_QTY as TIER_QTY", \
	"JNR_WM_LABORE_MSG_DTL___PALLET_QTY as PALLET_QTY", \
	"JNR_WM_LABORE_MSG_DTL___MISC as MISC", \
	"JNR_WM_LABORE_MSG_DTL___CO as CO", \
	"JNR_WM_LABORE_MSG_DTL___DIV as DIV", \
	"JNR_WM_LABORE_MSG_DTL___DSP_LOCN as DSP_LOCN", \
	"JNR_WM_LABORE_MSG_DTL___ITEM_BAR_CODE as ITEM_BAR_CODE", \
	"JNR_WM_LABORE_MSG_DTL___WEIGHT as WEIGHT", \
	"JNR_WM_LABORE_MSG_DTL___VOLUME as VOLUME", \
	"JNR_WM_LABORE_MSG_DTL___CRIT_DIM1 as CRIT_DIM1", \
	"JNR_WM_LABORE_MSG_DTL___CRIT_DIM2 as CRIT_DIM2", \
	"JNR_WM_LABORE_MSG_DTL___CRIT_DIM3 as CRIT_DIM3", \
	"JNR_WM_LABORE_MSG_DTL___START_DATE_TIME as START_DATE_TIME", \
	"JNR_WM_LABORE_MSG_DTL___HANDLING_UOM as HANDLING_UOM", \
	"JNR_WM_LABORE_MSG_DTL___SEASON as SEASON", \
	"JNR_WM_LABORE_MSG_DTL___SEASON_YR as SEASON_YR", \
	"JNR_WM_LABORE_MSG_DTL___STYLE as STYLE", \
	"JNR_WM_LABORE_MSG_DTL___STYLE_SFX as STYLE_SFX", \
	"JNR_WM_LABORE_MSG_DTL___COLOR as COLOR", \
	"JNR_WM_LABORE_MSG_DTL___COLOR_SFX as COLOR_SFX", \
	"JNR_WM_LABORE_MSG_DTL___SEC_DIM as SEC_DIM", \
	"JNR_WM_LABORE_MSG_DTL___QUAL as QUAL", \
	"JNR_WM_LABORE_MSG_DTL___SIZE_RNGE_CODE as SIZE_RNGE_CODE", \
	"JNR_WM_LABORE_MSG_DTL___SIZE_REL_POSN_IN_TABLE as SIZE_REL_POSN_IN_TABLE", \
	"JNR_WM_LABORE_MSG_DTL___MISC_NUM_1 as MISC_NUM_1", \
	"JNR_WM_LABORE_MSG_DTL___MISC_NUM_2 as MISC_NUM_2", \
	"JNR_WM_LABORE_MSG_DTL___MISC_2 as MISC_2", \
	"JNR_WM_LABORE_MSG_DTL___LOADED as LOADED", \
	"JNR_WM_LABORE_MSG_DTL___PUTAWAY_ZONE as PUTAWAY_ZONE", \
	"JNR_WM_LABORE_MSG_DTL___PICK_DETERMINATION_ZONE as PICK_DETERMINATION_ZONE", \
	"JNR_WM_LABORE_MSG_DTL___WORK_GROUP as WORK_GROUP", \
	"JNR_WM_LABORE_MSG_DTL___WORK_AREA as WORK_AREA", \
	"JNR_WM_LABORE_MSG_DTL___PULL_ZONE as PULL_ZONE", \
	"JNR_WM_LABORE_MSG_DTL___ASSIGNMENT_ZONE as ASSIGNMENT_ZONE", \
	"JNR_WM_LABORE_MSG_DTL___CREATED_SOURCE_TYPE as CREATED_SOURCE_TYPE", \
	"JNR_WM_LABORE_MSG_DTL___CREATED_SOURCE as CREATED_SOURCE", \
	"JNR_WM_LABORE_MSG_DTL___CREATED_DTTM as CREATED_DTTM", \
	"JNR_WM_LABORE_MSG_DTL___LAST_UPDATED_SOURCE_TYPE as LAST_UPDATED_SOURCE_TYPE", \
	"JNR_WM_LABORE_MSG_DTL___LAST_UPDATED_SOURCE as LAST_UPDATED_SOURCE", \
	"JNR_WM_LABORE_MSG_DTL___LAST_UPDATED_DTTM as LAST_UPDATED_DTTM", \
	"JNR_WM_LABORE_MSG_DTL___HIBERNATE_VERSION as HIBERNATE_VERSION", \
	"JNR_WM_LABORE_MSG_DTL___ITEM_NAME as ITEM_NAME", \
	"JNR_WM_LABORE_MSG_DTL___LOCN_GRP_ATTR as LOCN_GRP_ATTR", \
	"JNR_WM_LABORE_MSG_DTL___RESOURCE_GROUP_ID as RESOURCE_GROUP_ID", \
	"JNR_WM_LABORE_MSG_DTL___LOCATION_ID as LOCATION_ID", \
	"JNR_WM_LABORE_MSG_DTL___in_LOCATION_ID as in_LOCATION_ID", \
	"JNR_WM_LABORE_MSG_DTL___WM_LABOR_MSG_DTL_ID as WM_LABOR_MSG_DTL_ID", \
	"JNR_WM_LABORE_MSG_DTL___WM_LABOR_MSG_ID as WM_LABOR_MSG_ID", \
	"JNR_WM_LABORE_MSG_DTL___WM_TRAN_NBR as WM_TRAN_NBR", \
	"JNR_WM_LABORE_MSG_DTL___WM_TRAN_SEQ_NBR as WM_TRAN_SEQ_NBR", \
	"JNR_WM_LABORE_MSG_DTL___WM_MSG_STAT_CD as WM_MSG_STAT_CD", \
	"JNR_WM_LABORE_MSG_DTL___SEQ_NBR1 as SEQ_NBR1", \
	"JNR_WM_LABORE_MSG_DTL___WM_COMPANY as WM_COMPANY", \
	"JNR_WM_LABORE_MSG_DTL___WM_DIVISION as WM_DIVISION", \
	"JNR_WM_LABORE_MSG_DTL___WM_START_TSTMP as WM_START_TSTMP", \
	"JNR_WM_LABORE_MSG_DTL___WM_TC_ILPN_ID as WM_TC_ILPN_ID", \
	"JNR_WM_LABORE_MSG_DTL___WM_TC_OLPN_ID as WM_TC_OLPN_ID", \
	"JNR_WM_LABORE_MSG_DTL___WM_PUTAWAY_ZONE as WM_PUTAWAY_ZONE", \
	"JNR_WM_LABORE_MSG_DTL___WM_PICK_DETERMINATION_ZONE as WM_PICK_DETERMINATION_ZONE", \
	"JNR_WM_LABORE_MSG_DTL___WM_WORK_GROUP as WM_WORK_GROUP", \
	"JNR_WM_LABORE_MSG_DTL___WM_WORK_AREA as WM_WORK_AREA", \
	"JNR_WM_LABORE_MSG_DTL___WM_PULL_ZONE as WM_PULL_ZONE", \
	"JNR_WM_LABORE_MSG_DTL___WM_ASSIGNMENT_ZONE as WM_ASSIGNMENT_ZONE", \
	"JNR_WM_LABORE_MSG_DTL___WM_RESOURCE_GROUP_ID as WM_RESOURCE_GROUP_ID", \
	"JNR_WM_LABORE_MSG_DTL___LOADED_FLAG as LOADED_FLAG", \
	"JNR_WM_LABORE_MSG_DTL___WM_ITEM_BAR_CD as WM_ITEM_BAR_CD", \
	"JNR_WM_LABORE_MSG_DTL___WM_ITEM_NAME as WM_ITEM_NAME", \
	"JNR_WM_LABORE_MSG_DTL___in_SEC_DIM as in_SEC_DIM", \
	"JNR_WM_LABORE_MSG_DTL___in_WEIGHT as in_WEIGHT", \
	"JNR_WM_LABORE_MSG_DTL___in_VOLUME as in_VOLUME", \
	"JNR_WM_LABORE_MSG_DTL___in_SEASON as in_SEASON", \
	"JNR_WM_LABORE_MSG_DTL___in_SEASON_YR as in_SEASON_YR", \
	"JNR_WM_LABORE_MSG_DTL___in_STYLE as in_STYLE", \
	"JNR_WM_LABORE_MSG_DTL___in_STYLE_SFX as in_STYLE_SFX", \
	"JNR_WM_LABORE_MSG_DTL___in_COLOR as in_COLOR", \
	"JNR_WM_LABORE_MSG_DTL___in_COLOR_SFX as in_COLOR_SFX", \
	"JNR_WM_LABORE_MSG_DTL___WM_PALLET_ID as WM_PALLET_ID", \
	"JNR_WM_LABORE_MSG_DTL___WM_SIZE_RANGE_CD as WM_SIZE_RANGE_CD", \
	"JNR_WM_LABORE_MSG_DTL___SIZE_REL_POSN_IN_TABLE1 as SIZE_REL_POSN_IN_TABLE1", \
	"JNR_WM_LABORE_MSG_DTL___WM_LOCN_SLOT_TYPE as WM_LOCN_SLOT_TYPE", \
	"JNR_WM_LABORE_MSG_DTL___WM_LOCN_CLASS as WM_LOCN_CLASS", \
	"JNR_WM_LABORE_MSG_DTL___WM_LOCN_GRP_ATTR as WM_LOCN_GRP_ATTR", \
	"JNR_WM_LABORE_MSG_DTL___in_DSP_LOCN as in_DSP_LOCN", \
	"JNR_WM_LABORE_MSG_DTL___in_LOCN_X_COORD as in_LOCN_X_COORD", \
	"JNR_WM_LABORE_MSG_DTL___in_LOCN_Y_COORD as in_LOCN_Y_COORD", \
	"JNR_WM_LABORE_MSG_DTL___in_LOCN_Z_COORD as in_LOCN_Z_COORD", \
	"JNR_WM_LABORE_MSG_DTL___in_LOCN_TRAV_AISLE as in_LOCN_TRAV_AISLE", \
	"JNR_WM_LABORE_MSG_DTL___in_LOCN_TRAV_ZONE as in_LOCN_TRAV_ZONE", \
	"JNR_WM_LABORE_MSG_DTL___WM_HANDLING_ATTR as WM_HANDLING_ATTR", \
	"JNR_WM_LABORE_MSG_DTL___WM_HANDLING_UOM as WM_HANDLING_UOM", \
	"JNR_WM_LABORE_MSG_DTL___in_QUAL as in_QUAL", \
	"JNR_WM_LABORE_MSG_DTL___in_QTY_PER_GRAB as in_QTY_PER_GRAB", \
	"JNR_WM_LABORE_MSG_DTL___in_QTY as in_QTY", \
	"JNR_WM_LABORE_MSG_DTL___in_BOX_QTY as in_BOX_QTY", \
	"JNR_WM_LABORE_MSG_DTL___in_INNERPACK_QTY as in_INNERPACK_QTY", \
	"JNR_WM_LABORE_MSG_DTL___in_PACK_QTY as in_PACK_QTY", \
	"JNR_WM_LABORE_MSG_DTL___in_CASE_QTY as in_CASE_QTY", \
	"JNR_WM_LABORE_MSG_DTL___in_TIER_QTY as in_TIER_QTY", \
	"JNR_WM_LABORE_MSG_DTL___in_PALLET_QTY as in_PALLET_QTY", \
	"JNR_WM_LABORE_MSG_DTL___in_CRIT_DIM1 as in_CRIT_DIM1", \
	"JNR_WM_LABORE_MSG_DTL___in_CRIT_DIM2 as in_CRIT_DIM2", \
	"JNR_WM_LABORE_MSG_DTL___in_CRIT_DIM3 as in_CRIT_DIM3", \
	"JNR_WM_LABORE_MSG_DTL___in_MISC as in_MISC", \
	"JNR_WM_LABORE_MSG_DTL___in_MISC_2 as in_MISC_2", \
	"JNR_WM_LABORE_MSG_DTL___in_MISC_NUM_1 as in_MISC_NUM_1", \
	"JNR_WM_LABORE_MSG_DTL___in_MISC_NUM_2 as in_MISC_NUM_2", \
	"JNR_WM_LABORE_MSG_DTL___WM_HIBERNATE_VERSION as WM_HIBERNATE_VERSION", \
	"JNR_WM_LABORE_MSG_DTL___WM_CREATED_SOURCE_TYPE as WM_CREATED_SOURCE_TYPE", \
	"JNR_WM_LABORE_MSG_DTL___WM_CREATED_SOURCE as WM_CREATED_SOURCE", \
	"JNR_WM_LABORE_MSG_DTL___WM_CREATED_TSTMP as WM_CREATED_TSTMP", \
	"JNR_WM_LABORE_MSG_DTL___WM_LAST_UPDATED_SOURCE_TYPE as WM_LAST_UPDATED_SOURCE_TYPE", \
	"JNR_WM_LABORE_MSG_DTL___WM_LAST_UPDATED_SOURCE as WM_LAST_UPDATED_SOURCE", \
	"JNR_WM_LABORE_MSG_DTL___WM_LAST_UPDATED_TSTMP as WM_LAST_UPDATED_TSTMP", \
	"JNR_WM_LABORE_MSG_DTL___in_UPDATE_TSTMP as in_UPDATE_TSTMP", \
	"JNR_WM_LABORE_MSG_DTL___in_LOAD_TSTMP as in_LOAD_TSTMP")\
	.filter("WM_LABOR_MSG_DTL_ID is Null OR (  WM_LABOR_MSG_DTL_ID is not Null AND ( COALESCE(CREATED_DTTM, date'1900-01-01') != COALESCE(WM_CREATED_TSTMP, date'1900-01-01') OR COALESCE(LAST_UPDATED_DTTM, date'1900-01-01') != COALESCE(WM_LAST_UPDATED_TSTMP, date'1900-01-01')))").withColumn("sys_row_id", monotonically_increasing_id())


# COMMAND ----------
# Processing node EXP_EVAL_VALUES, type EXPRESSION 
# COLUMN COUNT: 141

# for each involved DataFrame, append the dataframe name to each column
FIL_NEW_CHANGE_REC_temp = FIL_NEW_CHANGE_REC.toDF(*["FIL_NEW_CHANGE_REC___" + col for col in FIL_NEW_CHANGE_REC.columns])

EXP_EVAL_VALUES = FIL_NEW_CHANGE_REC_temp.selectExpr( \
	"FIL_NEW_CHANGE_REC___sys_row_id as sys_row_id", \
	"FIL_NEW_CHANGE_REC___o_DC_NBR as o_DC_NBR", \
	"FIL_NEW_CHANGE_REC___LABOR_MSG_DTL_ID as LABOR_MSG_DTL_ID", \
	"FIL_NEW_CHANGE_REC___LABOR_MSG_ID as LABOR_MSG_ID", \
	"FIL_NEW_CHANGE_REC___TRAN_NBR as TRAN_NBR", \
	"FIL_NEW_CHANGE_REC___TRAN_SEQ_NBR as TRAN_SEQ_NBR", \
	"FIL_NEW_CHANGE_REC___MSG_STAT_CODE as MSG_STAT_CODE", \
	"FIL_NEW_CHANGE_REC___SEQ_NBR as SEQ_NBR", \
	"FIL_NEW_CHANGE_REC___HNDL_ATTR as HNDL_ATTR", \
	"FIL_NEW_CHANGE_REC___QTY_PER_GRAB as QTY_PER_GRAB", \
	"FIL_NEW_CHANGE_REC___LOCN_CLASS as LOCN_CLASS", \
	"FIL_NEW_CHANGE_REC___QTY as QTY", \
	"FIL_NEW_CHANGE_REC___TC_ILPN_ID as TC_ILPN_ID", \
	"FIL_NEW_CHANGE_REC___TC_OLPN_ID as TC_OLPN_ID", \
	"FIL_NEW_CHANGE_REC___PALLET_ID as PALLET_ID", \
	"FIL_NEW_CHANGE_REC___LOCN_SLOT_TYPE as LOCN_SLOT_TYPE", \
	"FIL_NEW_CHANGE_REC___LOCN_X_COORD as LOCN_X_COORD", \
	"FIL_NEW_CHANGE_REC___LOCN_Y_COORD as LOCN_Y_COORD", \
	"FIL_NEW_CHANGE_REC___LOCN_Z_COORD as LOCN_Z_COORD", \
	"FIL_NEW_CHANGE_REC___LOCN_TRAV_AISLE as LOCN_TRAV_AISLE", \
	"FIL_NEW_CHANGE_REC___LOCN_TRAV_ZONE as LOCN_TRAV_ZONE", \
	"FIL_NEW_CHANGE_REC___BOX_QTY as BOX_QTY", \
	"FIL_NEW_CHANGE_REC___INNERPACK_QTY as INNERPACK_QTY", \
	"FIL_NEW_CHANGE_REC___PACK_QTY as PACK_QTY", \
	"FIL_NEW_CHANGE_REC___CASE_QTY as CASE_QTY", \
	"FIL_NEW_CHANGE_REC___TIER_QTY as TIER_QTY", \
	"FIL_NEW_CHANGE_REC___PALLET_QTY as PALLET_QTY", \
	"FIL_NEW_CHANGE_REC___MISC as MISC", \
	"FIL_NEW_CHANGE_REC___CO as CO", \
	"FIL_NEW_CHANGE_REC___DIV as DIV", \
	"FIL_NEW_CHANGE_REC___DSP_LOCN as DSP_LOCN", \
	"FIL_NEW_CHANGE_REC___ITEM_BAR_CODE as ITEM_BAR_CODE", \
	"FIL_NEW_CHANGE_REC___WEIGHT as WEIGHT", \
	"FIL_NEW_CHANGE_REC___VOLUME as VOLUME", \
	"FIL_NEW_CHANGE_REC___CRIT_DIM1 as CRIT_DIM1", \
	"FIL_NEW_CHANGE_REC___CRIT_DIM2 as CRIT_DIM2", \
	"FIL_NEW_CHANGE_REC___CRIT_DIM3 as CRIT_DIM3", \
	"FIL_NEW_CHANGE_REC___START_DATE_TIME as START_DATE_TIME", \
	"FIL_NEW_CHANGE_REC___HANDLING_UOM as HANDLING_UOM", \
	"FIL_NEW_CHANGE_REC___SEASON as SEASON", \
	"FIL_NEW_CHANGE_REC___SEASON_YR as SEASON_YR", \
	"FIL_NEW_CHANGE_REC___STYLE as STYLE", \
	"FIL_NEW_CHANGE_REC___STYLE_SFX as STYLE_SFX", \
	"FIL_NEW_CHANGE_REC___COLOR as COLOR", \
	"FIL_NEW_CHANGE_REC___COLOR_SFX as COLOR_SFX", \
	"FIL_NEW_CHANGE_REC___SEC_DIM as SEC_DIM", \
	"FIL_NEW_CHANGE_REC___QUAL as QUAL", \
	"FIL_NEW_CHANGE_REC___SIZE_RNGE_CODE as SIZE_RNGE_CODE", \
	"FIL_NEW_CHANGE_REC___SIZE_REL_POSN_IN_TABLE as SIZE_REL_POSN_IN_TABLE", \
	"FIL_NEW_CHANGE_REC___MISC_NUM_1 as MISC_NUM_1", \
	"FIL_NEW_CHANGE_REC___MISC_NUM_2 as MISC_NUM_2", \
	"FIL_NEW_CHANGE_REC___MISC_2 as MISC_2", \
	"DECODE ( LTRIM ( RTRIM ( UPPER ( FIL_NEW_CHANGE_REC___LOADED ) ) ) , 'Y','1' , '1','1','0' ) as LOADED_FLAG_EXP", \
	"FIL_NEW_CHANGE_REC___PUTAWAY_ZONE as PUTAWAY_ZONE", \
	"FIL_NEW_CHANGE_REC___PICK_DETERMINATION_ZONE as PICK_DETERMINATION_ZONE", \
	"FIL_NEW_CHANGE_REC___WORK_GROUP as WORK_GROUP", \
	"FIL_NEW_CHANGE_REC___WORK_AREA as WORK_AREA", \
	"FIL_NEW_CHANGE_REC___PULL_ZONE as PULL_ZONE", \
	"FIL_NEW_CHANGE_REC___ASSIGNMENT_ZONE as ASSIGNMENT_ZONE", \
	"FIL_NEW_CHANGE_REC___CREATED_SOURCE_TYPE as CREATED_SOURCE_TYPE", \
	"FIL_NEW_CHANGE_REC___CREATED_SOURCE as CREATED_SOURCE", \
	"FIL_NEW_CHANGE_REC___CREATED_DTTM as CREATED_DTTM", \
	"FIL_NEW_CHANGE_REC___LAST_UPDATED_SOURCE_TYPE as LAST_UPDATED_SOURCE_TYPE", \
	"FIL_NEW_CHANGE_REC___LAST_UPDATED_SOURCE as LAST_UPDATED_SOURCE", \
	"FIL_NEW_CHANGE_REC___LAST_UPDATED_DTTM as LAST_UPDATED_DTTM", \
	"FIL_NEW_CHANGE_REC___HIBERNATE_VERSION as HIBERNATE_VERSION", \
	"FIL_NEW_CHANGE_REC___ITEM_NAME as ITEM_NAME", \
	"FIL_NEW_CHANGE_REC___LOCN_GRP_ATTR as LOCN_GRP_ATTR", \
	"FIL_NEW_CHANGE_REC___RESOURCE_GROUP_ID as RESOURCE_GROUP_ID", \
	"FIL_NEW_CHANGE_REC___LOCATION_ID as LOCATION_ID", \
	"FIL_NEW_CHANGE_REC___in_LOCATION_ID as in_LOCATION_ID", \
	"FIL_NEW_CHANGE_REC___WM_LABOR_MSG_DTL_ID as WM_LABOR_MSG_DTL_ID", \
	"FIL_NEW_CHANGE_REC___WM_LABOR_MSG_ID as WM_LABOR_MSG_ID", \
	"FIL_NEW_CHANGE_REC___WM_TRAN_NBR as WM_TRAN_NBR", \
	"FIL_NEW_CHANGE_REC___WM_TRAN_SEQ_NBR as WM_TRAN_SEQ_NBR", \
	"FIL_NEW_CHANGE_REC___WM_MSG_STAT_CD as WM_MSG_STAT_CD", \
	"FIL_NEW_CHANGE_REC___SEQ_NBR1 as SEQ_NBR1", \
	"FIL_NEW_CHANGE_REC___WM_COMPANY as WM_COMPANY", \
	"FIL_NEW_CHANGE_REC___WM_DIVISION as WM_DIVISION", \
	"FIL_NEW_CHANGE_REC___WM_START_TSTMP as WM_START_TSTMP", \
	"FIL_NEW_CHANGE_REC___WM_TC_ILPN_ID as WM_TC_ILPN_ID", \
	"FIL_NEW_CHANGE_REC___WM_TC_OLPN_ID as WM_TC_OLPN_ID", \
	"FIL_NEW_CHANGE_REC___WM_PUTAWAY_ZONE as WM_PUTAWAY_ZONE", \
	"FIL_NEW_CHANGE_REC___WM_PICK_DETERMINATION_ZONE as WM_PICK_DETERMINATION_ZONE", \
	"FIL_NEW_CHANGE_REC___WM_WORK_GROUP as WM_WORK_GROUP", \
	"FIL_NEW_CHANGE_REC___WM_WORK_AREA as WM_WORK_AREA", \
	"FIL_NEW_CHANGE_REC___WM_PULL_ZONE as WM_PULL_ZONE", \
	"FIL_NEW_CHANGE_REC___WM_ASSIGNMENT_ZONE as WM_ASSIGNMENT_ZONE", \
	"FIL_NEW_CHANGE_REC___WM_RESOURCE_GROUP_ID as WM_RESOURCE_GROUP_ID", \
	"FIL_NEW_CHANGE_REC___LOADED_FLAG as LOADED_FLAG", \
	"FIL_NEW_CHANGE_REC___WM_ITEM_BAR_CD as WM_ITEM_BAR_CD", \
	"FIL_NEW_CHANGE_REC___WM_ITEM_NAME as WM_ITEM_NAME", \
	"FIL_NEW_CHANGE_REC___in_SEC_DIM as in_SEC_DIM", \
	"FIL_NEW_CHANGE_REC___in_WEIGHT as in_WEIGHT", \
	"FIL_NEW_CHANGE_REC___in_VOLUME as in_VOLUME", \
	"FIL_NEW_CHANGE_REC___in_SEASON as in_SEASON", \
	"FIL_NEW_CHANGE_REC___in_SEASON_YR as in_SEASON_YR", \
	"FIL_NEW_CHANGE_REC___in_STYLE as in_STYLE", \
	"FIL_NEW_CHANGE_REC___in_STYLE_SFX as in_STYLE_SFX", \
	"FIL_NEW_CHANGE_REC___in_COLOR as in_COLOR", \
	"FIL_NEW_CHANGE_REC___in_COLOR_SFX as in_COLOR_SFX", \
	"FIL_NEW_CHANGE_REC___WM_PALLET_ID as WM_PALLET_ID", \
	"FIL_NEW_CHANGE_REC___WM_SIZE_RANGE_CD as WM_SIZE_RANGE_CD", \
	"FIL_NEW_CHANGE_REC___SIZE_REL_POSN_IN_TABLE1 as SIZE_REL_POSN_IN_TABLE1", \
	"FIL_NEW_CHANGE_REC___WM_LOCN_SLOT_TYPE as WM_LOCN_SLOT_TYPE", \
	"FIL_NEW_CHANGE_REC___WM_LOCN_CLASS as WM_LOCN_CLASS", \
	"FIL_NEW_CHANGE_REC___WM_LOCN_GRP_ATTR as WM_LOCN_GRP_ATTR", \
	"FIL_NEW_CHANGE_REC___in_DSP_LOCN as in_DSP_LOCN", \
	"FIL_NEW_CHANGE_REC___in_LOCN_X_COORD as in_LOCN_X_COORD", \
	"FIL_NEW_CHANGE_REC___in_LOCN_Y_COORD as in_LOCN_Y_COORD", \
	"FIL_NEW_CHANGE_REC___in_LOCN_Z_COORD as in_LOCN_Z_COORD", \
	"FIL_NEW_CHANGE_REC___in_LOCN_TRAV_AISLE as in_LOCN_TRAV_AISLE", \
	"FIL_NEW_CHANGE_REC___in_LOCN_TRAV_ZONE as in_LOCN_TRAV_ZONE", \
	"FIL_NEW_CHANGE_REC___WM_HANDLING_ATTR as WM_HANDLING_ATTR", \
	"FIL_NEW_CHANGE_REC___WM_HANDLING_UOM as WM_HANDLING_UOM", \
	"FIL_NEW_CHANGE_REC___in_QUAL as in_QUAL", \
	"FIL_NEW_CHANGE_REC___in_QTY_PER_GRAB as in_QTY_PER_GRAB", \
	"FIL_NEW_CHANGE_REC___in_QTY as in_QTY", \
	"FIL_NEW_CHANGE_REC___in_BOX_QTY as in_BOX_QTY", \
	"FIL_NEW_CHANGE_REC___in_INNERPACK_QTY as in_INNERPACK_QTY", \
	"FIL_NEW_CHANGE_REC___in_PACK_QTY as in_PACK_QTY", \
	"FIL_NEW_CHANGE_REC___in_CASE_QTY as in_CASE_QTY", \
	"FIL_NEW_CHANGE_REC___in_TIER_QTY as in_TIER_QTY", \
	"FIL_NEW_CHANGE_REC___in_PALLET_QTY as in_PALLET_QTY", \
	"FIL_NEW_CHANGE_REC___in_CRIT_DIM1 as in_CRIT_DIM1", \
	"FIL_NEW_CHANGE_REC___in_CRIT_DIM2 as in_CRIT_DIM2", \
	"FIL_NEW_CHANGE_REC___in_CRIT_DIM3 as in_CRIT_DIM3", \
	"FIL_NEW_CHANGE_REC___in_MISC as in_MISC", \
	"FIL_NEW_CHANGE_REC___in_MISC_2 as in_MISC_2", \
	"FIL_NEW_CHANGE_REC___in_MISC_NUM_1 as in_MISC_NUM_1", \
	"FIL_NEW_CHANGE_REC___in_MISC_NUM_2 as in_MISC_NUM_2", \
	"FIL_NEW_CHANGE_REC___WM_HIBERNATE_VERSION as WM_HIBERNATE_VERSION", \
	"FIL_NEW_CHANGE_REC___WM_CREATED_SOURCE_TYPE as WM_CREATED_SOURCE_TYPE", \
	"FIL_NEW_CHANGE_REC___WM_CREATED_SOURCE as WM_CREATED_SOURCE", \
	"FIL_NEW_CHANGE_REC___WM_CREATED_TSTMP as WM_CREATED_TSTMP", \
	"FIL_NEW_CHANGE_REC___WM_LAST_UPDATED_SOURCE_TYPE as WM_LAST_UPDATED_SOURCE_TYPE", \
	"FIL_NEW_CHANGE_REC___WM_LAST_UPDATED_SOURCE as WM_LAST_UPDATED_SOURCE", \
	"FIL_NEW_CHANGE_REC___WM_LAST_UPDATED_TSTMP as WM_LAST_UPDATED_TSTMP", \
	"FIL_NEW_CHANGE_REC___in_UPDATE_TSTMP as in_UPDATE_TSTMP", \
	"FIL_NEW_CHANGE_REC___in_LOAD_TSTMP as in_LOAD_TSTMP", \
	"CURRENT_TIMESTAMP as Update_TSTMP_E", \
	"IF (FIL_NEW_CHANGE_REC___in_LOAD_TSTMP IS NULL, CURRENT_TIMESTAMP, FIL_NEW_CHANGE_REC___in_LOAD_TSTMP) as LOAD_TSTMP" \
)

# COMMAND ----------
# Processing node UPD_VALIDATE, type UPDATE_STRATEGY 
# COLUMN COUNT: 71

# for each involved DataFrame, append the dataframe name to each column
EXP_EVAL_VALUES_temp = EXP_EVAL_VALUES.toDF(*["EXP_EVAL_VALUES___" + col for col in EXP_EVAL_VALUES.columns])

UPD_VALIDATE = EXP_EVAL_VALUES_temp.selectExpr( \
	"EXP_EVAL_VALUES___LOCATION_ID as LOCATION_ID", \
	"EXP_EVAL_VALUES___LABOR_MSG_DTL_ID as LABOR_MSG_DTL_ID", \
	"EXP_EVAL_VALUES___LABOR_MSG_ID as LABOR_MSG_ID", \
	"EXP_EVAL_VALUES___TRAN_NBR as TRAN_NBR", \
	"EXP_EVAL_VALUES___TRAN_SEQ_NBR as TRAN_SEQ_NBR", \
	"EXP_EVAL_VALUES___MSG_STAT_CODE as MSG_STAT_CODE", \
	"EXP_EVAL_VALUES___SEQ_NBR as SEQ_NBR", \
	"EXP_EVAL_VALUES___CO as CO", \
	"EXP_EVAL_VALUES___DIV as DIV", \
	"EXP_EVAL_VALUES___START_DATE_TIME as START_DATE_TIME", \
	"EXP_EVAL_VALUES___TC_ILPN_ID as TC_ILPN_ID", \
	"EXP_EVAL_VALUES___TC_OLPN_ID as TC_OLPN_ID", \
	"EXP_EVAL_VALUES___PUTAWAY_ZONE as PUTAWAY_ZONE", \
	"EXP_EVAL_VALUES___PICK_DETERMINATION_ZONE as PICK_DETERMINATION_ZONE", \
	"EXP_EVAL_VALUES___WORK_GROUP as WORK_GROUP", \
	"EXP_EVAL_VALUES___WORK_AREA as WORK_AREA", \
	"EXP_EVAL_VALUES___PULL_ZONE as PULL_ZONE", \
	"EXP_EVAL_VALUES___ASSIGNMENT_ZONE as ASSIGNMENT_ZONE", \
	"EXP_EVAL_VALUES___RESOURCE_GROUP_ID as RESOURCE_GROUP_ID", \
	"EXP_EVAL_VALUES___LOADED_FLAG_EXP as LOADED_FLAG_EXP", \
	"EXP_EVAL_VALUES___ITEM_BAR_CODE as ITEM_BAR_CODE", \
	"EXP_EVAL_VALUES___ITEM_NAME as ITEM_NAME", \
	"EXP_EVAL_VALUES___SEC_DIM as SEC_DIM", \
	"EXP_EVAL_VALUES___WEIGHT as WEIGHT", \
	"EXP_EVAL_VALUES___VOLUME as VOLUME", \
	"EXP_EVAL_VALUES___SEASON as SEASON", \
	"EXP_EVAL_VALUES___SEASON_YR as SEASON_YR", \
	"EXP_EVAL_VALUES___STYLE as STYLE", \
	"EXP_EVAL_VALUES___STYLE_SFX as STYLE_SFX", \
	"EXP_EVAL_VALUES___COLOR as COLOR", \
	"EXP_EVAL_VALUES___COLOR_SFX as COLOR_SFX", \
	"EXP_EVAL_VALUES___PALLET_ID as PALLET_ID", \
	"EXP_EVAL_VALUES___SIZE_RNGE_CODE as SIZE_RNGE_CODE", \
	"EXP_EVAL_VALUES___SIZE_REL_POSN_IN_TABLE as SIZE_REL_POSN_IN_TABLE", \
	"EXP_EVAL_VALUES___LOCN_SLOT_TYPE as LOCN_SLOT_TYPE", \
	"EXP_EVAL_VALUES___LOCN_CLASS as LOCN_CLASS", \
	"EXP_EVAL_VALUES___LOCN_GRP_ATTR as LOCN_GRP_ATTR", \
	"EXP_EVAL_VALUES___DSP_LOCN as DSP_LOCN", \
	"EXP_EVAL_VALUES___LOCN_X_COORD as LOCN_X_COORD", \
	"EXP_EVAL_VALUES___LOCN_Y_COORD as LOCN_Y_COORD", \
	"EXP_EVAL_VALUES___LOCN_Z_COORD as LOCN_Z_COORD", \
	"EXP_EVAL_VALUES___LOCN_TRAV_AISLE as LOCN_TRAV_AISLE", \
	"EXP_EVAL_VALUES___LOCN_TRAV_ZONE as LOCN_TRAV_ZONE", \
	"EXP_EVAL_VALUES___HNDL_ATTR as HNDL_ATTR", \
	"EXP_EVAL_VALUES___HANDLING_UOM as HANDLING_UOM", \
	"EXP_EVAL_VALUES___QUAL as QUAL", \
	"EXP_EVAL_VALUES___QTY_PER_GRAB as QTY_PER_GRAB", \
	"EXP_EVAL_VALUES___QTY as QTY", \
	"EXP_EVAL_VALUES___BOX_QTY as BOX_QTY", \
	"EXP_EVAL_VALUES___INNERPACK_QTY as INNERPACK_QTY", \
	"EXP_EVAL_VALUES___PACK_QTY as PACK_QTY", \
	"EXP_EVAL_VALUES___CASE_QTY as CASE_QTY", \
	"EXP_EVAL_VALUES___TIER_QTY as TIER_QTY", \
	"EXP_EVAL_VALUES___PALLET_QTY as PALLET_QTY", \
	"EXP_EVAL_VALUES___CRIT_DIM1 as CRIT_DIM1", \
	"EXP_EVAL_VALUES___CRIT_DIM2 as CRIT_DIM2", \
	"EXP_EVAL_VALUES___CRIT_DIM3 as CRIT_DIM3", \
	"EXP_EVAL_VALUES___MISC as MISC", \
	"EXP_EVAL_VALUES___MISC_NUM_1 as MISC_NUM_1", \
	"EXP_EVAL_VALUES___MISC_NUM_2 as MISC_NUM_2", \
	"EXP_EVAL_VALUES___MISC_2 as MISC_2", \
	"EXP_EVAL_VALUES___HIBERNATE_VERSION as HIBERNATE_VERSION", \
	"EXP_EVAL_VALUES___CREATED_SOURCE_TYPE as CREATED_SOURCE_TYPE", \
	"EXP_EVAL_VALUES___CREATED_SOURCE as CREATED_SOURCE", \
	"EXP_EVAL_VALUES___CREATED_DTTM as CREATED_DTTM", \
	"EXP_EVAL_VALUES___LAST_UPDATED_SOURCE_TYPE as LAST_UPDATED_SOURCE_TYPE", \
	"EXP_EVAL_VALUES___LAST_UPDATED_SOURCE as LAST_UPDATED_SOURCE", \
	"EXP_EVAL_VALUES___LAST_UPDATED_DTTM as LAST_UPDATED_DTTM", \
	"EXP_EVAL_VALUES___Update_TSTMP_E as Update_TSTMP_E", \
	"EXP_EVAL_VALUES___LOAD_TSTMP as LOAD_TSTMP", \
	"EXP_EVAL_VALUES___WM_LABOR_MSG_DTL_ID as WM_LABOR_MSG_DTL_ID") \
	.withColumn('pyspark_data_action', when((WM_LABOR_MSG_DTL_ID.isNull()) ,(lit(0))) .otherwise(lit(1)))

# COMMAND ----------
# Processing node Shortcut_to_WM_LABOR_MSG_DTL1, type TARGET 
# COLUMN COUNT: 70


Shortcut_to_WM_LABOR_MSG_DTL1 = UPD_VALIDATE.selectExpr( \
	"CAST(LOCATION_ID AS BIGINT) as LOCATION_ID", \
	"CAST(LABOR_MSG_DTL_ID AS BIGINT) as WM_LABOR_MSG_DTL_ID", \
	"CAST(LABOR_MSG_ID AS BIGINT) as WM_LABOR_MSG_ID", \
	"CAST(TRAN_NBR AS BIGINT) as WM_TRAN_NBR", \
	"CAST(TRAN_SEQ_NBR AS BIGINT) as WM_TRAN_SEQ_NBR", \
	"CAST(MSG_STAT_CODE AS STRING) as WM_MSG_STAT_CD", \
	"CAST(SEQ_NBR AS STRING) as SEQ_NBR", \
	"CAST(CO AS STRING) as WM_COMPANY", \
	"CAST(DIV AS STRING) as WM_DIVISION", \
	"CAST(START_DATE_TIME AS TIMESTAMP) as WM_START_TSTMP", \
	"CAST(TC_ILPN_ID AS STRING) as WM_TC_ILPN_ID", \
	"CAST(TC_OLPN_ID AS STRING) as WM_TC_OLPN_ID", \
	"CAST(PUTAWAY_ZONE AS STRING) as WM_PUTAWAY_ZONE", \
	"CAST(PICK_DETERMINATION_ZONE AS STRING) as WM_PICK_DETERMINATION_ZONE", \
	"CAST(WORK_GROUP AS STRING) as WM_WORK_GROUP", \
	"CAST(WORK_AREA AS STRING) as WM_WORK_AREA", \
	"CAST(PULL_ZONE AS STRING) as WM_PULL_ZONE", \
	"CAST(ASSIGNMENT_ZONE AS STRING) as WM_ASSIGNMENT_ZONE", \
	"CAST(RESOURCE_GROUP_ID AS STRING) as WM_RESOURCE_GROUP_ID", \
	"CAST(LOADED_FLAG_EXP AS BIGINT) as LOADED_FLAG", \
	"CAST(ITEM_BAR_CODE AS STRING) as WM_ITEM_BAR_CD", \
	"CAST(ITEM_NAME AS STRING) as WM_ITEM_NAME", \
	"CAST(SEC_DIM AS STRING) as SEC_DIM", \
	"CAST(WEIGHT AS BIGINT) as WEIGHT", \
	"CAST(VOLUME AS BIGINT) as VOLUME", \
	"CAST(SEASON AS STRING) as SEASON", \
	"CAST(SEASON_YR AS STRING) as SEASON_YR", \
	"CAST(STYLE AS STRING) as STYLE", \
	"CAST(STYLE_SFX AS STRING) as STYLE_SFX", \
	"CAST(COLOR AS STRING) as COLOR", \
	"CAST(COLOR_SFX AS STRING) as COLOR_SFX", \
	"CAST(PALLET_ID AS STRING) as WM_PALLET_ID", \
	"CAST(SIZE_RNGE_CODE AS STRING) as WM_SIZE_RANGE_CD", \
	"CAST(SIZE_REL_POSN_IN_TABLE AS STRING) as SIZE_REL_POSN_IN_TABLE", \
	"CAST(LOCN_SLOT_TYPE AS STRING) as WM_LOCN_SLOT_TYPE", \
	"CAST(LOCN_CLASS AS STRING) as WM_LOCN_CLASS", \
	"CAST(LOCN_GRP_ATTR AS STRING) as WM_LOCN_GRP_ATTR", \
	"CAST(DSP_LOCN AS STRING) as DSP_LOCN", \
	"CAST(LOCN_X_COORD AS BIGINT) as LOCN_X_COORD", \
	"CAST(LOCN_Y_COORD AS BIGINT) as LOCN_Y_COORD", \
	"CAST(LOCN_Z_COORD AS BIGINT) as LOCN_Z_COORD", \
	"CAST(LOCN_TRAV_AISLE AS STRING) as LOCN_TRAV_AISLE", \
	"CAST(LOCN_TRAV_ZONE AS STRING) as LOCN_TRAV_ZONE", \
	"CAST(HNDL_ATTR AS STRING) as WM_HANDLING_ATTR", \
	"CAST(HANDLING_UOM AS STRING) as WM_HANDLING_UOM", \
	"CAST(QUAL AS STRING) as QUAL", \
	"CAST(QTY_PER_GRAB AS BIGINT) as QTY_PER_GRAB", \
	"CAST(QTY AS BIGINT) as QTY", \
	"CAST(BOX_QTY AS BIGINT) as BOX_QTY", \
	"CAST(INNERPACK_QTY AS BIGINT) as INNERPACK_QTY", \
	"CAST(PACK_QTY AS BIGINT) as PACK_QTY", \
	"CAST(CASE_QTY AS BIGINT) as CASE_QTY", \
	"CAST(TIER_QTY AS BIGINT) as TIER_QTY", \
	"CAST(PALLET_QTY AS BIGINT) as PALLET_QTY", \
	"CAST(CRIT_DIM1 AS BIGINT) as CRIT_DIM1", \
	"CAST(CRIT_DIM2 AS BIGINT) as CRIT_DIM2", \
	"CAST(CRIT_DIM3 AS BIGINT) as CRIT_DIM3", \
	"CAST(MISC AS STRING) as MISC", \
	"CAST(MISC_2 AS STRING) as MISC_2", \
	"CAST(MISC_NUM_1 AS BIGINT) as MISC_NUM_1", \
	"CAST(MISC_NUM_2 AS BIGINT) as MISC_NUM_2", \
	"CAST(HIBERNATE_VERSION AS BIGINT) as WM_HIBERNATE_VERSION", \
	"CAST(CREATED_SOURCE_TYPE AS BIGINT) as WM_CREATED_SOURCE_TYPE", \
	"CAST(CREATED_SOURCE AS STRING) as WM_CREATED_SOURCE", \
	"CAST(CREATED_DTTM AS TIMESTAMP) as WM_CREATED_TSTMP", \
	"CAST(LAST_UPDATED_SOURCE_TYPE AS BIGINT) as WM_LAST_UPDATED_SOURCE_TYPE", \
	"CAST(LAST_UPDATED_SOURCE AS STRING) as WM_LAST_UPDATED_SOURCE", \
	"CAST(LAST_UPDATED_DTTM AS TIMESTAMP) as WM_LAST_UPDATED_TSTMP", \
	"CAST(Update_TSTMP_E AS TIMESTAMP) as UPDATE_TSTMP", \
	"CAST(LOAD_TSTMP AS TIMESTAMP) as LOAD_TSTMP" \
)
Shortcut_to_WM_LABOR_MSG_DTL1.write.saveAsTable(f'{raw}.WM_LABOR_MSG_DTL')