#Code converted on 2023-06-21 18:43:46
import os
import argparse
from pyspark.sql import *
from pyspark.sql.functions import *
from pyspark.sql.window import Window
from pyspark.sql.types import *
from datetime import datetime
from pyspark.dbutils import DBUtils
from Datalake.utils.genericUtilities import *
from Datalake.utils.configs import *
from Datalake.utils.mergeUtils import *
from Datalake.utils.logger import *

# COMMAND ----------

parser = argparse.ArgumentParser()
spark = SparkSession.getActiveSession()
dbutils = DBUtils(spark)

parser.add_argument('env', type=str, help='Env Variable')
args = parser.parse_args()
env = args.env
#                                                                                                                                     env = 'dev'

if env is None or env == '':
    raise ValueError('env is not set')

refine = getEnvPrefix(env) + 'refine'
raw = getEnvPrefix(env) + 'raw'
legacy = getEnvPrefix(env) + 'legacy'

# Set global variables
starttime = datetime.now() #start timestamp of the scriptstarttime = datetime.now() #start timestamp of the script
refined_perf_table = f"{refine}.WM_ITEM_CBO"
raw_perf_table = f"{raw}.WM_ITEM_CBO_PRE"
site_profile_table = f"{legacy}.SITE_PROFILE"


# COMMAND ----------
# Processing node SQ_Shortcut_to_WM_ITEM_CBO_PRE, type SOURCE 
# COLUMN COUNT: 105

SQ_Shortcut_to_WM_ITEM_CBO_PRE = spark.sql(f"""SELECT
DC_NBR,
ITEM_ID,
COMPANY_ID,
ITEM_NAME,
DESCRIPTION,
PROTECTION_LEVEL_ID,
COMMODITY_CLASS_ID,
COMMODITY_CODE_ID,
PRODUCT_CLASS_ID,
UN_NUMBER_ID,
BASE_STORAGE_UOM_ID,
ITEM_SEASON,
ITEM_SEASON_YEAR,
ITEM_STYLE,
ITEM_STYLE_SFX,
ITEM_COLOR,
ITEM_COLOR_SFX,
ITEM_SECOND_DIM,
ITEM_QUALITY,
ITEM_SIZE_DESC,
ITEM_BAR_CODE,
ITEM_DESC_SHORT,
ITEM_UPC_GTIN,
UNIT_WEIGHT,
WEIGHT_UOM_ID,
UNIT_VOLUME,
VOLUME_UOM_ID,
UNIT_HEIGHT,
UNIT_WIDTH,
UNIT_LENGTH,
DIMENSION_UOM_ID,
VARIABLE_WEIGHT,
DATABASE_QTY_UOM_ID,
DISPLAY_QTY_UOM_ID,
STATUS_CODE,
ITEM_IMAGE_FILENAME,
AUDIT_CREATED_SOURCE,
AUDIT_CREATED_SOURCE_TYPE,
AUDIT_CREATED_DTTM,
AUDIT_LAST_UPDATED_SOURCE,
AUDIT_LAST_UPDATED_SOURCE_TYPE,
AUDIT_LAST_UPDATED_DTTM,
MARK_FOR_DELETION,
CATCH_WEIGHT_ITEM,
COMMODITY_LEVEL_DESC,
CHANNEL_TYPE_ID,
COLOR_DESC,
VERSION,
ITEM_QUALITY_CODE,
PROD_TYPE,
STD_BUNDL_QTY,
STAB_CODE,
ITEM_ORIENTATION,
PROTN_FACTOR,
CAVITY_LEN,
CAVITY_WD,
CAVITY_HT,
INCREMENTAL_LEN,
INCREMENTAL_WD,
INCREMENTAL_HT,
STACKABLE_ITEM,
MAX_NEST_NUMBER,
STCC_CODE_ID,
SITC_CODE_ID,
SCHEDULE_B_CODE_ID,
SOLD_ONLINE,
SOLD_IN_STORES,
PICKUP_AT_STORE,
SHIP_TO_STORE,
URL,
IS_RETURNABLE,
REF_FIELD1,
REF_FIELD2,
REF_FIELD3,
REF_FIELD4,
REF_FIELD5,
CUBISCAN_LAST_UPDATED_DTTM,
IS_EXCHANGEABLE,
LONG_DESCRIPTION,
MIN_SHIP_INNER_UOM_ID,
PRICE_STATUS,
SELL_THROUGH,
COMMERCE_ATTRIBUTE1,
COMMERCE_ATTRIBUTE2,
COMMERCE_NUM_ATTRIBUTE1,
COMMERCE_NUM_ATTRIBUTE2,
COMMERCE_DATE_ATTRIBUTE1,
BRAND,
ITEM_DISPOSITION,
CREATED_DTTM,
LAST_UPDATED_DTTM,
REF_FIELD6,
REF_FIELD7,
REF_FIELD8,
REF_FIELD9,
REF_FIELD10,
REF_NUM1,
REF_NUM2,
REF_NUM3,
REF_NUM4,
REF_NUM5,
SIZE_SEQ,
COLOR_SEQ,
RETURNABLE_AT_STORE,
GIFT_CARD_TYPE
FROM {raw_perf_table}""").withColumn("sys_row_id", monotonically_increasing_id())

# COMMAND ----------
# Processing node SQ_Shortcut_to_WM_ITEM_CBO, type SOURCE 
# COLUMN COUNT: 7

SQ_Shortcut_to_WM_ITEM_CBO = spark.sql(f"""SELECT
LOCATION_ID,
WM_ITEM_ID,
WM_AUDIT_CREATED_TSTMP,
WM_AUDIT_LAST_UPDATED_TSTMP,
WM_CREATED_TSTMP,
WM_LAST_UPDATED_TSTMP,
LOAD_TSTMP
FROM {refined_perf_table}
WHERE WM_ITEM_ID IN (SELECT ITEM_ID FROM {raw_perf_table})""").withColumn("sys_row_id", monotonically_increasing_id())

# COMMAND ----------
# Processing node EXP_INT_CONVERSION, type EXPRESSION 
# COLUMN COUNT: 105

# for each involved DataFrame, append the dataframe name to each column
SQ_Shortcut_to_WM_ITEM_CBO_PRE_temp = SQ_Shortcut_to_WM_ITEM_CBO_PRE.toDF(*["SQ_Shortcut_to_WM_ITEM_CBO_PRE___" + col for col in SQ_Shortcut_to_WM_ITEM_CBO_PRE.columns])

EXP_INT_CONVERSION = SQ_Shortcut_to_WM_ITEM_CBO_PRE_temp.selectExpr( \
	"SQ_Shortcut_to_WM_ITEM_CBO_PRE___sys_row_id as sys_row_id", \
	"cast(SQ_Shortcut_to_WM_ITEM_CBO_PRE___DC_NBR as int) as o_DC_NBR", \
	"SQ_Shortcut_to_WM_ITEM_CBO_PRE___ITEM_ID as ITEM_ID", \
	"SQ_Shortcut_to_WM_ITEM_CBO_PRE___COMPANY_ID as COMPANY_ID", \
	"SQ_Shortcut_to_WM_ITEM_CBO_PRE___ITEM_NAME as ITEM_NAME", \
	"SQ_Shortcut_to_WM_ITEM_CBO_PRE___DESCRIPTION as DESCRIPTION", \
	"SQ_Shortcut_to_WM_ITEM_CBO_PRE___PROTECTION_LEVEL_ID as PROTECTION_LEVEL_ID", \
	"SQ_Shortcut_to_WM_ITEM_CBO_PRE___COMMODITY_CLASS_ID as COMMODITY_CLASS_ID", \
	"SQ_Shortcut_to_WM_ITEM_CBO_PRE___COMMODITY_CODE_ID as COMMODITY_CODE_ID", \
	"SQ_Shortcut_to_WM_ITEM_CBO_PRE___PRODUCT_CLASS_ID as PRODUCT_CLASS_ID", \
	"SQ_Shortcut_to_WM_ITEM_CBO_PRE___UN_NUMBER_ID as UN_NUMBER_ID", \
	"SQ_Shortcut_to_WM_ITEM_CBO_PRE___BASE_STORAGE_UOM_ID as BASE_STORAGE_UOM_ID", \
	"SQ_Shortcut_to_WM_ITEM_CBO_PRE___ITEM_SEASON as ITEM_SEASON", \
	"SQ_Shortcut_to_WM_ITEM_CBO_PRE___ITEM_SEASON_YEAR as ITEM_SEASON_YEAR", \
	"SQ_Shortcut_to_WM_ITEM_CBO_PRE___ITEM_STYLE as ITEM_STYLE", \
	"SQ_Shortcut_to_WM_ITEM_CBO_PRE___ITEM_STYLE_SFX as ITEM_STYLE_SFX", \
	"SQ_Shortcut_to_WM_ITEM_CBO_PRE___ITEM_COLOR as ITEM_COLOR", \
	"SQ_Shortcut_to_WM_ITEM_CBO_PRE___ITEM_COLOR_SFX as ITEM_COLOR_SFX", \
	"SQ_Shortcut_to_WM_ITEM_CBO_PRE___ITEM_SECOND_DIM as ITEM_SECOND_DIM", \
	"SQ_Shortcut_to_WM_ITEM_CBO_PRE___ITEM_QUALITY as ITEM_QUALITY", \
	"SQ_Shortcut_to_WM_ITEM_CBO_PRE___ITEM_SIZE_DESC as ITEM_SIZE_DESC", \
	"SQ_Shortcut_to_WM_ITEM_CBO_PRE___ITEM_BAR_CODE as ITEM_BAR_CODE", \
	"SQ_Shortcut_to_WM_ITEM_CBO_PRE___ITEM_DESC_SHORT as ITEM_DESC_SHORT", \
	"SQ_Shortcut_to_WM_ITEM_CBO_PRE___ITEM_UPC_GTIN as ITEM_UPC_GTIN", \
	"SQ_Shortcut_to_WM_ITEM_CBO_PRE___UNIT_WEIGHT as UNIT_WEIGHT", \
	"SQ_Shortcut_to_WM_ITEM_CBO_PRE___WEIGHT_UOM_ID as WEIGHT_UOM_ID", \
	"SQ_Shortcut_to_WM_ITEM_CBO_PRE___UNIT_VOLUME as UNIT_VOLUME", \
	"SQ_Shortcut_to_WM_ITEM_CBO_PRE___VOLUME_UOM_ID as VOLUME_UOM_ID", \
	"SQ_Shortcut_to_WM_ITEM_CBO_PRE___UNIT_HEIGHT as UNIT_HEIGHT", \
	"SQ_Shortcut_to_WM_ITEM_CBO_PRE___UNIT_WIDTH as UNIT_WIDTH", \
	"SQ_Shortcut_to_WM_ITEM_CBO_PRE___UNIT_LENGTH as UNIT_LENGTH", \
	"SQ_Shortcut_to_WM_ITEM_CBO_PRE___DIMENSION_UOM_ID as DIMENSION_UOM_ID", \
	"SQ_Shortcut_to_WM_ITEM_CBO_PRE___VARIABLE_WEIGHT as VARIABLE_WEIGHT", \
	"SQ_Shortcut_to_WM_ITEM_CBO_PRE___DATABASE_QTY_UOM_ID as DATABASE_QTY_UOM_ID", \
	"SQ_Shortcut_to_WM_ITEM_CBO_PRE___DISPLAY_QTY_UOM_ID as DISPLAY_QTY_UOM_ID", \
	"SQ_Shortcut_to_WM_ITEM_CBO_PRE___STATUS_CODE as STATUS_CODE", \
	"SQ_Shortcut_to_WM_ITEM_CBO_PRE___ITEM_IMAGE_FILENAME as ITEM_IMAGE_FILENAME", \
	"SQ_Shortcut_to_WM_ITEM_CBO_PRE___AUDIT_CREATED_SOURCE as AUDIT_CREATED_SOURCE", \
	"SQ_Shortcut_to_WM_ITEM_CBO_PRE___AUDIT_CREATED_SOURCE_TYPE as AUDIT_CREATED_SOURCE_TYPE", \
	"SQ_Shortcut_to_WM_ITEM_CBO_PRE___AUDIT_CREATED_DTTM as AUDIT_CREATED_DTTM", \
	"SQ_Shortcut_to_WM_ITEM_CBO_PRE___AUDIT_LAST_UPDATED_SOURCE as AUDIT_LAST_UPDATED_SOURCE", \
	"SQ_Shortcut_to_WM_ITEM_CBO_PRE___AUDIT_LAST_UPDATED_SOURCE_TYPE as AUDIT_LAST_UPDATED_SOURCE_TYPE", \
	"SQ_Shortcut_to_WM_ITEM_CBO_PRE___AUDIT_LAST_UPDATED_DTTM as AUDIT_LAST_UPDATED_DTTM", \
	"SQ_Shortcut_to_WM_ITEM_CBO_PRE___MARK_FOR_DELETION as MARK_FOR_DELETION", \
	"SQ_Shortcut_to_WM_ITEM_CBO_PRE___CATCH_WEIGHT_ITEM as CATCH_WEIGHT_ITEM", \
	"SQ_Shortcut_to_WM_ITEM_CBO_PRE___COMMODITY_LEVEL_DESC as COMMODITY_LEVEL_DESC", \
	"SQ_Shortcut_to_WM_ITEM_CBO_PRE___CHANNEL_TYPE_ID as CHANNEL_TYPE_ID", \
	"SQ_Shortcut_to_WM_ITEM_CBO_PRE___COLOR_DESC as COLOR_DESC", \
	"SQ_Shortcut_to_WM_ITEM_CBO_PRE___VERSION as VERSION", \
	"SQ_Shortcut_to_WM_ITEM_CBO_PRE___ITEM_QUALITY_CODE as ITEM_QUALITY_CODE", \
	"SQ_Shortcut_to_WM_ITEM_CBO_PRE___PROD_TYPE as PROD_TYPE", \
	"SQ_Shortcut_to_WM_ITEM_CBO_PRE___STD_BUNDL_QTY as STD_BUNDL_QTY", \
	"SQ_Shortcut_to_WM_ITEM_CBO_PRE___STAB_CODE as STAB_CODE", \
	"SQ_Shortcut_to_WM_ITEM_CBO_PRE___ITEM_ORIENTATION as ITEM_ORIENTATION", \
	"SQ_Shortcut_to_WM_ITEM_CBO_PRE___PROTN_FACTOR as PROTN_FACTOR", \
	"SQ_Shortcut_to_WM_ITEM_CBO_PRE___CAVITY_LEN as CAVITY_LEN", \
	"SQ_Shortcut_to_WM_ITEM_CBO_PRE___CAVITY_WD as CAVITY_WD", \
	"SQ_Shortcut_to_WM_ITEM_CBO_PRE___CAVITY_HT as CAVITY_HT", \
	"SQ_Shortcut_to_WM_ITEM_CBO_PRE___INCREMENTAL_LEN as INCREMENTAL_LEN", \
	"SQ_Shortcut_to_WM_ITEM_CBO_PRE___INCREMENTAL_WD as INCREMENTAL_WD", \
	"SQ_Shortcut_to_WM_ITEM_CBO_PRE___INCREMENTAL_HT as INCREMENTAL_HT", \
	"SQ_Shortcut_to_WM_ITEM_CBO_PRE___STACKABLE_ITEM as STACKABLE_ITEM", \
	"SQ_Shortcut_to_WM_ITEM_CBO_PRE___MAX_NEST_NUMBER as MAX_NEST_NUMBER", \
	"SQ_Shortcut_to_WM_ITEM_CBO_PRE___STCC_CODE_ID as STCC_CODE_ID", \
	"SQ_Shortcut_to_WM_ITEM_CBO_PRE___SITC_CODE_ID as SITC_CODE_ID", \
	"SQ_Shortcut_to_WM_ITEM_CBO_PRE___SCHEDULE_B_CODE_ID as SCHEDULE_B_CODE_ID", \
	"SQ_Shortcut_to_WM_ITEM_CBO_PRE___SOLD_ONLINE as SOLD_ONLINE", \
	"SQ_Shortcut_to_WM_ITEM_CBO_PRE___SOLD_IN_STORES as SOLD_IN_STORES", \
	"SQ_Shortcut_to_WM_ITEM_CBO_PRE___PICKUP_AT_STORE as PICKUP_AT_STORE", \
	"SQ_Shortcut_to_WM_ITEM_CBO_PRE___SHIP_TO_STORE as SHIP_TO_STORE", \
	"SQ_Shortcut_to_WM_ITEM_CBO_PRE___URL as URL", \
	"SQ_Shortcut_to_WM_ITEM_CBO_PRE___IS_RETURNABLE as IS_RETURNABLE", \
	"SQ_Shortcut_to_WM_ITEM_CBO_PRE___REF_FIELD1 as REF_FIELD1", \
	"SQ_Shortcut_to_WM_ITEM_CBO_PRE___REF_FIELD2 as REF_FIELD2", \
	"SQ_Shortcut_to_WM_ITEM_CBO_PRE___REF_FIELD3 as REF_FIELD3", \
	"SQ_Shortcut_to_WM_ITEM_CBO_PRE___REF_FIELD4 as REF_FIELD4", \
	"SQ_Shortcut_to_WM_ITEM_CBO_PRE___REF_FIELD5 as REF_FIELD5", \
	"SQ_Shortcut_to_WM_ITEM_CBO_PRE___CUBISCAN_LAST_UPDATED_DTTM as CUBISCAN_LAST_UPDATED_DTTM", \
	"SQ_Shortcut_to_WM_ITEM_CBO_PRE___IS_EXCHANGEABLE as IS_EXCHANGEABLE", \
	"SQ_Shortcut_to_WM_ITEM_CBO_PRE___LONG_DESCRIPTION as LONG_DESCRIPTION", \
	"SQ_Shortcut_to_WM_ITEM_CBO_PRE___MIN_SHIP_INNER_UOM_ID as MIN_SHIP_INNER_UOM_ID", \
	"SQ_Shortcut_to_WM_ITEM_CBO_PRE___PRICE_STATUS as PRICE_STATUS", \
	"SQ_Shortcut_to_WM_ITEM_CBO_PRE___SELL_THROUGH as SELL_THROUGH", \
	"SQ_Shortcut_to_WM_ITEM_CBO_PRE___COMMERCE_ATTRIBUTE1 as COMMERCE_ATTRIBUTE1", \
	"SQ_Shortcut_to_WM_ITEM_CBO_PRE___COMMERCE_ATTRIBUTE2 as COMMERCE_ATTRIBUTE2", \
	"SQ_Shortcut_to_WM_ITEM_CBO_PRE___COMMERCE_NUM_ATTRIBUTE1 as COMMERCE_NUM_ATTRIBUTE1", \
	"SQ_Shortcut_to_WM_ITEM_CBO_PRE___COMMERCE_NUM_ATTRIBUTE2 as COMMERCE_NUM_ATTRIBUTE2", \
	"SQ_Shortcut_to_WM_ITEM_CBO_PRE___COMMERCE_DATE_ATTRIBUTE1 as COMMERCE_DATE_ATTRIBUTE1", \
	"SQ_Shortcut_to_WM_ITEM_CBO_PRE___BRAND as BRAND", \
	"SQ_Shortcut_to_WM_ITEM_CBO_PRE___ITEM_DISPOSITION as ITEM_DISPOSITION", \
	"SQ_Shortcut_to_WM_ITEM_CBO_PRE___CREATED_DTTM as CREATED_DTTM", \
	"SQ_Shortcut_to_WM_ITEM_CBO_PRE___LAST_UPDATED_DTTM as LAST_UPDATED_DTTM", \
	"SQ_Shortcut_to_WM_ITEM_CBO_PRE___REF_FIELD6 as REF_FIELD6", \
	"SQ_Shortcut_to_WM_ITEM_CBO_PRE___REF_FIELD7 as REF_FIELD7", \
	"SQ_Shortcut_to_WM_ITEM_CBO_PRE___REF_FIELD8 as REF_FIELD8", \
	"SQ_Shortcut_to_WM_ITEM_CBO_PRE___REF_FIELD9 as REF_FIELD9", \
	"SQ_Shortcut_to_WM_ITEM_CBO_PRE___REF_FIELD10 as REF_FIELD10", \
	"SQ_Shortcut_to_WM_ITEM_CBO_PRE___REF_NUM1 as REF_NUM1", \
	"SQ_Shortcut_to_WM_ITEM_CBO_PRE___REF_NUM2 as REF_NUM2", \
	"SQ_Shortcut_to_WM_ITEM_CBO_PRE___REF_NUM3 as REF_NUM3", \
	"SQ_Shortcut_to_WM_ITEM_CBO_PRE___REF_NUM4 as REF_NUM4", \
	"SQ_Shortcut_to_WM_ITEM_CBO_PRE___REF_NUM5 as REF_NUM5", \
	"SQ_Shortcut_to_WM_ITEM_CBO_PRE___SIZE_SEQ as SIZE_SEQ", \
	"SQ_Shortcut_to_WM_ITEM_CBO_PRE___COLOR_SEQ as COLOR_SEQ", \
	"SQ_Shortcut_to_WM_ITEM_CBO_PRE___RETURNABLE_AT_STORE as RETURNABLE_AT_STORE", \
	"SQ_Shortcut_to_WM_ITEM_CBO_PRE___GIFT_CARD_TYPE as GIFT_CARD_TYPE" \
)

# COMMAND ----------
# Processing node SQ_Shortcut_to_SITE_PROFILE, type SOURCE 
# COLUMN COUNT: 2

SQ_Shortcut_to_SITE_PROFILE = spark.sql(f"""SELECT LOCATION_ID, STORE_NBR FROM {site_profile_table}""").withColumn("sys_row_id", monotonically_increasing_id())

# COMMAND ----------
# Processing node JNR_SITE_PROFILE, type JOINER 
# COLUMN COUNT: 107

JNR_SITE_PROFILE = SQ_Shortcut_to_SITE_PROFILE.join(EXP_INT_CONVERSION,[SQ_Shortcut_to_SITE_PROFILE.STORE_NBR == EXP_INT_CONVERSION.o_DC_NBR],'inner')

# COMMAND ----------
# Processing node JNR_WM_ITEM_CBO, type JOINER . Note: using additional SELECT to rename incoming columns
# COLUMN COUNT: 112

# for each involved DataFrame, append the dataframe name to each column
SQ_Shortcut_to_WM_ITEM_CBO_temp = SQ_Shortcut_to_WM_ITEM_CBO.toDF(*["SQ_Shortcut_to_WM_ITEM_CBO___" + col for col in SQ_Shortcut_to_WM_ITEM_CBO.columns])
JNR_SITE_PROFILE_temp = JNR_SITE_PROFILE.toDF(*["JNR_SITE_PROFILE___" + col for col in JNR_SITE_PROFILE.columns])

JNR_WM_ITEM_CBO = SQ_Shortcut_to_WM_ITEM_CBO_temp.join(JNR_SITE_PROFILE_temp,[SQ_Shortcut_to_WM_ITEM_CBO_temp.SQ_Shortcut_to_WM_ITEM_CBO___LOCATION_ID == JNR_SITE_PROFILE_temp.JNR_SITE_PROFILE___LOCATION_ID, SQ_Shortcut_to_WM_ITEM_CBO_temp.SQ_Shortcut_to_WM_ITEM_CBO___WM_ITEM_ID == JNR_SITE_PROFILE_temp.JNR_SITE_PROFILE___ITEM_ID],'right_outer').selectExpr( \
	"JNR_SITE_PROFILE___LOCATION_ID as LOCATION_ID", \
	"JNR_SITE_PROFILE___ITEM_ID as ITEM_ID", \
	"JNR_SITE_PROFILE___COMPANY_ID as COMPANY_ID", \
	"JNR_SITE_PROFILE___ITEM_NAME as ITEM_NAME", \
	"JNR_SITE_PROFILE___DESCRIPTION as DESCRIPTION", \
	"JNR_SITE_PROFILE___PROTECTION_LEVEL_ID as PROTECTION_LEVEL_ID", \
	"JNR_SITE_PROFILE___COMMODITY_CLASS_ID as COMMODITY_CLASS_ID", \
	"JNR_SITE_PROFILE___COMMODITY_CODE_ID as COMMODITY_CODE_ID", \
	"JNR_SITE_PROFILE___PRODUCT_CLASS_ID as PRODUCT_CLASS_ID", \
	"JNR_SITE_PROFILE___UN_NUMBER_ID as UN_NUMBER_ID", \
	"JNR_SITE_PROFILE___BASE_STORAGE_UOM_ID as BASE_STORAGE_UOM_ID", \
	"JNR_SITE_PROFILE___ITEM_SEASON as ITEM_SEASON", \
	"JNR_SITE_PROFILE___ITEM_SEASON_YEAR as ITEM_SEASON_YEAR", \
	"JNR_SITE_PROFILE___ITEM_STYLE as ITEM_STYLE", \
	"JNR_SITE_PROFILE___ITEM_STYLE_SFX as ITEM_STYLE_SFX", \
	"JNR_SITE_PROFILE___ITEM_COLOR as ITEM_COLOR", \
	"JNR_SITE_PROFILE___ITEM_COLOR_SFX as ITEM_COLOR_SFX", \
	"JNR_SITE_PROFILE___ITEM_SECOND_DIM as ITEM_SECOND_DIM", \
	"JNR_SITE_PROFILE___ITEM_QUALITY as ITEM_QUALITY", \
	"JNR_SITE_PROFILE___ITEM_SIZE_DESC as ITEM_SIZE_DESC", \
	"JNR_SITE_PROFILE___ITEM_BAR_CODE as ITEM_BAR_CODE", \
	"JNR_SITE_PROFILE___ITEM_DESC_SHORT as ITEM_DESC_SHORT", \
	"JNR_SITE_PROFILE___ITEM_UPC_GTIN as ITEM_UPC_GTIN", \
	"JNR_SITE_PROFILE___UNIT_WEIGHT as UNIT_WEIGHT", \
	"JNR_SITE_PROFILE___WEIGHT_UOM_ID as WEIGHT_UOM_ID", \
	"JNR_SITE_PROFILE___UNIT_VOLUME as UNIT_VOLUME", \
	"JNR_SITE_PROFILE___VOLUME_UOM_ID as VOLUME_UOM_ID", \
	"JNR_SITE_PROFILE___UNIT_HEIGHT as UNIT_HEIGHT", \
	"JNR_SITE_PROFILE___UNIT_WIDTH as UNIT_WIDTH", \
	"JNR_SITE_PROFILE___UNIT_LENGTH as UNIT_LENGTH", \
	"JNR_SITE_PROFILE___DIMENSION_UOM_ID as DIMENSION_UOM_ID", \
	"JNR_SITE_PROFILE___VARIABLE_WEIGHT as VARIABLE_WEIGHT", \
	"JNR_SITE_PROFILE___DATABASE_QTY_UOM_ID as DATABASE_QTY_UOM_ID", \
	"JNR_SITE_PROFILE___DISPLAY_QTY_UOM_ID as DISPLAY_QTY_UOM_ID", \
	"JNR_SITE_PROFILE___STATUS_CODE as STATUS_CODE", \
	"JNR_SITE_PROFILE___ITEM_IMAGE_FILENAME as ITEM_IMAGE_FILENAME", \
	"JNR_SITE_PROFILE___AUDIT_CREATED_SOURCE as AUDIT_CREATED_SOURCE", \
	"JNR_SITE_PROFILE___AUDIT_CREATED_SOURCE_TYPE as AUDIT_CREATED_SOURCE_TYPE", \
	"JNR_SITE_PROFILE___AUDIT_CREATED_DTTM as AUDIT_CREATED_DTTM", \
	"JNR_SITE_PROFILE___AUDIT_LAST_UPDATED_SOURCE as AUDIT_LAST_UPDATED_SOURCE", \
	"JNR_SITE_PROFILE___AUDIT_LAST_UPDATED_SOURCE_TYPE as AUDIT_LAST_UPDATED_SOURCE_TYPE", \
	"JNR_SITE_PROFILE___AUDIT_LAST_UPDATED_DTTM as AUDIT_LAST_UPDATED_DTTM", \
	"JNR_SITE_PROFILE___MARK_FOR_DELETION as MARK_FOR_DELETION", \
	"JNR_SITE_PROFILE___CATCH_WEIGHT_ITEM as CATCH_WEIGHT_ITEM", \
	"JNR_SITE_PROFILE___COMMODITY_LEVEL_DESC as COMMODITY_LEVEL_DESC", \
	"JNR_SITE_PROFILE___CHANNEL_TYPE_ID as CHANNEL_TYPE_ID", \
	"JNR_SITE_PROFILE___COLOR_DESC as COLOR_DESC", \
	"JNR_SITE_PROFILE___VERSION as VERSION", \
	"JNR_SITE_PROFILE___ITEM_QUALITY_CODE as ITEM_QUALITY_CODE", \
	"JNR_SITE_PROFILE___PROD_TYPE as PROD_TYPE", \
	"JNR_SITE_PROFILE___STD_BUNDL_QTY as STD_BUNDL_QTY", \
	"JNR_SITE_PROFILE___STAB_CODE as STAB_CODE", \
	"JNR_SITE_PROFILE___ITEM_ORIENTATION as ITEM_ORIENTATION", \
	"JNR_SITE_PROFILE___PROTN_FACTOR as PROTN_FACTOR", \
	"JNR_SITE_PROFILE___CAVITY_LEN as CAVITY_LEN", \
	"JNR_SITE_PROFILE___CAVITY_WD as CAVITY_WD", \
	"JNR_SITE_PROFILE___CAVITY_HT as CAVITY_HT", \
	"JNR_SITE_PROFILE___INCREMENTAL_LEN as INCREMENTAL_LEN", \
	"JNR_SITE_PROFILE___INCREMENTAL_WD as INCREMENTAL_WD", \
	"JNR_SITE_PROFILE___INCREMENTAL_HT as INCREMENTAL_HT", \
	"JNR_SITE_PROFILE___STACKABLE_ITEM as STACKABLE_ITEM", \
	"JNR_SITE_PROFILE___MAX_NEST_NUMBER as MAX_NEST_NUMBER", \
	"JNR_SITE_PROFILE___STCC_CODE_ID as STCC_CODE_ID", \
	"JNR_SITE_PROFILE___SITC_CODE_ID as SITC_CODE_ID", \
	"JNR_SITE_PROFILE___SCHEDULE_B_CODE_ID as SCHEDULE_B_CODE_ID", \
	"JNR_SITE_PROFILE___SOLD_ONLINE as SOLD_ONLINE", \
	"JNR_SITE_PROFILE___SOLD_IN_STORES as SOLD_IN_STORES", \
	"JNR_SITE_PROFILE___PICKUP_AT_STORE as PICKUP_AT_STORE", \
	"JNR_SITE_PROFILE___SHIP_TO_STORE as SHIP_TO_STORE", \
	"JNR_SITE_PROFILE___URL as URL", \
	"JNR_SITE_PROFILE___IS_RETURNABLE as IS_RETURNABLE", \
	"JNR_SITE_PROFILE___REF_FIELD1 as REF_FIELD1", \
	"JNR_SITE_PROFILE___REF_FIELD2 as REF_FIELD2", \
	"JNR_SITE_PROFILE___REF_FIELD3 as REF_FIELD3", \
	"JNR_SITE_PROFILE___REF_FIELD4 as REF_FIELD4", \
	"JNR_SITE_PROFILE___REF_FIELD5 as REF_FIELD5", \
	"JNR_SITE_PROFILE___CUBISCAN_LAST_UPDATED_DTTM as CUBISCAN_LAST_UPDATED_DTTM", \
	"JNR_SITE_PROFILE___IS_EXCHANGEABLE as IS_EXCHANGEABLE", \
	"JNR_SITE_PROFILE___LONG_DESCRIPTION as LONG_DESCRIPTION", \
	"JNR_SITE_PROFILE___MIN_SHIP_INNER_UOM_ID as MIN_SHIP_INNER_UOM_ID", \
	"JNR_SITE_PROFILE___PRICE_STATUS as PRICE_STATUS", \
	"JNR_SITE_PROFILE___SELL_THROUGH as SELL_THROUGH", \
	"JNR_SITE_PROFILE___COMMERCE_ATTRIBUTE1 as COMMERCE_ATTRIBUTE1", \
	"JNR_SITE_PROFILE___COMMERCE_ATTRIBUTE2 as COMMERCE_ATTRIBUTE2", \
	"JNR_SITE_PROFILE___COMMERCE_NUM_ATTRIBUTE1 as COMMERCE_NUM_ATTRIBUTE1", \
	"JNR_SITE_PROFILE___COMMERCE_NUM_ATTRIBUTE2 as COMMERCE_NUM_ATTRIBUTE2", \
	"JNR_SITE_PROFILE___COMMERCE_DATE_ATTRIBUTE1 as COMMERCE_DATE_ATTRIBUTE1", \
	"JNR_SITE_PROFILE___BRAND as BRAND", \
	"JNR_SITE_PROFILE___ITEM_DISPOSITION as ITEM_DISPOSITION", \
	"JNR_SITE_PROFILE___CREATED_DTTM as CREATED_DTTM", \
	"JNR_SITE_PROFILE___LAST_UPDATED_DTTM as LAST_UPDATED_DTTM", \
	"JNR_SITE_PROFILE___REF_FIELD6 as REF_FIELD6", \
	"JNR_SITE_PROFILE___REF_FIELD7 as REF_FIELD7", \
	"JNR_SITE_PROFILE___REF_FIELD8 as REF_FIELD8", \
	"JNR_SITE_PROFILE___REF_FIELD9 as REF_FIELD9", \
	"JNR_SITE_PROFILE___REF_FIELD10 as REF_FIELD10", \
	"JNR_SITE_PROFILE___REF_NUM1 as REF_NUM1", \
	"JNR_SITE_PROFILE___REF_NUM2 as REF_NUM2", \
	"JNR_SITE_PROFILE___REF_NUM3 as REF_NUM3", \
	"JNR_SITE_PROFILE___REF_NUM4 as REF_NUM4", \
	"JNR_SITE_PROFILE___REF_NUM5 as REF_NUM5", \
	"JNR_SITE_PROFILE___SIZE_SEQ as SIZE_SEQ", \
	"JNR_SITE_PROFILE___COLOR_SEQ as COLOR_SEQ", \
	"JNR_SITE_PROFILE___RETURNABLE_AT_STORE as RETURNABLE_AT_STORE", \
	"JNR_SITE_PROFILE___GIFT_CARD_TYPE as GIFT_CARD_TYPE", \
	"SQ_Shortcut_to_WM_ITEM_CBO___LOCATION_ID as i_LOCATION_ID", \
	"SQ_Shortcut_to_WM_ITEM_CBO___WM_ITEM_ID as i_WM_ITEM_ID", \
	"SQ_Shortcut_to_WM_ITEM_CBO___WM_AUDIT_CREATED_TSTMP as i_WM_AUDIT_CREATED_TSTMP", \
	"SQ_Shortcut_to_WM_ITEM_CBO___WM_AUDIT_LAST_UPDATED_TSTMP as i_WM_AUDIT_LAST_UPDATED_TSTMP", \
	"SQ_Shortcut_to_WM_ITEM_CBO___WM_CREATED_TSTMP as i_WM_CREATED_TSTMP", \
	"SQ_Shortcut_to_WM_ITEM_CBO___WM_LAST_UPDATED_TSTMP as i_WM_LAST_UPDATED_TSTMP", \
	"SQ_Shortcut_to_WM_ITEM_CBO___LOAD_TSTMP as i_LOAD_TSTMP")

# COMMAND ----------
# Processing node FIL_UNCHANGED_RECORDS, type FILTER 
# COLUMN COUNT: 111

# for each involved DataFrame, append the dataframe name to each column
JNR_WM_ITEM_CBO_temp = JNR_WM_ITEM_CBO.toDF(*["JNR_WM_ITEM_CBO___" + col for col in JNR_WM_ITEM_CBO.columns])

FIL_UNCHANGED_RECORDS = JNR_WM_ITEM_CBO_temp.selectExpr( \
	"JNR_WM_ITEM_CBO___LOCATION_ID as LOCATION_ID", \
	"JNR_WM_ITEM_CBO___ITEM_ID as ITEM_ID", \
	"JNR_WM_ITEM_CBO___COMPANY_ID as COMPANY_ID", \
	"JNR_WM_ITEM_CBO___ITEM_NAME as ITEM_NAME", \
	"JNR_WM_ITEM_CBO___DESCRIPTION as DESCRIPTION", \
	"JNR_WM_ITEM_CBO___PROTECTION_LEVEL_ID as PROTECTION_LEVEL_ID", \
	"JNR_WM_ITEM_CBO___COMMODITY_CLASS_ID as COMMODITY_CLASS_ID", \
	"JNR_WM_ITEM_CBO___COMMODITY_CODE_ID as COMMODITY_CODE_ID", \
	"JNR_WM_ITEM_CBO___PRODUCT_CLASS_ID as PRODUCT_CLASS_ID", \
	"JNR_WM_ITEM_CBO___UN_NUMBER_ID as UN_NUMBER_ID", \
	"JNR_WM_ITEM_CBO___BASE_STORAGE_UOM_ID as BASE_STORAGE_UOM_ID", \
	"JNR_WM_ITEM_CBO___ITEM_SEASON as ITEM_SEASON", \
	"JNR_WM_ITEM_CBO___ITEM_SEASON_YEAR as ITEM_SEASON_YEAR", \
	"JNR_WM_ITEM_CBO___ITEM_STYLE as ITEM_STYLE", \
	"JNR_WM_ITEM_CBO___ITEM_STYLE_SFX as ITEM_STYLE_SFX", \
	"JNR_WM_ITEM_CBO___ITEM_COLOR as ITEM_COLOR", \
	"JNR_WM_ITEM_CBO___ITEM_COLOR_SFX as ITEM_COLOR_SFX", \
	"JNR_WM_ITEM_CBO___ITEM_SECOND_DIM as ITEM_SECOND_DIM", \
	"JNR_WM_ITEM_CBO___ITEM_QUALITY as ITEM_QUALITY", \
	"JNR_WM_ITEM_CBO___ITEM_SIZE_DESC as ITEM_SIZE_DESC", \
	"JNR_WM_ITEM_CBO___ITEM_BAR_CODE as ITEM_BAR_CODE", \
	"JNR_WM_ITEM_CBO___ITEM_DESC_SHORT as ITEM_DESC_SHORT", \
	"JNR_WM_ITEM_CBO___ITEM_UPC_GTIN as ITEM_UPC_GTIN", \
	"JNR_WM_ITEM_CBO___UNIT_WEIGHT as UNIT_WEIGHT", \
	"JNR_WM_ITEM_CBO___WEIGHT_UOM_ID as WEIGHT_UOM_ID", \
	"JNR_WM_ITEM_CBO___UNIT_VOLUME as UNIT_VOLUME", \
	"JNR_WM_ITEM_CBO___VOLUME_UOM_ID as VOLUME_UOM_ID", \
	"JNR_WM_ITEM_CBO___UNIT_HEIGHT as UNIT_HEIGHT", \
	"JNR_WM_ITEM_CBO___UNIT_WIDTH as UNIT_WIDTH", \
	"JNR_WM_ITEM_CBO___UNIT_LENGTH as UNIT_LENGTH", \
	"JNR_WM_ITEM_CBO___DIMENSION_UOM_ID as DIMENSION_UOM_ID", \
	"JNR_WM_ITEM_CBO___VARIABLE_WEIGHT as VARIABLE_WEIGHT", \
	"JNR_WM_ITEM_CBO___DATABASE_QTY_UOM_ID as DATABASE_QTY_UOM_ID", \
	"JNR_WM_ITEM_CBO___DISPLAY_QTY_UOM_ID as DISPLAY_QTY_UOM_ID", \
	"JNR_WM_ITEM_CBO___STATUS_CODE as STATUS_CODE", \
	"JNR_WM_ITEM_CBO___ITEM_IMAGE_FILENAME as ITEM_IMAGE_FILENAME", \
	"JNR_WM_ITEM_CBO___AUDIT_CREATED_SOURCE as AUDIT_CREATED_SOURCE", \
	"JNR_WM_ITEM_CBO___AUDIT_CREATED_SOURCE_TYPE as AUDIT_CREATED_SOURCE_TYPE", \
	"JNR_WM_ITEM_CBO___AUDIT_CREATED_DTTM as AUDIT_CREATED_DTTM", \
	"JNR_WM_ITEM_CBO___AUDIT_LAST_UPDATED_SOURCE as AUDIT_LAST_UPDATED_SOURCE", \
	"JNR_WM_ITEM_CBO___AUDIT_LAST_UPDATED_SOURCE_TYPE as AUDIT_LAST_UPDATED_SOURCE_TYPE", \
	"JNR_WM_ITEM_CBO___AUDIT_LAST_UPDATED_DTTM as AUDIT_LAST_UPDATED_DTTM", \
	"JNR_WM_ITEM_CBO___MARK_FOR_DELETION as MARK_FOR_DELETION", \
	"JNR_WM_ITEM_CBO___CATCH_WEIGHT_ITEM as CATCH_WEIGHT_ITEM", \
	"JNR_WM_ITEM_CBO___COMMODITY_LEVEL_DESC as COMMODITY_LEVEL_DESC", \
	"JNR_WM_ITEM_CBO___CHANNEL_TYPE_ID as CHANNEL_TYPE_ID", \
	"JNR_WM_ITEM_CBO___COLOR_DESC as COLOR_DESC", \
	"JNR_WM_ITEM_CBO___VERSION as VERSION", \
	"JNR_WM_ITEM_CBO___ITEM_QUALITY_CODE as ITEM_QUALITY_CODE", \
	"JNR_WM_ITEM_CBO___PROD_TYPE as PROD_TYPE", \
	"JNR_WM_ITEM_CBO___STD_BUNDL_QTY as STD_BUNDL_QTY", \
	"JNR_WM_ITEM_CBO___STAB_CODE as STAB_CODE", \
	"JNR_WM_ITEM_CBO___ITEM_ORIENTATION as ITEM_ORIENTATION", \
	"JNR_WM_ITEM_CBO___PROTN_FACTOR as PROTN_FACTOR", \
	"JNR_WM_ITEM_CBO___CAVITY_LEN as CAVITY_LEN", \
	"JNR_WM_ITEM_CBO___CAVITY_WD as CAVITY_WD", \
	"JNR_WM_ITEM_CBO___CAVITY_HT as CAVITY_HT", \
	"JNR_WM_ITEM_CBO___INCREMENTAL_LEN as INCREMENTAL_LEN", \
	"JNR_WM_ITEM_CBO___INCREMENTAL_WD as INCREMENTAL_WD", \
	"JNR_WM_ITEM_CBO___INCREMENTAL_HT as INCREMENTAL_HT", \
	"JNR_WM_ITEM_CBO___STACKABLE_ITEM as STACKABLE_ITEM", \
	"JNR_WM_ITEM_CBO___MAX_NEST_NUMBER as MAX_NEST_NUMBER", \
	"JNR_WM_ITEM_CBO___STCC_CODE_ID as STCC_CODE_ID", \
	"JNR_WM_ITEM_CBO___SITC_CODE_ID as SITC_CODE_ID", \
	"JNR_WM_ITEM_CBO___SCHEDULE_B_CODE_ID as SCHEDULE_B_CODE_ID", \
	"JNR_WM_ITEM_CBO___SOLD_ONLINE as SOLD_ONLINE", \
	"JNR_WM_ITEM_CBO___SOLD_IN_STORES as SOLD_IN_STORES", \
	"JNR_WM_ITEM_CBO___PICKUP_AT_STORE as PICKUP_AT_STORE", \
	"JNR_WM_ITEM_CBO___SHIP_TO_STORE as SHIP_TO_STORE", \
	"JNR_WM_ITEM_CBO___URL as URL", \
	"JNR_WM_ITEM_CBO___IS_RETURNABLE as IS_RETURNABLE", \
	"JNR_WM_ITEM_CBO___REF_FIELD1 as REF_FIELD1", \
	"JNR_WM_ITEM_CBO___REF_FIELD2 as REF_FIELD2", \
	"JNR_WM_ITEM_CBO___REF_FIELD3 as REF_FIELD3", \
	"JNR_WM_ITEM_CBO___REF_FIELD4 as REF_FIELD4", \
	"JNR_WM_ITEM_CBO___REF_FIELD5 as REF_FIELD5", \
	"JNR_WM_ITEM_CBO___CUBISCAN_LAST_UPDATED_DTTM as CUBISCAN_LAST_UPDATED_DTTM", \
	"JNR_WM_ITEM_CBO___IS_EXCHANGEABLE as IS_EXCHANGEABLE", \
	"JNR_WM_ITEM_CBO___LONG_DESCRIPTION as LONG_DESCRIPTION", \
	"JNR_WM_ITEM_CBO___MIN_SHIP_INNER_UOM_ID as MIN_SHIP_INNER_UOM_ID", \
	"JNR_WM_ITEM_CBO___PRICE_STATUS as PRICE_STATUS", \
	"JNR_WM_ITEM_CBO___SELL_THROUGH as SELL_THROUGH", \
	"JNR_WM_ITEM_CBO___COMMERCE_ATTRIBUTE1 as COMMERCE_ATTRIBUTE1", \
	"JNR_WM_ITEM_CBO___COMMERCE_ATTRIBUTE2 as COMMERCE_ATTRIBUTE2", \
	"JNR_WM_ITEM_CBO___COMMERCE_NUM_ATTRIBUTE1 as COMMERCE_NUM_ATTRIBUTE1", \
	"JNR_WM_ITEM_CBO___COMMERCE_NUM_ATTRIBUTE2 as COMMERCE_NUM_ATTRIBUTE2", \
	"JNR_WM_ITEM_CBO___COMMERCE_DATE_ATTRIBUTE1 as COMMERCE_DATE_ATTRIBUTE1", \
	"JNR_WM_ITEM_CBO___BRAND as BRAND", \
	"JNR_WM_ITEM_CBO___ITEM_DISPOSITION as ITEM_DISPOSITION", \
	"JNR_WM_ITEM_CBO___CREATED_DTTM as CREATED_DTTM", \
	"JNR_WM_ITEM_CBO___LAST_UPDATED_DTTM as LAST_UPDATED_DTTM", \
	"JNR_WM_ITEM_CBO___REF_FIELD6 as REF_FIELD6", \
	"JNR_WM_ITEM_CBO___REF_FIELD7 as REF_FIELD7", \
	"JNR_WM_ITEM_CBO___REF_FIELD8 as REF_FIELD8", \
	"JNR_WM_ITEM_CBO___REF_FIELD9 as REF_FIELD9", \
	"JNR_WM_ITEM_CBO___REF_FIELD10 as REF_FIELD10", \
	"JNR_WM_ITEM_CBO___REF_NUM1 as REF_NUM1", \
	"JNR_WM_ITEM_CBO___REF_NUM2 as REF_NUM2", \
	"JNR_WM_ITEM_CBO___REF_NUM3 as REF_NUM3", \
	"JNR_WM_ITEM_CBO___REF_NUM4 as REF_NUM4", \
	"JNR_WM_ITEM_CBO___REF_NUM5 as REF_NUM5", \
	"JNR_WM_ITEM_CBO___SIZE_SEQ as SIZE_SEQ", \
	"JNR_WM_ITEM_CBO___COLOR_SEQ as COLOR_SEQ", \
	"JNR_WM_ITEM_CBO___RETURNABLE_AT_STORE as RETURNABLE_AT_STORE", \
	"JNR_WM_ITEM_CBO___GIFT_CARD_TYPE as GIFT_CARD_TYPE", \
	"JNR_WM_ITEM_CBO___i_WM_ITEM_ID as i_WM_ITEM_ID", \
	"JNR_WM_ITEM_CBO___i_WM_AUDIT_CREATED_TSTMP as i_WM_AUDIT_CREATED_TSTMP", \
	"JNR_WM_ITEM_CBO___i_WM_AUDIT_LAST_UPDATED_TSTMP as i_WM_AUDIT_LAST_UPDATED_TSTMP", \
	"JNR_WM_ITEM_CBO___i_WM_CREATED_TSTMP as i_WM_CREATED_TSTMP", \
	"JNR_WM_ITEM_CBO___i_WM_LAST_UPDATED_TSTMP as i_WM_LAST_UPDATED_TSTMP", \
	"JNR_WM_ITEM_CBO___i_LOAD_TSTMP as i_LOAD_TSTMP") \
    .filter("i_WM_ITEM_ID is Null OR (i_WM_ITEM_ID is not Null AND \
     ( COALESCE(AUDIT_CREATED_DTTM, date'1900-01-01') != COALESCE(i_WM_AUDIT_CREATED_TSTMP, date'1900-01-01') \
    OR COALESCE(AUDIT_LAST_UPDATED_DTTM, date'1900-01-01') != COALESCE(i_WM_AUDIT_LAST_UPDATED_TSTMP, date'1900-01-01') \
    OR COALESCE(CREATED_DTTM, date'1900-01-01') != COALESCE(i_WM_CREATED_TSTMP, date'1900-01-01') \
    OR COALESCE(LAST_UPDATED_DTTM, date'1900-01-01') != COALESCE(i_WM_LAST_UPDATED_TSTMP, date'1900-01-01')))").withColumn("sys_row_id", monotonically_increasing_id())


# COMMAND ----------
# Processing node EXP_UPD_VALIDATOR, type EXPRESSION 
# COLUMN COUNT: 108

# for each involved DataFrame, append the dataframe name to each column
FIL_UNCHANGED_RECORDS_temp = FIL_UNCHANGED_RECORDS.toDF(*["FIL_UNCHANGED_RECORDS___" + col for col in FIL_UNCHANGED_RECORDS.columns])

EXP_UPD_VALIDATOR = FIL_UNCHANGED_RECORDS_temp.selectExpr( \
	"FIL_UNCHANGED_RECORDS___sys_row_id as sys_row_id", \
	"FIL_UNCHANGED_RECORDS___LOCATION_ID as LOCATION_ID", \
	"FIL_UNCHANGED_RECORDS___ITEM_ID as ITEM_ID", \
	"FIL_UNCHANGED_RECORDS___COMPANY_ID as COMPANY_ID", \
	"FIL_UNCHANGED_RECORDS___ITEM_NAME as ITEM_NAME", \
	"FIL_UNCHANGED_RECORDS___DESCRIPTION as DESCRIPTION", \
	"FIL_UNCHANGED_RECORDS___PROTECTION_LEVEL_ID as PROTECTION_LEVEL_ID", \
	"FIL_UNCHANGED_RECORDS___COMMODITY_CLASS_ID as COMMODITY_CLASS_ID", \
	"FIL_UNCHANGED_RECORDS___COMMODITY_CODE_ID as COMMODITY_CODE_ID", \
	"FIL_UNCHANGED_RECORDS___PRODUCT_CLASS_ID as PRODUCT_CLASS_ID", \
	"FIL_UNCHANGED_RECORDS___UN_NUMBER_ID as UN_NUMBER_ID", \
	"FIL_UNCHANGED_RECORDS___BASE_STORAGE_UOM_ID as BASE_STORAGE_UOM_ID", \
	"FIL_UNCHANGED_RECORDS___ITEM_SEASON as ITEM_SEASON", \
	"FIL_UNCHANGED_RECORDS___ITEM_SEASON_YEAR as ITEM_SEASON_YEAR", \
	"FIL_UNCHANGED_RECORDS___ITEM_STYLE as ITEM_STYLE", \
	"FIL_UNCHANGED_RECORDS___ITEM_STYLE_SFX as ITEM_STYLE_SFX", \
	"FIL_UNCHANGED_RECORDS___ITEM_COLOR as ITEM_COLOR", \
	"FIL_UNCHANGED_RECORDS___ITEM_COLOR_SFX as ITEM_COLOR_SFX", \
	"FIL_UNCHANGED_RECORDS___ITEM_SECOND_DIM as ITEM_SECOND_DIM", \
	"FIL_UNCHANGED_RECORDS___ITEM_QUALITY as ITEM_QUALITY", \
	"FIL_UNCHANGED_RECORDS___ITEM_SIZE_DESC as ITEM_SIZE_DESC", \
	"FIL_UNCHANGED_RECORDS___ITEM_BAR_CODE as ITEM_BAR_CODE", \
	"FIL_UNCHANGED_RECORDS___ITEM_DESC_SHORT as ITEM_DESC_SHORT", \
	"FIL_UNCHANGED_RECORDS___ITEM_UPC_GTIN as ITEM_UPC_GTIN", \
	"FIL_UNCHANGED_RECORDS___UNIT_WEIGHT as UNIT_WEIGHT", \
	"FIL_UNCHANGED_RECORDS___WEIGHT_UOM_ID as WEIGHT_UOM_ID", \
	"FIL_UNCHANGED_RECORDS___UNIT_VOLUME as UNIT_VOLUME", \
	"FIL_UNCHANGED_RECORDS___VOLUME_UOM_ID as VOLUME_UOM_ID", \
	"FIL_UNCHANGED_RECORDS___UNIT_HEIGHT as UNIT_HEIGHT", \
	"FIL_UNCHANGED_RECORDS___UNIT_WIDTH as UNIT_WIDTH", \
	"FIL_UNCHANGED_RECORDS___UNIT_LENGTH as UNIT_LENGTH", \
	"FIL_UNCHANGED_RECORDS___DIMENSION_UOM_ID as DIMENSION_UOM_ID", \
	"FIL_UNCHANGED_RECORDS___VARIABLE_WEIGHT as VARIABLE_WEIGHT", \
	"FIL_UNCHANGED_RECORDS___DATABASE_QTY_UOM_ID as DATABASE_QTY_UOM_ID", \
	"FIL_UNCHANGED_RECORDS___DISPLAY_QTY_UOM_ID as DISPLAY_QTY_UOM_ID", \
	"FIL_UNCHANGED_RECORDS___STATUS_CODE as STATUS_CODE", \
	"FIL_UNCHANGED_RECORDS___ITEM_IMAGE_FILENAME as ITEM_IMAGE_FILENAME", \
	"FIL_UNCHANGED_RECORDS___AUDIT_CREATED_SOURCE as AUDIT_CREATED_SOURCE", \
	"FIL_UNCHANGED_RECORDS___AUDIT_CREATED_SOURCE_TYPE as AUDIT_CREATED_SOURCE_TYPE", \
	"FIL_UNCHANGED_RECORDS___AUDIT_CREATED_DTTM as AUDIT_CREATED_DTTM", \
	"FIL_UNCHANGED_RECORDS___AUDIT_LAST_UPDATED_SOURCE as AUDIT_LAST_UPDATED_SOURCE", \
	"FIL_UNCHANGED_RECORDS___AUDIT_LAST_UPDATED_SOURCE_TYPE as AUDIT_LAST_UPDATED_SOURCE_TYPE", \
	"FIL_UNCHANGED_RECORDS___AUDIT_LAST_UPDATED_DTTM as AUDIT_LAST_UPDATED_DTTM", \
	"FIL_UNCHANGED_RECORDS___MARK_FOR_DELETION as MARK_FOR_DELETION", \
    "CASE WHEN TRIM(UPPER(FIL_UNCHANGED_RECORDS___CATCH_WEIGHT_ITEM)) IN ('Y', '1') THEN '1' ELSE '0' END as CATCH_WEIGHT_ITEM_EXP", \
	"FIL_UNCHANGED_RECORDS___COMMODITY_LEVEL_DESC as COMMODITY_LEVEL_DESC", \
	"FIL_UNCHANGED_RECORDS___CHANNEL_TYPE_ID as CHANNEL_TYPE_ID", \
	"FIL_UNCHANGED_RECORDS___COLOR_DESC as COLOR_DESC", \
	"FIL_UNCHANGED_RECORDS___VERSION as VERSION", \
	"FIL_UNCHANGED_RECORDS___ITEM_QUALITY_CODE as ITEM_QUALITY_CODE", \
	"FIL_UNCHANGED_RECORDS___PROD_TYPE as PROD_TYPE", \
	"FIL_UNCHANGED_RECORDS___STD_BUNDL_QTY as STD_BUNDL_QTY", \
	"FIL_UNCHANGED_RECORDS___STAB_CODE as STAB_CODE", \
	"FIL_UNCHANGED_RECORDS___ITEM_ORIENTATION as ITEM_ORIENTATION", \
	"FIL_UNCHANGED_RECORDS___PROTN_FACTOR as PROTN_FACTOR", \
	"FIL_UNCHANGED_RECORDS___CAVITY_LEN as CAVITY_LEN", \
	"FIL_UNCHANGED_RECORDS___CAVITY_WD as CAVITY_WD", \
	"FIL_UNCHANGED_RECORDS___CAVITY_HT as CAVITY_HT", \
	"FIL_UNCHANGED_RECORDS___INCREMENTAL_LEN as INCREMENTAL_LEN", \
	"FIL_UNCHANGED_RECORDS___INCREMENTAL_WD as INCREMENTAL_WD", \
	"FIL_UNCHANGED_RECORDS___INCREMENTAL_HT as INCREMENTAL_HT", \
    "CASE WHEN TRIM(UPPER(FIL_UNCHANGED_RECORDS___STACKABLE_ITEM)) IN ('Y', '1') THEN '1' ELSE '0' END as STACKABLE_ITEM_EXP", \
	"FIL_UNCHANGED_RECORDS___MAX_NEST_NUMBER as MAX_NEST_NUMBER", \
	"FIL_UNCHANGED_RECORDS___STCC_CODE_ID as STCC_CODE_ID", \
	"FIL_UNCHANGED_RECORDS___SITC_CODE_ID as SITC_CODE_ID", \
	"FIL_UNCHANGED_RECORDS___SCHEDULE_B_CODE_ID as SCHEDULE_B_CODE_ID", \
	"FIL_UNCHANGED_RECORDS___SOLD_ONLINE as SOLD_ONLINE", \
	"FIL_UNCHANGED_RECORDS___SOLD_IN_STORES as SOLD_IN_STORES", \
	"FIL_UNCHANGED_RECORDS___PICKUP_AT_STORE as PICKUP_AT_STORE", \
	"FIL_UNCHANGED_RECORDS___SHIP_TO_STORE as SHIP_TO_STORE", \
	"FIL_UNCHANGED_RECORDS___URL as URL", \
	"FIL_UNCHANGED_RECORDS___IS_RETURNABLE as IS_RETURNABLE", \
	"FIL_UNCHANGED_RECORDS___REF_FIELD1 as REF_FIELD1", \
	"FIL_UNCHANGED_RECORDS___REF_FIELD2 as REF_FIELD2", \
	"FIL_UNCHANGED_RECORDS___REF_FIELD3 as REF_FIELD3", \
	"FIL_UNCHANGED_RECORDS___REF_FIELD4 as REF_FIELD4", \
	"FIL_UNCHANGED_RECORDS___REF_FIELD5 as REF_FIELD5", \
	"FIL_UNCHANGED_RECORDS___CUBISCAN_LAST_UPDATED_DTTM as CUBISCAN_LAST_UPDATED_DTTM", \
	"FIL_UNCHANGED_RECORDS___IS_EXCHANGEABLE as IS_EXCHANGEABLE", \
	"FIL_UNCHANGED_RECORDS___LONG_DESCRIPTION as LONG_DESCRIPTION", \
	"FIL_UNCHANGED_RECORDS___MIN_SHIP_INNER_UOM_ID as MIN_SHIP_INNER_UOM_ID", \
	"FIL_UNCHANGED_RECORDS___PRICE_STATUS as PRICE_STATUS", \
	"FIL_UNCHANGED_RECORDS___SELL_THROUGH as SELL_THROUGH", \
	"FIL_UNCHANGED_RECORDS___COMMERCE_ATTRIBUTE1 as COMMERCE_ATTRIBUTE1", \
	"FIL_UNCHANGED_RECORDS___COMMERCE_ATTRIBUTE2 as COMMERCE_ATTRIBUTE2", \
	"FIL_UNCHANGED_RECORDS___COMMERCE_NUM_ATTRIBUTE1 as COMMERCE_NUM_ATTRIBUTE1", \
	"FIL_UNCHANGED_RECORDS___COMMERCE_NUM_ATTRIBUTE2 as COMMERCE_NUM_ATTRIBUTE2", \
	"FIL_UNCHANGED_RECORDS___COMMERCE_DATE_ATTRIBUTE1 as COMMERCE_DATE_ATTRIBUTE1", \
	"FIL_UNCHANGED_RECORDS___BRAND as BRAND", \
	"FIL_UNCHANGED_RECORDS___ITEM_DISPOSITION as ITEM_DISPOSITION", \
	"FIL_UNCHANGED_RECORDS___CREATED_DTTM as CREATED_DTTM", \
	"FIL_UNCHANGED_RECORDS___LAST_UPDATED_DTTM as LAST_UPDATED_DTTM", \
	"FIL_UNCHANGED_RECORDS___REF_FIELD6 as REF_FIELD6", \
	"FIL_UNCHANGED_RECORDS___REF_FIELD7 as REF_FIELD7", \
	"FIL_UNCHANGED_RECORDS___REF_FIELD8 as REF_FIELD8", \
	"FIL_UNCHANGED_RECORDS___REF_FIELD9 as REF_FIELD9", \
	"FIL_UNCHANGED_RECORDS___REF_FIELD10 as REF_FIELD10", \
	"FIL_UNCHANGED_RECORDS___REF_NUM1 as REF_NUM1", \
	"FIL_UNCHANGED_RECORDS___REF_NUM2 as REF_NUM2", \
	"FIL_UNCHANGED_RECORDS___REF_NUM3 as REF_NUM3", \
	"FIL_UNCHANGED_RECORDS___REF_NUM4 as REF_NUM4", \
	"FIL_UNCHANGED_RECORDS___REF_NUM5 as REF_NUM5", \
	"FIL_UNCHANGED_RECORDS___SIZE_SEQ as SIZE_SEQ", \
	"FIL_UNCHANGED_RECORDS___COLOR_SEQ as COLOR_SEQ", \
	"FIL_UNCHANGED_RECORDS___RETURNABLE_AT_STORE as RETURNABLE_AT_STORE", \
	"FIL_UNCHANGED_RECORDS___GIFT_CARD_TYPE as GIFT_CARD_TYPE", \
	"CURRENT_TIMESTAMP as UPDATE_TSTMP", \
	"IF(FIL_UNCHANGED_RECORDS___i_LOAD_TSTMP IS NULL, CURRENT_TIMESTAMP, FIL_UNCHANGED_RECORDS___i_LOAD_TSTMP) as LOAD_TSTMP", \
	"IF(FIL_UNCHANGED_RECORDS___i_WM_ITEM_ID IS NULL, 1, 2) as o_UPDATE_VALIDATOR" \
)

# COMMAND ----------
# Processing node UPD_INS_UPD, type UPDATE_STRATEGY . Note: using additional SELECT to rename incoming columns
# COLUMN COUNT: 108

# for each involved DataFrame, append the dataframe name to each column
EXP_UPD_VALIDATOR_temp = EXP_UPD_VALIDATOR.toDF(*["EXP_UPD_VALIDATOR___" + col for col in EXP_UPD_VALIDATOR.columns])

UPD_INS_UPD = EXP_UPD_VALIDATOR_temp.selectExpr( \
	"EXP_UPD_VALIDATOR___LOCATION_ID as LOCATION_ID", \
	"EXP_UPD_VALIDATOR___ITEM_ID as ITEM_ID", \
	"EXP_UPD_VALIDATOR___COMPANY_ID as COMPANY_ID", \
	"EXP_UPD_VALIDATOR___ITEM_NAME as ITEM_NAME", \
	"EXP_UPD_VALIDATOR___DESCRIPTION as DESCRIPTION", \
	"EXP_UPD_VALIDATOR___PROTECTION_LEVEL_ID as PROTECTION_LEVEL_ID", \
	"EXP_UPD_VALIDATOR___COMMODITY_CLASS_ID as COMMODITY_CLASS_ID", \
	"EXP_UPD_VALIDATOR___COMMODITY_CODE_ID as COMMODITY_CODE_ID", \
	"EXP_UPD_VALIDATOR___PRODUCT_CLASS_ID as PRODUCT_CLASS_ID", \
	"EXP_UPD_VALIDATOR___UN_NUMBER_ID as UN_NUMBER_ID", \
	"EXP_UPD_VALIDATOR___BASE_STORAGE_UOM_ID as BASE_STORAGE_UOM_ID", \
	"EXP_UPD_VALIDATOR___ITEM_SEASON as ITEM_SEASON", \
	"EXP_UPD_VALIDATOR___ITEM_SEASON_YEAR as ITEM_SEASON_YEAR", \
	"EXP_UPD_VALIDATOR___ITEM_STYLE as ITEM_STYLE", \
	"EXP_UPD_VALIDATOR___ITEM_STYLE_SFX as ITEM_STYLE_SFX", \
	"EXP_UPD_VALIDATOR___ITEM_COLOR as ITEM_COLOR", \
	"EXP_UPD_VALIDATOR___ITEM_COLOR_SFX as ITEM_COLOR_SFX", \
	"EXP_UPD_VALIDATOR___ITEM_SECOND_DIM as ITEM_SECOND_DIM", \
	"EXP_UPD_VALIDATOR___ITEM_QUALITY as ITEM_QUALITY", \
	"EXP_UPD_VALIDATOR___ITEM_SIZE_DESC as ITEM_SIZE_DESC", \
	"EXP_UPD_VALIDATOR___ITEM_BAR_CODE as ITEM_BAR_CODE", \
	"EXP_UPD_VALIDATOR___ITEM_DESC_SHORT as ITEM_DESC_SHORT", \
	"EXP_UPD_VALIDATOR___ITEM_UPC_GTIN as ITEM_UPC_GTIN", \
	"EXP_UPD_VALIDATOR___UNIT_WEIGHT as UNIT_WEIGHT", \
	"EXP_UPD_VALIDATOR___WEIGHT_UOM_ID as WEIGHT_UOM_ID", \
	"EXP_UPD_VALIDATOR___UNIT_VOLUME as UNIT_VOLUME", \
	"EXP_UPD_VALIDATOR___VOLUME_UOM_ID as VOLUME_UOM_ID", \
	"EXP_UPD_VALIDATOR___UNIT_HEIGHT as UNIT_HEIGHT", \
	"EXP_UPD_VALIDATOR___UNIT_WIDTH as UNIT_WIDTH", \
	"EXP_UPD_VALIDATOR___UNIT_LENGTH as UNIT_LENGTH", \
	"EXP_UPD_VALIDATOR___DIMENSION_UOM_ID as DIMENSION_UOM_ID", \
	"EXP_UPD_VALIDATOR___VARIABLE_WEIGHT as VARIABLE_WEIGHT", \
	"EXP_UPD_VALIDATOR___DATABASE_QTY_UOM_ID as DATABASE_QTY_UOM_ID", \
	"EXP_UPD_VALIDATOR___DISPLAY_QTY_UOM_ID as DISPLAY_QTY_UOM_ID", \
	"EXP_UPD_VALIDATOR___STATUS_CODE as STATUS_CODE", \
	"EXP_UPD_VALIDATOR___ITEM_IMAGE_FILENAME as ITEM_IMAGE_FILENAME", \
	"EXP_UPD_VALIDATOR___AUDIT_CREATED_SOURCE as AUDIT_CREATED_SOURCE", \
	"EXP_UPD_VALIDATOR___AUDIT_CREATED_SOURCE_TYPE as AUDIT_CREATED_SOURCE_TYPE", \
	"EXP_UPD_VALIDATOR___AUDIT_CREATED_DTTM as AUDIT_CREATED_DTTM", \
	"EXP_UPD_VALIDATOR___AUDIT_LAST_UPDATED_SOURCE as AUDIT_LAST_UPDATED_SOURCE", \
	"EXP_UPD_VALIDATOR___AUDIT_LAST_UPDATED_SOURCE_TYPE as AUDIT_LAST_UPDATED_SOURCE_TYPE", \
	"EXP_UPD_VALIDATOR___AUDIT_LAST_UPDATED_DTTM as AUDIT_LAST_UPDATED_DTTM", \
	"EXP_UPD_VALIDATOR___MARK_FOR_DELETION as MARK_FOR_DELETION", \
	"EXP_UPD_VALIDATOR___CATCH_WEIGHT_ITEM_EXP as CATCH_WEIGHT_ITEM", \
	"EXP_UPD_VALIDATOR___COMMODITY_LEVEL_DESC as COMMODITY_LEVEL_DESC", \
	"EXP_UPD_VALIDATOR___CHANNEL_TYPE_ID as CHANNEL_TYPE_ID", \
	"EXP_UPD_VALIDATOR___COLOR_DESC as COLOR_DESC", \
	"EXP_UPD_VALIDATOR___VERSION as VERSION", \
	"EXP_UPD_VALIDATOR___ITEM_QUALITY_CODE as ITEM_QUALITY_CODE", \
	"EXP_UPD_VALIDATOR___PROD_TYPE as PROD_TYPE", \
	"EXP_UPD_VALIDATOR___STD_BUNDL_QTY as STD_BUNDL_QTY", \
	"EXP_UPD_VALIDATOR___STAB_CODE as STAB_CODE", \
	"EXP_UPD_VALIDATOR___ITEM_ORIENTATION as ITEM_ORIENTATION", \
	"EXP_UPD_VALIDATOR___PROTN_FACTOR as PROTN_FACTOR", \
	"EXP_UPD_VALIDATOR___CAVITY_LEN as CAVITY_LEN", \
	"EXP_UPD_VALIDATOR___CAVITY_WD as CAVITY_WD", \
	"EXP_UPD_VALIDATOR___CAVITY_HT as CAVITY_HT", \
	"EXP_UPD_VALIDATOR___INCREMENTAL_LEN as INCREMENTAL_LEN", \
	"EXP_UPD_VALIDATOR___INCREMENTAL_WD as INCREMENTAL_WD", \
	"EXP_UPD_VALIDATOR___INCREMENTAL_HT as INCREMENTAL_HT", \
	"EXP_UPD_VALIDATOR___STACKABLE_ITEM_EXP as STACKABLE_ITEM", \
	"EXP_UPD_VALIDATOR___MAX_NEST_NUMBER as MAX_NEST_NUMBER", \
	"EXP_UPD_VALIDATOR___STCC_CODE_ID as STCC_CODE_ID", \
	"EXP_UPD_VALIDATOR___SITC_CODE_ID as SITC_CODE_ID", \
	"EXP_UPD_VALIDATOR___SCHEDULE_B_CODE_ID as SCHEDULE_B_CODE_ID", \
	"EXP_UPD_VALIDATOR___SOLD_ONLINE as SOLD_ONLINE", \
	"EXP_UPD_VALIDATOR___SOLD_IN_STORES as SOLD_IN_STORES", \
	"EXP_UPD_VALIDATOR___PICKUP_AT_STORE as PICKUP_AT_STORE", \
	"EXP_UPD_VALIDATOR___SHIP_TO_STORE as SHIP_TO_STORE", \
	"EXP_UPD_VALIDATOR___URL as URL", \
	"EXP_UPD_VALIDATOR___IS_RETURNABLE as IS_RETURNABLE", \
	"EXP_UPD_VALIDATOR___REF_FIELD1 as REF_FIELD1", \
	"EXP_UPD_VALIDATOR___REF_FIELD2 as REF_FIELD2", \
	"EXP_UPD_VALIDATOR___REF_FIELD3 as REF_FIELD3", \
	"EXP_UPD_VALIDATOR___REF_FIELD4 as REF_FIELD4", \
	"EXP_UPD_VALIDATOR___REF_FIELD5 as REF_FIELD5", \
	"EXP_UPD_VALIDATOR___CUBISCAN_LAST_UPDATED_DTTM as CUBISCAN_LAST_UPDATED_DTTM", \
	"EXP_UPD_VALIDATOR___IS_EXCHANGEABLE as IS_EXCHANGEABLE", \
	"EXP_UPD_VALIDATOR___LONG_DESCRIPTION as LONG_DESCRIPTION", \
	"EXP_UPD_VALIDATOR___MIN_SHIP_INNER_UOM_ID as MIN_SHIP_INNER_UOM_ID", \
	"EXP_UPD_VALIDATOR___PRICE_STATUS as PRICE_STATUS", \
	"EXP_UPD_VALIDATOR___SELL_THROUGH as SELL_THROUGH", \
	"EXP_UPD_VALIDATOR___COMMERCE_ATTRIBUTE1 as COMMERCE_ATTRIBUTE1", \
	"EXP_UPD_VALIDATOR___COMMERCE_ATTRIBUTE2 as COMMERCE_ATTRIBUTE2", \
	"EXP_UPD_VALIDATOR___COMMERCE_NUM_ATTRIBUTE1 as COMMERCE_NUM_ATTRIBUTE1", \
	"EXP_UPD_VALIDATOR___COMMERCE_NUM_ATTRIBUTE2 as COMMERCE_NUM_ATTRIBUTE2", \
	"EXP_UPD_VALIDATOR___COMMERCE_DATE_ATTRIBUTE1 as COMMERCE_DATE_ATTRIBUTE1", \
	"EXP_UPD_VALIDATOR___BRAND as BRAND", \
	"EXP_UPD_VALIDATOR___ITEM_DISPOSITION as ITEM_DISPOSITION", \
	"EXP_UPD_VALIDATOR___CREATED_DTTM as CREATED_DTTM", \
	"EXP_UPD_VALIDATOR___LAST_UPDATED_DTTM as LAST_UPDATED_DTTM", \
	"EXP_UPD_VALIDATOR___REF_FIELD6 as REF_FIELD6", \
	"EXP_UPD_VALIDATOR___REF_FIELD7 as REF_FIELD7", \
	"EXP_UPD_VALIDATOR___REF_FIELD8 as REF_FIELD8", \
	"EXP_UPD_VALIDATOR___REF_FIELD9 as REF_FIELD9", \
	"EXP_UPD_VALIDATOR___REF_FIELD10 as REF_FIELD10", \
	"EXP_UPD_VALIDATOR___REF_NUM1 as REF_NUM1", \
	"EXP_UPD_VALIDATOR___REF_NUM2 as REF_NUM2", \
	"EXP_UPD_VALIDATOR___REF_NUM3 as REF_NUM3", \
	"EXP_UPD_VALIDATOR___REF_NUM4 as REF_NUM4", \
	"EXP_UPD_VALIDATOR___REF_NUM5 as REF_NUM5", \
	"EXP_UPD_VALIDATOR___SIZE_SEQ as SIZE_SEQ", \
	"EXP_UPD_VALIDATOR___COLOR_SEQ as COLOR_SEQ", \
	"EXP_UPD_VALIDATOR___RETURNABLE_AT_STORE as RETURNABLE_AT_STORE", \
	"EXP_UPD_VALIDATOR___GIFT_CARD_TYPE as GIFT_CARD_TYPE", \
	"EXP_UPD_VALIDATOR___UPDATE_TSTMP as UPDATE_TSTMP", \
	"EXP_UPD_VALIDATOR___LOAD_TSTMP as LOAD_TSTMP", \
	"EXP_UPD_VALIDATOR___o_UPDATE_VALIDATOR as o_UPDATE_VALIDATOR") \
	.withColumn('pyspark_data_action', when(col('o_UPDATE_VALIDATOR') ==(lit(1)), lit(0)).when(col('o_UPDATE_VALIDATOR') ==(lit(2)), lit(1)))

# COMMAND ----------
# Processing node Shortcut_to_WM_ITEM_CBO1, type TARGET 
# COLUMN COUNT: 107

Shortcut_to_WM_ITEM_CBO1 = UPD_INS_UPD.selectExpr(
	"CAST(LOCATION_ID AS BIGINT) as LOCATION_ID",
	"CAST(ITEM_ID AS INT) as WM_ITEM_ID",
	"CAST(COMPANY_ID AS INT) as WM_COMPANY_ID",
	"CAST(ITEM_NAME AS STRING) as WM_ITEM_NAME",
	"CAST(DESCRIPTION AS STRING) as WM_ITEM_DESC",
	"CAST(ITEM_DESC_SHORT AS STRING) as WM_ITEM_SHORT_DESC",
	"CAST(LONG_DESCRIPTION AS STRING) as WM_ITEM_LONG_DESC",
	"CAST(BRAND AS STRING) as BRAND",
	"CAST(ITEM_UPC_GTIN AS STRING) as ITEM_UPC_GTIN",
	"CAST(ITEM_BAR_CODE AS STRING) as ITEM_BAR_CD",
	"CAST(ITEM_ORIENTATION AS STRING) as ITEM_ORIENTATION",
	"CAST(ITEM_DISPOSITION AS STRING) as ITEM_DISPOSITION",
	"CAST(ITEM_SEASON AS STRING) as ITEM_SEASON",
	"CAST(ITEM_SEASON_YEAR AS STRING) as ITEM_SEASON_YEAR",
	"CAST(ITEM_STYLE AS STRING) as ITEM_STYLE",
	"CAST(ITEM_STYLE_SFX AS STRING) as ITEM_STYLE_SFX",
	"CAST(ITEM_COLOR AS STRING) as ITEM_COLOR",
	"CAST(ITEM_COLOR_SFX AS STRING) as ITEM_COLOR_SFX",
	"CAST(ITEM_SECOND_DIM AS STRING) as ITEM_SECOND_DIM",
	"CAST(ITEM_QUALITY AS STRING) as ITEM_QUALITY",
	"CAST(ITEM_SIZE_DESC AS STRING) as ITEM_SIZE_DESC",
	"CAST(SIZE_SEQ AS SMALLINT) as SIZE_SEQ",
	"CAST(COLOR_SEQ AS SMALLINT) as COLOR_SEQ",
	"CAST(COLOR_DESC AS STRING) as COLOR_DESC",
	"CAST(ITEM_QUALITY_CODE AS INT) as WM_ITEM_QUALITY_CD",
	"CAST(STD_BUNDL_QTY AS DECIMAL(9,2)) as STD_BUNDL_QTY",
	"CAST(MAX_NEST_NUMBER AS SMALLINT) as MAX_NEST_NBR",
	"CAST(SELL_THROUGH AS DECIMAL(13,4)) as SELL_THROUGH",
	"CAST(UNIT_HEIGHT AS DECIMAL(16,4)) as UNIT_HEIGHT",
	"CAST(UNIT_WIDTH AS DECIMAL(16,4)) as UNIT_WIDTH",
	"CAST(UNIT_LENGTH AS DECIMAL(16,4)) as UNIT_LENGTH",
	"CAST(VARIABLE_WEIGHT AS TINYINT) as VARIABLE_WEIGHT",
	"CAST(UNIT_WEIGHT AS DECIMAL(16,4)) as UNIT_WEIGHT",
	"CAST(UNIT_VOLUME AS DECIMAL(16,4)) as UNIT_VOLUME",
	"CAST(CAVITY_LEN AS DECIMAL(7,2)) as CAVITY_LEN",
	"CAST(CAVITY_WD AS DECIMAL(7,2)) as CAVITY_WD",
	"CAST(CAVITY_HT AS DECIMAL(7,2)) as CAVITY_HT",
	"CAST(INCREMENTAL_LEN AS DECIMAL(16,4)) as INCREMENTAL_LEN",
	"CAST(INCREMENTAL_WD AS DECIMAL(16,4)) as INCREMENTAL_WD",
	"CAST(INCREMENTAL_HT AS DECIMAL(16,4)) as INCREMENTAL_HT",
	"CAST(DIMENSION_UOM_ID AS INT) as WM_DIMENSION_UOM_ID",
	"CAST(WEIGHT_UOM_ID AS INT) as WM_WEIGHT_UOM_ID",
	"CAST(VOLUME_UOM_ID AS INT) as WM_VOLUME_UOM_ID",
	"CAST(DATABASE_QTY_UOM_ID AS INT) as WM_DATABASE_QTY_UOM_ID",
	"CAST(DISPLAY_QTY_UOM_ID AS INT) as WM_DISPLAY_QTY_UOM_ID",
	"CAST(MIN_SHIP_INNER_UOM_ID AS STRING) as WM_MIN_SHIP_INNER_UOM_ID",
	"CAST(BASE_STORAGE_UOM_ID AS INT) as WM_BASE_STORAGE_UOM_ID",
	"CAST(STATUS_CODE AS TINYINT) as WM_ITEM_STATUS_CD",
	"CAST(PRICE_STATUS AS STRING) as WM_PRICE_STATUS",
	"CAST(CATCH_WEIGHT_ITEM AS TINYINT) as CATCH_WEIGHT_ITEM_FLAG",
	"CAST(COMMODITY_LEVEL_DESC AS STRING) as COMMODITY_LEVEL_DESC",
	"CAST(CHANNEL_TYPE_ID AS INT) as WM_CHANNEL_TYPE_ID",
	"CAST(PROD_TYPE AS STRING) as WM_PROD_TYPE",
	"CAST(GIFT_CARD_TYPE AS STRING) as WM_GIFT_CARD_TYPE",
	"CAST(STAB_CODE AS STRING) as WM_STAB_CD",
	"CAST(PROTN_FACTOR AS STRING) as PROTN_FACTOR",
	"CAST(PROTECTION_LEVEL_ID AS INT) as WM_PROTECTION_LEVEL_ID",
	"CAST(COMMODITY_CLASS_ID AS INT) as WM_COMMODITY_CLASS_ID",
	"CAST(COMMODITY_CODE_ID AS BIGINT) as WM_COMMODITY_CD_ID",
	"CAST(PRODUCT_CLASS_ID AS INT) as WM_PRODUCT_CLASS_ID",
	"CAST(UN_NUMBER_ID AS BIGINT) as WM_UN_NBR_ID",
	"CAST(SCHEDULE_B_CODE_ID AS INT) as WM_SCHEDULE_B_CD_ID",
	"CAST(STCC_CODE_ID AS INT) as WM_STCC_CD_ID",
	"CAST(SITC_CODE_ID AS INT) as WM_SITC_CD_ID",
	"CAST(URL AS STRING) as WM_URL",
	"CAST(ITEM_IMAGE_FILENAME AS STRING) as WM_ITEM_IMAGE_FILE_NAME",
	"CAST(STACKABLE_ITEM AS TINYINT) as STACKABLE_ITEM_FLAG",
	"CAST(SOLD_ONLINE AS TINYINT) as SOLD_ONLINE_FLAG",
	"CAST(SOLD_IN_STORES AS TINYINT) as SOLD_IN_STORES_FLAG",
	"CAST(PICKUP_AT_STORE AS TINYINT) as PICKUP_AT_STORE_FLAG",
	"CAST(SHIP_TO_STORE AS TINYINT) as SHIP_TO_STORE_FLAG",
	"CAST(IS_RETURNABLE AS TINYINT) as RETURNABLE_FLAG",
	"CAST(IS_EXCHANGEABLE AS TINYINT) as EXCHANGEABLE_FLAG",
	"CAST(RETURNABLE_AT_STORE AS TINYINT) as RETURNABLE_AT_STORE_FLAG",
	"CAST(COMMERCE_ATTRIBUTE1 AS STRING) as COMMERCE_ATTR_1",
	"CAST(COMMERCE_ATTRIBUTE2 AS STRING) as COMMERCE_ATTR_2",
	"CAST(COMMERCE_NUM_ATTRIBUTE1 AS DECIMAL(13,4)) as COMMERCE_NUM_ATTR_1",
	"CAST(COMMERCE_NUM_ATTRIBUTE2 AS DECIMAL(13,4)) as COMMERCE_NUM_ATTR_2",
	"CAST(COMMERCE_DATE_ATTRIBUTE1 AS TIMESTAMP) as COMMERCE_DATE_ATTR_1",
	"CAST(REF_FIELD1 AS STRING) as REF_FIELD_1",
	"CAST(REF_FIELD2 AS STRING) as REF_FIELD_2",
	"CAST(REF_FIELD3 AS STRING) as REF_FIELD_3",
	"CAST(REF_FIELD4 AS STRING) as REF_FIELD_4",
	"CAST(REF_FIELD5 AS STRING) as REF_FIELD_5",
	"CAST(REF_NUM1 AS DECIMAL(13,5)) as REF_NUM_1",
	"CAST(REF_NUM2 AS DECIMAL(13,5)) as REF_NUM_2",
	"CAST(REF_NUM3 AS DECIMAL(13,5)) as REF_NUM_3",
	"CAST(REF_NUM4 AS DECIMAL(13,5)) as REF_NUM_4",
	"CAST(REF_NUM5 AS DECIMAL(13,5)) as REF_NUM_5",
	"CAST(REF_FIELD6 AS STRING) as REF_FIELD_6",
	"CAST(REF_FIELD7 AS STRING) as REF_FIELD_7",
	"CAST(REF_FIELD8 AS STRING) as REF_FIELD_8",
	"CAST(REF_FIELD9 AS STRING) as REF_FIELD_9",
	"CAST(REF_FIELD10 AS STRING) as REF_FIELD_10",
	"CAST(CUBISCAN_LAST_UPDATED_DTTM AS TIMESTAMP) as CUBISCAN_LAST_UPDATED_TSTMP",
	"CAST(VERSION AS BIGINT) as WM_VERSION",
	"CAST(MARK_FOR_DELETION AS TINYINT) as MARK_FOR_DELETION_FLAG",
	"CAST(AUDIT_CREATED_SOURCE_TYPE AS TINYINT) as WM_AUDIT_CREATED_SOURCE_TYPE",
	"CAST(AUDIT_CREATED_SOURCE AS STRING) as WM_AUDIT_CREATED_SOURCE",
	"CAST(AUDIT_CREATED_DTTM AS TIMESTAMP) as WM_AUDIT_CREATED_TSTMP",
	"CAST(AUDIT_LAST_UPDATED_SOURCE_TYPE AS TINYINT) as WM_AUDIT_LAST_UPDATED_SOURCE_TYPE",
	"CAST(AUDIT_LAST_UPDATED_SOURCE AS STRING) as WM_AUDIT_LAST_UPDATED_SOURCE",
	"CAST(AUDIT_LAST_UPDATED_DTTM AS TIMESTAMP) as WM_AUDIT_LAST_UPDATED_TSTMP",
	"CAST(CREATED_DTTM AS TIMESTAMP) as WM_CREATED_TSTMP",
	"CAST(LAST_UPDATED_DTTM AS TIMESTAMP) as WM_LAST_UPDATED_TSTMP",
	"CAST(UPDATE_TSTMP AS TIMESTAMP) as UPDATE_TSTMP",
	"CAST(LOAD_TSTMP AS TIMESTAMP) as LOAD_TSTMP", 
    "pyspark_data_action" 
)

try:
  primary_key = """source.LOCATION_ID = target.LOCATION_ID AND source.WM_ITEM_ID = target.WM_ITEM_ID"""
#   refined_perf_table = "WM_ITEM_CBO"
  executeMerge(Shortcut_to_WM_ITEM_CBO1, refined_perf_table, primary_key)
  logger.info(f"Merge with {refined_perf_table} completed]")
  logPrevRunDt("WM_ITEM_CBO", "WM_ITEM_CBO", "Completed", "N/A", f"{raw}.log_run_details")
except Exception as e:
  logPrevRunDt("WM_ITEM_CBO", "WM_ITEM_CBO","Failed",str(e), f"{raw}.log_run_details", )
  raise e
	