#Code converted on 2023-06-26 10:05:13
import os
import argparse
from pyspark.sql import *
from pyspark.sql.functions import *
from pyspark.sql.window import Window
from pyspark.sql.types import *
from datetime import datetime
from pyspark.dbutils import DBUtils
from utils.genericUtilities import *
from utils.configs import *
from utils.mergeUtils import *
from utils.logger import *
# COMMAND ----------

parser = argparse.ArgumentParser()
spark = SparkSession.getActiveSession()
dbutils = DBUtils(spark)
parser.add_argument('env', type=str, help='Env Variable')
args = parser.parse_args()
env = args.env

if env is None or env == '':
    raise ValueError('env is not set')

refine = getEnvPrefix(env) + 'refine'
raw = getEnvPrefix(env) + 'raw'
legacy = getEnvPrefix(env) + 'legacy'

# Set global variables
starttime = datetime.now() #start timestamp of the script

# COMMAND ----------
# Processing node SQ_Shortcut_to_WM_COMMODITY_CODE_PRE, type SOURCE 
# COLUMN COUNT: 14

SQ_Shortcut_to_WM_COMMODITY_CODE_PRE = spark.sql(f"""SELECT
WM_COMMODITY_CODE_PRE.DC_NBR,
WM_COMMODITY_CODE_PRE.COMMODITY_CODE_ID,
WM_COMMODITY_CODE_PRE.COMM_CODE_SECTION,
WM_COMMODITY_CODE_PRE.COMM_CODE_CHAPTER,
WM_COMMODITY_CODE_PRE.TC_COMPANY_ID,
WM_COMMODITY_CODE_PRE.DESCRIPTION_SHORT,
WM_COMMODITY_CODE_PRE.DESCRIPTION_LONG,
WM_COMMODITY_CODE_PRE.MARK_FOR_DELETION,
WM_COMMODITY_CODE_PRE.CREATED_SOURCE_TYPE,
WM_COMMODITY_CODE_PRE.CREATED_SOURCE,
WM_COMMODITY_CODE_PRE.CREATED_DTTM,
WM_COMMODITY_CODE_PRE.LAST_UPDATED_SOURCE_TYPE,
WM_COMMODITY_CODE_PRE.LAST_UPDATED_SOURCE,
WM_COMMODITY_CODE_PRE.LAST_UPDATED_DTTM
FROM WM_COMMODITY_CODE_PRE""").withColumn("sys_row_id", monotonically_increasing_id())

# COMMAND ----------
# Processing node SQ_Shortcut_to_WM_COMMODITY_CODE, type SOURCE 
# COLUMN COUNT: 5

SQ_Shortcut_to_WM_COMMODITY_CODE = spark.sql(f"""SELECT
WM_COMMODITY_CODE.LOCATION_ID,
WM_COMMODITY_CODE.WM_COMMODITY_CD_ID,
WM_COMMODITY_CODE.WM_CREATED_TSTMP,
WM_COMMODITY_CODE.WM_LAST_UPDATED_TSTMP,
WM_COMMODITY_CODE.LOAD_TSTMP
FROM WM_COMMODITY_CODE
WHERE WM_COMMODITY_CD_ID IN (SELECT COMMODITY_CODE_ID FROM WM_COMMODITY_CODE_PRE)""").withColumn("sys_row_id", monotonically_increasing_id())

# COMMAND ----------
# Processing node EXP_INT_CONV, type EXPRESSION 
# COLUMN COUNT: 14

# for each involved DataFrame, append the dataframe name to each column
SQ_Shortcut_to_WM_COMMODITY_CODE_PRE_temp = SQ_Shortcut_to_WM_COMMODITY_CODE_PRE.toDF(*["SQ_Shortcut_to_WM_COMMODITY_CODE_PRE___" + col for col in SQ_Shortcut_to_WM_COMMODITY_CODE_PRE.columns])

EXP_INT_CONV = SQ_Shortcut_to_WM_COMMODITY_CODE_PRE_temp.selectExpr( \
	"SQ_Shortcut_to_WM_COMMODITY_CODE_PRE___sys_row_id as sys_row_id", \
	"cast(SQ_Shortcut_to_WM_COMMODITY_CODE_PRE___DC_NBR as int) as o_DC_NBR", \
	"SQ_Shortcut_to_WM_COMMODITY_CODE_PRE___COMMODITY_CODE_ID as COMMODITY_CODE_ID", \
	"SQ_Shortcut_to_WM_COMMODITY_CODE_PRE___COMM_CODE_SECTION as COMM_CODE_SECTION", \
	"SQ_Shortcut_to_WM_COMMODITY_CODE_PRE___COMM_CODE_CHAPTER as COMM_CODE_CHAPTER", \
	"SQ_Shortcut_to_WM_COMMODITY_CODE_PRE___TC_COMPANY_ID as TC_COMPANY_ID", \
	"SQ_Shortcut_to_WM_COMMODITY_CODE_PRE___DESCRIPTION_SHORT as DESCRIPTION_SHORT", \
	"SQ_Shortcut_to_WM_COMMODITY_CODE_PRE___DESCRIPTION_LONG as DESCRIPTION_LONG", \
	"SQ_Shortcut_to_WM_COMMODITY_CODE_PRE___MARK_FOR_DELETION as MARK_FOR_DELETION", \
	"SQ_Shortcut_to_WM_COMMODITY_CODE_PRE___CREATED_SOURCE_TYPE as CREATED_SOURCE_TYPE", \
	"SQ_Shortcut_to_WM_COMMODITY_CODE_PRE___CREATED_SOURCE as CREATED_SOURCE", \
	"SQ_Shortcut_to_WM_COMMODITY_CODE_PRE___CREATED_DTTM as CREATED_DTTM", \
	"SQ_Shortcut_to_WM_COMMODITY_CODE_PRE___LAST_UPDATED_SOURCE_TYPE as LAST_UPDATED_SOURCE_TYPE", \
	"SQ_Shortcut_to_WM_COMMODITY_CODE_PRE___LAST_UPDATED_SOURCE as LAST_UPDATED_SOURCE", \
	"SQ_Shortcut_to_WM_COMMODITY_CODE_PRE___LAST_UPDATED_DTTM as LAST_UPDATED_DTTM" \
)

# COMMAND ----------
# Processing node SQ_Shortcut_to_SITE_PROFILE, type SOURCE 
# COLUMN COUNT: 2

SQ_Shortcut_to_SITE_PROFILE = spark.sql(f"""SELECT
SITE_PROFILE.LOCATION_ID,
SITE_PROFILE.STORE_NBR
FROM SITE_PROFILE""").withColumn("sys_row_id", monotonically_increasing_id())

# COMMAND ----------
# Processing node JNR_SITE_PROFILE, type JOINER 
# COLUMN COUNT: 16

JNR_SITE_PROFILE = EXP_INT_CONV.join(SQ_Shortcut_to_SITE_PROFILE,[EXP_INT_CONV.o_DC_NBR == SQ_Shortcut_to_SITE_PROFILE.STORE_NBR],'inner')

# COMMAND ----------
# Processing node JNR_WM_COMMODITY_CODE, type JOINER . Note: using additional SELECT to rename incoming columns
# COLUMN COUNT: 19

# for each involved DataFrame, append the dataframe name to each column
SQ_Shortcut_to_WM_COMMODITY_CODE_temp = SQ_Shortcut_to_WM_COMMODITY_CODE.toDF(*["SQ_Shortcut_to_WM_COMMODITY_CODE___" + col for col in SQ_Shortcut_to_WM_COMMODITY_CODE.columns])
JNR_SITE_PROFILE_temp = JNR_SITE_PROFILE.toDF(*["JNR_SITE_PROFILE___" + col for col in JNR_SITE_PROFILE.columns])

JNR_WM_COMMODITY_CODE = SQ_Shortcut_to_WM_COMMODITY_CODE_temp.join(JNR_SITE_PROFILE_temp,[SQ_Shortcut_to_WM_COMMODITY_CODE_temp.SQ_Shortcut_to_WM_COMMODITY_CODE___LOCATION_ID == JNR_SITE_PROFILE_temp.JNR_SITE_PROFILE___LOCATION_ID, SQ_Shortcut_to_WM_COMMODITY_CODE_temp.SQ_Shortcut_to_WM_COMMODITY_CODE___WM_COMMODITY_CD_ID == JNR_SITE_PROFILE_temp.JNR_SITE_PROFILE___COMMODITY_CODE_ID],'right_outer').selectExpr( \
	"JNR_SITE_PROFILE___LOCATION_ID as LOCATION_ID", \
	"JNR_SITE_PROFILE___COMMODITY_CODE_ID as COMMODITY_CODE_ID", \
	"JNR_SITE_PROFILE___COMM_CODE_SECTION as COMM_CODE_SECTION", \
	"JNR_SITE_PROFILE___COMM_CODE_CHAPTER as COMM_CODE_CHAPTER", \
	"JNR_SITE_PROFILE___TC_COMPANY_ID as TC_COMPANY_ID", \
	"JNR_SITE_PROFILE___DESCRIPTION_SHORT as DESCRIPTION_SHORT", \
	"JNR_SITE_PROFILE___DESCRIPTION_LONG as DESCRIPTION_LONG", \
	"JNR_SITE_PROFILE___MARK_FOR_DELETION as MARK_FOR_DELETION", \
	"JNR_SITE_PROFILE___CREATED_SOURCE_TYPE as CREATED_SOURCE_TYPE", \
	"JNR_SITE_PROFILE___CREATED_SOURCE as CREATED_SOURCE", \
	"JNR_SITE_PROFILE___CREATED_DTTM as CREATED_DTTM", \
	"JNR_SITE_PROFILE___LAST_UPDATED_SOURCE_TYPE as LAST_UPDATED_SOURCE_TYPE", \
	"JNR_SITE_PROFILE___LAST_UPDATED_SOURCE as LAST_UPDATED_SOURCE", \
	"JNR_SITE_PROFILE___LAST_UPDATED_DTTM as LAST_UPDATED_DTTM", \
	"SQ_Shortcut_to_WM_COMMODITY_CODE___LOCATION_ID as i_LOCATION_ID1", \
	"SQ_Shortcut_to_WM_COMMODITY_CODE___WM_COMMODITY_CD_ID as i_WM_COMMODITY_CD_ID", \
	"SQ_Shortcut_to_WM_COMMODITY_CODE___WM_CREATED_TSTMP as i_WM_CREATED_TSTMP", \
	"SQ_Shortcut_to_WM_COMMODITY_CODE___WM_LAST_UPDATED_TSTMP as i_WM_LAST_UPDATED_TSTMP", \
	"SQ_Shortcut_to_WM_COMMODITY_CODE___LOAD_TSTMP as i_LOAD_TSTMP")

# COMMAND ----------
# Processing node FIL_UNCHANGED_RECORDS, type FILTER 
# COLUMN COUNT: 18

# for each involved DataFrame, append the dataframe name to each column
JNR_WM_COMMODITY_CODE_temp = JNR_WM_COMMODITY_CODE.toDF(*["JNR_WM_COMMODITY_CODE___" + col for col in JNR_WM_COMMODITY_CODE.columns])

FIL_UNCHANGED_RECORDS = JNR_WM_COMMODITY_CODE_temp.selectExpr( \
	"JNR_WM_COMMODITY_CODE___LOCATION_ID as LOCATION_ID", \
	"JNR_WM_COMMODITY_CODE___COMMODITY_CODE_ID as COMMODITY_CODE_ID", \
	"JNR_WM_COMMODITY_CODE___COMM_CODE_SECTION as COMM_CODE_SECTION", \
	"JNR_WM_COMMODITY_CODE___COMM_CODE_CHAPTER as COMM_CODE_CHAPTER", \
	"JNR_WM_COMMODITY_CODE___TC_COMPANY_ID as TC_COMPANY_ID", \
	"JNR_WM_COMMODITY_CODE___DESCRIPTION_SHORT as DESCRIPTION_SHORT", \
	"JNR_WM_COMMODITY_CODE___DESCRIPTION_LONG as DESCRIPTION_LONG", \
	"JNR_WM_COMMODITY_CODE___MARK_FOR_DELETION as MARK_FOR_DELETION", \
	"JNR_WM_COMMODITY_CODE___CREATED_SOURCE_TYPE as CREATED_SOURCE_TYPE", \
	"JNR_WM_COMMODITY_CODE___CREATED_SOURCE as CREATED_SOURCE", \
	"JNR_WM_COMMODITY_CODE___CREATED_DTTM as CREATED_DTTM", \
	"JNR_WM_COMMODITY_CODE___LAST_UPDATED_SOURCE_TYPE as LAST_UPDATED_SOURCE_TYPE", \
	"JNR_WM_COMMODITY_CODE___LAST_UPDATED_SOURCE as LAST_UPDATED_SOURCE", \
	"JNR_WM_COMMODITY_CODE___LAST_UPDATED_DTTM as LAST_UPDATED_DTTM", \
	"JNR_WM_COMMODITY_CODE___i_WM_COMMODITY_CD_ID as i_WM_COMMODITY_CD_ID", \
	"JNR_WM_COMMODITY_CODE___i_WM_CREATED_TSTMP as i_WM_CREATED_TSTMP", \
	"JNR_WM_COMMODITY_CODE___i_WM_LAST_UPDATED_TSTMP as i_WM_LAST_UPDATED_TSTMP", \
	"JNR_WM_COMMODITY_CODE___i_LOAD_TSTMP as i_LOAD_TSTMP")\
    .filter("i_WM_COMMODITY_CD_ID is Null OR (  i_WM_COMMODITY_CD_ID is NOT Null AND ( COALESCE(CREATE_DATE_TIME, date'1900-01-01') != COALESCE(i_WM_CREATE_TSTMP, date'1900-01-01') \
            OR COALESCE(LAST_UPDATED_DTTM, date'1900-01-01') != COALESCE(i_WM_LAST_UPDATED_TSTMP, date'1900-01-01') ) )").withColumn("sys_row_id", monotonically_increasing_id())


# COMMAND ----------
# Processing node EXP_OUTPUT_VALIDATOR, type EXPRESSION 
# COLUMN COUNT: 17

# for each involved DataFrame, append the dataframe name to each column
FIL_UNCHANGED_RECORDS_temp = FIL_UNCHANGED_RECORDS.toDF(*["FIL_UNCHANGED_RECORDS___" + col for col in FIL_UNCHANGED_RECORDS.columns])

EXP_OUTPUT_VALIDATOR = FIL_UNCHANGED_RECORDS_temp.selectExpr( \
	"FIL_UNCHANGED_RECORDS___sys_row_id as sys_row_id", \
	"FIL_UNCHANGED_RECORDS___LOCATION_ID as LOCATION_ID", \
	"FIL_UNCHANGED_RECORDS___COMMODITY_CODE_ID as COMMODITY_CODE_ID", \
	"FIL_UNCHANGED_RECORDS___COMM_CODE_SECTION as COMM_CODE_SECTION", \
	"FIL_UNCHANGED_RECORDS___COMM_CODE_CHAPTER as COMM_CODE_CHAPTER", \
	"FIL_UNCHANGED_RECORDS___TC_COMPANY_ID as TC_COMPANY_ID", \
	"FIL_UNCHANGED_RECORDS___DESCRIPTION_SHORT as DESCRIPTION_SHORT", \
	"FIL_UNCHANGED_RECORDS___DESCRIPTION_LONG as DESCRIPTION_LONG", \
	"FIL_UNCHANGED_RECORDS___MARK_FOR_DELETION as MARK_FOR_DELETION", \
	"FIL_UNCHANGED_RECORDS___CREATED_SOURCE_TYPE as CREATED_SOURCE_TYPE", \
	"FIL_UNCHANGED_RECORDS___CREATED_SOURCE as CREATED_SOURCE", \
	"FIL_UNCHANGED_RECORDS___CREATED_DTTM as CREATED_DTTM", \
	"FIL_UNCHANGED_RECORDS___LAST_UPDATED_SOURCE_TYPE as LAST_UPDATED_SOURCE_TYPE", \
	"FIL_UNCHANGED_RECORDS___LAST_UPDATED_SOURCE as LAST_UPDATED_SOURCE", \
	"FIL_UNCHANGED_RECORDS___LAST_UPDATED_DTTM as LAST_UPDATED_DTTM", \
	"CURRENT_TIMESTAMP as UPDATE_TSTMP", \
	"IF (FIL_UNCHANGED_RECORDS___i_LOAD_TSTMP IS NULL, CURRENT_TIMESTAMP, FIL_UNCHANGED_RECORDS___i_LOAD_TSTMP) as LOAD_TSTMP", \
	"IF (FIL_UNCHANGED_RECORDS___i_WM_COMMODITY_CD_ID IS NULL, 1, 2) as o_UPDATE_VALIDATOR" \
)

# COMMAND ----------
# Processing node UPD_INS_UPD, type UPDATE_STRATEGY 
# COLUMN COUNT: 17

# for each involved DataFrame, append the dataframe name to each column
EXP_OUTPUT_VALIDATOR_temp = EXP_OUTPUT_VALIDATOR.toDF(*["EXP_OUTPUT_VALIDATOR___" + col for col in EXP_OUTPUT_VALIDATOR.columns])

UPD_INS_UPD = EXP_OUTPUT_VALIDATOR_temp.selectExpr( \
	"EXP_OUTPUT_VALIDATOR___LOCATION_ID as LOCATION_ID", \
	"EXP_OUTPUT_VALIDATOR___COMMODITY_CODE_ID as COMMODITY_CODE_ID", \
	"EXP_OUTPUT_VALIDATOR___COMM_CODE_SECTION as COMM_CODE_SECTION", \
	"EXP_OUTPUT_VALIDATOR___COMM_CODE_CHAPTER as COMM_CODE_CHAPTER", \
	"EXP_OUTPUT_VALIDATOR___TC_COMPANY_ID as TC_COMPANY_ID", \
	"EXP_OUTPUT_VALIDATOR___DESCRIPTION_SHORT as DESCRIPTION_SHORT", \
	"EXP_OUTPUT_VALIDATOR___DESCRIPTION_LONG as DESCRIPTION_LONG", \
	"EXP_OUTPUT_VALIDATOR___MARK_FOR_DELETION as MARK_FOR_DELETION", \
	"EXP_OUTPUT_VALIDATOR___CREATED_SOURCE_TYPE as CREATED_SOURCE_TYPE", \
	"EXP_OUTPUT_VALIDATOR___CREATED_SOURCE as CREATED_SOURCE", \
	"EXP_OUTPUT_VALIDATOR___CREATED_DTTM as CREATED_DTTM", \
	"EXP_OUTPUT_VALIDATOR___LAST_UPDATED_SOURCE_TYPE as LAST_UPDATED_SOURCE_TYPE", \
	"EXP_OUTPUT_VALIDATOR___LAST_UPDATED_SOURCE as LAST_UPDATED_SOURCE", \
	"EXP_OUTPUT_VALIDATOR___LAST_UPDATED_DTTM as LAST_UPDATED_DTTM", \
	"EXP_OUTPUT_VALIDATOR___UPDATE_TSTMP as UPDATE_TSTMP", \
	"EXP_OUTPUT_VALIDATOR___LOAD_TSTMP as LOAD_TSTMP", \
	"EXP_OUTPUT_VALIDATOR___o_UPDATE_VALIDATOR as o_UPDATE_VALIDATOR") \
	.withColumn('pyspark_data_action', when(EXP_OUTPUT_VALIDATOR.o_UPDATE_VALIDATOR ==(lit(1)) , lit(0)) .when(EXP_OUTPUT_VALIDATOR.o_UPDATE_VALIDATOR ==(lit(2)) , lit(1)))

# COMMAND ----------
# Processing node Shortcut_to_WM_COMMODITY_CODE1, type TARGET 
# COLUMN COUNT: 16

try:
  primary_key = """source.LOCATION_ID = target.LOCATION_ID AND source.WM_COMMODITY_CD_ID = target.WM_COMMODITY_CD_ID"""
  refined_perf_table = "WM_COMMODITY_CODE"
  executeMerge(UPD_INS_UPD, refined_perf_table, primary_key)
  logger.info(f"Merge with {refined_perf_table} completed]")
  logPrevRunDt("WM_COMMODITY_CODE", "WM_COMMODITY_CODE", "Completed", "N/A", f"{raw}.log_run_details")
except Exception as e:
  logPrevRunDt("WM_COMMODITY_CODE", "WM_COMMODITY_CODE","Failed",str(e), f"{raw}.log_run_details", )
  raise e
	