#Code converted on 2023-06-26 17:58:52
import os
import argparse
from pyspark.sql import *
from pyspark.sql.functions import *
from pyspark.sql.window import Window
from pyspark.sql.types import *
from datetime import datetime
from pyspark.dbutils import DBUtils
from Datalake.utils.genericUtilities import *
from Datalake.utils.configs import *
from Datalake.utils.mergeUtils import *
from Datalake.utils.logger import *
# COMMAND ----------

parser = argparse.ArgumentParser()
spark = SparkSession.getActiveSession()
dbutils = DBUtils(spark)

parser.add_argument('env', type=str, help='Env Variable')
#args = parser.parse_args()
#env = args.env
env = 'dev'

if env is None or env == '':
    raise ValueError('env is not set')

refine = getEnvPrefix(env) + 'refine'
raw = getEnvPrefix(env) + 'raw'
legacy = getEnvPrefix(env) + 'legacy'

# Set global variables
starttime = datetime.now() #start timestamp of the script
refined_perf_table = f"{refine}.WM_ORDER_LINE_ITEM"
raw_perf_table = f"{raw}.WM_ORDER_LINE_ITEM_PRE"
site_profile_table = f"{legacy}.SITE_PROFILE"

# COMMAND ----------
# Processing node SQ_Shortcut_to_WM_ORDER_LINE_ITEM, type SOURCE 
# COLUMN COUNT: 6

SQ_Shortcut_to_WM_ORDER_LINE_ITEM = spark.sql(f"""SELECT
LOCATION_ID,
WM_ORDER_ID,
WM_LINE_ITEM_ID,
WM_CREATED_TSTMP,
WM_LAST_UPDATED_TSTMP,
LOAD_TSTMP
FROM {refined_perf_table}
WHERE WM_ORDER_ID IN (SELECT ORDER_ID FROM {raw_perf_table})""").withColumn("sys_row_id", monotonically_increasing_id())

# COMMAND ----------
# Processing node SQ_Shortcut_to_WM_ORDER_LINE_ITEM_PRE, type SOURCE 
# COLUMN COUNT: 209

SQ_Shortcut_to_WM_ORDER_LINE_ITEM_PRE = spark.sql(f"""SELECT
DC_NBR,
ORDER_ID,
LINE_ITEM_ID,
PARENT_LINE_ITEM_ID,
TC_COMPANY_ID,
COMMODITY_CLASS,
REF_FIELD1,
REF_FIELD2,
REF_FIELD3,
EXT_SYS_LINE_ITEM_ID,
MASTER_ORDER_ID,
MO_LINE_ITEM_ID,
IS_HAZMAT,
IS_STACKABLE,
HAS_ERRORS,
ORIG_BUDG_COST,
BUDG_COST_CURRENCY_CODE,
BUDG_COST,
ACTUAL_COST_CURRENCY_CODE,
TOTAL_MONETARY_VALUE,
UNIT_MONETARY_VALUE,
UNIT_TAX_AMOUNT,
RTS_ID,
RTS_LINE_ITEM_ID,
STD_PACK_QTY,
PRODUCT_CLASS_ID,
PROTECTION_LEVEL_ID,
PACKAGE_TYPE_ID,
COMMODITY_CODE_ID,
MV_SIZE_UOM_ID,
QTY_UOM_ID_BASE,
MV_CURRENCY_CODE,
SHIPPED_QTY,
RECEIVED_QTY,
PRIORITY,
MERCHANDIZING_DEPARTMENT_ID,
UN_NUMBER_ID,
PICKUP_REFERENCE_NUMBER,
DELIVERY_REFERENCE_NUMBER,
CNTRY_OF_ORGN,
PROD_STAT,
STACK_RANK,
STACK_LENGTH_VALUE,
STACK_LENGTH_STANDARD_UOM,
STACK_WIDTH_VALUE,
STACK_WIDTH_STANDARD_UOM,
STACK_HEIGHT_VALUE,
STACK_HEIGHT_STANDARD_UOM,
STACK_DIAMETER_VALUE,
STACK_DIAMETER_STANDARD_UOM,
CREATED_SOURCE_TYPE,
CREATED_SOURCE,
CREATED_DTTM,
LAST_UPDATED_SOURCE_TYPE,
LAST_UPDATED_SOURCE,
LAST_UPDATED_DTTM,
HIBERNATE_VERSION,
CUBE_MULTIPLE_QTY,
DO_DTL_STATUS,
INTERNAL_ORDER_SEQ_NBR,
IS_EMERGENCY,
LPN_SIZE,
MANUFACTURING_DTTM,
ORDER_LINE_ID,
PACK_RATE,
ALLOCATED_QTY,
PLANNED_SHIP_DATE,
PPACK_QTY,
STD_BUNDLE_QTY,
STD_LPN_QTY,
STD_LPN_VOL,
STD_LPN_WT,
UNIT_COST,
UNIT_PRICE_AMOUNT,
UNIT_VOL,
UNIT_WT,
USER_CANCELED_QTY,
WAVE_PROC_TYPE,
DELIVERY_END_DTTM,
DELIVERY_START_DTTM,
EVENT_CODE,
REASON_CODE,
EXP_INFO_CODE,
PARTL_FILL,
LINE_TYPE,
REPL_PROC_TYPE,
ORDER_QTY,
ORIG_ORDER_QTY,
RTL_TO_BE_DISTROED_QTY,
PRICE,
RETAIL_PRICE,
UNITS_PAKD,
MINOR_ORDER_NBR,
ITEM_ID,
TC_ORDER_LINE_ID,
ACTUAL_SHIPPED_DTTM,
QTY_UOM_ID,
PICKUP_END_DTTM,
PURCHASE_ORDER_LINE_NUMBER,
PICKUP_START_DTTM,
REFERENCE_LINE_ITEM_ID,
REFERENCE_ORDER_ID,
REPL_WAVE_RUN,
STD_PALLET_QTY,
STD_SUB_PACK_QTY,
STORE_DEPT,
ALLOC_TYPE,
BATCH_NBR,
BATCH_REQUIREMENT_TYPE,
CHUTE_ASSIGN_TYPE,
CUSTOM_TAG,
CUSTOMER_ITEM,
INTERNAL_ORDER_ID,
INVN_TYPE,
ITEM_ATTR_1,
ITEM_ATTR_2,
ITEM_ATTR_3,
ITEM_ATTR_4,
ITEM_ATTR_5,
LPN_BRK_ATTRIB,
MERCH_GRP,
MERCH_TYPE,
PACK_ZONE,
PALLET_TYPE,
PICK_LOCN_ASSIGN_TYPE,
PICK_LOCN_ID,
PPACK_GRP_CODE,
PRICE_TKT_TYPE,
SERIAL_NUMBER_REQUIRED_FLAG,
SKU_GTIN,
SKU_SUB_CODE_ID,
SKU_SUB_CODE_VALUE,
VAS_PROCESS_TYPE,
SUBSTITUTED_PARENT_LINE_ID,
IS_CANCELLED,
ITEM_NAME,
ALLOC_LINE_ID,
ALLOCATION_SOURCE_ID,
ALLOCATION_SOURCE_LINE_ID,
ALLOCATION_SOURCE,
SHELF_DAYS,
FULFILLMENT_TYPE,
WAVE_NBR,
SHIP_WAVE_NBR,
REPL_WAVE_NBR,
SINGLE_UNIT_FLAG,
ACTUAL_COST,
QTY_CONV_FACTOR,
PLANNED_WEIGHT,
RECEIVED_WEIGHT,
SHIPPED_WEIGHT,
WEIGHT_UOM_ID_BASE,
WEIGHT_UOM_ID,
PLANNED_VOLUME,
RECEIVED_VOLUME,
SHIPPED_VOLUME,
VOLUME_UOM_ID_BASE,
VOLUME_UOM_ID,
SIZE1_UOM_ID,
SIZE1_VALUE,
RECEIVED_SIZE1,
SHIPPED_SIZE1,
SIZE2_UOM_ID,
SIZE2_VALUE,
RECEIVED_SIZE2,
SHIPPED_SIZE2,
LPN_TYPE,
ORDER_CONSOL_ATTR,
SKU_BREAK_ATTR,
PURCHASE_ORDER_NUMBER,
EXT_PURCHASE_ORDER,
CRITCL_DIM_1,
CRITCL_DIM_2,
CRITCL_DIM_3,
ASSORT_NBR,
DESCRIPTION,
ORIGINAL_ORDERED_ITEM_ID,
SUBSTITUTION_TYPE,
BACK_ORD_REASON,
FREIGHT_REVENUE_CURRENCY_CODE,
FREIGHT_REVENUE,
IS_CHASE_CREATED_LINE,
REF_FIELD4,
REF_FIELD5,
REF_FIELD6,
REF_FIELD7,
REF_FIELD8,
REF_FIELD9,
REF_FIELD10,
REF_NUM1,
REF_NUM2,
REF_NUM3,
REF_NUM4,
REF_NUM5,
IS_GIFT,
ADJUSTED_ORDER_QTY,
PRE_RECEIPT_STATUS,
ALLOW_REVIVAL_RECEIPT_ALLOC,
SEGMENT_NAME,
EFFECTIVE_RANK,
WM_RECEIPT_ALLOCATED,
GIFT_CARD_VALUE,
REF_BOOLEAN1,
REF_BOOLEAN2,
REF_SYSCODE1,
REF_SYSCODE2,
REF_SYSCODE3,
HARD_ALLOC_REASON_CODE,
LOCKED
FROM {raw_perf_table}""").withColumn("sys_row_id", monotonically_increasing_id())

# COMMAND ----------
# Processing node EXP_INT_CONVERSION, type EXPRESSION 
# COLUMN COUNT: 209

# for each involved DataFrame, append the dataframe name to each column
SQ_Shortcut_to_WM_ORDER_LINE_ITEM_PRE_temp = SQ_Shortcut_to_WM_ORDER_LINE_ITEM_PRE.toDF(*["SQ_Shortcut_to_WM_ORDER_LINE_ITEM_PRE___" + col for col in SQ_Shortcut_to_WM_ORDER_LINE_ITEM_PRE.columns])

EXP_INT_CONVERSION = SQ_Shortcut_to_WM_ORDER_LINE_ITEM_PRE_temp.selectExpr( \
	"SQ_Shortcut_to_WM_ORDER_LINE_ITEM_PRE___sys_row_id as sys_row_id", \
	"cast(SQ_Shortcut_to_WM_ORDER_LINE_ITEM_PRE___DC_NBR as int) as o_DC_NBR", \
	"SQ_Shortcut_to_WM_ORDER_LINE_ITEM_PRE___ORDER_ID as ORDER_ID", \
	"SQ_Shortcut_to_WM_ORDER_LINE_ITEM_PRE___LINE_ITEM_ID as LINE_ITEM_ID", \
	"SQ_Shortcut_to_WM_ORDER_LINE_ITEM_PRE___PARENT_LINE_ITEM_ID as PARENT_LINE_ITEM_ID", \
	"SQ_Shortcut_to_WM_ORDER_LINE_ITEM_PRE___TC_COMPANY_ID as TC_COMPANY_ID", \
	"SQ_Shortcut_to_WM_ORDER_LINE_ITEM_PRE___COMMODITY_CLASS as COMMODITY_CLASS", \
	"SQ_Shortcut_to_WM_ORDER_LINE_ITEM_PRE___REF_FIELD1 as REF_FIELD1", \
	"SQ_Shortcut_to_WM_ORDER_LINE_ITEM_PRE___REF_FIELD2 as REF_FIELD2", \
	"SQ_Shortcut_to_WM_ORDER_LINE_ITEM_PRE___REF_FIELD3 as REF_FIELD3", \
	"SQ_Shortcut_to_WM_ORDER_LINE_ITEM_PRE___EXT_SYS_LINE_ITEM_ID as EXT_SYS_LINE_ITEM_ID", \
	"SQ_Shortcut_to_WM_ORDER_LINE_ITEM_PRE___MASTER_ORDER_ID as MASTER_ORDER_ID", \
	"SQ_Shortcut_to_WM_ORDER_LINE_ITEM_PRE___MO_LINE_ITEM_ID as MO_LINE_ITEM_ID", \
	"SQ_Shortcut_to_WM_ORDER_LINE_ITEM_PRE___IS_HAZMAT as IS_HAZMAT", \
	"SQ_Shortcut_to_WM_ORDER_LINE_ITEM_PRE___IS_STACKABLE as IS_STACKABLE", \
	"SQ_Shortcut_to_WM_ORDER_LINE_ITEM_PRE___HAS_ERRORS as HAS_ERRORS", \
	"SQ_Shortcut_to_WM_ORDER_LINE_ITEM_PRE___ORIG_BUDG_COST as ORIG_BUDG_COST", \
	"SQ_Shortcut_to_WM_ORDER_LINE_ITEM_PRE___BUDG_COST_CURRENCY_CODE as BUDG_COST_CURRENCY_CODE", \
	"SQ_Shortcut_to_WM_ORDER_LINE_ITEM_PRE___BUDG_COST as BUDG_COST", \
	"SQ_Shortcut_to_WM_ORDER_LINE_ITEM_PRE___ACTUAL_COST_CURRENCY_CODE as ACTUAL_COST_CURRENCY_CODE", \
	"SQ_Shortcut_to_WM_ORDER_LINE_ITEM_PRE___TOTAL_MONETARY_VALUE as TOTAL_MONETARY_VALUE", \
	"SQ_Shortcut_to_WM_ORDER_LINE_ITEM_PRE___UNIT_MONETARY_VALUE as UNIT_MONETARY_VALUE", \
	"SQ_Shortcut_to_WM_ORDER_LINE_ITEM_PRE___UNIT_TAX_AMOUNT as UNIT_TAX_AMOUNT", \
	"SQ_Shortcut_to_WM_ORDER_LINE_ITEM_PRE___RTS_ID as RTS_ID", \
	"SQ_Shortcut_to_WM_ORDER_LINE_ITEM_PRE___RTS_LINE_ITEM_ID as RTS_LINE_ITEM_ID", \
	"SQ_Shortcut_to_WM_ORDER_LINE_ITEM_PRE___STD_PACK_QTY as STD_PACK_QTY", \
	"SQ_Shortcut_to_WM_ORDER_LINE_ITEM_PRE___PRODUCT_CLASS_ID as PRODUCT_CLASS_ID", \
	"SQ_Shortcut_to_WM_ORDER_LINE_ITEM_PRE___PROTECTION_LEVEL_ID as PROTECTION_LEVEL_ID", \
	"SQ_Shortcut_to_WM_ORDER_LINE_ITEM_PRE___PACKAGE_TYPE_ID as PACKAGE_TYPE_ID", \
	"SQ_Shortcut_to_WM_ORDER_LINE_ITEM_PRE___COMMODITY_CODE_ID as COMMODITY_CODE_ID", \
	"SQ_Shortcut_to_WM_ORDER_LINE_ITEM_PRE___MV_SIZE_UOM_ID as MV_SIZE_UOM_ID", \
	"SQ_Shortcut_to_WM_ORDER_LINE_ITEM_PRE___QTY_UOM_ID_BASE as QTY_UOM_ID_BASE", \
	"SQ_Shortcut_to_WM_ORDER_LINE_ITEM_PRE___MV_CURRENCY_CODE as MV_CURRENCY_CODE", \
	"SQ_Shortcut_to_WM_ORDER_LINE_ITEM_PRE___SHIPPED_QTY as SHIPPED_QTY", \
	"SQ_Shortcut_to_WM_ORDER_LINE_ITEM_PRE___RECEIVED_QTY as RECEIVED_QTY", \
	"SQ_Shortcut_to_WM_ORDER_LINE_ITEM_PRE___PRIORITY as PRIORITY", \
	"SQ_Shortcut_to_WM_ORDER_LINE_ITEM_PRE___MERCHANDIZING_DEPARTMENT_ID as MERCHANDIZING_DEPARTMENT_ID", \
	"SQ_Shortcut_to_WM_ORDER_LINE_ITEM_PRE___UN_NUMBER_ID as UN_NUMBER_ID", \
	"SQ_Shortcut_to_WM_ORDER_LINE_ITEM_PRE___PICKUP_REFERENCE_NUMBER as PICKUP_REFERENCE_NUMBER", \
	"SQ_Shortcut_to_WM_ORDER_LINE_ITEM_PRE___DELIVERY_REFERENCE_NUMBER as DELIVERY_REFERENCE_NUMBER", \
	"SQ_Shortcut_to_WM_ORDER_LINE_ITEM_PRE___CNTRY_OF_ORGN as CNTRY_OF_ORGN", \
	"SQ_Shortcut_to_WM_ORDER_LINE_ITEM_PRE___PROD_STAT as PROD_STAT", \
	"SQ_Shortcut_to_WM_ORDER_LINE_ITEM_PRE___STACK_RANK as STACK_RANK", \
	"SQ_Shortcut_to_WM_ORDER_LINE_ITEM_PRE___STACK_LENGTH_VALUE as STACK_LENGTH_VALUE", \
	"SQ_Shortcut_to_WM_ORDER_LINE_ITEM_PRE___STACK_LENGTH_STANDARD_UOM as STACK_LENGTH_STANDARD_UOM", \
	"SQ_Shortcut_to_WM_ORDER_LINE_ITEM_PRE___STACK_WIDTH_VALUE as STACK_WIDTH_VALUE", \
	"SQ_Shortcut_to_WM_ORDER_LINE_ITEM_PRE___STACK_WIDTH_STANDARD_UOM as STACK_WIDTH_STANDARD_UOM", \
	"SQ_Shortcut_to_WM_ORDER_LINE_ITEM_PRE___STACK_HEIGHT_VALUE as STACK_HEIGHT_VALUE", \
	"SQ_Shortcut_to_WM_ORDER_LINE_ITEM_PRE___STACK_HEIGHT_STANDARD_UOM as STACK_HEIGHT_STANDARD_UOM", \
	"SQ_Shortcut_to_WM_ORDER_LINE_ITEM_PRE___STACK_DIAMETER_VALUE as STACK_DIAMETER_VALUE", \
	"SQ_Shortcut_to_WM_ORDER_LINE_ITEM_PRE___STACK_DIAMETER_STANDARD_UOM as STACK_DIAMETER_STANDARD_UOM", \
	"SQ_Shortcut_to_WM_ORDER_LINE_ITEM_PRE___CREATED_SOURCE_TYPE as CREATED_SOURCE_TYPE", \
	"SQ_Shortcut_to_WM_ORDER_LINE_ITEM_PRE___CREATED_SOURCE as CREATED_SOURCE", \
	"SQ_Shortcut_to_WM_ORDER_LINE_ITEM_PRE___CREATED_DTTM as CREATED_DTTM", \
	"SQ_Shortcut_to_WM_ORDER_LINE_ITEM_PRE___LAST_UPDATED_SOURCE_TYPE as LAST_UPDATED_SOURCE_TYPE", \
	"SQ_Shortcut_to_WM_ORDER_LINE_ITEM_PRE___LAST_UPDATED_SOURCE as LAST_UPDATED_SOURCE", \
	"SQ_Shortcut_to_WM_ORDER_LINE_ITEM_PRE___LAST_UPDATED_DTTM as LAST_UPDATED_DTTM", \
	"SQ_Shortcut_to_WM_ORDER_LINE_ITEM_PRE___HIBERNATE_VERSION as HIBERNATE_VERSION", \
	"SQ_Shortcut_to_WM_ORDER_LINE_ITEM_PRE___CUBE_MULTIPLE_QTY as CUBE_MULTIPLE_QTY", \
	"SQ_Shortcut_to_WM_ORDER_LINE_ITEM_PRE___DO_DTL_STATUS as DO_DTL_STATUS", \
	"SQ_Shortcut_to_WM_ORDER_LINE_ITEM_PRE___INTERNAL_ORDER_SEQ_NBR as INTERNAL_ORDER_SEQ_NBR", \
	"SQ_Shortcut_to_WM_ORDER_LINE_ITEM_PRE___IS_EMERGENCY as IS_EMERGENCY", \
	"SQ_Shortcut_to_WM_ORDER_LINE_ITEM_PRE___LPN_SIZE as LPN_SIZE", \
	"SQ_Shortcut_to_WM_ORDER_LINE_ITEM_PRE___MANUFACTURING_DTTM as MANUFACTURING_DTTM", \
	"SQ_Shortcut_to_WM_ORDER_LINE_ITEM_PRE___ORDER_LINE_ID as ORDER_LINE_ID", \
	"SQ_Shortcut_to_WM_ORDER_LINE_ITEM_PRE___PACK_RATE as PACK_RATE", \
	"SQ_Shortcut_to_WM_ORDER_LINE_ITEM_PRE___ALLOCATED_QTY as ALLOCATED_QTY", \
	"SQ_Shortcut_to_WM_ORDER_LINE_ITEM_PRE___PLANNED_SHIP_DATE as PLANNED_SHIP_DATE", \
	"SQ_Shortcut_to_WM_ORDER_LINE_ITEM_PRE___PPACK_QTY as PPACK_QTY", \
	"SQ_Shortcut_to_WM_ORDER_LINE_ITEM_PRE___STD_BUNDLE_QTY as STD_BUNDLE_QTY", \
	"SQ_Shortcut_to_WM_ORDER_LINE_ITEM_PRE___STD_LPN_QTY as STD_LPN_QTY", \
	"SQ_Shortcut_to_WM_ORDER_LINE_ITEM_PRE___STD_LPN_VOL as STD_LPN_VOL", \
	"SQ_Shortcut_to_WM_ORDER_LINE_ITEM_PRE___STD_LPN_WT as STD_LPN_WT", \
	"SQ_Shortcut_to_WM_ORDER_LINE_ITEM_PRE___UNIT_COST as UNIT_COST", \
	"SQ_Shortcut_to_WM_ORDER_LINE_ITEM_PRE___UNIT_PRICE_AMOUNT as UNIT_PRICE_AMOUNT", \
	"SQ_Shortcut_to_WM_ORDER_LINE_ITEM_PRE___UNIT_VOL as UNIT_VOL", \
	"SQ_Shortcut_to_WM_ORDER_LINE_ITEM_PRE___UNIT_WT as UNIT_WT", \
	"SQ_Shortcut_to_WM_ORDER_LINE_ITEM_PRE___USER_CANCELED_QTY as USER_CANCELED_QTY", \
	"SQ_Shortcut_to_WM_ORDER_LINE_ITEM_PRE___WAVE_PROC_TYPE as WAVE_PROC_TYPE", \
	"SQ_Shortcut_to_WM_ORDER_LINE_ITEM_PRE___DELIVERY_END_DTTM as DELIVERY_END_DTTM", \
	"SQ_Shortcut_to_WM_ORDER_LINE_ITEM_PRE___DELIVERY_START_DTTM as DELIVERY_START_DTTM", \
	"SQ_Shortcut_to_WM_ORDER_LINE_ITEM_PRE___EVENT_CODE as EVENT_CODE", \
	"SQ_Shortcut_to_WM_ORDER_LINE_ITEM_PRE___REASON_CODE as REASON_CODE", \
	"SQ_Shortcut_to_WM_ORDER_LINE_ITEM_PRE___EXP_INFO_CODE as EXP_INFO_CODE", \
	"SQ_Shortcut_to_WM_ORDER_LINE_ITEM_PRE___PARTL_FILL as PARTL_FILL", \
	"SQ_Shortcut_to_WM_ORDER_LINE_ITEM_PRE___LINE_TYPE as LINE_TYPE", \
	"SQ_Shortcut_to_WM_ORDER_LINE_ITEM_PRE___REPL_PROC_TYPE as REPL_PROC_TYPE", \
	"SQ_Shortcut_to_WM_ORDER_LINE_ITEM_PRE___ORDER_QTY as ORDER_QTY", \
	"SQ_Shortcut_to_WM_ORDER_LINE_ITEM_PRE___ORIG_ORDER_QTY as ORIG_ORDER_QTY", \
	"SQ_Shortcut_to_WM_ORDER_LINE_ITEM_PRE___RTL_TO_BE_DISTROED_QTY as RTL_TO_BE_DISTROED_QTY", \
	"SQ_Shortcut_to_WM_ORDER_LINE_ITEM_PRE___PRICE as PRICE", \
	"SQ_Shortcut_to_WM_ORDER_LINE_ITEM_PRE___RETAIL_PRICE as RETAIL_PRICE", \
	"SQ_Shortcut_to_WM_ORDER_LINE_ITEM_PRE___UNITS_PAKD as UNITS_PAKD", \
	"SQ_Shortcut_to_WM_ORDER_LINE_ITEM_PRE___MINOR_ORDER_NBR as MINOR_ORDER_NBR", \
	"SQ_Shortcut_to_WM_ORDER_LINE_ITEM_PRE___ITEM_ID as ITEM_ID", \
	"SQ_Shortcut_to_WM_ORDER_LINE_ITEM_PRE___TC_ORDER_LINE_ID as TC_ORDER_LINE_ID", \
	"SQ_Shortcut_to_WM_ORDER_LINE_ITEM_PRE___ACTUAL_SHIPPED_DTTM as ACTUAL_SHIPPED_DTTM", \
	"SQ_Shortcut_to_WM_ORDER_LINE_ITEM_PRE___QTY_UOM_ID as QTY_UOM_ID", \
	"SQ_Shortcut_to_WM_ORDER_LINE_ITEM_PRE___PICKUP_END_DTTM as PICKUP_END_DTTM", \
	"SQ_Shortcut_to_WM_ORDER_LINE_ITEM_PRE___PURCHASE_ORDER_LINE_NUMBER as PURCHASE_ORDER_LINE_NUMBER", \
	"SQ_Shortcut_to_WM_ORDER_LINE_ITEM_PRE___PICKUP_START_DTTM as PICKUP_START_DTTM", \
	"SQ_Shortcut_to_WM_ORDER_LINE_ITEM_PRE___REFERENCE_LINE_ITEM_ID as REFERENCE_LINE_ITEM_ID", \
	"SQ_Shortcut_to_WM_ORDER_LINE_ITEM_PRE___REFERENCE_ORDER_ID as REFERENCE_ORDER_ID", \
	"SQ_Shortcut_to_WM_ORDER_LINE_ITEM_PRE___REPL_WAVE_RUN as REPL_WAVE_RUN", \
	"SQ_Shortcut_to_WM_ORDER_LINE_ITEM_PRE___STD_PALLET_QTY as STD_PALLET_QTY", \
	"SQ_Shortcut_to_WM_ORDER_LINE_ITEM_PRE___STD_SUB_PACK_QTY as STD_SUB_PACK_QTY", \
	"SQ_Shortcut_to_WM_ORDER_LINE_ITEM_PRE___STORE_DEPT as STORE_DEPT", \
	"SQ_Shortcut_to_WM_ORDER_LINE_ITEM_PRE___ALLOC_TYPE as ALLOC_TYPE", \
	"SQ_Shortcut_to_WM_ORDER_LINE_ITEM_PRE___BATCH_NBR as BATCH_NBR", \
	"SQ_Shortcut_to_WM_ORDER_LINE_ITEM_PRE___BATCH_REQUIREMENT_TYPE as BATCH_REQUIREMENT_TYPE", \
	"SQ_Shortcut_to_WM_ORDER_LINE_ITEM_PRE___CHUTE_ASSIGN_TYPE as CHUTE_ASSIGN_TYPE", \
	"SQ_Shortcut_to_WM_ORDER_LINE_ITEM_PRE___CUSTOM_TAG as CUSTOM_TAG", \
	"SQ_Shortcut_to_WM_ORDER_LINE_ITEM_PRE___CUSTOMER_ITEM as CUSTOMER_ITEM", \
	"SQ_Shortcut_to_WM_ORDER_LINE_ITEM_PRE___INTERNAL_ORDER_ID as INTERNAL_ORDER_ID", \
	"SQ_Shortcut_to_WM_ORDER_LINE_ITEM_PRE___INVN_TYPE as INVN_TYPE", \
	"SQ_Shortcut_to_WM_ORDER_LINE_ITEM_PRE___ITEM_ATTR_1 as ITEM_ATTR_1", \
	"SQ_Shortcut_to_WM_ORDER_LINE_ITEM_PRE___ITEM_ATTR_2 as ITEM_ATTR_2", \
	"SQ_Shortcut_to_WM_ORDER_LINE_ITEM_PRE___ITEM_ATTR_3 as ITEM_ATTR_3", \
	"SQ_Shortcut_to_WM_ORDER_LINE_ITEM_PRE___ITEM_ATTR_4 as ITEM_ATTR_4", \
	"SQ_Shortcut_to_WM_ORDER_LINE_ITEM_PRE___ITEM_ATTR_5 as ITEM_ATTR_5", \
	"SQ_Shortcut_to_WM_ORDER_LINE_ITEM_PRE___LPN_BRK_ATTRIB as LPN_BRK_ATTRIB", \
	"SQ_Shortcut_to_WM_ORDER_LINE_ITEM_PRE___MERCH_GRP as MERCH_GRP", \
	"SQ_Shortcut_to_WM_ORDER_LINE_ITEM_PRE___MERCH_TYPE as MERCH_TYPE", \
	"SQ_Shortcut_to_WM_ORDER_LINE_ITEM_PRE___PACK_ZONE as PACK_ZONE", \
	"SQ_Shortcut_to_WM_ORDER_LINE_ITEM_PRE___PALLET_TYPE as PALLET_TYPE", \
	"SQ_Shortcut_to_WM_ORDER_LINE_ITEM_PRE___PICK_LOCN_ASSIGN_TYPE as PICK_LOCN_ASSIGN_TYPE", \
	"SQ_Shortcut_to_WM_ORDER_LINE_ITEM_PRE___PICK_LOCN_ID as PICK_LOCN_ID", \
	"SQ_Shortcut_to_WM_ORDER_LINE_ITEM_PRE___PPACK_GRP_CODE as PPACK_GRP_CODE", \
	"SQ_Shortcut_to_WM_ORDER_LINE_ITEM_PRE___PRICE_TKT_TYPE as PRICE_TKT_TYPE", \
	"SQ_Shortcut_to_WM_ORDER_LINE_ITEM_PRE___SERIAL_NUMBER_REQUIRED_FLAG as SERIAL_NUMBER_REQUIRED_FLAG", \
	"SQ_Shortcut_to_WM_ORDER_LINE_ITEM_PRE___SKU_GTIN as SKU_GTIN", \
	"SQ_Shortcut_to_WM_ORDER_LINE_ITEM_PRE___SKU_SUB_CODE_ID as SKU_SUB_CODE_ID", \
	"SQ_Shortcut_to_WM_ORDER_LINE_ITEM_PRE___SKU_SUB_CODE_VALUE as SKU_SUB_CODE_VALUE", \
	"SQ_Shortcut_to_WM_ORDER_LINE_ITEM_PRE___VAS_PROCESS_TYPE as VAS_PROCESS_TYPE", \
	"SQ_Shortcut_to_WM_ORDER_LINE_ITEM_PRE___SUBSTITUTED_PARENT_LINE_ID as SUBSTITUTED_PARENT_LINE_ID", \
	"SQ_Shortcut_to_WM_ORDER_LINE_ITEM_PRE___IS_CANCELLED as IS_CANCELLED", \
	"SQ_Shortcut_to_WM_ORDER_LINE_ITEM_PRE___ITEM_NAME as ITEM_NAME", \
	"SQ_Shortcut_to_WM_ORDER_LINE_ITEM_PRE___ALLOC_LINE_ID as ALLOC_LINE_ID", \
	"SQ_Shortcut_to_WM_ORDER_LINE_ITEM_PRE___ALLOCATION_SOURCE_ID as ALLOCATION_SOURCE_ID", \
	"SQ_Shortcut_to_WM_ORDER_LINE_ITEM_PRE___ALLOCATION_SOURCE_LINE_ID as ALLOCATION_SOURCE_LINE_ID", \
	"SQ_Shortcut_to_WM_ORDER_LINE_ITEM_PRE___ALLOCATION_SOURCE as ALLOCATION_SOURCE", \
	"SQ_Shortcut_to_WM_ORDER_LINE_ITEM_PRE___SHELF_DAYS as SHELF_DAYS", \
	"SQ_Shortcut_to_WM_ORDER_LINE_ITEM_PRE___FULFILLMENT_TYPE as FULFILLMENT_TYPE", \
	"SQ_Shortcut_to_WM_ORDER_LINE_ITEM_PRE___WAVE_NBR as WAVE_NBR", \
	"SQ_Shortcut_to_WM_ORDER_LINE_ITEM_PRE___SHIP_WAVE_NBR as SHIP_WAVE_NBR", \
	"SQ_Shortcut_to_WM_ORDER_LINE_ITEM_PRE___REPL_WAVE_NBR as REPL_WAVE_NBR", \
	"SQ_Shortcut_to_WM_ORDER_LINE_ITEM_PRE___SINGLE_UNIT_FLAG as SINGLE_UNIT_FLAG", \
	"SQ_Shortcut_to_WM_ORDER_LINE_ITEM_PRE___ACTUAL_COST as ACTUAL_COST", \
	"SQ_Shortcut_to_WM_ORDER_LINE_ITEM_PRE___QTY_CONV_FACTOR as QTY_CONV_FACTOR", \
	"SQ_Shortcut_to_WM_ORDER_LINE_ITEM_PRE___PLANNED_WEIGHT as PLANNED_WEIGHT", \
	"SQ_Shortcut_to_WM_ORDER_LINE_ITEM_PRE___RECEIVED_WEIGHT as RECEIVED_WEIGHT", \
	"SQ_Shortcut_to_WM_ORDER_LINE_ITEM_PRE___SHIPPED_WEIGHT as SHIPPED_WEIGHT", \
	"SQ_Shortcut_to_WM_ORDER_LINE_ITEM_PRE___WEIGHT_UOM_ID_BASE as WEIGHT_UOM_ID_BASE", \
	"SQ_Shortcut_to_WM_ORDER_LINE_ITEM_PRE___WEIGHT_UOM_ID as WEIGHT_UOM_ID", \
	"SQ_Shortcut_to_WM_ORDER_LINE_ITEM_PRE___PLANNED_VOLUME as PLANNED_VOLUME", \
	"SQ_Shortcut_to_WM_ORDER_LINE_ITEM_PRE___RECEIVED_VOLUME as RECEIVED_VOLUME", \
	"SQ_Shortcut_to_WM_ORDER_LINE_ITEM_PRE___SHIPPED_VOLUME as SHIPPED_VOLUME", \
	"SQ_Shortcut_to_WM_ORDER_LINE_ITEM_PRE___VOLUME_UOM_ID_BASE as VOLUME_UOM_ID_BASE", \
	"SQ_Shortcut_to_WM_ORDER_LINE_ITEM_PRE___VOLUME_UOM_ID as VOLUME_UOM_ID", \
	"SQ_Shortcut_to_WM_ORDER_LINE_ITEM_PRE___SIZE1_UOM_ID as SIZE1_UOM_ID", \
	"SQ_Shortcut_to_WM_ORDER_LINE_ITEM_PRE___SIZE1_VALUE as SIZE1_VALUE", \
	"SQ_Shortcut_to_WM_ORDER_LINE_ITEM_PRE___RECEIVED_SIZE1 as RECEIVED_SIZE1", \
	"SQ_Shortcut_to_WM_ORDER_LINE_ITEM_PRE___SHIPPED_SIZE1 as SHIPPED_SIZE1", \
	"SQ_Shortcut_to_WM_ORDER_LINE_ITEM_PRE___SIZE2_UOM_ID as SIZE2_UOM_ID", \
	"SQ_Shortcut_to_WM_ORDER_LINE_ITEM_PRE___SIZE2_VALUE as SIZE2_VALUE", \
	"SQ_Shortcut_to_WM_ORDER_LINE_ITEM_PRE___RECEIVED_SIZE2 as RECEIVED_SIZE2", \
	"SQ_Shortcut_to_WM_ORDER_LINE_ITEM_PRE___SHIPPED_SIZE2 as SHIPPED_SIZE2", \
	"SQ_Shortcut_to_WM_ORDER_LINE_ITEM_PRE___LPN_TYPE as LPN_TYPE", \
	"SQ_Shortcut_to_WM_ORDER_LINE_ITEM_PRE___ORDER_CONSOL_ATTR as ORDER_CONSOL_ATTR", \
	"SQ_Shortcut_to_WM_ORDER_LINE_ITEM_PRE___SKU_BREAK_ATTR as SKU_BREAK_ATTR", \
	"SQ_Shortcut_to_WM_ORDER_LINE_ITEM_PRE___PURCHASE_ORDER_NUMBER as PURCHASE_ORDER_NUMBER", \
	"SQ_Shortcut_to_WM_ORDER_LINE_ITEM_PRE___EXT_PURCHASE_ORDER as EXT_PURCHASE_ORDER", \
	"SQ_Shortcut_to_WM_ORDER_LINE_ITEM_PRE___CRITCL_DIM_1 as CRITCL_DIM_1", \
	"SQ_Shortcut_to_WM_ORDER_LINE_ITEM_PRE___CRITCL_DIM_2 as CRITCL_DIM_2", \
	"SQ_Shortcut_to_WM_ORDER_LINE_ITEM_PRE___CRITCL_DIM_3 as CRITCL_DIM_3", \
	"SQ_Shortcut_to_WM_ORDER_LINE_ITEM_PRE___ASSORT_NBR as ASSORT_NBR", \
	"SQ_Shortcut_to_WM_ORDER_LINE_ITEM_PRE___DESCRIPTION as DESCRIPTION", \
	"SQ_Shortcut_to_WM_ORDER_LINE_ITEM_PRE___ORIGINAL_ORDERED_ITEM_ID as ORIGINAL_ORDERED_ITEM_ID", \
	"SQ_Shortcut_to_WM_ORDER_LINE_ITEM_PRE___SUBSTITUTION_TYPE as SUBSTITUTION_TYPE", \
	"SQ_Shortcut_to_WM_ORDER_LINE_ITEM_PRE___BACK_ORD_REASON as BACK_ORD_REASON", \
	"SQ_Shortcut_to_WM_ORDER_LINE_ITEM_PRE___FREIGHT_REVENUE_CURRENCY_CODE as FREIGHT_REVENUE_CURRENCY_CODE", \
	"SQ_Shortcut_to_WM_ORDER_LINE_ITEM_PRE___FREIGHT_REVENUE as FREIGHT_REVENUE", \
	"SQ_Shortcut_to_WM_ORDER_LINE_ITEM_PRE___IS_CHASE_CREATED_LINE as IS_CHASE_CREATED_LINE", \
	"SQ_Shortcut_to_WM_ORDER_LINE_ITEM_PRE___REF_FIELD4 as REF_FIELD4", \
	"SQ_Shortcut_to_WM_ORDER_LINE_ITEM_PRE___REF_FIELD5 as REF_FIELD5", \
	"SQ_Shortcut_to_WM_ORDER_LINE_ITEM_PRE___REF_FIELD6 as REF_FIELD6", \
	"SQ_Shortcut_to_WM_ORDER_LINE_ITEM_PRE___REF_FIELD7 as REF_FIELD7", \
	"SQ_Shortcut_to_WM_ORDER_LINE_ITEM_PRE___REF_FIELD8 as REF_FIELD8", \
	"SQ_Shortcut_to_WM_ORDER_LINE_ITEM_PRE___REF_FIELD9 as REF_FIELD9", \
	"SQ_Shortcut_to_WM_ORDER_LINE_ITEM_PRE___REF_FIELD10 as REF_FIELD10", \
	"SQ_Shortcut_to_WM_ORDER_LINE_ITEM_PRE___REF_NUM1 as REF_NUM1", \
	"SQ_Shortcut_to_WM_ORDER_LINE_ITEM_PRE___REF_NUM2 as REF_NUM2", \
	"SQ_Shortcut_to_WM_ORDER_LINE_ITEM_PRE___REF_NUM3 as REF_NUM3", \
	"SQ_Shortcut_to_WM_ORDER_LINE_ITEM_PRE___REF_NUM4 as REF_NUM4", \
	"SQ_Shortcut_to_WM_ORDER_LINE_ITEM_PRE___REF_NUM5 as REF_NUM5", \
	"SQ_Shortcut_to_WM_ORDER_LINE_ITEM_PRE___IS_GIFT as IS_GIFT", \
	"SQ_Shortcut_to_WM_ORDER_LINE_ITEM_PRE___ADJUSTED_ORDER_QTY as ADJUSTED_ORDER_QTY", \
	"SQ_Shortcut_to_WM_ORDER_LINE_ITEM_PRE___PRE_RECEIPT_STATUS as PRE_RECEIPT_STATUS", \
	"SQ_Shortcut_to_WM_ORDER_LINE_ITEM_PRE___ALLOW_REVIVAL_RECEIPT_ALLOC as ALLOW_REVIVAL_RECEIPT_ALLOC", \
	"SQ_Shortcut_to_WM_ORDER_LINE_ITEM_PRE___SEGMENT_NAME as SEGMENT_NAME", \
	"SQ_Shortcut_to_WM_ORDER_LINE_ITEM_PRE___EFFECTIVE_RANK as EFFECTIVE_RANK", \
	"SQ_Shortcut_to_WM_ORDER_LINE_ITEM_PRE___WM_RECEIPT_ALLOCATED as WM_RECEIPT_ALLOCATED", \
	"SQ_Shortcut_to_WM_ORDER_LINE_ITEM_PRE___GIFT_CARD_VALUE as GIFT_CARD_VALUE", \
	"SQ_Shortcut_to_WM_ORDER_LINE_ITEM_PRE___REF_BOOLEAN1 as REF_BOOLEAN1", \
	"SQ_Shortcut_to_WM_ORDER_LINE_ITEM_PRE___REF_BOOLEAN2 as REF_BOOLEAN2", \
	"SQ_Shortcut_to_WM_ORDER_LINE_ITEM_PRE___REF_SYSCODE1 as REF_SYSCODE1", \
	"SQ_Shortcut_to_WM_ORDER_LINE_ITEM_PRE___REF_SYSCODE2 as REF_SYSCODE2", \
	"SQ_Shortcut_to_WM_ORDER_LINE_ITEM_PRE___REF_SYSCODE3 as REF_SYSCODE3", \
	"SQ_Shortcut_to_WM_ORDER_LINE_ITEM_PRE___HARD_ALLOC_REASON_CODE as HARD_ALLOC_REASON_CODE", \
	"SQ_Shortcut_to_WM_ORDER_LINE_ITEM_PRE___LOCKED as LOCKED" \
)

# COMMAND ----------
# Processing node SQ_Shortcut_to_SITE_PROFILE, type SOURCE 
# COLUMN COUNT: 2

SQ_Shortcut_to_SITE_PROFILE = spark.sql(f"""SELECT LOCATION_ID, STORE_NBR FROM {site_profile_table}""").withColumn("sys_row_id", monotonically_increasing_id())

# COMMAND ----------
# Processing node JNR_SITE_PROFILE, type JOINER 
# COLUMN COUNT: 211

JNR_SITE_PROFILE = SQ_Shortcut_to_SITE_PROFILE.join(EXP_INT_CONVERSION,[SQ_Shortcut_to_SITE_PROFILE.STORE_NBR == EXP_INT_CONVERSION.o_DC_NBR],'inner')

# COMMAND ----------
# Processing node JNR_WM_ORDER_LINE_ITEM, type JOINER . Note: using additional SELECT to rename incoming columns
# COLUMN COUNT: 215

# for each involved DataFrame, append the dataframe name to each column
JNR_SITE_PROFILE_temp = JNR_SITE_PROFILE.toDF(*["JNR_SITE_PROFILE___" + col for col in JNR_SITE_PROFILE.columns])
SQ_Shortcut_to_WM_ORDER_LINE_ITEM_temp = SQ_Shortcut_to_WM_ORDER_LINE_ITEM.toDF(*["SQ_Shortcut_to_WM_ORDER_LINE_ITEM___" + col for col in SQ_Shortcut_to_WM_ORDER_LINE_ITEM.columns])

JNR_WM_ORDER_LINE_ITEM = SQ_Shortcut_to_WM_ORDER_LINE_ITEM_temp.join(JNR_SITE_PROFILE_temp,[SQ_Shortcut_to_WM_ORDER_LINE_ITEM_temp.SQ_Shortcut_to_WM_ORDER_LINE_ITEM___LOCATION_ID == JNR_SITE_PROFILE_temp.JNR_SITE_PROFILE___LOCATION_ID, SQ_Shortcut_to_WM_ORDER_LINE_ITEM_temp.SQ_Shortcut_to_WM_ORDER_LINE_ITEM___WM_ORDER_ID == JNR_SITE_PROFILE_temp.JNR_SITE_PROFILE___ORDER_ID, SQ_Shortcut_to_WM_ORDER_LINE_ITEM_temp.SQ_Shortcut_to_WM_ORDER_LINE_ITEM___WM_LINE_ITEM_ID == JNR_SITE_PROFILE_temp.JNR_SITE_PROFILE___LINE_ITEM_ID],'right_outer').selectExpr( \
	"JNR_SITE_PROFILE___LOCATION_ID as LOCATION_ID", \
	"JNR_SITE_PROFILE___ORDER_ID as ORDER_ID", \
	"JNR_SITE_PROFILE___LINE_ITEM_ID as LINE_ITEM_ID", \
	"JNR_SITE_PROFILE___PARENT_LINE_ITEM_ID as PARENT_LINE_ITEM_ID", \
	"JNR_SITE_PROFILE___TC_COMPANY_ID as TC_COMPANY_ID", \
	"JNR_SITE_PROFILE___COMMODITY_CLASS as COMMODITY_CLASS", \
	"JNR_SITE_PROFILE___REF_FIELD1 as REF_FIELD1", \
	"JNR_SITE_PROFILE___REF_FIELD2 as REF_FIELD2", \
	"JNR_SITE_PROFILE___REF_FIELD3 as REF_FIELD3", \
	"JNR_SITE_PROFILE___EXT_SYS_LINE_ITEM_ID as EXT_SYS_LINE_ITEM_ID", \
	"JNR_SITE_PROFILE___MASTER_ORDER_ID as MASTER_ORDER_ID", \
	"JNR_SITE_PROFILE___MO_LINE_ITEM_ID as MO_LINE_ITEM_ID", \
	"JNR_SITE_PROFILE___IS_HAZMAT as IS_HAZMAT", \
	"JNR_SITE_PROFILE___IS_STACKABLE as IS_STACKABLE", \
	"JNR_SITE_PROFILE___HAS_ERRORS as HAS_ERRORS", \
	"JNR_SITE_PROFILE___ORIG_BUDG_COST as ORIG_BUDG_COST", \
	"JNR_SITE_PROFILE___BUDG_COST_CURRENCY_CODE as BUDG_COST_CURRENCY_CODE", \
	"JNR_SITE_PROFILE___BUDG_COST as BUDG_COST", \
	"JNR_SITE_PROFILE___ACTUAL_COST_CURRENCY_CODE as ACTUAL_COST_CURRENCY_CODE", \
	"JNR_SITE_PROFILE___TOTAL_MONETARY_VALUE as TOTAL_MONETARY_VALUE", \
	"JNR_SITE_PROFILE___UNIT_MONETARY_VALUE as UNIT_MONETARY_VALUE", \
	"JNR_SITE_PROFILE___UNIT_TAX_AMOUNT as UNIT_TAX_AMOUNT", \
	"JNR_SITE_PROFILE___RTS_ID as RTS_ID", \
	"JNR_SITE_PROFILE___RTS_LINE_ITEM_ID as RTS_LINE_ITEM_ID", \
	"JNR_SITE_PROFILE___STD_PACK_QTY as STD_PACK_QTY", \
	"JNR_SITE_PROFILE___PRODUCT_CLASS_ID as PRODUCT_CLASS_ID", \
	"JNR_SITE_PROFILE___PROTECTION_LEVEL_ID as PROTECTION_LEVEL_ID", \
	"JNR_SITE_PROFILE___PACKAGE_TYPE_ID as PACKAGE_TYPE_ID", \
	"JNR_SITE_PROFILE___COMMODITY_CODE_ID as COMMODITY_CODE_ID", \
	"JNR_SITE_PROFILE___MV_SIZE_UOM_ID as MV_SIZE_UOM_ID", \
	"JNR_SITE_PROFILE___QTY_UOM_ID_BASE as QTY_UOM_ID_BASE", \
	"JNR_SITE_PROFILE___MV_CURRENCY_CODE as MV_CURRENCY_CODE", \
	"JNR_SITE_PROFILE___SHIPPED_QTY as SHIPPED_QTY", \
	"JNR_SITE_PROFILE___RECEIVED_QTY as RECEIVED_QTY", \
	"JNR_SITE_PROFILE___PRIORITY as PRIORITY", \
	"JNR_SITE_PROFILE___MERCHANDIZING_DEPARTMENT_ID as MERCHANDIZING_DEPARTMENT_ID", \
	"JNR_SITE_PROFILE___UN_NUMBER_ID as UN_NUMBER_ID", \
	"JNR_SITE_PROFILE___PICKUP_REFERENCE_NUMBER as PICKUP_REFERENCE_NUMBER", \
	"JNR_SITE_PROFILE___DELIVERY_REFERENCE_NUMBER as DELIVERY_REFERENCE_NUMBER", \
	"JNR_SITE_PROFILE___CNTRY_OF_ORGN as CNTRY_OF_ORGN", \
	"JNR_SITE_PROFILE___PROD_STAT as PROD_STAT", \
	"JNR_SITE_PROFILE___STACK_RANK as STACK_RANK", \
	"JNR_SITE_PROFILE___STACK_LENGTH_VALUE as STACK_LENGTH_VALUE", \
	"JNR_SITE_PROFILE___STACK_LENGTH_STANDARD_UOM as STACK_LENGTH_STANDARD_UOM", \
	"JNR_SITE_PROFILE___STACK_WIDTH_VALUE as STACK_WIDTH_VALUE", \
	"JNR_SITE_PROFILE___STACK_WIDTH_STANDARD_UOM as STACK_WIDTH_STANDARD_UOM", \
	"JNR_SITE_PROFILE___STACK_HEIGHT_VALUE as STACK_HEIGHT_VALUE", \
	"JNR_SITE_PROFILE___STACK_HEIGHT_STANDARD_UOM as STACK_HEIGHT_STANDARD_UOM", \
	"JNR_SITE_PROFILE___STACK_DIAMETER_VALUE as STACK_DIAMETER_VALUE", \
	"JNR_SITE_PROFILE___STACK_DIAMETER_STANDARD_UOM as STACK_DIAMETER_STANDARD_UOM", \
	"JNR_SITE_PROFILE___CREATED_SOURCE_TYPE as CREATED_SOURCE_TYPE", \
	"JNR_SITE_PROFILE___CREATED_SOURCE as CREATED_SOURCE", \
	"JNR_SITE_PROFILE___CREATED_DTTM as CREATED_DTTM", \
	"JNR_SITE_PROFILE___LAST_UPDATED_SOURCE_TYPE as LAST_UPDATED_SOURCE_TYPE", \
	"JNR_SITE_PROFILE___LAST_UPDATED_SOURCE as LAST_UPDATED_SOURCE", \
	"JNR_SITE_PROFILE___LAST_UPDATED_DTTM as LAST_UPDATED_DTTM", \
	"JNR_SITE_PROFILE___HIBERNATE_VERSION as HIBERNATE_VERSION", \
	"JNR_SITE_PROFILE___CUBE_MULTIPLE_QTY as CUBE_MULTIPLE_QTY", \
	"JNR_SITE_PROFILE___DO_DTL_STATUS as DO_DTL_STATUS", \
	"JNR_SITE_PROFILE___INTERNAL_ORDER_SEQ_NBR as INTERNAL_ORDER_SEQ_NBR", \
	"JNR_SITE_PROFILE___IS_EMERGENCY as IS_EMERGENCY", \
	"JNR_SITE_PROFILE___LPN_SIZE as LPN_SIZE", \
	"JNR_SITE_PROFILE___MANUFACTURING_DTTM as MANUFACTURING_DTTM", \
	"JNR_SITE_PROFILE___ORDER_LINE_ID as ORDER_LINE_ID", \
	"JNR_SITE_PROFILE___PACK_RATE as PACK_RATE", \
	"JNR_SITE_PROFILE___ALLOCATED_QTY as ALLOCATED_QTY", \
	"JNR_SITE_PROFILE___PLANNED_SHIP_DATE as PLANNED_SHIP_DATE", \
	"JNR_SITE_PROFILE___PPACK_QTY as PPACK_QTY", \
	"JNR_SITE_PROFILE___STD_BUNDLE_QTY as STD_BUNDLE_QTY", \
	"JNR_SITE_PROFILE___STD_LPN_QTY as STD_LPN_QTY", \
	"JNR_SITE_PROFILE___STD_LPN_VOL as STD_LPN_VOL", \
	"JNR_SITE_PROFILE___STD_LPN_WT as STD_LPN_WT", \
	"JNR_SITE_PROFILE___UNIT_COST as UNIT_COST", \
	"JNR_SITE_PROFILE___UNIT_PRICE_AMOUNT as UNIT_PRICE_AMOUNT", \
	"JNR_SITE_PROFILE___UNIT_VOL as UNIT_VOL", \
	"JNR_SITE_PROFILE___UNIT_WT as UNIT_WT", \
	"JNR_SITE_PROFILE___USER_CANCELED_QTY as USER_CANCELED_QTY", \
	"JNR_SITE_PROFILE___WAVE_PROC_TYPE as WAVE_PROC_TYPE", \
	"JNR_SITE_PROFILE___DELIVERY_END_DTTM as DELIVERY_END_DTTM", \
	"JNR_SITE_PROFILE___DELIVERY_START_DTTM as DELIVERY_START_DTTM", \
	"JNR_SITE_PROFILE___EVENT_CODE as EVENT_CODE", \
	"JNR_SITE_PROFILE___REASON_CODE as REASON_CODE", \
	"JNR_SITE_PROFILE___EXP_INFO_CODE as EXP_INFO_CODE", \
	"JNR_SITE_PROFILE___PARTL_FILL as PARTL_FILL", \
	"JNR_SITE_PROFILE___LINE_TYPE as LINE_TYPE", \
	"JNR_SITE_PROFILE___REPL_PROC_TYPE as REPL_PROC_TYPE", \
	"JNR_SITE_PROFILE___ORDER_QTY as ORDER_QTY", \
	"JNR_SITE_PROFILE___ORIG_ORDER_QTY as ORIG_ORDER_QTY", \
	"JNR_SITE_PROFILE___RTL_TO_BE_DISTROED_QTY as RTL_TO_BE_DISTROED_QTY", \
	"JNR_SITE_PROFILE___PRICE as PRICE", \
	"JNR_SITE_PROFILE___RETAIL_PRICE as RETAIL_PRICE", \
	"JNR_SITE_PROFILE___UNITS_PAKD as UNITS_PAKD", \
	"JNR_SITE_PROFILE___MINOR_ORDER_NBR as MINOR_ORDER_NBR", \
	"JNR_SITE_PROFILE___ITEM_ID as ITEM_ID", \
	"JNR_SITE_PROFILE___TC_ORDER_LINE_ID as TC_ORDER_LINE_ID", \
	"JNR_SITE_PROFILE___ACTUAL_SHIPPED_DTTM as ACTUAL_SHIPPED_DTTM", \
	"JNR_SITE_PROFILE___QTY_UOM_ID as QTY_UOM_ID", \
	"JNR_SITE_PROFILE___PICKUP_END_DTTM as PICKUP_END_DTTM", \
	"JNR_SITE_PROFILE___PURCHASE_ORDER_LINE_NUMBER as PURCHASE_ORDER_LINE_NUMBER", \
	"JNR_SITE_PROFILE___PICKUP_START_DTTM as PICKUP_START_DTTM", \
	"JNR_SITE_PROFILE___REFERENCE_LINE_ITEM_ID as REFERENCE_LINE_ITEM_ID", \
	"JNR_SITE_PROFILE___REFERENCE_ORDER_ID as REFERENCE_ORDER_ID", \
	"JNR_SITE_PROFILE___REPL_WAVE_RUN as REPL_WAVE_RUN", \
	"JNR_SITE_PROFILE___STD_PALLET_QTY as STD_PALLET_QTY", \
	"JNR_SITE_PROFILE___STD_SUB_PACK_QTY as STD_SUB_PACK_QTY", \
	"JNR_SITE_PROFILE___STORE_DEPT as STORE_DEPT", \
	"JNR_SITE_PROFILE___ALLOC_TYPE as ALLOC_TYPE", \
	"JNR_SITE_PROFILE___BATCH_NBR as BATCH_NBR", \
	"JNR_SITE_PROFILE___BATCH_REQUIREMENT_TYPE as BATCH_REQUIREMENT_TYPE", \
	"JNR_SITE_PROFILE___CHUTE_ASSIGN_TYPE as CHUTE_ASSIGN_TYPE", \
	"JNR_SITE_PROFILE___CUSTOM_TAG as CUSTOM_TAG", \
	"JNR_SITE_PROFILE___CUSTOMER_ITEM as CUSTOMER_ITEM", \
	"JNR_SITE_PROFILE___INTERNAL_ORDER_ID as INTERNAL_ORDER_ID", \
	"JNR_SITE_PROFILE___INVN_TYPE as INVN_TYPE", \
	"JNR_SITE_PROFILE___ITEM_ATTR_1 as ITEM_ATTR_1", \
	"JNR_SITE_PROFILE___ITEM_ATTR_2 as ITEM_ATTR_2", \
	"JNR_SITE_PROFILE___ITEM_ATTR_3 as ITEM_ATTR_3", \
	"JNR_SITE_PROFILE___ITEM_ATTR_4 as ITEM_ATTR_4", \
	"JNR_SITE_PROFILE___ITEM_ATTR_5 as ITEM_ATTR_5", \
	"JNR_SITE_PROFILE___LPN_BRK_ATTRIB as LPN_BRK_ATTRIB", \
	"JNR_SITE_PROFILE___MERCH_GRP as MERCH_GRP", \
	"JNR_SITE_PROFILE___MERCH_TYPE as MERCH_TYPE", \
	"JNR_SITE_PROFILE___PACK_ZONE as PACK_ZONE", \
	"JNR_SITE_PROFILE___PALLET_TYPE as PALLET_TYPE", \
	"JNR_SITE_PROFILE___PICK_LOCN_ASSIGN_TYPE as PICK_LOCN_ASSIGN_TYPE", \
	"JNR_SITE_PROFILE___PICK_LOCN_ID as PICK_LOCN_ID", \
	"JNR_SITE_PROFILE___PPACK_GRP_CODE as PPACK_GRP_CODE", \
	"JNR_SITE_PROFILE___PRICE_TKT_TYPE as PRICE_TKT_TYPE", \
	"JNR_SITE_PROFILE___SERIAL_NUMBER_REQUIRED_FLAG as SERIAL_NUMBER_REQUIRED_FLAG", \
	"JNR_SITE_PROFILE___SKU_GTIN as SKU_GTIN", \
	"JNR_SITE_PROFILE___SKU_SUB_CODE_ID as SKU_SUB_CODE_ID", \
	"JNR_SITE_PROFILE___SKU_SUB_CODE_VALUE as SKU_SUB_CODE_VALUE", \
	"JNR_SITE_PROFILE___VAS_PROCESS_TYPE as VAS_PROCESS_TYPE", \
	"JNR_SITE_PROFILE___SUBSTITUTED_PARENT_LINE_ID as SUBSTITUTED_PARENT_LINE_ID", \
	"JNR_SITE_PROFILE___IS_CANCELLED as IS_CANCELLED", \
	"JNR_SITE_PROFILE___ITEM_NAME as ITEM_NAME", \
	"JNR_SITE_PROFILE___ALLOC_LINE_ID as ALLOC_LINE_ID", \
	"JNR_SITE_PROFILE___ALLOCATION_SOURCE_ID as ALLOCATION_SOURCE_ID", \
	"JNR_SITE_PROFILE___ALLOCATION_SOURCE_LINE_ID as ALLOCATION_SOURCE_LINE_ID", \
	"JNR_SITE_PROFILE___ALLOCATION_SOURCE as ALLOCATION_SOURCE", \
	"JNR_SITE_PROFILE___SHELF_DAYS as SHELF_DAYS", \
	"JNR_SITE_PROFILE___FULFILLMENT_TYPE as FULFILLMENT_TYPE", \
	"JNR_SITE_PROFILE___WAVE_NBR as WAVE_NBR", \
	"JNR_SITE_PROFILE___SHIP_WAVE_NBR as SHIP_WAVE_NBR", \
	"JNR_SITE_PROFILE___REPL_WAVE_NBR as REPL_WAVE_NBR", \
	"JNR_SITE_PROFILE___SINGLE_UNIT_FLAG as SINGLE_UNIT_FLAG", \
	"JNR_SITE_PROFILE___ACTUAL_COST as ACTUAL_COST", \
	"JNR_SITE_PROFILE___QTY_CONV_FACTOR as QTY_CONV_FACTOR", \
	"JNR_SITE_PROFILE___PLANNED_WEIGHT as PLANNED_WEIGHT", \
	"JNR_SITE_PROFILE___RECEIVED_WEIGHT as RECEIVED_WEIGHT", \
	"JNR_SITE_PROFILE___SHIPPED_WEIGHT as SHIPPED_WEIGHT", \
	"JNR_SITE_PROFILE___WEIGHT_UOM_ID_BASE as WEIGHT_UOM_ID_BASE", \
	"JNR_SITE_PROFILE___WEIGHT_UOM_ID as WEIGHT_UOM_ID", \
	"JNR_SITE_PROFILE___PLANNED_VOLUME as PLANNED_VOLUME", \
	"JNR_SITE_PROFILE___RECEIVED_VOLUME as RECEIVED_VOLUME", \
	"JNR_SITE_PROFILE___SHIPPED_VOLUME as SHIPPED_VOLUME", \
	"JNR_SITE_PROFILE___VOLUME_UOM_ID_BASE as VOLUME_UOM_ID_BASE", \
	"JNR_SITE_PROFILE___VOLUME_UOM_ID as VOLUME_UOM_ID", \
	"JNR_SITE_PROFILE___SIZE1_UOM_ID as SIZE1_UOM_ID", \
	"JNR_SITE_PROFILE___SIZE1_VALUE as SIZE1_VALUE", \
	"JNR_SITE_PROFILE___RECEIVED_SIZE1 as RECEIVED_SIZE1", \
	"JNR_SITE_PROFILE___SHIPPED_SIZE1 as SHIPPED_SIZE1", \
	"JNR_SITE_PROFILE___SIZE2_UOM_ID as SIZE2_UOM_ID", \
	"JNR_SITE_PROFILE___SIZE2_VALUE as SIZE2_VALUE", \
	"JNR_SITE_PROFILE___RECEIVED_SIZE2 as RECEIVED_SIZE2", \
	"JNR_SITE_PROFILE___SHIPPED_SIZE2 as SHIPPED_SIZE2", \
	"JNR_SITE_PROFILE___LPN_TYPE as LPN_TYPE", \
	"JNR_SITE_PROFILE___ORDER_CONSOL_ATTR as ORDER_CONSOL_ATTR", \
	"JNR_SITE_PROFILE___SKU_BREAK_ATTR as SKU_BREAK_ATTR", \
	"JNR_SITE_PROFILE___PURCHASE_ORDER_NUMBER as PURCHASE_ORDER_NUMBER", \
	"JNR_SITE_PROFILE___EXT_PURCHASE_ORDER as EXT_PURCHASE_ORDER", \
	"JNR_SITE_PROFILE___CRITCL_DIM_1 as CRITCL_DIM_1", \
	"JNR_SITE_PROFILE___CRITCL_DIM_2 as CRITCL_DIM_2", \
	"JNR_SITE_PROFILE___CRITCL_DIM_3 as CRITCL_DIM_3", \
	"JNR_SITE_PROFILE___ASSORT_NBR as ASSORT_NBR", \
	"JNR_SITE_PROFILE___DESCRIPTION as DESCRIPTION", \
	"JNR_SITE_PROFILE___ORIGINAL_ORDERED_ITEM_ID as ORIGINAL_ORDERED_ITEM_ID", \
	"JNR_SITE_PROFILE___SUBSTITUTION_TYPE as SUBSTITUTION_TYPE", \
	"JNR_SITE_PROFILE___BACK_ORD_REASON as BACK_ORD_REASON", \
	"JNR_SITE_PROFILE___FREIGHT_REVENUE_CURRENCY_CODE as FREIGHT_REVENUE_CURRENCY_CODE", \
	"JNR_SITE_PROFILE___FREIGHT_REVENUE as FREIGHT_REVENUE", \
	"JNR_SITE_PROFILE___IS_CHASE_CREATED_LINE as IS_CHASE_CREATED_LINE", \
	"JNR_SITE_PROFILE___REF_FIELD4 as REF_FIELD4", \
	"JNR_SITE_PROFILE___REF_FIELD5 as REF_FIELD5", \
	"JNR_SITE_PROFILE___REF_FIELD6 as REF_FIELD6", \
	"JNR_SITE_PROFILE___REF_FIELD7 as REF_FIELD7", \
	"JNR_SITE_PROFILE___REF_FIELD8 as REF_FIELD8", \
	"JNR_SITE_PROFILE___REF_FIELD9 as REF_FIELD9", \
	"JNR_SITE_PROFILE___REF_FIELD10 as REF_FIELD10", \
	"JNR_SITE_PROFILE___REF_NUM1 as REF_NUM1", \
	"JNR_SITE_PROFILE___REF_NUM2 as REF_NUM2", \
	"JNR_SITE_PROFILE___REF_NUM3 as REF_NUM3", \
	"JNR_SITE_PROFILE___REF_NUM4 as REF_NUM4", \
	"JNR_SITE_PROFILE___REF_NUM5 as REF_NUM5", \
	"JNR_SITE_PROFILE___IS_GIFT as IS_GIFT", \
	"JNR_SITE_PROFILE___ADJUSTED_ORDER_QTY as ADJUSTED_ORDER_QTY", \
	"JNR_SITE_PROFILE___PRE_RECEIPT_STATUS as PRE_RECEIPT_STATUS", \
	"JNR_SITE_PROFILE___ALLOW_REVIVAL_RECEIPT_ALLOC as ALLOW_REVIVAL_RECEIPT_ALLOC", \
	"JNR_SITE_PROFILE___SEGMENT_NAME as SEGMENT_NAME", \
	"JNR_SITE_PROFILE___EFFECTIVE_RANK as EFFECTIVE_RANK", \
	"JNR_SITE_PROFILE___WM_RECEIPT_ALLOCATED as WM_RECEIPT_ALLOCATED", \
	"JNR_SITE_PROFILE___GIFT_CARD_VALUE as GIFT_CARD_VALUE", \
	"JNR_SITE_PROFILE___REF_BOOLEAN1 as REF_BOOLEAN1", \
	"JNR_SITE_PROFILE___REF_BOOLEAN2 as REF_BOOLEAN2", \
	"JNR_SITE_PROFILE___REF_SYSCODE1 as REF_SYSCODE1", \
	"JNR_SITE_PROFILE___REF_SYSCODE2 as REF_SYSCODE2", \
	"JNR_SITE_PROFILE___REF_SYSCODE3 as REF_SYSCODE3", \
	"JNR_SITE_PROFILE___HARD_ALLOC_REASON_CODE as HARD_ALLOC_REASON_CODE", \
	"JNR_SITE_PROFILE___LOCKED as LOCKED", \
	"SQ_Shortcut_to_WM_ORDER_LINE_ITEM___LOCATION_ID as i_LOCATION_ID", \
	"SQ_Shortcut_to_WM_ORDER_LINE_ITEM___WM_ORDER_ID as i_WM_ORDER_ID", \
	"SQ_Shortcut_to_WM_ORDER_LINE_ITEM___WM_LINE_ITEM_ID as i_WM_LINE_ITEM_ID", \
	"SQ_Shortcut_to_WM_ORDER_LINE_ITEM___WM_CREATED_TSTMP as i_WM_CREATED_TSTMP", \
	"SQ_Shortcut_to_WM_ORDER_LINE_ITEM___WM_LAST_UPDATED_TSTMP as i_WM_LAST_UPDATED_TSTMP", \
	"SQ_Shortcut_to_WM_ORDER_LINE_ITEM___LOAD_TSTMP as i_LOAD_TSTMP")

# COMMAND ----------
# Processing node FIL_UNCHANGED_RECORDS, type FILTER 
# COLUMN COUNT: 214

# for each involved DataFrame, append the dataframe name to each column
JNR_WM_ORDER_LINE_ITEM_temp = JNR_WM_ORDER_LINE_ITEM.toDF(*["JNR_WM_ORDER_LINE_ITEM___" + col for col in JNR_WM_ORDER_LINE_ITEM.columns])

FIL_UNCHANGED_RECORDS = JNR_WM_ORDER_LINE_ITEM_temp.selectExpr( \
	"JNR_WM_ORDER_LINE_ITEM___LOCATION_ID as LOCATION_ID", \
	"JNR_WM_ORDER_LINE_ITEM___ORDER_ID as ORDER_ID", \
	"JNR_WM_ORDER_LINE_ITEM___LINE_ITEM_ID as LINE_ITEM_ID", \
	"JNR_WM_ORDER_LINE_ITEM___PARENT_LINE_ITEM_ID as PARENT_LINE_ITEM_ID", \
	"JNR_WM_ORDER_LINE_ITEM___TC_COMPANY_ID as TC_COMPANY_ID", \
	"JNR_WM_ORDER_LINE_ITEM___COMMODITY_CLASS as COMMODITY_CLASS", \
	"JNR_WM_ORDER_LINE_ITEM___REF_FIELD1 as REF_FIELD1", \
	"JNR_WM_ORDER_LINE_ITEM___REF_FIELD2 as REF_FIELD2", \
	"JNR_WM_ORDER_LINE_ITEM___REF_FIELD3 as REF_FIELD3", \
	"JNR_WM_ORDER_LINE_ITEM___EXT_SYS_LINE_ITEM_ID as EXT_SYS_LINE_ITEM_ID", \
	"JNR_WM_ORDER_LINE_ITEM___MASTER_ORDER_ID as MASTER_ORDER_ID", \
	"JNR_WM_ORDER_LINE_ITEM___MO_LINE_ITEM_ID as MO_LINE_ITEM_ID", \
	"JNR_WM_ORDER_LINE_ITEM___IS_HAZMAT as IS_HAZMAT", \
	"JNR_WM_ORDER_LINE_ITEM___IS_STACKABLE as IS_STACKABLE", \
	"JNR_WM_ORDER_LINE_ITEM___HAS_ERRORS as HAS_ERRORS", \
	"JNR_WM_ORDER_LINE_ITEM___ORIG_BUDG_COST as ORIG_BUDG_COST", \
	"JNR_WM_ORDER_LINE_ITEM___BUDG_COST_CURRENCY_CODE as BUDG_COST_CURRENCY_CODE", \
	"JNR_WM_ORDER_LINE_ITEM___BUDG_COST as BUDG_COST", \
	"JNR_WM_ORDER_LINE_ITEM___ACTUAL_COST_CURRENCY_CODE as ACTUAL_COST_CURRENCY_CODE", \
	"JNR_WM_ORDER_LINE_ITEM___TOTAL_MONETARY_VALUE as TOTAL_MONETARY_VALUE", \
	"JNR_WM_ORDER_LINE_ITEM___UNIT_MONETARY_VALUE as UNIT_MONETARY_VALUE", \
	"JNR_WM_ORDER_LINE_ITEM___UNIT_TAX_AMOUNT as UNIT_TAX_AMOUNT", \
	"JNR_WM_ORDER_LINE_ITEM___RTS_ID as RTS_ID", \
	"JNR_WM_ORDER_LINE_ITEM___RTS_LINE_ITEM_ID as RTS_LINE_ITEM_ID", \
	"JNR_WM_ORDER_LINE_ITEM___STD_PACK_QTY as STD_PACK_QTY", \
	"JNR_WM_ORDER_LINE_ITEM___PRODUCT_CLASS_ID as PRODUCT_CLASS_ID", \
	"JNR_WM_ORDER_LINE_ITEM___PROTECTION_LEVEL_ID as PROTECTION_LEVEL_ID", \
	"JNR_WM_ORDER_LINE_ITEM___PACKAGE_TYPE_ID as PACKAGE_TYPE_ID", \
	"JNR_WM_ORDER_LINE_ITEM___COMMODITY_CODE_ID as COMMODITY_CODE_ID", \
	"JNR_WM_ORDER_LINE_ITEM___MV_SIZE_UOM_ID as MV_SIZE_UOM_ID", \
	"JNR_WM_ORDER_LINE_ITEM___QTY_UOM_ID_BASE as QTY_UOM_ID_BASE", \
	"JNR_WM_ORDER_LINE_ITEM___MV_CURRENCY_CODE as MV_CURRENCY_CODE", \
	"JNR_WM_ORDER_LINE_ITEM___SHIPPED_QTY as SHIPPED_QTY", \
	"JNR_WM_ORDER_LINE_ITEM___RECEIVED_QTY as RECEIVED_QTY", \
	"JNR_WM_ORDER_LINE_ITEM___PRIORITY as PRIORITY", \
	"JNR_WM_ORDER_LINE_ITEM___MERCHANDIZING_DEPARTMENT_ID as MERCHANDIZING_DEPARTMENT_ID", \
	"JNR_WM_ORDER_LINE_ITEM___UN_NUMBER_ID as UN_NUMBER_ID", \
	"JNR_WM_ORDER_LINE_ITEM___PICKUP_REFERENCE_NUMBER as PICKUP_REFERENCE_NUMBER", \
	"JNR_WM_ORDER_LINE_ITEM___DELIVERY_REFERENCE_NUMBER as DELIVERY_REFERENCE_NUMBER", \
	"JNR_WM_ORDER_LINE_ITEM___CNTRY_OF_ORGN as CNTRY_OF_ORGN", \
	"JNR_WM_ORDER_LINE_ITEM___PROD_STAT as PROD_STAT", \
	"JNR_WM_ORDER_LINE_ITEM___STACK_RANK as STACK_RANK", \
	"JNR_WM_ORDER_LINE_ITEM___STACK_LENGTH_VALUE as STACK_LENGTH_VALUE", \
	"JNR_WM_ORDER_LINE_ITEM___STACK_LENGTH_STANDARD_UOM as STACK_LENGTH_STANDARD_UOM", \
	"JNR_WM_ORDER_LINE_ITEM___STACK_WIDTH_VALUE as STACK_WIDTH_VALUE", \
	"JNR_WM_ORDER_LINE_ITEM___STACK_WIDTH_STANDARD_UOM as STACK_WIDTH_STANDARD_UOM", \
	"JNR_WM_ORDER_LINE_ITEM___STACK_HEIGHT_VALUE as STACK_HEIGHT_VALUE", \
	"JNR_WM_ORDER_LINE_ITEM___STACK_HEIGHT_STANDARD_UOM as STACK_HEIGHT_STANDARD_UOM", \
	"JNR_WM_ORDER_LINE_ITEM___STACK_DIAMETER_VALUE as STACK_DIAMETER_VALUE", \
	"JNR_WM_ORDER_LINE_ITEM___STACK_DIAMETER_STANDARD_UOM as STACK_DIAMETER_STANDARD_UOM", \
	"JNR_WM_ORDER_LINE_ITEM___CREATED_SOURCE_TYPE as CREATED_SOURCE_TYPE", \
	"JNR_WM_ORDER_LINE_ITEM___CREATED_SOURCE as CREATED_SOURCE", \
	"JNR_WM_ORDER_LINE_ITEM___CREATED_DTTM as CREATED_DTTM", \
	"JNR_WM_ORDER_LINE_ITEM___LAST_UPDATED_SOURCE_TYPE as LAST_UPDATED_SOURCE_TYPE", \
	"JNR_WM_ORDER_LINE_ITEM___LAST_UPDATED_SOURCE as LAST_UPDATED_SOURCE", \
	"JNR_WM_ORDER_LINE_ITEM___LAST_UPDATED_DTTM as LAST_UPDATED_DTTM", \
	"JNR_WM_ORDER_LINE_ITEM___HIBERNATE_VERSION as HIBERNATE_VERSION", \
	"JNR_WM_ORDER_LINE_ITEM___CUBE_MULTIPLE_QTY as CUBE_MULTIPLE_QTY", \
	"JNR_WM_ORDER_LINE_ITEM___DO_DTL_STATUS as DO_DTL_STATUS", \
	"JNR_WM_ORDER_LINE_ITEM___INTERNAL_ORDER_SEQ_NBR as INTERNAL_ORDER_SEQ_NBR", \
	"JNR_WM_ORDER_LINE_ITEM___IS_EMERGENCY as IS_EMERGENCY", \
	"JNR_WM_ORDER_LINE_ITEM___LPN_SIZE as LPN_SIZE", \
	"JNR_WM_ORDER_LINE_ITEM___MANUFACTURING_DTTM as MANUFACTURING_DTTM", \
	"JNR_WM_ORDER_LINE_ITEM___ORDER_LINE_ID as ORDER_LINE_ID", \
	"JNR_WM_ORDER_LINE_ITEM___PACK_RATE as PACK_RATE", \
	"JNR_WM_ORDER_LINE_ITEM___ALLOCATED_QTY as ALLOCATED_QTY", \
	"JNR_WM_ORDER_LINE_ITEM___PLANNED_SHIP_DATE as PLANNED_SHIP_DATE", \
	"JNR_WM_ORDER_LINE_ITEM___PPACK_QTY as PPACK_QTY", \
	"JNR_WM_ORDER_LINE_ITEM___STD_BUNDLE_QTY as STD_BUNDLE_QTY", \
	"JNR_WM_ORDER_LINE_ITEM___STD_LPN_QTY as STD_LPN_QTY", \
	"JNR_WM_ORDER_LINE_ITEM___STD_LPN_VOL as STD_LPN_VOL", \
	"JNR_WM_ORDER_LINE_ITEM___STD_LPN_WT as STD_LPN_WT", \
	"JNR_WM_ORDER_LINE_ITEM___UNIT_COST as UNIT_COST", \
	"JNR_WM_ORDER_LINE_ITEM___UNIT_PRICE_AMOUNT as UNIT_PRICE_AMOUNT", \
	"JNR_WM_ORDER_LINE_ITEM___UNIT_VOL as UNIT_VOL", \
	"JNR_WM_ORDER_LINE_ITEM___UNIT_WT as UNIT_WT", \
	"JNR_WM_ORDER_LINE_ITEM___USER_CANCELED_QTY as USER_CANCELED_QTY", \
	"JNR_WM_ORDER_LINE_ITEM___WAVE_PROC_TYPE as WAVE_PROC_TYPE", \
	"JNR_WM_ORDER_LINE_ITEM___DELIVERY_END_DTTM as DELIVERY_END_DTTM", \
	"JNR_WM_ORDER_LINE_ITEM___DELIVERY_START_DTTM as DELIVERY_START_DTTM", \
	"JNR_WM_ORDER_LINE_ITEM___EVENT_CODE as EVENT_CODE", \
	"JNR_WM_ORDER_LINE_ITEM___REASON_CODE as REASON_CODE", \
	"JNR_WM_ORDER_LINE_ITEM___EXP_INFO_CODE as EXP_INFO_CODE", \
	"JNR_WM_ORDER_LINE_ITEM___PARTL_FILL as PARTL_FILL", \
	"JNR_WM_ORDER_LINE_ITEM___LINE_TYPE as LINE_TYPE", \
	"JNR_WM_ORDER_LINE_ITEM___REPL_PROC_TYPE as REPL_PROC_TYPE", \
	"JNR_WM_ORDER_LINE_ITEM___ORDER_QTY as ORDER_QTY", \
	"JNR_WM_ORDER_LINE_ITEM___ORIG_ORDER_QTY as ORIG_ORDER_QTY", \
	"JNR_WM_ORDER_LINE_ITEM___RTL_TO_BE_DISTROED_QTY as RTL_TO_BE_DISTROED_QTY", \
	"JNR_WM_ORDER_LINE_ITEM___PRICE as PRICE", \
	"JNR_WM_ORDER_LINE_ITEM___RETAIL_PRICE as RETAIL_PRICE", \
	"JNR_WM_ORDER_LINE_ITEM___UNITS_PAKD as UNITS_PAKD", \
	"JNR_WM_ORDER_LINE_ITEM___MINOR_ORDER_NBR as MINOR_ORDER_NBR", \
	"JNR_WM_ORDER_LINE_ITEM___ITEM_ID as ITEM_ID", \
	"JNR_WM_ORDER_LINE_ITEM___TC_ORDER_LINE_ID as TC_ORDER_LINE_ID", \
	"JNR_WM_ORDER_LINE_ITEM___ACTUAL_SHIPPED_DTTM as ACTUAL_SHIPPED_DTTM", \
	"JNR_WM_ORDER_LINE_ITEM___QTY_UOM_ID as QTY_UOM_ID", \
	"JNR_WM_ORDER_LINE_ITEM___PICKUP_END_DTTM as PICKUP_END_DTTM", \
	"JNR_WM_ORDER_LINE_ITEM___PURCHASE_ORDER_LINE_NUMBER as PURCHASE_ORDER_LINE_NUMBER", \
	"JNR_WM_ORDER_LINE_ITEM___PICKUP_START_DTTM as PICKUP_START_DTTM", \
	"JNR_WM_ORDER_LINE_ITEM___REFERENCE_LINE_ITEM_ID as REFERENCE_LINE_ITEM_ID", \
	"JNR_WM_ORDER_LINE_ITEM___REFERENCE_ORDER_ID as REFERENCE_ORDER_ID", \
	"JNR_WM_ORDER_LINE_ITEM___REPL_WAVE_RUN as REPL_WAVE_RUN", \
	"JNR_WM_ORDER_LINE_ITEM___STD_PALLET_QTY as STD_PALLET_QTY", \
	"JNR_WM_ORDER_LINE_ITEM___STD_SUB_PACK_QTY as STD_SUB_PACK_QTY", \
	"JNR_WM_ORDER_LINE_ITEM___STORE_DEPT as STORE_DEPT", \
	"JNR_WM_ORDER_LINE_ITEM___ALLOC_TYPE as ALLOC_TYPE", \
	"JNR_WM_ORDER_LINE_ITEM___BATCH_NBR as BATCH_NBR", \
	"JNR_WM_ORDER_LINE_ITEM___BATCH_REQUIREMENT_TYPE as BATCH_REQUIREMENT_TYPE", \
	"JNR_WM_ORDER_LINE_ITEM___CHUTE_ASSIGN_TYPE as CHUTE_ASSIGN_TYPE", \
	"JNR_WM_ORDER_LINE_ITEM___CUSTOM_TAG as CUSTOM_TAG", \
	"JNR_WM_ORDER_LINE_ITEM___CUSTOMER_ITEM as CUSTOMER_ITEM", \
	"JNR_WM_ORDER_LINE_ITEM___INTERNAL_ORDER_ID as INTERNAL_ORDER_ID", \
	"JNR_WM_ORDER_LINE_ITEM___INVN_TYPE as INVN_TYPE", \
	"JNR_WM_ORDER_LINE_ITEM___ITEM_ATTR_1 as ITEM_ATTR_1", \
	"JNR_WM_ORDER_LINE_ITEM___ITEM_ATTR_2 as ITEM_ATTR_2", \
	"JNR_WM_ORDER_LINE_ITEM___ITEM_ATTR_3 as ITEM_ATTR_3", \
	"JNR_WM_ORDER_LINE_ITEM___ITEM_ATTR_4 as ITEM_ATTR_4", \
	"JNR_WM_ORDER_LINE_ITEM___ITEM_ATTR_5 as ITEM_ATTR_5", \
	"JNR_WM_ORDER_LINE_ITEM___LPN_BRK_ATTRIB as LPN_BRK_ATTRIB", \
	"JNR_WM_ORDER_LINE_ITEM___MERCH_GRP as MERCH_GRP", \
	"JNR_WM_ORDER_LINE_ITEM___MERCH_TYPE as MERCH_TYPE", \
	"JNR_WM_ORDER_LINE_ITEM___PACK_ZONE as PACK_ZONE", \
	"JNR_WM_ORDER_LINE_ITEM___PALLET_TYPE as PALLET_TYPE", \
	"JNR_WM_ORDER_LINE_ITEM___PICK_LOCN_ASSIGN_TYPE as PICK_LOCN_ASSIGN_TYPE", \
	"JNR_WM_ORDER_LINE_ITEM___PICK_LOCN_ID as PICK_LOCN_ID", \
	"JNR_WM_ORDER_LINE_ITEM___PPACK_GRP_CODE as PPACK_GRP_CODE", \
	"JNR_WM_ORDER_LINE_ITEM___PRICE_TKT_TYPE as PRICE_TKT_TYPE", \
	"JNR_WM_ORDER_LINE_ITEM___SERIAL_NUMBER_REQUIRED_FLAG as SERIAL_NUMBER_REQUIRED_FLAG", \
	"JNR_WM_ORDER_LINE_ITEM___SKU_GTIN as SKU_GTIN", \
	"JNR_WM_ORDER_LINE_ITEM___SKU_SUB_CODE_ID as SKU_SUB_CODE_ID", \
	"JNR_WM_ORDER_LINE_ITEM___SKU_SUB_CODE_VALUE as SKU_SUB_CODE_VALUE", \
	"JNR_WM_ORDER_LINE_ITEM___VAS_PROCESS_TYPE as VAS_PROCESS_TYPE", \
	"JNR_WM_ORDER_LINE_ITEM___SUBSTITUTED_PARENT_LINE_ID as SUBSTITUTED_PARENT_LINE_ID", \
	"JNR_WM_ORDER_LINE_ITEM___IS_CANCELLED as IS_CANCELLED", \
	"JNR_WM_ORDER_LINE_ITEM___ITEM_NAME as ITEM_NAME", \
	"JNR_WM_ORDER_LINE_ITEM___ALLOC_LINE_ID as ALLOC_LINE_ID", \
	"JNR_WM_ORDER_LINE_ITEM___ALLOCATION_SOURCE_ID as ALLOCATION_SOURCE_ID", \
	"JNR_WM_ORDER_LINE_ITEM___ALLOCATION_SOURCE_LINE_ID as ALLOCATION_SOURCE_LINE_ID", \
	"JNR_WM_ORDER_LINE_ITEM___ALLOCATION_SOURCE as ALLOCATION_SOURCE", \
	"JNR_WM_ORDER_LINE_ITEM___SHELF_DAYS as SHELF_DAYS", \
	"JNR_WM_ORDER_LINE_ITEM___FULFILLMENT_TYPE as FULFILLMENT_TYPE", \
	"JNR_WM_ORDER_LINE_ITEM___WAVE_NBR as WAVE_NBR", \
	"JNR_WM_ORDER_LINE_ITEM___SHIP_WAVE_NBR as SHIP_WAVE_NBR", \
	"JNR_WM_ORDER_LINE_ITEM___REPL_WAVE_NBR as REPL_WAVE_NBR", \
	"JNR_WM_ORDER_LINE_ITEM___SINGLE_UNIT_FLAG as SINGLE_UNIT_FLAG", \
	"JNR_WM_ORDER_LINE_ITEM___ACTUAL_COST as ACTUAL_COST", \
	"JNR_WM_ORDER_LINE_ITEM___QTY_CONV_FACTOR as QTY_CONV_FACTOR", \
	"JNR_WM_ORDER_LINE_ITEM___PLANNED_WEIGHT as PLANNED_WEIGHT", \
	"JNR_WM_ORDER_LINE_ITEM___RECEIVED_WEIGHT as RECEIVED_WEIGHT", \
	"JNR_WM_ORDER_LINE_ITEM___SHIPPED_WEIGHT as SHIPPED_WEIGHT", \
	"JNR_WM_ORDER_LINE_ITEM___WEIGHT_UOM_ID_BASE as WEIGHT_UOM_ID_BASE", \
	"JNR_WM_ORDER_LINE_ITEM___WEIGHT_UOM_ID as WEIGHT_UOM_ID", \
	"JNR_WM_ORDER_LINE_ITEM___PLANNED_VOLUME as PLANNED_VOLUME", \
	"JNR_WM_ORDER_LINE_ITEM___RECEIVED_VOLUME as RECEIVED_VOLUME", \
	"JNR_WM_ORDER_LINE_ITEM___SHIPPED_VOLUME as SHIPPED_VOLUME", \
	"JNR_WM_ORDER_LINE_ITEM___VOLUME_UOM_ID_BASE as VOLUME_UOM_ID_BASE", \
	"JNR_WM_ORDER_LINE_ITEM___VOLUME_UOM_ID as VOLUME_UOM_ID", \
	"JNR_WM_ORDER_LINE_ITEM___SIZE1_UOM_ID as SIZE1_UOM_ID", \
	"JNR_WM_ORDER_LINE_ITEM___SIZE1_VALUE as SIZE1_VALUE", \
	"JNR_WM_ORDER_LINE_ITEM___RECEIVED_SIZE1 as RECEIVED_SIZE1", \
	"JNR_WM_ORDER_LINE_ITEM___SHIPPED_SIZE1 as SHIPPED_SIZE1", \
	"JNR_WM_ORDER_LINE_ITEM___SIZE2_UOM_ID as SIZE2_UOM_ID", \
	"JNR_WM_ORDER_LINE_ITEM___SIZE2_VALUE as SIZE2_VALUE", \
	"JNR_WM_ORDER_LINE_ITEM___RECEIVED_SIZE2 as RECEIVED_SIZE2", \
	"JNR_WM_ORDER_LINE_ITEM___SHIPPED_SIZE2 as SHIPPED_SIZE2", \
	"JNR_WM_ORDER_LINE_ITEM___LPN_TYPE as LPN_TYPE", \
	"JNR_WM_ORDER_LINE_ITEM___ORDER_CONSOL_ATTR as ORDER_CONSOL_ATTR", \
	"JNR_WM_ORDER_LINE_ITEM___SKU_BREAK_ATTR as SKU_BREAK_ATTR", \
	"JNR_WM_ORDER_LINE_ITEM___PURCHASE_ORDER_NUMBER as PURCHASE_ORDER_NUMBER", \
	"JNR_WM_ORDER_LINE_ITEM___EXT_PURCHASE_ORDER as EXT_PURCHASE_ORDER", \
	"JNR_WM_ORDER_LINE_ITEM___CRITCL_DIM_1 as CRITCL_DIM_1", \
	"JNR_WM_ORDER_LINE_ITEM___CRITCL_DIM_2 as CRITCL_DIM_2", \
	"JNR_WM_ORDER_LINE_ITEM___CRITCL_DIM_3 as CRITCL_DIM_3", \
	"JNR_WM_ORDER_LINE_ITEM___ASSORT_NBR as ASSORT_NBR", \
	"JNR_WM_ORDER_LINE_ITEM___DESCRIPTION as DESCRIPTION", \
	"JNR_WM_ORDER_LINE_ITEM___ORIGINAL_ORDERED_ITEM_ID as ORIGINAL_ORDERED_ITEM_ID", \
	"JNR_WM_ORDER_LINE_ITEM___SUBSTITUTION_TYPE as SUBSTITUTION_TYPE", \
	"JNR_WM_ORDER_LINE_ITEM___BACK_ORD_REASON as BACK_ORD_REASON", \
	"JNR_WM_ORDER_LINE_ITEM___FREIGHT_REVENUE_CURRENCY_CODE as FREIGHT_REVENUE_CURRENCY_CODE", \
	"JNR_WM_ORDER_LINE_ITEM___FREIGHT_REVENUE as FREIGHT_REVENUE", \
	"JNR_WM_ORDER_LINE_ITEM___IS_CHASE_CREATED_LINE as IS_CHASE_CREATED_LINE", \
	"JNR_WM_ORDER_LINE_ITEM___REF_FIELD4 as REF_FIELD4", \
	"JNR_WM_ORDER_LINE_ITEM___REF_FIELD5 as REF_FIELD5", \
	"JNR_WM_ORDER_LINE_ITEM___REF_FIELD6 as REF_FIELD6", \
	"JNR_WM_ORDER_LINE_ITEM___REF_FIELD7 as REF_FIELD7", \
	"JNR_WM_ORDER_LINE_ITEM___REF_FIELD8 as REF_FIELD8", \
	"JNR_WM_ORDER_LINE_ITEM___REF_FIELD9 as REF_FIELD9", \
	"JNR_WM_ORDER_LINE_ITEM___REF_FIELD10 as REF_FIELD10", \
	"JNR_WM_ORDER_LINE_ITEM___REF_NUM1 as REF_NUM1", \
	"JNR_WM_ORDER_LINE_ITEM___REF_NUM2 as REF_NUM2", \
	"JNR_WM_ORDER_LINE_ITEM___REF_NUM3 as REF_NUM3", \
	"JNR_WM_ORDER_LINE_ITEM___REF_NUM4 as REF_NUM4", \
	"JNR_WM_ORDER_LINE_ITEM___REF_NUM5 as REF_NUM5", \
	"JNR_WM_ORDER_LINE_ITEM___IS_GIFT as IS_GIFT", \
	"JNR_WM_ORDER_LINE_ITEM___ADJUSTED_ORDER_QTY as ADJUSTED_ORDER_QTY", \
	"JNR_WM_ORDER_LINE_ITEM___PRE_RECEIPT_STATUS as PRE_RECEIPT_STATUS", \
	"JNR_WM_ORDER_LINE_ITEM___ALLOW_REVIVAL_RECEIPT_ALLOC as ALLOW_REVIVAL_RECEIPT_ALLOC", \
	"JNR_WM_ORDER_LINE_ITEM___SEGMENT_NAME as SEGMENT_NAME", \
	"JNR_WM_ORDER_LINE_ITEM___EFFECTIVE_RANK as EFFECTIVE_RANK", \
	"JNR_WM_ORDER_LINE_ITEM___WM_RECEIPT_ALLOCATED as WM_RECEIPT_ALLOCATED", \
	"JNR_WM_ORDER_LINE_ITEM___GIFT_CARD_VALUE as GIFT_CARD_VALUE", \
	"JNR_WM_ORDER_LINE_ITEM___REF_BOOLEAN1 as REF_BOOLEAN1", \
	"JNR_WM_ORDER_LINE_ITEM___REF_BOOLEAN2 as REF_BOOLEAN2", \
	"JNR_WM_ORDER_LINE_ITEM___REF_SYSCODE1 as REF_SYSCODE1", \
	"JNR_WM_ORDER_LINE_ITEM___REF_SYSCODE2 as REF_SYSCODE2", \
	"JNR_WM_ORDER_LINE_ITEM___REF_SYSCODE3 as REF_SYSCODE3", \
	"JNR_WM_ORDER_LINE_ITEM___HARD_ALLOC_REASON_CODE as HARD_ALLOC_REASON_CODE", \
	"JNR_WM_ORDER_LINE_ITEM___LOCKED as LOCKED", \
	"JNR_WM_ORDER_LINE_ITEM___i_WM_ORDER_ID as i_WM_ORDER_ID", \
	"JNR_WM_ORDER_LINE_ITEM___i_WM_LINE_ITEM_ID as i_WM_LINE_ITEM_ID", \
	"JNR_WM_ORDER_LINE_ITEM___i_WM_CREATED_TSTMP as i_WM_CREATED_TSTMP", \
	"JNR_WM_ORDER_LINE_ITEM___i_WM_LAST_UPDATED_TSTMP as i_WM_LAST_UPDATED_TSTMP", \
	"JNR_WM_ORDER_LINE_ITEM___i_LOAD_TSTMP as i_LOAD_TSTMP") \
    .filter("i_WM_ORDER_ID is Null OR (  i_WM_ORDER_ID is NOT Null AND ( COALESCE(CREATED_DTTM, date'1900-01-01') != COALESCE(i_WM_CREATED_TSTMP, date'1900-01-01') \
             OR COALESCE(LAST_UPDATED_DTTM, date'1900-01-01') != COALESCE(i_WM_LAST_UPDATED_TSTMP, date'1900-01-01')))").withColumn("sys_row_id", monotonically_increasing_id())

# COMMAND ----------
# Processing node EXP_UPD_VALIDATOR, type EXPRESSION 
# COLUMN COUNT: 212

# for each involved DataFrame, append the dataframe name to each column
FIL_UNCHANGED_RECORDS_temp = FIL_UNCHANGED_RECORDS.toDF(*["FIL_UNCHANGED_RECORDS___" + col for col in FIL_UNCHANGED_RECORDS.columns])

EXP_UPD_VALIDATOR = FIL_UNCHANGED_RECORDS_temp.selectExpr( \
	"FIL_UNCHANGED_RECORDS___sys_row_id as sys_row_id", \
	"FIL_UNCHANGED_RECORDS___LOCATION_ID as LOCATION_ID", \
	"FIL_UNCHANGED_RECORDS___ORDER_ID as ORDER_ID", \
	"FIL_UNCHANGED_RECORDS___LINE_ITEM_ID as LINE_ITEM_ID", \
	"FIL_UNCHANGED_RECORDS___PARENT_LINE_ITEM_ID as PARENT_LINE_ITEM_ID", \
	"FIL_UNCHANGED_RECORDS___TC_COMPANY_ID as TC_COMPANY_ID", \
	"FIL_UNCHANGED_RECORDS___COMMODITY_CLASS as COMMODITY_CLASS", \
	"FIL_UNCHANGED_RECORDS___REF_FIELD1 as REF_FIELD1", \
	"FIL_UNCHANGED_RECORDS___REF_FIELD2 as REF_FIELD2", \
	"FIL_UNCHANGED_RECORDS___REF_FIELD3 as REF_FIELD3", \
	"FIL_UNCHANGED_RECORDS___EXT_SYS_LINE_ITEM_ID as EXT_SYS_LINE_ITEM_ID", \
	"FIL_UNCHANGED_RECORDS___MASTER_ORDER_ID as MASTER_ORDER_ID", \
	"FIL_UNCHANGED_RECORDS___MO_LINE_ITEM_ID as MO_LINE_ITEM_ID", \
	"FIL_UNCHANGED_RECORDS___IS_HAZMAT as IS_HAZMAT", \
	"FIL_UNCHANGED_RECORDS___IS_STACKABLE as IS_STACKABLE", \
	"FIL_UNCHANGED_RECORDS___HAS_ERRORS as HAS_ERRORS", \
	"FIL_UNCHANGED_RECORDS___ORIG_BUDG_COST as ORIG_BUDG_COST", \
	"FIL_UNCHANGED_RECORDS___BUDG_COST_CURRENCY_CODE as BUDG_COST_CURRENCY_CODE", \
	"FIL_UNCHANGED_RECORDS___BUDG_COST as BUDG_COST", \
	"FIL_UNCHANGED_RECORDS___ACTUAL_COST_CURRENCY_CODE as ACTUAL_COST_CURRENCY_CODE", \
	"FIL_UNCHANGED_RECORDS___TOTAL_MONETARY_VALUE as TOTAL_MONETARY_VALUE", \
	"FIL_UNCHANGED_RECORDS___UNIT_MONETARY_VALUE as UNIT_MONETARY_VALUE", \
	"FIL_UNCHANGED_RECORDS___UNIT_TAX_AMOUNT as UNIT_TAX_AMOUNT", \
	"FIL_UNCHANGED_RECORDS___RTS_ID as RTS_ID", \
	"FIL_UNCHANGED_RECORDS___RTS_LINE_ITEM_ID as RTS_LINE_ITEM_ID", \
	"FIL_UNCHANGED_RECORDS___STD_PACK_QTY as STD_PACK_QTY", \
	"FIL_UNCHANGED_RECORDS___PRODUCT_CLASS_ID as PRODUCT_CLASS_ID", \
	"FIL_UNCHANGED_RECORDS___PROTECTION_LEVEL_ID as PROTECTION_LEVEL_ID", \
	"FIL_UNCHANGED_RECORDS___PACKAGE_TYPE_ID as PACKAGE_TYPE_ID", \
	"FIL_UNCHANGED_RECORDS___COMMODITY_CODE_ID as COMMODITY_CODE_ID", \
	"FIL_UNCHANGED_RECORDS___MV_SIZE_UOM_ID as MV_SIZE_UOM_ID", \
	"FIL_UNCHANGED_RECORDS___QTY_UOM_ID_BASE as QTY_UOM_ID_BASE", \
	"FIL_UNCHANGED_RECORDS___MV_CURRENCY_CODE as MV_CURRENCY_CODE", \
	"FIL_UNCHANGED_RECORDS___SHIPPED_QTY as SHIPPED_QTY", \
	"FIL_UNCHANGED_RECORDS___RECEIVED_QTY as RECEIVED_QTY", \
	"FIL_UNCHANGED_RECORDS___PRIORITY as PRIORITY", \
	"FIL_UNCHANGED_RECORDS___MERCHANDIZING_DEPARTMENT_ID as MERCHANDIZING_DEPARTMENT_ID", \
	"FIL_UNCHANGED_RECORDS___UN_NUMBER_ID as UN_NUMBER_ID", \
	"FIL_UNCHANGED_RECORDS___PICKUP_REFERENCE_NUMBER as PICKUP_REFERENCE_NUMBER", \
	"FIL_UNCHANGED_RECORDS___DELIVERY_REFERENCE_NUMBER as DELIVERY_REFERENCE_NUMBER", \
	"FIL_UNCHANGED_RECORDS___CNTRY_OF_ORGN as CNTRY_OF_ORGN", \
	"FIL_UNCHANGED_RECORDS___PROD_STAT as PROD_STAT", \
	"FIL_UNCHANGED_RECORDS___STACK_RANK as STACK_RANK", \
	"FIL_UNCHANGED_RECORDS___STACK_LENGTH_VALUE as STACK_LENGTH_VALUE", \
	"FIL_UNCHANGED_RECORDS___STACK_LENGTH_STANDARD_UOM as STACK_LENGTH_STANDARD_UOM", \
	"FIL_UNCHANGED_RECORDS___STACK_WIDTH_VALUE as STACK_WIDTH_VALUE", \
	"FIL_UNCHANGED_RECORDS___STACK_WIDTH_STANDARD_UOM as STACK_WIDTH_STANDARD_UOM", \
	"FIL_UNCHANGED_RECORDS___STACK_HEIGHT_VALUE as STACK_HEIGHT_VALUE", \
	"FIL_UNCHANGED_RECORDS___STACK_HEIGHT_STANDARD_UOM as STACK_HEIGHT_STANDARD_UOM", \
	"FIL_UNCHANGED_RECORDS___STACK_DIAMETER_VALUE as STACK_DIAMETER_VALUE", \
	"FIL_UNCHANGED_RECORDS___STACK_DIAMETER_STANDARD_UOM as STACK_DIAMETER_STANDARD_UOM", \
	"FIL_UNCHANGED_RECORDS___CREATED_SOURCE_TYPE as CREATED_SOURCE_TYPE", \
	"FIL_UNCHANGED_RECORDS___CREATED_SOURCE as CREATED_SOURCE", \
	"FIL_UNCHANGED_RECORDS___CREATED_DTTM as CREATED_DTTM", \
	"FIL_UNCHANGED_RECORDS___LAST_UPDATED_SOURCE_TYPE as LAST_UPDATED_SOURCE_TYPE", \
	"FIL_UNCHANGED_RECORDS___LAST_UPDATED_SOURCE as LAST_UPDATED_SOURCE", \
	"FIL_UNCHANGED_RECORDS___LAST_UPDATED_DTTM as LAST_UPDATED_DTTM", \
	"FIL_UNCHANGED_RECORDS___HIBERNATE_VERSION as HIBERNATE_VERSION", \
	"FIL_UNCHANGED_RECORDS___CUBE_MULTIPLE_QTY as CUBE_MULTIPLE_QTY", \
	"FIL_UNCHANGED_RECORDS___DO_DTL_STATUS as DO_DTL_STATUS", \
	"FIL_UNCHANGED_RECORDS___INTERNAL_ORDER_SEQ_NBR as INTERNAL_ORDER_SEQ_NBR", \
    "CASE WHEN TRIM(UPPER(FIL_UNCHANGED_RECORDS___IS_EMERGENCY)) IN ('Y', '1') THEN '1' ELSE '0' END as o_EMERGENCY_FLAG", \
	"FIL_UNCHANGED_RECORDS___LPN_SIZE as LPN_SIZE", \
	"FIL_UNCHANGED_RECORDS___MANUFACTURING_DTTM as MANUFACTURING_DTTM", \
	"FIL_UNCHANGED_RECORDS___ORDER_LINE_ID as ORDER_LINE_ID", \
	"FIL_UNCHANGED_RECORDS___PACK_RATE as PACK_RATE", \
	"FIL_UNCHANGED_RECORDS___ALLOCATED_QTY as ALLOCATED_QTY", \
	"FIL_UNCHANGED_RECORDS___PLANNED_SHIP_DATE as PLANNED_SHIP_DATE", \
	"FIL_UNCHANGED_RECORDS___PPACK_QTY as PPACK_QTY", \
	"FIL_UNCHANGED_RECORDS___STD_BUNDLE_QTY as STD_BUNDLE_QTY", \
	"FIL_UNCHANGED_RECORDS___STD_LPN_QTY as STD_LPN_QTY", \
	"FIL_UNCHANGED_RECORDS___STD_LPN_VOL as STD_LPN_VOL", \
	"FIL_UNCHANGED_RECORDS___STD_LPN_WT as STD_LPN_WT", \
	"FIL_UNCHANGED_RECORDS___UNIT_COST as UNIT_COST", \
	"FIL_UNCHANGED_RECORDS___UNIT_PRICE_AMOUNT as UNIT_PRICE_AMOUNT", \
	"FIL_UNCHANGED_RECORDS___UNIT_VOL as UNIT_VOL", \
	"FIL_UNCHANGED_RECORDS___UNIT_WT as UNIT_WT", \
	"FIL_UNCHANGED_RECORDS___USER_CANCELED_QTY as USER_CANCELED_QTY", \
	"FIL_UNCHANGED_RECORDS___WAVE_PROC_TYPE as WAVE_PROC_TYPE", \
	"FIL_UNCHANGED_RECORDS___DELIVERY_END_DTTM as DELIVERY_END_DTTM", \
	"FIL_UNCHANGED_RECORDS___DELIVERY_START_DTTM as DELIVERY_START_DTTM", \
	"FIL_UNCHANGED_RECORDS___EVENT_CODE as EVENT_CODE", \
	"FIL_UNCHANGED_RECORDS___REASON_CODE as REASON_CODE", \
	"FIL_UNCHANGED_RECORDS___EXP_INFO_CODE as EXP_INFO_CODE", \
    "CASE WHEN TRIM(UPPER(FIL_UNCHANGED_RECORDS___PARTL_FILL)) IN ('Y', '1') THEN '1' ELSE '0' END as o_PARTL_FILL", \
	"FIL_UNCHANGED_RECORDS___LINE_TYPE as LINE_TYPE", \
	"FIL_UNCHANGED_RECORDS___REPL_PROC_TYPE as REPL_PROC_TYPE", \
	"FIL_UNCHANGED_RECORDS___ORDER_QTY as ORDER_QTY", \
	"FIL_UNCHANGED_RECORDS___ORIG_ORDER_QTY as ORIG_ORDER_QTY", \
	"FIL_UNCHANGED_RECORDS___RTL_TO_BE_DISTROED_QTY as RTL_TO_BE_DISTROED_QTY", \
	"FIL_UNCHANGED_RECORDS___PRICE as PRICE", \
	"FIL_UNCHANGED_RECORDS___RETAIL_PRICE as RETAIL_PRICE", \
	"FIL_UNCHANGED_RECORDS___UNITS_PAKD as UNITS_PAKD", \
	"FIL_UNCHANGED_RECORDS___MINOR_ORDER_NBR as MINOR_ORDER_NBR", \
	"FIL_UNCHANGED_RECORDS___ITEM_ID as ITEM_ID", \
	"FIL_UNCHANGED_RECORDS___TC_ORDER_LINE_ID as TC_ORDER_LINE_ID", \
	"FIL_UNCHANGED_RECORDS___ACTUAL_SHIPPED_DTTM as ACTUAL_SHIPPED_DTTM", \
	"FIL_UNCHANGED_RECORDS___QTY_UOM_ID as QTY_UOM_ID", \
	"FIL_UNCHANGED_RECORDS___PICKUP_END_DTTM as PICKUP_END_DTTM", \
	"FIL_UNCHANGED_RECORDS___PURCHASE_ORDER_LINE_NUMBER as PURCHASE_ORDER_LINE_NUMBER", \
	"FIL_UNCHANGED_RECORDS___PICKUP_START_DTTM as PICKUP_START_DTTM", \
	"FIL_UNCHANGED_RECORDS___REFERENCE_LINE_ITEM_ID as REFERENCE_LINE_ITEM_ID", \
	"FIL_UNCHANGED_RECORDS___REFERENCE_ORDER_ID as REFERENCE_ORDER_ID", \
    "CASE WHEN TRIM(UPPER(FIL_UNCHANGED_RECORDS___REPL_WAVE_RUN)) IN ('Y', '1') THEN '1' ELSE '0' END as o_REPL_WAVE_RUN", \
	"FIL_UNCHANGED_RECORDS___STD_PALLET_QTY as STD_PALLET_QTY", \
	"FIL_UNCHANGED_RECORDS___STD_SUB_PACK_QTY as STD_SUB_PACK_QTY", \
	"FIL_UNCHANGED_RECORDS___STORE_DEPT as STORE_DEPT", \
	"FIL_UNCHANGED_RECORDS___ALLOC_TYPE as ALLOC_TYPE", \
	"FIL_UNCHANGED_RECORDS___BATCH_NBR as BATCH_NBR", \
	"FIL_UNCHANGED_RECORDS___BATCH_REQUIREMENT_TYPE as BATCH_REQUIREMENT_TYPE", \
	"FIL_UNCHANGED_RECORDS___CHUTE_ASSIGN_TYPE as CHUTE_ASSIGN_TYPE", \
	"FIL_UNCHANGED_RECORDS___CUSTOM_TAG as CUSTOM_TAG", \
	"FIL_UNCHANGED_RECORDS___CUSTOMER_ITEM as CUSTOMER_ITEM", \
	"FIL_UNCHANGED_RECORDS___INTERNAL_ORDER_ID as INTERNAL_ORDER_ID", \
	"FIL_UNCHANGED_RECORDS___INVN_TYPE as INVN_TYPE", \
	"FIL_UNCHANGED_RECORDS___ITEM_ATTR_1 as ITEM_ATTR_1", \
	"FIL_UNCHANGED_RECORDS___ITEM_ATTR_2 as ITEM_ATTR_2", \
	"FIL_UNCHANGED_RECORDS___ITEM_ATTR_3 as ITEM_ATTR_3", \
	"FIL_UNCHANGED_RECORDS___ITEM_ATTR_4 as ITEM_ATTR_4", \
	"FIL_UNCHANGED_RECORDS___ITEM_ATTR_5 as ITEM_ATTR_5", \
	"FIL_UNCHANGED_RECORDS___LPN_BRK_ATTRIB as LPN_BRK_ATTRIB", \
	"FIL_UNCHANGED_RECORDS___MERCH_GRP as MERCH_GRP", \
	"FIL_UNCHANGED_RECORDS___MERCH_TYPE as MERCH_TYPE", \
	"FIL_UNCHANGED_RECORDS___PACK_ZONE as PACK_ZONE", \
	"FIL_UNCHANGED_RECORDS___PALLET_TYPE as PALLET_TYPE", \
	"FIL_UNCHANGED_RECORDS___PICK_LOCN_ASSIGN_TYPE as PICK_LOCN_ASSIGN_TYPE", \
	"FIL_UNCHANGED_RECORDS___PICK_LOCN_ID as PICK_LOCN_ID", \
	"FIL_UNCHANGED_RECORDS___PPACK_GRP_CODE as PPACK_GRP_CODE", \
	"FIL_UNCHANGED_RECORDS___PRICE_TKT_TYPE as PRICE_TKT_TYPE", \
    "CASE WHEN TRIM(UPPER(FIL_UNCHANGED_RECORDS___SERIAL_NUMBER_REQUIRED_FLAG)) IN ('Y', '1') THEN '1' ELSE '0' END as o_SERIAL_NUMBER_REQUIRED_FLAG", \
    "FIL_UNCHANGED_RECORDS___SKU_GTIN as SKU_GTIN", \
	"FIL_UNCHANGED_RECORDS___SKU_SUB_CODE_ID as SKU_SUB_CODE_ID", \
	"FIL_UNCHANGED_RECORDS___SKU_SUB_CODE_VALUE as SKU_SUB_CODE_VALUE", \
	"FIL_UNCHANGED_RECORDS___VAS_PROCESS_TYPE as VAS_PROCESS_TYPE", \
	"FIL_UNCHANGED_RECORDS___SUBSTITUTED_PARENT_LINE_ID as SUBSTITUTED_PARENT_LINE_ID", \
    "CASE WHEN TRIM(UPPER(FIL_UNCHANGED_RECORDS___IS_CANCELLED)) IN ('Y', '1') THEN '1' ELSE '0' END as o_CANCELLED_FLAG", \
	"FIL_UNCHANGED_RECORDS___ITEM_NAME as ITEM_NAME", \
	"FIL_UNCHANGED_RECORDS___ALLOC_LINE_ID as ALLOC_LINE_ID", \
	"FIL_UNCHANGED_RECORDS___ALLOCATION_SOURCE_ID as ALLOCATION_SOURCE_ID", \
	"FIL_UNCHANGED_RECORDS___ALLOCATION_SOURCE_LINE_ID as ALLOCATION_SOURCE_LINE_ID", \
	"FIL_UNCHANGED_RECORDS___ALLOCATION_SOURCE as ALLOCATION_SOURCE", \
	"FIL_UNCHANGED_RECORDS___SHELF_DAYS as SHELF_DAYS", \
	"FIL_UNCHANGED_RECORDS___FULFILLMENT_TYPE as FULFILLMENT_TYPE", \
	"FIL_UNCHANGED_RECORDS___WAVE_NBR as WAVE_NBR", \
	"FIL_UNCHANGED_RECORDS___SHIP_WAVE_NBR as SHIP_WAVE_NBR", \
	"FIL_UNCHANGED_RECORDS___REPL_WAVE_NBR as REPL_WAVE_NBR", \
    "CASE WHEN TRIM(UPPER(FIL_UNCHANGED_RECORDS___SINGLE_UNIT_FLAG)) IN ('Y', '1') THEN '1' ELSE '0' END as o_SINGLE_UNIT_FLAG", \
	"FIL_UNCHANGED_RECORDS___ACTUAL_COST as ACTUAL_COST", \
	"FIL_UNCHANGED_RECORDS___QTY_CONV_FACTOR as QTY_CONV_FACTOR", \
	"FIL_UNCHANGED_RECORDS___PLANNED_WEIGHT as PLANNED_WEIGHT", \
	"FIL_UNCHANGED_RECORDS___RECEIVED_WEIGHT as RECEIVED_WEIGHT", \
	"FIL_UNCHANGED_RECORDS___SHIPPED_WEIGHT as SHIPPED_WEIGHT", \
	"FIL_UNCHANGED_RECORDS___WEIGHT_UOM_ID_BASE as WEIGHT_UOM_ID_BASE", \
	"FIL_UNCHANGED_RECORDS___WEIGHT_UOM_ID as WEIGHT_UOM_ID", \
	"FIL_UNCHANGED_RECORDS___PLANNED_VOLUME as PLANNED_VOLUME", \
	"FIL_UNCHANGED_RECORDS___RECEIVED_VOLUME as RECEIVED_VOLUME", \
	"FIL_UNCHANGED_RECORDS___SHIPPED_VOLUME as SHIPPED_VOLUME", \
	"FIL_UNCHANGED_RECORDS___VOLUME_UOM_ID_BASE as VOLUME_UOM_ID_BASE", \
	"FIL_UNCHANGED_RECORDS___VOLUME_UOM_ID as VOLUME_UOM_ID", \
	"FIL_UNCHANGED_RECORDS___SIZE1_UOM_ID as SIZE1_UOM_ID", \
	"FIL_UNCHANGED_RECORDS___SIZE1_VALUE as SIZE1_VALUE", \
	"FIL_UNCHANGED_RECORDS___RECEIVED_SIZE1 as RECEIVED_SIZE1", \
	"FIL_UNCHANGED_RECORDS___SHIPPED_SIZE1 as SHIPPED_SIZE1", \
	"FIL_UNCHANGED_RECORDS___SIZE2_UOM_ID as SIZE2_UOM_ID", \
	"FIL_UNCHANGED_RECORDS___SIZE2_VALUE as SIZE2_VALUE", \
	"FIL_UNCHANGED_RECORDS___RECEIVED_SIZE2 as RECEIVED_SIZE2", \
	"FIL_UNCHANGED_RECORDS___SHIPPED_SIZE2 as SHIPPED_SIZE2", \
	"FIL_UNCHANGED_RECORDS___LPN_TYPE as LPN_TYPE", \
	"FIL_UNCHANGED_RECORDS___ORDER_CONSOL_ATTR as ORDER_CONSOL_ATTR", \
	"FIL_UNCHANGED_RECORDS___SKU_BREAK_ATTR as SKU_BREAK_ATTR", \
	"FIL_UNCHANGED_RECORDS___PURCHASE_ORDER_NUMBER as PURCHASE_ORDER_NUMBER", \
	"FIL_UNCHANGED_RECORDS___EXT_PURCHASE_ORDER as EXT_PURCHASE_ORDER", \
	"FIL_UNCHANGED_RECORDS___CRITCL_DIM_1 as CRITCL_DIM_1", \
	"FIL_UNCHANGED_RECORDS___CRITCL_DIM_2 as CRITCL_DIM_2", \
	"FIL_UNCHANGED_RECORDS___CRITCL_DIM_3 as CRITCL_DIM_3", \
	"FIL_UNCHANGED_RECORDS___ASSORT_NBR as ASSORT_NBR", \
	"FIL_UNCHANGED_RECORDS___DESCRIPTION as DESCRIPTION", \
	"FIL_UNCHANGED_RECORDS___ORIGINAL_ORDERED_ITEM_ID as ORIGINAL_ORDERED_ITEM_ID", \
	"FIL_UNCHANGED_RECORDS___SUBSTITUTION_TYPE as SUBSTITUTION_TYPE", \
	"FIL_UNCHANGED_RECORDS___BACK_ORD_REASON as BACK_ORD_REASON", \
	"FIL_UNCHANGED_RECORDS___FREIGHT_REVENUE_CURRENCY_CODE as FREIGHT_REVENUE_CURRENCY_CODE", \
	"FIL_UNCHANGED_RECORDS___FREIGHT_REVENUE as FREIGHT_REVENUE", \
	"FIL_UNCHANGED_RECORDS___IS_CHASE_CREATED_LINE as IS_CHASE_CREATED_LINE", \
	"FIL_UNCHANGED_RECORDS___REF_FIELD4 as REF_FIELD4", \
	"FIL_UNCHANGED_RECORDS___REF_FIELD5 as REF_FIELD5", \
	"FIL_UNCHANGED_RECORDS___REF_FIELD6 as REF_FIELD6", \
	"FIL_UNCHANGED_RECORDS___REF_FIELD7 as REF_FIELD7", \
	"FIL_UNCHANGED_RECORDS___REF_FIELD8 as REF_FIELD8", \
	"FIL_UNCHANGED_RECORDS___REF_FIELD9 as REF_FIELD9", \
	"FIL_UNCHANGED_RECORDS___REF_FIELD10 as REF_FIELD10", \
	"FIL_UNCHANGED_RECORDS___REF_NUM1 as REF_NUM1", \
	"FIL_UNCHANGED_RECORDS___REF_NUM2 as REF_NUM2", \
	"FIL_UNCHANGED_RECORDS___REF_NUM3 as REF_NUM3", \
	"FIL_UNCHANGED_RECORDS___REF_NUM4 as REF_NUM4", \
	"FIL_UNCHANGED_RECORDS___REF_NUM5 as REF_NUM5", \
	"FIL_UNCHANGED_RECORDS___IS_GIFT as IS_GIFT", \
	"FIL_UNCHANGED_RECORDS___ADJUSTED_ORDER_QTY as ADJUSTED_ORDER_QTY", \
	"FIL_UNCHANGED_RECORDS___PRE_RECEIPT_STATUS as PRE_RECEIPT_STATUS", \
	"FIL_UNCHANGED_RECORDS___ALLOW_REVIVAL_RECEIPT_ALLOC as ALLOW_REVIVAL_RECEIPT_ALLOC", \
	"FIL_UNCHANGED_RECORDS___SEGMENT_NAME as SEGMENT_NAME", \
	"FIL_UNCHANGED_RECORDS___EFFECTIVE_RANK as EFFECTIVE_RANK", \
	"FIL_UNCHANGED_RECORDS___WM_RECEIPT_ALLOCATED as WM_RECEIPT_ALLOCATED", \
	"FIL_UNCHANGED_RECORDS___GIFT_CARD_VALUE as GIFT_CARD_VALUE", \
	"FIL_UNCHANGED_RECORDS___REF_BOOLEAN1 as REF_BOOLEAN1", \
	"FIL_UNCHANGED_RECORDS___REF_BOOLEAN2 as REF_BOOLEAN2", \
	"FIL_UNCHANGED_RECORDS___REF_SYSCODE1 as REF_SYSCODE1", \
	"FIL_UNCHANGED_RECORDS___REF_SYSCODE2 as REF_SYSCODE2", \
	"FIL_UNCHANGED_RECORDS___REF_SYSCODE3 as REF_SYSCODE3", \
	"FIL_UNCHANGED_RECORDS___HARD_ALLOC_REASON_CODE as HARD_ALLOC_REASON_CODE", \
	"FIL_UNCHANGED_RECORDS___LOCKED as LOCKED", \
	"CURRENT_TIMESTAMP as UPDATE_TSTMP", \
	"IF(FIL_UNCHANGED_RECORDS___i_LOAD_TSTMP IS NULL, CURRENT_TIMESTAMP, FIL_UNCHANGED_RECORDS___i_LOAD_TSTMP) as LOAD_TSTMP", \
	"IF(FIL_UNCHANGED_RECORDS___i_WM_ORDER_ID IS NULL, 1, 2) as o_UPDATE_VALIDATOR" \
)

# COMMAND ----------
# Processing node UPD_INS_UPD, type UPDATE_STRATEGY 
# COLUMN COUNT: 212

# for each involved DataFrame, append the dataframe name to each column
EXP_UPD_VALIDATOR_temp = EXP_UPD_VALIDATOR.toDF(*["EXP_UPD_VALIDATOR___" + col for col in EXP_UPD_VALIDATOR.columns])

UPD_INS_UPD = EXP_UPD_VALIDATOR_temp.selectExpr( \
	"EXP_UPD_VALIDATOR___LOCATION_ID as LOCATION_ID", \
	"EXP_UPD_VALIDATOR___ORDER_ID as ORDER_ID", \
	"EXP_UPD_VALIDATOR___LINE_ITEM_ID as LINE_ITEM_ID", \
	"EXP_UPD_VALIDATOR___PARENT_LINE_ITEM_ID as PARENT_LINE_ITEM_ID", \
	"EXP_UPD_VALIDATOR___TC_COMPANY_ID as TC_COMPANY_ID", \
	"EXP_UPD_VALIDATOR___COMMODITY_CLASS as COMMODITY_CLASS", \
	"EXP_UPD_VALIDATOR___REF_FIELD1 as REF_FIELD1", \
	"EXP_UPD_VALIDATOR___REF_FIELD2 as REF_FIELD2", \
	"EXP_UPD_VALIDATOR___REF_FIELD3 as REF_FIELD3", \
	"EXP_UPD_VALIDATOR___EXT_SYS_LINE_ITEM_ID as EXT_SYS_LINE_ITEM_ID", \
	"EXP_UPD_VALIDATOR___MASTER_ORDER_ID as MASTER_ORDER_ID", \
	"EXP_UPD_VALIDATOR___MO_LINE_ITEM_ID as MO_LINE_ITEM_ID", \
	"EXP_UPD_VALIDATOR___IS_HAZMAT as IS_HAZMAT", \
	"EXP_UPD_VALIDATOR___IS_STACKABLE as IS_STACKABLE", \
	"EXP_UPD_VALIDATOR___HAS_ERRORS as HAS_ERRORS", \
	"EXP_UPD_VALIDATOR___ORIG_BUDG_COST as ORIG_BUDG_COST", \
	"EXP_UPD_VALIDATOR___BUDG_COST_CURRENCY_CODE as BUDG_COST_CURRENCY_CODE", \
	"EXP_UPD_VALIDATOR___BUDG_COST as BUDG_COST", \
	"EXP_UPD_VALIDATOR___ACTUAL_COST_CURRENCY_CODE as ACTUAL_COST_CURRENCY_CODE", \
	"EXP_UPD_VALIDATOR___TOTAL_MONETARY_VALUE as TOTAL_MONETARY_VALUE", \
	"EXP_UPD_VALIDATOR___UNIT_MONETARY_VALUE as UNIT_MONETARY_VALUE", \
	"EXP_UPD_VALIDATOR___UNIT_TAX_AMOUNT as UNIT_TAX_AMOUNT", \
	"EXP_UPD_VALIDATOR___RTS_ID as RTS_ID", \
	"EXP_UPD_VALIDATOR___RTS_LINE_ITEM_ID as RTS_LINE_ITEM_ID", \
	"EXP_UPD_VALIDATOR___STD_PACK_QTY as STD_PACK_QTY", \
	"EXP_UPD_VALIDATOR___PRODUCT_CLASS_ID as PRODUCT_CLASS_ID", \
	"EXP_UPD_VALIDATOR___PROTECTION_LEVEL_ID as PROTECTION_LEVEL_ID", \
	"EXP_UPD_VALIDATOR___PACKAGE_TYPE_ID as PACKAGE_TYPE_ID", \
	"EXP_UPD_VALIDATOR___COMMODITY_CODE_ID as COMMODITY_CODE_ID", \
	"EXP_UPD_VALIDATOR___MV_SIZE_UOM_ID as MV_SIZE_UOM_ID", \
	"EXP_UPD_VALIDATOR___QTY_UOM_ID_BASE as QTY_UOM_ID_BASE", \
	"EXP_UPD_VALIDATOR___MV_CURRENCY_CODE as MV_CURRENCY_CODE", \
	"EXP_UPD_VALIDATOR___SHIPPED_QTY as SHIPPED_QTY", \
	"EXP_UPD_VALIDATOR___RECEIVED_QTY as RECEIVED_QTY", \
	"EXP_UPD_VALIDATOR___PRIORITY as PRIORITY", \
	"EXP_UPD_VALIDATOR___MERCHANDIZING_DEPARTMENT_ID as MERCHANDIZING_DEPARTMENT_ID", \
	"EXP_UPD_VALIDATOR___UN_NUMBER_ID as UN_NUMBER_ID", \
	"EXP_UPD_VALIDATOR___PICKUP_REFERENCE_NUMBER as PICKUP_REFERENCE_NUMBER", \
	"EXP_UPD_VALIDATOR___DELIVERY_REFERENCE_NUMBER as DELIVERY_REFERENCE_NUMBER", \
	"EXP_UPD_VALIDATOR___CNTRY_OF_ORGN as CNTRY_OF_ORGN", \
	"EXP_UPD_VALIDATOR___PROD_STAT as PROD_STAT", \
	"EXP_UPD_VALIDATOR___STACK_RANK as STACK_RANK", \
	"EXP_UPD_VALIDATOR___STACK_LENGTH_VALUE as STACK_LENGTH_VALUE", \
	"EXP_UPD_VALIDATOR___STACK_LENGTH_STANDARD_UOM as STACK_LENGTH_STANDARD_UOM", \
	"EXP_UPD_VALIDATOR___STACK_WIDTH_VALUE as STACK_WIDTH_VALUE", \
	"EXP_UPD_VALIDATOR___STACK_WIDTH_STANDARD_UOM as STACK_WIDTH_STANDARD_UOM", \
	"EXP_UPD_VALIDATOR___STACK_HEIGHT_VALUE as STACK_HEIGHT_VALUE", \
	"EXP_UPD_VALIDATOR___STACK_HEIGHT_STANDARD_UOM as STACK_HEIGHT_STANDARD_UOM", \
	"EXP_UPD_VALIDATOR___STACK_DIAMETER_VALUE as STACK_DIAMETER_VALUE", \
	"EXP_UPD_VALIDATOR___STACK_DIAMETER_STANDARD_UOM as STACK_DIAMETER_STANDARD_UOM", \
	"EXP_UPD_VALIDATOR___CREATED_SOURCE_TYPE as CREATED_SOURCE_TYPE", \
	"EXP_UPD_VALIDATOR___CREATED_SOURCE as CREATED_SOURCE", \
	"EXP_UPD_VALIDATOR___CREATED_DTTM as CREATED_DTTM", \
	"EXP_UPD_VALIDATOR___LAST_UPDATED_SOURCE_TYPE as LAST_UPDATED_SOURCE_TYPE", \
	"EXP_UPD_VALIDATOR___LAST_UPDATED_SOURCE as LAST_UPDATED_SOURCE", \
	"EXP_UPD_VALIDATOR___LAST_UPDATED_DTTM as LAST_UPDATED_DTTM", \
	"EXP_UPD_VALIDATOR___HIBERNATE_VERSION as HIBERNATE_VERSION", \
	"EXP_UPD_VALIDATOR___CUBE_MULTIPLE_QTY as CUBE_MULTIPLE_QTY", \
	"EXP_UPD_VALIDATOR___DO_DTL_STATUS as DO_DTL_STATUS", \
	"EXP_UPD_VALIDATOR___INTERNAL_ORDER_SEQ_NBR as INTERNAL_ORDER_SEQ_NBR", \
	"EXP_UPD_VALIDATOR___o_EMERGENCY_FLAG as o_EMERGENCY_FLAG", \
	"EXP_UPD_VALIDATOR___LPN_SIZE as LPN_SIZE", \
	"EXP_UPD_VALIDATOR___MANUFACTURING_DTTM as MANUFACTURING_DTTM", \
	"EXP_UPD_VALIDATOR___ORDER_LINE_ID as ORDER_LINE_ID", \
	"EXP_UPD_VALIDATOR___PACK_RATE as PACK_RATE", \
	"EXP_UPD_VALIDATOR___ALLOCATED_QTY as ALLOCATED_QTY", \
	"EXP_UPD_VALIDATOR___PLANNED_SHIP_DATE as PLANNED_SHIP_DATE", \
	"EXP_UPD_VALIDATOR___PPACK_QTY as PPACK_QTY", \
	"EXP_UPD_VALIDATOR___STD_BUNDLE_QTY as STD_BUNDLE_QTY", \
	"EXP_UPD_VALIDATOR___STD_LPN_QTY as STD_LPN_QTY", \
	"EXP_UPD_VALIDATOR___STD_LPN_VOL as STD_LPN_VOL", \
	"EXP_UPD_VALIDATOR___STD_LPN_WT as STD_LPN_WT", \
	"EXP_UPD_VALIDATOR___UNIT_COST as UNIT_COST", \
	"EXP_UPD_VALIDATOR___UNIT_PRICE_AMOUNT as UNIT_PRICE_AMOUNT", \
	"EXP_UPD_VALIDATOR___UNIT_VOL as UNIT_VOL", \
	"EXP_UPD_VALIDATOR___UNIT_WT as UNIT_WT", \
	"EXP_UPD_VALIDATOR___USER_CANCELED_QTY as USER_CANCELED_QTY", \
	"EXP_UPD_VALIDATOR___WAVE_PROC_TYPE as WAVE_PROC_TYPE", \
	"EXP_UPD_VALIDATOR___DELIVERY_END_DTTM as DELIVERY_END_DTTM", \
	"EXP_UPD_VALIDATOR___DELIVERY_START_DTTM as DELIVERY_START_DTTM", \
	"EXP_UPD_VALIDATOR___EVENT_CODE as EVENT_CODE", \
	"EXP_UPD_VALIDATOR___REASON_CODE as REASON_CODE", \
	"EXP_UPD_VALIDATOR___EXP_INFO_CODE as EXP_INFO_CODE", \
	"EXP_UPD_VALIDATOR___o_PARTL_FILL as o_PARTL_FILL", \
	"EXP_UPD_VALIDATOR___LINE_TYPE as LINE_TYPE", \
	"EXP_UPD_VALIDATOR___REPL_PROC_TYPE as REPL_PROC_TYPE", \
	"EXP_UPD_VALIDATOR___ORDER_QTY as ORDER_QTY", \
	"EXP_UPD_VALIDATOR___ORIG_ORDER_QTY as ORIG_ORDER_QTY", \
	"EXP_UPD_VALIDATOR___RTL_TO_BE_DISTROED_QTY as RTL_TO_BE_DISTROED_QTY", \
	"EXP_UPD_VALIDATOR___PRICE as PRICE", \
	"EXP_UPD_VALIDATOR___RETAIL_PRICE as RETAIL_PRICE", \
	"EXP_UPD_VALIDATOR___UNITS_PAKD as UNITS_PAKD", \
	"EXP_UPD_VALIDATOR___MINOR_ORDER_NBR as MINOR_ORDER_NBR", \
	"EXP_UPD_VALIDATOR___ITEM_ID as ITEM_ID", \
	"EXP_UPD_VALIDATOR___TC_ORDER_LINE_ID as TC_ORDER_LINE_ID", \
	"EXP_UPD_VALIDATOR___ACTUAL_SHIPPED_DTTM as ACTUAL_SHIPPED_DTTM", \
	"EXP_UPD_VALIDATOR___QTY_UOM_ID as QTY_UOM_ID", \
	"EXP_UPD_VALIDATOR___PICKUP_END_DTTM as PICKUP_END_DTTM", \
	"EXP_UPD_VALIDATOR___PURCHASE_ORDER_LINE_NUMBER as PURCHASE_ORDER_LINE_NUMBER", \
	"EXP_UPD_VALIDATOR___PICKUP_START_DTTM as PICKUP_START_DTTM", \
	"EXP_UPD_VALIDATOR___REFERENCE_LINE_ITEM_ID as REFERENCE_LINE_ITEM_ID", \
	"EXP_UPD_VALIDATOR___REFERENCE_ORDER_ID as REFERENCE_ORDER_ID", \
	"EXP_UPD_VALIDATOR___o_REPL_WAVE_RUN as o_REPL_WAVE_RUN", \
	"EXP_UPD_VALIDATOR___STD_PALLET_QTY as STD_PALLET_QTY", \
	"EXP_UPD_VALIDATOR___STD_SUB_PACK_QTY as STD_SUB_PACK_QTY", \
	"EXP_UPD_VALIDATOR___STORE_DEPT as STORE_DEPT", \
	"EXP_UPD_VALIDATOR___ALLOC_TYPE as ALLOC_TYPE", \
	"EXP_UPD_VALIDATOR___BATCH_NBR as BATCH_NBR", \
	"EXP_UPD_VALIDATOR___BATCH_REQUIREMENT_TYPE as BATCH_REQUIREMENT_TYPE", \
	"EXP_UPD_VALIDATOR___CHUTE_ASSIGN_TYPE as CHUTE_ASSIGN_TYPE", \
	"EXP_UPD_VALIDATOR___CUSTOM_TAG as CUSTOM_TAG", \
	"EXP_UPD_VALIDATOR___CUSTOMER_ITEM as CUSTOMER_ITEM", \
	"EXP_UPD_VALIDATOR___INTERNAL_ORDER_ID as INTERNAL_ORDER_ID", \
	"EXP_UPD_VALIDATOR___INVN_TYPE as INVN_TYPE", \
	"EXP_UPD_VALIDATOR___ITEM_ATTR_1 as ITEM_ATTR_1", \
	"EXP_UPD_VALIDATOR___ITEM_ATTR_2 as ITEM_ATTR_2", \
	"EXP_UPD_VALIDATOR___ITEM_ATTR_3 as ITEM_ATTR_3", \
	"EXP_UPD_VALIDATOR___ITEM_ATTR_4 as ITEM_ATTR_4", \
	"EXP_UPD_VALIDATOR___ITEM_ATTR_5 as ITEM_ATTR_5", \
	"EXP_UPD_VALIDATOR___LPN_BRK_ATTRIB as LPN_BRK_ATTRIB", \
	"EXP_UPD_VALIDATOR___MERCH_GRP as MERCH_GRP", \
	"EXP_UPD_VALIDATOR___MERCH_TYPE as MERCH_TYPE", \
	"EXP_UPD_VALIDATOR___PACK_ZONE as PACK_ZONE", \
	"EXP_UPD_VALIDATOR___PALLET_TYPE as PALLET_TYPE", \
	"EXP_UPD_VALIDATOR___PICK_LOCN_ASSIGN_TYPE as PICK_LOCN_ASSIGN_TYPE", \
	"EXP_UPD_VALIDATOR___PICK_LOCN_ID as PICK_LOCN_ID", \
	"EXP_UPD_VALIDATOR___PPACK_GRP_CODE as PPACK_GRP_CODE", \
	"EXP_UPD_VALIDATOR___PRICE_TKT_TYPE as PRICE_TKT_TYPE", \
	"EXP_UPD_VALIDATOR___o_SERIAL_NUMBER_REQUIRED_FLAG as o_SERIAL_NUMBER_REQUIRED_FLAG", \
	"EXP_UPD_VALIDATOR___SKU_GTIN as SKU_GTIN", \
	"EXP_UPD_VALIDATOR___SKU_SUB_CODE_ID as SKU_SUB_CODE_ID", \
	"EXP_UPD_VALIDATOR___SKU_SUB_CODE_VALUE as SKU_SUB_CODE_VALUE", \
	"EXP_UPD_VALIDATOR___VAS_PROCESS_TYPE as VAS_PROCESS_TYPE", \
	"EXP_UPD_VALIDATOR___SUBSTITUTED_PARENT_LINE_ID as SUBSTITUTED_PARENT_LINE_ID", \
	"EXP_UPD_VALIDATOR___o_CANCELLED_FLAG as o_CANCELLED_FLAG", \
	"EXP_UPD_VALIDATOR___ITEM_NAME as ITEM_NAME", \
	"EXP_UPD_VALIDATOR___ALLOC_LINE_ID as ALLOC_LINE_ID", \
	"EXP_UPD_VALIDATOR___ALLOCATION_SOURCE_ID as ALLOCATION_SOURCE_ID", \
	"EXP_UPD_VALIDATOR___ALLOCATION_SOURCE_LINE_ID as ALLOCATION_SOURCE_LINE_ID", \
	"EXP_UPD_VALIDATOR___ALLOCATION_SOURCE as ALLOCATION_SOURCE", \
	"EXP_UPD_VALIDATOR___SHELF_DAYS as SHELF_DAYS", \
	"EXP_UPD_VALIDATOR___FULFILLMENT_TYPE as FULFILLMENT_TYPE", \
	"EXP_UPD_VALIDATOR___WAVE_NBR as WAVE_NBR", \
	"EXP_UPD_VALIDATOR___SHIP_WAVE_NBR as SHIP_WAVE_NBR", \
	"EXP_UPD_VALIDATOR___REPL_WAVE_NBR as REPL_WAVE_NBR", \
	"EXP_UPD_VALIDATOR___o_SINGLE_UNIT_FLAG as o_SINGLE_UNIT_FLAG", \
	"EXP_UPD_VALIDATOR___ACTUAL_COST as ACTUAL_COST", \
	"EXP_UPD_VALIDATOR___QTY_CONV_FACTOR as QTY_CONV_FACTOR", \
	"EXP_UPD_VALIDATOR___PLANNED_WEIGHT as PLANNED_WEIGHT", \
	"EXP_UPD_VALIDATOR___RECEIVED_WEIGHT as RECEIVED_WEIGHT", \
	"EXP_UPD_VALIDATOR___SHIPPED_WEIGHT as SHIPPED_WEIGHT", \
	"EXP_UPD_VALIDATOR___WEIGHT_UOM_ID_BASE as WEIGHT_UOM_ID_BASE", \
	"EXP_UPD_VALIDATOR___WEIGHT_UOM_ID as WEIGHT_UOM_ID", \
	"EXP_UPD_VALIDATOR___PLANNED_VOLUME as PLANNED_VOLUME", \
	"EXP_UPD_VALIDATOR___RECEIVED_VOLUME as RECEIVED_VOLUME", \
	"EXP_UPD_VALIDATOR___SHIPPED_VOLUME as SHIPPED_VOLUME", \
	"EXP_UPD_VALIDATOR___VOLUME_UOM_ID_BASE as VOLUME_UOM_ID_BASE", \
	"EXP_UPD_VALIDATOR___VOLUME_UOM_ID as VOLUME_UOM_ID", \
	"EXP_UPD_VALIDATOR___SIZE1_UOM_ID as SIZE1_UOM_ID", \
	"EXP_UPD_VALIDATOR___SIZE1_VALUE as SIZE1_VALUE", \
	"EXP_UPD_VALIDATOR___RECEIVED_SIZE1 as RECEIVED_SIZE1", \
	"EXP_UPD_VALIDATOR___SHIPPED_SIZE1 as SHIPPED_SIZE1", \
	"EXP_UPD_VALIDATOR___SIZE2_UOM_ID as SIZE2_UOM_ID", \
	"EXP_UPD_VALIDATOR___SIZE2_VALUE as SIZE2_VALUE", \
	"EXP_UPD_VALIDATOR___RECEIVED_SIZE2 as RECEIVED_SIZE2", \
	"EXP_UPD_VALIDATOR___SHIPPED_SIZE2 as SHIPPED_SIZE2", \
	"EXP_UPD_VALIDATOR___LPN_TYPE as LPN_TYPE", \
	"EXP_UPD_VALIDATOR___ORDER_CONSOL_ATTR as ORDER_CONSOL_ATTR", \
	"EXP_UPD_VALIDATOR___SKU_BREAK_ATTR as SKU_BREAK_ATTR", \
	"EXP_UPD_VALIDATOR___PURCHASE_ORDER_NUMBER as PURCHASE_ORDER_NUMBER", \
	"EXP_UPD_VALIDATOR___EXT_PURCHASE_ORDER as EXT_PURCHASE_ORDER", \
	"EXP_UPD_VALIDATOR___CRITCL_DIM_1 as CRITCL_DIM_1", \
	"EXP_UPD_VALIDATOR___CRITCL_DIM_2 as CRITCL_DIM_2", \
	"EXP_UPD_VALIDATOR___CRITCL_DIM_3 as CRITCL_DIM_3", \
	"EXP_UPD_VALIDATOR___ASSORT_NBR as ASSORT_NBR", \
	"EXP_UPD_VALIDATOR___DESCRIPTION as DESCRIPTION", \
	"EXP_UPD_VALIDATOR___ORIGINAL_ORDERED_ITEM_ID as ORIGINAL_ORDERED_ITEM_ID", \
	"EXP_UPD_VALIDATOR___SUBSTITUTION_TYPE as SUBSTITUTION_TYPE", \
	"EXP_UPD_VALIDATOR___BACK_ORD_REASON as BACK_ORD_REASON", \
	"EXP_UPD_VALIDATOR___FREIGHT_REVENUE_CURRENCY_CODE as FREIGHT_REVENUE_CURRENCY_CODE", \
	"EXP_UPD_VALIDATOR___FREIGHT_REVENUE as FREIGHT_REVENUE", \
	"EXP_UPD_VALIDATOR___IS_CHASE_CREATED_LINE as IS_CHASE_CREATED_LINE", \
	"EXP_UPD_VALIDATOR___REF_FIELD4 as REF_FIELD4", \
	"EXP_UPD_VALIDATOR___REF_FIELD5 as REF_FIELD5", \
	"EXP_UPD_VALIDATOR___REF_FIELD6 as REF_FIELD6", \
	"EXP_UPD_VALIDATOR___REF_FIELD7 as REF_FIELD7", \
	"EXP_UPD_VALIDATOR___REF_FIELD8 as REF_FIELD8", \
	"EXP_UPD_VALIDATOR___REF_FIELD9 as REF_FIELD9", \
	"EXP_UPD_VALIDATOR___REF_FIELD10 as REF_FIELD10", \
	"EXP_UPD_VALIDATOR___REF_NUM1 as REF_NUM1", \
	"EXP_UPD_VALIDATOR___REF_NUM2 as REF_NUM2", \
	"EXP_UPD_VALIDATOR___REF_NUM3 as REF_NUM3", \
	"EXP_UPD_VALIDATOR___REF_NUM4 as REF_NUM4", \
	"EXP_UPD_VALIDATOR___REF_NUM5 as REF_NUM5", \
	"EXP_UPD_VALIDATOR___IS_GIFT as IS_GIFT", \
	"EXP_UPD_VALIDATOR___ADJUSTED_ORDER_QTY as ADJUSTED_ORDER_QTY", \
	"EXP_UPD_VALIDATOR___PRE_RECEIPT_STATUS as PRE_RECEIPT_STATUS", \
	"EXP_UPD_VALIDATOR___ALLOW_REVIVAL_RECEIPT_ALLOC as ALLOW_REVIVAL_RECEIPT_ALLOC", \
	"EXP_UPD_VALIDATOR___SEGMENT_NAME as SEGMENT_NAME", \
	"EXP_UPD_VALIDATOR___EFFECTIVE_RANK as EFFECTIVE_RANK", \
	"EXP_UPD_VALIDATOR___WM_RECEIPT_ALLOCATED as WM_RECEIPT_ALLOCATED", \
	"EXP_UPD_VALIDATOR___GIFT_CARD_VALUE as GIFT_CARD_VALUE", \
	"EXP_UPD_VALIDATOR___REF_BOOLEAN1 as REF_BOOLEAN1", \
	"EXP_UPD_VALIDATOR___REF_BOOLEAN2 as REF_BOOLEAN2", \
	"EXP_UPD_VALIDATOR___REF_SYSCODE1 as REF_SYSCODE1", \
	"EXP_UPD_VALIDATOR___REF_SYSCODE2 as REF_SYSCODE2", \
	"EXP_UPD_VALIDATOR___REF_SYSCODE3 as REF_SYSCODE3", \
	"EXP_UPD_VALIDATOR___HARD_ALLOC_REASON_CODE as HARD_ALLOC_REASON_CODE", \
	"EXP_UPD_VALIDATOR___LOCKED as LOCKED", \
	"EXP_UPD_VALIDATOR___UPDATE_TSTMP as UPDATE_TSTMP", \
	"EXP_UPD_VALIDATOR___LOAD_TSTMP as LOAD_TSTMP", \
	"EXP_UPD_VALIDATOR___o_UPDATE_VALIDATOR as o_UPDATE_VALIDATOR") \
	.withColumn('pyspark_data_action', when(col('o_UPDATE_VALIDATOR') ==(lit(1)),lit(0)).when(col('o_UPDATE_VALIDATOR') ==(lit(2)),lit(1)))

# COMMAND ----------
# Processing node Shortcut_to_WM_ORDER_LINE_ITEM1, type TARGET 
# COLUMN COUNT: 211


Shortcut_to_WM_ORDER_LINE_ITEM1 = UPD_INS_UPD.selectExpr(
	"CAST(LOCATION_ID AS BIGINT) as LOCATION_ID",
	"CAST(ORDER_ID AS BIGINT) as WM_ORDER_ID",
	"CAST(LINE_ITEM_ID AS BIGINT) as WM_LINE_ITEM_ID",
	"CAST(DESCRIPTION AS STRING) as WM_DESC",
	"CAST(MASTER_ORDER_ID AS BIGINT) as WM_MASTER_ORDER_ID",
	"CAST(MO_LINE_ITEM_ID AS BIGINT) as WM_MO_LINE_ITEM_ID",
	"CAST(ORDER_LINE_ID AS BIGINT) as WM_ORDER_LINE_ID",
	"CAST(PARENT_LINE_ITEM_ID AS BIGINT) as WM_PARENT_LINE_ITEM_ID",
	"CAST(ITEM_ID AS INT) as WM_ITEM_ID",
	"CAST(ITEM_NAME AS STRING) as WM_ITEM_NAME",
	"CAST(ORIGINAL_ORDERED_ITEM_ID AS INT) as WM_ORIGINAL_ORDERED_ITEM_ID",
	"CAST(TC_COMPANY_ID AS INT) as WM_TC_COMPANY_ID",
	"CAST(TC_ORDER_LINE_ID AS STRING) as WM_TC_ORDER_LINE_ID",
	"CAST(MINOR_ORDER_NBR AS STRING) as WM_MINOR_ORDER_NBR",
	"CAST(INTERNAL_ORDER_ID AS STRING) as WM_INTERNAL_ORDER_ID",
	"CAST(INTERNAL_ORDER_SEQ_NBR AS INT) as WM_INTERNAL_ORDER_SEQ_NBR",
	"CAST(REFERENCE_ORDER_ID AS BIGINT) as WM_REF_ORDER_ID",
	"CAST(REFERENCE_LINE_ITEM_ID AS BIGINT) as WM_REF_LINE_ITEM_ID",
	"CAST(PURCHASE_ORDER_NUMBER AS STRING) as WM_PURCHASE_ORDER_NBR",
	"CAST(PURCHASE_ORDER_LINE_NUMBER AS STRING) as WM_PURCHASE_ORDER_LINE_NBR",
	"CAST(EXT_PURCHASE_ORDER AS STRING) as WM_EXT_PURCHASE_ORDER",
	"CAST(EXT_SYS_LINE_ITEM_ID AS STRING) as WM_EXT_SYS_LINE_ITEM_ID",
	"CAST(MERCHANDIZING_DEPARTMENT_ID AS BIGINT) as WM_MERCHANDIZING_DEPT_ID",
	"CAST(UN_NUMBER_ID AS BIGINT) as WM_UN_NBR_ID",
	"CAST(PICKUP_REFERENCE_NUMBER AS STRING) as WM_PICKUP_REF_NBR",
	"CAST(DELIVERY_REFERENCE_NUMBER AS STRING) as WM_DELIVERY_REF_NBR",
	"CAST(RTS_ID AS BIGINT) as WM_RTS_ID",
	"CAST(RTS_LINE_ITEM_ID AS BIGINT) as WM_RTS_LINE_ITEM_ID",
	"CAST(PROTECTION_LEVEL_ID AS INT) as WM_PROTECTION_LEVEL_ID",
	"CAST(PACKAGE_TYPE_ID AS INT) as WM_PACKAGE_TYPE_ID",
	"CAST(COMMODITY_CODE_ID AS BIGINT) as WM_COMMODITY_CD_ID",
	"CAST(EVENT_CODE AS STRING) as WM_EVENT_CD",
	"CAST(WAVE_NBR AS STRING) as WM_WAVE_NBR",
	"CAST(SHIP_WAVE_NBR AS STRING) as WM_SHIP_WAVE_NBR",
	"CAST(REPL_WAVE_NBR AS STRING) as WM_REPL_WAVE_NBR",
	"CAST(LPN_TYPE AS STRING) as WM_LPN_TYPE",
	"CAST(PRE_RECEIPT_STATUS AS STRING) as WM_PRE_RECEIPT_STATUS",
	"CAST(DO_DTL_STATUS AS SMALLINT) as WM_DO_DTL_STATUS",
	"CAST(PROD_STAT AS STRING) as WM_PROD_STAT",
	"CAST(HARD_ALLOC_REASON_CODE AS STRING) as WM_HARD_ALLOC_REASON_CD",
	"CAST(REASON_CODE AS STRING) as WM_REASON_CD",
	"CAST(BACK_ORD_REASON AS STRING) as BACK_ORD_REASON",
	"CAST(EXP_INFO_CODE AS STRING) as WM_EXP_INFO_CD",
	"CAST(WAVE_PROC_TYPE AS SMALLINT) as WM_WAVE_PROC_TYPE",
	"CAST(LINE_TYPE AS STRING) as LINE_TYPE",
	"CAST(REPL_PROC_TYPE AS SMALLINT) as REPL_PROC_TYPE",
	"CAST(o_REPL_WAVE_RUN AS TINYINT) as REPL_WAVE_RUN_FLAG",
	"CAST(ALLOC_TYPE AS STRING) as WM_ALLOC_TYPE",
	"CAST(BATCH_NBR AS STRING) as WM_BATCH_NBR",
	"CAST(BATCH_REQUIREMENT_TYPE AS STRING) as WM_BATCH_REQUIREMENT_TYPE",
	"CAST(CHUTE_ASSIGN_TYPE AS STRING) as WM_CHUTE_ASSIGN_TYPE",
	"CAST(INVN_TYPE AS STRING) as WM_INVN_TYPE",
	"CAST(LPN_BRK_ATTRIB AS STRING) as LPN_BRK_ATTR",
	"CAST(PACK_ZONE AS STRING) as PACK_ZONE",
	"CAST(PALLET_TYPE AS STRING) as WM_PALLET_TYPE",
	"CAST(PICK_LOCN_ASSIGN_TYPE AS STRING) as WM_PICK_LOCN_ASSIGN_TYPE",
	"CAST(PICK_LOCN_ID AS STRING) as WM_PICK_LOCN_ID",
	"CAST(PPACK_GRP_CODE AS STRING) as WM_PPACK_GRP_CD",
	"CAST(PRICE_TKT_TYPE AS STRING) as WM_PRICE_TKT_TYPE",
	"CAST(SHELF_DAYS AS INT) as WM_SHELF_DAYS",
	"CAST(FULFILLMENT_TYPE AS STRING) as WM_FULFILLMENT_TYPE",
	"CAST(ORDER_CONSOL_ATTR AS STRING) as WM_ORDER_CONSOL_ATTR",
	"CAST(VAS_PROCESS_TYPE AS STRING) as VAS_PROCESS_TYPE",
	"CAST(SEGMENT_NAME AS STRING) as WM_SEGMENT_NAME",
	"CAST(EFFECTIVE_RANK AS STRING) as WM_EFFECTIVE_RANK",
	"CAST(PRIORITY AS BIGINT) as PRIORITY",
	"CAST(ALLOW_REVIVAL_RECEIPT_ALLOC AS STRING) as ALLOW_REVIVAL_RECEIPT_ALLOC",
	"CAST(WM_RECEIPT_ALLOCATED AS TINYINT) as RECEIPT_ALLOCATED_FLAG",
	"CAST(IS_HAZMAT AS TINYINT) as HAZMAT_FLAG",
	"CAST(IS_STACKABLE AS TINYINT) as STACKABLE_FLAG",
	"CAST(HAS_ERRORS AS TINYINT) as HAS_ERRORS_FLAG",
	"CAST(o_EMERGENCY_FLAG AS TINYINT) as EMERGENCY_FLAG",
	"CAST(o_SINGLE_UNIT_FLAG AS TINYINT) as SINGLE_UNIT_FLAG",
	"CAST(o_SERIAL_NUMBER_REQUIRED_FLAG AS TINYINT) as SERIAL_NBR_REQD_FLAG",
	"CAST(IS_CHASE_CREATED_LINE AS TINYINT) as CHASE_CREATED_LINE_FLAG",
	"CAST(IS_GIFT AS TINYINT) as GIFT_FLAG",
	"CAST(o_PARTL_FILL AS TINYINT) as PARTIAL_FILL_FLAG",
	"CAST(LOCKED AS TINYINT) as LOCKED_FLAG",
	"CAST(o_CANCELLED_FLAG AS TINYINT) as CANCELLED_FLAG",
	"CAST(SKU_GTIN AS STRING) as SKU_GTIN",
	"CAST(CNTRY_OF_ORGN AS STRING) as COUNTRY_OF_ORIGIN",
	"CAST(COMMODITY_CLASS AS STRING) as COMMODITY_CLASS",
	"CAST(PRODUCT_CLASS_ID AS INT) as WM_PRODUCT_CLASS_ID",
	"CAST(STORE_DEPT AS STRING) as WM_STORE_DEPT",
	"CAST(MERCH_GRP AS STRING) as WM_MERCH_GRP",
	"CAST(MERCH_TYPE AS STRING) as WM_MERCH_TYPE",
	"CAST(CUSTOM_TAG AS STRING) as CUSTOM_TAG",
	"CAST(CUSTOMER_ITEM AS STRING) as CUSTOMER_ITEM",
	"CAST(SKU_SUB_CODE_ID AS STRING) as WM_SKU_SUB_CD_ID",
	"CAST(SKU_SUB_CODE_VALUE AS STRING) as WM_SKU_SUB_CD_VALUE",
	"CAST(SUBSTITUTED_PARENT_LINE_ID AS BIGINT) as WM_SUBSTITUTED_PARENT_LINE_ID",
	"CAST(ALLOCATION_SOURCE AS TINYINT) as WM_ALLOCATION_SOURCE",
	"CAST(ALLOC_LINE_ID AS INT) as WM_ALLOC_LINE_ID",
	"CAST(ALLOCATION_SOURCE_ID AS STRING) as WM_ALLOCATION_SOURCE_ID",
	"CAST(ALLOCATION_SOURCE_LINE_ID AS STRING) as WM_ALLOCATION_SOURCE_LINE_ID",
	"CAST(SKU_BREAK_ATTR AS STRING) as SKU_BREAK_ATTR",
	"CAST(ASSORT_NBR AS STRING) as WM_ASSORT_NBR",
	"CAST(SUBSTITUTION_TYPE AS STRING) as SUBSTITUTION_TYPE",
	"CAST(MANUFACTURING_DTTM AS TIMESTAMP) as MANUFACTURING_TSTMP",
	"CAST(PICKUP_START_DTTM AS TIMESTAMP) as PICKUP_START_TSTMP",
	"CAST(PICKUP_END_DTTM AS TIMESTAMP) as PICKUP_END_TSTMP",
	"CAST(DELIVERY_START_DTTM AS TIMESTAMP) as DELIVERY_START_TSTMP",
	"CAST(DELIVERY_END_DTTM AS TIMESTAMP) as DELIVERY_END_TSTMP",
	"CAST(PLANNED_SHIP_DATE AS TIMESTAMP) as PLANNED_SHIP_TSTMP",
	"CAST(ACTUAL_SHIPPED_DTTM AS TIMESTAMP) as ACTUAL_SHIPPED_TSTMP",
	"CAST(PACK_RATE AS DECIMAL(13,4)) as PACK_RATE",
	"CAST(PPACK_QTY AS DECIMAL(13,4)) as PPACK_QTY",
	"CAST(USER_CANCELED_QTY AS DECIMAL(13,4)) as USER_CANCELED_QTY",
	"CAST(ACTUAL_COST AS DECIMAL(13,4)) as ACTUAL_COST",
	"CAST(ORIG_BUDG_COST AS DECIMAL(13,4)) as ORIG_BUDG_COST",
	"CAST(BUDG_COST AS DECIMAL(13,4)) as BUDG_COST",
	"CAST(BUDG_COST_CURRENCY_CODE AS STRING) as BUDG_COST_CURRENCY_CD",
	"CAST(ACTUAL_COST_CURRENCY_CODE AS STRING) as ACTUAL_COST_CURRENCY_CD",
	"CAST(TOTAL_MONETARY_VALUE AS DECIMAL(13,4)) as TOTAL_MONETARY_VALUE",
	"CAST(PRICE AS DECIMAL(13,4)) as PRICE",
	"CAST(RETAIL_PRICE AS DECIMAL(16,4)) as RETAIL_PRICE",
	"CAST(GIFT_CARD_VALUE AS DECIMAL(13,4)) as GIFT_CARD_VALUE",
	"CAST(UNIT_COST AS DECIMAL(16,4)) as UNIT_COST",
	"CAST(UNIT_PRICE_AMOUNT AS DECIMAL(13,4)) as UNIT_PRICE_AMT",
	"CAST(UNIT_VOL AS DECIMAL(13,4)) as UNIT_VOL",
	"CAST(UNIT_WT AS DECIMAL(13,4)) as UNIT_WT",
	"CAST(UNIT_TAX_AMOUNT AS DECIMAL(16,4)) as UNIT_TAX_AMT",
	"CAST(UNIT_MONETARY_VALUE AS DECIMAL(13,4)) as UNIT_MONETARY_VALUE",
	"CAST(MV_CURRENCY_CODE AS STRING) as MV_CURRENCY_CD",
	"CAST(ORIG_ORDER_QTY AS DECIMAL(13,4)) as ORIG_ORDER_QTY",
	"CAST(ORDER_QTY AS DECIMAL(13,4)) as ORDER_QTY",
	"CAST(ADJUSTED_ORDER_QTY AS DECIMAL(13,4)) as ADJUSTED_ORDER_QTY",
	"CAST(ALLOCATED_QTY AS DECIMAL(13,4)) as ALLOCATED_QTY",
	"CAST(SHIPPED_QTY AS DECIMAL(13,4)) as SHIPPED_QTY",
	"CAST(RECEIVED_QTY AS DECIMAL(13,4)) as RECEIVED_QTY",
	"CAST(RTL_TO_BE_DISTROED_QTY AS DECIMAL(9,2)) as RTL_TO_BE_DISTROED_QTY",
	"CAST(UNITS_PAKD AS DECIMAL(13,4)) as UNITS_PAKD",
	"CAST(CUBE_MULTIPLE_QTY AS DECIMAL(13,4)) as CUBE_MULTIPLE_QTY",
	"CAST(STD_PACK_QTY AS DECIMAL(13,4)) as STD_PACK_QTY",
	"CAST(STD_PALLET_QTY AS DECIMAL(13,4)) as STD_PALLET_QTY",
	"CAST(STD_SUB_PACK_QTY AS DECIMAL(13,4)) as STD_SUB_PACK_QTY",
	"CAST(STD_BUNDLE_QTY AS DECIMAL(13,4)) as STD_BUNDLE_QTY",
	"CAST(STD_LPN_QTY AS DECIMAL(13,4)) as STD_LPN_QTY",
	"CAST(STD_LPN_VOL AS DECIMAL(13,4)) as STD_LPN_VOL",
	"CAST(STD_LPN_WT AS DECIMAL(13,4)) as STD_LPN_WT",
	"CAST(LPN_SIZE AS DECIMAL(16,4)) as LPN_SIZE",
	"CAST(QTY_CONV_FACTOR AS DECIMAL(17,8)) as QTY_CONV_FACTOR",
	"CAST(QTY_UOM_ID AS BIGINT) as WM_QTY_UOM_ID",
	"CAST(QTY_UOM_ID_BASE AS INT) as WM_QTY_UOM_ID_BASE",
	"CAST(MV_SIZE_UOM_ID AS INT) as WM_MV_SIZE_UOM_ID",
	"CAST(PLANNED_WEIGHT AS DECIMAL(13,4)) as PLANNED_WEIGHT",
	"CAST(RECEIVED_WEIGHT AS DECIMAL(13,4)) as RECEIVED_WEIGHT",
	"CAST(SHIPPED_WEIGHT AS DECIMAL(13,4)) as SHIPPED_WEIGHT",
	"CAST(WEIGHT_UOM_ID_BASE AS INT) as WM_WEIGHT_UOM_ID_BASE",
	"CAST(WEIGHT_UOM_ID AS INT) as WM_WEIGHT_UOM_ID",
	"CAST(PLANNED_VOLUME AS DECIMAL(13,4)) as PLANNED_VOLUME",
	"CAST(RECEIVED_VOLUME AS DECIMAL(13,4)) as RECEIVED_VOLUME",
	"CAST(SHIPPED_VOLUME AS DECIMAL(13,4)) as SHIPPED_VOLUME",
	"CAST(VOLUME_UOM_ID_BASE AS INT) as WM_VOLUME_UOM_ID_BASE",
	"CAST(VOLUME_UOM_ID AS INT) as WM_VOLUME_UOM_ID",
	"CAST(SIZE1_VALUE AS DECIMAL(13,4)) as SIZE_1_VALUE",
	"CAST(RECEIVED_SIZE1 AS DECIMAL(13,4)) as RECEIVED_SIZE_1",
	"CAST(SHIPPED_SIZE1 AS DECIMAL(13,4)) as SHIPPED_SIZE_1",
	"CAST(SIZE1_UOM_ID AS INT) as WM_SIZE_1_UOM_ID",
	"CAST(SIZE2_VALUE AS DECIMAL(13,4)) as SIZE_2_VALUE",
	"CAST(RECEIVED_SIZE2 AS DECIMAL(13,4)) as RECEIVED_SIZE_2",
	"CAST(SHIPPED_SIZE2 AS DECIMAL(13,4)) as SHIPPED_SIZE_2",
	"CAST(SIZE2_UOM_ID AS INT) as WM_SIZE_2_UOM_ID",
	"CAST(STACK_RANK AS SMALLINT) as STACK_RANK",
	"CAST(STACK_LENGTH_VALUE AS DECIMAL(16,4)) as STACK_LENGTH_VALUE",
	"CAST(STACK_LENGTH_STANDARD_UOM AS INT) as WM_STACK_LENGTH_STANDARD_UOM",
	"CAST(STACK_WIDTH_VALUE AS DECIMAL(16,4)) as STACK_WIDTH_VALUE",
	"CAST(STACK_WIDTH_STANDARD_UOM AS INT) as WM_STACK_WIDTH_STANDARD_UOM",
	"CAST(STACK_HEIGHT_VALUE AS DECIMAL(16,4)) as STACK_HEIGHT_VALUE",
	"CAST(STACK_HEIGHT_STANDARD_UOM AS INT) as WM_STACK_HEIGHT_STANDARD_UOM",
	"CAST(STACK_DIAMETER_VALUE AS DECIMAL(16,4)) as STACK_DIAMETER_VALUE",
	"CAST(STACK_DIAMETER_STANDARD_UOM AS INT) as WM_STACK_DIAMETER_STANDARD_UOM",
	"CAST(FREIGHT_REVENUE AS DECIMAL(13,4)) as FREIGHT_REVENUE",
	"CAST(FREIGHT_REVENUE_CURRENCY_CODE AS STRING) as FREIGHT_REVENUE_CURRENCY_CD",
	"CAST(ITEM_ATTR_1 AS STRING) as ITEM_ATTR_1",
	"CAST(ITEM_ATTR_2 AS STRING) as ITEM_ATTR_2",
	"CAST(ITEM_ATTR_3 AS STRING) as ITEM_ATTR_3",
	"CAST(ITEM_ATTR_4 AS STRING) as ITEM_ATTR_4",
	"CAST(ITEM_ATTR_5 AS STRING) as ITEM_ATTR_5",
	"CAST(CRITCL_DIM_1 AS DECIMAL(7,2)) as CRITCL_DIM_1",
	"CAST(CRITCL_DIM_2 AS DECIMAL(7,2)) as CRITCL_DIM_2",
	"CAST(CRITCL_DIM_3 AS DECIMAL(7,2)) as CRITCL_DIM_3",
	"CAST(REF_BOOLEAN1 AS TINYINT) as REF_BOOLEAN_1",
	"CAST(REF_BOOLEAN2 AS TINYINT) as REF_BOOLEAN_2",
	"CAST(REF_SYSCODE1 AS STRING) as REF_SYS_CD_1",
	"CAST(REF_SYSCODE2 AS STRING) as REF_SYS_CD_2",
	"CAST(REF_SYSCODE3 AS STRING) as REF_SYS_CD_3",
	"CAST(REF_FIELD1 AS STRING) as REF_FIELD_1",
	"CAST(REF_FIELD2 AS STRING) as REF_FIELD_2",
	"CAST(REF_FIELD3 AS STRING) as REF_FIELD_3",
	"CAST(REF_FIELD4 AS STRING) as REF_FIELD_4",
	"CAST(REF_FIELD5 AS STRING) as REF_FIELD_5",
	"CAST(REF_FIELD6 AS STRING) as REF_FIELD_6",
	"CAST(REF_FIELD7 AS STRING) as REF_FIELD_7",
	"CAST(REF_FIELD8 AS STRING) as REF_FIELD_8",
	"CAST(REF_FIELD9 AS STRING) as REF_FIELD_9",
	"CAST(REF_FIELD10 AS STRING) as REF_FIELD_10",
	"CAST(REF_NUM1 AS DECIMAL(13,5)) as REF_NUM_1",
	"CAST(REF_NUM2 AS DECIMAL(13,5)) as REF_NUM_2",
	"CAST(REF_NUM3 AS DECIMAL(13,5)) as REF_NUM_3",
	"CAST(REF_NUM4 AS DECIMAL(13,5)) as REF_NUM_4",
	"CAST(REF_NUM5 AS DECIMAL(13,5)) as REF_NUM_5",
	"CAST(HIBERNATE_VERSION AS BIGINT) as WM_HIBERNATE_VERSION",
	"CAST(CREATED_SOURCE_TYPE AS TINYINT) as WM_CREATED_SOURCE_TYPE",
	"CAST(CREATED_SOURCE AS STRING) as WM_CREATED_SOURCE",
	"CAST(CREATED_DTTM AS TIMESTAMP) as WM_CREATED_TSTMP",
	"CAST(LAST_UPDATED_SOURCE_TYPE AS TINYINT) as WM_LAST_UPDATED_SOURCE_TYPE",
	"CAST(LAST_UPDATED_SOURCE AS STRING) as WM_LAST_UPDATED_SOURCE",
	"CAST(LAST_UPDATED_DTTM AS TIMESTAMP) as WM_LAST_UPDATED_TSTMP",
	"CAST(UPDATE_TSTMP AS TIMESTAMP) as UPDATE_TSTMP",
	"CAST(LOAD_TSTMP AS TIMESTAMP) as LOAD_TSTMP", 
    "pyspark_data_action"\
)

try:
  primary_key = """source.LOCATION_ID = target.LOCATION_ID AND source.WM_ORDER_ID = target.WM_ORDER_ID AND source.WM_LINE_ITEM_ID = target.WM_LINE_ITEM_ID"""
  # refined_perf_table = "WM_ORDER_LINE_ITEM"
  executeMerge(Shortcut_to_WM_ORDER_LINE_ITEM1, refined_perf_table, primary_key)
  logger.info(f"Merge with {refined_perf_table} completed]")
  logPrevRunDt("WM_ORDER_LINE_ITEM", "WM_ORDER_LINE_ITEM", "Completed", "N/A", f"{raw}.log_run_details")
except Exception as e:
  logPrevRunDt("WM_ORDER_LINE_ITEM", "WM_ORDER_LINE_ITEM","Failed",str(e), f"{raw}.log_run_details", )
  raise e
