#Code converted on 2023-06-26 17:05:21
import os
import argparse
from pyspark.sql import *
from pyspark.sql.functions import *
from pyspark.sql.window import Window
from pyspark.sql.types import *
from datetime import datetime
from pyspark.dbutils import DBUtils
from utils.genericUtilities import *
from utils.configs import *
from utils.mergeUtils import *
from utils.logger import *



def m_WM_Outpt_Orders_PRE(dcnbr, env):
    from logging import getLogger, INFO

    logger = getLogger()
    spark: SparkSession = SparkSession.getActiveSession()
    logger.info("inside m_WM_Outpt_Orders_PRE")
    
    if dcnbr is None or dcnbr == "":
        raise ValueError("DC_NBR is not set")
    if env is None or env == "":
        raise ValueError("env is not set")
    
    refine = getEnvPrefix(env) + "refine"
    raw = getEnvPrefix(env) + "raw"
    
    tableName = "WM_OUTPT_ORDERS_PRE"
    schemaName = raw
    
    target_table_name = schemaName + "." + tableName
    refine_table_name = "WM_OUTPT_ORDERS"
    prev_run_dt=gu.genPrevRunDt(refine_table_name, refine,raw)
    print("The prev run date is " + prev_run_dt)
    
    (username, password, connection_string) = getConfig(dcnbr, env)
    logger.info("username, password, connection_string is obtained from getConfig fun")
    
    dcnbr = dcnbr.strip()[2:]
    query = f"""SELECT
                    OUTPT_ORDERS.ACCT_RCVBL_ACCT_NBR,
                    OUTPT_ORDERS.ACCT_RCVBL_CODE,
                    OUTPT_ORDERS.ADDR_CODE,
                    OUTPT_ORDERS.BACKORDERED_QUANTITY,
                    OUTPT_ORDERS.BATCH_CTRL_NBR,
                    OUTPT_ORDERS.BILLING_METHOD,
                    OUTPT_ORDERS.BILL_ACCT_NBR,
                    OUTPT_ORDERS.BILL_FACILITY_ALIAS_ID,
                    OUTPT_ORDERS.BILL_FACILITY_ID,
                    OUTPT_ORDERS.BILL_OF_LADING_NUMBER,
                    OUTPT_ORDERS.BILL_TO_ADDRESS_1,
                    OUTPT_ORDERS.BILL_TO_ADDRESS_2,
                    OUTPT_ORDERS.BILL_TO_ADDRESS_3,
                    OUTPT_ORDERS.BILL_TO_CITY,
                    OUTPT_ORDERS.BILL_TO_CONTACT,
                    OUTPT_ORDERS.BILL_TO_CONTACT_NAME,
                    OUTPT_ORDERS.BILL_TO_COUNTRY_CODE,
                    OUTPT_ORDERS.BILL_TO_COUNTY,
                    OUTPT_ORDERS.BILL_TO_EMAIL,
                    OUTPT_ORDERS.BILL_TO_FACILITY_NAME,
                    OUTPT_ORDERS.BILL_TO_FAX_NUMBER,
                    OUTPT_ORDERS.BILL_TO_NAME,
                    OUTPT_ORDERS.BILL_TO_PHONE_NUMBER,
                    OUTPT_ORDERS.BILL_TO_POSTAL_CODE,
                    OUTPT_ORDERS.BILL_TO_STATE_PROV,
                    OUTPT_ORDERS.BILL_TO_TITLE,
                    OUTPT_ORDERS.BOL_BREAK_ATTR,
                    OUTPT_ORDERS.BOL_TYPE,
                    OUTPT_ORDERS.BUSINESS_PARTNER,
                    OUTPT_ORDERS.CREATED_DTTM,
                    OUTPT_ORDERS.CREATED_SOURCE,
                    OUTPT_ORDERS.CREATED_SOURCE_TYPE,
                    OUTPT_ORDERS.CURRENCY,
                    OUTPT_ORDERS.D_ADDRESS_1,
                    OUTPT_ORDERS.D_ADDRESS_2,
                    OUTPT_ORDERS.D_ADDRESS_3,
                    OUTPT_ORDERS.D_CITY,
                    OUTPT_ORDERS.D_CONTACT,
                    OUTPT_ORDERS.D_COUNTRY_CODE,
                    OUTPT_ORDERS.D_COUNTY,
                    OUTPT_ORDERS.D_DOCK_DOOR_ID,
                    OUTPT_ORDERS.D_DOCK_ID,
                    OUTPT_ORDERS.D_EMAIL,
                    OUTPT_ORDERS.D_FACILITY_ALIAS_ID,
                    OUTPT_ORDERS.D_FACILITY_ID,
                    OUTPT_ORDERS.D_FACILITY_NAME,
                    OUTPT_ORDERS.D_FAX_NUMBER,
                    OUTPT_ORDERS.D_NAME,
                    OUTPT_ORDERS.D_PHONE_NUMBER,
                    OUTPT_ORDERS.D_POSTAL_CODE,
                    OUTPT_ORDERS.D_STATE_PROV,
                    OUTPT_ORDERS.DC_CTR_NBR,
                    OUTPT_ORDERS.DELIVERY_START_DTTM,
                    OUTPT_ORDERS.DISTRIBUTION_SHIP_VIA,
                    OUTPT_ORDERS.DO_TYPE,
                    OUTPT_ORDERS.ORIGINAL_SHIP_VIA,
                    OUTPT_ORDERS.EXT_PURCHASE_ORDER,
                    OUTPT_ORDERS.FREIGHT_CLASS,
                    OUTPT_ORDERS.FREIGHT_FORWARDER_ACCT_NBR,
                    OUTPT_ORDERS.GLOBAL_LOCN_NBR,
                    OUTPT_ORDERS.HANDLING_CHARGES,
                    OUTPT_ORDERS.INCOTERM_FACILITY_ALIAS_ID,
                    OUTPT_ORDERS.INCOTERM_FACILITY_ID,
                    OUTPT_ORDERS.INCOTERM_ID,
                    OUTPT_ORDERS.INCOTERM_LOC_AVA_DTTM,
                    OUTPT_ORDERS.INCOTERM_LOC_AVA_TIME_ZONE_ID,
                    OUTPT_ORDERS.INCOTERM_NAME,
                    OUTPT_ORDERS.INSUR_CHRG,
                    OUTPT_ORDERS.INVC_BATCH_NBR,
                    OUTPT_ORDERS.IS_BACK_ORDERED,
                    OUTPT_ORDERS.LAST_UPDATED_DTTM,
                    OUTPT_ORDERS.LAST_UPDATED_SOURCE,
                    OUTPT_ORDERS.LAST_UPDATED_SOURCE_TYPE,
                    OUTPT_ORDERS.MAJOR_MINOR_ORDER,
                    OUTPT_ORDERS.MAJOR_ORDER_CTRL_NBR,
                    OUTPT_ORDERS.MAJOR_ORDER_GRP_ATTR,
                    OUTPT_ORDERS.MANIFEST_ID,
                    OUTPT_ORDERS.MERCHANDIZING_DEPARTMENT,
                    OUTPT_ORDERS.MISC_CHARGES,
                    OUTPT_ORDERS.MONETARY_VALUE,
                    OUTPT_ORDERS.MOVEMENT_OPTION,
                    OUTPT_ORDERS.MV_CURRENCY,
                    OUTPT_ORDERS.NON_MACHINEABLE,
                    OUTPT_ORDERS.O_ADDRESS_1,
                    OUTPT_ORDERS.O_ADDRESS_2,
                    OUTPT_ORDERS.O_ADDRESS_3,
                    OUTPT_ORDERS.O_CITY,
                    OUTPT_ORDERS.O_CONTACT,
                    OUTPT_ORDERS.O_COUNTRY_CODE,
                    OUTPT_ORDERS.O_COUNTY,
                    OUTPT_ORDERS.O_DOCK_DOOR_ID,
                    OUTPT_ORDERS.O_DOCK_ID,
                    OUTPT_ORDERS.O_EMAIL,
                    OUTPT_ORDERS.O_FACILITY_ALIAS_ID,
                    OUTPT_ORDERS.O_FACILITY_ID,
                    OUTPT_ORDERS.O_FACILITY_NAME,
                    OUTPT_ORDERS.O_FAX_NUMBER,
                    OUTPT_ORDERS.O_POSTAL_CODE,
                    OUTPT_ORDERS.O_STATE_PROV,
                    OUTPT_ORDERS.ORDER_DATE_DTTM,
                    OUTPT_ORDERS.ORDER_WEIGHT,
                    OUTPT_ORDERS.OUTPT_ORDERS_ID,
                    OUTPT_ORDERS.ORG_SHIP_FACILITY_ALIAS_ID,
                    OUTPT_ORDERS.ORG_SHIP_FACILITY_ID,
                    OUTPT_ORDERS.ORIGINAL_ASSIGNED_SHIP_VIA,
                    OUTPT_ORDERS.ORIGIN_SHIP_THRU_FACILITY_ID,
                    OUTPT_ORDERS.ORIGIN_SHIP_THRU_FAC_ALIAS_ID,
                    OUTPT_ORDERS.PICKUP_END_DTTM,
                    OUTPT_ORDERS.PICKUP_START_DTTM,
                    OUTPT_ORDERS.PLANNED_SHIP_DATE,
                    OUTPT_ORDERS.PRE_PACK_FLAG,
                    OUTPT_ORDERS.PRIORITY,
                    OUTPT_ORDERS.PRO_NUMBER,
                    OUTPT_ORDERS.PROC_DTTM,
                    OUTPT_ORDERS.PROC_STAT_CODE,
                    OUTPT_ORDERS.REC_XPANS_FIELD,
                    OUTPT_ORDERS.RTE_ID,
                    OUTPT_ORDERS.RTE_SHIPMENT_SEQ,
                    OUTPT_ORDERS.SCHED_DELIVERY_DTTM,
                    OUTPT_ORDERS.SHIPMENT_ID,
                    OUTPT_ORDERS.SHIP_DATE,
                    OUTPT_ORDERS.SHIP_GROUP_ID,
                    OUTPT_ORDERS.SHIP_GROUP_SEQUENCE,
                    OUTPT_ORDERS.SHPNG_CHRG,
                    OUTPT_ORDERS.ORDER_STATUS,
                    OUTPT_ORDERS.DO_STATUS,
                    OUTPT_ORDERS.STORE_NBR,
                    OUTPT_ORDERS.STORE_TYPE,
                    OUTPT_ORDERS.TAX_CHARGES,
                    OUTPT_ORDERS.TC_COMPANY_ID,
                    OUTPT_ORDERS.TC_ORDER_ID,
                    OUTPT_ORDERS.TC_SHIPMENT_ID,
                    OUTPT_ORDERS.TOTAL_NBR_OF_LPN,
                    OUTPT_ORDERS.TOTAL_NBR_OF_PLT,
                    OUTPT_ORDERS.TOTAL_NBR_OF_UNITS,
                    OUTPT_ORDERS.VERSION_NBR,
                    OUTPT_ORDERS.LINE_HAUL_SHIP_VIA,
                    OUTPT_ORDERS.PLAN_D_FACILITY_ALIAS_ID,
                    OUTPT_ORDERS.PLAN_D_FACILITY_ID,
                    OUTPT_ORDERS.PLAN_LEG_D_ALIAS_ID,
                    OUTPT_ORDERS.PLAN_LEG_D_ID,
                    OUTPT_ORDERS.PLAN_LEG_O_ALIAS_ID,
                    OUTPT_ORDERS.PLAN_LEG_O_ID,
                    OUTPT_ORDERS.PLAN_O_FACILITY_ALIAS_ID,
                    OUTPT_ORDERS.PLAN_O_FACILITY_ID,
                    OUTPT_ORDERS.SPL_INSTR_CODE_1,
                    OUTPT_ORDERS.SPL_INSTR_CODE_10,
                    OUTPT_ORDERS.SPL_INSTR_CODE_2,
                    OUTPT_ORDERS.SPL_INSTR_CODE_3,
                    OUTPT_ORDERS.SPL_INSTR_CODE_4,
                    OUTPT_ORDERS.SPL_INSTR_CODE_5,
                    OUTPT_ORDERS.SPL_INSTR_CODE_6,
                    OUTPT_ORDERS.SPL_INSTR_CODE_7,
                    OUTPT_ORDERS.SPL_INSTR_CODE_8,
                    OUTPT_ORDERS.SPL_INSTR_CODE_9,
                    OUTPT_ORDERS.PRE_BILL_STATUS,
                    OUTPT_ORDERS.PRTL_SHIP_CONF_FLAG,
                    OUTPT_ORDERS.PRTL_SHIP_CONF_STATUS,
                    OUTPT_ORDERS.PRE_BILLED_FLAG,
                    OUTPT_ORDERS.TAX_ID,
                    OUTPT_ORDERS.ALLOW_PRE_BILLING,
                    OUTPT_ORDERS.O_PHONE_NUMBER,
                    OUTPT_ORDERS.PURCHASE_ORDER_NBR,
                    OUTPT_ORDERS.MARK_FOR,
                    OUTPT_ORDERS.DISTRO_NUMBER,
                    OUTPT_ORDERS.REF_SHIPMENT_NBR,
                    OUTPT_ORDERS.REF_STOP_SEQ,
                    OUTPT_ORDERS.PO_TYPE_ATTR,
                    OUTPT_ORDERS.DSG_SHIP_VIA
                FROM OUTPT_ORDERS
                WHERE {Initial_Load} (trunc(OUTPT_ORDERS.CREATED_DTTM) >= trunc(to_date('{Prev_Run_Dt}','MM/DD/YYYY HH24:MI:SS'))-1) OR (trunc(OUTPT_ORDERS.LAST_UPDATED_DTTM) >=  trunc(to_date('{Prev_Run_Dt}','MM/DD/YYYY HH24:MI:SS'))-1)"""

    SQ_Shortcut_to_OUTPT_ORDERS = gu.jdbcOracleConnection(query, username, password, connection_string).withColumn("sys_row_id", monotonically_increasing_id())
    logger.info("SQL query for SQ_Shortcut_to_OUTPT_ORDERS is executed and data is loaded using jdbc")


    # Processing node EXPTRANS, type EXPRESSION 
    # COLUMN COUNT: 171
    
    # for each involved DataFrame, append the dataframe name to each column
    SQ_Shortcut_to_OUTPT_ORDERS_temp = SQ_Shortcut_to_OUTPT_ORDERS.toDF(*["SQ_Shortcut_to_OUTPT_ORDERS___" + col for col in SQ_Shortcut_to_OUTPT_ORDERS.columns])
    
    EXPTRANS = SQ_Shortcut_to_OUTPT_ORDERS_temp.selectExpr( \
    	"SQ_Shortcut_to_OUTPT_ORDERS___sys_row_id as sys_row_id", \
    	f"{DC_NBR} as DC_NBR_EXP", \
    	"SQ_Shortcut_to_OUTPT_ORDERS___ACCT_RCVBL_ACCT_NBR as ACCT_RCVBL_ACCT_NBR", \
    	"SQ_Shortcut_to_OUTPT_ORDERS___ACCT_RCVBL_CODE as ACCT_RCVBL_CODE", \
    	"SQ_Shortcut_to_OUTPT_ORDERS___ADDR_CODE as ADDR_CODE", \
    	"SQ_Shortcut_to_OUTPT_ORDERS___BACKORDERED_QUANTITY as BACKORDERED_QUANTITY", \
    	"SQ_Shortcut_to_OUTPT_ORDERS___BATCH_CTRL_NBR as BATCH_CTRL_NBR", \
    	"SQ_Shortcut_to_OUTPT_ORDERS___BILLING_METHOD as BILLING_METHOD", \
    	"SQ_Shortcut_to_OUTPT_ORDERS___BILL_ACCT_NBR as BILL_ACCT_NBR", \
    	"SQ_Shortcut_to_OUTPT_ORDERS___BILL_FACILITY_ALIAS_ID as BILL_FACILITY_ALIAS_ID", \
    	"SQ_Shortcut_to_OUTPT_ORDERS___BILL_FACILITY_ID as BILL_FACILITY_ID", \
    	"SQ_Shortcut_to_OUTPT_ORDERS___BILL_OF_LADING_NUMBER as BILL_OF_LADING_NUMBER", \
    	"SQ_Shortcut_to_OUTPT_ORDERS___BILL_TO_ADDRESS_1 as BILL_TO_ADDRESS_1", \
    	"SQ_Shortcut_to_OUTPT_ORDERS___BILL_TO_ADDRESS_2 as BILL_TO_ADDRESS_2", \
    	"SQ_Shortcut_to_OUTPT_ORDERS___BILL_TO_ADDRESS_3 as BILL_TO_ADDRESS_3", \
    	"SQ_Shortcut_to_OUTPT_ORDERS___BILL_TO_CITY as BILL_TO_CITY", \
    	"SQ_Shortcut_to_OUTPT_ORDERS___BILL_TO_CONTACT as BILL_TO_CONTACT", \
    	"SQ_Shortcut_to_OUTPT_ORDERS___BILL_TO_CONTACT_NAME as BILL_TO_CONTACT_NAME", \
    	"SQ_Shortcut_to_OUTPT_ORDERS___BILL_TO_COUNTRY_CODE as BILL_TO_COUNTRY_CODE", \
    	"SQ_Shortcut_to_OUTPT_ORDERS___BILL_TO_COUNTY as BILL_TO_COUNTY", \
    	"SQ_Shortcut_to_OUTPT_ORDERS___BILL_TO_EMAIL as BILL_TO_EMAIL", \
    	"SQ_Shortcut_to_OUTPT_ORDERS___BILL_TO_FACILITY_NAME as BILL_TO_FACILITY_NAME", \
    	"SQ_Shortcut_to_OUTPT_ORDERS___BILL_TO_FAX_NUMBER as BILL_TO_FAX_NUMBER", \
    	"SQ_Shortcut_to_OUTPT_ORDERS___BILL_TO_NAME as BILL_TO_NAME", \
    	"SQ_Shortcut_to_OUTPT_ORDERS___BILL_TO_PHONE_NUMBER as BILL_TO_PHONE_NUMBER", \
    	"SQ_Shortcut_to_OUTPT_ORDERS___BILL_TO_POSTAL_CODE as BILL_TO_POSTAL_CODE", \
    	"SQ_Shortcut_to_OUTPT_ORDERS___BILL_TO_STATE_PROV as BILL_TO_STATE_PROV", \
    	"SQ_Shortcut_to_OUTPT_ORDERS___BILL_TO_TITLE as BILL_TO_TITLE", \
    	"SQ_Shortcut_to_OUTPT_ORDERS___BOL_BREAK_ATTR as BOL_BREAK_ATTR", \
    	"SQ_Shortcut_to_OUTPT_ORDERS___BOL_TYPE as BOL_TYPE", \
    	"SQ_Shortcut_to_OUTPT_ORDERS___BUSINESS_PARTNER as BUSINESS_PARTNER", \
    	"SQ_Shortcut_to_OUTPT_ORDERS___CREATED_DTTM as CREATED_DTTM", \
    	"SQ_Shortcut_to_OUTPT_ORDERS___CREATED_SOURCE as CREATED_SOURCE", \
    	"SQ_Shortcut_to_OUTPT_ORDERS___CREATED_SOURCE_TYPE as CREATED_SOURCE_TYPE", \
    	"SQ_Shortcut_to_OUTPT_ORDERS___CURRENCY as CURRENCY", \
    	"SQ_Shortcut_to_OUTPT_ORDERS___D_ADDRESS_1 as D_ADDRESS_1", \
    	"SQ_Shortcut_to_OUTPT_ORDERS___D_ADDRESS_2 as D_ADDRESS_2", \
    	"SQ_Shortcut_to_OUTPT_ORDERS___D_ADDRESS_3 as D_ADDRESS_3", \
    	"SQ_Shortcut_to_OUTPT_ORDERS___D_CITY as D_CITY", \
    	"SQ_Shortcut_to_OUTPT_ORDERS___D_CONTACT as D_CONTACT", \
    	"SQ_Shortcut_to_OUTPT_ORDERS___D_COUNTRY_CODE as D_COUNTRY_CODE", \
    	"SQ_Shortcut_to_OUTPT_ORDERS___D_COUNTY as D_COUNTY", \
    	"SQ_Shortcut_to_OUTPT_ORDERS___D_DOCK_DOOR_ID as D_DOCK_DOOR_ID", \
    	"SQ_Shortcut_to_OUTPT_ORDERS___D_DOCK_ID as D_DOCK_ID", \
    	"SQ_Shortcut_to_OUTPT_ORDERS___D_EMAIL as D_EMAIL", \
    	"SQ_Shortcut_to_OUTPT_ORDERS___D_FACILITY_ALIAS_ID as D_FACILITY_ALIAS_ID", \
    	"SQ_Shortcut_to_OUTPT_ORDERS___D_FACILITY_ID as D_FACILITY_ID", \
    	"SQ_Shortcut_to_OUTPT_ORDERS___D_FACILITY_NAME as D_FACILITY_NAME", \
    	"SQ_Shortcut_to_OUTPT_ORDERS___D_FAX_NUMBER as D_FAX_NUMBER", \
    	"SQ_Shortcut_to_OUTPT_ORDERS___D_NAME as D_NAME", \
    	"SQ_Shortcut_to_OUTPT_ORDERS___D_PHONE_NUMBER as D_PHONE_NUMBER", \
    	"SQ_Shortcut_to_OUTPT_ORDERS___D_POSTAL_CODE as D_POSTAL_CODE", \
    	"SQ_Shortcut_to_OUTPT_ORDERS___D_STATE_PROV as D_STATE_PROV", \
    	"SQ_Shortcut_to_OUTPT_ORDERS___DC_CTR_NBR as DC_CTR_NBR", \
    	"SQ_Shortcut_to_OUTPT_ORDERS___DELIVERY_START_DTTM as DELIVERY_START_DTTM", \
    	"SQ_Shortcut_to_OUTPT_ORDERS___DISTRIBUTION_SHIP_VIA as DISTRIBUTION_SHIP_VIA", \
    	"SQ_Shortcut_to_OUTPT_ORDERS___DO_TYPE as DO_TYPE", \
    	"SQ_Shortcut_to_OUTPT_ORDERS___ORIGINAL_SHIP_VIA as ORIGINAL_SHIP_VIA", \
    	"SQ_Shortcut_to_OUTPT_ORDERS___EXT_PURCHASE_ORDER as EXT_PURCHASE_ORDER", \
    	"SQ_Shortcut_to_OUTPT_ORDERS___FREIGHT_CLASS as FREIGHT_CLASS", \
    	"SQ_Shortcut_to_OUTPT_ORDERS___FREIGHT_FORWARDER_ACCT_NBR as FREIGHT_FORWARDER_ACCT_NBR", \
    	"SQ_Shortcut_to_OUTPT_ORDERS___GLOBAL_LOCN_NBR as GLOBAL_LOCN_NBR", \
    	"SQ_Shortcut_to_OUTPT_ORDERS___HANDLING_CHARGES as HANDLING_CHARGES", \
    	"SQ_Shortcut_to_OUTPT_ORDERS___INCOTERM_FACILITY_ALIAS_ID as INCOTERM_FACILITY_ALIAS_ID", \
    	"SQ_Shortcut_to_OUTPT_ORDERS___INCOTERM_FACILITY_ID as INCOTERM_FACILITY_ID", \
    	"SQ_Shortcut_to_OUTPT_ORDERS___INCOTERM_ID as INCOTERM_ID", \
    	"SQ_Shortcut_to_OUTPT_ORDERS___INCOTERM_LOC_AVA_DTTM as INCOTERM_LOC_AVA_DTTM", \
    	"SQ_Shortcut_to_OUTPT_ORDERS___INCOTERM_LOC_AVA_TIME_ZONE_ID as INCOTERM_LOC_AVA_TIME_ZONE_ID", \
    	"SQ_Shortcut_to_OUTPT_ORDERS___INCOTERM_NAME as INCOTERM_NAME", \
    	"SQ_Shortcut_to_OUTPT_ORDERS___INSUR_CHRG as INSUR_CHRG", \
    	"SQ_Shortcut_to_OUTPT_ORDERS___INVC_BATCH_NBR as INVC_BATCH_NBR", \
    	"SQ_Shortcut_to_OUTPT_ORDERS___IS_BACK_ORDERED as IS_BACK_ORDERED", \
    	"SQ_Shortcut_to_OUTPT_ORDERS___LAST_UPDATED_DTTM as LAST_UPDATED_DTTM", \
    	"SQ_Shortcut_to_OUTPT_ORDERS___LAST_UPDATED_SOURCE as LAST_UPDATED_SOURCE", \
    	"SQ_Shortcut_to_OUTPT_ORDERS___LAST_UPDATED_SOURCE_TYPE as LAST_UPDATED_SOURCE_TYPE", \
    	"SQ_Shortcut_to_OUTPT_ORDERS___MAJOR_MINOR_ORDER as MAJOR_MINOR_ORDER", \
    	"SQ_Shortcut_to_OUTPT_ORDERS___MAJOR_ORDER_CTRL_NBR as MAJOR_ORDER_CTRL_NBR", \
    	"SQ_Shortcut_to_OUTPT_ORDERS___MAJOR_ORDER_GRP_ATTR as MAJOR_ORDER_GRP_ATTR", \
    	"SQ_Shortcut_to_OUTPT_ORDERS___MANIFEST_ID as MANIFEST_ID", \
    	"SQ_Shortcut_to_OUTPT_ORDERS___MERCHANDIZING_DEPARTMENT as MERCHANDIZING_DEPARTMENT", \
    	"SQ_Shortcut_to_OUTPT_ORDERS___MISC_CHARGES as MISC_CHARGES", \
    	"SQ_Shortcut_to_OUTPT_ORDERS___MONETARY_VALUE as MONETARY_VALUE", \
    	"SQ_Shortcut_to_OUTPT_ORDERS___MOVEMENT_OPTION as MOVEMENT_OPTION", \
    	"SQ_Shortcut_to_OUTPT_ORDERS___MV_CURRENCY as MV_CURRENCY", \
    	"SQ_Shortcut_to_OUTPT_ORDERS___NON_MACHINEABLE as NON_MACHINEABLE", \
    	"SQ_Shortcut_to_OUTPT_ORDERS___O_ADDRESS_1 as O_ADDRESS_1", \
    	"SQ_Shortcut_to_OUTPT_ORDERS___O_ADDRESS_2 as O_ADDRESS_2", \
    	"SQ_Shortcut_to_OUTPT_ORDERS___O_ADDRESS_3 as O_ADDRESS_3", \
    	"SQ_Shortcut_to_OUTPT_ORDERS___O_CITY as O_CITY", \
    	"SQ_Shortcut_to_OUTPT_ORDERS___O_CONTACT as O_CONTACT", \
    	"SQ_Shortcut_to_OUTPT_ORDERS___O_COUNTRY_CODE as O_COUNTRY_CODE", \
    	"SQ_Shortcut_to_OUTPT_ORDERS___O_COUNTY as O_COUNTY", \
    	"SQ_Shortcut_to_OUTPT_ORDERS___O_DOCK_DOOR_ID as O_DOCK_DOOR_ID", \
    	"SQ_Shortcut_to_OUTPT_ORDERS___O_DOCK_ID as O_DOCK_ID", \
    	"SQ_Shortcut_to_OUTPT_ORDERS___O_EMAIL as O_EMAIL", \
    	"SQ_Shortcut_to_OUTPT_ORDERS___O_FACILITY_ALIAS_ID as O_FACILITY_ALIAS_ID", \
    	"SQ_Shortcut_to_OUTPT_ORDERS___O_FACILITY_ID as O_FACILITY_ID", \
    	"SQ_Shortcut_to_OUTPT_ORDERS___O_FACILITY_NAME as O_FACILITY_NAME", \
    	"SQ_Shortcut_to_OUTPT_ORDERS___O_FAX_NUMBER as O_FAX_NUMBER", \
    	"SQ_Shortcut_to_OUTPT_ORDERS___O_POSTAL_CODE as O_POSTAL_CODE", \
    	"SQ_Shortcut_to_OUTPT_ORDERS___O_STATE_PROV as O_STATE_PROV", \
    	"SQ_Shortcut_to_OUTPT_ORDERS___ORDER_DATE_DTTM as ORDER_DATE_DTTM", \
    	"SQ_Shortcut_to_OUTPT_ORDERS___ORDER_WEIGHT as ORDER_WEIGHT", \
    	"SQ_Shortcut_to_OUTPT_ORDERS___OUTPT_ORDERS_ID as OUTPT_ORDERS_ID", \
    	"SQ_Shortcut_to_OUTPT_ORDERS___ORG_SHIP_FACILITY_ALIAS_ID as ORG_SHIP_FACILITY_ALIAS_ID", \
    	"SQ_Shortcut_to_OUTPT_ORDERS___ORG_SHIP_FACILITY_ID as ORG_SHIP_FACILITY_ID", \
    	"SQ_Shortcut_to_OUTPT_ORDERS___ORIGINAL_ASSIGNED_SHIP_VIA as ORIGINAL_ASSIGNED_SHIP_VIA", \
    	"SQ_Shortcut_to_OUTPT_ORDERS___ORIGIN_SHIP_THRU_FACILITY_ID as ORIGIN_SHIP_THRU_FACILITY_ID", \
    	"SQ_Shortcut_to_OUTPT_ORDERS___ORIGIN_SHIP_THRU_FAC_ALIAS_ID as ORIGIN_SHIP_THRU_FAC_ALIAS_ID", \
    	"SQ_Shortcut_to_OUTPT_ORDERS___PICKUP_END_DTTM as PICKUP_END_DTTM", \
    	"SQ_Shortcut_to_OUTPT_ORDERS___PICKUP_START_DTTM as PICKUP_START_DTTM", \
    	"SQ_Shortcut_to_OUTPT_ORDERS___PLANNED_SHIP_DATE as PLANNED_SHIP_DATE", \
    	"SQ_Shortcut_to_OUTPT_ORDERS___PRE_PACK_FLAG as PRE_PACK_FLAG", \
    	"SQ_Shortcut_to_OUTPT_ORDERS___PRIORITY as PRIORITY", \
    	"SQ_Shortcut_to_OUTPT_ORDERS___PRO_NUMBER as PRO_NUMBER", \
    	"SQ_Shortcut_to_OUTPT_ORDERS___PROC_DTTM as PROC_DTTM", \
    	"SQ_Shortcut_to_OUTPT_ORDERS___PROC_STAT_CODE as PROC_STAT_CODE", \
    	"SQ_Shortcut_to_OUTPT_ORDERS___REC_XPANS_FIELD as REC_XPANS_FIELD", \
    	"SQ_Shortcut_to_OUTPT_ORDERS___RTE_ID as RTE_ID", \
    	"SQ_Shortcut_to_OUTPT_ORDERS___RTE_SHIPMENT_SEQ as RTE_SHIPMENT_SEQ", \
    	"SQ_Shortcut_to_OUTPT_ORDERS___SCHED_DELIVERY_DTTM as SCHED_DELIVERY_DTTM", \
    	"SQ_Shortcut_to_OUTPT_ORDERS___SHIPMENT_ID as SHIPMENT_ID", \
    	"SQ_Shortcut_to_OUTPT_ORDERS___SHIP_DATE as SHIP_DATE", \
    	"SQ_Shortcut_to_OUTPT_ORDERS___SHIP_GROUP_ID as SHIP_GROUP_ID", \
    	"SQ_Shortcut_to_OUTPT_ORDERS___SHIP_GROUP_SEQUENCE as SHIP_GROUP_SEQUENCE", \
    	"SQ_Shortcut_to_OUTPT_ORDERS___SHPNG_CHRG as SHPNG_CHRG", \
    	"SQ_Shortcut_to_OUTPT_ORDERS___ORDER_STATUS as ORDER_STATUS", \
    	"SQ_Shortcut_to_OUTPT_ORDERS___DO_STATUS as DO_STATUS", \
    	"SQ_Shortcut_to_OUTPT_ORDERS___STORE_NBR as STORE_NBR", \
    	"SQ_Shortcut_to_OUTPT_ORDERS___STORE_TYPE as STORE_TYPE", \
    	"SQ_Shortcut_to_OUTPT_ORDERS___TAX_CHARGES as TAX_CHARGES", \
    	"SQ_Shortcut_to_OUTPT_ORDERS___TC_COMPANY_ID as TC_COMPANY_ID", \
    	"SQ_Shortcut_to_OUTPT_ORDERS___TC_ORDER_ID as TC_ORDER_ID", \
    	"SQ_Shortcut_to_OUTPT_ORDERS___TC_SHIPMENT_ID as TC_SHIPMENT_ID", \
    	"SQ_Shortcut_to_OUTPT_ORDERS___TOTAL_NBR_OF_LPN as TOTAL_NBR_OF_LPN", \
    	"SQ_Shortcut_to_OUTPT_ORDERS___TOTAL_NBR_OF_PLT as TOTAL_NBR_OF_PLT", \
    	"SQ_Shortcut_to_OUTPT_ORDERS___TOTAL_NBR_OF_UNITS as TOTAL_NBR_OF_UNITS", \
    	"SQ_Shortcut_to_OUTPT_ORDERS___VERSION_NBR as VERSION_NBR", \
    	"SQ_Shortcut_to_OUTPT_ORDERS___LINE_HAUL_SHIP_VIA as LINE_HAUL_SHIP_VIA", \
    	"SQ_Shortcut_to_OUTPT_ORDERS___PLAN_D_FACILITY_ALIAS_ID as PLAN_D_FACILITY_ALIAS_ID", \
    	"SQ_Shortcut_to_OUTPT_ORDERS___PLAN_D_FACILITY_ID as PLAN_D_FACILITY_ID", \
    	"SQ_Shortcut_to_OUTPT_ORDERS___PLAN_LEG_D_ALIAS_ID as PLAN_LEG_D_ALIAS_ID", \
    	"SQ_Shortcut_to_OUTPT_ORDERS___PLAN_LEG_D_ID as PLAN_LEG_D_ID", \
    	"SQ_Shortcut_to_OUTPT_ORDERS___PLAN_LEG_O_ALIAS_ID as PLAN_LEG_O_ALIAS_ID", \
    	"SQ_Shortcut_to_OUTPT_ORDERS___PLAN_LEG_O_ID as PLAN_LEG_O_ID", \
    	"SQ_Shortcut_to_OUTPT_ORDERS___PLAN_O_FACILITY_ALIAS_ID as PLAN_O_FACILITY_ALIAS_ID", \
    	"SQ_Shortcut_to_OUTPT_ORDERS___PLAN_O_FACILITY_ID as PLAN_O_FACILITY_ID", \
    	"SQ_Shortcut_to_OUTPT_ORDERS___SPL_INSTR_CODE_1 as SPL_INSTR_CODE_1", \
    	"SQ_Shortcut_to_OUTPT_ORDERS___SPL_INSTR_CODE_10 as SPL_INSTR_CODE_10", \
    	"SQ_Shortcut_to_OUTPT_ORDERS___SPL_INSTR_CODE_2 as SPL_INSTR_CODE_2", \
    	"SQ_Shortcut_to_OUTPT_ORDERS___SPL_INSTR_CODE_3 as SPL_INSTR_CODE_3", \
    	"SQ_Shortcut_to_OUTPT_ORDERS___SPL_INSTR_CODE_4 as SPL_INSTR_CODE_4", \
    	"SQ_Shortcut_to_OUTPT_ORDERS___SPL_INSTR_CODE_5 as SPL_INSTR_CODE_5", \
    	"SQ_Shortcut_to_OUTPT_ORDERS___SPL_INSTR_CODE_6 as SPL_INSTR_CODE_6", \
    	"SQ_Shortcut_to_OUTPT_ORDERS___SPL_INSTR_CODE_7 as SPL_INSTR_CODE_7", \
    	"SQ_Shortcut_to_OUTPT_ORDERS___SPL_INSTR_CODE_8 as SPL_INSTR_CODE_8", \
    	"SQ_Shortcut_to_OUTPT_ORDERS___SPL_INSTR_CODE_9 as SPL_INSTR_CODE_9", \
    	"SQ_Shortcut_to_OUTPT_ORDERS___PRE_BILL_STATUS as PRE_BILL_STATUS", \
    	"SQ_Shortcut_to_OUTPT_ORDERS___PRTL_SHIP_CONF_FLAG as PRTL_SHIP_CONF_FLAG", \
    	"SQ_Shortcut_to_OUTPT_ORDERS___PRTL_SHIP_CONF_STATUS as PRTL_SHIP_CONF_STATUS", \
    	"SQ_Shortcut_to_OUTPT_ORDERS___PRE_BILLED_FLAG as PRE_BILLED_FLAG", \
    	"SQ_Shortcut_to_OUTPT_ORDERS___TAX_ID as TAX_ID", \
    	"SQ_Shortcut_to_OUTPT_ORDERS___ALLOW_PRE_BILLING as ALLOW_PRE_BILLING", \
    	"SQ_Shortcut_to_OUTPT_ORDERS___O_PHONE_NUMBER as O_PHONE_NUMBER", \
    	"SQ_Shortcut_to_OUTPT_ORDERS___PURCHASE_ORDER_NBR as PURCHASE_ORDER_NBR", \
    	"SQ_Shortcut_to_OUTPT_ORDERS___MARK_FOR as MARK_FOR", \
    	"SQ_Shortcut_to_OUTPT_ORDERS___DISTRO_NUMBER as DISTRO_NUMBER", \
    	"SQ_Shortcut_to_OUTPT_ORDERS___REF_SHIPMENT_NBR as REF_SHIPMENT_NBR", \
    	"SQ_Shortcut_to_OUTPT_ORDERS___REF_STOP_SEQ as REF_STOP_SEQ", \
    	"SQ_Shortcut_to_OUTPT_ORDERS___PO_TYPE_ATTR as PO_TYPE_ATTR", \
    	"SQ_Shortcut_to_OUTPT_ORDERS___DSG_SHIP_VIA as DSG_SHIP_VIA", \
    	"CURRENT_TIMESTAMP() as LOAD_TSTMP_EXP" \
    )
    
    
    # Processing node Shortcut_to_WM_OUTPT_ORDERS_PRE, type TARGET 
    # COLUMN COUNT: 171
    
    
    Shortcut_to_WM_OUTPT_ORDERS_PRE = EXPTRANS.selectExpr( \
    	"CAST(DC_NBR_EXP AS BIGINT) as DC_NBR", \
    	"CAST(OUTPT_ORDERS_ID AS BIGINT) as OUTPT_ORDERS_ID", \
    	"CAST(ACCT_RCVBL_ACCT_NBR AS STRING) as ACCT_RCVBL_ACCT_NBR", \
    	"CAST(ACCT_RCVBL_CODE AS STRING) as ACCT_RCVBL_CODE", \
    	"CAST(ADDR_CODE AS STRING) as ADDR_CODE", \
    	"CAST(BACKORDERED_QUANTITY AS BIGINT) as BACKORDERED_QUANTITY", \
    	"CAST(BATCH_CTRL_NBR AS STRING) as BATCH_CTRL_NBR", \
    	"CAST(BILLING_METHOD AS BIGINT) as BILLING_METHOD", \
    	"CAST(BILL_ACCT_NBR AS STRING) as BILL_ACCT_NBR", \
    	"CAST(BILL_FACILITY_ALIAS_ID AS STRING) as BILL_FACILITY_ALIAS_ID", \
    	"CAST(BILL_FACILITY_ID AS BIGINT) as BILL_FACILITY_ID", \
    	"CAST(BILL_OF_LADING_NUMBER AS STRING) as BILL_OF_LADING_NUMBER", \
    	"CAST(BILL_TO_ADDRESS_1 AS STRING) as BILL_TO_ADDRESS_1", \
    	"CAST(BILL_TO_ADDRESS_2 AS STRING) as BILL_TO_ADDRESS_2", \
    	"CAST(BILL_TO_ADDRESS_3 AS STRING) as BILL_TO_ADDRESS_3", \
    	"CAST(BILL_TO_CITY AS STRING) as BILL_TO_CITY", \
    	"CAST(BILL_TO_CONTACT AS STRING) as BILL_TO_CONTACT", \
    	"CAST(BILL_TO_CONTACT_NAME AS STRING) as BILL_TO_CONTACT_NAME", \
    	"CAST(BILL_TO_COUNTRY_CODE AS STRING) as BILL_TO_COUNTRY_CODE", \
    	"CAST(BILL_TO_COUNTY AS STRING) as BILL_TO_COUNTY", \
    	"CAST(BILL_TO_EMAIL AS STRING) as BILL_TO_EMAIL", \
    	"CAST(BILL_TO_FACILITY_NAME AS STRING) as BILL_TO_FACILITY_NAME", \
    	"CAST(BILL_TO_FAX_NUMBER AS STRING) as BILL_TO_FAX_NUMBER", \
    	"CAST(BILL_TO_NAME AS STRING) as BILL_TO_NAME", \
    	"CAST(BILL_TO_PHONE_NUMBER AS STRING) as BILL_TO_PHONE_NUMBER", \
    	"CAST(BILL_TO_POSTAL_CODE AS STRING) as BILL_TO_POSTAL_CODE", \
    	"CAST(BILL_TO_STATE_PROV AS STRING) as BILL_TO_STATE_PROV", \
    	"CAST(BILL_TO_TITLE AS STRING) as BILL_TO_TITLE", \
    	"CAST(BOL_BREAK_ATTR AS STRING) as BOL_BREAK_ATTR", \
    	"CAST(BOL_TYPE AS STRING) as BOL_TYPE", \
    	"CAST(BUSINESS_PARTNER AS STRING) as BUSINESS_PARTNER", \
    	"CAST(CREATED_DTTM AS TIMESTAMP) as CREATED_DTTM", \
    	"CAST(CREATED_SOURCE AS STRING) as CREATED_SOURCE", \
    	"CAST(CREATED_SOURCE_TYPE AS BIGINT) as CREATED_SOURCE_TYPE", \
    	"CAST(CURRENCY AS STRING) as CURRENCY", \
    	"CAST(D_ADDRESS_1 AS STRING) as D_ADDRESS_1", \
    	"CAST(D_ADDRESS_2 AS STRING) as D_ADDRESS_2", \
    	"CAST(D_ADDRESS_3 AS STRING) as D_ADDRESS_3", \
    	"CAST(D_CITY AS STRING) as D_CITY", \
    	"CAST(D_CONTACT AS STRING) as D_CONTACT", \
    	"CAST(D_COUNTRY_CODE AS STRING) as D_COUNTRY_CODE", \
    	"CAST(D_COUNTY AS STRING) as D_COUNTY", \
    	"CAST(D_DOCK_DOOR_ID AS BIGINT) as D_DOCK_DOOR_ID", \
    	"CAST(D_DOCK_ID AS STRING) as D_DOCK_ID", \
    	"CAST(D_EMAIL AS STRING) as D_EMAIL", \
    	"CAST(D_FACILITY_ALIAS_ID AS STRING) as D_FACILITY_ALIAS_ID", \
    	"CAST(D_FACILITY_ID AS BIGINT) as D_FACILITY_ID", \
    	"CAST(D_FACILITY_NAME AS STRING) as D_FACILITY_NAME", \
    	"CAST(D_FAX_NUMBER AS STRING) as D_FAX_NUMBER", \
    	"CAST(D_NAME AS STRING) as D_NAME", \
    	"CAST(D_PHONE_NUMBER AS STRING) as D_PHONE_NUMBER", \
    	"CAST(D_POSTAL_CODE AS STRING) as D_POSTAL_CODE", \
    	"CAST(D_STATE_PROV AS STRING) as D_STATE_PROV", \
    	"CAST(DC_CTR_NBR AS STRING) as DC_CTR_NBR", \
    	"CAST(DELIVERY_START_DTTM AS TIMESTAMP) as DELIVERY_START_DTTM", \
    	"CAST(DISTRIBUTION_SHIP_VIA AS STRING) as DISTRIBUTION_SHIP_VIA", \
    	"CAST(DO_TYPE AS BIGINT) as DO_TYPE", \
    	"CAST(ORIGINAL_SHIP_VIA AS STRING) as ORIGINAL_SHIP_VIA", \
    	"CAST(EXT_PURCHASE_ORDER AS STRING) as EXT_PURCHASE_ORDER", \
    	"CAST(FREIGHT_CLASS AS BIGINT) as FREIGHT_CLASS", \
    	"CAST(FREIGHT_FORWARDER_ACCT_NBR AS STRING) as FREIGHT_FORWARDER_ACCT_NBR", \
    	"CAST(GLOBAL_LOCN_NBR AS STRING) as GLOBAL_LOCN_NBR", \
    	"CAST(HANDLING_CHARGES AS BIGINT) as HANDLING_CHARGES", \
    	"CAST(INCOTERM_FACILITY_ALIAS_ID AS STRING) as INCOTERM_FACILITY_ALIAS_ID", \
    	"CAST(INCOTERM_FACILITY_ID AS BIGINT) as INCOTERM_FACILITY_ID", \
    	"CAST(INCOTERM_ID AS BIGINT) as INCOTERM_ID", \
    	"CAST(INCOTERM_LOC_AVA_DTTM AS TIMESTAMP) as INCOTERM_LOC_AVA_DTTM", \
    	"CAST(INCOTERM_LOC_AVA_TIME_ZONE_ID AS BIGINT) as INCOTERM_LOC_AVA_TIME_ZONE_ID", \
    	"CAST(INCOTERM_NAME AS STRING) as INCOTERM_NAME", \
    	"CAST(INSUR_CHRG AS BIGINT) as INSUR_CHRG", \
    	"CAST(INVC_BATCH_NBR AS BIGINT) as INVC_BATCH_NBR", \
    	"CAST(IS_BACK_ORDERED AS STRING) as IS_BACK_ORDERED", \
    	"CAST(LAST_UPDATED_DTTM AS TIMESTAMP) as LAST_UPDATED_DTTM", \
    	"CAST(LAST_UPDATED_SOURCE AS STRING) as LAST_UPDATED_SOURCE", \
    	"CAST(LAST_UPDATED_SOURCE_TYPE AS BIGINT) as LAST_UPDATED_SOURCE_TYPE", \
    	"CAST(MAJOR_MINOR_ORDER AS STRING) as MAJOR_MINOR_ORDER", \
    	"CAST(MAJOR_ORDER_CTRL_NBR AS STRING) as MAJOR_ORDER_CTRL_NBR", \
    	"CAST(MAJOR_ORDER_GRP_ATTR AS STRING) as MAJOR_ORDER_GRP_ATTR", \
    	"CAST(MANIFEST_ID AS STRING) as MANIFEST_ID", \
    	"CAST(MERCHANDIZING_DEPARTMENT AS STRING) as MERCHANDIZING_DEPARTMENT", \
    	"CAST(MISC_CHARGES AS BIGINT) as MISC_CHARGES", \
    	"CAST(MONETARY_VALUE AS BIGINT) as MONETARY_VALUE", \
    	"CAST(MOVEMENT_OPTION AS BIGINT) as MOVEMENT_OPTION", \
    	"CAST(MV_CURRENCY AS STRING) as MV_CURRENCY", \
    	"CAST(NON_MACHINEABLE AS BIGINT) as NON_MACHINEABLE", \
    	"CAST(O_ADDRESS_1 AS STRING) as O_ADDRESS_1", \
    	"CAST(O_ADDRESS_2 AS STRING) as O_ADDRESS_2", \
    	"CAST(O_ADDRESS_3 AS STRING) as O_ADDRESS_3", \
    	"CAST(O_CITY AS STRING) as O_CITY", \
    	"CAST(O_CONTACT AS STRING) as O_CONTACT", \
    	"CAST(O_COUNTRY_CODE AS STRING) as O_COUNTRY_CODE", \
    	"CAST(O_COUNTY AS STRING) as O_COUNTY", \
    	"CAST(O_DOCK_DOOR_ID AS BIGINT) as O_DOCK_DOOR_ID", \
    	"CAST(O_DOCK_ID AS STRING) as O_DOCK_ID", \
    	"CAST(O_EMAIL AS STRING) as O_EMAIL", \
    	"CAST(O_FACILITY_ALIAS_ID AS STRING) as O_FACILITY_ALIAS_ID", \
    	"CAST(O_FACILITY_ID AS BIGINT) as O_FACILITY_ID", \
    	"CAST(O_FACILITY_NAME AS STRING) as O_FACILITY_NAME", \
    	"CAST(O_FAX_NUMBER AS STRING) as O_FAX_NUMBER", \
    	"CAST(O_POSTAL_CODE AS STRING) as O_POSTAL_CODE", \
    	"CAST(O_STATE_PROV AS STRING) as O_STATE_PROV", \
    	"CAST(ORDER_DATE_DTTM AS TIMESTAMP) as ORDER_DATE_DTTM", \
    	"CAST(ORDER_WEIGHT AS BIGINT) as ORDER_WEIGHT", \
    	"CAST(ORG_SHIP_FACILITY_ALIAS_ID AS STRING) as ORG_SHIP_FACILITY_ALIAS_ID", \
    	"CAST(ORG_SHIP_FACILITY_ID AS BIGINT) as ORG_SHIP_FACILITY_ID", \
    	"CAST(ORIGINAL_ASSIGNED_SHIP_VIA AS STRING) as ORIGINAL_ASSIGNED_SHIP_VIA", \
    	"CAST(ORIGIN_SHIP_THRU_FACILITY_ID AS BIGINT) as ORIGIN_SHIP_THRU_FACILITY_ID", \
    	"CAST(ORIGIN_SHIP_THRU_FAC_ALIAS_ID AS STRING) as ORIGIN_SHIP_THRU_FAC_ALIAS_ID", \
    	"CAST(PICKUP_END_DTTM AS TIMESTAMP) as PICKUP_END_DTTM", \
    	"CAST(PICKUP_START_DTTM AS TIMESTAMP) as PICKUP_START_DTTM", \
    	"CAST(PLANNED_SHIP_DATE AS TIMESTAMP) as PLANNED_SHIP_DATE", \
    	"CAST(PRE_PACK_FLAG AS BIGINT) as PRE_PACK_FLAG", \
    	"CAST(PRIORITY AS BIGINT) as PRIORITY", \
    	"CAST(PRO_NUMBER AS STRING) as PRO_NUMBER", \
    	"CAST(PROC_DTTM AS TIMESTAMP) as PROC_DTTM", \
    	"CAST(PROC_STAT_CODE AS BIGINT) as PROC_STAT_CODE", \
    	"CAST(REC_XPANS_FIELD AS STRING) as REC_XPANS_FIELD", \
    	"CAST(RTE_ID AS STRING) as RTE_ID", \
    	"CAST(RTE_SHIPMENT_SEQ AS BIGINT) as RTE_SHIPMENT_SEQ", \
    	"CAST(SCHED_DELIVERY_DTTM AS TIMESTAMP) as SCHED_DELIVERY_DTTM", \
    	"CAST(SHIPMENT_ID AS BIGINT) as SHIPMENT_ID", \
    	"CAST(SHIP_DATE AS TIMESTAMP) as SHIP_DATE", \
    	"CAST(SHIP_GROUP_ID AS STRING) as SHIP_GROUP_ID", \
    	"CAST(SHIP_GROUP_SEQUENCE AS BIGINT) as SHIP_GROUP_SEQUENCE", \
    	"CAST(SHPNG_CHRG AS BIGINT) as SHPNG_CHRG", \
    	"CAST(ORDER_STATUS AS BIGINT) as ORDER_STATUS", \
    	"CAST(DO_STATUS AS BIGINT) as DO_STATUS", \
    	"CAST(STORE_NBR AS STRING) as STORE_NBR", \
    	"CAST(STORE_TYPE AS STRING) as STORE_TYPE", \
    	"CAST(TAX_CHARGES AS BIGINT) as TAX_CHARGES", \
    	"CAST(TC_COMPANY_ID AS BIGINT) as TC_COMPANY_ID", \
    	"CAST(TC_ORDER_ID AS STRING) as TC_ORDER_ID", \
    	"CAST(TC_SHIPMENT_ID AS STRING) as TC_SHIPMENT_ID", \
    	"CAST(TOTAL_NBR_OF_LPN AS BIGINT) as TOTAL_NBR_OF_LPN", \
    	"CAST(TOTAL_NBR_OF_PLT AS BIGINT) as TOTAL_NBR_OF_PLT", \
    	"CAST(TOTAL_NBR_OF_UNITS AS BIGINT) as TOTAL_NBR_OF_UNITS", \
    	"CAST(VERSION_NBR AS BIGINT) as VERSION_NBR", \
    	"CAST(LINE_HAUL_SHIP_VIA AS STRING) as LINE_HAUL_SHIP_VIA", \
    	"CAST(PLAN_D_FACILITY_ALIAS_ID AS STRING) as PLAN_D_FACILITY_ALIAS_ID", \
    	"CAST(PLAN_D_FACILITY_ID AS BIGINT) as PLAN_D_FACILITY_ID", \
    	"CAST(PLAN_LEG_D_ALIAS_ID AS STRING) as PLAN_LEG_D_ALIAS_ID", \
    	"CAST(PLAN_LEG_D_ID AS BIGINT) as PLAN_LEG_D_ID", \
    	"CAST(PLAN_LEG_O_ALIAS_ID AS STRING) as PLAN_LEG_O_ALIAS_ID", \
    	"CAST(PLAN_LEG_O_ID AS BIGINT) as PLAN_LEG_O_ID", \
    	"CAST(PLAN_O_FACILITY_ALIAS_ID AS STRING) as PLAN_O_FACILITY_ALIAS_ID", \
    	"CAST(PLAN_O_FACILITY_ID AS BIGINT) as PLAN_O_FACILITY_ID", \
    	"CAST(SPL_INSTR_CODE_1 AS STRING) as SPL_INSTR_CODE_1", \
    	"CAST(SPL_INSTR_CODE_10 AS STRING) as SPL_INSTR_CODE_10", \
    	"CAST(SPL_INSTR_CODE_2 AS STRING) as SPL_INSTR_CODE_2", \
    	"CAST(SPL_INSTR_CODE_3 AS STRING) as SPL_INSTR_CODE_3", \
    	"CAST(SPL_INSTR_CODE_4 AS STRING) as SPL_INSTR_CODE_4", \
    	"CAST(SPL_INSTR_CODE_5 AS STRING) as SPL_INSTR_CODE_5", \
    	"CAST(SPL_INSTR_CODE_6 AS STRING) as SPL_INSTR_CODE_6", \
    	"CAST(SPL_INSTR_CODE_7 AS STRING) as SPL_INSTR_CODE_7", \
    	"CAST(SPL_INSTR_CODE_8 AS STRING) as SPL_INSTR_CODE_8", \
    	"CAST(SPL_INSTR_CODE_9 AS STRING) as SPL_INSTR_CODE_9", \
    	"CAST(PRE_BILL_STATUS AS BIGINT) as PRE_BILL_STATUS", \
    	"CAST(PRTL_SHIP_CONF_FLAG AS BIGINT) as PRTL_SHIP_CONF_FLAG", \
    	"CAST(PRTL_SHIP_CONF_STATUS AS BIGINT) as PRTL_SHIP_CONF_STATUS", \
    	"CAST(PRE_BILLED_FLAG AS BIGINT) as PRE_BILLED_FLAG", \
    	"CAST(TAX_ID AS STRING) as TAX_ID", \
    	"CAST(ALLOW_PRE_BILLING AS BIGINT) as ALLOW_PRE_BILLING", \
    	"CAST(O_PHONE_NUMBER AS STRING) as O_PHONE_NUMBER", \
    	"CAST(PURCHASE_ORDER_NBR AS STRING) as PURCHASE_ORDER_NBR", \
    	"CAST(MARK_FOR AS STRING) as MARK_FOR", \
    	"CAST(DISTRO_NUMBER AS STRING) as DISTRO_NUMBER", \
    	"CAST(REF_SHIPMENT_NBR AS STRING) as REF_SHIPMENT_NBR", \
    	"CAST(REF_STOP_SEQ AS BIGINT) as REF_STOP_SEQ", \
    	"CAST(PO_TYPE_ATTR AS STRING) as PO_TYPE_ATTR", \
    	"CAST(DSG_SHIP_VIA AS STRING) as DSG_SHIP_VIA", \
    	"CAST(LOAD_TSTMP_EXP AS TIMESTAMP) as LOAD_TSTMP" \
    )
    
    gu.overwriteDeltaPartition(Shortcut_to_WM_OUTPT_ORDERS_PRE, "DC_NBR", dcnbr, target_table_name)
    logger.info("Shortcut_to_WM_OUTPT_ORDERS_PRE is written to the target table - " + target_table_name)
