#Code converted on 2023-06-26 10:20:00
import os
import argparse
from pyspark.sql import *
from pyspark.sql.functions import *
from pyspark.sql.window import Window
from pyspark.sql.types import *
from datetime import datetime
from pyspark.dbutils import DBUtils
from Datalake.utils.genericUtilities import *
from Datalake.utils.configs import *
from Datalake.utils.mergeUtils import *
from Datalake.utils.logger import *
# COMMAND ----------

parser = argparse.ArgumentParser()
spark = SparkSession.getActiveSession()
dbutils = DBUtils(spark)

parser.add_argument('env', type=str, help='Env Variable')
# args = parser.parse_args()
# env = args.env
env = 'dev'

if env is None or env == '':
    raise ValueError('env is not set')

refine = getEnvPrefix(env) + 'refine'
raw = getEnvPrefix(env) + 'raw'
legacy = getEnvPrefix(env) + 'legacy'

# Set global variables
starttime = datetime.now() #start timestamp of the script
refined_perf_table = f"{refine}.WM_LABOR_MSG"
raw_perf_table = f"{raw}.WM_LABOR_MSG_PRE"
site_profile_table = f"{legacy}.SITE_PROFILE"


# COMMAND ----------
# Processing node SQ_Shortcut_to_WM_LABOR_MSG, type SOURCE 
# COLUMN COUNT: 81

SQ_Shortcut_to_WM_LABOR_MSG = spark.sql(f"""SELECT
LOCATION_ID,
WM_LABOR_MSG_ID,
WM_TC_COMPANY_ID,
WM_WHSE,
WM_LABOR_MSG_STATUS,
WM_MSG_STAT_CD,
WM_TRAN_NBR,
WM_LOGIN_USER_ID,
WM_ACCOUNT_NAME,
WM_ORIG_ACCOUNT_NAME,
WM_DEPT,
WM_DIVISION,
WM_JOB_FUNCTION,
WM_SHIFT,
WM_WHSE_TSTMP,
WM_ORIG_EVNT_START_TSTMP,
WM_ORIG_EVNT_END_TSTMP,
WM_SCHED_START_TIME,
WM_SCHED_START_TSTMP,
WM_ACTUAL_END_TIME,
WM_ACTUAL_END_TSTMP,
WM_TASK_NBR,
WM_CASE_NBR,
WM_CARTON_NBR,
WM_WAVE_NBR,
WM_TRAN_DATA_ELS_TRAN_ID,
WM_LOCN_GRP_ATTR,
WM_VEHICLE_TYPE,
WM_ENGINE_CD,
WM_ENGINE_GROUP,
WM_TEAM_STD_GRP,
WM_REF_CD,
WM_REF_NBR,
WM_MONITOR_SMRY_ID,
HAS_MONITOR_MSG_FLAG,
RESEND_TRAN_FLAG,
REQ_SAM_REPLY_FLAG,
CONFLICT_FLAG,
PRIORITY,
WM_PLAN_ID,
WM_RESOURCE_GROUP_ID,
WM_ADJ_REASON_CD,
WM_ADJ_REF_TRAN_NBR,
WM_INV_NEED_TYPE,
WM_TRANS_TYPE,
WM_TRANS_VALUE,
WM_DISPLAY_UOM,
UOM_QTY,
THRUPUT_MIN,
TOTAL_QTY,
ORIG_COMPLETED_WORK,
COMPLETED_WORK,
USER_DEF_VAL_1,
USER_DEF_VAL_2,
MISC,
MISC_2,
MISC_TXT_1,
MISC_TXT_2,
MISC_NUM_1,
MISC_NUM_2,
EVNT_CTGRY_1,
EVNT_CTGRY_2,
EVNT_CTGRY_3,
EVNT_CTGRY_4,
EVNT_CTGRY_5,
LEVEL_1,
LEVEL_2,
LEVEL_3,
LEVEL_4,
LEVEL_5,
WM_SOURCE,
WM_MOD_USER_ID,
WM_HIBERNATE_VERSION,
WM_CREATED_SOURCE_TYPE,
WM_CREATED_SOURCE,
WM_LAST_UPDATED_SOURCE_TYPE,
WM_LAST_UPDATED_SOURCE,
WM_CREATED_TSTMP,
WM_LAST_UPDATED_DTTM,
UPDATE_TSTMP,
LOAD_TSTMP
FROM {refined_perf_table}
WHERE WM_LABOR_MSG_ID IN (SELECT LABOR_MSG_ID FROM {raw_perf_table})""").withColumn("sys_row_id", monotonically_increasing_id())

# COMMAND ----------
# Processing node SQ_Shortcut_to_SITE_PROFILE, type SOURCE 
# COLUMN COUNT: 2

SQ_Shortcut_to_SITE_PROFILE = spark.sql(f"""SELECT LOCATION_ID, STORE_NBR FROM {site_profile_table}""").withColumn("sys_row_id", monotonically_increasing_id())

# COMMAND ----------
# Processing node SQ_Shortcut_to_WM_LABOR_MSG_PRE, type SOURCE 
# COLUMN COUNT: 80

SQ_Shortcut_to_WM_LABOR_MSG_PRE = spark.sql(f"""SELECT
DC_NBR,
LABOR_MSG_ID,
STATUS,
WHSE,
TRAN_NBR,
ACT_NAME,
LOGIN_USER_ID,
SCHED_START_TIME,
SCHED_START_DATE,
VHCL_TYPE,
REF_CODE,
REF_NBR,
TC_COMPANY_ID,
DIV,
SHIFT,
USER_DEF_VAL_1,
USER_DEF_VAL_2,
MOD_USER_ID,
RESEND_TRAN,
REQ_SAM_REPLY,
PRIORITY,
ENGINE_CODE,
TEAM_STD_GRP,
MISC,
MISC_2,
CREATED_SOURCE_TYPE,
CREATED_SOURCE,
CREATED_DTTM,
LAST_UPDATED_SOURCE_TYPE,
LAST_UPDATED_SOURCE,
LAST_UPDATED_DTTM,
ACTUAL_END_TIME,
ACTUAL_END_DATE,
PLAN_ID,
WAVE_NBR,
TRANS_TYPE,
TRANS_VALUE,
ENGINE_GROUP,
COMPLETED_WORK,
WHSE_DATE,
JOB_FUNCTION,
LEVEL_1,
LEVEL_2,
LEVEL_3,
LEVEL_4,
LEVEL_5,
CARTON_NBR,
TASK_NBR,
CASE_NBR,
ORIG_COMPLETED_WORK,
TRAN_DATA_ELS_TRAN_ID,
MISC_TXT_1,
MISC_TXT_2,
MISC_NUM_1,
MISC_NUM_2,
EVNT_CTGRY_1,
EVNT_CTGRY_2,
EVNT_CTGRY_3,
EVNT_CTGRY_4,
EVNT_CTGRY_5,
HIBERNATE_VERSION,
DEPT,
MSG_STAT_CODE,
MONITOR_SMRY_ID,
ORIG_ACT_NAME,
SOURCE,
HAS_MONITOR_MSG,
TOTAL_QTY,
ORIG_EVNT_START_TIME,
ORIG_EVNT_END_TIME,
ADJ_REASON_CODE,
ADJ_REF_TRAN_NBR,
INT_TYPE,
CONFLICT,
DISPLAY_UOM,
UOM_QTY,
THRUPUT_MIN,
LOCN_GRP_ATTR,
RESOURCE_GROUP_ID,
LOAD_TSTMP
FROM {raw_perf_table}""").withColumn("sys_row_id", monotonically_increasing_id())

# COMMAND ----------
# Processing node EXP_INT_CONV, type EXPRESSION 
# COLUMN COUNT: 80

# for each involved DataFrame, append the dataframe name to each column
SQ_Shortcut_to_WM_LABOR_MSG_PRE_temp = SQ_Shortcut_to_WM_LABOR_MSG_PRE.toDF(*["SQ_Shortcut_to_WM_LABOR_MSG_PRE___" + col for col in SQ_Shortcut_to_WM_LABOR_MSG_PRE.columns])

EXP_INT_CONV = SQ_Shortcut_to_WM_LABOR_MSG_PRE_temp.selectExpr( \
	"SQ_Shortcut_to_WM_LABOR_MSG_PRE___sys_row_id as sys_row_id", \
	"cast(SQ_Shortcut_to_WM_LABOR_MSG_PRE___DC_NBR as int) as o_DC_NBR", \
	"SQ_Shortcut_to_WM_LABOR_MSG_PRE___LABOR_MSG_ID as LABOR_MSG_ID", \
	"SQ_Shortcut_to_WM_LABOR_MSG_PRE___STATUS as STATUS", \
	"SQ_Shortcut_to_WM_LABOR_MSG_PRE___WHSE as WHSE", \
	"SQ_Shortcut_to_WM_LABOR_MSG_PRE___TRAN_NBR as TRAN_NBR", \
	"SQ_Shortcut_to_WM_LABOR_MSG_PRE___ACT_NAME as ACT_NAME", \
	"SQ_Shortcut_to_WM_LABOR_MSG_PRE___LOGIN_USER_ID as LOGIN_USER_ID", \
	"SQ_Shortcut_to_WM_LABOR_MSG_PRE___SCHED_START_TIME as SCHED_START_TIME", \
	"SQ_Shortcut_to_WM_LABOR_MSG_PRE___SCHED_START_DATE as SCHED_START_DATE", \
	"SQ_Shortcut_to_WM_LABOR_MSG_PRE___VHCL_TYPE as VHCL_TYPE", \
	"SQ_Shortcut_to_WM_LABOR_MSG_PRE___REF_CODE as REF_CODE", \
	"SQ_Shortcut_to_WM_LABOR_MSG_PRE___REF_NBR as REF_NBR", \
	"SQ_Shortcut_to_WM_LABOR_MSG_PRE___TC_COMPANY_ID as TC_COMPANY_ID", \
	"SQ_Shortcut_to_WM_LABOR_MSG_PRE___DIV as DIV", \
	"SQ_Shortcut_to_WM_LABOR_MSG_PRE___SHIFT as SHIFT", \
	"SQ_Shortcut_to_WM_LABOR_MSG_PRE___USER_DEF_VAL_1 as USER_DEF_VAL_1", \
	"SQ_Shortcut_to_WM_LABOR_MSG_PRE___USER_DEF_VAL_2 as USER_DEF_VAL_2", \
	"SQ_Shortcut_to_WM_LABOR_MSG_PRE___MOD_USER_ID as MOD_USER_ID", \
	"SQ_Shortcut_to_WM_LABOR_MSG_PRE___RESEND_TRAN as RESEND_TRAN", \
	"SQ_Shortcut_to_WM_LABOR_MSG_PRE___REQ_SAM_REPLY as REQ_SAM_REPLY", \
	"SQ_Shortcut_to_WM_LABOR_MSG_PRE___PRIORITY as PRIORITY", \
	"SQ_Shortcut_to_WM_LABOR_MSG_PRE___ENGINE_CODE as ENGINE_CODE", \
	"SQ_Shortcut_to_WM_LABOR_MSG_PRE___TEAM_STD_GRP as TEAM_STD_GRP", \
	"SQ_Shortcut_to_WM_LABOR_MSG_PRE___MISC as MISC", \
	"SQ_Shortcut_to_WM_LABOR_MSG_PRE___MISC_2 as MISC_2", \
	"SQ_Shortcut_to_WM_LABOR_MSG_PRE___CREATED_SOURCE_TYPE as CREATED_SOURCE_TYPE", \
	"SQ_Shortcut_to_WM_LABOR_MSG_PRE___CREATED_SOURCE as CREATED_SOURCE", \
	"SQ_Shortcut_to_WM_LABOR_MSG_PRE___CREATED_DTTM as CREATED_DTTM", \
	"SQ_Shortcut_to_WM_LABOR_MSG_PRE___LAST_UPDATED_SOURCE_TYPE as LAST_UPDATED_SOURCE_TYPE", \
	"SQ_Shortcut_to_WM_LABOR_MSG_PRE___LAST_UPDATED_SOURCE as LAST_UPDATED_SOURCE", \
	"SQ_Shortcut_to_WM_LABOR_MSG_PRE___LAST_UPDATED_DTTM as LAST_UPDATED_DTTM", \
	"SQ_Shortcut_to_WM_LABOR_MSG_PRE___ACTUAL_END_TIME as ACTUAL_END_TIME", \
	"SQ_Shortcut_to_WM_LABOR_MSG_PRE___ACTUAL_END_DATE as ACTUAL_END_DATE", \
	"SQ_Shortcut_to_WM_LABOR_MSG_PRE___PLAN_ID as PLAN_ID", \
	"SQ_Shortcut_to_WM_LABOR_MSG_PRE___WAVE_NBR as WAVE_NBR", \
	"SQ_Shortcut_to_WM_LABOR_MSG_PRE___TRANS_TYPE as TRANS_TYPE", \
	"SQ_Shortcut_to_WM_LABOR_MSG_PRE___TRANS_VALUE as TRANS_VALUE", \
	"SQ_Shortcut_to_WM_LABOR_MSG_PRE___ENGINE_GROUP as ENGINE_GROUP", \
	"SQ_Shortcut_to_WM_LABOR_MSG_PRE___COMPLETED_WORK as COMPLETED_WORK", \
	"SQ_Shortcut_to_WM_LABOR_MSG_PRE___WHSE_DATE as WHSE_DATE", \
	"SQ_Shortcut_to_WM_LABOR_MSG_PRE___JOB_FUNCTION as JOB_FUNCTION", \
	"SQ_Shortcut_to_WM_LABOR_MSG_PRE___LEVEL_1 as LEVEL_1", \
	"SQ_Shortcut_to_WM_LABOR_MSG_PRE___LEVEL_2 as LEVEL_2", \
	"SQ_Shortcut_to_WM_LABOR_MSG_PRE___LEVEL_3 as LEVEL_3", \
	"SQ_Shortcut_to_WM_LABOR_MSG_PRE___LEVEL_4 as LEVEL_4", \
	"SQ_Shortcut_to_WM_LABOR_MSG_PRE___LEVEL_5 as LEVEL_5", \
	"SQ_Shortcut_to_WM_LABOR_MSG_PRE___CARTON_NBR as CARTON_NBR", \
	"SQ_Shortcut_to_WM_LABOR_MSG_PRE___TASK_NBR as TASK_NBR", \
	"SQ_Shortcut_to_WM_LABOR_MSG_PRE___CASE_NBR as CASE_NBR", \
	"SQ_Shortcut_to_WM_LABOR_MSG_PRE___ORIG_COMPLETED_WORK as ORIG_COMPLETED_WORK", \
	"SQ_Shortcut_to_WM_LABOR_MSG_PRE___TRAN_DATA_ELS_TRAN_ID as TRAN_DATA_ELS_TRAN_ID", \
	"SQ_Shortcut_to_WM_LABOR_MSG_PRE___MISC_TXT_1 as MISC_TXT_1", \
	"SQ_Shortcut_to_WM_LABOR_MSG_PRE___MISC_TXT_2 as MISC_TXT_2", \
	"SQ_Shortcut_to_WM_LABOR_MSG_PRE___MISC_NUM_1 as MISC_NUM_1", \
	"SQ_Shortcut_to_WM_LABOR_MSG_PRE___MISC_NUM_2 as MISC_NUM_2", \
	"SQ_Shortcut_to_WM_LABOR_MSG_PRE___EVNT_CTGRY_1 as EVNT_CTGRY_1", \
	"SQ_Shortcut_to_WM_LABOR_MSG_PRE___EVNT_CTGRY_2 as EVNT_CTGRY_2", \
	"SQ_Shortcut_to_WM_LABOR_MSG_PRE___EVNT_CTGRY_3 as EVNT_CTGRY_3", \
	"SQ_Shortcut_to_WM_LABOR_MSG_PRE___EVNT_CTGRY_4 as EVNT_CTGRY_4", \
	"SQ_Shortcut_to_WM_LABOR_MSG_PRE___EVNT_CTGRY_5 as EVNT_CTGRY_5", \
	"SQ_Shortcut_to_WM_LABOR_MSG_PRE___HIBERNATE_VERSION as HIBERNATE_VERSION", \
	"SQ_Shortcut_to_WM_LABOR_MSG_PRE___DEPT as DEPT", \
	"SQ_Shortcut_to_WM_LABOR_MSG_PRE___MSG_STAT_CODE as MSG_STAT_CODE", \
	"SQ_Shortcut_to_WM_LABOR_MSG_PRE___MONITOR_SMRY_ID as MONITOR_SMRY_ID", \
	"SQ_Shortcut_to_WM_LABOR_MSG_PRE___ORIG_ACT_NAME as ORIG_ACT_NAME", \
	"SQ_Shortcut_to_WM_LABOR_MSG_PRE___SOURCE as SOURCE", \
	"SQ_Shortcut_to_WM_LABOR_MSG_PRE___HAS_MONITOR_MSG as HAS_MONITOR_MSG", \
	"SQ_Shortcut_to_WM_LABOR_MSG_PRE___TOTAL_QTY as TOTAL_QTY", \
	"SQ_Shortcut_to_WM_LABOR_MSG_PRE___ORIG_EVNT_START_TIME as ORIG_EVNT_START_TIME", \
	"SQ_Shortcut_to_WM_LABOR_MSG_PRE___ORIG_EVNT_END_TIME as ORIG_EVNT_END_TIME", \
	"SQ_Shortcut_to_WM_LABOR_MSG_PRE___ADJ_REASON_CODE as ADJ_REASON_CODE", \
	"SQ_Shortcut_to_WM_LABOR_MSG_PRE___ADJ_REF_TRAN_NBR as ADJ_REF_TRAN_NBR", \
	"SQ_Shortcut_to_WM_LABOR_MSG_PRE___INT_TYPE as INT_TYPE", \
	"SQ_Shortcut_to_WM_LABOR_MSG_PRE___CONFLICT as CONFLICT", \
	"SQ_Shortcut_to_WM_LABOR_MSG_PRE___DISPLAY_UOM as DISPLAY_UOM", \
	"SQ_Shortcut_to_WM_LABOR_MSG_PRE___UOM_QTY as UOM_QTY", \
	"SQ_Shortcut_to_WM_LABOR_MSG_PRE___THRUPUT_MIN as THRUPUT_MIN", \
	"SQ_Shortcut_to_WM_LABOR_MSG_PRE___LOCN_GRP_ATTR as LOCN_GRP_ATTR", \
	"SQ_Shortcut_to_WM_LABOR_MSG_PRE___RESOURCE_GROUP_ID as RESOURCE_GROUP_ID", \
	"SQ_Shortcut_to_WM_LABOR_MSG_PRE___LOAD_TSTMP as LOAD_TSTMP" \
)

# COMMAND ----------
# Processing node JNR_SITE_PROFILE, type JOINER 
# COLUMN COUNT: 82

JNR_SITE_PROFILE = SQ_Shortcut_to_SITE_PROFILE.join(EXP_INT_CONV,[SQ_Shortcut_to_SITE_PROFILE.STORE_NBR == EXP_INT_CONV.o_DC_NBR],'inner')

# COMMAND ----------
# Processing node JNR_WM_LABOR_MSG, type JOINER . Note: using additional SELECT to rename incoming columns
# COLUMN COUNT: 161

# for each involved DataFrame, append the dataframe name to each column
JNR_SITE_PROFILE_temp = JNR_SITE_PROFILE.toDF(*["JNR_SITE_PROFILE___" + col for col in JNR_SITE_PROFILE.columns])
SQ_Shortcut_to_WM_LABOR_MSG_temp = SQ_Shortcut_to_WM_LABOR_MSG.toDF(*["SQ_Shortcut_to_WM_LABOR_MSG___" + col for col in SQ_Shortcut_to_WM_LABOR_MSG.columns])

JNR_WM_LABOR_MSG = SQ_Shortcut_to_WM_LABOR_MSG_temp.join(JNR_SITE_PROFILE_temp,[SQ_Shortcut_to_WM_LABOR_MSG_temp.SQ_Shortcut_to_WM_LABOR_MSG___LOCATION_ID == JNR_SITE_PROFILE_temp.JNR_SITE_PROFILE___LOCATION_ID, SQ_Shortcut_to_WM_LABOR_MSG_temp.SQ_Shortcut_to_WM_LABOR_MSG___WM_LABOR_MSG_ID == JNR_SITE_PROFILE_temp.JNR_SITE_PROFILE___LABOR_MSG_ID],'right_outer').selectExpr( \
	"JNR_SITE_PROFILE___o_DC_NBR as o_DC_NBR", \
	"JNR_SITE_PROFILE___LABOR_MSG_ID as LABOR_MSG_ID", \
	"JNR_SITE_PROFILE___STATUS as STATUS", \
	"JNR_SITE_PROFILE___WHSE as WHSE", \
	"JNR_SITE_PROFILE___TRAN_NBR as TRAN_NBR", \
	"JNR_SITE_PROFILE___ACT_NAME as ACT_NAME", \
	"JNR_SITE_PROFILE___LOGIN_USER_ID as LOGIN_USER_ID", \
	"JNR_SITE_PROFILE___SCHED_START_TIME as SCHED_START_TIME", \
	"JNR_SITE_PROFILE___SCHED_START_DATE as SCHED_START_DATE", \
	"JNR_SITE_PROFILE___VHCL_TYPE as VHCL_TYPE", \
	"JNR_SITE_PROFILE___REF_CODE as REF_CODE", \
	"JNR_SITE_PROFILE___REF_NBR as REF_NBR", \
	"JNR_SITE_PROFILE___TC_COMPANY_ID as TC_COMPANY_ID", \
	"JNR_SITE_PROFILE___DIV as DIV", \
	"JNR_SITE_PROFILE___SHIFT as SHIFT", \
	"JNR_SITE_PROFILE___USER_DEF_VAL_1 as USER_DEF_VAL_1", \
	"JNR_SITE_PROFILE___USER_DEF_VAL_2 as USER_DEF_VAL_2", \
	"JNR_SITE_PROFILE___MOD_USER_ID as MOD_USER_ID", \
	"JNR_SITE_PROFILE___RESEND_TRAN as RESEND_TRAN", \
	"JNR_SITE_PROFILE___REQ_SAM_REPLY as REQ_SAM_REPLY", \
	"JNR_SITE_PROFILE___PRIORITY as PRIORITY", \
	"JNR_SITE_PROFILE___ENGINE_CODE as ENGINE_CODE", \
	"JNR_SITE_PROFILE___TEAM_STD_GRP as TEAM_STD_GRP", \
	"JNR_SITE_PROFILE___MISC as MISC", \
	"JNR_SITE_PROFILE___MISC_2 as MISC_2", \
	"JNR_SITE_PROFILE___CREATED_SOURCE_TYPE as CREATED_SOURCE_TYPE", \
	"JNR_SITE_PROFILE___CREATED_SOURCE as CREATED_SOURCE", \
	"JNR_SITE_PROFILE___CREATED_DTTM as CREATED_DTTM", \
	"JNR_SITE_PROFILE___LAST_UPDATED_SOURCE_TYPE as LAST_UPDATED_SOURCE_TYPE", \
	"JNR_SITE_PROFILE___LAST_UPDATED_SOURCE as LAST_UPDATED_SOURCE", \
	"JNR_SITE_PROFILE___LAST_UPDATED_DTTM as LAST_UPDATED_DTTM", \
	"JNR_SITE_PROFILE___ACTUAL_END_TIME as ACTUAL_END_TIME", \
	"JNR_SITE_PROFILE___ACTUAL_END_DATE as ACTUAL_END_DATE", \
	"JNR_SITE_PROFILE___PLAN_ID as PLAN_ID", \
	"JNR_SITE_PROFILE___WAVE_NBR as WAVE_NBR", \
	"JNR_SITE_PROFILE___TRANS_TYPE as TRANS_TYPE", \
	"JNR_SITE_PROFILE___TRANS_VALUE as TRANS_VALUE", \
	"JNR_SITE_PROFILE___ENGINE_GROUP as ENGINE_GROUP", \
	"JNR_SITE_PROFILE___COMPLETED_WORK as COMPLETED_WORK", \
	"JNR_SITE_PROFILE___WHSE_DATE as WHSE_DATE", \
	"JNR_SITE_PROFILE___JOB_FUNCTION as JOB_FUNCTION", \
	"JNR_SITE_PROFILE___LEVEL_1 as LEVEL_1", \
	"JNR_SITE_PROFILE___LEVEL_2 as LEVEL_2", \
	"JNR_SITE_PROFILE___LEVEL_3 as LEVEL_3", \
	"JNR_SITE_PROFILE___LEVEL_4 as LEVEL_4", \
	"JNR_SITE_PROFILE___LEVEL_5 as LEVEL_5", \
	"JNR_SITE_PROFILE___CARTON_NBR as CARTON_NBR", \
	"JNR_SITE_PROFILE___TASK_NBR as TASK_NBR", \
	"JNR_SITE_PROFILE___CASE_NBR as CASE_NBR", \
	"JNR_SITE_PROFILE___ORIG_COMPLETED_WORK as ORIG_COMPLETED_WORK", \
	"JNR_SITE_PROFILE___TRAN_DATA_ELS_TRAN_ID as TRAN_DATA_ELS_TRAN_ID", \
	"JNR_SITE_PROFILE___MISC_TXT_1 as MISC_TXT_1", \
	"JNR_SITE_PROFILE___MISC_TXT_2 as MISC_TXT_2", \
	"JNR_SITE_PROFILE___MISC_NUM_1 as MISC_NUM_1", \
	"JNR_SITE_PROFILE___MISC_NUM_2 as MISC_NUM_2", \
	"JNR_SITE_PROFILE___EVNT_CTGRY_1 as EVNT_CTGRY_1", \
	"JNR_SITE_PROFILE___EVNT_CTGRY_2 as EVNT_CTGRY_2", \
	"JNR_SITE_PROFILE___EVNT_CTGRY_3 as EVNT_CTGRY_3", \
	"JNR_SITE_PROFILE___EVNT_CTGRY_4 as EVNT_CTGRY_4", \
	"JNR_SITE_PROFILE___EVNT_CTGRY_5 as EVNT_CTGRY_5", \
	"JNR_SITE_PROFILE___HIBERNATE_VERSION as HIBERNATE_VERSION", \
	"JNR_SITE_PROFILE___DEPT as DEPT", \
	"JNR_SITE_PROFILE___MSG_STAT_CODE as MSG_STAT_CODE", \
	"JNR_SITE_PROFILE___MONITOR_SMRY_ID as MONITOR_SMRY_ID", \
	"JNR_SITE_PROFILE___ORIG_ACT_NAME as ORIG_ACT_NAME", \
	"JNR_SITE_PROFILE___SOURCE as SOURCE", \
	"JNR_SITE_PROFILE___HAS_MONITOR_MSG as HAS_MONITOR_MSG", \
	"JNR_SITE_PROFILE___TOTAL_QTY as TOTAL_QTY", \
	"JNR_SITE_PROFILE___ORIG_EVNT_START_TIME as ORIG_EVNT_START_TIME", \
	"JNR_SITE_PROFILE___ORIG_EVNT_END_TIME as ORIG_EVNT_END_TIME", \
	"JNR_SITE_PROFILE___ADJ_REASON_CODE as ADJ_REASON_CODE", \
	"JNR_SITE_PROFILE___ADJ_REF_TRAN_NBR as ADJ_REF_TRAN_NBR", \
	"JNR_SITE_PROFILE___INT_TYPE as INT_TYPE", \
	"JNR_SITE_PROFILE___CONFLICT as CONFLICT", \
	"JNR_SITE_PROFILE___DISPLAY_UOM as DISPLAY_UOM", \
	"JNR_SITE_PROFILE___UOM_QTY as UOM_QTY", \
	"JNR_SITE_PROFILE___THRUPUT_MIN as THRUPUT_MIN", \
	"JNR_SITE_PROFILE___LOCN_GRP_ATTR as LOCN_GRP_ATTR", \
	"JNR_SITE_PROFILE___RESOURCE_GROUP_ID as RESOURCE_GROUP_ID", \
	"JNR_SITE_PROFILE___LOCATION_ID as LOCATION_ID", \
	"SQ_Shortcut_to_WM_LABOR_MSG___LOCATION_ID as in_WM_LOCATION_ID", \
	"SQ_Shortcut_to_WM_LABOR_MSG___WM_LABOR_MSG_ID as WM_LABOR_MSG_ID", \
	"SQ_Shortcut_to_WM_LABOR_MSG___WM_TC_COMPANY_ID as WM_TC_COMPANY_ID", \
	"SQ_Shortcut_to_WM_LABOR_MSG___WM_WHSE as WM_WHSE", \
	"SQ_Shortcut_to_WM_LABOR_MSG___WM_LABOR_MSG_STATUS as WM_LABOR_MSG_STATUS", \
	"SQ_Shortcut_to_WM_LABOR_MSG___WM_MSG_STAT_CD as WM_MSG_STAT_CD", \
	"SQ_Shortcut_to_WM_LABOR_MSG___WM_TRAN_NBR as WM_TRAN_NBR", \
	"SQ_Shortcut_to_WM_LABOR_MSG___WM_LOGIN_USER_ID as WM_LOGIN_USER_ID", \
	"SQ_Shortcut_to_WM_LABOR_MSG___WM_ACCOUNT_NAME as WM_ACCOUNT_NAME", \
	"SQ_Shortcut_to_WM_LABOR_MSG___WM_ORIG_ACCOUNT_NAME as WM_ORIG_ACCOUNT_NAME", \
	"SQ_Shortcut_to_WM_LABOR_MSG___WM_DEPT as WM_DEPT", \
	"SQ_Shortcut_to_WM_LABOR_MSG___WM_DIVISION as WM_DIVISION", \
	"SQ_Shortcut_to_WM_LABOR_MSG___WM_JOB_FUNCTION as WM_JOB_FUNCTION", \
	"SQ_Shortcut_to_WM_LABOR_MSG___WM_SHIFT as WM_SHIFT", \
	"SQ_Shortcut_to_WM_LABOR_MSG___WM_WHSE_TSTMP as WM_WHSE_TSTMP", \
	"SQ_Shortcut_to_WM_LABOR_MSG___WM_ORIG_EVNT_START_TSTMP as WM_ORIG_EVNT_START_TSTMP", \
	"SQ_Shortcut_to_WM_LABOR_MSG___WM_ORIG_EVNT_END_TSTMP as WM_ORIG_EVNT_END_TSTMP", \
	"SQ_Shortcut_to_WM_LABOR_MSG___WM_SCHED_START_TIME as WM_SCHED_START_TIME", \
	"SQ_Shortcut_to_WM_LABOR_MSG___WM_SCHED_START_TSTMP as WM_SCHED_START_TSTMP", \
	"SQ_Shortcut_to_WM_LABOR_MSG___WM_ACTUAL_END_TIME as WM_ACTUAL_END_TIME", \
	"SQ_Shortcut_to_WM_LABOR_MSG___WM_ACTUAL_END_TSTMP as WM_ACTUAL_END_TSTMP", \
	"SQ_Shortcut_to_WM_LABOR_MSG___WM_TASK_NBR as WM_TASK_NBR", \
	"SQ_Shortcut_to_WM_LABOR_MSG___WM_CASE_NBR as WM_CASE_NBR", \
	"SQ_Shortcut_to_WM_LABOR_MSG___WM_CARTON_NBR as WM_CARTON_NBR", \
	"SQ_Shortcut_to_WM_LABOR_MSG___WM_WAVE_NBR as WM_WAVE_NBR", \
	"SQ_Shortcut_to_WM_LABOR_MSG___WM_TRAN_DATA_ELS_TRAN_ID as WM_TRAN_DATA_ELS_TRAN_ID", \
	"SQ_Shortcut_to_WM_LABOR_MSG___WM_LOCN_GRP_ATTR as WM_LOCN_GRP_ATTR", \
	"SQ_Shortcut_to_WM_LABOR_MSG___WM_VEHICLE_TYPE as WM_VEHICLE_TYPE", \
	"SQ_Shortcut_to_WM_LABOR_MSG___WM_ENGINE_CD as WM_ENGINE_CD", \
	"SQ_Shortcut_to_WM_LABOR_MSG___WM_ENGINE_GROUP as WM_ENGINE_GROUP", \
	"SQ_Shortcut_to_WM_LABOR_MSG___WM_TEAM_STD_GRP as WM_TEAM_STD_GRP", \
	"SQ_Shortcut_to_WM_LABOR_MSG___WM_REF_CD as WM_REF_CD", \
	"SQ_Shortcut_to_WM_LABOR_MSG___WM_REF_NBR as WM_REF_NBR", \
	"SQ_Shortcut_to_WM_LABOR_MSG___WM_MONITOR_SMRY_ID as WM_MONITOR_SMRY_ID", \
	"SQ_Shortcut_to_WM_LABOR_MSG___HAS_MONITOR_MSG_FLAG as HAS_MONITOR_MSG_FLAG", \
	"SQ_Shortcut_to_WM_LABOR_MSG___RESEND_TRAN_FLAG as RESEND_TRAN_FLAG", \
	"SQ_Shortcut_to_WM_LABOR_MSG___REQ_SAM_REPLY_FLAG as REQ_SAM_REPLY_FLAG", \
	"SQ_Shortcut_to_WM_LABOR_MSG___CONFLICT_FLAG as CONFLICT_FLAG", \
	"SQ_Shortcut_to_WM_LABOR_MSG___PRIORITY as PRIORITY1", \
	"SQ_Shortcut_to_WM_LABOR_MSG___WM_PLAN_ID as WM_PLAN_ID", \
	"SQ_Shortcut_to_WM_LABOR_MSG___WM_RESOURCE_GROUP_ID as WM_RESOURCE_GROUP_ID", \
	"SQ_Shortcut_to_WM_LABOR_MSG___WM_ADJ_REASON_CD as WM_ADJ_REASON_CD", \
	"SQ_Shortcut_to_WM_LABOR_MSG___WM_ADJ_REF_TRAN_NBR as WM_ADJ_REF_TRAN_NBR", \
	"SQ_Shortcut_to_WM_LABOR_MSG___WM_INV_NEED_TYPE as WM_INV_NEED_TYPE", \
	"SQ_Shortcut_to_WM_LABOR_MSG___WM_TRANS_TYPE as WM_TRANS_TYPE", \
	"SQ_Shortcut_to_WM_LABOR_MSG___WM_TRANS_VALUE as WM_TRANS_VALUE", \
	"SQ_Shortcut_to_WM_LABOR_MSG___WM_DISPLAY_UOM as WM_DISPLAY_UOM", \
	"SQ_Shortcut_to_WM_LABOR_MSG___UOM_QTY as in_WM_UOM_QTY", \
	"SQ_Shortcut_to_WM_LABOR_MSG___THRUPUT_MIN as in_WM_THRUPUT_MIN", \
	"SQ_Shortcut_to_WM_LABOR_MSG___TOTAL_QTY as TOTAL_QTY1", \
	"SQ_Shortcut_to_WM_LABOR_MSG___ORIG_COMPLETED_WORK as in_WM_ORIG_COMPLETED_WORK", \
	"SQ_Shortcut_to_WM_LABOR_MSG___COMPLETED_WORK as in_WM_COMPLETED_WORK", \
	"SQ_Shortcut_to_WM_LABOR_MSG___USER_DEF_VAL_1 as in_WM_USER_DEF_VAL_1", \
	"SQ_Shortcut_to_WM_LABOR_MSG___USER_DEF_VAL_2 as in_WM_USER_DEF_VAL_2", \
	"SQ_Shortcut_to_WM_LABOR_MSG___MISC as in_WM_MISC", \
	"SQ_Shortcut_to_WM_LABOR_MSG___MISC_2 as in_WM_MISC_2", \
	"SQ_Shortcut_to_WM_LABOR_MSG___MISC_TXT_1 as in_WM_MISC_TXT_1", \
	"SQ_Shortcut_to_WM_LABOR_MSG___MISC_TXT_2 as in_WM_MISC_TXT_2", \
	"SQ_Shortcut_to_WM_LABOR_MSG___MISC_NUM_1 as in_WM_MISC_NUM_1", \
	"SQ_Shortcut_to_WM_LABOR_MSG___MISC_NUM_2 as in_WM_MISC_NUM_2", \
	"SQ_Shortcut_to_WM_LABOR_MSG___EVNT_CTGRY_1 as in_WM_EVNT_CTGRY_1", \
	"SQ_Shortcut_to_WM_LABOR_MSG___EVNT_CTGRY_2 as in_WM_EVNT_CTGRY_2", \
	"SQ_Shortcut_to_WM_LABOR_MSG___EVNT_CTGRY_3 as in_WM_EVNT_CTGRY_3", \
	"SQ_Shortcut_to_WM_LABOR_MSG___EVNT_CTGRY_4 as in_WM_EVNT_CTGRY_4", \
	"SQ_Shortcut_to_WM_LABOR_MSG___EVNT_CTGRY_5 as in_WM_EVNT_CTGRY_5", \
	"SQ_Shortcut_to_WM_LABOR_MSG___LEVEL_1 as in_WM_LEVEL_1", \
	"SQ_Shortcut_to_WM_LABOR_MSG___LEVEL_2 as in_WM_LEVEL_2", \
	"SQ_Shortcut_to_WM_LABOR_MSG___LEVEL_3 as in_WM_LEVEL_3", \
	"SQ_Shortcut_to_WM_LABOR_MSG___LEVEL_4 as in_WM_LEVEL_4", \
	"SQ_Shortcut_to_WM_LABOR_MSG___LEVEL_5 as in_WM_LEVEL_5", \
	"SQ_Shortcut_to_WM_LABOR_MSG___WM_SOURCE as WM_SOURCE", \
	"SQ_Shortcut_to_WM_LABOR_MSG___WM_MOD_USER_ID as WM_MOD_USER_ID", \
	"SQ_Shortcut_to_WM_LABOR_MSG___WM_HIBERNATE_VERSION as WM_HIBERNATE_VERSION", \
	"SQ_Shortcut_to_WM_LABOR_MSG___WM_CREATED_SOURCE_TYPE as WM_CREATED_SOURCE_TYPE", \
	"SQ_Shortcut_to_WM_LABOR_MSG___WM_CREATED_SOURCE as WM_CREATED_SOURCE", \
	"SQ_Shortcut_to_WM_LABOR_MSG___WM_LAST_UPDATED_SOURCE_TYPE as WM_LAST_UPDATED_SOURCE_TYPE", \
	"SQ_Shortcut_to_WM_LABOR_MSG___WM_LAST_UPDATED_SOURCE as WM_LAST_UPDATED_SOURCE", \
	"SQ_Shortcut_to_WM_LABOR_MSG___WM_CREATED_TSTMP as WM_CREATED_TSTMP", \
	"SQ_Shortcut_to_WM_LABOR_MSG___WM_LAST_UPDATED_DTTM as WM_LAST_UPDATED_DTTM", \
	"SQ_Shortcut_to_WM_LABOR_MSG___UPDATE_TSTMP as in_WM_UPDATE_TSTMP", \
	"SQ_Shortcut_to_WM_LABOR_MSG___LOAD_TSTMP as in_WM_LOAD_TSTMP")

# COMMAND ----------
# Processing node FIL_NO_CHANGE_REC, type FILTER 
# COLUMN COUNT: 161

# for each involved DataFrame, append the dataframe name to each column
JNR_WM_LABOR_MSG_temp = JNR_WM_LABOR_MSG.toDF(*["JNR_WM_LABOR_MSG___" + col for col in JNR_WM_LABOR_MSG.columns])

FIL_NO_CHANGE_REC = JNR_WM_LABOR_MSG_temp.selectExpr( \
	"JNR_WM_LABOR_MSG___o_DC_NBR as o_DC_NBR", \
	"JNR_WM_LABOR_MSG___LABOR_MSG_ID as LABOR_MSG_ID", \
	"JNR_WM_LABOR_MSG___STATUS as STATUS", \
	"JNR_WM_LABOR_MSG___WHSE as WHSE", \
	"JNR_WM_LABOR_MSG___TRAN_NBR as TRAN_NBR", \
	"JNR_WM_LABOR_MSG___ACT_NAME as ACT_NAME", \
	"JNR_WM_LABOR_MSG___LOGIN_USER_ID as LOGIN_USER_ID", \
	"JNR_WM_LABOR_MSG___SCHED_START_TIME as SCHED_START_TIME", \
	"JNR_WM_LABOR_MSG___SCHED_START_DATE as SCHED_START_DATE", \
	"JNR_WM_LABOR_MSG___VHCL_TYPE as VHCL_TYPE", \
	"JNR_WM_LABOR_MSG___REF_CODE as REF_CODE", \
	"JNR_WM_LABOR_MSG___REF_NBR as REF_NBR", \
	"JNR_WM_LABOR_MSG___TC_COMPANY_ID as TC_COMPANY_ID", \
	"JNR_WM_LABOR_MSG___DIV as DIV", \
	"JNR_WM_LABOR_MSG___SHIFT as SHIFT", \
	"JNR_WM_LABOR_MSG___USER_DEF_VAL_1 as USER_DEF_VAL_1", \
	"JNR_WM_LABOR_MSG___USER_DEF_VAL_2 as USER_DEF_VAL_2", \
	"JNR_WM_LABOR_MSG___MOD_USER_ID as MOD_USER_ID", \
	"JNR_WM_LABOR_MSG___RESEND_TRAN as RESEND_TRAN", \
	"JNR_WM_LABOR_MSG___REQ_SAM_REPLY as REQ_SAM_REPLY", \
	"JNR_WM_LABOR_MSG___PRIORITY as PRIORITY", \
	"JNR_WM_LABOR_MSG___ENGINE_CODE as ENGINE_CODE", \
	"JNR_WM_LABOR_MSG___TEAM_STD_GRP as TEAM_STD_GRP", \
	"JNR_WM_LABOR_MSG___MISC as MISC", \
	"JNR_WM_LABOR_MSG___MISC_2 as MISC_2", \
	"JNR_WM_LABOR_MSG___CREATED_SOURCE_TYPE as CREATED_SOURCE_TYPE", \
	"JNR_WM_LABOR_MSG___CREATED_SOURCE as CREATED_SOURCE", \
	"JNR_WM_LABOR_MSG___CREATED_DTTM as CREATED_DTTM", \
	"JNR_WM_LABOR_MSG___LAST_UPDATED_SOURCE_TYPE as LAST_UPDATED_SOURCE_TYPE", \
	"JNR_WM_LABOR_MSG___LAST_UPDATED_SOURCE as LAST_UPDATED_SOURCE", \
	"JNR_WM_LABOR_MSG___LAST_UPDATED_DTTM as LAST_UPDATED_DTTM", \
	"JNR_WM_LABOR_MSG___ACTUAL_END_TIME as ACTUAL_END_TIME", \
	"JNR_WM_LABOR_MSG___ACTUAL_END_DATE as ACTUAL_END_DATE", \
	"JNR_WM_LABOR_MSG___PLAN_ID as PLAN_ID", \
	"JNR_WM_LABOR_MSG___WAVE_NBR as WAVE_NBR", \
	"JNR_WM_LABOR_MSG___TRANS_TYPE as TRANS_TYPE", \
	"JNR_WM_LABOR_MSG___TRANS_VALUE as TRANS_VALUE", \
	"JNR_WM_LABOR_MSG___ENGINE_GROUP as ENGINE_GROUP", \
	"JNR_WM_LABOR_MSG___COMPLETED_WORK as COMPLETED_WORK", \
	"JNR_WM_LABOR_MSG___WHSE_DATE as WHSE_DATE", \
	"JNR_WM_LABOR_MSG___JOB_FUNCTION as JOB_FUNCTION", \
	"JNR_WM_LABOR_MSG___LEVEL_1 as LEVEL_1", \
	"JNR_WM_LABOR_MSG___LEVEL_2 as LEVEL_2", \
	"JNR_WM_LABOR_MSG___LEVEL_3 as LEVEL_3", \
	"JNR_WM_LABOR_MSG___LEVEL_4 as LEVEL_4", \
	"JNR_WM_LABOR_MSG___LEVEL_5 as LEVEL_5", \
	"JNR_WM_LABOR_MSG___CARTON_NBR as CARTON_NBR", \
	"JNR_WM_LABOR_MSG___TASK_NBR as TASK_NBR", \
	"JNR_WM_LABOR_MSG___CASE_NBR as CASE_NBR", \
	"JNR_WM_LABOR_MSG___ORIG_COMPLETED_WORK as ORIG_COMPLETED_WORK", \
	"JNR_WM_LABOR_MSG___TRAN_DATA_ELS_TRAN_ID as TRAN_DATA_ELS_TRAN_ID", \
	"JNR_WM_LABOR_MSG___MISC_TXT_1 as MISC_TXT_1", \
	"JNR_WM_LABOR_MSG___MISC_TXT_2 as MISC_TXT_2", \
	"JNR_WM_LABOR_MSG___MISC_NUM_1 as MISC_NUM_1", \
	"JNR_WM_LABOR_MSG___MISC_NUM_2 as MISC_NUM_2", \
	"JNR_WM_LABOR_MSG___EVNT_CTGRY_1 as EVNT_CTGRY_1", \
	"JNR_WM_LABOR_MSG___EVNT_CTGRY_2 as EVNT_CTGRY_2", \
	"JNR_WM_LABOR_MSG___EVNT_CTGRY_3 as EVNT_CTGRY_3", \
	"JNR_WM_LABOR_MSG___EVNT_CTGRY_4 as EVNT_CTGRY_4", \
	"JNR_WM_LABOR_MSG___EVNT_CTGRY_5 as EVNT_CTGRY_5", \
	"JNR_WM_LABOR_MSG___HIBERNATE_VERSION as HIBERNATE_VERSION", \
	"JNR_WM_LABOR_MSG___DEPT as DEPT", \
	"JNR_WM_LABOR_MSG___MSG_STAT_CODE as MSG_STAT_CODE", \
	"JNR_WM_LABOR_MSG___MONITOR_SMRY_ID as MONITOR_SMRY_ID", \
	"JNR_WM_LABOR_MSG___ORIG_ACT_NAME as ORIG_ACT_NAME", \
	"JNR_WM_LABOR_MSG___SOURCE as SOURCE", \
	"JNR_WM_LABOR_MSG___HAS_MONITOR_MSG as HAS_MONITOR_MSG", \
	"JNR_WM_LABOR_MSG___TOTAL_QTY as TOTAL_QTY", \
	"JNR_WM_LABOR_MSG___ORIG_EVNT_START_TIME as ORIG_EVNT_START_TIME", \
	"JNR_WM_LABOR_MSG___ORIG_EVNT_END_TIME as ORIG_EVNT_END_TIME", \
	"JNR_WM_LABOR_MSG___ADJ_REASON_CODE as ADJ_REASON_CODE", \
	"JNR_WM_LABOR_MSG___ADJ_REF_TRAN_NBR as ADJ_REF_TRAN_NBR", \
	"JNR_WM_LABOR_MSG___INT_TYPE as INT_TYPE", \
	"JNR_WM_LABOR_MSG___CONFLICT as CONFLICT", \
	"JNR_WM_LABOR_MSG___DISPLAY_UOM as DISPLAY_UOM", \
	"JNR_WM_LABOR_MSG___UOM_QTY as UOM_QTY", \
	"JNR_WM_LABOR_MSG___THRUPUT_MIN as THRUPUT_MIN", \
	"JNR_WM_LABOR_MSG___LOCN_GRP_ATTR as LOCN_GRP_ATTR", \
	"JNR_WM_LABOR_MSG___RESOURCE_GROUP_ID as RESOURCE_GROUP_ID", \
	"JNR_WM_LABOR_MSG___LOCATION_ID as LOCATION_ID", \
	"JNR_WM_LABOR_MSG___in_WM_LOCATION_ID as in_WM_LOCATION_ID", \
	"JNR_WM_LABOR_MSG___WM_LABOR_MSG_ID as WM_LABOR_MSG_ID", \
	"JNR_WM_LABOR_MSG___WM_TC_COMPANY_ID as WM_TC_COMPANY_ID", \
	"JNR_WM_LABOR_MSG___WM_WHSE as WM_WHSE", \
	"JNR_WM_LABOR_MSG___WM_LABOR_MSG_STATUS as WM_LABOR_MSG_STATUS", \
	"JNR_WM_LABOR_MSG___WM_MSG_STAT_CD as WM_MSG_STAT_CD", \
	"JNR_WM_LABOR_MSG___WM_TRAN_NBR as WM_TRAN_NBR", \
	"JNR_WM_LABOR_MSG___WM_LOGIN_USER_ID as WM_LOGIN_USER_ID", \
	"JNR_WM_LABOR_MSG___WM_ACCOUNT_NAME as WM_ACCOUNT_NAME", \
	"JNR_WM_LABOR_MSG___WM_ORIG_ACCOUNT_NAME as WM_ORIG_ACCOUNT_NAME", \
	"JNR_WM_LABOR_MSG___WM_DEPT as WM_DEPT", \
	"JNR_WM_LABOR_MSG___WM_DIVISION as WM_DIVISION", \
	"JNR_WM_LABOR_MSG___WM_JOB_FUNCTION as WM_JOB_FUNCTION", \
	"JNR_WM_LABOR_MSG___WM_SHIFT as WM_SHIFT", \
	"JNR_WM_LABOR_MSG___WM_WHSE_TSTMP as WM_WHSE_TSTMP", \
	"JNR_WM_LABOR_MSG___WM_ORIG_EVNT_START_TSTMP as WM_ORIG_EVNT_START_TSTMP", \
	"JNR_WM_LABOR_MSG___WM_ORIG_EVNT_END_TSTMP as WM_ORIG_EVNT_END_TSTMP", \
	"JNR_WM_LABOR_MSG___WM_SCHED_START_TIME as WM_SCHED_START_TIME", \
	"JNR_WM_LABOR_MSG___WM_SCHED_START_TSTMP as WM_SCHED_START_TSTMP", \
	"JNR_WM_LABOR_MSG___WM_ACTUAL_END_TIME as WM_ACTUAL_END_TIME", \
	"JNR_WM_LABOR_MSG___WM_ACTUAL_END_TSTMP as WM_ACTUAL_END_TSTMP", \
	"JNR_WM_LABOR_MSG___WM_TASK_NBR as WM_TASK_NBR", \
	"JNR_WM_LABOR_MSG___WM_CASE_NBR as WM_CASE_NBR", \
	"JNR_WM_LABOR_MSG___WM_CARTON_NBR as WM_CARTON_NBR", \
	"JNR_WM_LABOR_MSG___WM_WAVE_NBR as WM_WAVE_NBR", \
	"JNR_WM_LABOR_MSG___WM_TRAN_DATA_ELS_TRAN_ID as WM_TRAN_DATA_ELS_TRAN_ID", \
	"JNR_WM_LABOR_MSG___WM_LOCN_GRP_ATTR as WM_LOCN_GRP_ATTR", \
	"JNR_WM_LABOR_MSG___WM_VEHICLE_TYPE as WM_VEHICLE_TYPE", \
	"JNR_WM_LABOR_MSG___WM_ENGINE_CD as WM_ENGINE_CD", \
	"JNR_WM_LABOR_MSG___WM_ENGINE_GROUP as WM_ENGINE_GROUP", \
	"JNR_WM_LABOR_MSG___WM_TEAM_STD_GRP as WM_TEAM_STD_GRP", \
	"JNR_WM_LABOR_MSG___WM_REF_CD as WM_REF_CD", \
	"JNR_WM_LABOR_MSG___WM_REF_NBR as WM_REF_NBR", \
	"JNR_WM_LABOR_MSG___WM_MONITOR_SMRY_ID as WM_MONITOR_SMRY_ID", \
	"JNR_WM_LABOR_MSG___HAS_MONITOR_MSG_FLAG as HAS_MONITOR_MSG_FLAG", \
	"JNR_WM_LABOR_MSG___RESEND_TRAN_FLAG as RESEND_TRAN_FLAG", \
	"JNR_WM_LABOR_MSG___REQ_SAM_REPLY_FLAG as REQ_SAM_REPLY_FLAG", \
	"JNR_WM_LABOR_MSG___CONFLICT_FLAG as CONFLICT_FLAG", \
	"JNR_WM_LABOR_MSG___PRIORITY1 as PRIORITY1", \
	"JNR_WM_LABOR_MSG___WM_PLAN_ID as WM_PLAN_ID", \
	"JNR_WM_LABOR_MSG___WM_RESOURCE_GROUP_ID as WM_RESOURCE_GROUP_ID", \
	"JNR_WM_LABOR_MSG___WM_ADJ_REASON_CD as WM_ADJ_REASON_CD", \
	"JNR_WM_LABOR_MSG___WM_ADJ_REF_TRAN_NBR as WM_ADJ_REF_TRAN_NBR", \
	"JNR_WM_LABOR_MSG___WM_INV_NEED_TYPE as WM_INV_NEED_TYPE", \
	"JNR_WM_LABOR_MSG___WM_TRANS_TYPE as WM_TRANS_TYPE", \
	"JNR_WM_LABOR_MSG___WM_TRANS_VALUE as WM_TRANS_VALUE", \
	"JNR_WM_LABOR_MSG___WM_DISPLAY_UOM as WM_DISPLAY_UOM", \
	"JNR_WM_LABOR_MSG___in_WM_UOM_QTY as in_WM_UOM_QTY", \
	"JNR_WM_LABOR_MSG___in_WM_THRUPUT_MIN as in_WM_THRUPUT_MIN", \
	"JNR_WM_LABOR_MSG___TOTAL_QTY1 as TOTAL_QTY1", \
	"JNR_WM_LABOR_MSG___in_WM_ORIG_COMPLETED_WORK as in_WM_ORIG_COMPLETED_WORK", \
	"JNR_WM_LABOR_MSG___in_WM_COMPLETED_WORK as in_WM_COMPLETED_WORK", \
	"JNR_WM_LABOR_MSG___in_WM_USER_DEF_VAL_1 as in_WM_USER_DEF_VAL_1", \
	"JNR_WM_LABOR_MSG___in_WM_USER_DEF_VAL_2 as in_WM_USER_DEF_VAL_2", \
	"JNR_WM_LABOR_MSG___in_WM_MISC as in_WM_MISC", \
	"JNR_WM_LABOR_MSG___in_WM_MISC_2 as in_WM_MISC_2", \
	"JNR_WM_LABOR_MSG___in_WM_MISC_TXT_1 as in_WM_MISC_TXT_1", \
	"JNR_WM_LABOR_MSG___in_WM_MISC_TXT_2 as in_WM_MISC_TXT_2", \
	"JNR_WM_LABOR_MSG___in_WM_MISC_NUM_1 as in_WM_MISC_NUM_1", \
	"JNR_WM_LABOR_MSG___in_WM_MISC_NUM_2 as in_WM_MISC_NUM_2", \
	"JNR_WM_LABOR_MSG___in_WM_EVNT_CTGRY_1 as in_WM_EVNT_CTGRY_1", \
	"JNR_WM_LABOR_MSG___in_WM_EVNT_CTGRY_2 as in_WM_EVNT_CTGRY_2", \
	"JNR_WM_LABOR_MSG___in_WM_EVNT_CTGRY_3 as in_WM_EVNT_CTGRY_3", \
	"JNR_WM_LABOR_MSG___in_WM_EVNT_CTGRY_4 as in_WM_EVNT_CTGRY_4", \
	"JNR_WM_LABOR_MSG___in_WM_EVNT_CTGRY_5 as in_WM_EVNT_CTGRY_5", \
	"JNR_WM_LABOR_MSG___in_WM_LEVEL_1 as in_WM_LEVEL_1", \
	"JNR_WM_LABOR_MSG___in_WM_LEVEL_2 as in_WM_LEVEL_2", \
	"JNR_WM_LABOR_MSG___in_WM_LEVEL_3 as in_WM_LEVEL_3", \
	"JNR_WM_LABOR_MSG___in_WM_LEVEL_4 as in_WM_LEVEL_4", \
	"JNR_WM_LABOR_MSG___in_WM_LEVEL_5 as in_WM_LEVEL_5", \
	"JNR_WM_LABOR_MSG___WM_SOURCE as WM_SOURCE", \
	"JNR_WM_LABOR_MSG___WM_MOD_USER_ID as WM_MOD_USER_ID", \
	"JNR_WM_LABOR_MSG___WM_HIBERNATE_VERSION as WM_HIBERNATE_VERSION", \
	"JNR_WM_LABOR_MSG___WM_CREATED_SOURCE_TYPE as WM_CREATED_SOURCE_TYPE", \
	"JNR_WM_LABOR_MSG___WM_CREATED_SOURCE as WM_CREATED_SOURCE", \
	"JNR_WM_LABOR_MSG___WM_LAST_UPDATED_SOURCE_TYPE as WM_LAST_UPDATED_SOURCE_TYPE", \
	"JNR_WM_LABOR_MSG___WM_LAST_UPDATED_SOURCE as WM_LAST_UPDATED_SOURCE", \
	"JNR_WM_LABOR_MSG___WM_CREATED_TSTMP as WM_CREATED_TSTMP", \
	"JNR_WM_LABOR_MSG___WM_LAST_UPDATED_DTTM as WM_LAST_UPDATED_DTTM", \
	"JNR_WM_LABOR_MSG___in_WM_UPDATE_TSTMP as in_WM_UPDATE_TSTMP", \
	"JNR_WM_LABOR_MSG___in_WM_LOAD_TSTMP as in_WM_LOAD_TSTMP") \
    .filter("WM_LABOR_MSG_ID is Null OR (  WM_LABOR_MSG_ID is NOT Null ) AND ( COALESCE(CREATED_DTTM, date'1900-01-01') != COALESCE(WM_CREATED_TSTMP, date'1900-01-01') OR COALESCE(LAST_UPDATED_DTTM, date'1900-01-01') != COALESCE(WM_LAST_UPDATED_TSTMP, date'1900-01-01')))").withColumn("sys_row_id", monotonically_increasing_id())

# COMMAND ----------
# Processing node EXP_EVAL_VALUES, type EXPRESSION 
# COLUMN COUNT: 163

# for each involved DataFrame, append the dataframe name to each column
FIL_NO_CHANGE_REC_temp = FIL_NO_CHANGE_REC.toDF(*["FIL_NO_CHANGE_REC___" + col for col in FIL_NO_CHANGE_REC.columns])

EXP_EVAL_VALUES = FIL_NO_CHANGE_REC_temp.selectExpr( \
	"FIL_NO_CHANGE_REC___sys_row_id as sys_row_id", \
	"FIL_NO_CHANGE_REC___o_DC_NBR as o_DC_NBR", \
	"FIL_NO_CHANGE_REC___LABOR_MSG_ID as LABOR_MSG_ID", \
	"FIL_NO_CHANGE_REC___STATUS as STATUS", \
	"FIL_NO_CHANGE_REC___WHSE as WHSE", \
	"FIL_NO_CHANGE_REC___TRAN_NBR as TRAN_NBR", \
	"FIL_NO_CHANGE_REC___ACT_NAME as ACT_NAME", \
	"FIL_NO_CHANGE_REC___LOGIN_USER_ID as LOGIN_USER_ID", \
	"FIL_NO_CHANGE_REC___SCHED_START_TIME as SCHED_START_TIME", \
	"FIL_NO_CHANGE_REC___SCHED_START_DATE as SCHED_START_DATE", \
	"FIL_NO_CHANGE_REC___VHCL_TYPE as VHCL_TYPE", \
	"FIL_NO_CHANGE_REC___REF_CODE as REF_CODE", \
	"FIL_NO_CHANGE_REC___REF_NBR as REF_NBR", \
	"FIL_NO_CHANGE_REC___TC_COMPANY_ID as TC_COMPANY_ID", \
	"FIL_NO_CHANGE_REC___DIV as DIV", \
	"FIL_NO_CHANGE_REC___SHIFT as SHIFT", \
	"FIL_NO_CHANGE_REC___USER_DEF_VAL_1 as USER_DEF_VAL_1", \
	"FIL_NO_CHANGE_REC___USER_DEF_VAL_2 as USER_DEF_VAL_2", \
	"FIL_NO_CHANGE_REC___MOD_USER_ID as MOD_USER_ID", \
	"FIL_NO_CHANGE_REC___RESEND_TRAN as RESEND_TRAN", \
	"FIL_NO_CHANGE_REC___REQ_SAM_REPLY as REQ_SAM_REPLY", \
	"FIL_NO_CHANGE_REC___PRIORITY as PRIORITY", \
	"FIL_NO_CHANGE_REC___ENGINE_CODE as ENGINE_CODE", \
	"FIL_NO_CHANGE_REC___TEAM_STD_GRP as TEAM_STD_GRP", \
	"FIL_NO_CHANGE_REC___MISC as MISC", \
	"FIL_NO_CHANGE_REC___MISC_2 as MISC_2", \
	"FIL_NO_CHANGE_REC___CREATED_SOURCE_TYPE as CREATED_SOURCE_TYPE", \
	"FIL_NO_CHANGE_REC___CREATED_SOURCE as CREATED_SOURCE", \
	"FIL_NO_CHANGE_REC___CREATED_DTTM as CREATED_DTTM", \
	"FIL_NO_CHANGE_REC___LAST_UPDATED_SOURCE_TYPE as LAST_UPDATED_SOURCE_TYPE", \
	"FIL_NO_CHANGE_REC___LAST_UPDATED_SOURCE as LAST_UPDATED_SOURCE", \
	"FIL_NO_CHANGE_REC___LAST_UPDATED_DTTM as LAST_UPDATED_DTTM", \
	"FIL_NO_CHANGE_REC___ACTUAL_END_TIME as ACTUAL_END_TIME", \
	"FIL_NO_CHANGE_REC___ACTUAL_END_DATE as ACTUAL_END_DATE", \
	"FIL_NO_CHANGE_REC___PLAN_ID as PLAN_ID", \
	"FIL_NO_CHANGE_REC___WAVE_NBR as WAVE_NBR", \
	"FIL_NO_CHANGE_REC___TRANS_TYPE as TRANS_TYPE", \
	"FIL_NO_CHANGE_REC___TRANS_VALUE as TRANS_VALUE", \
	"FIL_NO_CHANGE_REC___ENGINE_GROUP as ENGINE_GROUP", \
	"FIL_NO_CHANGE_REC___COMPLETED_WORK as COMPLETED_WORK", \
	"FIL_NO_CHANGE_REC___WHSE_DATE as WHSE_DATE", \
	"FIL_NO_CHANGE_REC___JOB_FUNCTION as JOB_FUNCTION", \
	"FIL_NO_CHANGE_REC___LEVEL_1 as LEVEL_1", \
	"FIL_NO_CHANGE_REC___LEVEL_2 as LEVEL_2", \
	"FIL_NO_CHANGE_REC___LEVEL_3 as LEVEL_3", \
	"FIL_NO_CHANGE_REC___LEVEL_4 as LEVEL_4", \
	"FIL_NO_CHANGE_REC___LEVEL_5 as LEVEL_5", \
	"FIL_NO_CHANGE_REC___CARTON_NBR as CARTON_NBR", \
	"FIL_NO_CHANGE_REC___TASK_NBR as TASK_NBR", \
	"FIL_NO_CHANGE_REC___CASE_NBR as CASE_NBR", \
	"FIL_NO_CHANGE_REC___ORIG_COMPLETED_WORK as ORIG_COMPLETED_WORK", \
	"FIL_NO_CHANGE_REC___TRAN_DATA_ELS_TRAN_ID as TRAN_DATA_ELS_TRAN_ID", \
	"FIL_NO_CHANGE_REC___MISC_TXT_1 as MISC_TXT_1", \
	"FIL_NO_CHANGE_REC___MISC_TXT_2 as MISC_TXT_2", \
	"FIL_NO_CHANGE_REC___MISC_NUM_1 as MISC_NUM_1", \
	"FIL_NO_CHANGE_REC___MISC_NUM_2 as MISC_NUM_2", \
	"FIL_NO_CHANGE_REC___EVNT_CTGRY_1 as EVNT_CTGRY_1", \
	"FIL_NO_CHANGE_REC___EVNT_CTGRY_2 as EVNT_CTGRY_2", \
	"FIL_NO_CHANGE_REC___EVNT_CTGRY_3 as EVNT_CTGRY_3", \
	"FIL_NO_CHANGE_REC___EVNT_CTGRY_4 as EVNT_CTGRY_4", \
	"FIL_NO_CHANGE_REC___EVNT_CTGRY_5 as EVNT_CTGRY_5", \
	"FIL_NO_CHANGE_REC___HIBERNATE_VERSION as HIBERNATE_VERSION", \
	"FIL_NO_CHANGE_REC___DEPT as DEPT", \
	"FIL_NO_CHANGE_REC___MSG_STAT_CODE as MSG_STAT_CODE", \
	"FIL_NO_CHANGE_REC___MONITOR_SMRY_ID as MONITOR_SMRY_ID", \
	"FIL_NO_CHANGE_REC___ORIG_ACT_NAME as ORIG_ACT_NAME", \
	"FIL_NO_CHANGE_REC___SOURCE as SOURCE", \
	"FIL_NO_CHANGE_REC___HAS_MONITOR_MSG as HAS_MONITOR_MSG", \
	"FIL_NO_CHANGE_REC___TOTAL_QTY as TOTAL_QTY", \
	"FIL_NO_CHANGE_REC___ORIG_EVNT_START_TIME as ORIG_EVNT_START_TIME", \
	"FIL_NO_CHANGE_REC___ORIG_EVNT_END_TIME as ORIG_EVNT_END_TIME", \
	"FIL_NO_CHANGE_REC___ADJ_REASON_CODE as ADJ_REASON_CODE", \
	"FIL_NO_CHANGE_REC___ADJ_REF_TRAN_NBR as ADJ_REF_TRAN_NBR", \
	"FIL_NO_CHANGE_REC___INT_TYPE as INT_TYPE", \
    "CASE WHEN TRIM(UPPER(FIL_NO_CHANGE_REC___CONFLICT)) IN ('Y', '1') THEN '1' ELSE '0' END as CONFLICT_FLAG_EXP", \
	"FIL_NO_CHANGE_REC___DISPLAY_UOM as DISPLAY_UOM", \
	"FIL_NO_CHANGE_REC___UOM_QTY as UOM_QTY", \
	"FIL_NO_CHANGE_REC___THRUPUT_MIN as THRUPUT_MIN", \
	"FIL_NO_CHANGE_REC___LOCN_GRP_ATTR as LOCN_GRP_ATTR", \
	"FIL_NO_CHANGE_REC___RESOURCE_GROUP_ID as RESOURCE_GROUP_ID", \
	"FIL_NO_CHANGE_REC___LOCATION_ID as LOCATION_ID", \
	"FIL_NO_CHANGE_REC___in_WM_LOCATION_ID as in_WM_LOCATION_ID", \
	"FIL_NO_CHANGE_REC___WM_LABOR_MSG_ID as WM_LABOR_MSG_ID", \
	"FIL_NO_CHANGE_REC___WM_TC_COMPANY_ID as WM_TC_COMPANY_ID", \
	"FIL_NO_CHANGE_REC___WM_WHSE as WM_WHSE", \
	"FIL_NO_CHANGE_REC___WM_LABOR_MSG_STATUS as WM_LABOR_MSG_STATUS", \
	"FIL_NO_CHANGE_REC___WM_MSG_STAT_CD as WM_MSG_STAT_CD", \
	"FIL_NO_CHANGE_REC___WM_TRAN_NBR as WM_TRAN_NBR", \
	"FIL_NO_CHANGE_REC___WM_LOGIN_USER_ID as WM_LOGIN_USER_ID", \
	"FIL_NO_CHANGE_REC___WM_ACCOUNT_NAME as WM_ACCOUNT_NAME", \
	"FIL_NO_CHANGE_REC___WM_ORIG_ACCOUNT_NAME as WM_ORIG_ACCOUNT_NAME", \
	"FIL_NO_CHANGE_REC___WM_DEPT as WM_DEPT", \
	"FIL_NO_CHANGE_REC___WM_DIVISION as WM_DIVISION", \
	"FIL_NO_CHANGE_REC___WM_JOB_FUNCTION as WM_JOB_FUNCTION", \
	"FIL_NO_CHANGE_REC___WM_SHIFT as WM_SHIFT", \
	"FIL_NO_CHANGE_REC___WM_WHSE_TSTMP as WM_WHSE_TSTMP", \
	"FIL_NO_CHANGE_REC___WM_ORIG_EVNT_START_TSTMP as WM_ORIG_EVNT_START_TSTMP", \
	"FIL_NO_CHANGE_REC___WM_ORIG_EVNT_END_TSTMP as WM_ORIG_EVNT_END_TSTMP", \
	"FIL_NO_CHANGE_REC___WM_SCHED_START_TIME as WM_SCHED_START_TIME", \
	"FIL_NO_CHANGE_REC___WM_SCHED_START_TSTMP as WM_SCHED_START_TSTMP", \
	"FIL_NO_CHANGE_REC___WM_ACTUAL_END_TIME as WM_ACTUAL_END_TIME", \
	"FIL_NO_CHANGE_REC___WM_ACTUAL_END_TSTMP as WM_ACTUAL_END_TSTMP", \
	"FIL_NO_CHANGE_REC___WM_TASK_NBR as WM_TASK_NBR", \
	"FIL_NO_CHANGE_REC___WM_CASE_NBR as WM_CASE_NBR", \
	"FIL_NO_CHANGE_REC___WM_CARTON_NBR as WM_CARTON_NBR", \
	"FIL_NO_CHANGE_REC___WM_WAVE_NBR as WM_WAVE_NBR", \
	"FIL_NO_CHANGE_REC___WM_TRAN_DATA_ELS_TRAN_ID as WM_TRAN_DATA_ELS_TRAN_ID", \
	"FIL_NO_CHANGE_REC___WM_LOCN_GRP_ATTR as WM_LOCN_GRP_ATTR", \
	"FIL_NO_CHANGE_REC___WM_VEHICLE_TYPE as WM_VEHICLE_TYPE", \
	"FIL_NO_CHANGE_REC___WM_ENGINE_CD as WM_ENGINE_CD", \
	"FIL_NO_CHANGE_REC___WM_ENGINE_GROUP as WM_ENGINE_GROUP", \
	"FIL_NO_CHANGE_REC___WM_TEAM_STD_GRP as WM_TEAM_STD_GRP", \
	"FIL_NO_CHANGE_REC___WM_REF_CD as WM_REF_CD", \
	"FIL_NO_CHANGE_REC___WM_REF_NBR as WM_REF_NBR", \
	"FIL_NO_CHANGE_REC___WM_MONITOR_SMRY_ID as WM_MONITOR_SMRY_ID", \
	"FIL_NO_CHANGE_REC___HAS_MONITOR_MSG_FLAG as HAS_MONITOR_MSG_FLAG", \
	"FIL_NO_CHANGE_REC___RESEND_TRAN_FLAG as RESEND_TRAN_FLAG", \
	"FIL_NO_CHANGE_REC___REQ_SAM_REPLY_FLAG as REQ_SAM_REPLY_FLAG", \
	"FIL_NO_CHANGE_REC___CONFLICT_FLAG as CONFLICT_FLAG", \
	"FIL_NO_CHANGE_REC___PRIORITY1 as PRIORITY1", \
	"FIL_NO_CHANGE_REC___WM_PLAN_ID as WM_PLAN_ID", \
	"FIL_NO_CHANGE_REC___WM_RESOURCE_GROUP_ID as WM_RESOURCE_GROUP_ID", \
	"FIL_NO_CHANGE_REC___WM_ADJ_REASON_CD as WM_ADJ_REASON_CD", \
	"FIL_NO_CHANGE_REC___WM_ADJ_REF_TRAN_NBR as WM_ADJ_REF_TRAN_NBR", \
	"FIL_NO_CHANGE_REC___WM_INV_NEED_TYPE as WM_INV_NEED_TYPE", \
	"FIL_NO_CHANGE_REC___WM_TRANS_TYPE as WM_TRANS_TYPE", \
	"FIL_NO_CHANGE_REC___WM_TRANS_VALUE as WM_TRANS_VALUE", \
	"FIL_NO_CHANGE_REC___WM_DISPLAY_UOM as WM_DISPLAY_UOM", \
	"FIL_NO_CHANGE_REC___in_WM_UOM_QTY as in_WM_UOM_QTY", \
	"FIL_NO_CHANGE_REC___in_WM_THRUPUT_MIN as in_WM_THRUPUT_MIN", \
	"FIL_NO_CHANGE_REC___TOTAL_QTY1 as TOTAL_QTY1", \
	"FIL_NO_CHANGE_REC___in_WM_ORIG_COMPLETED_WORK as in_WM_ORIG_COMPLETED_WORK", \
	"FIL_NO_CHANGE_REC___in_WM_COMPLETED_WORK as in_WM_COMPLETED_WORK", \
	"FIL_NO_CHANGE_REC___in_WM_USER_DEF_VAL_1 as in_WM_USER_DEF_VAL_1", \
	"FIL_NO_CHANGE_REC___in_WM_USER_DEF_VAL_2 as in_WM_USER_DEF_VAL_2", \
	"FIL_NO_CHANGE_REC___in_WM_MISC as in_WM_MISC", \
	"FIL_NO_CHANGE_REC___in_WM_MISC_2 as in_WM_MISC_2", \
	"FIL_NO_CHANGE_REC___in_WM_MISC_TXT_1 as in_WM_MISC_TXT_1", \
	"FIL_NO_CHANGE_REC___in_WM_MISC_TXT_2 as in_WM_MISC_TXT_2", \
	"FIL_NO_CHANGE_REC___in_WM_MISC_NUM_1 as in_WM_MISC_NUM_1", \
	"FIL_NO_CHANGE_REC___in_WM_MISC_NUM_2 as in_WM_MISC_NUM_2", \
	"FIL_NO_CHANGE_REC___in_WM_EVNT_CTGRY_1 as in_WM_EVNT_CTGRY_1", \
	"FIL_NO_CHANGE_REC___in_WM_EVNT_CTGRY_2 as in_WM_EVNT_CTGRY_2", \
	"FIL_NO_CHANGE_REC___in_WM_EVNT_CTGRY_3 as in_WM_EVNT_CTGRY_3", \
	"FIL_NO_CHANGE_REC___in_WM_EVNT_CTGRY_4 as in_WM_EVNT_CTGRY_4", \
	"FIL_NO_CHANGE_REC___in_WM_EVNT_CTGRY_5 as in_WM_EVNT_CTGRY_5", \
	"FIL_NO_CHANGE_REC___in_WM_LEVEL_1 as in_WM_LEVEL_1", \
	"FIL_NO_CHANGE_REC___in_WM_LEVEL_2 as in_WM_LEVEL_2", \
	"FIL_NO_CHANGE_REC___in_WM_LEVEL_3 as in_WM_LEVEL_3", \
	"FIL_NO_CHANGE_REC___in_WM_LEVEL_4 as in_WM_LEVEL_4", \
	"FIL_NO_CHANGE_REC___in_WM_LEVEL_5 as in_WM_LEVEL_5", \
	"FIL_NO_CHANGE_REC___WM_SOURCE as WM_SOURCE", \
	"FIL_NO_CHANGE_REC___WM_MOD_USER_ID as WM_MOD_USER_ID", \
	"FIL_NO_CHANGE_REC___WM_HIBERNATE_VERSION as WM_HIBERNATE_VERSION", \
	"FIL_NO_CHANGE_REC___WM_CREATED_SOURCE_TYPE as WM_CREATED_SOURCE_TYPE", \
	"FIL_NO_CHANGE_REC___WM_CREATED_SOURCE as WM_CREATED_SOURCE", \
	"FIL_NO_CHANGE_REC___WM_LAST_UPDATED_SOURCE_TYPE as WM_LAST_UPDATED_SOURCE_TYPE", \
	"FIL_NO_CHANGE_REC___WM_LAST_UPDATED_SOURCE as WM_LAST_UPDATED_SOURCE", \
	"FIL_NO_CHANGE_REC___WM_CREATED_TSTMP as WM_CREATED_TSTMP", \
	"FIL_NO_CHANGE_REC___WM_LAST_UPDATED_DTTM as WM_LAST_UPDATED_DTTM", \
	"FIL_NO_CHANGE_REC___in_WM_UPDATE_TSTMP as in_WM_UPDATE_TSTMP", \
	"FIL_NO_CHANGE_REC___in_WM_LOAD_TSTMP as in_WM_LOAD_TSTMP", \
	"CURRENT_TIMESTAMP as UPDATE_TSTMP", \
	"IF(FIL_NO_CHANGE_REC___in_WM_LOAD_TSTMP IS NULL, CURRENT_TIMESTAMP, FIL_NO_CHANGE_REC___in_WM_LOAD_TSTMP) as LOAD_STSMP" \
)

# COMMAND ----------
# Processing node UPD_VALIDATE, type UPDATE_STRATEGY . Note: using additional SELECT to rename incoming columns
# COLUMN COUNT: 82

# for each involved DataFrame, append the dataframe name to each column
EXP_EVAL_VALUES_temp = EXP_EVAL_VALUES.toDF(*["EXP_EVAL_VALUES___" + col for col in EXP_EVAL_VALUES.columns])

UPD_VALIDATE = EXP_EVAL_VALUES_temp.selectExpr( \
	"EXP_EVAL_VALUES___LOCATION_ID as LOCATION_ID", \
	"EXP_EVAL_VALUES___LABOR_MSG_ID as LABOR_MSG_ID", \
	"EXP_EVAL_VALUES___TC_COMPANY_ID as TC_COMPANY_ID", \
	"EXP_EVAL_VALUES___WHSE as WHSE", \
	"EXP_EVAL_VALUES___STATUS as STATUS", \
	"EXP_EVAL_VALUES___MSG_STAT_CODE as MSG_STAT_CODE", \
	"EXP_EVAL_VALUES___TRAN_NBR as TRAN_NBR", \
	"EXP_EVAL_VALUES___LOGIN_USER_ID as LOGIN_USER_ID", \
	"EXP_EVAL_VALUES___ACT_NAME as ACT_NAME", \
	"EXP_EVAL_VALUES___ORIG_ACT_NAME as ORIG_ACT_NAME", \
	"EXP_EVAL_VALUES___DEPT as DEPT", \
	"EXP_EVAL_VALUES___DIV as DIV", \
	"EXP_EVAL_VALUES___JOB_FUNCTION as JOB_FUNCTION", \
	"EXP_EVAL_VALUES___SHIFT as SHIFT", \
	"EXP_EVAL_VALUES___WHSE_DATE as WHSE_DATE", \
	"EXP_EVAL_VALUES___ORIG_EVNT_START_TIME as ORIG_EVNT_START_TIME", \
	"EXP_EVAL_VALUES___ORIG_EVNT_END_TIME as ORIG_EVNT_END_TIME", \
	"EXP_EVAL_VALUES___SCHED_START_TIME as SCHED_START_TIME", \
	"EXP_EVAL_VALUES___SCHED_START_DATE as SCHED_START_DATE", \
	"EXP_EVAL_VALUES___ACTUAL_END_TIME as ACTUAL_END_TIME", \
	"EXP_EVAL_VALUES___ACTUAL_END_DATE as ACTUAL_END_DATE", \
	"EXP_EVAL_VALUES___TASK_NBR as TASK_NBR", \
	"EXP_EVAL_VALUES___CASE_NBR as CASE_NBR", \
	"EXP_EVAL_VALUES___CARTON_NBR as CARTON_NBR", \
	"EXP_EVAL_VALUES___WAVE_NBR as WAVE_NBR", \
	"EXP_EVAL_VALUES___TRAN_DATA_ELS_TRAN_ID as TRAN_DATA_ELS_TRAN_ID", \
	"EXP_EVAL_VALUES___LOCN_GRP_ATTR as LOCN_GRP_ATTR", \
	"EXP_EVAL_VALUES___VHCL_TYPE as VHCL_TYPE", \
	"EXP_EVAL_VALUES___ENGINE_CODE as ENGINE_CODE", \
	"EXP_EVAL_VALUES___ENGINE_GROUP as ENGINE_GROUP", \
	"EXP_EVAL_VALUES___TEAM_STD_GRP as TEAM_STD_GRP", \
	"EXP_EVAL_VALUES___REF_CODE as REF_CODE", \
	"EXP_EVAL_VALUES___REF_NBR as REF_NBR", \
	"EXP_EVAL_VALUES___MONITOR_SMRY_ID as MONITOR_SMRY_ID", \
	"EXP_EVAL_VALUES___HAS_MONITOR_MSG as HAS_MONITOR_MSG", \
	"EXP_EVAL_VALUES___RESEND_TRAN as RESEND_TRAN_EXP", \
	"EXP_EVAL_VALUES___REQ_SAM_REPLY as REQ_SAM_REPLY_EXP", \
	"EXP_EVAL_VALUES___CONFLICT_FLAG_EXP as CONFLICT_FLAG_EXP", \
	"EXP_EVAL_VALUES___PRIORITY as PRIORITY", \
	"EXP_EVAL_VALUES___PLAN_ID as PLAN_ID", \
	"EXP_EVAL_VALUES___RESOURCE_GROUP_ID as RESOURCE_GROUP_ID", \
	"EXP_EVAL_VALUES___ADJ_REASON_CODE as ADJ_REASON_CODE", \
	"EXP_EVAL_VALUES___ADJ_REF_TRAN_NBR as ADJ_REF_TRAN_NBR", \
	"EXP_EVAL_VALUES___INT_TYPE as INT_TYPE", \
	"EXP_EVAL_VALUES___TRANS_TYPE as TRANS_TYPE", \
	"EXP_EVAL_VALUES___TRANS_VALUE as TRANS_VALUE", \
	"EXP_EVAL_VALUES___DISPLAY_UOM as DISPLAY_UOM", \
	"EXP_EVAL_VALUES___UOM_QTY as UOM_QTY", \
	"EXP_EVAL_VALUES___THRUPUT_MIN as THRUPUT_MIN", \
	"EXP_EVAL_VALUES___TOTAL_QTY as TOTAL_QTY", \
	"EXP_EVAL_VALUES___ORIG_COMPLETED_WORK as ORIG_COMPLETED_WORK", \
	"EXP_EVAL_VALUES___COMPLETED_WORK as COMPLETED_WORK", \
	"EXP_EVAL_VALUES___USER_DEF_VAL_1 as USER_DEF_VAL_1", \
	"EXP_EVAL_VALUES___USER_DEF_VAL_2 as USER_DEF_VAL_2", \
	"EXP_EVAL_VALUES___MISC as MISC", \
	"EXP_EVAL_VALUES___MISC_2 as MISC_2", \
	"EXP_EVAL_VALUES___MISC_TXT_1 as MISC_TXT_1", \
	"EXP_EVAL_VALUES___MISC_TXT_2 as MISC_TXT_2", \
	"EXP_EVAL_VALUES___MISC_NUM_1 as MISC_NUM_1", \
	"EXP_EVAL_VALUES___MISC_NUM_2 as MISC_NUM_2", \
	"EXP_EVAL_VALUES___EVNT_CTGRY_1 as EVNT_CTGRY_1", \
	"EXP_EVAL_VALUES___EVNT_CTGRY_2 as EVNT_CTGRY_2", \
	"EXP_EVAL_VALUES___EVNT_CTGRY_3 as EVNT_CTGRY_3", \
	"EXP_EVAL_VALUES___EVNT_CTGRY_4 as EVNT_CTGRY_4", \
	"EXP_EVAL_VALUES___EVNT_CTGRY_5 as EVNT_CTGRY_5", \
	"EXP_EVAL_VALUES___LEVEL_1 as LEVEL_1", \
	"EXP_EVAL_VALUES___LEVEL_2 as LEVEL_2", \
	"EXP_EVAL_VALUES___LEVEL_3 as LEVEL_3", \
	"EXP_EVAL_VALUES___LEVEL_4 as LEVEL_4", \
	"EXP_EVAL_VALUES___LEVEL_5 as LEVEL_5", \
	"EXP_EVAL_VALUES___SOURCE as SOURCE", \
	"EXP_EVAL_VALUES___MOD_USER_ID as MOD_USER_ID", \
	"EXP_EVAL_VALUES___HIBERNATE_VERSION as HIBERNATE_VERSION", \
	"EXP_EVAL_VALUES___CREATED_SOURCE_TYPE as CREATED_SOURCE_TYPE", \
	"EXP_EVAL_VALUES___CREATED_SOURCE as CREATED_SOURCE", \
	"EXP_EVAL_VALUES___LAST_UPDATED_SOURCE_TYPE as LAST_UPDATED_SOURCE_TYPE", \
	"EXP_EVAL_VALUES___LAST_UPDATED_SOURCE as LAST_UPDATED_SOURCE", \
	"EXP_EVAL_VALUES___CREATED_DTTM as CREATED_DTTM", \
	"EXP_EVAL_VALUES___LAST_UPDATED_DTTM as LAST_UPDATED_DTTM", \
	"EXP_EVAL_VALUES___UPDATE_TSTMP as UPDATE_TSTMP", \
	"EXP_EVAL_VALUES___LOAD_STSMP as LOAD_STSMP", \
	"EXP_EVAL_VALUES___WM_LABOR_MSG_ID as WM_LABOR_MSG_ID") \
	.withColumn('pyspark_data_action', when((col('WM_LABOR_MSG_ID').isNull()) ,(lit(0))) .otherwise(lit(1)))

# COMMAND ----------
# Processing node Shortcut_to_WM_LABOR_MSG1, type TARGET 
# COLUMN COUNT: 81

Shortcut_to_WM_LABOR_MSG1 = UPD_VALIDATE.selectExpr(
	"CAST(LOCATION_ID AS BIGINT) as LOCATION_ID",
	"CAST(LABOR_MSG_ID AS DECIMAL(20,0)) as WM_LABOR_MSG_ID",
	"CAST(TC_COMPANY_ID AS DECIMAL(9,0)) as WM_TC_COMPANY_ID",
	"CAST(WHSE AS STRING) as WM_WHSE",
	"CAST(STATUS AS DECIMAL(9,0)) as WM_LABOR_MSG_STATUS",
	"CAST(MSG_STAT_CODE AS DECIMAL(4,0)) as WM_MSG_STAT_CD",
	"CAST(TRAN_NBR AS DECIMAL(9,0)) as WM_TRAN_NBR",
	"CAST(LOGIN_USER_ID AS STRING) as WM_LOGIN_USER_ID",
	"CAST(ACT_NAME AS STRING) as WM_ACCOUNT_NAME",
	"CAST(ORIG_ACT_NAME AS STRING) as WM_ORIG_ACCOUNT_NAME",
	"CAST(DEPT AS STRING) as WM_DEPT",
	"CAST(DIV AS STRING) as WM_DIVISION",
	"CAST(JOB_FUNCTION AS STRING) as WM_JOB_FUNCTION",
	"CAST(SHIFT AS STRING) as WM_SHIFT",
	"CAST(WHSE_DATE AS TIMESTAMP) as WM_WHSE_TSTMP",
	"CAST(ORIG_EVNT_START_TIME AS TIMESTAMP) as WM_ORIG_EVNT_START_TSTMP",
	"CAST(ORIG_EVNT_END_TIME AS TIMESTAMP) as WM_ORIG_EVNT_END_TSTMP",
	"CAST(SCHED_START_TIME AS TIMESTAMP) as WM_SCHED_START_TIME",
	"CAST(SCHED_START_DATE AS TIMESTAMP) as WM_SCHED_START_TSTMP",
	"CAST(ACTUAL_END_TIME AS TIMESTAMP) as WM_ACTUAL_END_TIME",
	"CAST(ACTUAL_END_DATE AS TIMESTAMP) as WM_ACTUAL_END_TSTMP",
	"CAST(TASK_NBR AS STRING) as WM_TASK_NBR",
	"CAST(CASE_NBR AS STRING) as WM_CASE_NBR",
	"CAST(CARTON_NBR AS STRING) as WM_CARTON_NBR",
	"CAST(WAVE_NBR AS STRING) as WM_WAVE_NBR",
	"CAST(TRAN_DATA_ELS_TRAN_ID AS DECIMAL(20,0)) as WM_TRAN_DATA_ELS_TRAN_ID",
	"CAST(LOCN_GRP_ATTR AS STRING) as WM_LOCN_GRP_ATTR",
	"CAST(VHCL_TYPE AS STRING) as WM_VEHICLE_TYPE",
	"CAST(ENGINE_CODE AS STRING) as WM_ENGINE_CD",
	"CAST(ENGINE_GROUP AS STRING) as WM_ENGINE_GROUP",
	"CAST(TEAM_STD_GRP AS STRING) as WM_TEAM_STD_GRP",
	"CAST(REF_CODE AS STRING) as WM_REF_CD",
	"CAST(REF_NBR AS STRING) as WM_REF_NBR",
	"CAST(MONITOR_SMRY_ID AS DECIMAL(9,0)) as WM_MONITOR_SMRY_ID",
	"CAST(HAS_MONITOR_MSG AS DECIMAL(1,0)) as HAS_MONITOR_MSG_FLAG",
	"CAST(RESEND_TRAN_EXP AS STRING) as RESEND_TRAN_FLAG",
	"CAST(REQ_SAM_REPLY_EXP AS STRING) as REQ_SAM_REPLY_FLAG",
	"CAST(CONFLICT_FLAG_EXP AS DECIMAL(1,0)) as CONFLICT_FLAG",
	"CAST(PRIORITY AS DECIMAL(9,0)) as PRIORITY",
	"CAST(PLAN_ID AS STRING) as WM_PLAN_ID",
	"CAST(RESOURCE_GROUP_ID AS STRING) as WM_RESOURCE_GROUP_ID",
	"CAST(ADJ_REASON_CODE AS STRING) as WM_ADJ_REASON_CD",
	"CAST(ADJ_REF_TRAN_NBR AS DECIMAL(20,0)) as WM_ADJ_REF_TRAN_NBR",
	"CAST(INT_TYPE AS STRING) as WM_INV_NEED_TYPE",
	"CAST(TRANS_TYPE AS STRING) as WM_TRANS_TYPE",
	"CAST(TRANS_VALUE AS STRING) as WM_TRANS_VALUE",
	"CAST(DISPLAY_UOM AS STRING) as WM_DISPLAY_UOM",
	"CAST(UOM_QTY AS DECIMAL(20,7)) as UOM_QTY",
	"CAST(THRUPUT_MIN AS DECIMAL(20,7)) as THRUPUT_MIN",
	"CAST(TOTAL_QTY AS DECIMAL(20,7)) as TOTAL_QTY",
	"CAST(ORIG_COMPLETED_WORK AS DECIMAL(20,7)) as ORIG_COMPLETED_WORK",
	"CAST(COMPLETED_WORK AS DECIMAL(20,7)) as COMPLETED_WORK",
	"CAST(USER_DEF_VAL_1 AS STRING) as USER_DEF_VAL_1",
	"CAST(USER_DEF_VAL_2 AS STRING) as USER_DEF_VAL_2",
	"CAST(MISC AS STRING) as MISC",
	"CAST(MISC_2 AS STRING) as MISC_2",
	"CAST(MISC_TXT_1 AS STRING) as MISC_TXT_1",
	"CAST(MISC_TXT_2 AS STRING) as MISC_TXT_2",
	"CAST(MISC_NUM_1 AS DECIMAL(20,7)) as MISC_NUM_1",
	"CAST(MISC_NUM_2 AS DECIMAL(20,7)) as MISC_NUM_2",
	"CAST(EVNT_CTGRY_1 AS STRING) as EVNT_CTGRY_1",
	"CAST(EVNT_CTGRY_2 AS STRING) as EVNT_CTGRY_2",
	"CAST(EVNT_CTGRY_3 AS STRING) as EVNT_CTGRY_3",
	"CAST(EVNT_CTGRY_4 AS STRING) as EVNT_CTGRY_4",
	"CAST(EVNT_CTGRY_5 AS STRING) as EVNT_CTGRY_5",
	"CAST(LEVEL_1 AS STRING) as LEVEL_1",
	"CAST(LEVEL_2 AS STRING) as LEVEL_2",
	"CAST(LEVEL_3 AS STRING) as LEVEL_3",
	"CAST(LEVEL_4 AS STRING) as LEVEL_4",
	"CAST(LEVEL_5 AS STRING) as LEVEL_5",
	"CAST(SOURCE AS STRING) as WM_SOURCE",
	"CAST(MOD_USER_ID AS STRING) as WM_MOD_USER_ID",
	"CAST(HIBERNATE_VERSION AS DECIMAL(10,0)) as WM_HIBERNATE_VERSION",
	"CAST(CREATED_SOURCE_TYPE AS DECIMAL(4,0)) as WM_CREATED_SOURCE_TYPE",
	"CAST(CREATED_SOURCE AS STRING) as WM_CREATED_SOURCE",
	"CAST(LAST_UPDATED_SOURCE_TYPE AS DECIMAL(4,0)) as WM_LAST_UPDATED_SOURCE_TYPE",
	"CAST(LAST_UPDATED_SOURCE AS STRING) as WM_LAST_UPDATED_SOURCE",
	"CAST(CREATED_DTTM AS TIMESTAMP) as WM_CREATED_TSTMP",
	"CAST(LAST_UPDATED_DTTM AS TIMESTAMP) as WM_LAST_UPDATED_DTTM",
	"CAST(UPDATE_TSTMP AS TIMESTAMP) as UPDATE_TSTMP",
	"CAST(LOAD_STSMP AS TIMESTAMP) as LOAD_TSTMP", 
    "pyspark_data_action" 
)

try:
  primary_key = """source.LOCATION_ID = target.LOCATION_ID AND source.WM_LABOR_MSG_ID = target.WM_LABOR_MSG_ID"""
#   refined_perf_table = "WM_LABOR_MSG"
  executeMerge(Shortcut_to_WM_LABOR_MSG1, refined_perf_table, primary_key)
  logger.info(f"Merge with {refined_perf_table} completed]")
  logPrevRunDt("WM_LABOR_MSG", "WM_LABOR_MSG", "Completed", "N/A", f"{raw}.log_run_details")
except Exception as e:
  logPrevRunDt("WM_LABOR_MSG", "WM_LABOR_MSG","Failed",str(e), f"{raw}.log_run_details", )
  raise e
	