# Databricks notebook source
#Code converted on 2023-11-06 15:44:15
import os
from pyspark.sql import *
from pyspark.sql.functions import *
from datetime import datetime
from Datalake.utils.genericUtilities import *
from Datalake.utils.configs import *
from Datalake.utils.mergeUtils import *
from Datalake.utils.logger import *
from Datalake.utils.pk import *

# COMMAND ----------

spark = SparkSession.getActiveSession()
dbutils = DBUtils(spark)
dbutils.widgets.text(name = 'env', defaultValue = 'dev')
env = dbutils.widgets.get('env')

if env is None or env == '':
    raise ValueError('env is not set')

raw = getEnvPrefix(env) + 'raw'
legacy = getEnvPrefix(env) + 'legacy'
refine = getEnvPrefix(env) + 'refine'

# Set global variables
starttime = datetime.now() #start timestamp of the script


# COMMAND ----------

# Processing node SQ_Shortcut_to_SALES_RANKING_WK_PRE, type SOURCE 
# COLUMN COUNT: 58

SQ_Shortcut_to_SALES_RANKING_WK_PRE = spark.sql(f"""SELECT
WEEK_DT,
LOCATION_ID,
COMP_CURR_FLAG,
SALES_CURR_FLAG,
TOTAL_52WK_SALES_AMT,
TOTAL_52WK_COMP_STORES_AMT,
STORE_TOTAL_SALES_PCT,
RUNNING_SUM_TOTAL_SALES_PCT,
TOTAL_SALES_RANKING_CD,
TOTAL_SALES_RANKING_LEVEL,
MERCH_52WK_SALES_AMT,
MERCH_52WK_COMP_STORES_AMT,
STORE_MERCH_SALES_PCT,
RUNNING_SUM_MERCH_SALES_PCT,
MERCH_SALES_RANKING_CD,
MERCH_SALES_RANKING_LEVEL,
SERVICES_52WK_SALES_AMT,
SERVICES_52WK_COMP_STORES_AMT,
STORE_SERVICES_SALES_PCT,
RUNNING_SUM_SERVICES_SALES_PCT,
SERVICES_SALES_RANKING_CD,
SERVICES_SALES_RANKING_LEVEL,
SALON_52WK_SALES_AMT,
SALON_52WK_COMP_STORES_AMT,
STORE_SALON_SALES_PCT,
RUNNING_SUM_SALON_SALES_PCT,
SALON_SALES_RANKING_CD,
SALON_SALES_RANKING_LEVEL,
TRAINING_52WK_SALES_AMT,
TRAINING_52WK_COMP_STORES_AMT,
STORE_TRAINING_SALES_PCT,
RUNNING_SUM_TRAINING_SALES_PCT,
TRAINING_SALES_RANKING_CD,
TRAINING_SALES_RANKING_LEVEL,
HOTEL_DDC_52WK_SALES_AMT,
HOTEL_DDC_52WK_COMP_STORES_AMT,
STORE_HOTEL_DDC_SALES_PCT,
RUNNING_SUM_HOTEL_DDC_SALES_PCT,
HOTEL_DDC_SALES_RANKING_CD,
HOTEL_DDC_SALES_RANKING_LEVEL,
CONSUMABLES_52WK_SALES_AMT,
CONSUMABLES_52WK_COMP_STORES_AMT,
STORE_CONSUMABLES_SALES_PCT,
RUNNING_SUM_CONSUMABLES_SALES_PCT,
CONSUMABLES_SALES_RANKING_CD,
CONSUMABLES_SALES_RANKING_LEVEL,
HARDGOODS_52WK_SALES_AMT,
HARDGOODS_52WK_COMP_STORES_AMT,
STORE_HARDGOODS_SALES_PCT,
RUNNING_SUM_HARDGOODS_SALES_PCT,
HARDGOODS_SALES_RANKING_CD,
HARDGOODS_SALES_RANKING_LEVEL,
SPECIALTY_52WK_SALES_AMT,
SPECIALTY_52WK_COMP_STORES_AMT,
STORE_SPECIALTY_SALES_PCT,
RUNNING_SUM_SPECIALTY_SALES_PCT,
SPECIALTY_SALES_RANKING_CD,
SPECIALTY_SALES_RANKING_LEVEL
FROM {raw}.SALES_RANKING_WK_PRE""").withColumn("sys_row_id", monotonically_increasing_id())
# Conforming fields names to the component layout
SQ_Shortcut_to_SALES_RANKING_WK_PRE = SQ_Shortcut_to_SALES_RANKING_WK_PRE \
	.withColumnRenamed(SQ_Shortcut_to_SALES_RANKING_WK_PRE.columns[0],'WEEK_DT') \
	.withColumnRenamed(SQ_Shortcut_to_SALES_RANKING_WK_PRE.columns[1],'LOCATION_ID') \
	.withColumnRenamed(SQ_Shortcut_to_SALES_RANKING_WK_PRE.columns[2],'COMP_CURR_FLAG') \
	.withColumnRenamed(SQ_Shortcut_to_SALES_RANKING_WK_PRE.columns[3],'SALES_CURR_FLAG') \
	.withColumnRenamed(SQ_Shortcut_to_SALES_RANKING_WK_PRE.columns[4],'TOTAL_52WK_SALES_AMT') \
	.withColumnRenamed(SQ_Shortcut_to_SALES_RANKING_WK_PRE.columns[5],'TOTAL_52WK_COMP_STORES_AMT') \
	.withColumnRenamed(SQ_Shortcut_to_SALES_RANKING_WK_PRE.columns[6],'STORE_TOTAL_SALES_PCT') \
	.withColumnRenamed(SQ_Shortcut_to_SALES_RANKING_WK_PRE.columns[7],'RUNNING_SUM_TOTAL_SALES_PCT') \
	.withColumnRenamed(SQ_Shortcut_to_SALES_RANKING_WK_PRE.columns[8],'TOTAL_SALES_RANKING_CD') \
	.withColumnRenamed(SQ_Shortcut_to_SALES_RANKING_WK_PRE.columns[9],'TOTAL_SALES_RANKING_LEVEL') \
	.withColumnRenamed(SQ_Shortcut_to_SALES_RANKING_WK_PRE.columns[10],'MERCH_52WK_SALES_AMT') \
	.withColumnRenamed(SQ_Shortcut_to_SALES_RANKING_WK_PRE.columns[11],'MERCH_52WK_COMP_STORES_AMT') \
	.withColumnRenamed(SQ_Shortcut_to_SALES_RANKING_WK_PRE.columns[12],'STORE_MERCH_SALES_PCT') \
	.withColumnRenamed(SQ_Shortcut_to_SALES_RANKING_WK_PRE.columns[13],'RUNNING_SUM_MERCH_SALES_PCT') \
	.withColumnRenamed(SQ_Shortcut_to_SALES_RANKING_WK_PRE.columns[14],'MERCH_SALES_RANKING_CD') \
	.withColumnRenamed(SQ_Shortcut_to_SALES_RANKING_WK_PRE.columns[15],'MERCH_SALES_RANKING_LEVEL') \
	.withColumnRenamed(SQ_Shortcut_to_SALES_RANKING_WK_PRE.columns[16],'SERVICES_52WK_SALES_AMT') \
	.withColumnRenamed(SQ_Shortcut_to_SALES_RANKING_WK_PRE.columns[17],'SERVICES_52WK_COMP_STORES_AMT') \
	.withColumnRenamed(SQ_Shortcut_to_SALES_RANKING_WK_PRE.columns[18],'STORE_SERVICES_SALES_PCT') \
	.withColumnRenamed(SQ_Shortcut_to_SALES_RANKING_WK_PRE.columns[19],'RUNNING_SUM_SERVICES_SALES_PCT') \
	.withColumnRenamed(SQ_Shortcut_to_SALES_RANKING_WK_PRE.columns[20],'SERVICES_SALES_RANKING_CD') \
	.withColumnRenamed(SQ_Shortcut_to_SALES_RANKING_WK_PRE.columns[21],'SERVICES_SALES_RANKING_LEVEL') \
	.withColumnRenamed(SQ_Shortcut_to_SALES_RANKING_WK_PRE.columns[22],'SALON_52WK_SALES_AMT') \
	.withColumnRenamed(SQ_Shortcut_to_SALES_RANKING_WK_PRE.columns[23],'SALON_52WK_COMP_STORES_AMT') \
	.withColumnRenamed(SQ_Shortcut_to_SALES_RANKING_WK_PRE.columns[24],'STORE_SALON_SALES_PCT') \
	.withColumnRenamed(SQ_Shortcut_to_SALES_RANKING_WK_PRE.columns[25],'RUNNING_SUM_SALON_SALES_PCT') \
	.withColumnRenamed(SQ_Shortcut_to_SALES_RANKING_WK_PRE.columns[26],'SALON_SALES_RANKING_CD') \
	.withColumnRenamed(SQ_Shortcut_to_SALES_RANKING_WK_PRE.columns[27],'SALON_SALES_RANKING_LEVEL') \
	.withColumnRenamed(SQ_Shortcut_to_SALES_RANKING_WK_PRE.columns[28],'TRAINING_52WK_SALES_AMT') \
	.withColumnRenamed(SQ_Shortcut_to_SALES_RANKING_WK_PRE.columns[29],'TRAINING_52WK_COMP_STORES_AMT') \
	.withColumnRenamed(SQ_Shortcut_to_SALES_RANKING_WK_PRE.columns[30],'STORE_TRAINING_SALES_PCT') \
	.withColumnRenamed(SQ_Shortcut_to_SALES_RANKING_WK_PRE.columns[31],'RUNNING_SUM_TRAINING_SALES_PCT') \
	.withColumnRenamed(SQ_Shortcut_to_SALES_RANKING_WK_PRE.columns[32],'TRAINING_SALES_RANKING_CD') \
	.withColumnRenamed(SQ_Shortcut_to_SALES_RANKING_WK_PRE.columns[33],'TRAINING_SALES_RANKING_LEVEL') \
	.withColumnRenamed(SQ_Shortcut_to_SALES_RANKING_WK_PRE.columns[34],'HOTEL_DDC_52WK_SALES_AMT') \
	.withColumnRenamed(SQ_Shortcut_to_SALES_RANKING_WK_PRE.columns[35],'HOTEL_DDC_52WK_COMP_STORES_AMT') \
	.withColumnRenamed(SQ_Shortcut_to_SALES_RANKING_WK_PRE.columns[36],'STORE_HOTEL_DDC_SALES_PCT') \
	.withColumnRenamed(SQ_Shortcut_to_SALES_RANKING_WK_PRE.columns[37],'RUNNING_SUM_HOTEL_DDC_SALES_PCT') \
	.withColumnRenamed(SQ_Shortcut_to_SALES_RANKING_WK_PRE.columns[38],'HOTEL_DDC_SALES_RANKING_CD') \
	.withColumnRenamed(SQ_Shortcut_to_SALES_RANKING_WK_PRE.columns[39],'HOTEL_DDC_SALES_RANKING_LEVEL') \
	.withColumnRenamed(SQ_Shortcut_to_SALES_RANKING_WK_PRE.columns[40],'CONSUMABLES_52WK_SALES_AMT') \
	.withColumnRenamed(SQ_Shortcut_to_SALES_RANKING_WK_PRE.columns[41],'CONSUMABLES_52WK_COMP_STORES_AMT') \
	.withColumnRenamed(SQ_Shortcut_to_SALES_RANKING_WK_PRE.columns[42],'STORE_CONSUMABLES_SALES_PCT') \
	.withColumnRenamed(SQ_Shortcut_to_SALES_RANKING_WK_PRE.columns[43],'RUNNING_SUM_CONSUMABLES_SALES_PCT') \
	.withColumnRenamed(SQ_Shortcut_to_SALES_RANKING_WK_PRE.columns[44],'CONSUMABLES_SALES_RANKING_CD') \
	.withColumnRenamed(SQ_Shortcut_to_SALES_RANKING_WK_PRE.columns[45],'CONSUMABLES_SALES_RANKING_LEVEL') \
	.withColumnRenamed(SQ_Shortcut_to_SALES_RANKING_WK_PRE.columns[46],'HARDGOODS_52WK_SALES_AMT') \
	.withColumnRenamed(SQ_Shortcut_to_SALES_RANKING_WK_PRE.columns[47],'HARDGOODS_52WK_COMP_STORES_AMT') \
	.withColumnRenamed(SQ_Shortcut_to_SALES_RANKING_WK_PRE.columns[48],'STORE_HARDGOODS_SALES_PCT') \
	.withColumnRenamed(SQ_Shortcut_to_SALES_RANKING_WK_PRE.columns[49],'RUNNING_SUM_HARDGOODS_SALES_PCT') \
	.withColumnRenamed(SQ_Shortcut_to_SALES_RANKING_WK_PRE.columns[50],'HARDGOODS_SALES_RANKING_CD') \
	.withColumnRenamed(SQ_Shortcut_to_SALES_RANKING_WK_PRE.columns[51],'HARDGOODS_SALES_RANKING_LEVEL') \
	.withColumnRenamed(SQ_Shortcut_to_SALES_RANKING_WK_PRE.columns[52],'SPECIALTY_52WK_SALES_AMT') \
	.withColumnRenamed(SQ_Shortcut_to_SALES_RANKING_WK_PRE.columns[53],'SPECIALTY_52WK_COMP_STORES_AMT') \
	.withColumnRenamed(SQ_Shortcut_to_SALES_RANKING_WK_PRE.columns[54],'STORE_SPECIALTY_SALES_PCT') \
	.withColumnRenamed(SQ_Shortcut_to_SALES_RANKING_WK_PRE.columns[55],'RUNNING_SUM_SPECIALTY_SALES_PCT') \
	.withColumnRenamed(SQ_Shortcut_to_SALES_RANKING_WK_PRE.columns[56],'SPECIALTY_SALES_RANKING_CD') \
	.withColumnRenamed(SQ_Shortcut_to_SALES_RANKING_WK_PRE.columns[57],'SPECIALTY_SALES_RANKING_LEVEL')

# COMMAND ----------

# Processing node EXP_LOAD_DATES, type EXPRESSION 
# COLUMN COUNT: 60

# for each involved DataFrame, append the dataframe name to each column
SQ_Shortcut_to_SALES_RANKING_WK_PRE_temp = SQ_Shortcut_to_SALES_RANKING_WK_PRE.toDF(*["SQ_Shortcut_to_SALES_RANKING_WK_PRE___" + col for col in SQ_Shortcut_to_SALES_RANKING_WK_PRE.columns])

EXP_LOAD_DATES = SQ_Shortcut_to_SALES_RANKING_WK_PRE_temp.selectExpr(
	"SQ_Shortcut_to_SALES_RANKING_WK_PRE___sys_row_id as sys_row_id",
	"SQ_Shortcut_to_SALES_RANKING_WK_PRE___WEEK_DT as WEEK_DT",
	"SQ_Shortcut_to_SALES_RANKING_WK_PRE___LOCATION_ID as LOCATION_ID",
	"SQ_Shortcut_to_SALES_RANKING_WK_PRE___COMP_CURR_FLAG as COMP_CURR_FLAG",
	"SQ_Shortcut_to_SALES_RANKING_WK_PRE___SALES_CURR_FLAG as SALES_CURR_FLAG",
	"SQ_Shortcut_to_SALES_RANKING_WK_PRE___TOTAL_52WK_SALES_AMT as TOTAL_52WK_SALES_AMT",
	"SQ_Shortcut_to_SALES_RANKING_WK_PRE___TOTAL_52WK_COMP_STORES_AMT as TOTAL_52WK_COMP_STORES_AMT",
	"SQ_Shortcut_to_SALES_RANKING_WK_PRE___STORE_TOTAL_SALES_PCT as STORE_TOTAL_SALES_PCT",
	"SQ_Shortcut_to_SALES_RANKING_WK_PRE___RUNNING_SUM_TOTAL_SALES_PCT as RUNNING_SUM_TOTAL_SALES_PCT",
	"SQ_Shortcut_to_SALES_RANKING_WK_PRE___TOTAL_SALES_RANKING_CD as TOTAL_SALES_RANKING_CD",
	"SQ_Shortcut_to_SALES_RANKING_WK_PRE___TOTAL_SALES_RANKING_LEVEL as TOTAL_SALES_RANKING_LEVEL",
	"SQ_Shortcut_to_SALES_RANKING_WK_PRE___MERCH_52WK_SALES_AMT as MERCH_52WK_SALES_AMT",
	"SQ_Shortcut_to_SALES_RANKING_WK_PRE___MERCH_52WK_COMP_STORES_AMT as MERCH_52WK_COMP_STORES_AMT",
	"SQ_Shortcut_to_SALES_RANKING_WK_PRE___STORE_MERCH_SALES_PCT as STORE_MERCH_SALES_PCT",
	"SQ_Shortcut_to_SALES_RANKING_WK_PRE___RUNNING_SUM_MERCH_SALES_PCT as RUNNING_SUM_MERCH_SALES_PCT",
	"SQ_Shortcut_to_SALES_RANKING_WK_PRE___MERCH_SALES_RANKING_CD as MERCH_SALES_RANKING_CD",
	"SQ_Shortcut_to_SALES_RANKING_WK_PRE___MERCH_SALES_RANKING_LEVEL as MERCH_SALES_RANKING_LEVEL",
	"SQ_Shortcut_to_SALES_RANKING_WK_PRE___SERVICES_52WK_SALES_AMT as SERVICES_52WK_SALES_AMT",
	"SQ_Shortcut_to_SALES_RANKING_WK_PRE___SERVICES_52WK_COMP_STORES_AMT as SERVICES_52WK_COMP_STORES_AMT",
	"SQ_Shortcut_to_SALES_RANKING_WK_PRE___STORE_SERVICES_SALES_PCT as STORE_SERVICES_SALES_PCT",
	"SQ_Shortcut_to_SALES_RANKING_WK_PRE___RUNNING_SUM_SERVICES_SALES_PCT as RUNNING_SUM_SERVICES_SALES_PCT",
	"SQ_Shortcut_to_SALES_RANKING_WK_PRE___SERVICES_SALES_RANKING_CD as SERVICES_SALES_RANKING_CD",
	"SQ_Shortcut_to_SALES_RANKING_WK_PRE___SERVICES_SALES_RANKING_LEVEL as SERVICES_SALES_RANKING_LEVEL",
	"SQ_Shortcut_to_SALES_RANKING_WK_PRE___SALON_52WK_SALES_AMT as SALON_52WK_SALES_AMT",
	"SQ_Shortcut_to_SALES_RANKING_WK_PRE___SALON_52WK_COMP_STORES_AMT as SALON_52WK_COMP_STORES_AMT",
	"SQ_Shortcut_to_SALES_RANKING_WK_PRE___STORE_SALON_SALES_PCT as STORE_SALON_SALES_PCT",
	"SQ_Shortcut_to_SALES_RANKING_WK_PRE___RUNNING_SUM_SALON_SALES_PCT as RUNNING_SUM_SALON_SALES_PCT",
	"SQ_Shortcut_to_SALES_RANKING_WK_PRE___SALON_SALES_RANKING_CD as SALON_SALES_RANKING_CD",
	"SQ_Shortcut_to_SALES_RANKING_WK_PRE___SALON_SALES_RANKING_LEVEL as SALON_SALES_RANKING_LEVEL",
	"SQ_Shortcut_to_SALES_RANKING_WK_PRE___TRAINING_52WK_SALES_AMT as TRAINING_52WK_SALES_AMT",
	"SQ_Shortcut_to_SALES_RANKING_WK_PRE___TRAINING_52WK_COMP_STORES_AMT as TRAINING_52WK_COMP_STORES_AMT",
	"SQ_Shortcut_to_SALES_RANKING_WK_PRE___STORE_TRAINING_SALES_PCT as STORE_TRAINING_SALES_PCT",
	"SQ_Shortcut_to_SALES_RANKING_WK_PRE___RUNNING_SUM_TRAINING_SALES_PCT as RUNNING_SUM_TRAINING_SALES_PCT",
	"SQ_Shortcut_to_SALES_RANKING_WK_PRE___TRAINING_SALES_RANKING_CD as TRAINING_SALES_RANKING_CD",
	"SQ_Shortcut_to_SALES_RANKING_WK_PRE___TRAINING_SALES_RANKING_LEVEL as TRAINING_SALES_RANKING_LEVEL",
	"SQ_Shortcut_to_SALES_RANKING_WK_PRE___HOTEL_DDC_52WK_SALES_AMT as HOTEL_DDC_52WK_SALES_AMT",
	"SQ_Shortcut_to_SALES_RANKING_WK_PRE___HOTEL_DDC_52WK_COMP_STORES_AMT as HOTEL_DDC_52WK_COMP_STORES_AMT",
	"SQ_Shortcut_to_SALES_RANKING_WK_PRE___STORE_HOTEL_DDC_SALES_PCT as STORE_HOTEL_DDC_SALES_PCT",
	"SQ_Shortcut_to_SALES_RANKING_WK_PRE___RUNNING_SUM_HOTEL_DDC_SALES_PCT as RUNNING_SUM_HOTEL_DDC_SALES_PCT",
	"SQ_Shortcut_to_SALES_RANKING_WK_PRE___HOTEL_DDC_SALES_RANKING_CD as HOTEL_DDC_SALES_RANKING_CD",
	"SQ_Shortcut_to_SALES_RANKING_WK_PRE___HOTEL_DDC_SALES_RANKING_LEVEL as HOTEL_DDC_SALES_RANKING_LEVEL",
	"SQ_Shortcut_to_SALES_RANKING_WK_PRE___CONSUMABLES_52WK_SALES_AMT as CONSUMABLES_52WK_SALES_AMT",
	"SQ_Shortcut_to_SALES_RANKING_WK_PRE___CONSUMABLES_52WK_COMP_STORES_AMT as CONSUMABLES_52WK_COMP_STORES_AMT",
	"SQ_Shortcut_to_SALES_RANKING_WK_PRE___STORE_CONSUMABLES_SALES_PCT as STORE_CONSUMABLES_SALES_PCT",
	"SQ_Shortcut_to_SALES_RANKING_WK_PRE___RUNNING_SUM_CONSUMABLES_SALES_PCT as RUNNING_SUM_CONSUMABLES_SALES_PCT",
	"SQ_Shortcut_to_SALES_RANKING_WK_PRE___CONSUMABLES_SALES_RANKING_CD as CONSUMABLES_SALES_RANKING_CD",
	"SQ_Shortcut_to_SALES_RANKING_WK_PRE___CONSUMABLES_SALES_RANKING_LEVEL as CONSUMABLES_SALES_RANKING_LEVEL",
	"SQ_Shortcut_to_SALES_RANKING_WK_PRE___HARDGOODS_52WK_SALES_AMT as HARDGOODS_52WK_SALES_AMT",
	"SQ_Shortcut_to_SALES_RANKING_WK_PRE___HARDGOODS_52WK_COMP_STORES_AMT as HARDGOODS_52WK_COMP_STORES_AMT",
	"SQ_Shortcut_to_SALES_RANKING_WK_PRE___STORE_HARDGOODS_SALES_PCT as STORE_HARDGOODS_SALES_PCT",
	"SQ_Shortcut_to_SALES_RANKING_WK_PRE___RUNNING_SUM_HARDGOODS_SALES_PCT as RUNNING_SUM_HARDGOODS_SALES_PCT",
	"SQ_Shortcut_to_SALES_RANKING_WK_PRE___HARDGOODS_SALES_RANKING_CD as HARDGOODS_SALES_RANKING_CD",
	"SQ_Shortcut_to_SALES_RANKING_WK_PRE___HARDGOODS_SALES_RANKING_LEVEL as HARDGOODS_SALES_RANKING_LEVEL",
	"SQ_Shortcut_to_SALES_RANKING_WK_PRE___SPECIALTY_52WK_SALES_AMT as SPECIALTY_52WK_SALES_AMT",
	"SQ_Shortcut_to_SALES_RANKING_WK_PRE___SPECIALTY_52WK_COMP_STORES_AMT as SPECIALTY_52WK_COMP_STORES_AMT",
	"SQ_Shortcut_to_SALES_RANKING_WK_PRE___STORE_SPECIALTY_SALES_PCT as STORE_SPECIALTY_SALES_PCT",
	"SQ_Shortcut_to_SALES_RANKING_WK_PRE___RUNNING_SUM_SPECIALTY_SALES_PCT as RUNNING_SUM_SPECIALTY_SALES_PCT",
	"SQ_Shortcut_to_SALES_RANKING_WK_PRE___SPECIALTY_SALES_RANKING_CD as SPECIALTY_SALES_RANKING_CD",
	"SQ_Shortcut_to_SALES_RANKING_WK_PRE___SPECIALTY_SALES_RANKING_LEVEL as SPECIALTY_SALES_RANKING_LEVEL",
	"CURRENT_TIMESTAMP as UPDATE_TSTMP",
	"CURRENT_TIMESTAMP as LOAD_TSTMP"
)

# COMMAND ----------

# EXP_LOAD_DATES.show()

# COMMAND ----------

# Processing node Shortcut_to_SALES_RANKING_WK1, type TARGET 
# COLUMN COUNT: 60


Shortcut_to_SALES_RANKING_WK1 = EXP_LOAD_DATES.selectExpr(
	"CAST(WEEK_DT AS DATE) as WEEK_DT",
	"CAST(LOCATION_ID AS INT) as LOCATION_ID",
	"CAST(COMP_CURR_FLAG as tinyint) as COMP_CURR_FLAG",
	"CAST(SALES_CURR_FLAG as tinyint) as SALES_CURR_FLAG",
	"CAST(TOTAL_52WK_SALES_AMT AS DECIMAL(18,2)) as TOTAL_52WK_SALES_AMT",
	"CAST(TOTAL_52WK_COMP_STORES_AMT AS DECIMAL(18,2)) as TOTAL_52WK_COMP_STORES_AMT",
	"CAST(STORE_TOTAL_SALES_PCT AS DECIMAL(14,10)) as STORE_TOTAL_SALES_PCT",
	"CAST(RUNNING_SUM_TOTAL_SALES_PCT AS DECIMAL(14,10)) as RUNNING_SUM_TOTAL_SALES_PCT",
	"CAST(TOTAL_SALES_RANKING_CD AS STRING) as TOTAL_SALES_RANKING_CD",
	"CAST(TOTAL_SALES_RANKING_LEVEL as smallint) as TOTAL_SALES_RANKING_LEVEL",
	"CAST(MERCH_52WK_SALES_AMT AS DECIMAL(18,2)) as MERCH_52WK_SALES_AMT",
	"CAST(MERCH_52WK_COMP_STORES_AMT AS DECIMAL(18,2)) as MERCH_52WK_COMP_STORES_AMT",
	"CAST(STORE_MERCH_SALES_PCT AS DECIMAL(14,10)) as STORE_MERCH_SALES_PCT",
	"CAST(RUNNING_SUM_MERCH_SALES_PCT AS DECIMAL(14,10)) as RUNNING_SUM_MERCH_SALES_PCT",
	"CAST(MERCH_SALES_RANKING_CD AS STRING) as MERCH_SALES_RANKING_CD",
	"CAST(MERCH_SALES_RANKING_LEVEL as smallint) as MERCH_SALES_RANKING_LEVEL",
	"CAST(SERVICES_52WK_SALES_AMT AS DECIMAL(18,2)) as SERVICES_52WK_SALES_AMT",
	"CAST(SERVICES_52WK_COMP_STORES_AMT AS DECIMAL(18,2)) as SERVICES_52WK_COMP_STORES_AMT",
	"CAST(STORE_SERVICES_SALES_PCT AS DECIMAL(14,10)) as STORE_SERVICES_SALES_PCT",
	"CAST(RUNNING_SUM_SERVICES_SALES_PCT AS DECIMAL(14,10)) as RUNNING_SUM_SERVICES_SALES_PCT",
	"CAST(SERVICES_SALES_RANKING_CD AS STRING) as SERVICES_SALES_RANKING_CD",
	"CAST(SERVICES_SALES_RANKING_LEVEL as smallint) as SERVICES_SALES_RANKING_LEVEL",
	"CAST(SALON_52WK_SALES_AMT AS DECIMAL(18,2)) as SALON_52WK_SALES_AMT",
	"CAST(SALON_52WK_COMP_STORES_AMT AS DECIMAL(18,2)) as SALON_52WK_COMP_STORES_AMT",
	"CAST(STORE_SALON_SALES_PCT AS DECIMAL(14,10)) as STORE_SALON_SALES_PCT",
	"CAST(RUNNING_SUM_SALON_SALES_PCT AS DECIMAL(14,10)) as RUNNING_SUM_SALON_SALES_PCT",
	"CAST(SALON_SALES_RANKING_CD AS STRING) as SALON_SALES_RANKING_CD",
	"CAST(SALON_SALES_RANKING_LEVEL as smallint) as SALON_SALES_RANKING_LEVEL",
	"CAST(TRAINING_52WK_SALES_AMT AS DECIMAL(18,2)) as TRAINING_52WK_SALES_AMT",
	"CAST(TRAINING_52WK_COMP_STORES_AMT AS DECIMAL(18,2)) as TRAINING_52WK_COMP_STORES_AMT",
	"CAST(STORE_TRAINING_SALES_PCT AS DECIMAL(14,10)) as STORE_TRAINING_SALES_PCT",
	"CAST(RUNNING_SUM_TRAINING_SALES_PCT AS DECIMAL(14,10)) as RUNNING_SUM_TRAINING_SALES_PCT",
	"CAST(TRAINING_SALES_RANKING_CD AS STRING) as TRAINING_SALES_RANKING_CD",
	"CAST(TRAINING_SALES_RANKING_LEVEL as smallint) as TRAINING_SALES_RANKING_LEVEL",
	"CAST(HOTEL_DDC_52WK_SALES_AMT AS DECIMAL(18,2)) as HOTEL_DDC_52WK_SALES_AMT",
	"CAST(HOTEL_DDC_52WK_COMP_STORES_AMT AS DECIMAL(18,2)) as HOTEL_DDC_52WK_COMP_STORES_AMT",
	"CAST(STORE_HOTEL_DDC_SALES_PCT AS DECIMAL(14,10)) as STORE_HOTEL_DDC_SALES_PCT",
	"CAST(RUNNING_SUM_HOTEL_DDC_SALES_PCT AS DECIMAL(14,10)) as RUNNING_SUM_HOTEL_DDC_SALES_PCT",
	"CAST(HOTEL_DDC_SALES_RANKING_CD AS STRING) as HOTEL_DDC_SALES_RANKING_CD",
	"CAST(HOTEL_DDC_SALES_RANKING_LEVEL as smallint) as HOTEL_DDC_SALES_RANKING_LEVEL",
	"CAST(CONSUMABLES_52WK_SALES_AMT AS DECIMAL(18,2)) as CONSUMABLES_52WK_SALES_AMT",
	"CAST(CONSUMABLES_52WK_COMP_STORES_AMT AS DECIMAL(18,2)) as CONSUMABLES_52WK_COMP_STORES_AMT",
	"CAST(STORE_CONSUMABLES_SALES_PCT AS DECIMAL(14,10)) as STORE_CONSUMABLES_SALES_PCT",
	"CAST(RUNNING_SUM_CONSUMABLES_SALES_PCT AS DECIMAL(14,10)) as RUNNING_SUM_CONSUMABLES_SALES_PCT",
	"CAST(CONSUMABLES_SALES_RANKING_CD AS STRING) as CONSUMABLES_SALES_RANKING_CD",
	"CAST(CONSUMABLES_SALES_RANKING_LEVEL as smallint) as CONSUMABLES_SALES_RANKING_LEVEL",
	"CAST(HARDGOODS_52WK_SALES_AMT AS DECIMAL(18,2)) as HARDGOODS_52WK_SALES_AMT",
	"CAST(HARDGOODS_52WK_COMP_STORES_AMT AS DECIMAL(18,2)) as HARDGOODS_52WK_COMP_STORES_AMT",
	"CAST(STORE_HARDGOODS_SALES_PCT AS DECIMAL(14,10)) as STORE_HARDGOODS_SALES_PCT",
	"CAST(RUNNING_SUM_HARDGOODS_SALES_PCT AS DECIMAL(14,10)) as RUNNING_SUM_HARDGOODS_SALES_PCT",
	"CAST(HARDGOODS_SALES_RANKING_CD AS STRING) as HARDGOODS_SALES_RANKING_CD",
	"CAST(HARDGOODS_SALES_RANKING_LEVEL as smallint) as HARDGOODS_SALES_RANKING_LEVEL",
	"CAST(SPECIALTY_52WK_SALES_AMT AS DECIMAL(18,2)) as SPECIALTY_52WK_SALES_AMT",
	"CAST(SPECIALTY_52WK_COMP_STORES_AMT AS DECIMAL(18,2)) as SPECIALTY_52WK_COMP_STORES_AMT",
	"CAST(STORE_SPECIALTY_SALES_PCT AS DECIMAL(14,10)) as STORE_SPECIALTY_SALES_PCT",
	"CAST(RUNNING_SUM_SPECIALTY_SALES_PCT AS DECIMAL(14,10)) as RUNNING_SUM_SPECIALTY_SALES_PCT",
	"CAST(SPECIALTY_SALES_RANKING_CD AS STRING) as SPECIALTY_SALES_RANKING_CD",
	"CAST(SPECIALTY_SALES_RANKING_LEVEL as smallint) as SPECIALTY_SALES_RANKING_LEVEL",
	"CAST(UPDATE_TSTMP AS TIMESTAMP) as UPDATE_TSTMP",
	"CAST(LOAD_TSTMP AS TIMESTAMP) as LOAD_TSTMP"
)
try:
    # chk=DuplicateChecker()
    # chk.check_for_duplicate_primary_keys(Shortcut_to_SALES_RANKING_WK1,["WEEK_DT","LOCATION_ID"])
    Shortcut_to_SALES_RANKING_WK1.write.saveAsTable(f'{legacy}.SALES_RANKING_WK', mode = 'append')
except Exception as e:
    raise e

# COMMAND ----------
