# Databricks notebook source
from logging import *
from pyspark.dbutils import DBUtils
from pyspark.sql import *
from pyspark.sql.functions import *
from pyspark.sql.types import *
from pyspark.sql.session import SparkSession
from utils.genericUtilities import getEnvPrefix
from utils.mergeUtils import executeMerge
from utils.logger import logPrevRunDt

# COMMAND ----------
dbutils:DBUtils=dbutils
spark:SparkSession=spark

dbutils.widgets.text(name='env', defaultValue='')
env = getEnvPrefix(dbutils.widgets.get('env'))

# COMMAND ----------

pre_perf_table=f'{env}raw.WM_E_CONSOL_PERF_SMRY_PRE'
refined_perf_table=f'{env}refine.WM_E_CONSOL_PERF_SMRY'
site_profile_table=f'{env}legacy.SITE_PROFILE'
logger=getLogger()
logger.setLevel(INFO)

# COMMAND ----------

consol_perf_smry_pre_query=f"""SELECT
WM_E_CONSOL_PERF_SMRY_PRE.DC_NBR,
WM_E_CONSOL_PERF_SMRY_PRE.PERF_SMRY_TRAN_ID,
WM_E_CONSOL_PERF_SMRY_PRE.WHSE,
WM_E_CONSOL_PERF_SMRY_PRE.LOGIN_USER_ID,
WM_E_CONSOL_PERF_SMRY_PRE.JOB_FUNCTION_NAME,
WM_E_CONSOL_PERF_SMRY_PRE.SPVSR_LOGIN_USER_ID,
WM_E_CONSOL_PERF_SMRY_PRE.DEPT_CODE,
WM_E_CONSOL_PERF_SMRY_PRE.CLOCK_IN_DATE,
WM_E_CONSOL_PERF_SMRY_PRE.CLOCK_IN_STATUS,
WM_E_CONSOL_PERF_SMRY_PRE.TOTAL_SAM,
WM_E_CONSOL_PERF_SMRY_PRE.TOTAL_PAM,
WM_E_CONSOL_PERF_SMRY_PRE.TOTAL_TIME,
WM_E_CONSOL_PERF_SMRY_PRE.OSDL,
WM_E_CONSOL_PERF_SMRY_PRE.OSIL,
WM_E_CONSOL_PERF_SMRY_PRE.NSDL,
WM_E_CONSOL_PERF_SMRY_PRE.SIL,
WM_E_CONSOL_PERF_SMRY_PRE.UDIL,
WM_E_CONSOL_PERF_SMRY_PRE.UIL,
WM_E_CONSOL_PERF_SMRY_PRE.ADJ_OSDL,
WM_E_CONSOL_PERF_SMRY_PRE.ADJ_OSIL,
WM_E_CONSOL_PERF_SMRY_PRE.ADJ_UDIL,
WM_E_CONSOL_PERF_SMRY_PRE.ADJ_NSDL,
WM_E_CONSOL_PERF_SMRY_PRE.PAID_BRK,
WM_E_CONSOL_PERF_SMRY_PRE.UNPAID_BRK,
WM_E_CONSOL_PERF_SMRY_PRE.REF_OSDL,
WM_E_CONSOL_PERF_SMRY_PRE.REF_OSIL,
WM_E_CONSOL_PERF_SMRY_PRE.REF_UDIL,
WM_E_CONSOL_PERF_SMRY_PRE.REF_NSDL,
WM_E_CONSOL_PERF_SMRY_PRE.REF_ADJ_OSDL,
WM_E_CONSOL_PERF_SMRY_PRE.REF_ADJ_OSIL,
WM_E_CONSOL_PERF_SMRY_PRE.REF_ADJ_UDIL,
WM_E_CONSOL_PERF_SMRY_PRE.REF_ADJ_NSDL,
WM_E_CONSOL_PERF_SMRY_PRE.MISC_NUMBER_1,
WM_E_CONSOL_PERF_SMRY_PRE.CREATE_DATE_TIME,
WM_E_CONSOL_PERF_SMRY_PRE.MOD_DATE_TIME,
WM_E_CONSOL_PERF_SMRY_PRE.USER_ID,
WM_E_CONSOL_PERF_SMRY_PRE.MISC_1,
WM_E_CONSOL_PERF_SMRY_PRE.MISC_2,
WM_E_CONSOL_PERF_SMRY_PRE.CLOCK_OUT_DATE,
WM_E_CONSOL_PERF_SMRY_PRE.SHIFT_CODE,
WM_E_CONSOL_PERF_SMRY_PRE.EVENT_COUNT,
WM_E_CONSOL_PERF_SMRY_PRE.START_DATE_TIME,
WM_E_CONSOL_PERF_SMRY_PRE.END_DATE_TIME,
WM_E_CONSOL_PERF_SMRY_PRE.LEVEL_1,
WM_E_CONSOL_PERF_SMRY_PRE.LEVEL_2,
WM_E_CONSOL_PERF_SMRY_PRE.LEVEL_3,
WM_E_CONSOL_PERF_SMRY_PRE.LEVEL_4,
WM_E_CONSOL_PERF_SMRY_PRE.LEVEL_5,
WM_E_CONSOL_PERF_SMRY_PRE.WHSE_DATE,
WM_E_CONSOL_PERF_SMRY_PRE.OPS_CODE,
WM_E_CONSOL_PERF_SMRY_PRE.REF_SAM,
WM_E_CONSOL_PERF_SMRY_PRE.REF_PAM,
WM_E_CONSOL_PERF_SMRY_PRE.REPORT_SHIFT,
WM_E_CONSOL_PERF_SMRY_PRE.MISC_TXT_1,
WM_E_CONSOL_PERF_SMRY_PRE.MISC_TXT_2,
WM_E_CONSOL_PERF_SMRY_PRE.MISC_NUM_1,
WM_E_CONSOL_PERF_SMRY_PRE.MISC_NUM_2,
WM_E_CONSOL_PERF_SMRY_PRE.EVNT_CTGRY_1,
WM_E_CONSOL_PERF_SMRY_PRE.EVNT_CTGRY_2,
WM_E_CONSOL_PERF_SMRY_PRE.EVNT_CTGRY_3,
WM_E_CONSOL_PERF_SMRY_PRE.EVNT_CTGRY_4,
WM_E_CONSOL_PERF_SMRY_PRE.EVNT_CTGRY_5,
WM_E_CONSOL_PERF_SMRY_PRE.LABOR_COST_RATE,
WM_E_CONSOL_PERF_SMRY_PRE.PAID_OVERLAP_OSDL,
WM_E_CONSOL_PERF_SMRY_PRE.UNPAID_OVERLAP_OSDL,
WM_E_CONSOL_PERF_SMRY_PRE.PAID_OVERLAP_NSDL,
WM_E_CONSOL_PERF_SMRY_PRE.UNPAID_OVERLAP_NSDL,
WM_E_CONSOL_PERF_SMRY_PRE.PAID_OVERLAP_OSIL,
WM_E_CONSOL_PERF_SMRY_PRE.UNPAID_OVERLAP_OSIL,
WM_E_CONSOL_PERF_SMRY_PRE.PAID_OVERLAP_UDIL,
WM_E_CONSOL_PERF_SMRY_PRE.UNPAID_OVERLAP_UDIL,
WM_E_CONSOL_PERF_SMRY_PRE.VERSION_ID,
WM_E_CONSOL_PERF_SMRY_PRE.TEAM_CODE,
WM_E_CONSOL_PERF_SMRY_PRE.DEFAULT_JF_FLAG,
WM_E_CONSOL_PERF_SMRY_PRE.EMP_PERF_SMRY_ID,
WM_E_CONSOL_PERF_SMRY_PRE.TOTAL_QTY,
WM_E_CONSOL_PERF_SMRY_PRE.REF_NBR,
WM_E_CONSOL_PERF_SMRY_PRE.TEAM_BEGIN_TIME,
WM_E_CONSOL_PERF_SMRY_PRE.THRUPUT_MIN,
WM_E_CONSOL_PERF_SMRY_PRE.DISPLAY_UOM_QTY,
WM_E_CONSOL_PERF_SMRY_PRE.DISPLAY_UOM,
WM_E_CONSOL_PERF_SMRY_PRE.LOCN_GRP_ATTR,
WM_E_CONSOL_PERF_SMRY_PRE.RESOURCE_GROUP_ID,
WM_E_CONSOL_PERF_SMRY_PRE.COMP_ASSIGNMENT_ID,
WM_E_CONSOL_PERF_SMRY_PRE.REFLECTIVE_CODE,
WM_E_CONSOL_PERF_SMRY_PRE.LOAD_TSTMP
FROM """+pre_perf_table

# COMMAND ----------

SQ_Shortcut_to_WM_E_CONSOL_PERF_SMRY_PRE=spark.sql(consol_perf_smry_pre_query).withColumn("sys_row_id", monotonically_increasing_id())

logger.info('Query to extract data from'+pre_perf_table+' executed successfully')

# COMMAND ----------

consol_perf_smry_query="""SELECT
WM_E_CONSOL_PERF_SMRY.LOCATION_ID,
WM_E_CONSOL_PERF_SMRY.WM_PERF_SMRY_TRAN_ID,
WM_E_CONSOL_PERF_SMRY.WM_CREATE_TSTMP,
WM_E_CONSOL_PERF_SMRY.WM_MOD_TSTMP,
WM_E_CONSOL_PERF_SMRY.LOAD_TSTMP
FROM """+refined_perf_table+"""
WHERE WM_PERF_SMRY_TRAN_ID IN (SELECT PERF_SMRY_TRAN_ID FROM """+pre_perf_table+""")"""

# COMMAND ----------

SQ_Shortcut_to_WM_E_CONSOL_PERF_SMRY=spark.sql(consol_perf_smry_query).withColumn("sys_row_id", monotonically_increasing_id())
logger.info('Query to extract data from'+refined_perf_table+' executed successfully')

# COMMAND ----------

EXP_INT_CONV = SQ_Shortcut_to_WM_E_CONSOL_PERF_SMRY_PRE.select( \
	SQ_Shortcut_to_WM_E_CONSOL_PERF_SMRY_PRE.sys_row_id.alias('sys_row_id'), \
	SQ_Shortcut_to_WM_E_CONSOL_PERF_SMRY_PRE.DC_NBR.alias('in_DC_NBR'), \
	SQ_Shortcut_to_WM_E_CONSOL_PERF_SMRY_PRE.PERF_SMRY_TRAN_ID.alias('PERF_SMRY_TRAN_ID'), \
	SQ_Shortcut_to_WM_E_CONSOL_PERF_SMRY_PRE.WHSE.alias('WHSE'), \
	SQ_Shortcut_to_WM_E_CONSOL_PERF_SMRY_PRE.LOGIN_USER_ID.alias('LOGIN_USER_ID'), \
	SQ_Shortcut_to_WM_E_CONSOL_PERF_SMRY_PRE.JOB_FUNCTION_NAME.alias('JOB_FUNCTION_NAME'), \
	SQ_Shortcut_to_WM_E_CONSOL_PERF_SMRY_PRE.SPVSR_LOGIN_USER_ID.alias('SPVSR_LOGIN_USER_ID'), \
	SQ_Shortcut_to_WM_E_CONSOL_PERF_SMRY_PRE.DEPT_CODE.alias('DEPT_CODE'), \
	SQ_Shortcut_to_WM_E_CONSOL_PERF_SMRY_PRE.CLOCK_IN_DATE.alias('CLOCK_IN_DATE'), \
	SQ_Shortcut_to_WM_E_CONSOL_PERF_SMRY_PRE.CLOCK_IN_STATUS.alias('CLOCK_IN_STATUS'), \
	SQ_Shortcut_to_WM_E_CONSOL_PERF_SMRY_PRE.TOTAL_SAM.alias('TOTAL_SAM'), \
	SQ_Shortcut_to_WM_E_CONSOL_PERF_SMRY_PRE.TOTAL_PAM.alias('TOTAL_PAM'), \
	SQ_Shortcut_to_WM_E_CONSOL_PERF_SMRY_PRE.TOTAL_TIME.alias('TOTAL_TIME'), \
	SQ_Shortcut_to_WM_E_CONSOL_PERF_SMRY_PRE.OSDL.alias('OSDL'), \
	SQ_Shortcut_to_WM_E_CONSOL_PERF_SMRY_PRE.OSIL.alias('OSIL'), \
	SQ_Shortcut_to_WM_E_CONSOL_PERF_SMRY_PRE.NSDL.alias('NSDL'), \
	SQ_Shortcut_to_WM_E_CONSOL_PERF_SMRY_PRE.SIL.alias('SIL'), \
	SQ_Shortcut_to_WM_E_CONSOL_PERF_SMRY_PRE.UDIL.alias('UDIL'), \
	SQ_Shortcut_to_WM_E_CONSOL_PERF_SMRY_PRE.UIL.alias('UIL'), \
	SQ_Shortcut_to_WM_E_CONSOL_PERF_SMRY_PRE.ADJ_OSDL.alias('ADJ_OSDL'), \
	SQ_Shortcut_to_WM_E_CONSOL_PERF_SMRY_PRE.ADJ_OSIL.alias('ADJ_OSIL'), \
	SQ_Shortcut_to_WM_E_CONSOL_PERF_SMRY_PRE.ADJ_UDIL.alias('ADJ_UDIL'), \
	SQ_Shortcut_to_WM_E_CONSOL_PERF_SMRY_PRE.ADJ_NSDL.alias('ADJ_NSDL'), \
	SQ_Shortcut_to_WM_E_CONSOL_PERF_SMRY_PRE.PAID_BRK.alias('PAID_BRK'), \
	SQ_Shortcut_to_WM_E_CONSOL_PERF_SMRY_PRE.UNPAID_BRK.alias('UNPAID_BRK'), \
	SQ_Shortcut_to_WM_E_CONSOL_PERF_SMRY_PRE.REF_OSDL.alias('REF_OSDL'), \
	SQ_Shortcut_to_WM_E_CONSOL_PERF_SMRY_PRE.REF_OSIL.alias('REF_OSIL'), \
	SQ_Shortcut_to_WM_E_CONSOL_PERF_SMRY_PRE.REF_UDIL.alias('REF_UDIL'), \
	SQ_Shortcut_to_WM_E_CONSOL_PERF_SMRY_PRE.REF_NSDL.alias('REF_NSDL'), \
	SQ_Shortcut_to_WM_E_CONSOL_PERF_SMRY_PRE.REF_ADJ_OSDL.alias('REF_ADJ_OSDL'), \
	SQ_Shortcut_to_WM_E_CONSOL_PERF_SMRY_PRE.REF_ADJ_OSIL.alias('REF_ADJ_OSIL'), \
	SQ_Shortcut_to_WM_E_CONSOL_PERF_SMRY_PRE.REF_ADJ_UDIL.alias('REF_ADJ_UDIL'), \
	SQ_Shortcut_to_WM_E_CONSOL_PERF_SMRY_PRE.REF_ADJ_NSDL.alias('REF_ADJ_NSDL'), \
	SQ_Shortcut_to_WM_E_CONSOL_PERF_SMRY_PRE.MISC_NUMBER_1.alias('MISC_NUMBER_1'), \
	SQ_Shortcut_to_WM_E_CONSOL_PERF_SMRY_PRE.CREATE_DATE_TIME.alias('CREATE_DATE_TIME'), \
	SQ_Shortcut_to_WM_E_CONSOL_PERF_SMRY_PRE.MOD_DATE_TIME.alias('MOD_DATE_TIME'), \
	SQ_Shortcut_to_WM_E_CONSOL_PERF_SMRY_PRE.USER_ID.alias('USER_ID'), \
	SQ_Shortcut_to_WM_E_CONSOL_PERF_SMRY_PRE.MISC_1.alias('MISC_1'), \
	SQ_Shortcut_to_WM_E_CONSOL_PERF_SMRY_PRE.MISC_2.alias('MISC_2'), \
	SQ_Shortcut_to_WM_E_CONSOL_PERF_SMRY_PRE.CLOCK_OUT_DATE.alias('CLOCK_OUT_DATE'), \
	SQ_Shortcut_to_WM_E_CONSOL_PERF_SMRY_PRE.SHIFT_CODE.alias('SHIFT_CODE'), \
	SQ_Shortcut_to_WM_E_CONSOL_PERF_SMRY_PRE.EVENT_COUNT.alias('EVENT_COUNT'), \
	SQ_Shortcut_to_WM_E_CONSOL_PERF_SMRY_PRE.START_DATE_TIME.alias('START_DATE_TIME'), \
	SQ_Shortcut_to_WM_E_CONSOL_PERF_SMRY_PRE.END_DATE_TIME.alias('END_DATE_TIME'), \
	SQ_Shortcut_to_WM_E_CONSOL_PERF_SMRY_PRE.LEVEL_1.alias('LEVEL_1'), \
	SQ_Shortcut_to_WM_E_CONSOL_PERF_SMRY_PRE.LEVEL_2.alias('LEVEL_2'), \
	SQ_Shortcut_to_WM_E_CONSOL_PERF_SMRY_PRE.LEVEL_3.alias('LEVEL_3'), \
	SQ_Shortcut_to_WM_E_CONSOL_PERF_SMRY_PRE.LEVEL_4.alias('LEVEL_4'), \
	SQ_Shortcut_to_WM_E_CONSOL_PERF_SMRY_PRE.LEVEL_5.alias('LEVEL_5'), \
	SQ_Shortcut_to_WM_E_CONSOL_PERF_SMRY_PRE.WHSE_DATE.alias('WHSE_DATE'), \
	SQ_Shortcut_to_WM_E_CONSOL_PERF_SMRY_PRE.OPS_CODE.alias('OPS_CODE'), \
	SQ_Shortcut_to_WM_E_CONSOL_PERF_SMRY_PRE.REF_SAM.alias('REF_SAM'), \
	SQ_Shortcut_to_WM_E_CONSOL_PERF_SMRY_PRE.REF_PAM.alias('REF_PAM'), \
	SQ_Shortcut_to_WM_E_CONSOL_PERF_SMRY_PRE.REPORT_SHIFT.alias('REPORT_SHIFT'), \
	SQ_Shortcut_to_WM_E_CONSOL_PERF_SMRY_PRE.MISC_TXT_1.alias('MISC_TXT_1'), \
	SQ_Shortcut_to_WM_E_CONSOL_PERF_SMRY_PRE.MISC_TXT_2.alias('MISC_TXT_2'), \
	SQ_Shortcut_to_WM_E_CONSOL_PERF_SMRY_PRE.MISC_NUM_1.alias('MISC_NUM_1'), \
	SQ_Shortcut_to_WM_E_CONSOL_PERF_SMRY_PRE.MISC_NUM_2.alias('MISC_NUM_2'), \
	SQ_Shortcut_to_WM_E_CONSOL_PERF_SMRY_PRE.EVNT_CTGRY_1.alias('EVNT_CTGRY_1'), \
	SQ_Shortcut_to_WM_E_CONSOL_PERF_SMRY_PRE.EVNT_CTGRY_2.alias('EVNT_CTGRY_2'), \
	SQ_Shortcut_to_WM_E_CONSOL_PERF_SMRY_PRE.EVNT_CTGRY_3.alias('EVNT_CTGRY_3'), \
	SQ_Shortcut_to_WM_E_CONSOL_PERF_SMRY_PRE.EVNT_CTGRY_4.alias('EVNT_CTGRY_4'), \
	SQ_Shortcut_to_WM_E_CONSOL_PERF_SMRY_PRE.EVNT_CTGRY_5.alias('EVNT_CTGRY_5'), \
	SQ_Shortcut_to_WM_E_CONSOL_PERF_SMRY_PRE.LABOR_COST_RATE.alias('LABOR_COST_RATE'), \
	SQ_Shortcut_to_WM_E_CONSOL_PERF_SMRY_PRE.PAID_OVERLAP_OSDL.alias('PAID_OVERLAP_OSDL'), \
	SQ_Shortcut_to_WM_E_CONSOL_PERF_SMRY_PRE.UNPAID_OVERLAP_OSDL.alias('UNPAID_OVERLAP_OSDL'), \
	SQ_Shortcut_to_WM_E_CONSOL_PERF_SMRY_PRE.PAID_OVERLAP_NSDL.alias('PAID_OVERLAP_NSDL'), \
	SQ_Shortcut_to_WM_E_CONSOL_PERF_SMRY_PRE.UNPAID_OVERLAP_NSDL.alias('UNPAID_OVERLAP_NSDL'), \
	SQ_Shortcut_to_WM_E_CONSOL_PERF_SMRY_PRE.PAID_OVERLAP_OSIL.alias('PAID_OVERLAP_OSIL'), \
	SQ_Shortcut_to_WM_E_CONSOL_PERF_SMRY_PRE.UNPAID_OVERLAP_OSIL.alias('UNPAID_OVERLAP_OSIL'), \
	SQ_Shortcut_to_WM_E_CONSOL_PERF_SMRY_PRE.PAID_OVERLAP_UDIL.alias('PAID_OVERLAP_UDIL'), \
	SQ_Shortcut_to_WM_E_CONSOL_PERF_SMRY_PRE.UNPAID_OVERLAP_UDIL.alias('UNPAID_OVERLAP_UDIL'), \
	SQ_Shortcut_to_WM_E_CONSOL_PERF_SMRY_PRE.VERSION_ID.alias('VERSION_ID'), \
	SQ_Shortcut_to_WM_E_CONSOL_PERF_SMRY_PRE.TEAM_CODE.alias('TEAM_CODE'), \
	SQ_Shortcut_to_WM_E_CONSOL_PERF_SMRY_PRE.DEFAULT_JF_FLAG.alias('DEFAULT_JF_FLAG'), \
	SQ_Shortcut_to_WM_E_CONSOL_PERF_SMRY_PRE.EMP_PERF_SMRY_ID.alias('EMP_PERF_SMRY_ID'), \
	SQ_Shortcut_to_WM_E_CONSOL_PERF_SMRY_PRE.TOTAL_QTY.alias('TOTAL_QTY'), \
	SQ_Shortcut_to_WM_E_CONSOL_PERF_SMRY_PRE.REF_NBR.alias('REF_NBR'), \
	SQ_Shortcut_to_WM_E_CONSOL_PERF_SMRY_PRE.TEAM_BEGIN_TIME.alias('TEAM_BEGIN_TIME'), \
	SQ_Shortcut_to_WM_E_CONSOL_PERF_SMRY_PRE.THRUPUT_MIN.alias('THRUPUT_MIN'), \
	SQ_Shortcut_to_WM_E_CONSOL_PERF_SMRY_PRE.DISPLAY_UOM_QTY.alias('DISPLAY_UOM_QTY'), \
	SQ_Shortcut_to_WM_E_CONSOL_PERF_SMRY_PRE.DISPLAY_UOM.alias('DISPLAY_UOM'), \
	SQ_Shortcut_to_WM_E_CONSOL_PERF_SMRY_PRE.LOCN_GRP_ATTR.alias('LOCN_GRP_ATTR'), \
	SQ_Shortcut_to_WM_E_CONSOL_PERF_SMRY_PRE.RESOURCE_GROUP_ID.alias('RESOURCE_GROUP_ID'), \
	SQ_Shortcut_to_WM_E_CONSOL_PERF_SMRY_PRE.COMP_ASSIGNMENT_ID.alias('COMP_ASSIGNMENT_ID'), \
	SQ_Shortcut_to_WM_E_CONSOL_PERF_SMRY_PRE.REFLECTIVE_CODE.alias('REFLECTIVE_CODE'), \
	SQ_Shortcut_to_WM_E_CONSOL_PERF_SMRY_PRE.LOAD_TSTMP.alias('LOAD_TSTMP')).select( \
	(col('sys_row_id')).alias('sys_row_id'), \
	(col('in_DC_NBR').cast(DecimalType(3,0))).alias('DC_NBR'), \
	col('PERF_SMRY_TRAN_ID'), \
	col('WHSE'), \
	col('LOGIN_USER_ID'), \
	col('JOB_FUNCTION_NAME'), \
	col('SPVSR_LOGIN_USER_ID'), \
	col('DEPT_CODE'), \
	col('CLOCK_IN_DATE'), \
	col('CLOCK_IN_STATUS'), \
	col('TOTAL_SAM'), \
	col('TOTAL_PAM'), \
	col('TOTAL_TIME'), \
	col('OSDL'), \
	col('OSIL'), \
	col('NSDL'), \
	col('SIL'), \
	col('UDIL'), \
	col('UIL'), \
	col('ADJ_OSDL'), \
	col('ADJ_OSIL'), \
	col('ADJ_UDIL'), \
	col('ADJ_NSDL'), \
	col('PAID_BRK'), \
	col('UNPAID_BRK'), \
	col('REF_OSDL'), \
	col('REF_OSIL'), \
	col('REF_UDIL'), \
	col('REF_NSDL'), \
	col('REF_ADJ_OSDL'), \
	col('REF_ADJ_OSIL'), \
	col('REF_ADJ_UDIL'), \
	col('REF_ADJ_NSDL'), \
	col('MISC_NUMBER_1'), \
	col('CREATE_DATE_TIME'), \
	col('MOD_DATE_TIME'), \
	col('USER_ID'), \
	col('MISC_1'), \
	col('MISC_2'), \
	col('CLOCK_OUT_DATE'), \
	col('SHIFT_CODE'), \
	col('EVENT_COUNT'), \
	col('START_DATE_TIME'), \
	col('END_DATE_TIME'), \
	col('LEVEL_1'), \
	col('LEVEL_2'), \
	col('LEVEL_3'), \
	col('LEVEL_4'), \
	col('LEVEL_5'), \
	col('WHSE_DATE'), \
	col('OPS_CODE'), \
	col('REF_SAM'), \
	col('REF_PAM'), \
	col('REPORT_SHIFT'), \
	col('MISC_TXT_1'), \
	col('MISC_TXT_2'), \
	col('MISC_NUM_1'), \
	col('MISC_NUM_2'), \
	col('EVNT_CTGRY_1'), \
	col('EVNT_CTGRY_2'), \
	col('EVNT_CTGRY_3'), \
	col('EVNT_CTGRY_4'), \
	col('EVNT_CTGRY_5'), \
	col('LABOR_COST_RATE'), \
	col('PAID_OVERLAP_OSDL'), \
	col('UNPAID_OVERLAP_OSDL'), \
	col('PAID_OVERLAP_NSDL'), \
	col('UNPAID_OVERLAP_NSDL'), \
	col('PAID_OVERLAP_OSIL'), \
	col('UNPAID_OVERLAP_OSIL'), \
	col('PAID_OVERLAP_UDIL'), \
	col('UNPAID_OVERLAP_UDIL'), \
	col('VERSION_ID'), \
	col('TEAM_CODE'), \
	col('DEFAULT_JF_FLAG'), \
	col('EMP_PERF_SMRY_ID'), \
	col('TOTAL_QTY'), \
	col('REF_NBR'), \
	col('TEAM_BEGIN_TIME'), \
	col('THRUPUT_MIN'), \
	col('DISPLAY_UOM_QTY'), \
	col('DISPLAY_UOM'), \
	col('LOCN_GRP_ATTR'), \
	col('RESOURCE_GROUP_ID'), \
	col('COMP_ASSIGNMENT_ID'), \
	col('REFLECTIVE_CODE'), \
	col('LOAD_TSTMP') \
)
logger.info('EXP_INT_CONV dataframe created successfully')

# COMMAND ----------

site_profile_query="""SELECT
SITE_PROFILE.LOCATION_ID,
SITE_PROFILE.STORE_NBR
FROM """+site_profile_table

# COMMAND ----------

SQ_Shortcut_to_SITE_PROFILE = spark.sql(site_profile_query).withColumn("sys_row_id", monotonically_increasing_id())
logger.info('Site profile table query executed successfully!')

# COMMAND ----------

JNR_SITE_PROFILE = SQ_Shortcut_to_SITE_PROFILE.join(EXP_INT_CONV,[SQ_Shortcut_to_SITE_PROFILE.STORE_NBR == EXP_INT_CONV.DC_NBR],'inner')
logger.info('JNR_SITE_PROFILE dataframe created successfully')

# COMMAND ----------

JNR_WM_E_CON_PERF_SMRY = SQ_Shortcut_to_WM_E_CONSOL_PERF_SMRY.join(JNR_SITE_PROFILE,[SQ_Shortcut_to_WM_E_CONSOL_PERF_SMRY.LOCATION_ID == JNR_SITE_PROFILE.LOCATION_ID, SQ_Shortcut_to_WM_E_CONSOL_PERF_SMRY.WM_PERF_SMRY_TRAN_ID == JNR_SITE_PROFILE.PERF_SMRY_TRAN_ID],'right_outer').select( \
	SQ_Shortcut_to_WM_E_CONSOL_PERF_SMRY.sys_row_id.alias('sys_row_id'), \
	JNR_SITE_PROFILE.LOCATION_ID.alias('LOCATION_ID'), \
	JNR_SITE_PROFILE.PERF_SMRY_TRAN_ID.alias('PERF_SMRY_TRAN_ID'), \
	JNR_SITE_PROFILE.WHSE.alias('WHSE'), \
	JNR_SITE_PROFILE.LOGIN_USER_ID.alias('LOGIN_USER_ID'), \
	JNR_SITE_PROFILE.JOB_FUNCTION_NAME.alias('JOB_FUNCTION_NAME'), \
	JNR_SITE_PROFILE.SPVSR_LOGIN_USER_ID.alias('SPVSR_LOGIN_USER_ID'), \
	JNR_SITE_PROFILE.DEPT_CODE.alias('DEPT_CODE'), \
	JNR_SITE_PROFILE.CLOCK_IN_DATE.alias('CLOCK_IN_DATE'), \
	JNR_SITE_PROFILE.CLOCK_IN_STATUS.alias('CLOCK_IN_STATUS'), \
	JNR_SITE_PROFILE.TOTAL_SAM.alias('TOTAL_SAM'), \
	JNR_SITE_PROFILE.TOTAL_PAM.alias('TOTAL_PAM'), \
	JNR_SITE_PROFILE.TOTAL_TIME.alias('TOTAL_TIME'), \
	JNR_SITE_PROFILE.OSDL.alias('OSDL'), \
	JNR_SITE_PROFILE.OSIL.alias('OSIL'), \
	JNR_SITE_PROFILE.NSDL.alias('NSDL'), \
	JNR_SITE_PROFILE.SIL.alias('SIL'), \
	JNR_SITE_PROFILE.UDIL.alias('UDIL'), \
	JNR_SITE_PROFILE.UIL.alias('UIL'), \
	JNR_SITE_PROFILE.ADJ_OSDL.alias('ADJ_OSDL'), \
	JNR_SITE_PROFILE.ADJ_OSIL.alias('ADJ_OSIL'), \
	JNR_SITE_PROFILE.ADJ_UDIL.alias('ADJ_UDIL'), \
	JNR_SITE_PROFILE.ADJ_NSDL.alias('ADJ_NSDL'), \
	JNR_SITE_PROFILE.PAID_BRK.alias('PAID_BRK'), \
	JNR_SITE_PROFILE.UNPAID_BRK.alias('UNPAID_BRK'), \
	JNR_SITE_PROFILE.REF_OSDL.alias('REF_OSDL'), \
	JNR_SITE_PROFILE.REF_OSIL.alias('REF_OSIL'), \
	JNR_SITE_PROFILE.REF_UDIL.alias('REF_UDIL'), \
	JNR_SITE_PROFILE.REF_NSDL.alias('REF_NSDL'), \
	JNR_SITE_PROFILE.REF_ADJ_OSDL.alias('REF_ADJ_OSDL'), \
	JNR_SITE_PROFILE.REF_ADJ_OSIL.alias('REF_ADJ_OSIL'), \
	JNR_SITE_PROFILE.REF_ADJ_UDIL.alias('REF_ADJ_UDIL'), \
	JNR_SITE_PROFILE.REF_ADJ_NSDL.alias('REF_ADJ_NSDL'), \
	JNR_SITE_PROFILE.MISC_NUMBER_1.alias('MISC_NUMBER_1'), \
	JNR_SITE_PROFILE.CREATE_DATE_TIME.alias('CREATE_DATE_TIME'), \
	JNR_SITE_PROFILE.MOD_DATE_TIME.alias('MOD_DATE_TIME'), \
	JNR_SITE_PROFILE.USER_ID.alias('USER_ID'), \
	JNR_SITE_PROFILE.MISC_1.alias('MISC_1'), \
	JNR_SITE_PROFILE.MISC_2.alias('MISC_2'), \
	JNR_SITE_PROFILE.CLOCK_OUT_DATE.alias('CLOCK_OUT_DATE'), \
	JNR_SITE_PROFILE.SHIFT_CODE.alias('SHIFT_CODE'), \
	JNR_SITE_PROFILE.EVENT_COUNT.alias('EVENT_COUNT'), \
	JNR_SITE_PROFILE.START_DATE_TIME.alias('START_DATE_TIME'), \
	JNR_SITE_PROFILE.END_DATE_TIME.alias('END_DATE_TIME'), \
	JNR_SITE_PROFILE.LEVEL_1.alias('LEVEL_1'), \
	JNR_SITE_PROFILE.LEVEL_2.alias('LEVEL_2'), \
	JNR_SITE_PROFILE.LEVEL_3.alias('LEVEL_3'), \
	JNR_SITE_PROFILE.LEVEL_4.alias('LEVEL_4'), \
	JNR_SITE_PROFILE.LEVEL_5.alias('LEVEL_5'), \
	JNR_SITE_PROFILE.WHSE_DATE.alias('WHSE_DATE'), \
	JNR_SITE_PROFILE.OPS_CODE.alias('OPS_CODE'), \
	JNR_SITE_PROFILE.REF_SAM.alias('REF_SAM'), \
	JNR_SITE_PROFILE.REF_PAM.alias('REF_PAM'), \
	JNR_SITE_PROFILE.REPORT_SHIFT.alias('REPORT_SHIFT'), \
	JNR_SITE_PROFILE.MISC_TXT_1.alias('MISC_TXT_1'), \
	JNR_SITE_PROFILE.MISC_TXT_2.alias('MISC_TXT_2'), \
	JNR_SITE_PROFILE.MISC_NUM_1.alias('MISC_NUM_1'), \
	JNR_SITE_PROFILE.MISC_NUM_2.alias('MISC_NUM_2'), \
	JNR_SITE_PROFILE.EVNT_CTGRY_1.alias('EVNT_CTGRY_1'), \
	JNR_SITE_PROFILE.EVNT_CTGRY_2.alias('EVNT_CTGRY_2'), \
	JNR_SITE_PROFILE.EVNT_CTGRY_3.alias('EVNT_CTGRY_3'), \
	JNR_SITE_PROFILE.EVNT_CTGRY_4.alias('EVNT_CTGRY_4'), \
	JNR_SITE_PROFILE.EVNT_CTGRY_5.alias('EVNT_CTGRY_5'), \
	JNR_SITE_PROFILE.LABOR_COST_RATE.alias('LABOR_COST_RATE'), \
	JNR_SITE_PROFILE.PAID_OVERLAP_OSDL.alias('PAID_OVERLAP_OSDL'), \
	JNR_SITE_PROFILE.UNPAID_OVERLAP_OSDL.alias('UNPAID_OVERLAP_OSDL'), \
	JNR_SITE_PROFILE.PAID_OVERLAP_NSDL.alias('PAID_OVERLAP_NSDL'), \
	JNR_SITE_PROFILE.UNPAID_OVERLAP_NSDL.alias('UNPAID_OVERLAP_NSDL'), \
	JNR_SITE_PROFILE.PAID_OVERLAP_OSIL.alias('PAID_OVERLAP_OSIL'), \
	JNR_SITE_PROFILE.UNPAID_OVERLAP_OSIL.alias('UNPAID_OVERLAP_OSIL'), \
	JNR_SITE_PROFILE.PAID_OVERLAP_UDIL.alias('PAID_OVERLAP_UDIL'), \
	JNR_SITE_PROFILE.UNPAID_OVERLAP_UDIL.alias('UNPAID_OVERLAP_UDIL'), \
	JNR_SITE_PROFILE.VERSION_ID.alias('VERSION_ID'), \
	JNR_SITE_PROFILE.TEAM_CODE.alias('TEAM_CODE'), \
	JNR_SITE_PROFILE.DEFAULT_JF_FLAG.alias('DEFAULT_JF_FLAG'), \
	JNR_SITE_PROFILE.EMP_PERF_SMRY_ID.alias('EMP_PERF_SMRY_ID'), \
	JNR_SITE_PROFILE.TOTAL_QTY.alias('TOTAL_QTY'), \
	JNR_SITE_PROFILE.REF_NBR.alias('REF_NBR'), \
	JNR_SITE_PROFILE.TEAM_BEGIN_TIME.alias('TEAM_BEGIN_TIME'), \
	JNR_SITE_PROFILE.THRUPUT_MIN.alias('THRUPUT_MIN'), \
	JNR_SITE_PROFILE.DISPLAY_UOM_QTY.alias('DISPLAY_UOM_QTY'), \
	JNR_SITE_PROFILE.DISPLAY_UOM.alias('DISPLAY_UOM'), \
	JNR_SITE_PROFILE.LOCN_GRP_ATTR.alias('LOCN_GRP_ATTR'), \
	JNR_SITE_PROFILE.RESOURCE_GROUP_ID.alias('RESOURCE_GROUP_ID'), \
	JNR_SITE_PROFILE.COMP_ASSIGNMENT_ID.alias('COMP_ASSIGNMENT_ID'), \
	JNR_SITE_PROFILE.REFLECTIVE_CODE.alias('REFLECTIVE_CODE'), \
	SQ_Shortcut_to_WM_E_CONSOL_PERF_SMRY.LOCATION_ID.alias('in_LOCATION_ID'), \
	SQ_Shortcut_to_WM_E_CONSOL_PERF_SMRY.WM_PERF_SMRY_TRAN_ID.alias('in_WM_PERF_SMRY_TRAN_ID'), \
	SQ_Shortcut_to_WM_E_CONSOL_PERF_SMRY.LOAD_TSTMP.alias('in_LOAD_TSTMP'), \
	SQ_Shortcut_to_WM_E_CONSOL_PERF_SMRY.WM_CREATE_TSTMP.alias('in_WM_CREATE_TSTMP'), \
	SQ_Shortcut_to_WM_E_CONSOL_PERF_SMRY.WM_MOD_TSTMP.alias('in_WM_MOD_TSTMP'))


logger.info('JNR_WM_E_CON_PERF_SMRY dataframe created successfully')


FIL_NO_CHANGE_REC = JNR_WM_E_CON_PERF_SMRY.select( \
	JNR_WM_E_CON_PERF_SMRY.LOCATION_ID.alias('LOCATION_ID'), \
	JNR_WM_E_CON_PERF_SMRY.PERF_SMRY_TRAN_ID.alias('PERF_SMRY_TRAN_ID'), \
	JNR_WM_E_CON_PERF_SMRY.WHSE.alias('WHSE'), \
	JNR_WM_E_CON_PERF_SMRY.LOGIN_USER_ID.alias('LOGIN_USER_ID'), \
	JNR_WM_E_CON_PERF_SMRY.JOB_FUNCTION_NAME.alias('JOB_FUNCTION_NAME'), \
	JNR_WM_E_CON_PERF_SMRY.SPVSR_LOGIN_USER_ID.alias('SPVSR_LOGIN_USER_ID'), \
	JNR_WM_E_CON_PERF_SMRY.DEPT_CODE.alias('DEPT_CODE'), \
	JNR_WM_E_CON_PERF_SMRY.CLOCK_IN_DATE.alias('CLOCK_IN_DATE'), \
	JNR_WM_E_CON_PERF_SMRY.CLOCK_IN_STATUS.alias('CLOCK_IN_STATUS'), \
	JNR_WM_E_CON_PERF_SMRY.TOTAL_SAM.alias('TOTAL_SAM'), \
	JNR_WM_E_CON_PERF_SMRY.TOTAL_PAM.alias('TOTAL_PAM'), \
	JNR_WM_E_CON_PERF_SMRY.TOTAL_TIME.alias('TOTAL_TIME'), \
	JNR_WM_E_CON_PERF_SMRY.OSDL.alias('OSDL'), \
	JNR_WM_E_CON_PERF_SMRY.OSIL.alias('OSIL'), \
	JNR_WM_E_CON_PERF_SMRY.NSDL.alias('NSDL'), \
	JNR_WM_E_CON_PERF_SMRY.SIL.alias('SIL'), \
	JNR_WM_E_CON_PERF_SMRY.UDIL.alias('UDIL'), \
	JNR_WM_E_CON_PERF_SMRY.UIL.alias('UIL'), \
	JNR_WM_E_CON_PERF_SMRY.ADJ_OSDL.alias('ADJ_OSDL'), \
	JNR_WM_E_CON_PERF_SMRY.ADJ_OSIL.alias('ADJ_OSIL'), \
	JNR_WM_E_CON_PERF_SMRY.ADJ_UDIL.alias('ADJ_UDIL'), \
	JNR_WM_E_CON_PERF_SMRY.ADJ_NSDL.alias('ADJ_NSDL'), \
	JNR_WM_E_CON_PERF_SMRY.PAID_BRK.alias('PAID_BRK'), \
	JNR_WM_E_CON_PERF_SMRY.UNPAID_BRK.alias('UNPAID_BRK'), \
	JNR_WM_E_CON_PERF_SMRY.REF_OSDL.alias('REF_OSDL'), \
	JNR_WM_E_CON_PERF_SMRY.REF_OSIL.alias('REF_OSIL'), \
	JNR_WM_E_CON_PERF_SMRY.REF_UDIL.alias('REF_UDIL'), \
	JNR_WM_E_CON_PERF_SMRY.REF_NSDL.alias('REF_NSDL'), \
	JNR_WM_E_CON_PERF_SMRY.REF_ADJ_OSDL.alias('REF_ADJ_OSDL'), \
	JNR_WM_E_CON_PERF_SMRY.REF_ADJ_OSIL.alias('REF_ADJ_OSIL'), \
	JNR_WM_E_CON_PERF_SMRY.REF_ADJ_UDIL.alias('REF_ADJ_UDIL'), \
	JNR_WM_E_CON_PERF_SMRY.REF_ADJ_NSDL.alias('REF_ADJ_NSDL'), \
	JNR_WM_E_CON_PERF_SMRY.MISC_NUMBER_1.alias('MISC_NUMBER_1'), \
	JNR_WM_E_CON_PERF_SMRY.CREATE_DATE_TIME.alias('CREATE_DATE_TIME'), \
	JNR_WM_E_CON_PERF_SMRY.MOD_DATE_TIME.alias('MOD_DATE_TIME'), \
	JNR_WM_E_CON_PERF_SMRY.USER_ID.alias('USER_ID'), \
	JNR_WM_E_CON_PERF_SMRY.MISC_1.alias('MISC_1'), \
	JNR_WM_E_CON_PERF_SMRY.MISC_2.alias('MISC_2'), \
	JNR_WM_E_CON_PERF_SMRY.CLOCK_OUT_DATE.alias('CLOCK_OUT_DATE'), \
	JNR_WM_E_CON_PERF_SMRY.SHIFT_CODE.alias('SHIFT_CODE'), \
	JNR_WM_E_CON_PERF_SMRY.EVENT_COUNT.alias('EVENT_COUNT'), \
	JNR_WM_E_CON_PERF_SMRY.START_DATE_TIME.alias('START_DATE_TIME'), \
	JNR_WM_E_CON_PERF_SMRY.END_DATE_TIME.alias('END_DATE_TIME'), \
	JNR_WM_E_CON_PERF_SMRY.LEVEL_1.alias('LEVEL_1'), \
	JNR_WM_E_CON_PERF_SMRY.LEVEL_2.alias('LEVEL_2'), \
	JNR_WM_E_CON_PERF_SMRY.LEVEL_3.alias('LEVEL_3'), \
	JNR_WM_E_CON_PERF_SMRY.LEVEL_4.alias('LEVEL_4'), \
	JNR_WM_E_CON_PERF_SMRY.LEVEL_5.alias('LEVEL_5'), \
	JNR_WM_E_CON_PERF_SMRY.WHSE_DATE.alias('WHSE_DATE'), \
	JNR_WM_E_CON_PERF_SMRY.OPS_CODE.alias('OPS_CODE'), \
	JNR_WM_E_CON_PERF_SMRY.REF_SAM.alias('REF_SAM'), \
	JNR_WM_E_CON_PERF_SMRY.REF_PAM.alias('REF_PAM'), \
	JNR_WM_E_CON_PERF_SMRY.REPORT_SHIFT.alias('REPORT_SHIFT'), \
	JNR_WM_E_CON_PERF_SMRY.MISC_TXT_1.alias('MISC_TXT_1'), \
	JNR_WM_E_CON_PERF_SMRY.MISC_TXT_2.alias('MISC_TXT_2'), \
	JNR_WM_E_CON_PERF_SMRY.MISC_NUM_1.alias('MISC_NUM_1'), \
	JNR_WM_E_CON_PERF_SMRY.MISC_NUM_2.alias('MISC_NUM_2'), \
	JNR_WM_E_CON_PERF_SMRY.EVNT_CTGRY_1.alias('EVNT_CTGRY_1'), \
	JNR_WM_E_CON_PERF_SMRY.EVNT_CTGRY_2.alias('EVNT_CTGRY_2'), \
	JNR_WM_E_CON_PERF_SMRY.EVNT_CTGRY_3.alias('EVNT_CTGRY_3'), \
	JNR_WM_E_CON_PERF_SMRY.EVNT_CTGRY_4.alias('EVNT_CTGRY_4'), \
	JNR_WM_E_CON_PERF_SMRY.EVNT_CTGRY_5.alias('EVNT_CTGRY_5'), \
	JNR_WM_E_CON_PERF_SMRY.LABOR_COST_RATE.alias('LABOR_COST_RATE'), \
	JNR_WM_E_CON_PERF_SMRY.PAID_OVERLAP_OSDL.alias('PAID_OVERLAP_OSDL'), \
	JNR_WM_E_CON_PERF_SMRY.UNPAID_OVERLAP_OSDL.alias('UNPAID_OVERLAP_OSDL'), \
	JNR_WM_E_CON_PERF_SMRY.PAID_OVERLAP_NSDL.alias('PAID_OVERLAP_NSDL'), \
	JNR_WM_E_CON_PERF_SMRY.UNPAID_OVERLAP_NSDL.alias('UNPAID_OVERLAP_NSDL'), \
	JNR_WM_E_CON_PERF_SMRY.PAID_OVERLAP_OSIL.alias('PAID_OVERLAP_OSIL'), \
	JNR_WM_E_CON_PERF_SMRY.UNPAID_OVERLAP_OSIL.alias('UNPAID_OVERLAP_OSIL'), \
	JNR_WM_E_CON_PERF_SMRY.PAID_OVERLAP_UDIL.alias('PAID_OVERLAP_UDIL'), \
	JNR_WM_E_CON_PERF_SMRY.UNPAID_OVERLAP_UDIL.alias('UNPAID_OVERLAP_UDIL'), \
	JNR_WM_E_CON_PERF_SMRY.VERSION_ID.alias('VERSION_ID'), \
	JNR_WM_E_CON_PERF_SMRY.TEAM_CODE.alias('TEAM_CODE'), \
	JNR_WM_E_CON_PERF_SMRY.DEFAULT_JF_FLAG.alias('DEFAULT_JF_FLAG'), \
	JNR_WM_E_CON_PERF_SMRY.EMP_PERF_SMRY_ID.alias('EMP_PERF_SMRY_ID'), \
	JNR_WM_E_CON_PERF_SMRY.TOTAL_QTY.alias('TOTAL_QTY'), \
	JNR_WM_E_CON_PERF_SMRY.REF_NBR.alias('REF_NBR'), \
	JNR_WM_E_CON_PERF_SMRY.TEAM_BEGIN_TIME.alias('TEAM_BEGIN_TIME'), \
	JNR_WM_E_CON_PERF_SMRY.THRUPUT_MIN.alias('THRUPUT_MIN'), \
	JNR_WM_E_CON_PERF_SMRY.DISPLAY_UOM_QTY.alias('DISPLAY_UOM_QTY'), \
	JNR_WM_E_CON_PERF_SMRY.DISPLAY_UOM.alias('DISPLAY_UOM'), \
	JNR_WM_E_CON_PERF_SMRY.LOCN_GRP_ATTR.alias('LOCN_GRP_ATTR'), \
	JNR_WM_E_CON_PERF_SMRY.RESOURCE_GROUP_ID.alias('RESOURCE_GROUP_ID'), \
	JNR_WM_E_CON_PERF_SMRY.COMP_ASSIGNMENT_ID.alias('COMP_ASSIGNMENT_ID'), \
	JNR_WM_E_CON_PERF_SMRY.REFLECTIVE_CODE.alias('REFLECTIVE_CODE'), \
	JNR_WM_E_CON_PERF_SMRY.in_LOCATION_ID.alias('in_LOCATION_ID'), \
	JNR_WM_E_CON_PERF_SMRY.in_WM_PERF_SMRY_TRAN_ID.alias('in_WM_PERF_SMRY_TRAN_ID'), \
	JNR_WM_E_CON_PERF_SMRY.in_LOAD_TSTMP.alias('in_LOAD_TSTMP'), \
	JNR_WM_E_CON_PERF_SMRY.in_WM_CREATE_TSTMP.alias('in_WM_CREATE_TSTMP'), \
	JNR_WM_E_CON_PERF_SMRY.in_WM_MOD_TSTMP.alias('in_WM_MOD_TSTMP')).filter(" (in_WM_PERF_SMRY_TRAN_ID is null) OR ( NOT (in_WM_PERF_SMRY_TRAN_ID is null) AND ( ((case when CREATE_DATE_TIME is null then TO_DATE('01/01/1900','M/d/y') else CREATE_DATE_TIME end ) != (case when in_WM_CREATE_TSTMP is null then TO_DATE('01/01/1900','M/d/y') else in_WM_CREATE_TSTMP end )) or ((case when MOD_DATE_TIME is null then TO_DATE('01/01/1900','M/d/y') else MOD_DATE_TIME end )!= (case when in_WM_MOD_TSTMP is null then TO_DATE('01/01/1900','M/d/y') else in_WM_MOD_TSTMP end )) ) )").withColumn("sys_row_id", monotonically_increasing_id())

logger.info('FIL_NO_CHANGE_REC dataframe created successfully')


# COMMAND ----------

EXP_EVAL_VALUES = FIL_NO_CHANGE_REC.select( \
	FIL_NO_CHANGE_REC.sys_row_id.alias('sys_row_id'), \
	FIL_NO_CHANGE_REC.LOCATION_ID.alias('LOCATION_ID'), \
	FIL_NO_CHANGE_REC.PERF_SMRY_TRAN_ID.alias('PERF_SMRY_TRAN_ID'), \
	FIL_NO_CHANGE_REC.WHSE.alias('WHSE'), \
	FIL_NO_CHANGE_REC.LOGIN_USER_ID.alias('LOGIN_USER_ID'), \
	FIL_NO_CHANGE_REC.JOB_FUNCTION_NAME.alias('JOB_FUNCTION_NAME'), \
	FIL_NO_CHANGE_REC.SPVSR_LOGIN_USER_ID.alias('SPVSR_LOGIN_USER_ID'), \
	FIL_NO_CHANGE_REC.DEPT_CODE.alias('DEPT_CODE'), \
	FIL_NO_CHANGE_REC.CLOCK_IN_DATE.alias('CLOCK_IN_DATE'), \
	FIL_NO_CHANGE_REC.CLOCK_IN_STATUS.alias('CLOCK_IN_STATUS'), \
	FIL_NO_CHANGE_REC.TOTAL_SAM.alias('TOTAL_SAM'), \
	FIL_NO_CHANGE_REC.TOTAL_PAM.alias('TOTAL_PAM'), \
	FIL_NO_CHANGE_REC.TOTAL_TIME.alias('TOTAL_TIME'), \
	FIL_NO_CHANGE_REC.OSDL.alias('OSDL'), \
	FIL_NO_CHANGE_REC.OSIL.alias('OSIL'), \
	FIL_NO_CHANGE_REC.NSDL.alias('NSDL'), \
	FIL_NO_CHANGE_REC.SIL.alias('SIL'), \
	FIL_NO_CHANGE_REC.UDIL.alias('UDIL'), \
	FIL_NO_CHANGE_REC.UIL.alias('UIL'), \
	FIL_NO_CHANGE_REC.ADJ_OSDL.alias('ADJ_OSDL'), \
	FIL_NO_CHANGE_REC.ADJ_OSIL.alias('ADJ_OSIL'), \
	FIL_NO_CHANGE_REC.ADJ_UDIL.alias('ADJ_UDIL'), \
	FIL_NO_CHANGE_REC.ADJ_NSDL.alias('ADJ_NSDL'), \
	FIL_NO_CHANGE_REC.PAID_BRK.alias('PAID_BRK'), \
	FIL_NO_CHANGE_REC.UNPAID_BRK.alias('UNPAID_BRK'), \
	FIL_NO_CHANGE_REC.REF_OSDL.alias('REF_OSDL'), \
	FIL_NO_CHANGE_REC.REF_OSIL.alias('REF_OSIL'), \
	FIL_NO_CHANGE_REC.REF_UDIL.alias('REF_UDIL'), \
	FIL_NO_CHANGE_REC.REF_NSDL.alias('REF_NSDL'), \
	FIL_NO_CHANGE_REC.REF_ADJ_OSDL.alias('REF_ADJ_OSDL'), \
	FIL_NO_CHANGE_REC.REF_ADJ_OSIL.alias('REF_ADJ_OSIL'), \
	FIL_NO_CHANGE_REC.REF_ADJ_UDIL.alias('REF_ADJ_UDIL'), \
	FIL_NO_CHANGE_REC.REF_ADJ_NSDL.alias('REF_ADJ_NSDL'), \
	FIL_NO_CHANGE_REC.MISC_NUMBER_1.alias('MISC_NUMBER_1'), \
	FIL_NO_CHANGE_REC.CREATE_DATE_TIME.alias('CREATE_DATE_TIME'), \
	FIL_NO_CHANGE_REC.MOD_DATE_TIME.alias('MOD_DATE_TIME'), \
	FIL_NO_CHANGE_REC.USER_ID.alias('USER_ID'), \
	FIL_NO_CHANGE_REC.MISC_1.alias('MISC_1'), \
	FIL_NO_CHANGE_REC.MISC_2.alias('MISC_2'), \
	FIL_NO_CHANGE_REC.CLOCK_OUT_DATE.alias('CLOCK_OUT_DATE'), \
	FIL_NO_CHANGE_REC.SHIFT_CODE.alias('SHIFT_CODE'), \
	FIL_NO_CHANGE_REC.EVENT_COUNT.alias('EVENT_COUNT'), \
	FIL_NO_CHANGE_REC.START_DATE_TIME.alias('START_DATE_TIME'), \
	FIL_NO_CHANGE_REC.END_DATE_TIME.alias('END_DATE_TIME'), \
	FIL_NO_CHANGE_REC.LEVEL_1.alias('LEVEL_1'), \
	FIL_NO_CHANGE_REC.LEVEL_2.alias('LEVEL_2'), \
	FIL_NO_CHANGE_REC.LEVEL_3.alias('LEVEL_3'), \
	FIL_NO_CHANGE_REC.LEVEL_4.alias('LEVEL_4'), \
	FIL_NO_CHANGE_REC.LEVEL_5.alias('LEVEL_5'), \
	FIL_NO_CHANGE_REC.WHSE_DATE.alias('WHSE_DATE'), \
	FIL_NO_CHANGE_REC.OPS_CODE.alias('OPS_CODE'), \
	FIL_NO_CHANGE_REC.REF_SAM.alias('REF_SAM'), \
	FIL_NO_CHANGE_REC.REF_PAM.alias('REF_PAM'), \
	FIL_NO_CHANGE_REC.REPORT_SHIFT.alias('REPORT_SHIFT'), \
	FIL_NO_CHANGE_REC.MISC_TXT_1.alias('MISC_TXT_1'), \
	FIL_NO_CHANGE_REC.MISC_TXT_2.alias('MISC_TXT_2'), \
	FIL_NO_CHANGE_REC.MISC_NUM_1.alias('MISC_NUM_1'), \
	FIL_NO_CHANGE_REC.MISC_NUM_2.alias('MISC_NUM_2'), \
	FIL_NO_CHANGE_REC.EVNT_CTGRY_1.alias('EVNT_CTGRY_1'), \
	FIL_NO_CHANGE_REC.EVNT_CTGRY_2.alias('EVNT_CTGRY_2'), \
	FIL_NO_CHANGE_REC.EVNT_CTGRY_3.alias('EVNT_CTGRY_3'), \
	FIL_NO_CHANGE_REC.EVNT_CTGRY_4.alias('EVNT_CTGRY_4'), \
	FIL_NO_CHANGE_REC.EVNT_CTGRY_5.alias('EVNT_CTGRY_5'), \
	FIL_NO_CHANGE_REC.LABOR_COST_RATE.alias('LABOR_COST_RATE'), \
	FIL_NO_CHANGE_REC.PAID_OVERLAP_OSDL.alias('PAID_OVERLAP_OSDL'), \
	FIL_NO_CHANGE_REC.UNPAID_OVERLAP_OSDL.alias('UNPAID_OVERLAP_OSDL'), \
	FIL_NO_CHANGE_REC.PAID_OVERLAP_NSDL.alias('PAID_OVERLAP_NSDL'), \
	FIL_NO_CHANGE_REC.UNPAID_OVERLAP_NSDL.alias('UNPAID_OVERLAP_NSDL'), \
	FIL_NO_CHANGE_REC.PAID_OVERLAP_OSIL.alias('PAID_OVERLAP_OSIL'), \
	FIL_NO_CHANGE_REC.UNPAID_OVERLAP_OSIL.alias('UNPAID_OVERLAP_OSIL'), \
	FIL_NO_CHANGE_REC.PAID_OVERLAP_UDIL.alias('PAID_OVERLAP_UDIL'), \
	FIL_NO_CHANGE_REC.UNPAID_OVERLAP_UDIL.alias('UNPAID_OVERLAP_UDIL'), \
	FIL_NO_CHANGE_REC.VERSION_ID.alias('VERSION_ID'), \
	FIL_NO_CHANGE_REC.TEAM_CODE.alias('TEAM_CODE'), \
	FIL_NO_CHANGE_REC.DEFAULT_JF_FLAG.alias('DEFAULT_JF_FLAG'), \
	FIL_NO_CHANGE_REC.EMP_PERF_SMRY_ID.alias('EMP_PERF_SMRY_ID'), \
	FIL_NO_CHANGE_REC.TOTAL_QTY.alias('TOTAL_QTY'), \
	FIL_NO_CHANGE_REC.REF_NBR.alias('REF_NBR'), \
	FIL_NO_CHANGE_REC.TEAM_BEGIN_TIME.alias('TEAM_BEGIN_TIME'), \
	FIL_NO_CHANGE_REC.THRUPUT_MIN.alias('THRUPUT_MIN'), \
	FIL_NO_CHANGE_REC.DISPLAY_UOM_QTY.alias('DISPLAY_UOM_QTY'), \
	FIL_NO_CHANGE_REC.DISPLAY_UOM.alias('DISPLAY_UOM'), \
	FIL_NO_CHANGE_REC.LOCN_GRP_ATTR.alias('LOCN_GRP_ATTR'), \
	FIL_NO_CHANGE_REC.RESOURCE_GROUP_ID.alias('RESOURCE_GROUP_ID'), \
	FIL_NO_CHANGE_REC.COMP_ASSIGNMENT_ID.alias('COMP_ASSIGNMENT_ID'), \
	FIL_NO_CHANGE_REC.REFLECTIVE_CODE.alias('REFLECTIVE_CODE'), \
	FIL_NO_CHANGE_REC.in_LOAD_TSTMP.alias('in_LOAD_TSTMP'), \
	FIL_NO_CHANGE_REC.in_WM_PERF_SMRY_TRAN_ID.alias('in_WM_PERF_SMRY_TRAN_ID'), \
	FIL_NO_CHANGE_REC.in_WM_CREATE_TSTMP.alias('WM_CREATE_TSTMP'), \
	FIL_NO_CHANGE_REC.in_WM_MOD_TSTMP.alias('WM_MOD_TSTMP')).select( \
	(col('sys_row_id')).alias('sys_row_id'), \
	col('LOCATION_ID'), \
	col('PERF_SMRY_TRAN_ID'), \
	col('WHSE'), \
	col('LOGIN_USER_ID'), \
	col('JOB_FUNCTION_NAME'), \
	col('SPVSR_LOGIN_USER_ID'), \
	col('DEPT_CODE'), \
	col('CLOCK_IN_DATE'), \
	col('CLOCK_IN_STATUS'), \
	col('TOTAL_SAM'), \
	col('TOTAL_PAM'), \
	col('TOTAL_TIME'), \
	col('OSDL'), \
	col('OSIL'), \
	col('NSDL'), \
	col('SIL'), \
	col('UDIL'), \
	col('UIL'), \
	col('ADJ_OSDL'), \
	col('ADJ_OSIL'), \
	col('ADJ_UDIL'), \
	col('ADJ_NSDL'), \
	col('PAID_BRK'), \
	col('UNPAID_BRK'), \
	col('REF_OSDL'), \
	col('REF_OSIL'), \
	col('REF_UDIL'), \
	col('REF_NSDL'), \
	col('REF_ADJ_OSDL'), \
	col('REF_ADJ_OSIL'), \
	col('REF_ADJ_UDIL'), \
	col('REF_ADJ_NSDL'), \
	col('MISC_NUMBER_1'), \
	col('CREATE_DATE_TIME'), \
	col('MOD_DATE_TIME'), \
	col('USER_ID'), \
	col('MISC_1'), \
	col('MISC_2'), \
	col('CLOCK_OUT_DATE'), \
	col('SHIFT_CODE'), \
	col('EVENT_COUNT'), \
	col('START_DATE_TIME'), \
	col('END_DATE_TIME'), \
	col('LEVEL_1'), \
	col('LEVEL_2'), \
	col('LEVEL_3'), \
	col('LEVEL_4'), \
	col('LEVEL_5'), \
	col('WHSE_DATE'), \
	col('OPS_CODE'), \
	col('REF_SAM'), \
	col('REF_PAM'), \
	col('REPORT_SHIFT'), \
	col('MISC_TXT_1'), \
	col('MISC_TXT_2'), \
	col('MISC_NUM_1'), \
	col('MISC_NUM_2'), \
	col('EVNT_CTGRY_1'), \
	col('EVNT_CTGRY_2'), \
	col('EVNT_CTGRY_3'), \
	col('EVNT_CTGRY_4'), \
	col('EVNT_CTGRY_5'), \
	col('LABOR_COST_RATE'), \
	col('PAID_OVERLAP_OSDL'), \
	col('UNPAID_OVERLAP_OSDL'), \
	col('PAID_OVERLAP_NSDL'), \
	col('UNPAID_OVERLAP_NSDL'), \
	col('PAID_OVERLAP_OSIL'), \
	col('UNPAID_OVERLAP_OSIL'), \
	col('PAID_OVERLAP_UDIL'), \
	col('UNPAID_OVERLAP_UDIL'), \
	col('VERSION_ID'), \
	col('TEAM_CODE'), \
	col('DEFAULT_JF_FLAG'), \
	col('EMP_PERF_SMRY_ID'), \
	col('TOTAL_QTY'), \
	col('REF_NBR'), \
	col('TEAM_BEGIN_TIME'), \
	col('THRUPUT_MIN'), \
	col('DISPLAY_UOM_QTY'), \
	col('DISPLAY_UOM'), \
	col('LOCN_GRP_ATTR'), \
	col('RESOURCE_GROUP_ID'), \
	col('COMP_ASSIGNMENT_ID'), \
	col('REFLECTIVE_CODE'), \
	(when((col('in_LOAD_TSTMP').isNull()) ,(date_trunc('second',current_timestamp()))).otherwise(col('in_LOAD_TSTMP'))).alias('LOAD_TSTMP'), \
	(date_trunc('second',current_timestamp())).alias('UPDATE_TSTMP'), \
	col('in_WM_PERF_SMRY_TRAN_ID'), \
	col('WM_CREATE_TSTMP'), \
	col('WM_MOD_TSTMP') \
)
logger.info('EXP_EVAL_VALUES dataframe created successfully')


# COMMAND ----------

UPD_VALIDATE = EXP_EVAL_VALUES.select( \
	EXP_EVAL_VALUES.LOCATION_ID.alias('LOCATION_ID'), \
	EXP_EVAL_VALUES.PERF_SMRY_TRAN_ID.alias('PERF_SMRY_TRAN_ID'), \
	EXP_EVAL_VALUES.WHSE.alias('WHSE'), \
	EXP_EVAL_VALUES.LOGIN_USER_ID.alias('LOGIN_USER_ID'), \
	EXP_EVAL_VALUES.JOB_FUNCTION_NAME.alias('JOB_FUNCTION_NAME'), \
	EXP_EVAL_VALUES.SPVSR_LOGIN_USER_ID.alias('SPVSR_LOGIN_USER_ID'), \
	EXP_EVAL_VALUES.DEPT_CODE.alias('DEPT_CODE'), \
	EXP_EVAL_VALUES.CLOCK_IN_DATE.alias('CLOCK_IN_DATE'), \
	EXP_EVAL_VALUES.CLOCK_IN_STATUS.alias('CLOCK_IN_STATUS'), \
	EXP_EVAL_VALUES.TOTAL_SAM.alias('TOTAL_SAM'), \
	EXP_EVAL_VALUES.TOTAL_PAM.alias('TOTAL_PAM'), \
	EXP_EVAL_VALUES.TOTAL_TIME.alias('TOTAL_TIME'), \
	EXP_EVAL_VALUES.OSDL.alias('OSDL'), \
	EXP_EVAL_VALUES.OSIL.alias('OSIL'), \
	EXP_EVAL_VALUES.NSDL.alias('NSDL'), \
	EXP_EVAL_VALUES.SIL.alias('SIL'), \
	EXP_EVAL_VALUES.UDIL.alias('UDIL'), \
	EXP_EVAL_VALUES.UIL.alias('UIL'), \
	EXP_EVAL_VALUES.ADJ_OSDL.alias('ADJ_OSDL'), \
	EXP_EVAL_VALUES.ADJ_OSIL.alias('ADJ_OSIL'), \
	EXP_EVAL_VALUES.ADJ_UDIL.alias('ADJ_UDIL'), \
	EXP_EVAL_VALUES.ADJ_NSDL.alias('ADJ_NSDL'), \
	EXP_EVAL_VALUES.PAID_BRK.alias('PAID_BRK'), \
	EXP_EVAL_VALUES.UNPAID_BRK.alias('UNPAID_BRK'), \
	EXP_EVAL_VALUES.REF_OSDL.alias('REF_OSDL'), \
	EXP_EVAL_VALUES.REF_OSIL.alias('REF_OSIL'), \
	EXP_EVAL_VALUES.REF_UDIL.alias('REF_UDIL'), \
	EXP_EVAL_VALUES.REF_NSDL.alias('REF_NSDL'), \
	EXP_EVAL_VALUES.REF_ADJ_OSDL.alias('REF_ADJ_OSDL'), \
	EXP_EVAL_VALUES.REF_ADJ_OSIL.alias('REF_ADJ_OSIL'), \
	EXP_EVAL_VALUES.REF_ADJ_UDIL.alias('REF_ADJ_UDIL'), \
	EXP_EVAL_VALUES.REF_ADJ_NSDL.alias('REF_ADJ_NSDL'), \
	EXP_EVAL_VALUES.MISC_NUMBER_1.alias('MISC_NUMBER_1'), \
	EXP_EVAL_VALUES.CREATE_DATE_TIME.alias('CREATE_DATE_TIME'), \
	EXP_EVAL_VALUES.MOD_DATE_TIME.alias('MOD_DATE_TIME'), \
	EXP_EVAL_VALUES.USER_ID.alias('USER_ID'), \
	EXP_EVAL_VALUES.MISC_1.alias('MISC_1'), \
	EXP_EVAL_VALUES.MISC_2.alias('MISC_2'), \
	EXP_EVAL_VALUES.CLOCK_OUT_DATE.alias('CLOCK_OUT_DATE'), \
	EXP_EVAL_VALUES.SHIFT_CODE.alias('SHIFT_CODE'), \
	EXP_EVAL_VALUES.EVENT_COUNT.alias('EVENT_COUNT'), \
	EXP_EVAL_VALUES.START_DATE_TIME.alias('START_DATE_TIME'), \
	EXP_EVAL_VALUES.END_DATE_TIME.alias('END_DATE_TIME'), \
	EXP_EVAL_VALUES.LEVEL_1.alias('LEVEL_1'), \
	EXP_EVAL_VALUES.LEVEL_2.alias('LEVEL_2'), \
	EXP_EVAL_VALUES.LEVEL_3.alias('LEVEL_3'), \
	EXP_EVAL_VALUES.LEVEL_4.alias('LEVEL_4'), \
	EXP_EVAL_VALUES.LEVEL_5.alias('LEVEL_5'), \
	EXP_EVAL_VALUES.WHSE_DATE.alias('WHSE_DATE'), \
	EXP_EVAL_VALUES.OPS_CODE.alias('OPS_CODE'), \
	EXP_EVAL_VALUES.REF_SAM.alias('REF_SAM'), \
	EXP_EVAL_VALUES.REF_PAM.alias('REF_PAM'), \
	EXP_EVAL_VALUES.REPORT_SHIFT.alias('REPORT_SHIFT'), \
	EXP_EVAL_VALUES.MISC_TXT_1.alias('MISC_TXT_1'), \
	EXP_EVAL_VALUES.MISC_TXT_2.alias('MISC_TXT_2'), \
	EXP_EVAL_VALUES.MISC_NUM_1.alias('MISC_NUM_1'), \
	EXP_EVAL_VALUES.MISC_NUM_2.alias('MISC_NUM_2'), \
	EXP_EVAL_VALUES.EVNT_CTGRY_1.alias('EVNT_CTGRY_1'), \
	EXP_EVAL_VALUES.EVNT_CTGRY_2.alias('EVNT_CTGRY_2'), \
	EXP_EVAL_VALUES.EVNT_CTGRY_3.alias('EVNT_CTGRY_3'), \
	EXP_EVAL_VALUES.EVNT_CTGRY_4.alias('EVNT_CTGRY_4'), \
	EXP_EVAL_VALUES.EVNT_CTGRY_5.alias('EVNT_CTGRY_5'), \
	EXP_EVAL_VALUES.LABOR_COST_RATE.alias('LABOR_COST_RATE'), \
	EXP_EVAL_VALUES.PAID_OVERLAP_OSDL.alias('PAID_OVERLAP_OSDL'), \
	EXP_EVAL_VALUES.UNPAID_OVERLAP_OSDL.alias('UNPAID_OVERLAP_OSDL'), \
	EXP_EVAL_VALUES.PAID_OVERLAP_NSDL.alias('PAID_OVERLAP_NSDL'), \
	EXP_EVAL_VALUES.UNPAID_OVERLAP_NSDL.alias('UNPAID_OVERLAP_NSDL'), \
	EXP_EVAL_VALUES.PAID_OVERLAP_OSIL.alias('PAID_OVERLAP_OSIL'), \
	EXP_EVAL_VALUES.UNPAID_OVERLAP_OSIL.alias('UNPAID_OVERLAP_OSIL'), \
	EXP_EVAL_VALUES.PAID_OVERLAP_UDIL.alias('PAID_OVERLAP_UDIL'), \
	EXP_EVAL_VALUES.UNPAID_OVERLAP_UDIL.alias('UNPAID_OVERLAP_UDIL'), \
	EXP_EVAL_VALUES.VERSION_ID.alias('VERSION_ID'), \
	EXP_EVAL_VALUES.TEAM_CODE.alias('TEAM_CODE'), \
	EXP_EVAL_VALUES.DEFAULT_JF_FLAG.alias('DEFAULT_JF_FLAG'), \
	EXP_EVAL_VALUES.EMP_PERF_SMRY_ID.alias('EMP_PERF_SMRY_ID'), \
	EXP_EVAL_VALUES.TOTAL_QTY.alias('TOTAL_QTY'), \
	EXP_EVAL_VALUES.REF_NBR.alias('REF_NBR'), \
	EXP_EVAL_VALUES.TEAM_BEGIN_TIME.alias('TEAM_BEGIN_TIME'), \
	EXP_EVAL_VALUES.THRUPUT_MIN.alias('THRUPUT_MIN'), \
	EXP_EVAL_VALUES.DISPLAY_UOM_QTY.alias('DISPLAY_UOM_QTY'), \
	EXP_EVAL_VALUES.DISPLAY_UOM.alias('DISPLAY_UOM'), \
	EXP_EVAL_VALUES.LOCN_GRP_ATTR.alias('LOCN_GRP_ATTR'), \
	EXP_EVAL_VALUES.RESOURCE_GROUP_ID.alias('RESOURCE_GROUP_ID'), \
	EXP_EVAL_VALUES.COMP_ASSIGNMENT_ID.alias('COMP_ASSIGNMENT_ID'), \
	EXP_EVAL_VALUES.REFLECTIVE_CODE.alias('REFLECTIVE_CODE'), \
	EXP_EVAL_VALUES.LOAD_TSTMP.alias('LOAD_TSTMP'), \
	EXP_EVAL_VALUES.UPDATE_TSTMP.alias('UPDATE_TSTMP'), \
	EXP_EVAL_VALUES.in_WM_PERF_SMRY_TRAN_ID.alias('in_WM_PERF_SMRY_TRAN_ID')) 
UPD_VALIDATE = UPD_VALIDATE.withColumn('pyspark_data_action', when((UPD_VALIDATE.in_WM_PERF_SMRY_TRAN_ID.isNull()),(lit(0))).otherwise(lit(1)))
logger.info('UPD_VALIDATE dataframe created successfully')

# COMMAND ----------

Shortcut_to_WM_E_CONSOL_PERF_SMRY = UPD_VALIDATE.select( \
	UPD_VALIDATE.LOCATION_ID.cast(DecimalType(10,0)).alias('LOCATION_ID'), \
	UPD_VALIDATE.PERF_SMRY_TRAN_ID.cast(DecimalType(20,0)).alias('WM_PERF_SMRY_TRAN_ID'), \
	UPD_VALIDATE.WHSE.cast(StringType()).alias('WM_WHSE'), \
	UPD_VALIDATE.LOGIN_USER_ID.cast(StringType()).alias('WM_LOGIN_USER_ID'), \
	UPD_VALIDATE.JOB_FUNCTION_NAME.cast(StringType()).alias('WM_JOB_FUNCTION_NAME'), \
	UPD_VALIDATE.CLOCK_IN_DATE.cast(TimestampType()).alias('CLOCK_IN_TSTMP'), \
	UPD_VALIDATE.CLOCK_OUT_DATE.cast(TimestampType()).alias('CLOCK_OUT_TSTMP'), \
	UPD_VALIDATE.CLOCK_IN_STATUS.cast(DecimalType(3,0)).alias('CLOCK_IN_STATUS'), \
	UPD_VALIDATE.START_DATE_TIME.cast(TimestampType()).alias('START_TSTMP'), \
	UPD_VALIDATE.END_DATE_TIME.cast(TimestampType()).alias('END_TSTMP'), \
	UPD_VALIDATE.WHSE_DATE.cast(TimestampType()).alias('WHSE_TSTMP'), \
	UPD_VALIDATE.TEAM_BEGIN_TIME.cast(TimestampType()).alias('TEAM_BEGIN_TSTMP'), \
	UPD_VALIDATE.SHIFT_CODE.cast(StringType()).alias('WM_SHIFT_CD'), \
	UPD_VALIDATE.REPORT_SHIFT.cast(StringType()).alias('WM_REPORT_SHIFT_CD'), \
	UPD_VALIDATE.USER_ID.cast(StringType()).alias('WM_USER_ID'), \
	UPD_VALIDATE.SPVSR_LOGIN_USER_ID.cast(StringType()).alias('WM_SPVSR_LOGIN_USER_ID'), \
	UPD_VALIDATE.DEPT_CODE.cast(StringType()).alias('WM_DEPT_CD'), \
	UPD_VALIDATE.RESOURCE_GROUP_ID.cast(StringType()).alias('WM_RESOURCE_GROUP_ID'), \
	UPD_VALIDATE.COMP_ASSIGNMENT_ID.cast(StringType()).alias('WM_COMP_ASSIGNMENT_ID'), \
	UPD_VALIDATE.REFLECTIVE_CODE.cast(StringType()).alias('WM_REFLECTIVE_CD'), \
	UPD_VALIDATE.EMP_PERF_SMRY_ID.cast(DecimalType(20,0)).alias('WM_EMP_PERF_SMRY_ID'), \
	UPD_VALIDATE.LOCN_GRP_ATTR.cast(StringType()).alias('WM_LOCN_GRP_ATTR'), \
	UPD_VALIDATE.VERSION_ID.cast(DecimalType(6,0)).alias('WM_VERSION_ID'), \
	UPD_VALIDATE.OPS_CODE.cast(StringType()).alias('WM_OPS_CD'), \
	UPD_VALIDATE.TEAM_CODE.cast(StringType()).alias('WM_TEAM_CD'), \
	UPD_VALIDATE.REF_NBR.cast(StringType()).alias('WM_REF_NBR'), \
	UPD_VALIDATE.DEFAULT_JF_FLAG.cast(DecimalType(9,0)).alias('DEFAULT_JF_FLAG'), \
	UPD_VALIDATE.EVENT_COUNT.cast(DecimalType(9,0)).alias('EVENT_CNT'), \
	UPD_VALIDATE.TOTAL_SAM.cast(DecimalType(20,7)).alias('TOTAL_SAM'), \
	UPD_VALIDATE.TOTAL_PAM.cast(DecimalType(13,5)).alias('TOTAL_PAM'), \
	UPD_VALIDATE.TOTAL_TIME.cast(DecimalType(13,5)).alias('TOTAL_TIME'), \
	UPD_VALIDATE.TOTAL_QTY.cast(DecimalType(13,5)).alias('TOTAL_QTY'), \
	UPD_VALIDATE.OSDL.cast(DecimalType(13,5)).alias('OSDL'), \
	UPD_VALIDATE.OSIL.cast(DecimalType(13,5)).alias('OSIL'), \
	UPD_VALIDATE.NSDL.cast(DecimalType(13,5)).alias('NSDL'), \
	UPD_VALIDATE.SIL.cast(DecimalType(13,5)).alias('SIL'), \
	UPD_VALIDATE.UDIL.cast(DecimalType(13,5)).alias('UDIL'), \
	UPD_VALIDATE.UIL.cast(DecimalType(13,5)).alias('UIL'), \
	UPD_VALIDATE.ADJ_OSDL.cast(DecimalType(13,5)).alias('ADJ_OSDL'), \
	UPD_VALIDATE.ADJ_OSIL.cast(DecimalType(13,5)).alias('ADJ_OSIL'), \
	UPD_VALIDATE.ADJ_UDIL.cast(DecimalType(13,5)).alias('ADJ_UDIL'), \
	UPD_VALIDATE.ADJ_NSDL.cast(DecimalType(13,5)).alias('ADJ_NSDL'), \
	UPD_VALIDATE.PAID_BRK.cast(DecimalType(13,5)).alias('PAID_BRK'), \
	UPD_VALIDATE.UNPAID_BRK.cast(DecimalType(13,5)).alias('UNPAID_BRK'), \
	UPD_VALIDATE.REF_OSDL.cast(DecimalType(13,5)).alias('REF_OSDL'), \
	UPD_VALIDATE.REF_OSIL.cast(DecimalType(13,5)).alias('REF_OSIL'), \
	UPD_VALIDATE.REF_UDIL.cast(DecimalType(13,5)).alias('REF_UDIL'), \
	UPD_VALIDATE.REF_NSDL.cast(DecimalType(13,5)).alias('REF_NSDL'), \
	UPD_VALIDATE.REF_ADJ_OSDL.cast(DecimalType(13,5)).alias('REF_ADJ_OSDL'), \
	UPD_VALIDATE.REF_ADJ_OSIL.cast(DecimalType(13,5)).alias('REF_ADJ_OSIL'), \
	UPD_VALIDATE.REF_ADJ_UDIL.cast(DecimalType(13,5)).alias('REF_ADJ_UDIL'), \
	UPD_VALIDATE.REF_ADJ_NSDL.cast(DecimalType(13,5)).alias('REF_ADJ_NSDL'), \
	UPD_VALIDATE.REF_SAM.cast(DecimalType(13,5)).alias('REF_SAM'), \
	UPD_VALIDATE.REF_PAM.cast(DecimalType(13,5)).alias('REF_PAM'), \
	UPD_VALIDATE.LABOR_COST_RATE.cast(DecimalType(20,7)).alias('LABOR_COST_RATE'), \
	UPD_VALIDATE.THRUPUT_MIN.cast(DecimalType(20,7)).alias('THRUPUT_MIN'), \
	UPD_VALIDATE.PAID_OVERLAP_OSDL.cast(DecimalType(20,7)).alias('PAID_OVERLAP_OSDL'), \
	UPD_VALIDATE.UNPAID_OVERLAP_OSDL.cast(DecimalType(20,7)).alias('UNPAID_OVERLAP_OSDL'), \
	UPD_VALIDATE.PAID_OVERLAP_NSDL.cast(DecimalType(20,7)).alias('PAID_OVERLAP_NSDL'), \
	UPD_VALIDATE.UNPAID_OVERLAP_NSDL.cast(DecimalType(20,7)).alias('UNPAID_OVERLAP_NSDL'), \
	UPD_VALIDATE.PAID_OVERLAP_OSIL.cast(DecimalType(20,7)).alias('PAID_OVERLAP_OSIL'), \
	UPD_VALIDATE.UNPAID_OVERLAP_OSIL.cast(DecimalType(20,7)).alias('UNPAID_OVERLAP_OSIL'), \
	UPD_VALIDATE.PAID_OVERLAP_UDIL.cast(DecimalType(20,7)).alias('PAID_OVERLAP_UDIL'), \
	UPD_VALIDATE.UNPAID_OVERLAP_UDIL.cast(DecimalType(20,7)).alias('UNPAID_OVERLAP_UDIL'), \
	UPD_VALIDATE.DISPLAY_UOM_QTY.cast(DecimalType(20,7)).alias('DISPLAY_UOM_QTY'), \
	UPD_VALIDATE.DISPLAY_UOM.cast(StringType()).alias('DISPLAY_UOM'), \
	UPD_VALIDATE.MISC_1.cast(StringType()).alias('MISC_1'), \
	UPD_VALIDATE.MISC_2.cast(StringType()).alias('MISC_2'), \
	UPD_VALIDATE.MISC_TXT_1.cast(StringType()).alias('MISC_TXT_1'), \
	UPD_VALIDATE.MISC_TXT_2.cast(StringType()).alias('MISC_TXT_2'), \
	UPD_VALIDATE.MISC_NUMBER_1.cast(DecimalType(13,5)).alias('MISC_NBR_1'), \
	UPD_VALIDATE.MISC_NUM_1.cast(DecimalType(20,7)).alias('MISC_NUM_1'), \
	UPD_VALIDATE.MISC_NUM_2.cast(DecimalType(20,7)).alias('MISC_NUM_2'), \
	UPD_VALIDATE.LEVEL_1.cast(StringType()).alias('LEVEL_1'), \
	UPD_VALIDATE.LEVEL_2.cast(StringType()).alias('LEVEL_2'), \
	UPD_VALIDATE.LEVEL_3.cast(StringType()).alias('LEVEL_3'), \
	UPD_VALIDATE.LEVEL_4.cast(StringType()).alias('LEVEL_4'), \
	UPD_VALIDATE.LEVEL_5.cast(StringType()).alias('LEVEL_5'), \
	UPD_VALIDATE.EVNT_CTGRY_1.cast(StringType()).alias('WM_EVNT_CTGRY_1'), \
	UPD_VALIDATE.EVNT_CTGRY_2.cast(StringType()).alias('WM_EVNT_CTGRY_2'), \
	UPD_VALIDATE.EVNT_CTGRY_3.cast(StringType()).alias('WM_EVNT_CTGRY_3'), \
	UPD_VALIDATE.EVNT_CTGRY_4.cast(StringType()).alias('WM_EVNT_CTGRY_4'), \
	UPD_VALIDATE.EVNT_CTGRY_5.cast(StringType()).alias('WM_EVNT_CTGRY_5'), \
	UPD_VALIDATE.CREATE_DATE_TIME.cast(TimestampType()).alias('WM_CREATE_TSTMP'), \
	UPD_VALIDATE.MOD_DATE_TIME.cast(TimestampType()).alias('WM_MOD_TSTMP'), \
	UPD_VALIDATE.UPDATE_TSTMP.cast(TimestampType()).alias('UPDATE_TSTMP'), \
	UPD_VALIDATE.LOAD_TSTMP.cast(TimestampType()).alias('LOAD_TSTMP'), \
	UPD_VALIDATE.pyspark_data_action.alias('pyspark_data_action') \
)


logger.info('Shortcut_to_WM_E_CONSOL_PERF_SMRY dataframe created successfully')

# COMMAND ----------

# MAGIC %run ./utils/mergeUtils

# COMMAND ----------

# MAGIC %run ./utils/logger

# COMMAND ----------

#Final Merge 
try:
    primary_key = "source.LOCATION_ID = target.LOCATION_ID AND source.WM_PERF_SMRY_TRAN_ID = target.WM_PERF_SMRY_TRAN_ID"
    executeMerge(Shortcut_to_WM_E_CONSOL_PERF_SMRY, refined_perf_table, primary_key)
    logger.info(f'Merge with {refined_perf_smry_table} completed]')
    #logPrevRunDt('WM_E_CONSOL_PERF_SMRY','WM_E_CONSOL_PERF_SMRY','Completed','N/A',f"{env}_raw.log_run_details")
except Exception as e:
    logPrevRunDt('WM_E_CONSOL_PERF_SMRY','WM_E_CONSOL_PERF_SMRY','Failed',str(e),f"{env}raw.log_run_details")
    raise e

